Repository kgateway-dev/kgateway, pull requests merged in 2019-12, with the labels that each got.

#1826 Add --release-name flag to install and uninstall commands
  install/helm/gloo/generate/values.go
  projects/gloo/cli/pkg/cmd/install/install_test.go
  projects/gloo/cli/pkg/cmd/install/installer.go
  projects/gloo/cli/pkg/cmd/install/installer_test.go
  projects/gloo/cli/pkg/cmd/install/uninstall.go
  projects/gloo/cli/pkg/cmd/install/uninstall_test.go
  projects/gloo/cli/pkg/cmd/options/options.go
  projects/gloo/cli/pkg/flagutils/install.go
  projects/gloo/cli/pkg/flagutils/uninstall.go
Labels: work in progress

#1837 Fix helm race
  changelog/v1.2.1/make-settings-hook.yaml
  install/helm/gloo/templates/18-settings.yaml
  install/test/helm_test.go
Labels: Area: Helm

#1851 Remove `make clean` invocation from helm tests
  changelog/v1.2.3/remove-make-clean.yaml
  install/test/helm_suite_test.go
Labels: Area: CI

#1886 Report error on empty domain during virtual service validation
  changelog/v1.2.5/empty-domain-validation.yaml
  docs/content/installation/gateway/docker-compose-file/_index.md
  projects/gloo/api/grpc/validation/proxy_validation.proto
  projects/gloo/pkg/api/grpc/validation/proxy_validation.pb.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
Labels: Area: Validation

#1914 Direct response header manipulation
  changelog/v1.2.8/direct-response-header-manipulation.yaml
  go.mod
  go.sum
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
Labels: Area: Envoy, Type: Enhancement

#1936 Fix release manifests
  Makefile
  changelog/v1.2.9/fix-released-gloo-manifests.yaml
  projects/gloo/cli/pkg/cmd/install/installer.go
Labels: Area: CI

#1943 Fix manifest release
  Makefile
  changelog/v1.2.10/fix-manifest-release.yaml
  cloudbuild.yaml
  install/test/helm_suite_test.go
Labels: Area: CI

#1913 1893 - move glooctl version check to individual commands for non-kube…
  changelog/v1.2.10/non-kube-version-check.yaml
  projects/gloo/cli/pkg/cmd/add/root.go
  projects/gloo/cli/pkg/cmd/create/authconfig/authconfig.go
  projects/gloo/cli/pkg/cmd/create/upstream.go
  projects/gloo/cli/pkg/cmd/create/upstreamgroup.go
  projects/gloo/cli/pkg/cmd/create/virtualservice.go
  projects/gloo/cli/pkg/cmd/del/root.go
  projects/gloo/cli/pkg/cmd/edit/root.go
  projects/gloo/cli/pkg/cmd/get/root.go
  projects/gloo/cli/pkg/cmd/remove/root.go
  projects/gloo/cli/pkg/cmd/root.go
  projects/gloo/cli/pkg/cmd/route/root.go
  projects/gloo/cli/pkg/prerun/prerun_consul.go
  projects/gloo/cli/pkg/prerun/version_warning.go
Labels: work in progress

#1971 Fix uninstall command
  changelog/v1.2.11/fix-crd-uninstall.yaml
  projects/gloo/cli/pkg/cmd/debug/debug.go
  projects/gloo/cli/pkg/cmd/debug/debug_test.go
  projects/gloo/cli/pkg/cmd/install/install_suite_test.go
  projects/gloo/cli/pkg/cmd/install/install_test.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/install/uninstall.go
  projects/gloo/cli/pkg/cmd/install/uninstall_test.go
  projects/gloo/cli/pkg/cmd/install/util.go
Labels: Area: glooctl, Type: bug

#1984 Remove --upgrade flag from glooctl install gateway
  changelog/v1.2.11/remove-install-gateway-upgrade.yaml
  docs/content/cli/glooctl_install.md
  docs/content/cli/glooctl_install_gateway.md
  docs/content/cli/glooctl_install_gateway_enterprise.md
  docs/content/cli/glooctl_install_ingress.md
  docs/content/cli/glooctl_install_knative.md
  projects/gloo/cli/pkg/cmd/install/install_test.go
  projects/gloo/cli/pkg/cmd/options/options.go
  projects/gloo/cli/pkg/flagutils/install.go
Labels: Area: glooctl

#2015 Update plugin auth docs
  docs/content/dev/writing_auth_plugins/_index.md
  docs/content/security/auth/custom_auth/gloo-vs.yaml
  docs/content/security/auth/plugin_auth/vs-echo-no-auth.yaml
  docs/content/security/auth/plugin_auth/vs-echo-with-auth.yaml
Labels: Area: Docs
