Repository kgateway-dev/kgateway, pull requests merged in 2020-09, with the labels that each got.

#3584 failover-docs-fixes
  changelog/v1.5.0-beta21/failover-dns-docs.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/failover.proto.sk.md
  projects/gloo/api/v1/failover.proto
  projects/gloo/pkg/api/v1/failover.pb.go
Labels: keep pr updated

#3585 support for query parameter matchers, header matchers, and method matchers to the route table delegation API
  changelog/v1.5.0-beta21/support-delegation-with-advanced-prefix-routes.yaml
  docs/content/guides/traffic_management/destination_types/delegation/_index.md
  projects/gateway/pkg/translator/converter.go
  projects/gateway/pkg/translator/converter_test.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#3583 Custom label comment fixes
  changelog/v1.5.0-beta21/custom-label-comments.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
Labels: keep pr updated

#3580 force reporter to update status
  .githooks/pre-commit
  .githooks/pre-commit-python.py
  changelog/v1.5.0-beta21/gateway-update-status.yaml
  go.mod
  go.sum
  projects/gateway/pkg/propagator/gateway_propagator.go
  projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
  projects/gateway/pkg/syncer/setup_syncer.go
  projects/gateway/pkg/syncer/syncer_suite_test.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_integration_test.go
  projects/gateway/pkg/syncer/translator_syncer_test.go
Labels: keep pr updated

#3596 Githook fix
  .githooks/pre-commit
  .githooks/pre-commit-python.py
  changelog/v1.5.0-beta22/githook-mac-fix.yaml
Labels: keep pr updated

#3599 Update dev portal docs
  changelog/v1.5.0-beta22/update-dev-portal-docs.yaml
  docs/content/guides/dev_portal/_index.md
Labels: keep pr updated

#3601 Remove Developer Portal related code from glooctl
  changelog/v1.5.0-beta22/remove-dev-portal-code.yaml
  projects/gloo/cli/pkg/cmd/install/uninstall.go
  projects/gloo/cli/pkg/cmd/install/uninstall_test.go
  projects/gloo/cli/pkg/cmd/install/util.go
Labels: keep pr updated

#3593 Expose cluster configuration `common_http_protocol_options`
  changelog/v1.5.0-beta21/gateway-update-status.yaml
  changelog/v1.5.0-beta23/upstream-http-protocol-options.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk.md
  projects/gloo/api/v1/connection.proto
  projects/gloo/pkg/api/v1/connection.pb.go
  projects/gloo/pkg/api/v1/connection.pb.hash.go
  projects/gloo/pkg/plugins/upstreamconn/plugin.go
  projects/gloo/pkg/plugins/upstreamconn/plugin_test.go
Labels: keep pr updated

#3546 no duplicate empty sni domains
  changelog/v1.5.0-beta23/conflicting-empty-sni-domains.yaml
  projects/gateway/pkg/translator/http.go
  projects/gateway/pkg/translator/translator_test.go
  projects/gloo/pkg/translator/listener.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#3574 Fix default sds gateway proxy cluster name
  changelog/v1.5.0-beta23/sds-clustername-default.yaml
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/older_istio_versions.md
  docs/content/guides/security/tls/mtls/_index.md
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: keep pr updated

#3612 Extauth tls docs
  changelog/v1.5.0-beta23/extauth-mtls-doc.yaml
  docs/content/guides/security/auth/extauth/_index.md
Labels: keep pr updated

#3611 Istio ux improvements
  .github/workflows/regression-tests-and-codegen.yaml
  changelog/v1.5.0-beta23/istio-ux-improvements.yaml
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/older_istio_versions.md
  docs/content/reference/cli/glooctl.md
  docs/content/reference/cli/glooctl_istio.md
  docs/content/reference/cli/glooctl_istio_enable-mtls.md
  docs/content/reference/cli/glooctl_istio_inject.md
  docs/content/reference/cli/glooctl_istio_uninject.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  install/test/val_custom_istio_sidecar.yaml
  projects/gloo/cli/pkg/cmd/istio/enable_mtls.go
  projects/gloo/cli/pkg/cmd/istio/inject.go
  projects/gloo/cli/pkg/cmd/istio/root.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.6.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/matcher.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/sds.go
  projects/gloo/cli/pkg/cmd/istio/uninject.go
  projects/gloo/cli/pkg/cmd/istio/util.go
  projects/gloo/cli/pkg/cmd/options/options.go
  projects/gloo/cli/pkg/cmd/root.go
  projects/gloo/cli/pkg/constants/commands.go
  projects/gloo/cli/pkg/flagutils/common.go
  test/kube2e/glooctl/glooctl_suite_test.go
  test/kube2e/glooctl/glooctl_test.go
  test/kube2e/glooctl/petstore_peerauth_permissive.yaml
  test/kube2e/glooctl/petstore_peerauth_strict.yaml
Labels: Type: Enhancement, keep pr updated

#3614 Secrets on headers
  changelog/v1.5.0-beta23/secrets-in-headers.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/headers/headers.proto.sk.md
  projects/clusteringress/pkg/translator/translate_test.go
  projects/gloo/api/v1/options/headers/headers.proto
  projects/gloo/pkg/api/v1/options/headers/headers.pb.go
  projects/gloo/pkg/plugins/headers/plugin.go
  projects/gloo/pkg/plugins/headers/plugin_test.go
  projects/knative/pkg/translator/translate.go
  projects/knative/pkg/translator/translate_test.go
Labels: keep pr updated

#3621 Remove dangling ratelimit comments
  changelog/v1.5.0-beta23/remove-dangling-comments.yaml
  install/helm/gloo/values-template.yaml
Labels: keep pr updated

#3632 fix debugf statement in validator
  projects/gateway/pkg/validation/validator.go
Labels: keep pr updated

#3618 Install script pulls latest stable version
  changelog/v1.5.0-beta24/install-script-stable.yaml
  projects/gloo/cli/install.sh
Labels: keep pr updated

#3633 api: waf api to skip body processsing
  changelog/v1.5.0-beta24/waf-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/waf/waf.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/waf/waf.proto.sk.md
  projects/gloo/api/external/envoy/extensions/waf/waf.proto
  projects/gloo/api/v1/enterprise/options/waf/waf.proto
  projects/gloo/pkg/api/external/envoy/extensions/waf/waf.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/waf/waf.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/waf/waf.pb.hash.go
Labels: keep pr updated

#3635 matcher inheritance added to route delegation
  changelog/v1.5.0-beta25/inheritance-delegation.yaml
  docs/content/guides/traffic_management/destination_types/delegation/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
  projects/gateway/api/v1/virtual_service.proto
  projects/gateway/pkg/api/v1/virtual_service.pb.go
  projects/gateway/pkg/api/v1/virtual_service.pb.hash.go
  projects/gateway/pkg/translator/converter.go
  projects/gateway/pkg/translator/converter_test.go
Labels: keep pr updated

#3637 Faster ci
  changelog/v1.5.0-beta25/no-cleanup-gloo-in-ci.yaml
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gloo-mtls/gloo_mtls_suite_test.go
  test/kube2e/helm/helm_suite_test.go
  test/kube2e/ingress/ingress_suite_test.go
  test/kube2e/knative/knative_suite_test.go
  test/kube2e/wasm/wasm_suite_test.go
Labels: keep pr updated

#3642 Fix glooctl istio inject for GlooE
  changelog/v1.5.0-beta25/istio-inject-fix.yaml
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
  projects/gloo/cli/pkg/cmd/istio/util.go
Labels: Type: Bug, keep pr updated

#3644 Generate standard Kubernetes clients for AuthConfigs
  changelog/v1.5.0-beta25/native-authconfig-type.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/solo-kit.json
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_event_loop.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_simple_event_loop.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_snapshot.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_snapshot_simple_emitter.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/apis/enterprise.gloo.solo.io/v1/doc.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/apis/enterprise.gloo.solo.io/v1/register.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/apis/enterprise.gloo.solo.io/v1/types.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/apis/enterprise.gloo.solo.io/v1/zz_generated.deepcopy.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/clientset.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/doc.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/fake/clientset_generated.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/fake/doc.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/fake/register.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/scheme/doc.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/scheme/register.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/typed/enterprise.gloo.solo.io/v1/authconfig.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/typed/enterprise.gloo.solo.io/v1/doc.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/typed/enterprise.gloo.solo.io/v1/enterprise.gloo.solo.io_client.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/typed/enterprise.gloo.solo.io/v1/fake/doc.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/typed/enterprise.gloo.solo.io/v1/fake/fake_authconfig.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/typed/enterprise.gloo.solo.io/v1/fake/fake_enterprise.gloo.solo.io_client.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/clientset/versioned/typed/enterprise.gloo.solo.io/v1/generated_expansion.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/informers/externalversions/enterprise.gloo.solo.io/interface.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/informers/externalversions/enterprise.gloo.solo.io/v1/authconfig.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/informers/externalversions/enterprise.gloo.solo.io/v1/interface.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/informers/externalversions/factory.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/informers/externalversions/generic.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/listers/enterprise.gloo.solo.io/v1/authconfig.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/client/listers/enterprise.gloo.solo.io/v1/expansion_generated.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/hack/update-codegen.sh
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/hack/verify-codegen.sh
Labels: keep pr updated

#3625 Wasm update
  Makefile
  changelog/v1.5.0-beta26/wasm-update.yaml
  docs/content/reference/api/envoy/extensions/wasm/v3/wasm.proto.sk.md
  projects/gloo/api/external/envoy/extensions/wasm/v3/wasm.proto
  projects/gloo/pkg/api/external/envoy/extensions/wasm/v3/wasm.pb.go
  projects/gloo/pkg/plugins/wasm/plugin.go
  projects/gloo/pkg/syncer/setup_syncer.go
  projects/gloo/pkg/translator/translator.go
  test/kube2e/wasm/wasm_test.go
Labels: keep pr updated

#3660 doc fixes and updates
  changelog/v1.5.0-beta26/oauth-doc-update.yaml
  docs/content/guides/security/auth/extauth/oauth/google/_index.md
  docs/content/guides/security/auth/extauth/oauth/google/petclinic-home.png
  docs/content/guides/security/auth/extauth/oauth/google/petclinic-querystring.jpeg
Labels: Type: Docs, keep pr updated

#3667 Fix Istio 1.7.1+ and Istio 1.6.9+
  .github/workflows/regression-tests-and-codegen.yaml
  changelog/v1.5.0-beta26/istio-1-7-1-fix.yaml
  projects/gloo/cli/pkg/cmd/istio/enable_mtls.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.6.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7.go
Labels: Type: Bug, keep pr updated

#3670 Basic ratelimit docs - route-level rate limits
  changelog/v1.5.0-beta26/route-basic-ratelimit-docs.yaml
  docs/content/guides/security/rate_limiting/simple/_index.md
Labels: keep pr updated

#3661 Update from wasme -> wasm/tools/wasme/pkg
  changelog/v1.5.0-beta26/wasme-update.yaml
  docs/content/installation/advanced_configuration/wasm.md
  example/proxycontroller/go.sum
  go.mod
  go.sum
  projects/gloo/pkg/plugins/wasm/mocks/mock_cache.go
  projects/gloo/pkg/plugins/wasm/plugin.go
Labels: keep pr updated

#3676 Extauth boolean expr api
  changelog/v1.5.0-beta27/add-boolean-expr-api-to-extauth.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#3669 make proxy custom resource
  changelog/v1.5.0-beta28/compressed-spec-fix.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_test.go
  projects/gateway/pkg/translator/mocks/mock_translator.go
  projects/gateway/pkg/translator/translator.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/compress/compress.go
  projects/gloo/pkg/api/compress/compress_suite_test.go
  projects/gloo/pkg/api/compress/compress_test.go
  projects/gloo/pkg/api/v1/proxy_extensions.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#3680 handle CVEs CVE-2020-25017 and CVE-2020-25018
  Makefile
  changelog/v1.5.0-beta28/bump-cve.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  example/proxycontroller/go.sum
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#3686 Transformation doc update
  changelog/v1.5.0-beta29/transformation-doc-update.yaml
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
Labels: Type: Docs, keep pr updated

#3690 Change default cluster registration namespace
  changelog/v1.5.0-beta29/cluster-reg-fix.yaml
  docs/content/guides/gloo_federation/cluster_registration.md
  docs/content/reference/cli/glooctl_cluster_deregister.md
  docs/content/reference/cli/glooctl_cluster_register.md
  projects/gloo/cli/pkg/flagutils/cluster.go
Labels: keep pr updated

#3688 Document declarative approach to Istio-Gloo mTLS integration
  changelog/v1.5.0-beta29/declarative-istio-integration.yaml
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
Labels: Type: Docs, keep pr updated

#3692 bump-envoy-v1.16.0-rc4
  Makefile
  changelog/v1.5.0-beta29/bump-envoy-v1.16.0-rc4.yaml
Labels: keep pr updated
