Repository kgateway-dev/kgateway, pull requests merged in 2020-10, with the labels that each got.

#3695 setup changelogs for 1.5 release
  changelog/v1.5.0/1.5-placeholder.yaml
  changelog/v1.5.0/bump-envoy-v1.16.0-rc4.yaml
  changelog/v1.5.0/cluster-reg-fix.yaml
  changelog/v1.5.0/declarative-istio-integration.yaml
  changelog/v1.5.0/transformation-doc-update.yaml
Labels: keep pr updated

#3693 docs for proxy spec compression code
  changelog/v1.5.1/compressed-spec-fix.yaml
  docs/content/operations/advanced/_index.md
  docs/content/operations/advanced/crd_comperssion/_index.md
Labels: keep pr updated

#3697 1.5.1 changelog placeholder
  changelog/v1.5.1/gloo-1.5.1-placeholder.yaml
Labels: keep pr updated

#3696 1.6 beta1 changelog placeholder
  changelog/v1.6.0-beta1/1.6-placeholder.yaml
  changelog/v1.6.0-beta1/compressed-spec-fix.yaml
Labels: keep pr updated

#3701 Fix datadog integration annotation in doc
  docs/content/guides/integrations/datadog/_index.md
Labels: keep pr updated

#3705 Fix misleading message in `glooctl install` output
  changelog/v1.6.0-beta1/fix-glooctl-install-output.yaml
  projects/gloo/cli/pkg/cmd/install/installer.go
Labels: keep pr updated

#3630 Remove duplicate resources in helm charts
  changelog/v1.6.0-beta1/remove-dup-helm-values.yaml
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  pkg/cliutil/helm/hooks.go
  projects/gloo/cli/pkg/cmd/install/installer.go
  projects/gloo/cli/pkg/cmd/install/installer_test.go
  projects/gloo/cli/pkg/constants/constants.go
Labels: keep pr updated

#3712 Remove dup helm values 1.5 backport
  changelog/v1.5.1/remove-dup-helm-values.yaml
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  pkg/cliutil/helm/hooks.go
  projects/gloo/cli/pkg/cmd/install/installer.go
  projects/gloo/cli/pkg/cmd/install/installer_test.go
  projects/gloo/cli/pkg/constants/constants.go
Labels: keep pr updated

#3720 Expose max_connection_duration via Gloo API
  changelog/v1.6.0-beta1/max-connection-duration.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/external/envoy/config/core/v3/protocol.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/protocol.pb.hash.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.hash.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
Labels: Type: Enhancement, keep pr updated

#3723 Update 1.5 upgrade docs
  changelog/v1.6.0-beta1/1.5-docs-update.yaml
  docs/content/operations/upgrading/1.5.0.md
Labels: keep pr updated

#3724 Backport Max duration helm change to 1.5
  changelog/v1.5.1/max-connection-duration.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/external/envoy/config/core/v3/protocol.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/protocol.pb.hash.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.hash.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
Labels: keep pr updated

#3709 Fix example in CORS docs
  docs/content/guides/security/cors/_index.md
Labels: Type: Docs, keep pr updated

#3722 add link to K8 ingress page on the website
  docs/content/guides/integrations/ingress/_index.md
Labels: keep pr updated

#3725 Fix helm chart to honor `.Values.settings.replaceInvalidRoutes` value.
  changelog/v1.6.0-beta1/invalid-rts.yaml
  install/helm/gloo/templates/18-settings.yaml
  install/test/helm_test.go
  test/kube2e/helm/helm_test.go
  test/kube2e/util.go
Labels: keep pr updated

#3727 Fix helm chart to honor `.Values.settings.replaceInvalidRoutes` value
  changelog/v1.5.1/invalid-rts.yaml
  install/helm/gloo/templates/18-settings.yaml
  install/test/helm_test.go
  test/kube2e/helm/helm_test.go
  test/kube2e/util.go
Labels: keep pr updated

#3702 Add an access token guide
  changelog/v1.6.0-beta1/access-token-oauth-doc.yaml
  docs/content/guides/security/auth/extauth/oauth/access_token/_index.md
Labels: Type: Docs, keep pr updated

#3734 Unpin curl
  changelog/v1.6.0-beta2/unpin-curl.yaml
  ci/extended-docker/Dockerfile
Labels: keep pr updated

#3738 Validation proxy toggle
  changelog/v1.6.0-beta3/add-proxy-toggle.yaml
  projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
  projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook_test.go
Labels: keep pr updated

#3666 Add TLS to consul service discovery
  changelog/v1.6.0-beta3/consul-tls-discovery.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/consul/consul.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/test/helm_test.go
  install/test/val_consul_discovery_test_inputs.yaml
  install/test/val_consul_test_inputs.yaml
  projects/gloo/api/v1/options/consul/consul.proto
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/options/consul/consul.pb.go
  projects/gloo/pkg/api/v1/options/consul/consul.pb.hash.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/plugins/consul/eds.go
  projects/gloo/pkg/plugins/consul/plugin.go
  projects/gloo/pkg/plugins/consul/plugin_test.go
  projects/gloo/pkg/plugins/consul/uds.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/upstreams/consul/conversions.go
  projects/gloo/pkg/upstreams/consul/conversions_test.go
  projects/gloo/pkg/upstreams/consul/upstream_client.go
  projects/gloo/pkg/upstreams/consul/upstream_client_test.go
  projects/gloo/pkg/upstreams/consul/watcher.go
  projects/gloo/pkg/upstreams/hybrid_client.go
Labels: keep pr updated

#3742 Oauth2 docs
  changelog/v1.6.0-beta3/oauth2-docs-update.yaml
  docs/content/guides/security/auth/extauth/oauth/dex/_index.md
  docs/content/guides/security/auth/extauth/oauth/google/_index.md
Labels: Type: Docs, keep pr updated

#3743 Custom CA guide
  changelog/v1.6.0-beta3/extauth-ca-doc.yaml
  docs/content/guides/security/auth/extauth/oauth/dex/_index.md
  docs/content/installation/advanced_configuration/extauth_custom_ca.md
Labels: Type: Docs, keep pr updated

#3744 Homebrew update docs
  changelog/v1.6.0-beta3/homebrew-doc-update.yaml
  docs/content/installation/glooctl_setup.md
Labels: Type: Docs, keep pr updated

#3754 Use upstream envoy for wasm instead of envoy-wasm fork
  Makefile
  changelog/v1.6.0-beta3/bump-envoy.yaml
  docs/content/installation/advanced_configuration/wasm.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
  projects/gloo/pkg/plugins/wasm/plugin.go
  projects/gloo/pkg/plugins/wasm/plugin_test.go
  test/kube2e/wasm/wasm_suite_test.go
Labels: keep pr updated

#3746 Validation UX improvements
  changelog/v1.6.0-beta4/validation-ux-improvements.yaml
  projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
  projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook_test.go
  projects/gateway/pkg/validation/fixtures/unmarshal-err.json
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#3756 Validation UX improvements: Gloo 1.5
  changelog/v1.5.2/validation-ux-improvements.yaml
  projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
  projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook_test.go
  projects/gateway/pkg/validation/fixtures/unmarshal-err.json
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#3775 Sessions in redis
  changelog/v1.6.0-beta4/api-oidc-redis.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#3780 use marked docs container
  changelog/v1.6.0-beta4/older-docs-marking.yaml
  docs/docs-staging.yaml
  docs/old-version-marker.sh
Labels: Type: Docs, keep pr updated

#3782 oidc logout api
  changelog/v1.6.0-beta4/api-oidc-logout.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#3777 fix: ssl config parameters are taken to account when merging matching ssl configs
  changelog/v1.6.0-beta4/fix-ssl-params.yaml
  projects/gloo/pkg/translator/listener.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#3784 Fix broken kind links in gloo docs
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/platform_configuration/cluster_setup.md
Labels: keep pr updated

#3786 Fix docs typo in istio mTLS
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
Labels: Type: Docs, keep pr updated

#3779 Set route prefix rewrite to ingress proxy and knative proxy configs
  changelog/v1.6.0-beta5/helm-route-prefix-rewrite-to-ingressproxy-and-knativeproxy.yaml
  install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
  install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
  install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
  install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
  install/test/helm_test.go
Labels: keep pr updated

#3787 fix: ssl config parameters are taken to account when merging matching…
  changelog/v1.5.3/fix-ssl-params.yaml
  projects/gloo/pkg/translator/listener.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#3772 Add sidecar/sds resource config value
  changelog/v1.6.0-beta5/helm-small-container-resources.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#3792 Glooctl check tests
  changelog/v1.6.0-beta6/glooctl-check-tests.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/check/root_test.go
  projects/gloo/cli/pkg/helpers/clients.go
Labels: keep pr updated

#3796 Fix broken AWS load balancer annotations link
  docs/content/guides/integrations/aws/_index.md
Labels: Type: Docs, keep pr updated

#3781 Add link to full regex grammar in regex path matching doc
  docs/content/guides/traffic_management/destination_selection/path_matching/_index.md
Labels: Area: API, Type: Docs, keep pr updated

#3800 Helm resource limits backport
  changelog/v1.5.4/add-helm-resource-limits.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#3773 Return multierror from glooctl check resources
  changelog/v1.6.0-beta6/glooctl-check-multierror.yaml
  go.mod
  go.sum
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/proxy_prom_stats.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/check/root_test.go
  test/kube2e/gloo-mtls/gloo_mtls_suite_test.go
  test/kube2e/util.go
Labels: keep pr updated

#3807 individual sni for static upstreams
  changelog/v1.6.0-beta6/sni-static-upstream.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/static/static.proto.sk.md
  projects/gloo/api/v1/options/static/static.proto
  projects/gloo/pkg/api/v1/options/static/static.pb.go
  projects/gloo/pkg/api/v1/options/static/static.pb.hash.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/plugins/static/plugin.go
  projects/gloo/pkg/plugins/static/plugin_test.go
  projects/gloo/pkg/plugins/upstreamssl/plugin.go
  projects/gloo/pkg/plugins/upstreamssl/plugin_test.go
  projects/gloo/pkg/plugins/upstreamssl/upstream_suite_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator_test.go
  test/e2e/happypath_test.go
  test/v1helpers/ssl_proxy.go
Labels: keep pr updated

#3808 Sni static - backport 1.5
  changelog/v1.5.5/sni-static-upstream.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/static/static.proto.sk.md
  projects/gloo/api/v1/options/static/static.proto
  projects/gloo/pkg/api/v1/options/static/static.pb.go
  projects/gloo/pkg/api/v1/options/static/static.pb.hash.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/plugins/static/plugin.go
  projects/gloo/pkg/plugins/static/plugin_test.go
  projects/gloo/pkg/plugins/upstreamssl/plugin.go
  projects/gloo/pkg/plugins/upstreamssl/plugin_test.go
  projects/gloo/pkg/plugins/upstreamssl/upstream_suite_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator_test.go
  test/e2e/happypath_test.go
  test/v1helpers/ssl_proxy.go
Labels: keep pr updated
