Repository kgateway-dev/kgateway, pull requests merged in 2020-12, with the labels that each got.

#3934 Fix multi proxy status reporting
  changelog/v1.6.0-beta15/fix-multi-proxy-status.yaml
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_test.go
Labels: keep pr updated

#3939 Issue 3839 docs
  changelog/v1.6.0-beta15/update-docker-compose-guides.yaml
  install/docker-compose-consul/docker-compose.yaml
  install/docker-compose-file/docker-compose.yaml
  install/docker-compose-file/prepare-directories.sh
Labels: Type: Docs, keep pr updated

#3929 Add API for OIDC configuration override in ext-auth
  changelog/v1.6.0-beta15/oidc-configuration-override.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#3945 update go utils to 20
  changelog/v1.6.0-beta16/upgrade-go-utils-to-20.yaml
  docs/content/guides/dev/example-proxy-controller.go
  docs/content/reference/api/github.com/solo-io/skv2/api/multicluster/v1alpha1/cluster.proto.sk.md
  docs/data/ProtoMap.yaml
  example/proxycontroller/proxycontroller.go
  go.mod
  go.sum
  install/helm/gloo/generate.go
  install/test/helm_suite_test.go
  install/test/helm_test.go
  install/test/rbac_test.go
  install/test/svc_accnt_test.go
  install/test/util.go
  jobs/pkg/certgen/gen_certs.go
  jobs/pkg/kube/secret_test.go
  pkg/cliutil/nsselect/setup.go
  pkg/cliutil/uri.go
  pkg/utils/gogoutils/routematch.go
  pkg/utils/setuputils/main_setup.go
  projects/accesslogger/pkg/runner/run.go
  projects/clusteringress/pkg/status/status_syncer_test.go
  projects/gateway/pkg/api/v1/kube/generated_kube_suite_test.go
  projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go
  projects/gloo/cli/pkg/cmd/dashboard/root.go
  projects/gloo/cli/pkg/cmd/debug/debug.go
  projects/gloo/cli/pkg/cmd/federation/register/deregister.go
  projects/gloo/cli/pkg/cmd/federation/register/register.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/version/clients.go
  projects/gloo/cli/pkg/helpers/clients.go
  projects/gloo/cli/pkg/helpers/kube.go
  projects/gloo/pkg/bootstrap/utils.go
  projects/gloo/pkg/bootstrap/utils_test.go
  projects/gloo/pkg/plugins/aws/ec2/eds.go
  projects/gloo/pkg/plugins/consul/eds.go
  projects/gloo/pkg/plugins/kubernetes/uds_convert.go
  projects/gloo/pkg/plugins/linkerd/plugin_test.go
  projects/gloo/pkg/plugins/stats/stats.go
  projects/ingress/pkg/api/ingress/resource_client_test.go
  projects/ingress/pkg/api/service/resource_client_test.go
  projects/ingress/pkg/setup/setup_syncer.go
  projects/ingress/pkg/status/status_syncer_test.go
  test/e2e/happypath_test.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/gateway/robustness_test.go
  test/kube2e/gloo-mtls/gloo_mtls_suite_test.go
  test/kube2e/gloo-mtls/gloo_mtls_test.go
  test/kube2e/glooctl/glooctl_suite_test.go
  test/kube2e/glooctl/glooctl_test.go
  test/kube2e/helm/helm_suite_test.go
  test/kube2e/ingress/ingress_suite_test.go
  test/kube2e/ingress/ingress_test.go
  test/kube2e/knative/knative_manual_tls_test.go
  test/kube2e/knative/knative_suite_test.go
  test/kube2e/knative/knative_test.go
  test/kube2e/util.go
  test/kube2e/wasm/wasm_suite_test.go
  test/kube2e/wasm/wasm_test.go
  test/v1helpers/test_grpc_service/testgrpcservice.go
Labels: keep pr updated

#3944 Helm bootstrap config changes (wasm/static clusters)
  Makefile
  changelog/v1.6.0-beta16/envoy-bootstrap-config.yaml
  docs/content/reference/values.txt
  go.mod
  go.sum
  hack/utils/oss_compliance/third_party_licenses.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/fixtures/envoy_config/bootstrap_extensions.yaml
  install/test/fixtures/envoy_config/static_clusters.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  install/test/val_tracing_provider.yaml
  install/test/values/val_access_logger.yaml
  install/test/values/val_consul_discovery_test_inputs.yaml
  install/test/values/val_consul_test_inputs.yaml
  install/test/values/val_custom_bootstrap_extensions.yaml
  install/test/values/val_custom_gateways.yaml
  install/test/values/val_custom_istio_sidecar.yaml
  install/test/values/val_lb_source_ranges.yaml
  install/test/values/val_static_clusters.yaml
  install/test/values/val_tracing_provider_cluster.yaml
  out.yaml
  projects/envoyinit/cmd/utils/utils.go
  projects/envoyinit/pkg/downward/downward.go
  projects/envoyinit/pkg/downward/downward_suite_test.go
  projects/envoyinit/pkg/downward/downward_test.go
  projects/envoyinit/pkg/downward/interface.go
  projects/envoyinit/pkg/downward/template.go
  projects/envoyinit/pkg/downward/template_test.go
  projects/envoyinit/pkg/downward/transform.go
  projects/envoyinit/pkg/downward/transform_test.go
  test/e2e/envoyconfigs/zipkin-envoy-conf.yaml
  test/e2e/envoyconfigs/zipkin-envoy-invalid-conf.yaml
  test/e2e/happypath_test.go
  test/e2e/zipkin_test.go
  test/services/envoy.go
Labels: keep pr updated

#3951 Add Open source release notes to chronological ordering of enterprise changelog
  changelog/v1.6.0-beta17/fix-enterprise-changelog-docs.yaml
  docs/cmd/changelogutils/changelog_utils.go
  docs/cmd/generate_changelog_doc.go
  docs/cmd/test/generate_changelog_doc_test.go
Labels: keep pr updated

#3950 Tracing propagate opts
  changelog/v1.6.0-beta17/tracing-propagate-opts.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/tracing/tracing.proto.sk.md
  projects/gloo/api/v1/options/tracing/tracing.proto
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.hash.go
  projects/gloo/pkg/plugins/tracing/plugin.go
  projects/gloo/pkg/plugins/tracing/plugin_test.go
Labels: keep pr updated

#3957 Prefer specific types in API for OIDC configuration override in ext-auth
  changelog/v1.6.0-beta17/discovery-override-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#3940 fixed extauth proto bug for auth chain boolean expr example
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#3958 Enhance production deployment docs
  changelog/v1.6.0-beta17/enhance-prod-docs.yaml
  docs/content/operations/production_deployment/_index.md
Labels: keep pr updated

#3942 Check Lambda destinations for routes
  changelog/v1.6.0-beta17/lambda-delete-bug-fix.yaml
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#3960 (Backport) Lambda function routing error reporting
  changelog/v1.5.13/lambda-delete-bug-fix.yaml
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#3961 Backport propagate opt
  changelog/v1.5.13/backport-tracing-propagate-opts.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/tracing/tracing.proto.sk.md
  projects/gloo/api/v1/options/tracing/tracing.proto
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.hash.go
  projects/gloo/pkg/plugins/tracing/plugin.go
  projects/gloo/pkg/plugins/tracing/plugin_test.go
Labels: keep pr updated

#3955 Support static tracing cluster
  changelog/v1.6.0-beta17/tracing-static-cluster.yaml
  docs/content/guides/traffic_management/listener_configuration/http_connection_manager.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/trace/v3/datadog.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/trace/v3/zipkin.proto.sk.md
  projects/gloo/api/external/envoy/config/trace/v3/datadog.proto
  projects/gloo/api/external/envoy/config/trace/v3/zipkin.proto
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/zipkin.pb.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/plugins/tracing/plugin.go
  projects/gloo/pkg/plugins/tracing/plugin_test.go
  test/e2e/envoyconfigs/zipkin-envoy-conf.yaml
  test/e2e/envoyconfigs/zipkin-static-cluster.yaml
  test/e2e/zipkin_test.go
  test/services/envoy.go
Labels: keep pr updated

#3963 Fix sed CI flake
  changelog/v1.6.0-beta18/fix-sed-ci.yaml
  ci/kind.sh
Labels: keep pr updated

#3959 Rename istio-pilot to istiod
  changelog/v1.6.0-beta18/rename-istiod.yaml
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/older_istio_versions.md
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/values/val_custom_istio_sidecar.yaml
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.6.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7-1.8.go
Labels: keep pr updated

#3971 add helm value to datadog docs
  docs/content/guides/integrations/datadog/_index.md
Labels: keep pr updated

#3969 Docs CLI
  .github/workflows/regression-tests-and-codegen.yaml
  changelog/v1.6.0-beta18/disable-community-docs-deploy.yaml
Labels: work in progress

#3974 Docs CLI Fix (#3969)
  .github/workflows/regression-tests-and-codegen.yaml
  changelog/v1.6.0-beta18/disable-community-docs-deploy.yaml
Labels: keep pr updated

#3973 proxycontroller example fixes
  .gitignore
  changelog/v1.6.0-beta18/fix-proxycontroller-ex.yaml
  cloudbuild.yaml
  docs/content/guides/dev/example-proxy-controller.md
  example/proxycontroller/go.mod
  example/proxycontroller/proxycontroller.go
Labels: keep pr updated

#3978 Helm extauth
  changelog/v1.6.0-beta18/helm-value-for-settings-extauth.yaml
  go.mod
  go.sum
  install/helm/gloo/templates/18-settings.yaml
  install/test/helm_test.go
Labels: keep pr updated

#3979 Fix lambda route validation bug
  changelog/v1.6.0-beta18/fix-usptream-lambda-destination-validation.yaml
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#3981 (Backport) fix lambda validation
  changelog/v1.5.14/fix-usptream-lambda-destination-validation.yaml
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#3968 extauth refresh api
  changelog/v1.6.0-beta18/refresh-idtoken-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#3885 Fix syncers competing to write proxy status (Gloo Edge Enterprise only)
  changelog/v1.6.0-beta20/proxy-mulit-write-fix.yaml
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
Labels: keep pr updated

#3987 Change default Istio to 1.8.1 for helm istioSDS installs
  changelog/v1.6.0-beta21/istio-1-8-sds-helm.yaml
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#3982 Path case sensitivity opt
  changelog/v1.6.0-beta21/case-sensitivity-path-matcher.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/core/matchers/matchers.proto.sk.md
  projects/gateway/pkg/translator/converter.go
  projects/gateway/pkg/translator/converter_test.go
  projects/gloo/api/v1/core/matchers/matchers.proto
  projects/gloo/pkg/api/v1/core/matchers/matchers.pb.equal.go
  projects/gloo/pkg/api/v1/core/matchers/matchers.pb.go
  projects/gloo/pkg/api/v1/core/matchers/matchers.pb.hash.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#3991 Update oauth example docs
  docs/content/guides/security/auth/extauth/oauth/dex/_index.md
  docs/content/guides/security/auth/extauth/oauth/google/_index.md
Labels: keep pr updated

#3986 fix glooctl demo federation
  changelog/v1.6.0-beta21/fix-glooctl-demo-federation.yaml
  example/proxycontroller/go.sum
  go.mod
  go.sum
  projects/gloo/cli/pkg/cmd/federation/register/deregister.go
  projects/gloo/cli/pkg/cmd/federation/register/register.go
  projects/gloo/cli/pkg/cmd/federation/register/root.go
Labels: keep pr updated

#3990 Support logical jwt auth api
  changelog/v1.6.0-beta21/jwt-extauth-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/jwt/jwt.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/api/v1/enterprise/options/jwt/jwt.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.hash.go
  projects/gloo/pkg/plugins/buffer/plugin_test.go
  projects/gloo/pkg/plugins/extauth/filter.go
  projects/gloo/pkg/plugins/extauth/filter_test.go
  projects/gloo/pkg/plugins/gzip/plugin_test.go
Labels: keep pr updated

#3997 Introduce Pass Through Ext Auth Service API
  changelog/v1.6.0-beta21/pass-through-ext-auth-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#3999 updated comment in proto
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#4005 Goroutine leak
  changelog/v1.6.0-beta22/setup-loop-goroutine-leak.yaml
  go.mod
  go.sum
  projects/clusteringress/pkg/api/external/knative/cluster_ingress_client.sk.go
  projects/gateway/pkg/api/v1/gateway_client.sk.go
  projects/gateway/pkg/api/v1/route_table_client.sk.go
  projects/gateway/pkg/api/v1/virtual_service_client.sk.go
  projects/gloo/pkg/api/external/solo/ratelimit/rate_limit_config_client.sk.go
  projects/gloo/pkg/api/v1/artifact_client.sk.go
  projects/gloo/pkg/api/v1/endpoint_client.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/auth_config_client.sk.go
  projects/gloo/pkg/api/v1/proxy_client.sk.go
  projects/gloo/pkg/api/v1/secret_client.sk.go
  projects/gloo/pkg/api/v1/settings_client.sk.go
  projects/gloo/pkg/api/v1/upstream_client.sk.go
  projects/gloo/pkg/api/v1/upstream_group_client.sk.go
  projects/gloo/pkg/upstreams/hybrid_client.go
  projects/gloo/pkg/upstreams/kubernetes/upstream_client.go
  projects/ingress/pkg/api/v1/ingress_client.sk.go
  projects/ingress/pkg/api/v1/kube_service_client.sk.go
  projects/knative/pkg/api/external/knative/ingress_client.sk.go
Labels: keep pr updated

#4009 Inheritable Matchers improvements
  changelog/v1.6.0-beta22/inheritable-path-matchers.yaml
  changelog/v1.6.0-beta22/setup-loop-goroutine-leak.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
  projects/gateway/api/v1/virtual_service.proto
  projects/gateway/pkg/api/v1/virtual_service.pb.equal.go
  projects/gateway/pkg/api/v1/virtual_service.pb.go
  projects/gateway/pkg/api/v1/virtual_service.pb.hash.go
  projects/gateway/pkg/translator/converter.go
  projects/gateway/pkg/translator/converter_test.go
Labels: keep pr updated

#3977 Csrf filter
  changelog/v1.6.0-beta23/support-csrf-filter.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/filters/http/csrf/v3/csrf.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/external/envoy/extensions/filters/http/csrf/v3/csrf.proto
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/csrf/v3/csrf.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/csrf/v3/csrf.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/csrf/v3/csrf.pb.hash.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/plugins/csrf/csrf_suite_test.go
  projects/gloo/pkg/plugins/csrf/plugin.go
  projects/gloo/pkg/plugins/csrf/plugin_test.go
  projects/gloo/pkg/plugins/registry/registry.go
  test/e2e/csrf_test.go
Labels: keep pr updated

#3998 Add grafana dashboard folder id to upstream proto
  changelog/v1.6.0-beta23/add-folder-id-to-upstream.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  projects/gloo/api/v1/settings.proto
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
Labels: keep pr updated

#4013 Add gatewayProxies.gatewayProxy.readConfigMulticluster helm value
  changelog/v1.6.0-beta24/gateway-proxy-config-dump-service.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/8-gateway-proxy-service.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4015 Fix adding buffer filter
  changelog/v1.6.0-beta24/add-gzip-buffer.yaml
  projects/gloo/pkg/plugins/buffer/plugin.go
  projects/gloo/pkg/plugins/buffer/plugin_test.go
  test/e2e/buffer_test.go
Labels: keep pr updated, work in progress

#4018 Update docs referencing oauth to use oauth2
  docs/content/guides/security/auth/extauth/oauth/_index.md
  docs/content/guides/security/auth/extauth/opa/_index.md
Labels: keep pr updated

#4024 Don't add keep-pr-updated label if community PR
  .github/workflows/add-pr-label.yaml
  changelog/v1.6.0-beta24/disable-community-pr-github-label.yaml
Labels: keep pr updated

#4027 fix shadow translation
  changelog/v1.6.0-beta24/fix-csrf-shadow-enabled.yaml
  projects/gloo/pkg/plugins/csrf/plugin.go
Labels: keep pr updated

#4017 Allow duplicate header transformations api
  Makefile
  changelog/v1.6.0-beta24/duplicate-headers-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.hash.go
  test/e2e/staged_transformation_test.go
Labels: keep pr updated

#4028 Disable rest eds
  changelog/v1.6.0-beta24/disable-rest-eds.yaml
  docs/content/reference/values.txt
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/helm_test.go
  projects/gloo/pkg/xds/utils.go
Labels: keep pr updated

#4026 Update wasm
  .github/workflows/regression-tests-and-codegen.yaml
  changelog/v1.6.0-beta25/wasm-update.yaml
  docs/content/installation/advanced_configuration/wasm.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/wasm/wasm.proto.sk.md
  projects/envoyinit/cmd/Dockerfile.envoywasm
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/wasm/wasm.proto
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options/wasm/wasm.pb.equal.go
  projects/gloo/pkg/api/v1/options/wasm/wasm.pb.go
  projects/gloo/pkg/api/v1/options/wasm/wasm.pb.hash.go
  projects/gloo/pkg/plugins/plugin_interface.go
  projects/gloo/pkg/plugins/wasm/plugin.go
  projects/gloo/pkg/plugins/wasm/plugin_test.go
  projects/gloo/pkg/syncer/setup_syncer.go
  test/kube2e/wasm/wasm_suite_test.go
  test/kube2e/wasm/wasm_test.go
Labels: keep pr updated

#4021 Gzip to compressor filter
  changelog/v1.6.0-beta26/gzip-to-compressor.yaml
  projects/gloo/pkg/plugins/gzip/plugin.go
  projects/gloo/pkg/plugins/gzip/plugin_test.go
  test/e2e/gzip_test.go
Labels: keep pr updated

#4036 glooctl uninstall removes ratelimitconfig crd
  changelog/v1.6.0-beta26/fix-uninstall-ratelimit.yaml
  projects/gloo/cli/pkg/cmd/install/install_suite_test.go
  projects/gloo/cli/pkg/cmd/install/util.go
Labels: keep pr updated

#4040 Docs header secret
  changelog/v1.6.0-beta26/docs-header-secret.yaml
  docs/content/guides/traffic_management/request_processing/append_remove_headers/_index.md
Labels: Type: Docs, keep pr updated

#4035 report invalid namespaces
  changelog/v1.6.0-beta26/report-invalid-namespaces.yaml
  projects/gloo/pkg/plugins/kubernetes/plugin.go
  projects/gloo/pkg/plugins/kubernetes/plugin_test.go
  projects/gloo/pkg/plugins/kubernetes/uds.go
Labels: keep pr updated

#4032 Improve warning reporting on short-circuited routes
  changelog/v1.6.0-beta26/flag-warning-routes.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  projects/gateway/pkg/syncer/setup_syncer.go
  projects/gateway/pkg/translator/http.go
  projects/gateway/pkg/translator/opts.go
  projects/gateway/pkg/translator/translator.go
  projects/gateway/pkg/translator/translator_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/utils/sort_routes.go
Labels: keep pr updated

#4041 Bump envoy dependency to pickup WASM singleton bug fix; update changelogs for 1.6.0 release
  Makefile
  changelog/v1.6.0/bump-envoy-gloo.yaml
  changelog/v1.6.0/docs-header-secret.yaml
  changelog/v1.6.0/fix-uninstall-ratelimit.yaml
  changelog/v1.6.0/flag-warning-routes.yaml
  changelog/v1.6.0/gzip-to-compressor.yaml
  changelog/v1.6.0/report-invalid-namespaces.yaml
  install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
  install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
  install/helm/gloo/templates/19-gloo-mtls-configmap.yaml
  install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
  install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/fixtures.go
  install/test/fixtures/envoy_config/bootstrap_extensions.yaml
  install/test/fixtures/envoy_config/static_clusters.yaml
  out.yaml
  test/e2e/envoyconfigs/zipkin-envoy-conf.yaml
  test/e2e/envoyconfigs/zipkin-static-cluster.yaml
  test/services/envoy.go
Labels: keep pr updated

#4046 Placeholder changelog
  changelog/v1.7.0-beta1/placeholder.yaml
Labels: keep pr updated

#4045 Placeholder changelog
  changelog/v1.6.1/placeholder.yaml
Labels: keep pr updated

#4048 Update docs for 1.6 release
  changelog/v1.7.0-beta1/update-docs.yaml
  docs/active_versions.json
Labels: keep pr updated

#4049 Update docs
  docs/active_versions.json
Labels: keep pr updated
