Repository kgateway-dev/kgateway, pull requests merged in 2020-08, with the labels that each got.

#3550 fix deployment_arch doc broken link and typo
  docs/content/introduction/architecture/deployment_arch.md
Labels: Type: Docs

#3552 fixed listener config code blocks to clarify and fix copy-paste errors
  docs/content/guides/traffic_management/listener_configuration/_index.md
Labels: Type: Docs

#3563 Enable bulldozer keep pr updated
  .github/workflows/add-pr-label.yaml
  changelog/v1.5.0-beta21/add-pr-label-adder.yaml
Labels: keep pr updated

#3562 Prometheus stat for valid config
  changelog/v1.5.0-beta21/prom-stat-valid-config.yaml
  docs/content/guides/traffic_management/configuration_validation/_index.md
  pkg/utils/statsutils.go
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#3541 Pull in envoy/go-control-plane types so that we can deserialize
  changelog/v1.5.0-beta21/opentrace-fix.yaml
  projects/envoyinit/cmd/main.go
  projects/envoyinit/cmd/utils/filter_types.gen.go
  projects/envoyinit/cmd/utils/filter_types.go
  projects/envoyinit/cmd/utils/utils.go
  test/e2e/envoyconfigs/zipkin-envoy-conf.yaml
  test/e2e/envoyconfigs/zipkin-envoy-invalid-conf.yaml
  test/e2e/zipkin_test.go
  test/services/envoy.go
Labels: Type: Bug, keep pr updated

#3571 fix aws sts test
  test/e2e/aws_test.go
Labels: keep pr updated

#3556 Add Kind to cluster setup docs for Gloo
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/platform_configuration/cluster_setup.md
Labels: keep pr updated

#3569 Jwt v2
  .githooks/pre-commit
  .githooks/pre-commit-python.py
  changelog/v1.5.0-beta21/revise-jwt-githook.yaml
Labels: keep pr updated
