Repository kgateway-dev/kgateway, pull requests merged in 2021-12, with the labels that each got.

#5632 HybridListener translation
  projects/gloo/pkg/translator/filter_chain.go
  projects/gloo/pkg/translator/listener_subsystem.go
  projects/gloo/pkg/translator/names.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/utils/names.go
  projects/gloo/pkg/utils/validation/proxy_validation.go
  projects/gloo/pkg/utils/validation/proxy_validation_test.go
  test/e2e/hybrid_test.go
Labels: keep pr updated

#5652 Backport change to use faster hashes for routes
  changelog/v1.9.4/faster-hashes.yaml
  go.mod
  go.sum
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer_test.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#5656 Doc revisions to OPA page
  changelog/v1.10.0-beta11/docs-opa-script.yaml
  docs/content/guides/security/opa/_index.md
  docs/content/guides/security/opa/setup.sh
Labels: keep pr updated

#5664 Support disabling UDS (1.9.x backport)
  changelog/v1.9.5/disable-uds.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures/settings/uds_disabled.yaml
  install/test/helm_test.go
  projects/discovery/pkg/fds/syncer/discovery_syncer_test.go
  projects/discovery/pkg/fds/syncer/setup_syncer.go
  projects/discovery/pkg/syncer/utils.go
  projects/discovery/pkg/syncer/utils_suite_test.go
  projects/discovery/pkg/syncer/utils_test.go
  projects/discovery/pkg/uds/syncer/setup_syncer.go
  projects/discovery/pkg/uds/syncer/setup_syncer_test.go
  projects/discovery/pkg/uds/syncer/syncer_suite_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
Labels: keep pr updated

#5667 Doc bump to match latest version
  changelog/v1.10.0-beta11/docs-version-bump.yaml
  docs/active_versions.json
  docs/content/installation/enterprise/_index.md
  docs/content/installation/glooctl_setup.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/static/content/gee_version_latest.md
  docs/content/static/content/geoss_version_latest.md
  docs/content/static/content/geoss_version_n-1.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#5681 Docs: Update patch for custom CA w ExtAuth
  changelog/v1.9.6/docs-extauth-customca.yaml
  docs/content/installation/advanced_configuration/extauth_custom_ca.md
Labels: keep pr updated

#5668 Fix for rejected RT preventing updates for other RTs
  .gitignore
  changelog/v1.10.0-beta11/rt-route-replacement.yaml
  projects/gateway/pkg/translator/converter.go
  projects/gateway/pkg/translator/converter_test.go
  projects/gateway/pkg/translator/http.go
  projects/gateway/pkg/translator/merge_options.go
  projects/gateway/pkg/translator/merge_options_test.go
  projects/gateway/pkg/translator/translator.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#5684 Fix for rejected RT preventing updates [1.9]
  .gitignore
  changelog/v1.9.6/route-table-selector-validation.yaml
  projects/gateway/pkg/translator/converter.go
  projects/gateway/pkg/translator/converter_test.go
  projects/gateway/pkg/translator/http.go
  projects/gateway/pkg/translator/merge_options.go
  projects/gateway/pkg/translator/merge_options_test.go
  projects/gateway/pkg/translator/translator.go
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
  test/kube2e/gateway/gateway_test.go
  test/samples/route_tables.go
  test/samples/sample_gloo_api_snapshot.go
Labels: keep pr updated

#5685 Fix for rejected RT preventing updates [1.8]
  .gitignore
  changelog/v1.8.24/route-table-selector-validation.yaml
  projects/gateway/pkg/translator/converter.go
  projects/gateway/pkg/translator/converter_test.go
  projects/gateway/pkg/translator/http.go
  projects/gateway/pkg/translator/merge_options.go
  projects/gateway/pkg/translator/merge_options_test.go
  projects/gateway/pkg/translator/translator.go
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
  test/kube2e/gateway/gateway_test.go
  test/samples/route_tables.go
  test/samples/sample_gloo_api_snapshot.go
Labels: keep pr updated

#5686 Fix for rejected RT preventing updates [1.7]
  .gitignore
  changelog/v1.7.24/route-table-selector-validation.yaml
  projects/gateway/pkg/translator/converter.go
  projects/gateway/pkg/translator/converter_test.go
  projects/gateway/pkg/translator/merge_route_options.go
  projects/gateway/pkg/translator/merge_route_options_test.go
  projects/gateway/pkg/translator/translator.go
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
  test/kube2e/gateway/gateway_test.go
  test/samples/route_tables.go
  test/samples/sample_gloo_api_snapshot.go
Labels: keep pr updated

#5691 Add pre_expiry_buffer to extauth API (1.9.x backport)
  changelog/v1.9.6/pre-expiry-buffer.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#5676 Hybrid Gateway guide
  docs/content/guides/traffic_management/listener_configuration/hybrid_gateway.md
Labels: keep pr updated

#5705 fix obsolete modsec link in waf doc
  docs/content/guides/security/waf/_index.md
Labels: Type: Docs, keep pr updated

#5709 Deprecate Gloo Edge Knative Ingress
  changelog/v1.10.0-beta12/deprecate-knative.yaml
  docs/content/guides/integrations/knative/getting_started.md
  docs/content/installation/knative/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/version/version.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/cli/glooctl_install.md
  docs/content/reference/cli/glooctl_install_knative.md
  projects/gloo/api/grpc/version/version.proto
  projects/gloo/api/v1/settings.proto
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/pkg/api/grpc/version/version.pb.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/knative/README.md
Labels: keep pr updated

#5702 build(k8s.io/*): upgraded k8s libraries to v0.22.4
  .github/workflows/regression-tests.yaml
  changelog/v1.10.0-beta12/5543-k8s-upgrades.yaml
  docs/content/reference/values.txt
  docs/content/static/content/osa_included.md
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  projects/clusteringress/pkg/translator/translate_test.go
  projects/knative/api/external/knative/ingress.go
  projects/knative/pkg/translator/translate.go
  projects/knative/pkg/translator/translate_test.go
  projects/knative/pkg/translator/translator_syncer_test.go
  test/mocks/kubernetes/kubeinterface.go
Labels: keep pr updated

#5724 Glooctl check eventually healthy gives more descriptive error
  test/kube2e/gloo-mtls/gloo_mtls_suite_test.go
  test/kube2e/util.go
Labels: keep pr updated

#5729 api: Http only cookie setting
  changelog/v1.10.0-beta13/httponly_api.yaml
  ci/tools.go
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  go.sum
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#5732 makefile: Bump envoy-gloo version to latest 1.19
  Makefile
  changelog/v1.10.0-beta14/bump-envoy.yaml
Labels: keep pr updated

#5704 Resolver API Refactor (Part 1) - Make resolvers easier to write
  changelog/v1.10.0-beta14/new-resolver-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.hash.go
Labels: keep pr updated

#5723 Add preserve IP to gcp docs
  changelog/v1.10.0-rc1/docs-gcp-improvements.yaml
  docs/content/guides/integrations/google_cloud/_index.md
Labels: keep pr updated

#5715 Add new setting to enable regex oauth callbackpaths
  changelog/v1.10.0-rc2/regex-oauth-callback-path.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#5734 external/envoy/extensions/aws: Update aws proto + gen
  changelog/v1.10.0-rc2/aws-lambda-helm-expose.yaml
  docs/content/guides/security/access_logging/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/aws/filter.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  projects/gloo/api/external/envoy/extensions/aws/filter.proto
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.hash.go
Labels: keep pr updated

#5701 update envoy 1.20
  Makefile
  changelog/v1.10.0-rc3/update-envoy.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto.sk.md
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
  projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation_ee/transformation.pb.go
  test/services/envoy.go
Labels: keep pr updated

#5735 Graphql - Using directives to attach resolver defs to fields
  changelog/v1.11.0-beta1/new-resolver-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.hash.go
Labels: work in progress, keep pr updated

#5738 Adding exauth grpc
  changelog/v1.11.0-beta2/adding_extauth_grpc.yaml
  docs/content/guides/dev/example-proxy-controller.go
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  example/proxycontroller/proxycontroller.go
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
  projects/gloo/pkg/bootstrap/bootstrap_validation.go
  projects/gloo/pkg/plugins/cors/route_plugin_test.go
  projects/gloo/pkg/plugins/cors/vhost_plugin_test.go
  projects/gloo/pkg/plugins/extauth/config_generator.go
  projects/gloo/pkg/plugins/extauth/config_generator_test.go
  projects/gloo/pkg/plugins/gzip/plugin_test.go
  projects/gloo/pkg/plugins/kubernetes/uds_convert_test.go
  projects/gloo/pkg/plugins/pluginutils/cluster_extensions_test.go
  projects/gloo/pkg/plugins/rest/plugin_test.go
  projects/gloo/pkg/plugins/static/plugin_test.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer_test.go
  projects/gloo/pkg/utils/any_test.go
Labels: keep pr updated

#5739 Add new setting to enable regex oauth callbackpaths in OidcAuthorizationCode
  changelog/v1.10.0-rc4/regex-oauth-callback-path-redux.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#5740 Add new setting to enable regex oauth callbackpaths in OidcAuthorizationCode
  changelog/v1.11.0-beta2/regex-oauth-callback-path-redux.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#5725 Update all apis to v1
  .github/workflows/regression-tests.yaml
  changelog/v1.11.0-beta2/update-ci-dependencies.yaml
  ci/deploy-to-kind-cluster.sh
  cloudbuild.yaml
  docs/content/guides/integrations/ingress/_index.md
  docs/content/installation/_index.md
  docs/content/installation/platform_configuration/cluster_setup.md
  go.mod
  go.sum
  hack/test.sh
  install/helm/gloo/templates/21-namespace-clusterrole-ingress.yaml
  jobs/pkg/kube/validating_webhook_configuration.go
  jobs/pkg/kube/validating_webhook_configuration_test.go
  out.yaml
  projects/clusteringress/pkg/status/status_syncer_suite_test.go
  projects/clusteringress/pkg/status/status_syncer_test.go
  projects/gateway/pkg/validation/notification_channel.go
  projects/gloo/cli/pkg/cmd/demo/federation.go
  projects/gloo/cli/pkg/cmd/install/knative_test.go
  projects/gloo/cli/pkg/cmd/install/knative_test_yaml.yaml
  projects/ingress/pkg/api/ingress/ingress_suite_test.go
  projects/ingress/pkg/api/ingress/resource_client.go
  projects/ingress/pkg/api/ingress/resource_client_test.go
  projects/ingress/pkg/status/status_suite_test.go
  projects/ingress/pkg/status/status_syncer_test.go
  projects/ingress/pkg/translator/translate.go
  projects/ingress/pkg/translator/translate_test.go
  test/kube2e/README.md
  test/kube2e/eds/eds_test.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/gateway/robustness_test.go
  test/kube2e/gloo-mtls/gloo_mtls_test.go
  test/kube2e/helm/helm_suite_test.go
  test/kube2e/helm/helm_test.go
  test/kube2e/ingress/ingress_test.go
  test/kube2e/ingress/resource_client_test.go
  test/kube2e/ingress/status_syncer_test.go
  test/kube2e/knative/knative_suite_test.go
  test/kube2e/util.go
Labels: keep pr updated

#5745 Remove required from GraphQL dataplane API
  changelog/v1.11.0-beta2/remove-required-gql-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/graphql/graphql.proto.sk.md
  projects/gloo/api/external/envoy/extensions/graphql/graphql.proto
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/graphql/v2/graphql.pb.go
Labels: keep pr updated

#5744 Remove EDS Test Suite
  .github/workflows/regression-tests.yaml
  changelog/v1.11.0-beta2/remove-eds-regression-tests.yaml
  ci/deploy-to-kind-cluster.sh
  test/kube2e/README.md
  test/kube2e/eds/eds_suite_test.go
  test/kube2e/eds/eds_test.go
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#5733 Docs/multi extauth
  changelog/v1.11.0-beta3/docs-multiauth.yaml
  docs/content/guides/security/auth/multi_authz/_index.md
  docs/content/guides/security/auth/multi_authz/authconfig-oidc-and-passthrough.png
  docs/content/guides/security/auth/multi_authz/namedextauth-use-case.png
  docs/content/guides/security/auth/multi_authz/two-options-external-authz-service.png
Labels: keep pr updated

#5748 add license key to gloo and discovery deployments
  changelog/v1.11.0-beta3/add-license-env-var.yaml
  docs/content/operations/upgrading/1.10.0.md
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
Labels: keep pr updated
