Repository kgateway-dev/kgateway, pull requests merged in 2021-01, with the labels that each got.

#4054 Update docs
  docs/content/guides/gloo_federation/federated_configuration.md
  docs/content/guides/gloo_federation/service_failover.md
Labels: keep pr updated

#4056 Update glooctl docs for upgrades
  changelog/v1.7.0-beta1/document-glooctl-upgrade.yaml
  docs/content/installation/glooctl_setup.md
Labels: keep pr updated

#4060 Support Locality Weighted Load Balancing
  changelog/v1.7.0-beta1/docs-and-locality-lb.yaml
  docs/content/guides/traffic_management/listener_configuration/http_connection_manager.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/failover.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/load_balancer.proto.sk.md
  projects/gloo/api/v1/failover.proto
  projects/gloo/api/v1/load_balancer.proto
  projects/gloo/pkg/api/v1/failover.pb.go
  projects/gloo/pkg/api/v1/load_balancer.pb.equal.go
  projects/gloo/pkg/api/v1/load_balancer.pb.go
  projects/gloo/pkg/api/v1/load_balancer.pb.hash.go
  projects/gloo/pkg/plugins/loadbalancer/plugin.go
  projects/gloo/pkg/plugins/loadbalancer/plugin_test.go
Labels: keep pr updated

#4061 Add CSRF guide to security docs
  docs/content/guides/security/auth/extauth/oauth/okta/_index.md
  docs/content/guides/security/csrf/_index.md
Labels: Type: Docs, keep pr updated

#4065 Patch broken CSRF internal doc link
  docs/content/guides/security/csrf/_index.md
Labels: keep pr updated

#4064 Backport Locality Weighted Load Balancing
  changelog/v1.6.1/docs-and-locality-lb.yaml
  docs/content/guides/traffic_management/listener_configuration/http_connection_manager.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/failover.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/load_balancer.proto.sk.md
  projects/gloo/api/v1/failover.proto
  projects/gloo/api/v1/load_balancer.proto
  projects/gloo/pkg/api/v1/failover.pb.go
  projects/gloo/pkg/api/v1/load_balancer.pb.equal.go
  projects/gloo/pkg/api/v1/load_balancer.pb.go
  projects/gloo/pkg/api/v1/load_balancer.pb.hash.go
  projects/gloo/pkg/plugins/loadbalancer/plugin.go
  projects/gloo/pkg/plugins/loadbalancer/plugin_test.go
Labels: keep pr updated

#4067 Update docs to use newer example filter
  docs/content/installation/advanced_configuration/wasm.md
Labels: Type: Docs, keep pr updated

#4066 Additional route short-circuiting validation
  changelog/v1.7.0-beta2/additional-short-circuiting-validation.yaml
  projects/gateway/pkg/translator/http.go
  projects/gateway/pkg/translator/translator_test.go
Labels: keep pr updated

#4070 Additional route short-circuiting validation (#4066)
  changelog/v1.7.0-beta2/additional-short-circuiting-validation.yaml
  projects/gateway/pkg/translator/http.go
  projects/gateway/pkg/translator/translator_test.go
Labels: keep pr updated

#4058 Fix switching from enabled mode to shadow mode in csrf filter
  changelog/v1.7.0-beta2/fix-csrf-enabled.yaml
  projects/gloo/pkg/plugins/csrf/plugin.go
  projects/gloo/pkg/plugins/csrf/plugin_test.go
  test/e2e/csrf_test.go
Labels: keep pr updated

#4074 Support Envoys PackAsBytes for custom auth server
  changelog/v1.6.1/additional-short-circuiting-validation.yaml
  changelog/v1.6.1/envoy-packasbytes.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
  projects/gloo/pkg/plugins/extauth/filter.go
  projects/gloo/pkg/plugins/extauth/filter_test.go
Labels: keep pr updated

#4076 Fix switching from enabled mode to shadow mode in csrf filter (#4058)
  changelog/v1.6.2/additional-short-circuiting-validation.yaml
  changelog/v1.6.2/envoy-packasbytes.yaml
  changelog/v1.6.2/fix-csrf-enabled.yaml
  projects/gloo/pkg/plugins/csrf/plugin.go
  projects/gloo/pkg/plugins/csrf/plugin_test.go
  test/e2e/csrf_test.go
Labels: keep pr updated

#4075 Add Istio discovery config to helm
  changelog/v1.7.0-beta3/istio-discovery.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/0-namespace.yaml
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/10-ingress-deployment.yaml
  install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
  install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
  install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
  install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/helm/gloo/templates/5-gateway-deployment.yaml
  install/helm/gloo/templates/6-access-logger-deployment.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4087 More efficient upstream to endpoint computation
  changelog/v1.7.0-beta4/more-efficient-cluster-computation.yaml
  go.mod
  go.sum
  install/test/helm_test.go
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/endpoints.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/upstreams/consul/conversions_test.go
Labels: keep pr updated

#4088 Faster snapshot hashing
  changelog/v1.7.0-beta5/faster-snapshot-hashing.yaml
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/translator_test.go
  test/benchmark/snapshot_benchmark_test.go
Labels: keep pr updated

#4099 Backport 1.6
  changelog/v1.6.3/cpu-and-validation-fixes.yaml
  docs/content/guides/security/auth/extauth/oauth/okta/_index.md
  docs/content/guides/security/csrf/_index.md
  docs/content/installation/advanced_configuration/wasm.md
  go.mod
  go.sum
  install/test/helm_test.go
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/endpoints.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/upstreams/consul/conversions_test.go
  test/benchmark/snapshot_benchmark_test.go
Labels: keep pr updated

#4101 fix changelog dir
  changelog/v1.7.0-beta6/staged-jwt-api.yaml
Labels: keep pr updated

#4103 Docs build validate latest
  changelog/v1.7.0-beta7/validate-latest-docs-version.yaml
  docs/build-docs.sh
Labels: keep pr updated

#4105 Add gateway-proxy-specific services
  changelog/v1.7.0-beta7/proxy-specific-config-dump-services.yaml
  install/helm/gloo/templates/8-gateway-proxy-service.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4104 removed duplicate route_components.proto
  changelog/v1.7.0-beta7/remove-duplicate-route-components-proto.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/core/v3/route_components.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/route/v3/route_components.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/filters/http/jwt_authn/v3/config.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  projects/gloo/api/external/envoy/config/core/v3/route_components.pb.go
  projects/gloo/api/external/envoy/config/core/v3/route_components.proto
Labels: keep pr updated

#4113 Consul timer leak
  changelog/v1.7.0-beta7/fix-leak-timer.yaml
  projects/gloo/pkg/plugins/consul/eds.go
Labels: keep pr updated

#4116 Update hugo theme to fix docs search bug
  docs/Makefile
Labels: keep pr updated

#4117 Update hugo theme backport to 1.6
  docs/Makefile
Labels: keep pr updated

#4118 Update hugo docs theme 1.5
  changelog/v1.6.0-beta18/fix-usptream-lambda-destination-validation.yaml
  docs/Makefile
Labels: keep pr updated

#4122 Remove accidental changelog
  changelog/v1.6.0-beta18/fix-usptream-lambda-destination-validation.yaml
Labels: keep pr updated

#4052 Add enterprise-only feature warning
  changelog/v1.7.0-beta7/enterprise-only-feature-warning.yaml
  projects/discovery/pkg/fds/setup/setup.go
  projects/discovery/pkg/uds/setup/setup.go
  projects/gloo/pkg/plugins/dlp/dlp_suite_test.go
  projects/gloo/pkg/plugins/dlp/plugin.go
  projects/gloo/pkg/plugins/dlp/plugin_test.go
  projects/gloo/pkg/plugins/failover/failover_suite_test.go
  projects/gloo/pkg/plugins/failover/plugin.go
  projects/gloo/pkg/plugins/failover/plugin_test.go
  projects/gloo/pkg/plugins/http_path/http_path_suite_test.go
  projects/gloo/pkg/plugins/http_path/plugin.go
  projects/gloo/pkg/plugins/http_path/plugin_test.go
  projects/gloo/pkg/plugins/jwt/jwt_suite_test.go
  projects/gloo/pkg/plugins/jwt/plugin.go
  projects/gloo/pkg/plugins/jwt/plugin_test.go
  projects/gloo/pkg/plugins/proxylatency/plugin.go
  projects/gloo/pkg/plugins/proxylatency/plugin_test.go
  projects/gloo/pkg/plugins/proxylatency/proxylatency_suite_test.go
  projects/gloo/pkg/plugins/rbac/plugin.go
  projects/gloo/pkg/plugins/rbac/plugin_test.go
  projects/gloo/pkg/plugins/rbac/rbac_suite_test.go
  projects/gloo/pkg/plugins/sanitize_cluster_header/plugin.go
  projects/gloo/pkg/plugins/sanitize_cluster_header/plugin_test.go
  projects/gloo/pkg/plugins/sanitize_cluster_header/sanitize_cluster_header_suite_test.go
  projects/gloo/pkg/plugins/waf/plugin.go
  projects/gloo/pkg/plugins/waf/plugin_test.go
  projects/gloo/pkg/plugins/waf/waf_suite_test.go
  projects/gloo/pkg/plugins/wasm/plugin.go
  projects/gloo/pkg/setup/setup.go
  projects/gloo/pkg/syncer/extauth/extauth_suite_test.go
  projects/gloo/pkg/syncer/extauth/extauth_translator_syncer.go
  projects/gloo/pkg/syncer/extauth/extauth_translator_syncer_test.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_suite_test.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/setup/setup_syncer_test.go
  projects/gloo/pkg/syncer/syncer_test_helper.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  test/services/gateway.go
Labels: keep pr updated

#4111 Remove old gloo portal guide
  docs/content/guides/dev_portal/_index.md
  docs/content/guides/dev_portal/api_reference/_index.md
  docs/content/guides/dev_portal/api_reference/access_level.md
  docs/content/guides/dev_portal/api_reference/apidoc.md
  docs/content/guides/dev_portal/api_reference/common.md
  docs/content/guides/dev_portal/api_reference/group.md
  docs/content/guides/dev_portal/api_reference/portal.md
  docs/content/guides/dev_portal/api_reference/user.md
  docs/content/guides/dev_portal/img/api-1.png
  docs/content/guides/dev_portal/img/api-2-editor.png
  docs/content/guides/dev_portal/img/dev-portal-empty-landing.png
  docs/content/guides/dev_portal/img/group-1.png
  docs/content/guides/dev_portal/img/key-scope-1.png
  docs/content/guides/dev_portal/img/key-scope-2.png
  docs/content/guides/dev_portal/img/password-change.png
  docs/content/guides/dev_portal/img/portal-api-1.png
  docs/content/guides/dev_portal/img/portal-api-2.png
  docs/content/guides/dev_portal/img/portal-api-3-no-auth-ok.png
  docs/content/guides/dev_portal/img/portal-api-4-no-auth-ko.png
  docs/content/guides/dev_portal/img/portal-api-5-auth-dialog.png
  docs/content/guides/dev_portal/img/portal-api-6-auth-ok.png
  docs/content/guides/dev_portal/img/portal-details-1.png
  docs/content/guides/dev_portal/img/portal-home-1.png
  docs/content/guides/dev_portal/img/portal-key-scopes-1.png
  docs/content/guides/dev_portal/img/portal-key-scopes-2.png
  docs/content/guides/dev_portal/img/portal-wizard-1.png
  docs/content/guides/dev_portal/img/static-page-1.png
  docs/content/guides/dev_portal/img/static-page-2.png
  docs/content/guides/dev_portal/img/static-page-3.png
  docs/content/guides/dev_portal/img/ui-landing-page.png
  docs/content/guides/dev_portal/img/user-1.png
  docs/content/guides/dev_portal/specs/gloo-resources.yaml
  docs/content/guides/dev_portal/specs/petstore-secure.json
  docs/content/guides/dev_portal/specs/petstore.json
Labels: keep pr updated

#4097 Add glooctl get ratelimitconfigs
  changelog/v1.7.0-beta7/cli-get-ratelimitconfigs.yaml
  docs/content/guides/gloo_federation/cluster_registration.md
  docs/content/reference/cli/glooctl_get.md
  docs/content/reference/cli/glooctl_get_ratelimitconfig.md
  projects/gloo/cli/pkg/cmd/get/authconfig.go
  projects/gloo/cli/pkg/cmd/get/ratelimitconfig.go
  projects/gloo/cli/pkg/cmd/get/root.go
  projects/gloo/cli/pkg/common/get.go
  projects/gloo/cli/pkg/constants/commands.go
  projects/gloo/cli/pkg/printers/ratelimitconfig.go
Labels: keep pr updated

#4080 Fix proto conflicts
  changelog/v1.7.0-beta7/fix-proto-conflicts.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/udpa/annotations/migrate.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/udpa/annotations/sensitive.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/udpa/annotations/status.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/udpa/annotations/versioning.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/external/envoy/annotations/deprecation.proto
  projects/gloo/api/external/envoy/config/core/v3/address.proto
  projects/gloo/api/external/envoy/config/core/v3/backoff.proto
  projects/gloo/api/external/envoy/config/core/v3/base.proto
  projects/gloo/api/external/envoy/config/core/v3/event_service_config.proto
  projects/gloo/api/external/envoy/config/core/v3/extension.proto
  projects/gloo/api/external/envoy/config/core/v3/grpc_service.proto
  projects/gloo/api/external/envoy/config/core/v3/health_check.proto
  projects/gloo/api/external/envoy/config/core/v3/http_uri.proto
  projects/gloo/api/external/envoy/config/core/v3/proxy_protocol.proto
  projects/gloo/api/external/envoy/config/core/v3/socket_option.proto
  projects/gloo/api/external/envoy/config/route/v3/route_components.proto
  projects/gloo/api/external/envoy/config/trace/v3/datadog.proto
  projects/gloo/api/external/envoy/config/trace/v3/zipkin.proto
  projects/gloo/api/external/envoy/extensions/http_path/http_path.proto
  projects/gloo/api/external/envoy/type/matcher/v3/regex.proto
  projects/gloo/api/external/envoy/type/matcher/v3/string.proto
  projects/gloo/api/external/envoy/type/metadata/v3/metadata.proto
  projects/gloo/api/external/envoy/type/tracing/v3/custom_tag.proto
  projects/gloo/api/external/envoy/type/v3/http.proto
  projects/gloo/api/external/envoy/type/v3/percent.proto
  projects/gloo/api/external/envoy/type/v3/range.proto
  projects/gloo/api/external/envoy/type/v3/semantic_version.proto
  projects/gloo/api/external/udpa/annotations/migrate.proto
  projects/gloo/api/external/udpa/annotations/sensitive.proto
  projects/gloo/api/external/udpa/annotations/status.proto
  projects/gloo/api/external/udpa/annotations/versioning.proto
  projects/gloo/pkg/api/external/envoy/annotations/deprecation.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/address.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/backoff.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/base.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/event_service_config.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/extension.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/grpc_service.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/health_check.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/http_uri.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/proxy_protocol.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/socket_option.pb.go
  projects/gloo/pkg/api/external/envoy/config/route/v3/route_components.pb.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/zipkin.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/jwt_authn/v3/config.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/http_path/http_path.pb.go
  projects/gloo/pkg/api/external/envoy/type/matcher/v3/regex.pb.go
  projects/gloo/pkg/api/external/envoy/type/matcher/v3/string.pb.go
  projects/gloo/pkg/api/external/envoy/type/metadata/v3/metadata.pb.go
  projects/gloo/pkg/api/external/envoy/type/tracing/v3/custom_tag.pb.go
  projects/gloo/pkg/api/external/envoy/type/v3/http.pb.go
  projects/gloo/pkg/api/external/envoy/type/v3/percent.pb.go
  projects/gloo/pkg/api/external/envoy/type/v3/range.pb.go
  projects/gloo/pkg/api/external/envoy/type/v3/semantic_version.pb.go
Labels: Type: Tech Debt, keep pr updated

#4129 Update solo apis GitHub action
  .github/workflows/update-solo-apis.yaml
  changelog/v1.7.0-beta8/update-solo-apis-github-action.yaml
  install/helm/gloo/templates/8-default-gateways.yaml
  projects/gloo/cli/pkg/cmd/demo/federation.go
Labels: keep pr updated

#4128 Validator Race Condition
  changelog/v1.7.0-beta8/gateway-validation-webhook-race-condition.yaml
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#4132 proxy-memory-leak
  changelog/v1.7.0-beta8/proxy-mem-leak.yaml
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/extauth/extauth_translator_syncer.go
  projects/gloo/pkg/syncer/extauth/extauth_translator_syncer_test.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer_test.go
  projects/gloo/pkg/syncer/setup/setup_suite_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/translator/listener.go
Labels: keep pr updated

#4138 Backport proxy memory leak
  changelog/v1.6.3/proxy-mem-leak.yaml
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/translator/listener.go
Labels: keep pr updated

#4139 Backport Validator Race Condition
  changelog/v1.6.3/gateway-validation-webhook-race-condition.yaml
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#4141 Backport Validator Race Condition
  changelog/v1.5.15/gateway-validation-webhook-race-condition.yaml
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#4142 Update docs versions
  docs/active_versions.json
Labels: keep pr updated

#4143 Add install link in Gloo Edge WASM filter intro doc
  docs/content/installation/advanced_configuration/wasm.md
Labels: Type: Docs, keep pr updated

#4146 Update to docs around Rate Limiting by IP Address
  changelog/v1.7.0-beta9/update-gloo-edge-docs.yaml
  docs/content/guides/security/rate_limiting/envoy/_index.md
Labels: keep pr updated

#4156 Fixes for gRPC passthrough docs
  docs/content/guides/security/auth/extauth/passthrough_auth/_index.md
  docs/examples/grpc-passthrough-auth/authconfig.yaml
  docs/examples/grpc-passthrough-auth/service.yaml
Labels: keep pr updated

#4157 Fix passthrough docs backport 1.6
  docs/content/guides/security/auth/extauth/passthrough_auth/_index.md
  docs/examples/grpc-passthrough-auth/authconfig.yaml
  docs/examples/grpc-passthrough-auth/service.yaml
Labels: keep pr updated

#4158 Rate-Limit Set Style: fix request header ratelimiting
  changelog/v1.7.0-beta9/fix-ratelimit-set.yaml
  projects/gloo/pkg/plugins/ratelimit/raw_util.go
  projects/gloo/pkg/plugins/ratelimit/raw_util_test.go
Labels: keep pr updated

#4161 Expose static metadata on route
  changelog/v1.7.0-beta9/expose-static-envoy-route-md.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  projects/gateway/pkg/translator/converter.go
  projects/gateway/pkg/translator/merge_route_options.go
  projects/gateway/pkg/translator/merge_route_options_test.go
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/plugins/metadata/metadata_suite_test.go
  projects/gloo/pkg/plugins/metadata/plugin.go
  projects/gloo/pkg/plugins/metadata/plugin_test.go
  projects/gloo/pkg/plugins/registry/registry.go
Labels: keep pr updated

#4165 Change Helm to make deploying restxds optional
  changelog/v1.7.0-beta9/optional-rest-xds.yaml
  docs/content/reference/values.txt
  install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
  install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
  install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
  install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4170 Change Helm to make deploying restxds optional (#4165)
  changelog/v1.6.5/optional-rest-xds.yaml
  docs/content/reference/values.txt
  install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
  install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
  install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
  install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4167 re-enable rest eds by default
  changelog/v1.7.0-beta9/enable-rest-eds.yaml
  install/helm/gloo/templates/18-settings.yaml
  install/test/helm_test.go
  projects/gloo/pkg/xds/utils.go
Labels: keep pr updated

#4155 Re-enable REST EDS
  changelog/v1.6.5/enable-rest-eds.yaml
  install/helm/gloo/templates/18-settings.yaml
  projects/gloo/pkg/xds/utils.go
Labels: keep pr updated

#4174 Add ConfigDumpServiceSuffix constant
  changelog/v1.7.0-beta9/service-name-suffix-constant.yaml
  projects/gateway/pkg/defaults/gateway.go
Labels: keep pr updated

#4147 Update k8 v.19
  changelog/v1.7.0-beta9/update-k8s-19.yaml
  go.mod
  go.sum
  test/mocks/kubernetes/kubeinterface.go
Labels: keep pr updated, work in progress

#4180 add dep bump to changelog for 1.19
  changelog/v1.7.0-beta9/update-k8s-19.yaml
Labels: keep pr updated

#4172 Rate limit metadata actions
  changelog/v1.7.0-beta9/metadata-rate-limit-actions.yaml
  docs/content/reference/api/github.com/solo-io/solo-apis/api/rate-limiter/v1alpha1/ratelimit.proto.sk.md
  go.mod
  go.sum
  projects/gloo/pkg/plugins/ratelimit/plugin.go
  projects/gloo/pkg/plugins/ratelimit/raw_util.go
  projects/gloo/pkg/plugins/ratelimit/raw_util_test.go
  projects/gloo/pkg/plugins/ratelimit/util.go
  test/e2e/ratelimit_test.go
Labels: keep pr updated

#4175 Wasm initcontainers
  docs/Makefile
  docs/content/installation/advanced_configuration/wasm.md
Labels: Type: Docs, keep pr updated

#4183 Fix broken link in docs
  changelog/v1.7.0-beta10/docs-link-fix-datadog.yaml
  docs/content/guides/integrations/datadog/_index.md
Labels: keep pr updated

#4184 Rate-Limit Set Style: fix request header ratelimiting
  changelog/v1.6.5/fix-ratelimit-set.yaml
  projects/gloo/pkg/plugins/ratelimit/raw_util.go
  projects/gloo/pkg/plugins/ratelimit/raw_util_test.go
Labels: keep pr updated

#4185 Extauth transport v3
  changelog/v1.7.0-beta10/extauth-transport-version.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
  projects/gloo/pkg/plugins/extauth/filter.go
  projects/gloo/pkg/plugins/extauth/filter_test.go
Labels: keep pr updated

#4181 Generate Open Source Attribution doc in codegen
  Makefile
  changelog/v1.7.0-beta11/osa-docs.yaml
  ci/kind.sh
  docs/content/reference/open-source-attribution/_index.md
  go.mod
  go.sum
  hack/utils/oss_compliance/main.go
  hack/utils/oss_compliance/third_party_licenses.txt
  projects/gloo/cmd/Dockerfile
Labels: keep pr updated

#4189 Refactor generated Open Source Attribution docs to markdown files
  Makefile
  docs/content/reference/open-source-attribution/_index.md
  docs/content/static/content/osa_included.md
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  hack/utils/oss_compliance/oss_compliance.go
Labels: keep pr updated

#4191 Expose listener socket options
  changelog/v1.7.0-beta11/socket-options.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/plugins/listener/listener_suite_test.go
  projects/gloo/pkg/plugins/listener/plugin.go
  projects/gloo/pkg/plugins/listener/plugin_test.go
Labels: keep pr updated

#4192 Backport expose listener socket options
  changelog/v1.6.6/socket-options.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/plugins/listener/listener_suite_test.go
  projects/gloo/pkg/plugins/listener/plugin.go
  projects/gloo/pkg/plugins/listener/plugin_test.go
Labels: keep pr updated

#4195 Add Rest XDS to envoy tests
  awang-test-do-not-merge.txt
  test/consulvaulte2e/consul_vault_test.go
  test/e2e/access_log_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
  test/e2e/buffer_test.go
  test/e2e/consul_test.go
  test/e2e/cors_test.go
  test/e2e/csrf_test.go
  test/e2e/custom_auth_test.go
  test/e2e/fault_injection_test.go
  test/e2e/gateway_test.go
  test/e2e/grpc_json_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/grpcweb_test.go
  test/e2e/gzip_test.go
  test/e2e/happypath_test.go
  test/e2e/health_checks_test.go
  test/e2e/ratelimit_test.go
  test/e2e/route_transformation_test.go
  test/e2e/staged_transformation_test.go
  test/e2e/util_test.go
  test/e2e/zipkin_test.go
  test/services/envoy.go
  test/services/gateway.go
Labels: keep pr updated

#4200 Backport expose listener socket options
  changelog/v1.5.16/socket-options.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/plugins/listener/listener_suite_test.go
  projects/gloo/pkg/plugins/listener/plugin.go
  projects/gloo/pkg/plugins/listener/plugin_test.go
Labels: keep pr updated

#4179 Fix rest eds default 1.6
  changelog/v1.6.5/enable-rest-eds.yaml
  projects/gloo/pkg/xds/utils.go
  projects/gloo/pkg/xds/utils_test.go
  test/consulvaulte2e/consul_vault_test.go
  test/e2e/access_log_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
  test/e2e/buffer_test.go
  test/e2e/consul_test.go
  test/e2e/cors_test.go
  test/e2e/csrf_test.go
  test/e2e/custom_auth_test.go
  test/e2e/fault_injection_test.go
  test/e2e/gateway_test.go
  test/e2e/grpc_json_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/grpcweb_test.go
  test/e2e/gzip_test.go
  test/e2e/happypath_test.go
  test/e2e/health_checks_test.go
  test/e2e/ratelimit_test.go
  test/e2e/route_transformation_test.go
  test/e2e/staged_transformation_test.go
  test/e2e/util_test.go
  test/e2e/zipkin_test.go
  test/services/envoy.go
  test/services/gateway.go
Labels: keep pr updated

#4178 Fix rest eds default
  changelog/v1.7.0-beta9/enable-rest-eds.yaml
  projects/gloo/pkg/xds/utils.go
  projects/gloo/pkg/xds/utils_test.go
  test/consulvaulte2e/consul_vault_test.go
  test/e2e/access_log_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
  test/e2e/buffer_test.go
  test/e2e/consul_test.go
  test/e2e/cors_test.go
  test/e2e/csrf_test.go
  test/e2e/custom_auth_test.go
  test/e2e/fault_injection_test.go
  test/e2e/gateway_test.go
  test/e2e/grpc_json_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/grpcweb_test.go
  test/e2e/gzip_test.go
  test/e2e/happypath_test.go
  test/e2e/health_checks_test.go
  test/e2e/ratelimit_test.go
  test/e2e/route_transformation_test.go
  test/e2e/staged_transformation_test.go
  test/e2e/util_test.go
  test/e2e/zipkin_test.go
  test/services/envoy.go
  test/services/gateway.go
Labels: keep pr updated

#4199 Add GPL check to CI
  Makefile
  changelog/v1.7.0-beta12/check-gpl-licenses.yaml
  docs/content/reference/cli/glooctl_add.md
  docs/content/reference/cli/glooctl_check.md
  docs/content/reference/cli/glooctl_cluster_list.md
  docs/content/reference/cli/glooctl_debug.md
  docs/content/reference/cli/glooctl_debug_logs.md
  docs/content/reference/cli/glooctl_debug_yaml.md
  docs/content/reference/cli/glooctl_delete.md
  docs/content/reference/cli/glooctl_demo.md
  docs/content/reference/cli/glooctl_edit.md
  docs/content/reference/cli/glooctl_edit_route.md
  docs/content/reference/cli/glooctl_edit_settings.md
  docs/content/reference/cli/glooctl_get.md
  docs/content/reference/cli/glooctl_istio.md
  docs/content/reference/cli/glooctl_plugin_list.md
  docs/content/reference/cli/glooctl_proxy_dump.md
  docs/content/reference/cli/glooctl_proxy_logs.md
  docs/content/reference/cli/glooctl_proxy_served-config.md
  docs/content/reference/cli/glooctl_proxy_stats.md
  docs/content/reference/cli/glooctl_remove.md
  docs/content/reference/cli/glooctl_route.md
  docs/content/reference/cli/glooctl_uninstall.md
  docs/content/reference/cli/glooctl_uninstall_federation.md
  docs/content/reference/cli/glooctl_upgrade.md
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  hack/utils/oss_compliance/oss_compliance.go
Labels: keep pr updated

#4202 Minor wasm initContainers docs improvements
  docs/content/installation/advanced_configuration/wasm.md
Labels: Type: Docs, keep pr updated

#4212 Bump protoc gen ext
  changelog/v1.7.0-beta12/bump-protoc-gen-ext.yaml
  go.mod
  go.sum
  projects/gateway/pkg/api/v1/gateway.pb.equal.go
  projects/gateway/pkg/api/v1/virtual_service.pb.equal.go
  projects/gloo/pkg/api/external/envoy/api/v2/core/health_check.pb.equal.go
  projects/gloo/pkg/api/external/envoy/api/v2/route/route.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/address.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/base.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/event_service_config.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/grpc_service.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/health_check.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/http_uri.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/socket_option.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/route/v3/route_components.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/zipkin.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/buffer/v3/buffer.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/wasm/v3/wasm.pb.equal.go
  projects/gloo/pkg/api/external/envoy/type/matcher/v3/regex.pb.equal.go
  projects/gloo/pkg/api/external/envoy/type/matcher/v3/string.pb.equal.go
  projects/gloo/pkg/api/external/envoy/type/metadata/v3/metadata.pb.equal.go
  projects/gloo/pkg/api/external/envoy/type/tracing/v3/custom_tag.pb.equal.go
  projects/gloo/pkg/api/grpc/version/version.pb.equal.go
  projects/gloo/pkg/api/v1/core/matchers/matchers.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/waf/waf.pb.equal.go
  projects/gloo/pkg/api/v1/load_balancer.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options/als/als.pb.equal.go
  projects/gloo/pkg/api/v1/options/aws/ec2/aws_ec2.pb.equal.go
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.equal.go
  projects/gloo/pkg/api/v1/options/lbhash/lbhash.pb.equal.go
  projects/gloo/pkg/api/v1/options/protocol_upgrade/protocol_upgrade.pb.equal.go
  projects/gloo/pkg/api/v1/options/rest/rest.pb.equal.go
  projects/gloo/pkg/api/v1/options/service_spec.pb.equal.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.equal.go
  projects/gloo/pkg/api/v1/options/wasm/wasm.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/secret.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/ssl.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  test/e2e/aws_ec2_test.go
Labels: keep pr updated

#4201 Envoy discovery flake Test
  .github/workflows/regression-tests-and-codegen.yaml
  changelog/v1.7.0-beta12/endpoint-discovery-flake-test.yaml
  ci/kind.sh
  go.mod
  go.sum
  test/kube2e/README.md
  test/kube2e/eds/eds_suite_test.go
  test/kube2e/eds/eds_test.go
Labels: keep pr updated

#4220 (1.6.x backport) Bump protoc gen ext (#4212)
  changelog/v1.6.7/bump-protoc-gen-ext.yaml
  go.mod
  go.sum
  projects/gateway/pkg/api/v1/gateway.pb.equal.go
  projects/gateway/pkg/api/v1/virtual_service.pb.equal.go
  projects/gloo/pkg/api/external/envoy/api/v2/core/health_check.pb.equal.go
  projects/gloo/pkg/api/external/envoy/api/v2/route/route.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/address.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/base.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/event_service_config.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/grpc_service.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/health_check.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/http_uri.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/socket_option.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/route/v3/route_components.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/zipkin.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/buffer/v3/buffer.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/wasm/v3/wasm.pb.equal.go
  projects/gloo/pkg/api/external/envoy/type/matcher/v3/regex.pb.equal.go
  projects/gloo/pkg/api/external/envoy/type/matcher/v3/string.pb.equal.go
  projects/gloo/pkg/api/external/envoy/type/metadata/v3/metadata.pb.equal.go
  projects/gloo/pkg/api/external/envoy/type/tracing/v3/custom_tag.pb.equal.go
  projects/gloo/pkg/api/grpc/version/version.pb.equal.go
  projects/gloo/pkg/api/v1/core/matchers/matchers.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/waf/waf.pb.equal.go
  projects/gloo/pkg/api/v1/load_balancer.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options/als/als.pb.equal.go
  projects/gloo/pkg/api/v1/options/aws/ec2/aws_ec2.pb.equal.go
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.equal.go
  projects/gloo/pkg/api/v1/options/lbhash/lbhash.pb.equal.go
  projects/gloo/pkg/api/v1/options/protocol_upgrade/protocol_upgrade.pb.equal.go
  projects/gloo/pkg/api/v1/options/rest/rest.pb.equal.go
  projects/gloo/pkg/api/v1/options/service_spec.pb.equal.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.equal.go
  projects/gloo/pkg/api/v1/options/wasm/wasm.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/secret.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/ssl.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  test/e2e/aws_ec2_test.go
Labels: keep pr updated

#4225 Fix gzip flake
  changelog/v1.7.0-beta13/endpoint-discovery-flake-test.yaml
  test/e2e/gzip_test.go
Labels: keep pr updated

#4229 Remove obsolete references to AMQP support + others
  docs/content/guides/traffic_management/_index.md
  docs/content/introduction/architecture/concepts.md
Labels: keep pr updated
