Repository kgateway-dev/kgateway, pull requests merged in 2021-09, with the labels that each got.

#5279 update upgrade docs for enterprise UI
  docs/content/installation/advanced_configuration/gloo-readonly-ui.md
  docs/content/operations/upgrading/1.8.0.md
Labels: Type: Docs, keep pr updated

#5273 Add details about finer-grained log access and resetting to info logs to debug docs
  docs/content/operations/debugging_gloo/_index.md
Labels: Type: Docs, keep pr updated

#5281 Add directions for scraping Edge control plane metrics to Datadog
  docs/content/guides/integrations/datadog/_index.md
  docs/content/guides/integrations/datadog/envoy-dd-dash.png
  docs/content/guides/integrations/datadog/envoy-dd-logs.png
  docs/content/guides/integrations/datadog/envoy-dd-metrics-explorer.png
Labels: Type: Docs, keep pr updated

#5285 Add RegexAction to user facing settings
  changelog/v1.9.0-beta16/dlp-regex-matching.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/dlp/dlp.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto
  projects/gloo/api/v1/enterprise/options/dlp/dlp.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation_ee/transformation.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.hash.go
Labels: keep pr updated

#5290 Fixing compressedProxySpec not working after crd schemas introduction
  changelog/v1.9.0-beta17/dlp-regex-matching.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.hash.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#5295 Compress proxy fix
  changelog/v1.8.13/dlp-regex-matching.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.hash.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#5294 Fix broken doc links in multiple proto files
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/ec2/aws_ec2.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/azure/azure.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/tracing/tracing.proto.sk.md
  projects/gateway/api/v1/gateway.proto
  projects/gateway/pkg/api/v1/gateway.pb.go
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/aws/aws.proto
  projects/gloo/api/v1/options/aws/ec2/aws_ec2.proto
  projects/gloo/api/v1/options/azure/azure.proto
  projects/gloo/api/v1/options/tracing/tracing.proto
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.go
  projects/gloo/pkg/api/v1/options/aws/ec2/aws_ec2.pb.go
  projects/gloo/pkg/api/v1/options/azure/azure.pb.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.go
Labels: keep pr updated

#5284 Backport RegexAction to DLP proto
  changelog/v1.8.14/regexaction-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/dlp/dlp.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto
  projects/gloo/api/v1/enterprise/options/dlp/dlp.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation_ee/transformation.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.hash.go
Labels: keep pr updated

#5299 Doc - multi gateway deployments
  changelog/v1.9.0-beta17/doc-multi-gw-deployment.yaml
  docs/content/img/gateways-relationship.png
  docs/content/img/gw-proxies-full-example.png
  docs/content/installation/advanced_configuration/multi-gw-deployment.md
Labels: Type: Docs, keep pr updated

#5307 Use correct map key when deleting endpoints in sanitizer
  changelog/v1.9.0-beta17/upstream-sanitizer-fix.yaml
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer.go
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer_test.go
Labels: keep pr updated

#5310 Backport change to use correct map key when deleting endpoints in san…
  changelog/v1.8.15/upstream-sanitizer-fix.yaml
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer.go
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer_test.go
Labels: keep pr updated

#5313 Backport change to correct map key when deleting endpoints in sanitiz…
  changelog/v1.6.38/upstream-sanitizer-fix.yaml
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer.go
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer_test.go
Labels: keep pr updated

#5311 Add JwksAsyncFetch configuration
  changelog/v1.9.0-beta17/jwk_async_fetch.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/filters/http/jwt_authn/v3/config.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/jwt/jwt.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/external/envoy/extensions/filters/http/jwt_authn/v3/config.proto
  projects/gloo/api/v1/enterprise/options/jwt/jwt.proto
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/jwt_authn/v3/config.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.hash.go
Labels: keep pr updated

#5292 go to prod check list: reworked chapters order and add some new content
  changelog/v1.9.0-beta18/got-to-prod-checklist.yaml
  docs/content/img/grafana-us-part1.png
  docs/content/img/grafana-us-part2.png
  docs/content/img/grafana-us-part3.png
  docs/content/operations/production_deployment/_index.md
Labels: keep pr updated

#5308 Aws Lambda Request Transform
  changelog/v1.9.0-beta18/aws-lambda-header-body-request-transform.yaml
  docs/content/guides/dev/registry.go
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
  projects/gloo/api/v1/options/aws/aws.proto
  projects/gloo/pkg/api/v1/options/aws/aws.pb.equal.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.hash.go
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/azure/plugin.go
  projects/gloo/pkg/plugins/azure/plugin_test.go
  projects/gloo/pkg/plugins/grpc/plugin.go
  projects/gloo/pkg/plugins/grpc/plugin_test.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/plugins/rest/plugin_test.go
  projects/gloo/pkg/plugins/rest/rest.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  test/e2e/README.md
  test/e2e/aws_test.go
Labels: keep pr updated

#5325 Ignore health on host removal
  changelog/v1.9.0-beta18/ignore-health-check-on-host-removal.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#5328 Backport 1.8 upgrade docs
  changelog/v1.8.16/upgrade-docs-backport.yaml
  docs/content/operations/upgrading/1.8.0.md
Labels: keep pr updated

#5329 Bump latest doc version
  docs/active_versions.json
Labels: keep pr updated

#5334 update_upstream_spec includes ignoreHealthOnHostRemoval
  projects/gloo/pkg/plugins/utils/update_upstream_spec.go
Labels: keep pr updated

#5315 add tips for all cases in {tls, mtls, trusted CAs, unstrusted CAs}
  changelog/v1.9.0-beta19/doc-upstream-tls-mtls.yaml
  docs/content/guides/security/tls/client_tls.md
Labels: Type: Docs, keep pr updated

#5330 Ignore health backport 1.8
  changelog/v1.8.17/ignore-health-check-on-host-removal.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#5321 Fix valid config metric
  changelog/v1.9.0-beta19/fix-valid-config-metric.yaml
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#5300 Docs - Updating to pull the Hugo theme dynamically
  docs/Makefile
Labels: Type: Docs, keep pr updated

#5349 Update _index.md
  docs/content/guides/integrations/datadog/_index.md
Labels: Type: Docs

#5354 V1 vwh
  changelog/v1.9.0-beta19/upgrade-vwh.yaml
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  install/test/helm_test.go
Labels: keep pr updated

#5348 Fail release loudly
  Makefile
  changelog/v1.9.0-beta19/release-build-fails.yaml
  ci/extended-docker/extended-docker.sh
  cloudbuild.yaml
Labels: keep pr updated

#5356 Add CI check for DO_NOT_SUBMIT comments in go files.
  .github/workflows/do-not-submit.yaml
  changelog/v1.9.0-beta19/do-not-submit.yaml
  ci/do-not-submit.sh
Labels: keep pr updated

#5367 Fix the tags for -extended gcr images
  Makefile
  changelog/v1.9.0-beta20/gcr-push-fix.yaml
Labels: keep pr updated

#5363 Canary docs
  changelog/v1.9.0-beta21/doc-canary.yaml
  docs/content/operations/upgrading/1.8.0.md
  docs/content/operations/upgrading/1.9.0.md
  docs/content/operations/upgrading/canary.md
  docs/content/operations/upgrading/upgrade_steps.md
Labels: keep pr updated

#5369 return validation reports for each proxy
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/validation/gloo_validation.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gateway/pkg/reconciler/proxy_reconciler.go
  projects/gateway/pkg/validation/validator.go
  projects/gloo/api/grpc/validation/gloo_validation.proto
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.equal.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.hash.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/validation/server.go
  projects/gloo/pkg/validation/server_test.go
  test/benchmark/snapshot_benchmark_test.go
Labels: keep pr updated

#5360 Doc - update the doc on NLB and add examples for HTTPs redirections
  docs/content/guides/integrations/aws/_index.md
  docs/content/img/https-redirect-tls-offloading.png
Labels: keep pr updated

#5374 Fix valid config metric [1.8]
  changelog/v1.8.18/fix-valid-config-metric.yaml
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#5375 Relase fail loudly 1 7
  changelog/v1.7.22/release-build-fails.yaml
  ci/extended-docker/extended-docker.sh
Labels: keep pr updated

#5365 Fail release loudly (#5348)
  changelog/v1.8.18/release-build-fails.yaml
  ci/extended-docker/extended-docker.sh
Labels: keep pr updated

#5382 fix typo on the ALBC target type annotation
  docs/content/guides/integrations/aws/_index.md
Labels: keep pr updated

#5380 doc - small reorg of the production deployment page
  docs/content/operations/production_deployment/_index.md
Labels: keep pr updated

#5379 Add docs for updating expired enterprise license
  docs/content/img/jwt-io-license-expired.png
  docs/content/img/k9s-license-expired.png
  docs/content/img/k9s-license-refreshed.png
  docs/content/installation/enterprise/_index.md
  docs/content/operations/updating_license/_index.md
Labels: Type: Docs, keep pr updated

#5384 Doc - zero downtime gateway rollout
  docs/content/img/0dt-grafana-results-helm-upgrade.png
  docs/content/img/0dt-grafana-results-rollout-restart.png
  docs/content/img/0dt-overview.png
  docs/content/operations/advanced/zero-downtime-gateway-rollout/_index.md
Labels: Type: Docs, keep pr updated

#5387 Fix typo in glooctl check
  changelog/v1.9.0-beta22/fix-glooctl-check-gloo-fed.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_instances.go
Labels: keep pr updated

#5390 Prepare 1.9.0-rc1 directory
  changelog/v1.9.0-rc1/fix-glooctl-check-gloo-fed.yaml
Labels: keep pr updated

#5392 fix the glooctl gloo fed check to use deployment
  changelog/v1.9.0-rc2/fix-glooctl-check-gloo-fed.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_instances.go
Labels: keep pr updated

#5397 Docs: Move helm prefix warning
  docs/content/reference/helm_chart_values/enterprise_helm_chart_values.md
  docs/content/reference/helm_chart_values/open_source_helm_chart_values.md
Labels: keep pr updated

#5399 Backport: Docs: Move helm prefix warning (#5397)
  docs/content/reference/helm_chart_values/enterprise_helm_chart_values.md
  docs/content/reference/helm_chart_values/open_source_helm_chart_values.md
Labels: keep pr updated

#5418 Upgrade dependencies to fix vulnerabilities found in security scan (1.6)
  changelog/v1.6.38/upgrade-protobuf-dep.yaml
  go.mod
  go.sum
Labels: keep pr updated

#5373 Generate v1 CRDs
  changelog/v1.9.0-rc2/v1-crds.yaml
  go.mod
  go.sum
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
  install/helm/gloo/crds/ratelimit_config.yaml
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#5402 Upgrade dependencies to fix vulnerabilities found in security scan (1.8)
  changelog/v1.8.18/upgrade-protobuf-dep.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#5301 Add upstream to gRPC validation service
  changelog/v1.9.0-rc3/upstream-validation.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/validation/gloo_validation.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  install/test/helm_test.go
  projects/gateway/pkg/reconciler/proxy_reconciler.go
  projects/gateway/pkg/reconciler/proxy_reconciler_test.go
  projects/gateway/pkg/services/k8sadmission/cert_provider.go
  projects/gateway/pkg/services/k8sadmission/cert_provider_test.go
  projects/gateway/pkg/services/k8sadmission/k8sadmisssion_suite_test.go
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook.go
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook_test.go
  projects/gateway/pkg/syncer/setup_syncer.go
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
  projects/gloo/api/grpc/validation/gloo_validation.proto
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.equal.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.hash.go
  projects/gloo/pkg/validation/server.go
  projects/gloo/pkg/validation/server_test.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#5421 Node selector overwrite
  changelog/v1.9.0-rc3/nodeselector-override.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#5420 Downstream healthcheck docfix
  changelog/v1.9.0-rc3/doc-lb-downstream-healtcheck.yaml
  docs/content/operations/production_deployment/_index.md
Labels: keep pr updated

#5398 Update Trivy Dependency
  .github/workflows/trivy-analysis-scheduled.yaml
Labels: keep pr updated

#5400 Doc revisions to the upgrade process
  docs/content/operations/upgrading/0.18.1.md
  docs/content/operations/upgrading/1.0.0.md
  docs/content/operations/upgrading/1.3.0.md
  docs/content/operations/upgrading/1.4.0.md
  docs/content/operations/upgrading/1.5.0.md
  docs/content/operations/upgrading/1.7.0.md
  docs/content/operations/upgrading/1.8.0.md
  docs/content/operations/upgrading/1.9.0.md
  docs/content/operations/upgrading/canary.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/static/content/gee_version_latest.md
  docs/content/static/content/geoss_version_latest.md
  docs/content/static/content/geoss_version_n-1.md
Labels: keep pr updated

#5423 Backport for doc revisions to the upgrade process (#5400)
  docs/content/operations/upgrading/0.18.1.md
  docs/content/operations/upgrading/1.0.0.md
  docs/content/operations/upgrading/1.3.0.md
  docs/content/operations/upgrading/1.4.0.md
  docs/content/operations/upgrading/1.5.0.md
  docs/content/operations/upgrading/1.7.0.md
  docs/content/operations/upgrading/1.8.0.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/static/content/gee_version_latest.md
  docs/content/static/content/geoss_version_latest.md
  docs/content/static/content/geoss_version_n-1.md
Labels: keep pr updated

#5424 Node selector overwrite 1.8 backport
  changelog/v1.8.19/nodeselector-override.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#5425 Node selector overwrite (#5421)
  changelog/v1.7.23/nodeselector-override.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated
