Repository kgateway-dev/kgateway, pull requests merged in 2021-03, with the labels that each got.

#4356 fix extra v in branch name
  .github/workflows/update-solo-apis.yaml
Labels: keep pr updated

#4351 Only generate docs on Pull Requests to Master
  .github/workflows/docs-gen.yaml
  .github/workflows/regression-tests-and-codegen.yaml
  changelog/v1.7.0-beta25/cleanup-docs-workflows.yaml
  ci/check-generated-code.sh
Labels: keep pr updated

#4365 Backport Only generate docs on Pull Requests to Master
  .github/workflows/docs-gen.yaml
  .github/workflows/regression-tests-and-codegen.yaml
  changelog/v1.6.9/cleanup-docs-workflows.yaml
  ci/check-generated-code.sh
Labels: keep pr updated

#4342 Install gloo-fed alongside gloo-ee
  changelog/v1.7.0-beta25/install-gloo-fed-with-glooee.yaml
  docs/content/installation/gloo_federation.md
  docs/content/reference/cli/glooctl_install_gateway_enterprise.md
  projects/gloo/cli/pkg/cmd/install/enterprise.go
  projects/gloo/cli/pkg/cmd/install/install_test.go
  projects/gloo/cli/pkg/cmd/install/installer.go
  projects/gloo/cli/pkg/cmd/install/installer_test.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/options/options.go
  projects/gloo/cli/pkg/flagutils/install.go
Labels: keep pr updated

#4344 Backport One way TLS Supports Global SslParameters
  changelog/v1.6.9/one-way-tls-params.yaml
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
  projects/gloo/pkg/plugins/azure/plugin.go
  projects/gloo/pkg/plugins/azure/plugin_test.go
  projects/gloo/pkg/plugins/static/plugin.go
  projects/gloo/pkg/plugins/static/plugin_test.go
  projects/gloo/pkg/utils/mocks/mock_ssl.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
  projects/gloo/pkg/utils/upstream.go
Labels: keep pr updated

#4308 Add init-plugin-manager command
  changelog/v1.7.0-beta26/init-plugin-manager.yaml
  docs/content/reference/cli/glooctl.md
  docs/content/reference/cli/glooctl_init-plugin-manager.md
  projects/gloo/cli/pkg/cmd/initpluginmanager/initpluginmanager.go
  projects/gloo/cli/pkg/cmd/root.go
Labels: keep pr updated

#4359 Add OAuth2 docs guide for Auth0
  docs/content/guides/security/auth/extauth/oauth/auth0/_index.md
  docs/content/guides/security/auth/extauth/oauth/auth0/auth0-app-assignments.png
  docs/content/guides/security/auth/extauth/oauth/auth0/auth0-app-profile.png
  docs/content/guides/security/auth/extauth/oauth/auth0/auth0-dashboard.png
  docs/content/guides/security/auth/extauth/oauth/auth0/auth0-glootest-get-1.png
  docs/content/guides/security/auth/extauth/oauth/auth0/auth0-glootest-get-2.png
  docs/content/guides/security/auth/extauth/oauth/auth0/auth0-glootest-get-3.png
  docs/content/guides/security/auth/extauth/oauth/auth0/auth0-google-user-auth.png
  docs/content/guides/security/auth/extauth/oauth/auth0/auth0-jwt-claims-decoded.png
  docs/content/guides/security/auth/extauth/oauth/auth0/auth0-session-cookie.png
  docs/content/guides/security/auth/extauth/oauth/auth0/auth0-sign-in.png
  docs/content/guides/security/auth/extauth/oauth/auth0/auth0-user-list.png
  docs/content/guides/security/auth/extauth/oauth/auth0/glootest-access-denied.png
  docs/content/guides/security/auth/extauth/oauth/auth0/httpbin-base64.png
  docs/content/guides/security/auth/extauth/oauth/auth0/okta-jwt-request.png
  docs/content/guides/security/auth/extauth/oauth/auth0/okta-user-list.png
Labels: Type: Docs

#4372 Add comment around v2 xDS server
  projects/gloo/pkg/xds/envoy.go
Labels: keep pr updated

#4358 Http connect proxy
  changelog/v1.7.0-beta26/http_connect_tunneling.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/tcp/tcp.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/ssl.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  go.mod
  go.sum
  projects/gateway/pkg/translator/translator_test.go
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/tcp/tcp.proto
  projects/gloo/api/v1/proxy.proto
  projects/gloo/api/v1/ssl.proto
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options/tcp/tcp.pb.equal.go
  projects/gloo/pkg/api/v1/options/tcp/tcp.pb.go
  projects/gloo/pkg/api/v1/options/tcp/tcp.pb.hash.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/ssl.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/plugin_interface.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/plugins/tcp/plugin.go
  projects/gloo/pkg/plugins/tcp/plugin_test.go
  projects/gloo/pkg/plugins/tunneling/tunneling.go
  projects/gloo/pkg/plugins/tunneling/tunneling_suite_test.go
  projects/gloo/pkg/plugins/tunneling/tunneling_test.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/utils.go
  projects/gloo/pkg/translator/utils_test.go
  test/e2e/http_tunneling_test.go
Labels: keep pr updated

#4376 JWT docs fix
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/jwt/jwt.proto.sk.md
  projects/gloo/api/v1/enterprise/options/jwt/jwt.proto
  projects/gloo/pkg/api/v1/enterprise/options/jwt/jwt.pb.go
Labels: keep pr updated

#4377 Http connect proxy 1.6
  changelog/v1.6.10/http_connect_tunneling.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/tcp/tcp.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/ssl.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  go.mod
  go.sum
  projects/gateway/pkg/translator/translator_test.go
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/tcp/tcp.proto
  projects/gloo/api/v1/proxy.proto
  projects/gloo/api/v1/ssl.proto
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options/tcp/tcp.pb.equal.go
  projects/gloo/pkg/api/v1/options/tcp/tcp.pb.go
  projects/gloo/pkg/api/v1/options/tcp/tcp.pb.hash.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/ssl.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/plugin_interface.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/plugins/tcp/plugin.go
  projects/gloo/pkg/plugins/tcp/plugin_test.go
  projects/gloo/pkg/plugins/tunneling/tunneling.go
  projects/gloo/pkg/plugins/tunneling/tunneling_suite_test.go
  projects/gloo/pkg/plugins/tunneling/tunneling_test.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/utils.go
  projects/gloo/pkg/translator/utils_test.go
  test/e2e/http_tunneling_test.go
Labels: keep pr updated

#4380 Backport passthrough config api
  changelog/v1.6.11/passthrough-auth-custom-config.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4373 Passthrough auth config doc
  docs/content/guides/security/auth/extauth/passthrough_auth/_index.md
Labels: keep pr updated

#4381 Backport passthrough auth config doc
  docs/content/guides/security/auth/extauth/passthrough_auth/_index.md
Labels: keep pr updated

#4375 Helm log level env var
  changelog/v1.7.0-beta26/add-helm-log-level-env-variables.yaml
  docs/content/operations/debugging_gloo/_index.md
  go.mod
  go.sum
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/helm/gloo/templates/5-gateway-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4382 Add changelog for 1.6.13
  changelog/v1.6.13/passthrough-auth-custom-config.yaml
Labels: keep pr updated

#4384 Improve test to know when we can go back to gRPC
  test/kube2e/eds/eds_test.go
  test/kube2e/util.go
Labels: keep pr updated

#4388 Tweak JWT claim routing doc to fix pipe character formatting
  docs/content/guides/security/auth/jwt/claim_routing.md
Labels: Type: Docs, keep pr updated

#4393 Improve CPU & bump envoy dependency
  Makefile
  changelog/v1.7.0-beta26/improve-rest-eds-perf.yaml
  go.mod
  go.sum
Labels: keep pr updated

#4399 Fix bad email reference in Auth0 doc
  docs/content/guides/security/auth/extauth/oauth/auth0/_index.md
Labels: Type: Docs, keep pr updated

#4400 Fix workflow name for trivy scanner
  .github/workflows/docs-gen.yaml
  .github/workflows/trivy-analysis.yaml
  changelog/v1.7.0-beta27/fix-workflow-name.yaml
Labels: keep pr updated

#4402 Backport trivy workflow 1.5
  .github/workflows/trivy-analysis.yaml
  Makefile
  changelog/v1.5.17/backport-trivy-workflow.yaml
Labels: keep pr updated

#4401 Backport workflow for trivy scan 1.6
  .github/workflows/trivy-analysis.yaml
  Makefile
  changelog/v1.6.15/backport-trivy-workflow.yaml
Labels: keep pr updated

#4408 Update latest version for doc generation
  changelog/v1.7.0-beta27/update-latest-doc-version.yaml
  docs/active_versions.json
Labels: keep pr updated

#4414 Fix/docs scroll bug
  changelog/v1.7.0-beta27/fix-docs-scroll-bug.yaml
  docs/Makefile
Labels: keep pr updated

#4415 Fix/docs scroll bug backport
  changelog/v1.6.15/fix-docs-scroll-bug.yaml
  docs/Makefile
Labels: keep pr updated

#4412 Helm cleanup
  changelog/v1.7.0-beta27/helm-consolidation.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4403 Updating endpoints only does not require previous snapshot
  changelog/v1.7.0-beta28/eds-works-with-missing-prev-snapshot.yaml
  go.mod
  go.sum
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/syncer_test_helper.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/xds/envoy_snapshot.go
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#4420 Oauth2 supports authenticated introspection request
  changelog/v1.7.0-beta28/access-token-validation-client-details.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4423 solo-kit:v0.18.2
  changelog/v1.7.0-beta29/bump-solo-kit.yaml
  go.mod
  go.sum
Labels: keep pr updated

#4406 Generate glooe security scan
  .github/workflows/trivy-analysis.yaml
  Makefile
  changelog/v1.7.0-beta30/add-docs-security-scan-glooe.yaml
  docs/Makefile
  docs/cmd/generate_docs.go
  docs/cmd/securityscanutils/securityscan_utils.go
  docs/cmd/test/securityscanutils/generate_securityscan_doc_test.go
  docs/content/reference/security-updates/_index.md
  docs/content/reference/security-updates/enterprise/_index.md
  docs/content/reference/security-updates/open_source/_index.md
Labels: keep pr updated

#4431 Trigger on release for trivy scan
  .github/workflows/trivy-analysis.yaml
  Makefile
  changelog/v1.5.17/trigger-trivy-on-release.yaml
Labels: keep pr updated

#4430 Trigger on release for trivy scan
  .github/workflows/trivy-analysis.yaml
  Makefile
  changelog/v1.6.16/trigger-trivy-on-release.yaml
Labels: keep pr updated

#4435 Add modsecurity RBL warning to docs
  changelog/v1.7.0-beta31/add-rbl-warning.yaml
  docs/content/guides/security/waf/_index.md
Labels: keep pr updated

#4429 EDS missing snapshot fix
  changelog/v1.6.16/eds-works-with-missing-prev-snapshot.yaml
  go.mod
  go.sum
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/syncer_test_helper.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/xds/envoy_snapshot.go
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#4441 Fix gloo-fed demo script
  projects/gloo/cli/pkg/cmd/demo/federation.go
Labels: keep pr updated

#4437 Helm regex max program size
  changelog/v1.7.0-beta31/helm-value-regexmaxprgmsize.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/helm_test.go
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#4442 Helm regex max program size backport
  changelog/v1.6.16/helm-value-regexmaxprgmsize.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4444 Bump alpine version
  changelog/v1.7.0-beta31/bump-alpine.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#4450 Bump alpine
  changelog/v1.6.16/bump-alpine.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#4451 Bump alpine
  Makefile
Labels: keep pr updated

#4454 Markdown template
  changelog/v1.6.17/markdown-template-scan-report.yaml
  hack/utils/security_scan_report/markdown.tpl
Labels: keep pr updated

#4455 Bump docs
  docs/active_versions.json
Labels: keep pr updated

#4457 Markdown template backport 1.5
  changelog/v1.5.17/markdown-template-scan-report.yaml
  hack/utils/security_scan_report/markdown.tpl
Labels: keep pr updated

#4458 Fix doc gen formatting
  changelog/v1.7.0-beta32/doc-gen-format-fix-security-updates.yaml
  docs/cmd/securityscanutils/securityscan_utils.go
Labels: keep pr updated

#4462 typo
  docs/content/_index.md
Labels: keep pr updated

#4471 Support OIDC discoveryPollInterval
  changelog/v1.7.0-beta32/oidc-discovery-poll-interval.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4472 Support OIDC discoveryPollInterval
  changelog/v1.6.18/oidc-discoervy-poll-interval.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4473 Support OIDC discoveryPollInterval
  changelog/v1.5.17/oidc-discovery-poll-interval.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4478 Mtls toggle
  changelog/v1.7.0-beta33/one-way-tls-termination.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/ssl.proto.sk.md
  projects/gloo/api/v1/ssl.proto
  projects/gloo/pkg/api/v1/ssl.pb.equal.go
  projects/gloo/pkg/api/v1/ssl.pb.go
  projects/gloo/pkg/api/v1/ssl.pb.hash.go
  projects/gloo/pkg/bootstrap/utils.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: keep pr updated

#4479 Custom envoy bootstrap static layer from helm
  changelog/v1.7.0-rc1/custom-static-bootstrap.yaml
  changelog/v1.7.0-rc1/one-way-tls-termination.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/fixtures.go
  install/test/fixtures/envoy_config/bootstrap_extensions.yaml
  install/test/fixtures/envoy_config/custom_static_bootstrap.yaml
  install/test/fixtures/envoy_config/static_clusters.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  install/test/values/val_custom_static_bootstrap.yaml
Labels: keep pr updated

#4481 Consolidate gloo uis: remove with-admin-console flag
  changelog/v1.7.0-rc2/remove-readonly-gloo-ui.yaml
  docs/content/installation/advanced_configuration/gloo-readonly-ui.md
  docs/content/reference/cli/glooctl_install_gateway.md
  docs/content/reference/cli/glooctl_install_gateway_enterprise.md
  docs/content/reference/cli/glooctl_install_ingress.md
  docs/content/reference/cli/glooctl_install_knative.md
  projects/gloo/cli/pkg/cmd/dashboard/root.go
  projects/gloo/cli/pkg/cmd/install/enterprise.go
  projects/gloo/cli/pkg/cmd/install/gateway.go
  projects/gloo/cli/pkg/cmd/install/install_test.go
  projects/gloo/cli/pkg/cmd/install/installer.go
  projects/gloo/cli/pkg/cmd/options/options.go
  projects/gloo/cli/pkg/constants/constants.go
  projects/gloo/cli/pkg/flagutils/install.go
Labels: keep pr updated

#4489 Fix glooctl dashboard & small docs changes for 1.7
  changelog/v1.7.0-rc2/docs-changes.yaml
  docs/content/installation/enterprise/_index.md
  docs/content/operations/upgrading/1.7.0.md
  docs/content/reference/gloo_port_reference.md
  docs/content/reference/helm_chart_values.md
  projects/gloo/cli/pkg/cmd/dashboard/root.go
Labels: keep pr updated

#4492 Add changelog
  changelog/v1.8.0-beta1/placeholder.yaml
Labels: keep pr updated

#4439 Replacing errored routes
  changelog/v1.8.0-beta1/replace-routes-on-proxy-errors.yaml
  docs/content/guides/traffic_management/configuration_validation/invalid_route_replacement.md
  go.mod
  go.sum
  projects/gateway/pkg/reporting/add_proxy_validation_result_test.go
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer.go
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer_test.go
  projects/gloo/pkg/syncer/sanitizer/snapshot_sanitizer.go
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/utils/validation/proxy_validation.go
  projects/gloo/pkg/validation/server.go
  projects/gloo/pkg/validation/server_test.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#4498 add links to changelog version headers
  changelog/v1.8.0-beta1/changelog-link-releases.yaml
  docs/cmd/changelogutils/changelog_utils.go
  docs/cmd/generate_docs.go
Labels: keep pr updated

#4496 Helm support tracing on default gateway
  changelog/v1.8.0-beta1/tracing-provider-helm.yaml
  docs/content/operations/upgrading/1.7.0.md
  install/helm/gloo/templates/8-default-gateways.yaml
  install/test/helm_test.go
  install/test/values/val_tracing_provider_cluster.yaml
Labels: keep pr updated

#4509 Expose API for OIDC JWKS Cache Refresh Policy
  changelog/v1.8.0-beta1/jwks-cache-refresh-policy.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4511 Expose API for OIDC JWKS Cache Refresh Policy
  changelog/v1.6.19/jwks-cache-refresh-policy.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4512 Expose API for OIDC JWKS Cache Refresh Policy
  changelog/v1.5.18/jwks-cache-refresh-policy.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4518 Fix CI Test Flake: istio inject works on gateway-pod
  changelog/v1.7.0-rc3/fix-glooctl-test-flake.yaml
  test/kube2e/glooctl/glooctl_test.go
Labels: keep pr updated

#4517 Fix CI Test Flake: istio inject works on gateway-pod
  changelog/v1.8.0-beta2/fix-glooctl-test-flake.yaml
  test/kube2e/glooctl/glooctl_test.go
Labels: keep pr updated

#4510 Expose API for OIDC JWKS Cache Refresh Policy
  changelog/v1.7.0-rc3/jwks-cache-refresh-policy.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4506 Fix uninstall --all to work with gloo fed
  changelog/v1.8.0-beta2/fix-uninstall-all.yaml
  docs/content/installation/gloo_federation.md
  projects/gloo/cli/pkg/cmd/install/uninstall.go
  projects/gloo/cli/pkg/cmd/install/uninstall_test.go
Labels: keep pr updated

#4508 Backport fix uninstall all
  changelog/v1.7.0-rc3/fix-uninstall-all.yaml
  docs/content/installation/gloo_federation.md
  projects/gloo/cli/pkg/cmd/install/uninstall.go
  projects/gloo/cli/pkg/cmd/install/uninstall_test.go
Labels: keep pr updated

#4514 Helm support tracing on default gateway
  changelog/v1.6.19/tracing-provider-helm.yaml
  install/helm/gloo/templates/8-default-gateways.yaml
  install/test/helm_test.go
  install/test/values/val_tracing_provider_cluster.yaml
Labels: keep pr updated

#4513 Helm support tracing on default gateway
  changelog/v1.7.0-rc3/tracing-provider-helm.yaml
  docs/content/operations/upgrading/1.7.0.md
  install/helm/gloo/templates/8-default-gateways.yaml
  install/test/helm_test.go
  install/test/values/val_tracing_provider_cluster.yaml
Labels: keep pr updated

#4516 Determine user ID when using OAuth2.0 token introspection
  changelog/v1.8.0-beta2/extauth-token-introspection-user-id.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4477 Modify helm values to allow chart deduplication
  changelog/v1.8.0-beta2/omitempty-checking.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/helm/gloo/templates/5-gateway-deployment.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4527 Add the user_id_attribute_name to the xDS ext auth config
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated
