Repository kgateway-dev/kgateway, pull requests merged in 2021-02, with the labels that each got.

#4214 Add more test docs
  CONTRIBUTING.md
  changelog/v1.7.0-beta13/add-more-test-docs.yaml
  test/README.md
Labels: keep pr updated

#4233 Bump skv2
  changelog/v1.7.0-beta13/bump-skv2.yaml
  go.mod
  go.sum
Labels: keep pr updated

#4234 Add docs for socket-options
  changelog/v1.7.0-beta13/socket-options-docs.yaml
  docs/content/guides/dev/configuring-socket-options.md
  docs/content/guides/integrations/aws/_index.md
Labels: Type: Docs, keep pr updated

#4193 Remove envoy v2 api config refs
  changelog/v1.7.0-beta14/update-envoy-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
  install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
  install/helm/gloo/templates/19-gloo-mtls-configmap.yaml
  install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
  install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/fixtures.go
  install/test/fixtures/envoy_config/bootstrap_extensions.yaml
  install/test/fixtures/envoy_config/static_clusters.yaml
  out.yaml
  projects/accesslogger/pkg/loggingservice/server.go
  projects/accesslogger/pkg/runner/run.go
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/plugins/als/plugin.go
  projects/gloo/pkg/plugins/extauth/filter_test.go
  test/e2e/access_log_test.go
  test/e2e/custom_auth_test.go
  test/e2e/envoyconfigs/zipkin-envoy-conf.yaml
  test/e2e/envoyconfigs/zipkin-static-cluster.yaml
  test/e2e/grpcweb_test.go
  test/e2e/happypath_test.go
  test/services/envoy.go
Labels: keep pr updated

#4186 Upstream health checks docs
  changelog/v1.7.0-beta10/update-gloo-edge-docs.yaml
  docs/content/guides/traffic_management/request_processing/upstream_health_checks/_index.md
Labels: Type: Docs

#4188 Tls inspector filter
  changelog/v1.7.0-beta15/tls_inspector_filter.yaml
  install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
  install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
  install/helm/gloo/templates/19-gloo-mtls-configmap.yaml
  install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
  install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/fixtures.go
  install/test/fixtures/envoy_config/bootstrap_extensions.yaml
  install/test/fixtures/envoy_config/static_clusters.yaml
  out.yaml
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/plugins/tcp/plugin.go
  projects/gloo/pkg/plugins/tcp/plugin_test.go
  projects/gloo/pkg/plugins/tls_inspector/plugin.go
  projects/gloo/pkg/plugins/tls_inspector/plugin_test.go
  projects/gloo/pkg/plugins/tls_inspector/tls_inspector_suite_test.go
  projects/gloo/pkg/translator/translator_test.go
  test/e2e/envoyconfigs/zipkin-envoy-conf.yaml
  test/e2e/envoyconfigs/zipkin-static-cluster.yaml
  test/e2e/gateway_test.go
  test/services/envoy.go
Labels: keep pr updated

#4242 Fix outlier detection ux
  changelog/v1.7.0-beta16/fix-ux-outlier-detection.yaml
  projects/gloo/pkg/translator/clusters.go
Labels: keep pr updated

#4247 JWT OAuth2.0 access token validation API
  changelog/v1.7.0-beta16/extauth-jwt-access-token.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4252 updated license check to analyze all gloo packages
  Makefile
  changelog/v1.7.0-beta17/fix-gpl-license-check.yaml
  docs/content/static/content/osa_included.md
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  hack/utils/oss_compliance/oss_compliance.go
Labels: keep pr updated

#4251 fix config example
  docs/content/guides/security/rate_limiting/metrics/_index.md
Labels: keep pr updated

#4261 Testrunner
  changelog/v1.7.0-beta17/testrunner.yaml
  go.mod
  go.sum
  test/kube2e/containers/testrunner/Dockerfile
Labels: keep pr updated

#4241 Regex rewrite
  changelog/v1.7.0-beta17/regex-rewrite.yaml
  docs/content/guides/traffic_management/request_processing/regex_rewrite/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/plugins/basicroute/plugin.go
  projects/gloo/pkg/plugins/basicroute/plugin_test.go
Labels: keep pr updated

#4264 only examine direct dependencies of gloo edge
  changelog/v1.7.0-beta17/gpl-license-scan-direct-deps-only.yaml
  docs/content/static/content/osa_included.md
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  hack/utils/oss_compliance/oss_compliance.go
Labels: keep pr updated

#4272 PassThrough Auth Docs
  changelog/v1.7.0-beta17/passthrough-state-docs.yaml
  docs/content/guides/security/auth/extauth/passthrough_auth/_index.md
  docs/examples/grpc-passthrough-auth/go.mod
  docs/examples/grpc-passthrough-auth/go.sum
  docs/examples/grpc-passthrough-auth/pkg/auth/v3/auth-with-state.go
Labels: keep pr updated

#4275 Docs use v1.6.7
  docs/active_versions.json
Labels: keep pr updated

#4265 upgrade docs
  changelog/v1.7.0-beta17/1-7-upgrade-docs.yaml
  docs/content/operations/upgrading/1.7.0.md
Labels: keep pr updated

#4268 add left most xff filter proto
  changelog/v1.7.0-beta17/leftmost-xff-filter.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/xff_offset/solo_xff_offset_filter.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/external/envoy/extensions/xff_offset/solo_xff_offset_filter.proto
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/external/envoy/extensions/xff_offset/solo_xff_offset_filter.pb.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/plugins/leftmost_xff_address/leftmost_xff_address_suite_test.go
  projects/gloo/pkg/plugins/leftmost_xff_address/plugin.go
  projects/gloo/pkg/plugins/leftmost_xff_address/plugin_test.go
Labels: keep pr updated

#4278 Fix docs example with FDS step skipped
  docs/content/guides/traffic_management/destination_types/discovered_upstream/_index.md
Labels: keep pr updated

#4284 rbac validating webhook ratelimitconfig docs
  docs/content/guides/gloo_federation/multicluster_rbac.md
Labels: keep pr updated

#4283 Support Global Upstream SslParameter Configuration
  changelog/v1.7.0-beta18/global-upstream-cipher-config.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#4287 Backport Support Global Upstream SslParameter Configuration
  changelog/v1.6.8/global-upstream-cipher-config.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#4281 Remove v2 server creation
  changelog/v1.7.0-beta19/remove-v2-envoy-server.yaml
  projects/gloo/pkg/xds/envoy.go
Labels: keep pr updated

#4273 Setup trivy security scanner
  .github/workflows/publish-docs.yaml
  .github/workflows/trivy-analysis.yaml
  Makefile
  changelog/v1.7.0-beta19/add-trivy-security-scan.yaml
  docs/Makefile
  docs/build-docs.sh
  docs/cmd/generate_docs.go
  docs/cmd/securityscanutils/securityscan_utils.go
  docs/cmd/test/securityscanutils/generate_securityscan_doc_suite_test.go
  docs/cmd/test/securityscanutils/generate_securityscan_doc_test.go
  docs/content/reference/security-updates/_index.md
  go.sum
  hack/utils/security_scan_report/markdown.tpl
Labels: keep pr updated

#4291 Fix semver check for security scan versions
  docs/cmd/generate_docs.go
Labels: keep pr updated

#4294 Fix image ref name parsing in trivy scanner workflow
  .github/workflows/trivy-analysis.yaml
  changelog/v1.7.0-beta20/fix-image-ref-parsing.yaml
Labels: keep pr updated

#4312 Fix image name for trivy workflow
  .github/workflows/trivy-analysis.yaml
  changelog/v1.7.0-beta21/fix-version-name-trivy-scanner.yaml
Labels: keep pr updated

#4309 Fix Updating Homebrew in CI
  changelog/v1.7.0-beta21/fix-homebrew-ci.yaml
  ci/upload_github_release_assets.go
Labels: keep pr updated

#4307 GitHub workflow
  .github/workflows/update-solo-apis.yaml
  changelog/v1.7.0-beta21/update-solo-apis.yaml
Labels: keep pr updated

#4305 add imagePullSecret on k8s jobs
  changelog/v1.7.0-beta21/add-imagepullsecret-in-jobs.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
Labels: keep pr updated

#4314 Create test assets on every PR
  Makefile
  changelog/v1.7.0-beta21/create-test-assets.yaml
  cloudbuild.yaml
  test/make/make_suite_test.go
  test/make/make_test.go
Labels: keep pr updated

#4326 fix extauth_custom_ca doc link
  docs/content/guides/security/auth/extauth/oauth/dex/_index.md
  docs/content/installation/advanced_configuration/extauth_custom_ca.md
Labels: Type: Docs, keep pr updated

#4332 Fix helm gateway proxy merge
  changelog/v1.7.0-beta21/fix-helm-gateway-proxies-deep-merge.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/8-default-gateways.yaml
  install/helm/gloo/templates/8-gateway-proxy-horizontal-pod-autoscaler.yaml
  install/helm/gloo/templates/8-gateway-proxy-pod-disruption-budget.yaml
  install/helm/gloo/templates/8-gateway-proxy-service.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/helm_suite_test.go
Labels: keep pr updated

#4334 quick docs update
  docs/content/introduction/gloo_federation.md
Labels: keep pr updated

#4335 Add tests for helm changes
  changelog/v1.7.0-beta21/add-helm-gateway-proxy-tests.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4337 Add explanation of when OAuth cookieSettings.domain matters in AuthConfig
  docs/content/guides/security/auth/extauth/oauth/_index.md
Labels: Type: Docs, keep pr updated

#4328 Update gloo-fed install license
  changelog/v1.7.0-beta21/update-gloo-fed-license-validation.yaml
  docs/content/installation/gloo_federation.md
  projects/gloo/cli/pkg/cmd/demo/federation.go
  projects/gloo/cli/pkg/cmd/install/federation.go
  projects/gloo/cli/pkg/cmd/install/installer.go
  projects/gloo/cli/pkg/cmd/install/installer_test.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/options/options.go
  projects/gloo/cli/pkg/flagutils/install.go
  projects/gloo/cli/pkg/prerun/version_warning.go
Labels: keep pr updated

#4338 One way TLS Supports Global SslParameters
  changelog/v1.7.0-beta22/one-way-tls-params.yaml
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
  projects/gloo/pkg/plugins/azure/plugin.go
  projects/gloo/pkg/plugins/azure/plugin_test.go
  projects/gloo/pkg/plugins/static/plugin.go
  projects/gloo/pkg/plugins/static/plugin_test.go
  projects/gloo/pkg/utils/mocks/mock_ssl.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
  projects/gloo/pkg/utils/upstream.go
Labels: keep pr updated

#4346 Revert "Remove v2 server creation (#4281)"
  changelog/v1.7.0-beta19/remove-v2-envoy-server.yaml
  projects/gloo/pkg/xds/envoy.go
Labels: keep pr updated

#4347 Changelog Placeholder to Enable Release
  changelog/v1.7.0-beta23/revert-remove-v2-envoy-server.yaml
Labels: keep pr updated

#4355 Passthrough auth custom config
  changelog/v1.7.0-beta24/passthrough-auth-custom-config.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated
