Repository kgateway-dev/kgateway, pull requests merged in 2021-04, with the labels that each got.

#4515 Less noisy eds logs
  changelog/v1.8.0-beta3/less-noisy-k8s-eds-logging.yaml
  projects/clusteringress/pkg/api/custom/knative/cache.go
  projects/gloo/pkg/plugins/kubernetes/client.go
  projects/gloo/pkg/plugins/kubernetes/eds.go
  projects/gloo/pkg/translator/translator.go
  projects/knative/pkg/api/custom/knative/cache.go
Labels: keep pr updated

#4530 Backport oauth introspection change
  changelog/v1.7.0-rc3/extauth-token-introspection-user-id.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4531 Less noisy eds logs 1.7
  changelog/v1.7.0-rc3/less-noisy-k8s-eds-logging.yaml
  projects/clusteringress/pkg/api/custom/knative/cache.go
  projects/gloo/pkg/plugins/kubernetes/client.go
  projects/gloo/pkg/plugins/kubernetes/eds.go
  projects/gloo/pkg/translator/translator.go
  projects/knative/pkg/api/custom/knative/cache.go
Labels: keep pr updated

#4532 Fix allow warnings
  changelog/v1.8.0-beta3/fix-allow-warnings.yaml
  projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#4534 Fix allow warnings 1.7.0
  changelog/v1.7.0/extauth-token-introspection-user-id.yaml
  changelog/v1.7.0/fix-allow-warnings.yaml
  changelog/v1.7.0/fix-glooctl-test-flake.yaml
  changelog/v1.7.0/fix-uninstall-all.yaml
  changelog/v1.7.0/jwks-cache-refresh-policy.yaml
  changelog/v1.7.0/less-noisy-k8s-eds-logging.yaml
  changelog/v1.7.0/tracing-provider-helm.yaml
  projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#4541 Update docs
  docs/active_versions.json
Labels: keep pr updated

#4540 Deduplicate helm image values.
  changelog/v1.8.0-beta3/helm-image-reductions.yaml
  install/helm/gloo/generate.go
  install/helm/gloo/generate/values.go
  install/test/helm_test.go
  projects/gloo/cli/pkg/cmd/version/clients.go
Labels: keep pr updated

#4552 Helm merging fix
  changelog/v1.7.1/multiple-gateway-helm-rendering.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/8-default-gateways.yaml
  install/helm/gloo/templates/8-gateway-proxy-horizontal-pod-autoscaler.yaml
  install/helm/gloo/templates/8-gateway-proxy-pod-disruption-budget.yaml
  install/helm/gloo/templates/8-gateway-proxy-service.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4553 Fix gateways helmchart
  changelog/v1.8.0-beta4/fix-gateway-options.yaml
  install/helm/gloo/templates/8-default-gateways.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4546 Update Google Oauth guide
  docs/content/guides/security/auth/extauth/oauth/google/_index.md
Labels: keep pr updated

#4554 correct-enterprise-version
  Makefile
  changelog/v1.8.0-beta4/glooctl-enterprise-version-fix.yaml
  cloudbuild.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  pkg/version/enterprise.go
  pkg/version/federation.go
  projects/envoyinit/cmd/utils/filter_types.gen.go
  projects/gloo/cli/pkg/cmd/add/root_test.go
  projects/gloo/cli/pkg/cmd/create/output_format_test.go
  projects/gloo/cli/pkg/cmd/create/secret/extauth_apikey_test.go
  projects/gloo/cli/pkg/cmd/create/secret/extauth_oauth_test.go
  projects/gloo/cli/pkg/cmd/create/secret/secret_test.go
  projects/gloo/cli/pkg/cmd/create/upstream_test.go
  projects/gloo/cli/pkg/cmd/create/upstreamgroup_test.go
  projects/gloo/cli/pkg/cmd/create/virtualservice_glooe_test.go
  projects/gloo/cli/pkg/cmd/create/virtualservice_test.go
  projects/gloo/cli/pkg/cmd/get/output_format_test.go
  projects/gloo/cli/pkg/cmd/get/root_test.go
  projects/gloo/cli/pkg/cmd/get/route_table_test.go
  projects/gloo/cli/pkg/cmd/get/virtualservice_test.go
  projects/gloo/cli/pkg/cmd/install/install_suite_test.go
  projects/gloo/cli/pkg/cmd/version/version_test.go
Labels: keep pr updated

#4562 Correct enterprise version backport v1.7.x
  Makefile
  changelog/v1.7.1/glooctl-enterprise-version-fix.yaml
  cloudbuild.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  pkg/version/enterprise.go
  pkg/version/federation.go
  projects/envoyinit/cmd/utils/filter_types.gen.go
  projects/gloo/cli/pkg/cmd/add/root_test.go
  projects/gloo/cli/pkg/cmd/create/output_format_test.go
  projects/gloo/cli/pkg/cmd/create/secret/extauth_apikey_test.go
  projects/gloo/cli/pkg/cmd/create/secret/extauth_oauth_test.go
  projects/gloo/cli/pkg/cmd/create/secret/secret_test.go
  projects/gloo/cli/pkg/cmd/create/upstream_test.go
  projects/gloo/cli/pkg/cmd/create/upstreamgroup_test.go
  projects/gloo/cli/pkg/cmd/create/virtualservice_glooe_test.go
  projects/gloo/cli/pkg/cmd/create/virtualservice_test.go
  projects/gloo/cli/pkg/cmd/get/output_format_test.go
  projects/gloo/cli/pkg/cmd/get/root_test.go
  projects/gloo/cli/pkg/cmd/get/route_table_test.go
  projects/gloo/cli/pkg/cmd/get/virtualservice_test.go
  projects/gloo/cli/pkg/cmd/install/install_suite_test.go
  projects/gloo/cli/pkg/cmd/version/version_test.go
Labels: keep pr updated

#4557 Fix gateways helmchart (#4553)
  changelog/v1.7.1/fix-gateway-options.yaml
  install/helm/gloo/templates/8-default-gateways.yaml
  install/test/helm_test.go
Labels: keep pr updated

#4550 Doc/broken link invalid route replacement
  changelog/v1.8.0-beta4/doc-broken-link-invalid-route-repl.yaml
  docs/content/operations/production_deployment/_index.md
Labels: keep pr updated

#4567 fix-release-build
  changelog/v1.8.0-beta4/fix-release-build.yaml
  cloudbuild.yaml
Labels: keep pr updated

#4569 cherry pick
  changelog/v1.7.1/fix-release-build.yaml
  cloudbuild.yaml
Labels: keep pr updated

#4570 cherry pick
  changelog/v1.6.21/fix-release-build.yaml
  cloudbuild.yaml
Labels: keep pr updated

#4563 Fix consul DNS resolution error handling
  changelog/v1.8.0-beta5/fix-consul-dns-resolution-error-handling.yaml
  projects/gloo/pkg/plugins/consul/eds.go
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/plugins/consul/plugin.go
Labels: keep pr updated

#4558 Trivy scan on pr
  .github/workflows/trivy-analysis-release.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.8.0-beta5/run-scheduled-trivy-scan.yaml
Labels: keep pr updated

#4577 alpine 3.13.4
  Makefile
  changelog/v1.8.0-beta5/upgrade-alpine.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#4581 Alpine backport
  Makefile
  changelog/v1.7.1/upgrade-alpine.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#4580 Fix glooctl check secrets throttling
  changelog/v1.8.0-beta6/fix-glooctl-secrets-throttling.yaml
  projects/gloo/cli/pkg/helpers/clients.go
Labels: keep pr updated

#4583 Backport glooctl fix
  changelog/v1.7.2/fix-glooctl-secrets-throttling.yaml
  projects/gloo/cli/pkg/helpers/clients.go
Labels: keep pr updated

#4587 Add failover DNS polling to gloo settings
  changelog/v1.8.0-beta7/accept-api-emitter-channel.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  go.sum
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
Labels: keep pr updated

#4590 Docs: cleanup ext-auth links
  docs/content/guides/security/auth/extauth/apikey_auth/_index.md
  docs/content/guides/security/auth/extauth/basic_auth/_index.md
  docs/content/guides/security/auth/extauth/opa/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/_index.md
Labels: keep pr updated

#4601 Always run testspace, even on failures
  .github/workflows/regression-tests.yaml
Labels: keep pr updated

#4605 Bump envoy 1.6
  Makefile
  changelog/v1.6.22/bump-envoy.yaml
Labels: keep pr updated

#4604 Bump envoy 1.18
  Makefile
  changelog/v1.8.0-beta8/bump-envoy.yaml
Labels: keep pr updated

#4606 Bump envoy 1.5
  Makefile
  changelog/v1.5.19/bump-envoy.yaml
  cloudbuild.yaml
  pkg/version/enterprise.go
  pkg/version/federation.go
  projects/gloo/cli/pkg/cmd/add/root_test.go
  projects/gloo/cli/pkg/cmd/create/output_format_test.go
  projects/gloo/cli/pkg/cmd/create/secret/extauth_apikey_test.go
  projects/gloo/cli/pkg/cmd/create/secret/extauth_oauth_test.go
  projects/gloo/cli/pkg/cmd/create/secret/secret_test.go
  projects/gloo/cli/pkg/cmd/create/upstream_test.go
  projects/gloo/cli/pkg/cmd/create/upstreamgroup_test.go
  projects/gloo/cli/pkg/cmd/create/virtualservice_glooe_test.go
  projects/gloo/cli/pkg/cmd/create/virtualservice_test.go
  projects/gloo/cli/pkg/cmd/get/output_format_test.go
  projects/gloo/cli/pkg/cmd/get/root_test.go
  projects/gloo/cli/pkg/cmd/get/route_table_test.go
  projects/gloo/cli/pkg/cmd/get/virtualservice_test.go
  projects/gloo/cli/pkg/cmd/install/install_suite_test.go
  projects/gloo/cli/pkg/cmd/install/install_test.go
  projects/gloo/cli/pkg/cmd/version/version_test.go
Labels: keep pr updated

#4163 Inherit transformations from parent routes (vhost → route tables → routes)
  changelog/v1.8.0-beta9/merge-staged-transformations.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
  projects/gateway/api/v1/virtual_service.proto
  projects/gateway/pkg/api/v1/virtual_service.pb.equal.go
  projects/gateway/pkg/api/v1/virtual_service.pb.go
  projects/gateway/pkg/api/v1/virtual_service.pb.hash.go
  projects/gateway/pkg/translator/converter.go
  projects/gateway/pkg/translator/converter_test.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  test/e2e/staged_transformation_test.go
Labels: keep pr updated

#4617 Add notice to wasm docs
  changelog/v1.8.0-beta9/wasm-sdk-bump-doc-notice.yaml
  docs/content/installation/advanced_configuration/wasm.md
Labels: keep pr updated

#4619 refactored inheritable transfomrations api
  changelog/v1.8.0-beta9/inherit-transformations.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/transformation/transformation.proto.sk.md
  projects/gateway/api/v1/virtual_service.proto
  projects/gateway/pkg/api/v1/virtual_service.pb.equal.go
  projects/gateway/pkg/api/v1/virtual_service.pb.go
  projects/gateway/pkg/api/v1/virtual_service.pb.hash.go
  projects/gateway/pkg/translator/converter.go
  projects/gateway/pkg/translator/converter_test.go
  projects/gloo/api/v1/options/transformation/transformation.proto
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.hash.go
Labels: keep pr updated

#4625 backport: Helm - Make webhook more configurable #4610
  changelog/v1.7.3/webhook-helm.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  install/helm/gloo/values-template.yaml
Labels: keep pr updated

#4611 Refresh Okta OIDC docs with current images and new content
  docs/content/guides/security/auth/extauth/oauth/okta/_index.md
  docs/content/guides/security/auth/extauth/oauth/okta/okta-dashboard.png
  docs/content/img/glootest-access-denied.png
  docs/content/img/glootest-get-1.png
  docs/content/img/glootest-get-2.png
  docs/content/img/glootest-get-3.png
  docs/content/img/httpbin-base64.png
  docs/content/img/jwt-claims-decoded.png
  docs/content/img/okta-app-assignments.png
  docs/content/img/okta-app-profile.png
  docs/content/img/okta-create-new-app-integration.png
  docs/content/img/okta-dashboard.png
  docs/content/img/okta-jwt-request.png
  docs/content/img/okta-session-cookie.png
  docs/content/img/okta-sign-in.png
  docs/content/img/okta-user-list.png
Labels: Type: Docs

#4635 Fix Dex OIDC docs obsolete refs and clean up image locations
  docs/content/guides/security/auth/extauth/oauth/access_token/_index.md
  docs/content/guides/security/auth/extauth/oauth/dex/_index.md
  docs/content/guides/security/auth/extauth/opa/_index.md
  docs/content/img/dex-login.png
  docs/content/img/petclinic-home.png
Labels: Type: Docs, keep pr updated

#4626 Configurable max grpc message size (gateway → gloo) for proxy validation.
  changelog/v1.8.0-beta9/configurable-max-grpc-message-size-validation.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
Labels: keep pr updated

#4641 Backport proxy validation maxmsgsize v1.7.x
  changelog/v1.7.3/configurable-max-grpc-message-size-validation.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  go.sum
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
Labels: keep pr updated

#4643 Backport 1.6 proxy validation maxmsgsize
  changelog/v1.6.23/configurable-max-grpc-message-size-validation.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  go.sum
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/syncer/setup_syncer.go
Labels: keep pr updated

#4649 configurable query params for OIDC token endpoints: PKCE
  changelog/v1.8.0-beta9/pkce-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4651 bump envoy with singleton fix
  Makefile
  changelog/v1.6.23/bump-envoy-singleton-fix.yaml
Labels: keep pr updated

#4650 Bump envoy 1.19
  Makefile
  changelog/v1.8.0-beta10/bump-envoy-19.yaml
Labels: keep pr updated

#4585 Xslt transformer api
  changelog/v1.8.0-beta10/xslt-transformer-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformers/xslt/xslt_transformer.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/transformation/transformation.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gateway/pkg/translator/converter_test.go
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/api/external/envoy/extensions/transformers/xslt/xslt_transformer.proto
  projects/gloo/api/v1/options/transformation/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.hash.go
  projects/gloo/pkg/api/external/envoy/extensions/transformers/xslt/xslt_transformer.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/xslt/xslt.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/xslt/xslt.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/xslt/xslt.pb.hash.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.hash.go
  projects/gloo/pkg/api/v1/transformation.pb.equal.go
  projects/gloo/pkg/api/v1/transformation.pb.go
  projects/gloo/pkg/api/v1/transformation.pb.hash.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/transformation/plugin_test.go
  test/e2e/route_transformation_test.go
  test/e2e/staged_transformation_test.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#4654 Fix security update docs for glooee
  changelog/v1.8.0-beta11/fix-scan-docs-missing-image.yaml
  docs/cmd/securityscanutils/securityscan_utils.go
Labels: keep pr updated

#4660 Fix: Istio mTLS not working in permissive mode (1.5)
  changelog/v1.5.20/fix-istio-mtls-sds-alpn.yaml
  projects/gloo/pkg/utils/ssl.go
Labels: keep pr updated

#4659 Fix: Istio mTLS not working in permissive mode (1.6)
  changelog/v1.6.24/fix-istio-mtls-sds-alpn.yaml
  projects/gloo/pkg/utils/ssl.go
Labels: keep pr updated

#4658 Fix: Istio mTLS not working in permissive mode (1.7)
  changelog/v1.7.3/fix-istio-mtls-sds-alpn.yaml
  projects/gloo/pkg/utils/ssl.go
Labels: keep pr updated

#4664 configurable query params for OIDC token endpoints: PKCE ; server-side config
  changelog/v1.8.0-beta11/oidc-token-endpoint-query-params-server-config.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#4670 Docs for AWS Load Balancer setup
  changelog/v1.8.0-beta12/add-tls-termination-lb-docs.yaml
  docs/content/guides/integrations/aws/_index.md
Labels: keep pr updated

#4676 Update Transformation Docs
  docs/content/guides/dev/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/img/transformation_stages.png
Labels: keep pr updated

#4683 Remove helm2 references from 1.8 docs
  changelog/v1.8.0-beta12/docs-remove-helm2.yaml
  docs/content/guides/observability/prometheus/metrics.md
  docs/content/installation/advanced_configuration/gloo-readonly-ui.md
  docs/content/installation/advanced_configuration/multiple-gloo-installs.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/operations/upgrading/upgrade_steps.md
Labels: keep pr updated

#4679 Fix helm2
  changelog/v1.7.3/fix-helm2.yaml
  docs/content/installation/advanced_configuration/gloo-readonly-ui.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/8-default-gateways.yaml
  install/helm/gloo/templates/8-gateway-proxy-horizontal-pod-autoscaler.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/helm/gloo/values-template.yaml
Labels: keep pr updated

#4688 Fix a couple small issues in docs rendering
  docs/content/installation/advanced_configuration/multiple-gloo-installs.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/glooctl_setup.md
Labels: keep pr updated

#4686 Clean up helm2 code
  Makefile
  changelog/v1.8.0-beta12/remove-helm2-code.yaml
  docs/content/operations/upgrading/faq.md
  docs/content/reference/helm_chart_values.md
  docs/content/reference/values.txt
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/100-crds.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  install/test/merge_ingress_values.yaml
  projects/gloo/cli/pkg/cmd/install/installer.go
  projects/gloo/cli/pkg/cmd/install/installer_test.go
Labels: keep pr updated

#4674 Expose max_direct_response_body_size_bytes in Gloo
  changelog/v1.8.0-beta12/add-max-direct-response-body-size.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  docs/content/static/content/osa_provided.md
  docs/data/ProtoMap.yaml
  go.mod
  go.sum
  projects/envoyinit/cmd/utils/filter_types.gen.go
  projects/gateway/api/v1/gateway.proto
  projects/gateway/pkg/api/v1/gateway.pb.equal.go
  projects/gateway/pkg/api/v1/gateway.pb.go
  projects/gateway/pkg/api/v1/gateway.pb.hash.go
  projects/gateway/pkg/translator/translator.go
  projects/gateway/pkg/translator/translator_test.go
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.hash.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/xds/internal/listener.go
Labels: keep pr updated
