Repository kgateway-dev/kgateway, pull requests merged in 2022-04, with the labels that each got.

#6187 Removed references to deprecated removed references to deprecated http2ProtocolOptions (revised)
  changelog/v1.11.0-rc6/http2_protocol_options_update.yaml
  projects/gloo/pkg/plugins/protocoloptions/plugin.go
  projects/gloo/pkg/plugins/protocoloptions/plugin_test.go
Labels: keep pr updated

#6210 Doc fixes
  changelog/v1.11.0-rc6/docs-xds-relay.yaml
  docs/active_versions.json
  docs/content/operations/advanced/xds_relay/_index.md
  docs/content/operations/production_deployment/_index.md
Labels: keep pr updated

#6218 envoy: Bump to 1.21
  Makefile
  changelog/v1.11.0-rc6/bump-envoy-1.21.yaml
Labels: keep pr updated

#6217 Docs: Update version support page
  changelog/v1.11.0-rc7/docs-version-support.yaml
  docs/active_versions.json
  docs/content/reference/support.md
Labels: work in progress, keep pr updated

#6226 utils/regexutils: Re-allow nil engine types in regex.
  changelog/v1.11.0-rc7/regex-rewrite-engine.yaml
  pkg/utils/regexutils/regex.go
  pkg/utils/regexutils/regex_test.go
Labels: keep pr updated

#6230 Doc fixes 1.10.x
  changelog/v1.10.20/doc-fixes.yaml
  docs/content/operations/upgrading/1.10.0.md
Labels: keep pr updated

#6229 Doc fixes
  changelog/v1.11.0-rc7/doc-fixes.yaml
  docs/content/operations/upgrading/v0.18.md
  docs/content/operations/upgrading/v1.0.md
  docs/content/operations/upgrading/v1.10.md
  docs/content/operations/upgrading/v1.11.md
  docs/content/operations/upgrading/v1.3.md
  docs/content/operations/upgrading/v1.4.md
  docs/content/operations/upgrading/v1.5.md
  docs/content/operations/upgrading/v1.7.md
  docs/content/operations/upgrading/v1.8.md
  docs/content/operations/upgrading/v1.9.md
Labels: keep pr updated

#6236 bump containerd version
  changelog/v1.11.0-rc7/fix-cve.yaml
  go.mod
  go.sum
Labels: keep pr updated

#6231 Add README.md to .github/workflows
  .github/workflows/README.md
  changelog/v1.11.0-rc7/update-push-solo-apis-docs.yaml
Labels: keep pr updated

#6238 Update changelog for 1.11.0
  changelog/v1.11.0/doc-fixes.yaml
  changelog/v1.11.0/docs-version-support.yaml
  changelog/v1.11.0/fix-cve.yaml
  changelog/v1.11.0/graphql-alpha-to-beta.yaml
  changelog/v1.11.0/regex-rewrite-engine.yaml
  changelog/v1.11.0/update-push-solo-apis-docs.yaml
Labels: keep pr updated

#6239 Add 1.12 placeholder
  changelog/v1.12.0-beta1/placeholder.yaml
Labels: keep pr updated

#6240 Backport change to bump containerd version to v10.x
  changelog/v1.10.20/fix-cve.yaml
  go.mod
  go.sum
Labels: keep pr updated

#6242 Bump doc version
  changelog/v1.12.0-beta1/docs-version-bump.yaml
  docs/active_versions.json
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#6211 Reduce test flakes
  changelog/v1.12.0-beta1/reduce-test-flakes.yaml
  test/consulvaulte2e/consul_vault_test.go
  test/e2e/access_log_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
  test/e2e/buffer_test.go
  test/e2e/consul_test.go
  test/e2e/cors_test.go
  test/e2e/csrf_test.go
  test/e2e/custom_auth_test.go
  test/e2e/dynamic_forward_proxy_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/gateway_test.go
  test/e2e/grpc_json_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/gzip_test.go
  test/e2e/happypath_test.go
  test/e2e/health_checks_test.go
  test/e2e/http_tunneling_test.go
  test/e2e/hybrid_test.go
  test/e2e/proxy_protocol_test.go
  test/e2e/ratelimit_test.go
  test/e2e/staged_transformation_test.go
  test/e2e/zipkin_test.go
  test/helpers/default_gateways.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/util.go
  test/services/envoy.go
  test/services/gateway.go
  test/v1helpers/test_upstream.go
Labels: keep pr updated

#6249 Disabled discovery empty subjects fix
  changelog/v1.12.0-beta1/helm-fix-discovery-empty-subjects.yaml
  install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
Labels: keep pr updated

#6208 Add Custom PrecenseFilter to LDAP Auth
  changelog/v1.12.0-beta1/add-ldap-search-filter-config.yaml
  docs/content/guides/security/auth/extauth/ldap/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6252 [1.10.x] Disabled discovery empty subjects fix (#6249)
  changelog/v1.10.20/helm-fix-discovery-empty-subjects.yaml
  install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
Labels: keep pr updated

#6251 [1.11.x] Disabled discovery empty subjects fix (#6249)
  changelog/v1.11.1/helm-fix-discovery-empty-subjects.yaml
  install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
Labels: keep pr updated

#6245 Doc fixes
  .github/ISSUE_TEMPLATE/DOCS-ISSUE.yml
  changelog/v1.12.0-beta2/docs-fixes.yaml
  docs/content/guides/graphql/stitching.txt
  docs/content/guides/security/auth/extauth/oauth/_index.md
  docs/content/guides/traffic_management/configuration_validation/admission_control.md
Labels: Type: Docs, keep pr updated

#6233 Process all route plugin config in direct and redirect actions
  changelog/v1.12.0-beta2/process-route-plugins-all-actions.yaml
  projects/gloo/pkg/plugins/basicroute/plugin.go
  projects/gloo/pkg/plugins/basicroute/plugin_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6260 Resolve panic in gateway validation client
  changelog/v1.12.0-beta2/robust-client-panic.yaml
  projects/gateway/pkg/validation/robust_client.go
  projects/gateway/pkg/validation/robust_client_test.go
Labels: keep pr updated

#6263 v1.11.x: Process all route plugin config in direct and redirect actions
  changelog/v1.11.1/process-route-plugins-all-actions.yaml
  projects/gloo/pkg/plugins/basicroute/plugin.go
  projects/gloo/pkg/plugins/basicroute/plugin_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6264 v1.10.x: Process all route plugin config in direct and redirect actions
  changelog/v1.10.20/process-route-plugins-all-actions.yaml
  projects/gloo/pkg/plugins/basicroute/plugin.go
  projects/gloo/pkg/plugins/basicroute/plugin_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6265 v1.9.x: Process all route plugin config in direct and redirect actions
  changelog/v1.9.12/process-route-plugins-all-actions.yaml
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/azure/plugin.go
  projects/gloo/pkg/plugins/basicroute/plugin.go
  projects/gloo/pkg/plugins/basicroute/plugin_test.go
  projects/gloo/pkg/plugins/faultinjection/plugin.go
  projects/gloo/pkg/plugins/grpc/plugin.go
  projects/gloo/pkg/plugins/rest/rest.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6258 Increased default validation server max message size to 100 MB
  changelog/v1.12.0-beta2/increase-validation-max-size-bytes.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/enable_rest_eds_and_gloo_mtls.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/gateway_validation.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/fixtures/settings/uds_disabled.yaml
  install/test/fixtures/settings/watched_discovery_labels.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#6266 link-fix
  changelog/v1.12.0-beta2/docs-links.yaml
  docs/content/introduction/architecture/concepts.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
  projects/gateway/api/v1/virtual_service.proto
  projects/gateway/pkg/api/v1/virtual_service.pb.go
Labels: keep pr updated

#6271 Resolve consul plugin data race
  changelog/v1.12.0-beta2/consul-plugin-data-race.yaml
  projects/gloo/pkg/plugins/consul/dns_resolver.go
  projects/gloo/pkg/plugins/consul/eds.go
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/plugins/consul/plugin.go
  projects/gloo/pkg/plugins/registry/registry.go
Labels: keep pr updated

#6277 Bump doc versions and link fixes
  changelog/v1.12.0-beta2/docs-links2.yaml
  docs/active_versions.json
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n-1.md
  projects/gateway/api/v1/virtual_service.proto
  projects/gateway/pkg/api/v1/virtual_service.pb.go
Labels: Type: Docs, keep pr updated

#6254 Documentation for 'created-by' labels on proxies
  changelog/v1.12.0-beta2/proxy-labels.yaml
  docs/content/guides/dev/example-proxy-controller.md
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/ingress/pkg/translator/translator_syncer.go
Labels: keep pr updated

#6282 Resolve data race in setup syncer test
  changelog/v1.12.0-beta3/setup-syncer-data-race.yaml
  test/kube2e/gloo/setup_syncer_test.go
Labels: keep pr updated

#6278 Backporting doc fixes to 1.11.x
  changelog/v1.11.2/docs-links.yaml
  docs/content/guides/graphql/_index.md
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/guides/graphql/getting_started.md
  docs/content/guides/graphql/graphql_ui.md
  docs/content/guides/graphql/observability.md
  docs/content/guides/graphql/resolver_config.md
  docs/content/guides/graphql/stitching.txt
  docs/content/installation/glooctl_setup.md
  docs/content/introduction/architecture/concepts.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  projects/gateway/api/v1/virtual_service.proto
  projects/gateway/pkg/api/v1/virtual_service.pb.go
Labels: Type: Docs, keep pr updated

#6284 Bump the doc version
  changelog/v1.12.0-beta3/doc-bump.yaml
  docs/active_versions.json
  docs/content/static/content/version_gee_latest.md
Labels: Type: Docs, keep pr updated

#6287 Fix graphql upgrade steps
  docs/content/operations/upgrading/v1.11.md
Labels: keep pr updated

#6286 Backport to 1.10 Documentation for 'created-by' labels on proxies (#6254)
  changelog/v1.10.21/proxy-labels.yaml
  docs/content/guides/dev/example-proxy-controller.md
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/ingress/pkg/translator/translator_syncer.go
Labels: keep pr updated

#6288 Backport to 1.9 Documentation for 'created-by' labels on proxies (#6254)
  changelog/v1.9.13/proxy-labels.yaml
  docs/content/guides/dev/example-proxy-controller.md
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/ingress/pkg/translator/translator_syncer.go
Labels: keep pr updated

#6285 Backport: Documentation for 'created-by' labels on proxies (#6254)
  changelog/v1.11.3/proxy-labels.yaml
  docs/content/guides/dev/example-proxy-controller.md
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/ingress/pkg/translator/translator_syncer.go
Labels: keep pr updated

#6294 [1.11] Reduce test flakes
  changelog/v1.11.3/reduce-test-flakes.yaml
  projects/gateway/pkg/validation/robust_client.go
  projects/gateway/pkg/validation/robust_client_test.go
  projects/gloo/pkg/plugins/consul/dns_resolver.go
  projects/gloo/pkg/plugins/consul/eds.go
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/plugins/consul/plugin.go
  projects/gloo/pkg/plugins/registry/registry.go
  test/consulvaulte2e/consul_vault_test.go
  test/e2e/access_log_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
  test/e2e/buffer_test.go
  test/e2e/consul_test.go
  test/e2e/cors_test.go
  test/e2e/csrf_test.go
  test/e2e/custom_auth_test.go
  test/e2e/dynamic_forward_proxy_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/gateway_test.go
  test/e2e/grpc_json_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/gzip_test.go
  test/e2e/happypath_test.go
  test/e2e/health_checks_test.go
  test/e2e/http_tunneling_test.go
  test/e2e/hybrid_test.go
  test/e2e/proxy_protocol_test.go
  test/e2e/ratelimit_test.go
  test/e2e/staged_transformation_test.go
  test/e2e/zipkin_test.go
  test/helpers/default_gateways.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/gloo/setup_syncer_test.go
  test/kube2e/util.go
  test/services/envoy.go
  test/services/gateway.go
  test/v1helpers/test_upstream.go
Labels: keep pr updated

#6297 [1.10] Reduce test flakes
  changelog/v1.10.21/reduce-test-flakes.yaml
  projects/gateway/pkg/validation/robust_client.go
  projects/gateway/pkg/validation/robust_client_test.go
  projects/gloo/pkg/plugins/consul/dns_resolver.go
  projects/gloo/pkg/plugins/consul/eds.go
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/plugins/consul/plugin.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/syncer/setup/setup_syncer_test.go
  test/consulvaulte2e/consul_vault_test.go
  test/e2e/access_log_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
  test/e2e/buffer_test.go
  test/e2e/consul_test.go
  test/e2e/cors_test.go
  test/e2e/csrf_test.go
  test/e2e/custom_auth_test.go
  test/e2e/dynamic_forward_proxy_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/gateway_test.go
  test/e2e/grpc_json_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/gzip_test.go
  test/e2e/happypath_test.go
  test/e2e/health_checks_test.go
  test/e2e/http_tunneling_test.go
  test/e2e/hybrid_test.go
  test/e2e/proxy_protocol_test.go
  test/e2e/ratelimit_test.go
  test/e2e/staged_transformation_test.go
  test/e2e/zipkin_test.go
  test/helpers/default_gateways.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/util.go
  test/services/envoy.go
  test/services/gateway.go
  test/v1helpers/test_upstream.go
Labels: keep pr updated

#6299 Add line about draft PRs to github actions readme
  .github/workflows/README.md
Labels: keep pr updated

#6296 Sanitizers never error 1.11
  changelog/v1.11.3/sanitizers-never-error.yaml
  go.mod
  go.sum
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer.go
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer_test.go
  projects/gloo/pkg/syncer/sanitizer/snapshot_sanitizer.go
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer.go
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer_test.go
  projects/gloo/pkg/syncer/syncer_test_helper.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/utils/names.go
  projects/gloo/pkg/xds/envoy.go
  projects/gloo/pkg/xds/envoy_snapshot.go
  projects/gloo/pkg/xds/envoy_snapshot_test.go
  test/e2e/gzip_test.go
  test/e2e/hybrid_test.go
Labels: keep pr updated

#6304 Run gzip compression after transformation
  changelog/v1.12.0-beta4/gzip-early.yaml
  projects/gloo/pkg/plugins/gzip/plugin.go
  projects/gloo/pkg/plugins/gzip/plugin_test.go
Labels: keep pr updated

#6308 update gloo edge versions in issue templates
  .github/ISSUE_TEMPLATE/BUG-ISSUE.yml
  .github/ISSUE_TEMPLATE/FEATURE-ISSUE.yml
Labels: keep pr updated

#6303 Add e2e test for sanitizers never error
  changelog/v1.12.0-beta4/add-e2e-test-sanitizers.yaml
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#6309 Run gzip compression after transformation [1.11]
  changelog/v1.11.4/gzip-early.yaml
  projects/gloo/pkg/plugins/gzip/plugin.go
  projects/gloo/pkg/plugins/gzip/plugin_test.go
Labels: keep pr updated

#6306 Additional helm configurable paths to envoy stats
  changelog/v1.12.0-beta4/datadog-and-prometheus-metrics.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
  install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
  install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
  install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/helm/gloo/values-template.yaml
Labels: keep pr updated

#6283 Support custom Vault secret prefix
  changelog/v1.12.0-beta4/support-custom-vault-secret-prefix.yaml
  docs/content/installation/gateway/nomad/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/cli/glooctl_create_secret.md
  docs/content/reference/cli/glooctl_create_secret_apikey.md
  docs/content/reference/cli/glooctl_create_secret_aws.md
  docs/content/reference/cli/glooctl_create_secret_azure.md
  docs/content/reference/cli/glooctl_create_secret_header.md
  docs/content/reference/cli/glooctl_create_secret_oauth.md
  docs/content/reference/cli/glooctl_create_secret_tls.md
  go.mod
  go.sum
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/settings.proto
  projects/gloo/cli/pkg/cmd/create/secret/create_test.go
  projects/gloo/cli/pkg/cmd/options/options.go
  projects/gloo/cli/pkg/flagutils/common.go
  projects/gloo/cli/pkg/helpers/clients.go
  projects/gloo/cli/pkg/helpers/clients_test.go
  projects/gloo/cli/pkg/prerun/prerun_consul.go
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/bootstrap/utils.go
  projects/gloo/pkg/bootstrap/vault.go
  test/consulvaulte2e/consul_vault_test.go
  test/consulvaulte2e/e2e_suite_test.go
  test/services/vault.go
Labels: keep pr updated

#6323 Docs: Fix GraphQL links
  changelog/v1.12.0-beta5/docs-fix-links.yaml
  docs/content/guides/graphql/getting_started.md
Labels: keep pr updated

#6324 Backport: Docs: Fix GraphQL links 1.11.x
  changelog/v1.11.5/docs-links.yaml
  docs/content/guides/graphql/getting_started.md
Labels: keep pr updated

#6325 Backport: Docs: Fix GraphQL links 1.10.x
  changelog/v1.10.21/doc-fix-links.yaml
  docs/content/guides/graphql/getting_started.md
Labels: keep pr updated

#6312 POC: Full istio Sidecar Support
  changelog/v1.12.0-beta5/full-istio-sidecar.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/10-ingress-deployment.yaml
  install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
  install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
  install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
  install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/helm/gloo/templates/5-gateway-deployment.yaml
  install/helm/gloo/templates/6-access-logger-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6319 Add e2e tests for secret engine
  projects/gloo/cli/pkg/cmd/create/secret/create_test.go
  test/consulvaulte2e/consul_vault_test.go
  test/consulvaulte2e/e2e_suite_test.go
  test/services/vault.go
Labels: keep pr updated

#6243 Various readiness and liveness probes added
  changelog/v1.12.0-beta6/liveness.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/5-gateway-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  install/test/values/val_custom_istio_sidecar.yaml
  projects/gloo/cli/pkg/cmd/install/knative_test_yaml.yaml
  projects/sds/cmd/main.go
Labels: keep pr updated

#6339 Additional helm configurable paths to envoy stats [1.11]
  changelog/v1.11.5/datadog-and-prometheus-metrics.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
  install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
  install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
  install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/helm/gloo/values-template.yaml
Labels: keep pr updated

#6340 Additional helm configurable paths to envoy stats [1.10]
  changelog/v1.10.21/datadog-and-prometheus-metrics.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
  install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml
  install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml
  install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/helm/gloo/values-template.yaml
Labels: keep pr updated

#6338 Fixed template to correctly use envoySidecarResources for istio-proxy
  changelog/v1.12.0-beta6/fix-proxy-deployment-override.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6345 [1.11] Fixed template to correctly use envoySidecarResources for istio-proxy
  changelog/v1.11.5/fix-proxy-deployment-override.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6347 [1.9] Fixed template to correctly use envoySidecarResources for istio-proxy
  changelog/v1.9.13/fix-proxy-deployment-override.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6346 [1.10] Fixed template to correctly use envoySidecarResources for istio-proxy
  changelog/v1.10.21/fix-proxy-deployment-override.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6330 Go 1.18.1 upgrade
  .github/workflows/codegen.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  Makefile
  changelog/v1.12.0-beta6/bump-go.yaml
  cloudbuild-cache.yaml
  cloudbuild.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  go.mod
  go.sum
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/gloo/pkg/api/external/envoy/api/v2/core/health_check.pb.go
  projects/gloo/pkg/api/external/envoy/api/v2/route/route.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/base.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/extension.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/grpc_service.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/health_check.pb.go
  projects/gloo/pkg/api/external/envoy/config/route/v3/route_components.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/graphql/v2/graphql.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/wasm/v3/wasm.pb.go
  projects/gloo/pkg/api/v1/options/wasm/wasm.pb.go
  projects/ingress/cmd/Dockerfile
  projects/ingress/pkg/api/v1/ingress.pb.go
  projects/ingress/pkg/api/v1/service.pb.go
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6352 Ensure Hybrid Gateway tests have VirtualService available
  test/e2e/gateway_test.go
Labels: keep pr updated

#6344 Envoy Overload Config
  changelog/v1.12.0-beta6/envoy-overload-manager.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/envoy_config/overload_manager.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6353 [1.11] Reject gateways without gatewayType
  changelog/v1.11.6/gw-without-type.yaml
  projects/gateway/pkg/translator/listener_translator.go
  projects/gateway/pkg/translator/translator.go
  projects/gateway/pkg/translator/translator_test.go
  test/e2e/gateway_test.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#6350 Clarify JSON logging Formatting for WAF/ModSecurity
  changelog/v1.12.0-beta6/waf-json-logging-docs-update.yaml
  docs/content/guides/security/waf/_index.md
Labels: keep pr updated

#6354 [1.10] Reject gateways without gatewayType
  changelog/v1.10.22/gw-without-type.yaml
  projects/gateway/pkg/translator/listener_translator.go
  projects/gateway/pkg/translator/translator.go
  projects/gateway/pkg/translator/translator_test.go
  test/e2e/gateway_test.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#6341 Staged rate limiting: support regular stage
  changelog/v1.12.0-beta6/staged-ratelimit-part-2.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer_test.go
Labels: keep pr updated

#6357 Doc fixes
  changelog/v1.12.0-beta7/docs-fixes.yaml
  docs/content/guides/dev/_index.md
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/introduction/development.md
  docs/content/operations/upgrading/v1.11.md
Labels: keep pr updated

#6358 Doc fixes 1.11.x
  changelog/v1.11.6/doc-fixes.yaml
  docs/content/guides/dev/_index.md
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/introduction/development.md
Labels: keep pr updated

#6360 [1.11] Staged rate limiting: support regular stage
  changelog/v1.11.6/staged-ratelimit-part-2.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer_test.go
Labels: keep pr updated

#6363 doc-fixes
  docs/content/guides/security/cors/_index.md
Labels: keep pr updated

#6361 Doc version bumps
  changelog/v1.12.0-beta7/doc-versions.yaml
  docs/active_versions.json
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#6359 New GraphQL api
  changelog/v1.12.0-beta7/graphql_api_route.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1beta1/graphql.proto.sk.md
  install/helm/gloo/crds/graphql.gloo.solo.io_v1beta1_GraphQLApi.yaml
  projects/gloo/api/v1/enterprise/options/graphql/v1beta1/graphql.proto
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.hash.go
Labels: keep pr updated

#6379 CVE fix 0422
  changelog/v1.12.0-beta8/cve-patch.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#6382 CVE fix 0422 1.11
  changelog/v1.11.7/cve-patch.yaml
  docs/content/guides/security/auth/extauth/ldap/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6383 CVE fix 0422 1.10
  changelog/v1.10.22/cve-patch.yaml
  docs/content/guides/security/auth/extauth/ldap/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6385 Fix certgen upgrade
  changelog/v1.12.0-beta8/fix-certgen-upgrade.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/test/helm_test.go
  jobs/pkg/kube/secret.go
  jobs/pkg/kube/secret_test.go
  jobs/pkg/run/run.go
  test/kube2e/knative/knative_manual_tls_test.go
Labels: keep pr updated

#6387 Docs: Re-add updated graphql stitching guidance
  changelog/v1.12.0-beta9/docs-graphql-sititching.yaml
  docs/content/guides/graphql/getting_started.md
  docs/content/guides/graphql/resolver_config.md
  docs/content/guides/graphql/stitching.md
  docs/content/guides/graphql/stitching.txt
Labels: keep pr updated

#6390 fix translator syncer test flake
  changelog/v1.12.0-beta9/fix-translator-syncer-flake.yaml
  projects/gateway/pkg/syncer/translator_syncer_test.go
Labels: keep pr updated

#6392 Back/samesite 1.10
  changelog/v1.10.23/add-samesite.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6393 Test flake fixes
  changelog/v1.12.0-beta9/staged-transformation-flake.yaml
  test/e2e/staged_transformation_test.go
Labels: keep pr updated
