Repository kgateway-dev/kgateway, pull requests merged in 2022-10, with the labels that each got.

#7276 [1.12] Move status updates to their own goroutine
  changelog/v1.12.27/goroutine-status.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/disabled_gateway.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/enable_rest_eds_and_gloo_mtls.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/gateway_validation.yaml
  install/test/fixtures/settings/isolate_virtual_hosts_by_ssl_config.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/fixtures/settings/uds_disabled.yaml
  install/test/fixtures/settings/watched_discovery_labels.yaml
  install/test/helm_test.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/transformation/plugin_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/translator/translator.go
Labels: keep pr updated

#7277 Move status updates to their own goroutine
  changelog/v1.13.0-beta20/goroutine-status.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/disabled_gateway.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/enable_rest_eds_and_gloo_mtls.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/gateway_validation.yaml
  install/test/fixtures/settings/isolate_virtual_hosts_by_ssl_config.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/fixtures/settings/uds_disabled.yaml
  install/test/fixtures/settings/watched_discovery_labels.yaml
  install/test/helm_test.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/transformation/plugin_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/translator/translator.go
Labels: keep pr updated

#7151 Update Statuses on Election Changes
  Makefile
  changelog/v1.13.0-beta20/ha-startup-action.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  pkg/bootstrap/leaderelector/identity.go
  pkg/bootstrap/leaderelector/identity_test.go
  pkg/bootstrap/leaderelector/kube/factory.go
  pkg/bootstrap/leaderelector/leader.go
  pkg/bootstrap/leaderelector/leader_test.go
  pkg/bootstrap/leaderelector/leaderelector_suite_test.go
  pkg/bootstrap/leaderelector/singlereplica/factory.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/api/v1/enterprise/verify.go
  projects/gloo/pkg/syncer/translator_syncer.go
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#7279 [1.12] Update Statuses on Election Changes
  Makefile
  changelog/v1.12.28/ha-startup-action.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  pkg/bootstrap/leaderelector/identity.go
  pkg/bootstrap/leaderelector/identity_test.go
  pkg/bootstrap/leaderelector/kube/factory.go
  pkg/bootstrap/leaderelector/leader.go
  pkg/bootstrap/leaderelector/leader_test.go
  pkg/bootstrap/leaderelector/leaderelector_suite_test.go
  pkg/bootstrap/leaderelector/singlereplica/factory.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/api/v1/enterprise/verify.go
  projects/gloo/pkg/syncer/translator_syncer.go
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#7282 12 | helm: standardized *Image as the default data type
  changelog/v1.12.28/helm-tweak.yaml
  install/helm/gloo/generate/values.go
Labels: keep pr updated

#7283 helm: standardized *Image as the default data type
  changelog/v1.11.39/helm-tweak.yaml
  install/helm/gloo/generate/values.go
Labels: keep pr updated

#7285 3957 dlp performance
  changelog/v1.13.0-beta21/all-credit-cards-dlp-regex.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/dlp/dlp.proto.sk.md
  projects/gloo/api/v1/enterprise/options/dlp/dlp.proto
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.go
Labels: keep pr updated

#7287 v1.12.x: Backport #7255 to add support for base64, substring Inja functions
  Makefile
  changelog/v1.12.29/base64_transformation_functions.yaml
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/decode_and_modify_base64_headers/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  docs/content/static/content/setup_postman_echo.md
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
  test/e2e/staged_transformation_test.go
Labels: keep pr updated

#7294 Fix upstream bulk backport
  changelog/v1.12.29/upstream-load.yaml
  projects/gloo/pkg/upstreams/hybrid_client.go
  projects/gloo/pkg/upstreams/hybrid_client_test.go
Labels: keep pr updated

#7292 fix: upstream processing priority for bulk updates
  changelog/v1.13.0-beta22/upstream-load.yaml
  projects/gloo/pkg/upstreams/hybrid_client.go
  projects/gloo/pkg/upstreams/hybrid_client_test.go
Labels: keep pr updated

#7296 v1.11.x: Backport #7255 to add support for base64, substring Inja functions
  Makefile
  changelog/v1.11.40/base64_transformation_functions.yaml
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/decode_and_modify_base64_headers/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  docs/content/static/content/setup_postman_echo.md
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
  test/e2e/staged_transformation_test.go
Labels: keep pr updated

#7295 Add missing guide to documentation
  changelog/v1.13.0-beta22/developer-documentation.yaml
  docs/content/guides/dev/building-and-deploying-gloo.md
Labels: Type: Docs, keep pr updated

#7306 Doc fixes
  changelog/v1.13.0-beta22/doc-fixes.yaml
  docs/active_versions.json
  docs/content/guides/dev/building-and-deploying-gloo.md
  docs/content/guides/dev/plugins.proto
  docs/content/guides/dev/writing-upstream-plugins.md
  docs/content/guides/dev/writing_auth_plugins/_index.md
  docs/content/guides/traffic_management/destination_selection/header_matching/_index.md
  docs/content/guides/traffic_management/listener_configuration/http_connection_manager/_index.md
  docs/content/guides/traffic_management/request_processing/prefix_rewrite/_index.md
  docs/content/installation/advanced_configuration/session_affinity.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/lbhash/lbhash.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/shadowing/shadowing.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  projects/gateway/api/v1/gateway.proto
  projects/gateway/pkg/api/v1/gateway.pb.go
  projects/gloo/api/v1/connection.proto
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/api/v1/options/lbhash/lbhash.proto
  projects/gloo/api/v1/options/shadowing/shadowing.proto
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/connection.pb.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/lbhash/lbhash.pb.go
  projects/gloo/pkg/api/v1/options/shadowing/shadowing.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/plugins/listener/plugin.go
Labels: Type: Docs, keep pr updated

#7312 Added `make help` target
  Makefile
  changelog/v1.13.0-beta22/ci-stability.yaml
Labels: keep pr updated

#7314 Doc updates - passthrough metrics, and chaining description
  changelog/v1.13.0-beta22/update-docs-to-include-failureModeAllow.yaml
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#7310 Passthrough failure mode allow 1.12 backport
  changelog/v1.12.30/passthrough-auth-failure-mode-allow.yaml
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#7328 fix(digest): enable fips digest encoding
  changelog/v1.13.0-beta23/fips-digest-fix.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/_helpers.tpl
Labels: keep pr updated

#7334 12/fips digest
  changelog/v1.12.31/fips-digest-fix.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/_helpers.tpl
Labels: keep pr updated

#7335 11/fips digest
  changelog/v1.11.41/fips-digest-fix.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/_helpers.tpl
Labels: keep pr updated

#7216 Waf dynamic load
  changelog/v1.13.0-beta24/waf-dynamic-load-configmap.yaml
  docs/content/guides/security/waf/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/waf/waf.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/waf/waf.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  projects/gloo/api/external/envoy/extensions/waf/waf.proto
  projects/gloo/api/v1/enterprise/options/waf/waf.proto
  projects/gloo/pkg/api/external/envoy/extensions/waf/waf.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/waf/waf.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/waf/waf.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/waf/waf.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/waf/waf.pb.hash.go
Labels: keep pr updated

#7341 V1.12.x doc fixes
  changelog/v1.12.32/doc-fixes.yaml
  docs/active_versions.json
  docs/content/guides/dev/building-and-deploying-gloo.md
  docs/content/guides/dev/plugins.proto
  docs/content/guides/dev/writing-upstream-plugins.md
  docs/content/guides/dev/writing_auth_plugins/_index.md
  docs/content/guides/traffic_management/destination_selection/header_matching/_index.md
  docs/content/guides/traffic_management/listener_configuration/http_connection_manager/_index.md
  docs/content/guides/traffic_management/request_processing/prefix_rewrite/_index.md
  docs/content/img/favicon.ico
  docs/content/installation/advanced_configuration/session_affinity.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/lbhash/lbhash.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/shadowing/shadowing.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  projects/gateway/api/v1/gateway.proto
  projects/gateway/pkg/api/v1/gateway.pb.go
  projects/gloo/api/v1/connection.proto
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/api/v1/options/lbhash/lbhash.proto
  projects/gloo/api/v1/options/shadowing/shadowing.proto
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/connection.pb.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/lbhash/lbhash.pb.go
  projects/gloo/pkg/api/v1/options/shadowing/shadowing.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/plugins/listener/plugin.go
Labels: keep pr updated

#7347 V1.11.x: Status reporting Scale Fixes
  changelog/v1.11.42/status_reporting_scale_fixes.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  go.mod
  go.sum
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
  install/helm/gloo/crds/graphql.gloo.solo.io_v1beta1_GraphQLApi.yaml
  install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
  install/test/rbac_test.go
  install/test/util.go
  projects/clusteringress/pkg/api/custom/knative/knative_clusteringress_client.go
  projects/clusteringress/pkg/api/v1/translator_event_loop.sk.go
  projects/clusteringress/pkg/api/v1/translator_simple_event_loop.sk.go
  projects/gateway/pkg/api/v1/api_event_loop.sk.go
  projects/gateway/pkg/api/v1/api_simple_event_loop.sk.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/external/solo/ratelimit/extensions.go
  projects/gloo/pkg/api/v1/discovery_event_loop.sk.go
  projects/gloo/pkg/api/v1/discovery_simple_event_loop.sk.go
  projects/gloo/pkg/api/v1/eds_event_loop.sk.go
  projects/gloo/pkg/api/v1/eds_simple_event_loop.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_event_loop.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_simple_event_loop.sk.go
  projects/gloo/pkg/api/v1/gloosnapshot/api_event_loop.sk.go
  projects/gloo/pkg/api/v1/gloosnapshot/api_simple_event_loop.sk.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/setup_event_loop.sk.go
  projects/gloo/pkg/api/v1/setup_simple_event_loop.sk.go
  projects/gloo/pkg/bootstrap/utils.go
  projects/gloo/pkg/syncer/extauth/extauth_translator_syncer.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/upstreams/base_client.go
  projects/gloo/pkg/upstreams/hybrid_client.go
  projects/ingress/pkg/api/ingress/resource_client.go
  projects/ingress/pkg/api/service/resource_client.go
  projects/ingress/pkg/api/v1/status_event_loop.sk.go
  projects/ingress/pkg/api/v1/status_simple_event_loop.sk.go
  projects/ingress/pkg/api/v1/translator_event_loop.sk.go
  projects/ingress/pkg/api/v1/translator_simple_event_loop.sk.go
  projects/knative/pkg/api/custom/knative/knative_clusteringress_client.go
  projects/knative/pkg/api/v1/translator_event_loop.sk.go
  projects/knative/pkg/api/v1/translator_simple_event_loop.sk.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#7370 [1.12] Allow disabling leader election explicitly
  changelog/v1.12.32/placeholder.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  pkg/bootstrap/leaderelector/election_factory.go
  pkg/utils/setuputils/main_setup.go
  projects/gloo/pkg/setup/setup.go
Labels: keep pr updated

#7322 fix(Upstream): allow use_downstream_protocol when useHttp2 is set
  changelog/v1.13.0-beta25/7096-downstream-protocol.yaml
  projects/gloo/pkg/plugins/protocoloptions/plugin.go
  projects/gloo/pkg/plugins/protocoloptions/plugin_test.go
  projects/gloo/pkg/plugins/upstreamconn/plugin.go
  projects/gloo/pkg/plugins/utils/httpprotocolhelpers/http1_utils.go
Labels: keep pr updated

#7372 fix(Upstream): allow use_downstream_protocol when useHttp2 is set
  changelog/v1.12.32/7096-downstream-protocol.yaml
  projects/gloo/pkg/plugins/protocoloptions/plugin.go
  projects/gloo/pkg/plugins/protocoloptions/plugin_test.go
  projects/gloo/pkg/plugins/upstreamconn/plugin.go
  projects/gloo/pkg/plugins/utils/httpprotocolhelpers/http1_utils.go
Labels: keep pr updated

#7289 Add ldap service account to API
  changelog/v1.13.0-beta25/extauth-api-update.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/secret.proto.sk.md
  docs/content/reference/cli/glooctl_create_secret.md
  docs/content/reference/cli/glooctl_create_secret_authcredentials.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  pkg/utils/syncutil/log_redactor_test.go
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/api/v1/secret.proto
  projects/gloo/cli/pkg/cmd/create/secret/extauth_credentials.go
  projects/gloo/cli/pkg/cmd/create/secret/extauth_credentials_test.go
  projects/gloo/cli/pkg/cmd/create/secret/root.go
  projects/gloo/pkg/api/converters/kube/account_credentials_secret.go
  projects/gloo/pkg/api/converters/kube/account_credentials_secret_test.go
  projects/gloo/pkg/api/converters/kube/secretconverter.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
  projects/gloo/pkg/api/v1/secret.pb.clone.go
  projects/gloo/pkg/api/v1/secret.pb.equal.go
  projects/gloo/pkg/api/v1/secret.pb.go
  projects/gloo/pkg/api/v1/secret.pb.hash.go
Labels: work in progress, keep pr updated

#7373 [1.12] Deflake hybrid gateway e2e test
  test/e2e/gateway_test.go
Labels: keep pr updated

#7365 V1.12.x: bump golang.org/x/text to v0.4.0 to resolve CVEs
  changelog/v1.12.32/backports-batch.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#7368 [1.12] Backport Recent Fixes
  changelog/v1.12.32/backports-batch.yaml
  docs/content/reference/values.txt
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  pkg/bootstrap/leaderelector/election_factory.go
  pkg/utils/setuputils/main_setup.go
  projects/gloo/pkg/plugins/protocoloptions/plugin.go
  projects/gloo/pkg/plugins/protocoloptions/plugin_test.go
  projects/gloo/pkg/plugins/upstreamconn/plugin.go
  projects/gloo/pkg/plugins/utils/httpprotocolhelpers/http1_utils.go
  projects/gloo/pkg/setup/setup.go
  test/e2e/envoyconfigs/zipkin-static-cluster.yaml
  test/e2e/gateway_test.go
  test/e2e/gzip_test.go
  test/e2e/zipkin_test.go
  test/helpers/util.go
  test/kube2e/util.go
Labels: keep pr updated

#7367 11/fix(Upstream): allow use_downstream_protocol when useHttp2 is set
  changelog/v1.11.43/7096-downstream-protocol.yaml
  projects/gloo/pkg/plugins/protocoloptions/plugin.go
  projects/gloo/pkg/plugins/protocoloptions/plugin_test.go
  projects/gloo/pkg/plugins/upstreamconn/plugin.go
  projects/gloo/pkg/plugins/utils/httpprotocolhelpers/http1_utils.go
Labels: keep pr updated

#7284 Generic Validation Webhook
  changelog/v1.13.0-beta26/generic_validation_webhook.yaml
  go.mod
  go.sum
  projects/clusteringress/pkg/api/external/knative/cluster_ingress.sk.go
  projects/clusteringress/pkg/api/v1/translator_snapshot.sk.go
  projects/gateway/pkg/api/v1/gateway.sk.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.sk.go
  projects/gateway/pkg/api/v1/route_option.sk.go
  projects/gateway/pkg/api/v1/route_table.sk.go
  projects/gateway/pkg/api/v1/virtual_host_option.sk.go
  projects/gateway/pkg/api/v1/virtual_service.sk.go
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook.go
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook_test.go
  projects/gateway/pkg/translator/hybrid_translator.go
  projects/gateway/pkg/translator/virtual_service_translator.go
  projects/gateway/pkg/validation/README.md
  projects/gateway/pkg/validation/helper_test.go
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
  projects/gloo/pkg/api/external/solo/ratelimit/rate_limit_config.sk.go
  projects/gloo/pkg/api/v1/artifact.sk.go
  projects/gloo/pkg/api/v1/discovery_snapshot.sk.go
  projects/gloo/pkg/api/v1/eds_snapshot.sk.go
  projects/gloo/pkg/api/v1/endpoint.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/auth_config.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_snapshot.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graph_ql_api.sk.go
  projects/gloo/pkg/api/v1/gloosnapshot/api_snapshot.sk.go
  projects/gloo/pkg/api/v1/proxy.sk.go
  projects/gloo/pkg/api/v1/secret.sk.go
  projects/gloo/pkg/api/v1/settings.sk.go
  projects/gloo/pkg/api/v1/setup_snapshot.sk.go
  projects/gloo/pkg/api/v1/upstream.sk.go
  projects/gloo/pkg/api/v1/upstream_group.sk.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/validation/gloo_validator.go
  projects/gloo/pkg/validation/server.go
  projects/gloo/pkg/validation/server_test.go
  projects/ingress/pkg/api/v1/ingress.sk.go
  projects/ingress/pkg/api/v1/kube_service.sk.go
  projects/ingress/pkg/api/v1/status_snapshot.sk.go
  projects/ingress/pkg/api/v1/translator_snapshot.sk.go
  projects/knative/pkg/api/external/knative/ingress.sk.go
  projects/knative/pkg/api/v1/translator_snapshot.sk.go
  test/samples/sample_gloo_api_snapshot.go
Labels: keep pr updated

#7379 [1.12] FDS graphql discovery opt out
  Makefile
  changelog/v1.12.33/disable-graphql-discovery-api.yaml
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/installation/advanced_configuration/fds_mode.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures/settings/graphql_fds_disabled.yaml
  install/test/helm_test.go
  projects/discovery/pkg/fds/syncer/discovery_syncer_test.go
  projects/discovery/pkg/fds/syncer/setup_syncer.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
Labels: keep pr updated

#7374 Race image arm ci support
  Makefile
  changelog/v1.13.0-beta26/build-race-image-only-on-ci.yaml
  ci/deploy-to-kind-cluster.sh
Labels: keep pr updated

#7383 Doc fixes for week of 10/27/2022
  changelog/v1.13.0-beta26/doc-fixes.yaml
  docs/active_versions.json
  docs/content/guides/dev/_index.md
  docs/content/guides/traffic_management/request_processing/health_checks/_index.md
  docs/content/introduction/development.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#7356 [1.11] fds discovery opt out
  Makefile
  changelog/v1.11.44/disable-graphql-discovery-api.yaml
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/installation/advanced_configuration/fds_mode.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures/settings/graphql_fds_disabled.yaml
  install/test/helm_test.go
  projects/discovery/pkg/fds/syncer/discovery_syncer_test.go
  projects/discovery/pkg/fds/syncer/setup_syncer.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
Labels: keep pr updated

#7392 v1.9.x: bump golang.org/x/text to v0.4.0
  changelog/v1.9.29/golang_text_cve_bump.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#7391 v1.10.x: bump golang.org/x/text to v0.4.0
  changelog/v1.10.40/golang_text_cve_bump.yaml
  changelog/v1.13.0-beta18/deflake-glooctl-istio-tests.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated
