Repository kgateway-dev/kgateway, pull requests merged in 2022-07, with the labels that each got.

#6658 Fix broken stitching link in GraphQL API reference doc
  docs/content/guides/graphql/stitching.md
Labels: Type: Docs, keep pr updated

#6548 Fix issues with helm custom resource install/upgrade
  changelog/v1.12.0-beta27/helm-custom-resources.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-gateway-validation-rollout-job.yaml
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/8-gateway-proxy-service-account.yaml
  install/helm/gloo/templates/_8-default-gateways.tpl
  install/helm/gloo/templates/_custom-resources.tpl
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#6657 V1.11.x redis tls
  changelog/v1.11.19/tls-user-sessions.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6653 Add http2 downstream settings
  changelog/v1.12.0-beta27/adding-http2-downstream-settings.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/protocol/protocol.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  projects/gloo/api/v1/connection.proto
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/api/v1/options/protocol/protocol.proto
  projects/gloo/pkg/api/v1/connection.pb.clone.go
  projects/gloo/pkg/api/v1/connection.pb.equal.go
  projects/gloo/pkg/api/v1/connection.pb.go
  projects/gloo/pkg/api/v1/connection.pb.hash.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.clone.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.equal.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.hash.go
  projects/gloo/pkg/api/v1/options/protocol/protocol.pb.clone.go
  projects/gloo/pkg/api/v1/options/protocol/protocol.pb.equal.go
  projects/gloo/pkg/api/v1/options/protocol/protocol.pb.go
  projects/gloo/pkg/api/v1/options/protocol/protocol.pb.hash.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/plugins/protocoloptions/plugin.go
  projects/gloo/pkg/plugins/upstreamconn/plugin.go
  projects/gloo/pkg/plugins/upstreamconn/plugin_test.go
  projects/gloo/pkg/plugins/utils/httpprotocolvalidation/protocol_validation_utils.go
Labels: keep pr updated

#6651 Parametrize the gateway proxy sidecar image
  changelog/v1.12.0-beta27/helm-gateway-proxy-image.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6663 Add http2 downstream settings
  changelog/v1.11.19/adding-http2-downstream-settings.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/protocol/protocol.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  projects/gloo/api/v1/connection.proto
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/api/v1/options/protocol/protocol.proto
  projects/gloo/pkg/api/v1/connection.pb.clone.go
  projects/gloo/pkg/api/v1/connection.pb.equal.go
  projects/gloo/pkg/api/v1/connection.pb.go
  projects/gloo/pkg/api/v1/connection.pb.hash.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.clone.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.equal.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.hash.go
  projects/gloo/pkg/api/v1/options/protocol/protocol.pb.clone.go
  projects/gloo/pkg/api/v1/options/protocol/protocol.pb.equal.go
  projects/gloo/pkg/api/v1/options/protocol/protocol.pb.go
  projects/gloo/pkg/api/v1/options/protocol/protocol.pb.hash.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/plugins/protocoloptions/plugin.go
  projects/gloo/pkg/plugins/upstreamconn/plugin.go
  projects/gloo/pkg/plugins/upstreamconn/plugin_test.go
  projects/gloo/pkg/plugins/utils/httpprotocolvalidation/protocol_validation_utils.go
Labels: keep pr updated

#6669 gloo/upstreams/hybrid: Needssync should reflect failure
  projects/gloo/pkg/upstreams/hybrid_client.go
Labels: keep pr updated

#6665 Reject WeightedDestination when Total Weight < 1 (v1.10.x)
  changelog/v1.10.30/weighted-cluster-validation.yaml
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6671 Doc fixes
  docs/active_versions.json
  docs/content/guides/security/auth/extauth/oauth/_index.md
  docs/content/operations/advanced/zero-downtime-gateway-rollout/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#6664 Reject WeightedDestination when Total Weight < 1 (v1.9.x)
  changelog/v1.9.19/weighted-cluster-validation.yaml
  ci/tools.go
  docs/content/guides/dev/example-proxy-controller.go
  docs/content/guides/dev/plugin.go
  docs/content/guides/dev/registry.go
  example/proxycontroller/proxycontroller.go
  projects/gateway/pkg/api/v1/kube/apis/gateway.solo.io/v1/zz_generated.deepcopy.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/apis/enterprise.gloo.solo.io/v1/zz_generated.deepcopy.go
  projects/gloo/pkg/api/v1/kube/apis/gloo.solo.io/v1/zz_generated.deepcopy.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6667 Reject WeightedDestination when Total Weight < 1
  changelog/v1.12.0-beta28/weighted-cluster-validation.yaml
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6670 Parameterize the gateway proxy sidecar image [1.11]
  changelog/v1.11.20/helm-gateway-proxy-image.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6672 1.8 emitter map fix
  changelog/v1.8.34/emission-map-init.yaml
  ci/tools.go
  docs/content/guides/dev/example-proxy-controller.go
  docs/content/guides/dev/plugin.go
  docs/content/guides/dev/registry.go
  example/proxycontroller/proxycontroller.go
  go.mod
  go.sum
  projects/clusteringress/pkg/api/v1/translator_snapshot_emitter.sk.go
  projects/gateway/pkg/api/v1/api_snapshot_emitter.sk.go
  projects/gateway/pkg/api/v1/kube/apis/gateway.solo.io/v1/zz_generated.deepcopy.go
  projects/gloo/pkg/api/v1/api_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/discovery_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/eds_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/kube/apis/enterprise.gloo.solo.io/v1/zz_generated.deepcopy.go
  projects/gloo/pkg/api/v1/kube/apis/gloo.solo.io/v1/zz_generated.deepcopy.go
  projects/gloo/pkg/api/v1/setup_snapshot_emitter.sk.go
  projects/gloo/pkg/upstreams/hybrid_client.go
  projects/ingress/pkg/api/v1/status_snapshot_emitter.sk.go
  projects/ingress/pkg/api/v1/translator_snapshot_emitter.sk.go
  projects/knative/pkg/api/v1/translator_snapshot_emitter.sk.go
Labels: keep pr updated

#6666 Reject WeightedDestination when Total Weight < 1 (v1.11.x)
  changelog/v1.11.20/weighted-cluster-validation.yaml
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6676 add 'failurepolicy: Fail' to the production deployment tips
  docs/content/operations/production_deployment/_index.md
Labels: keep pr updated

#6673 helm: fix rollout job when gateways are empty
  changelog/v1.12.0-beta28/helm-fix-empty-gateways.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6684 golang.org/x/tools dependency bump
  changelog/v1.9.19/x-tools-bump.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#6685 docs : specify weight of 0 is allowed on weighted destination given other non zero destinations
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/v1/proxy.pb.go
Labels: keep pr updated

#6687 UnmarshalStatus never errors (#6645)
  changelog/v1.11.21/status-unmarshal-never-errors.yaml
  go.mod
  go.sum
  install/test/helm_suite_test.go
  projects/gateway/pkg/api/v1/kube/generated_kube_suite_test.go
  projects/gateway/pkg/services/k8sadmission/k8sadmisssion_suite_test.go
  projects/gateway/pkg/validation/validation_suite_test.go
  projects/gloo/api/external/solo/ratelimit/rate_limit_config.go
  projects/gloo/cli/pkg/cmd/check/check_suite_test.go
  projects/gloo/cli/pkg/cmd/check/root_test.go
  projects/gloo/cli/pkg/printers/virtualservice_test.go
  projects/gloo/pkg/api/compress/compress.go
  projects/gloo/pkg/api/compress/compress_suite_test.go
  projects/gloo/pkg/api/compress/compress_test.go
  projects/gloo/pkg/api/v1/proxy_extensions.go
  projects/gloo/pkg/plugins/kubernetes/kubernetes_suite_test.go
  test/e2e/e2e_suite_test.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gloo-mtls/gloo_mtls_suite_test.go
  test/kube2e/gloo/setup_syncer_test.go
  test/kube2e/glooctl/glooctl_suite_test.go
  test/kube2e/helm/helm_suite_test.go
Labels: keep pr updated

#6690 Weighted Destination Document Updates backport - weight of 0 allowed
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/v1/proxy.pb.go
Labels: keep pr updated

#6691 Weighted Destination Document Updates backport - weight of 0 allowed
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/v1/proxy.pb.go
Labels: keep pr updated

#6668 use new solo-kit; emitter map fix
  changelog/v1.12.0-beta29/solo-kit-emitter-map.yaml
  go.mod
  go.sum
  projects/clusteringress/pkg/api/v1/translator_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/discovery_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/eds_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/gloosnapshot/api_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/setup_snapshot_emitter.sk.go
  projects/gloo/pkg/upstreams/hybrid_client.go
  projects/ingress/pkg/api/v1/status_snapshot_emitter.sk.go
  projects/ingress/pkg/api/v1/translator_snapshot_emitter.sk.go
  projects/knative/pkg/api/v1/translator_snapshot_emitter.sk.go
Labels: keep pr updated

#6695 Weighted destination test updates
  changelog/v1.12.0-beta30/weighted-destingation-test-updates.yaml
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6701 Weighted destination test updates
  changelog/v1.10.31/weighted-destingation-test-updates.yaml
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6704 Weighted destination test updates
  changelog/v1.8.35/weighted-destingation-test-updates.yaml
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6700 Weighted destination test updates
  changelog/v1.11.22/weighted-destingation-test-updates.yaml
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#6680 Ext auth add cert mount
  changelog/v1.12.0-beta30/tls-certs-for-user-sessions.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6709 Upgrade Security Scanner
  .github/workflows/README.md
  .github/workflows/trivy-analysis-scheduled.yaml
  Makefile
  changelog/v1.12.0-beta31/upgrade-security-scanner.yaml
  docs/Makefile
  docs/cmd/generate_docs.go
  docs/cmd/securityscanutils/README.md
  go.mod
  go.sum
  test/kube2e/util.go
Labels: keep pr updated

#6712 Dependency bumps for gloo v1.10
  changelog/v1.10.31/solo-kit-fixes.yaml
  go.mod
  go.sum
  projects/clusteringress/pkg/api/v1/translator_snapshot_emitter.sk.go
  projects/gateway/pkg/api/v1/api_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/api_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/discovery_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/eds_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/setup_snapshot_emitter.sk.go
  projects/ingress/pkg/api/v1/status_snapshot_emitter.sk.go
  projects/ingress/pkg/api/v1/translator_snapshot_emitter.sk.go
  projects/knative/pkg/api/v1/translator_snapshot_emitter.sk.go
Labels: keep pr updated

#6723 Update the secret used for Github automation
  .github/workflows/issue_board.yaml
  changelog/v1.12.0-beta31/automation_secret.yaml
Labels: keep pr updated

#6726 only set maxGrpcRecvSize if >= 0 (#6711)
  changelog/v1.10.32/grpcmaxsize-default.yaml
  projects/gloo/pkg/syncer/setup/setup_syncer.go
Labels: keep pr updated

#6725 only set maxGrpcRecvSize if >= 0 (#6711)
  changelog/v1.9.20/grpcmaxsize-default.yaml
  projects/gloo/pkg/syncer/setup/setup_syncer.go
Labels: keep pr updated

#6724 only set maxGrpcRecvSize if >= 0 (#6711)
  changelog/v1.8.35/grpcmaxsize-default.yaml
  projects/gloo/pkg/syncer/setup/setup_syncer.go
Labels: keep pr updated

#6727 only set maxGrpcRecvSize if >= 0 (#6711)
  changelog/v1.12.0-beta31/grpcmaxsize-default.yaml
  projects/gloo/pkg/syncer/setup/setup_syncer.go
Labels: keep pr updated

#6719 Fix showing defaults
  changelog/v1.12.0-beta31/allow-default-weight-to-be-viewed.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
  projects/clusteringress/pkg/translator/translate_test.go
  projects/gloo/api/v1/proxy.proto
  projects/gloo/cli/pkg/cmd/create/upstreamgroup.go
  projects/gloo/cli/pkg/cmd/create/upstreamgroup_test.go
  projects/gloo/cli/pkg/printers/upstreamgroup.go
  projects/gloo/pkg/api/v1/proxy.pb.clone.go
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.hash.go
  projects/gloo/pkg/plugins/extauth/plugin_test.go
  projects/gloo/pkg/plugins/tcp/plugin.go
  projects/gloo/pkg/plugins/tcp/plugin_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/translator_test.go
  projects/knative/pkg/translator/translate.go
  projects/knative/pkg/translator/translate_test.go
  test/e2e/csrf_test.go
  test/e2e/route_transformation_test.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#6740 handles NPE
  changelog/v1.12.0-beta31/handle-npe-markperfilerconfig.yaml
  projects/gloo/pkg/plugins/pluginutils/per_filter_config.go
  projects/gloo/pkg/plugins/pluginutils/per_filter_config_test.go
Labels: keep pr updated

#6750 v1.11.x - handles NPE (#6740)
  changelog/v1.11.23/handle-npe-markperfilerconfig.yaml
  projects/gloo/pkg/plugins/pluginutils/per_filter_config.go
  projects/gloo/pkg/plugins/pluginutils/per_filter_config_test.go
Labels: keep pr updated

#6749 v1.10.x - NPE
  changelog/v1.10.32/handle-npe-markperfilerconfig.yaml
  projects/gloo/pkg/plugins/pluginutils/per_filter_config.go
  projects/gloo/pkg/plugins/pluginutils/per_filter_config_test.go
Labels: keep pr updated

#6747 v1.8.x - NPE
  changelog/v1.8.35/handle-npe-markperfilerconfig.yaml
  projects/gloo/pkg/plugins/pluginutils/per_filter_config.go
  projects/gloo/pkg/plugins/pluginutils/per_filter_config_test.go
Labels: keep pr updated

#6742 HTTP Connect Tunnelling: Support Encryption to HTTP Connect Proxy
  changelog/v1.12.0-beta31/http-connect-tls.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/upstream.pb.clone.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/tunneling/plugin.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  test/e2e/custom_auth_test.go
  test/e2e/http_tunneling_test.go
  test/v1helpers/test_upstream.go
Labels: keep pr updated

#6752 Doc fixes 1.10.x
  docs/active_versions.json
  docs/content/operations/upgrading/1.10.0.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#6717 Enable config to expose Envoy's X-RateLimit headers
  changelog/v1.12.0-beta31/rate-limit-counters.yaml
  docs/content/guides/security/rate_limiting/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.hash.go
  projects/gloo/pkg/plugins/ratelimit/plugin.go
  projects/gloo/pkg/plugins/ratelimit/util.go
  test/e2e/ratelimit_test.go
Labels: keep pr updated

#6765 CVE Fixes
  changelog/v1.12.0-beta32/cve.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#6766 v1.11.x CVE Fixes
  changelog/v1.11.24/cve.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/content/static/content/osa_provided.md
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  go.mod
  go.sum
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6772 1.10 CVE fix
  Makefile
  changelog/v1.10.33/cve.yaml
  docs/content/guides/dev/writing_auth_plugins/_index.md
  docs/content/guides/security/tls/Dockerfile
  docs/content/static/content/osa_provided.md
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  go.mod
  go.sum
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6773 update doc versions
  docs/active_versions.json
Labels: keep pr updated

#6761 Image Digest Pinning #6581
  changelog/v1.12.0-beta32/image-digest-pinning.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
Labels: keep pr updated

#6776 caching: Update for proto changes and hardening in 1.12
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/caching/caching.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/enterprise/options/caching/caching.proto
  projects/gloo/pkg/api/v1/enterprise/options/caching/caching.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/caching/caching.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/caching/caching.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/caching/caching.pb.hash.go
Labels: keep pr updated

#6775 Tunnelling connect 1.11
  changelog/v1.11.24/http-connect-tls.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/upstream.pb.clone.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/tunneling/plugin.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  test/e2e/custom_auth_test.go
  test/e2e/http_tunneling_test.go
  test/v1helpers/test_upstream.go
Labels: keep pr updated

#6783 Image Digest Pinning #6581 (#6761)
  changelog/v1.11.24/image-digest-pinning.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
Labels: keep pr updated

#6787 Doc backport 1.11.x
  changelog/v1.11.24/docs-graphql-gs.yaml
  docs/active_versions.json
  docs/content/guides/dev/example-proxy-controller.md
  docs/content/guides/graphql/getting_started.md
  docs/content/guides/integrations/cert_manager/_index.md
  docs/content/guides/integrations/ingress/_index.md
  docs/content/guides/security/auth/custom_auth/_index.md
  docs/content/guides/security/auth/extauth/oauth/_index.md
  docs/content/guides/security/auth/extauth/oauth/google/_index.md
  docs/content/guides/security/auth/extauth/opa/_index.md
  docs/content/guides/security/auth/extauth/plugin_auth/_index.md
  docs/content/guides/security/auth/jwt/access_control/_index.md
  docs/content/guides/security/data_loss_prevention/_index.md
  docs/content/guides/security/rate_limiting/set/_index.md
  docs/content/guides/security/tls/server_tls.md
  docs/content/guides/traffic_management/destination_types/discovered_upstream/_index.md
  docs/content/guides/traffic_management/destination_types/http2/_index.md
  docs/content/guides/traffic_management/hello_world/_index.md
  docs/content/guides/traffic_management/request_processing/prefix_rewrite/_index.md
  docs/content/guides/traffic_management/request_processing/regex_rewrite/_index.md
  docs/content/introduction/_index.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#6790 helm: fix argocd hanging [1.11]
  changelog/v1.11.24/fix-argo-hanging.yaml
  changelog/v1.11.24/http-connect-tls.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/values-template.yaml
Labels: keep pr updated

#6793 [1.8] Proxy Reconciliation is Forward and Backward Compatible
  changelog/v1.8.36/set-based-proxy-selection.yaml
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/ingress/pkg/translator/translator_syncer.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#6741 Gateway install cleanup
  Makefile
  changelog/v1.12.0-rc3/gateway-install.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/version/version.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate.go
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
  install/helm/gloo/templates/5-gateway-deployment.yaml
  install/helm/gloo/templates/5-gateway-service-account.yaml
  install/helm/gloo/templates/5-gateway-service.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  install/test/svc_accnt_test.go
  install/test/util.go
  projects/gateway/cmd/Dockerfile
  projects/gateway/cmd/main.go
  projects/gateway/pkg/setup/setup.go
  projects/gateway/pkg/syncer/setup_syncer.go
  projects/gloo/api/grpc/version/version.proto
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/version/clients.go
  projects/gloo/cli/pkg/prerun/version_warning.go
  projects/gloo/cli/pkg/prerun/version_warning_test.go
  projects/gloo/pkg/api/grpc/version/version.pb.clone.go
  projects/gloo/pkg/api/grpc/version/version.pb.equal.go
  projects/gloo/pkg/api/grpc/version/version.pb.go
  projects/gloo/pkg/api/grpc/version/version.pb.hash.go
Labels: keep pr updated

#6794 Fix/cache max sizes
  changelog/v1.12.0-rc3/fix-caching-custom-layer-bytes.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/cache/grpc/config.proto.sk.md
  projects/gloo/api/external/envoy/extensions/cache/grpc/config.proto
  projects/gloo/pkg/api/external/envoy/extensions/cache/grpc/config.pb.go
Labels: keep pr updated

#6803 Upgrade deps
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.12.0-rc4/upgrade-dependencies.yaml
  docs/cmd/generate_docs.go
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  go.mod
  go.sum
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/clusteringress/pkg/api/external/knative/cluster_ingress.sk.go
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/pkg/api/v1/gateway.sk.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.sk.go
  projects/gateway/pkg/api/v1/route_option.sk.go
  projects/gateway/pkg/api/v1/route_table.sk.go
  projects/gateway/pkg/api/v1/virtual_host_option.sk.go
  projects/gateway/pkg/api/v1/virtual_service.sk.go
  projects/gloo/api/external/solo/ratelimit/rate_limit_config.go
  projects/gloo/pkg/api/compress/compress.go
  projects/gloo/pkg/api/compress/compress_test.go
  projects/gloo/pkg/api/external/solo/ratelimit/rate_limit_config.sk.go
  projects/gloo/pkg/api/v1/artifact.sk.go
  projects/gloo/pkg/api/v1/endpoint.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/auth_config.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graph_ql_api.sk.go
  projects/gloo/pkg/api/v1/proxy.sk.go
  projects/gloo/pkg/api/v1/secret.sk.go
  projects/gloo/pkg/api/v1/settings.sk.go
  projects/gloo/pkg/api/v1/upstream.sk.go
  projects/gloo/pkg/api/v1/upstream_group.sk.go
  projects/ingress/cmd/Dockerfile
  projects/ingress/pkg/api/v1/ingress.sk.go
  projects/ingress/pkg/api/v1/kube_service.sk.go
  projects/knative/pkg/api/external/knative/ingress.sk.go
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6809 Upgrade doc fixes
  changelog/v1.12.0-rc5/upgrade-docs-fixes.yaml
  docs/content/contributing/documentation/editing_locally.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/gloo_federation.md
  docs/content/installation/ingress/_index.md
  docs/content/operations/upgrading/v1.11.md
  docs/content/operations/upgrading/v1.12.md
  docs/content/static/content/upgrade-crd.md
  docs/content/static/content/upgrade-note.md
Labels: work in progress, keep pr updated

#6807 v1.10.x: Solo-kit and go-utils update
  changelog/v1.10.34/sk-go-utils-bumps.yaml
  go.mod
  go.sum
  projects/gloo/api/external/solo/ratelimit/rate_limit_config.go
  projects/gloo/pkg/api/compress/compress.go
  projects/gloo/pkg/api/compress/compress_test.go
  test/kube2e/util.go
Labels: keep pr updated

#6813 Upgrade doc fixes [1.11]
  changelog/v1.11.25/upgrade-docs-fixes.yaml
  docs/content/contributing/documentation/editing_locally.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/gloo_federation.md
  docs/content/installation/ingress/_index.md
  docs/content/operations/upgrading/v1.11.md
  docs/content/static/content/upgrade-crd.md
  docs/content/static/content/upgrade-note.md
Labels: keep pr updated

#6768 Update cookie session to allow use of refresh token
  changelog/v1.12.0-rc5/allow-use-of-refresh-token-in-ext-auth-cookie-session.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6818 End session endpoint
  changelog/v1.12.0-rc5/adding-end-session-endpoint.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6810 Docs: AWS Lambda
  changelog/v1.12.0-rc5/docs-lambda.yaml
  docs/content/guides/traffic_management/destination_types/aws_lambda/_index.md
Labels: keep pr updated

#6735 Add key_prefix to InternalSession
  changelog/v1.12.0-rc5/add-key-prefix-to-extauth-cookies.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6823 Doc fixes - links, field desc, security posture
  changelog/v1.12.0-rc6/docs-fixes.yaml
  docs/active_versions.json
  docs/content/guides/traffic_management/destination_types/discovered_upstream/_index.md
  docs/content/img/Gloo-01-200-by-155.png
  docs/content/img/Gloo-01-350-by-65.png
  docs/content/img/Gloo-01.png
  docs/content/img/logo.png
  docs/content/installation/advanced_configuration/fds_mode.md
  docs/content/introduction/architecture/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/reference/security-posture.md
  docs/content/reference/security-posture.yaml
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  docs/docs.toml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: Type: Docs, keep pr updated
