Repository kgateway-dev/kgateway, pull requests merged in 2022-02, with the labels that each got.

#5846 Accept opaque header secrets in addition to `gloo.solo.io/header` (v1.10.x backport)
  projects/gloo/pkg/api/converters/kube/header_secret.go
  projects/gloo/pkg/api/converters/kube/header_secret_test.go
  projects/gloo/pkg/api/converters/kube/secretconverter.go
Labels: keep pr updated

#5844 Introduce MatchableHttpGateway
  changelog/v1.11.0-beta8/new-http-gateway-crd.yaml
  docs/content/reference/api/envoy.glooe.solo.io.project.sk.md
  docs/content/reference/api/gateway.solo.io.project.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/http_gateway.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/core/selectors/selectors.proto.sk.md
  docs/content/reference/api/gloo.solo.io.project.sk.md
  docs/content/reference/api/glooe.solo.io.project.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
  install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
  install/test/rbac_test.go
  install/test/util.go
  projects/gateway/api/v1/gateway.proto
  projects/gateway/api/v1/http_gateway.proto
  projects/gateway/api/v1/solo-kit.json
  projects/gateway/pkg/api/v1/api_snapshot.sk.go
  projects/gateway/pkg/api/v1/api_snapshot_emitter.sk.go
  projects/gateway/pkg/api/v1/api_snapshot_simple_emitter.sk.go
  projects/gateway/pkg/api/v1/gateway.pb.clone.go
  projects/gateway/pkg/api/v1/gateway.pb.equal.go
  projects/gateway/pkg/api/v1/gateway.pb.go
  projects/gateway/pkg/api/v1/gateway.pb.hash.go
  projects/gateway/pkg/api/v1/http_gateway.pb.clone.go
  projects/gateway/pkg/api/v1/http_gateway.pb.equal.go
  projects/gateway/pkg/api/v1/http_gateway.pb.go
  projects/gateway/pkg/api/v1/http_gateway.pb.hash.go
  projects/gateway/pkg/api/v1/kube/apis/gateway.solo.io/v1/register.go
  projects/gateway/pkg/api/v1/kube/apis/gateway.solo.io/v1/types.go
  projects/gateway/pkg/api/v1/kube/apis/gateway.solo.io/v1/zz_generated.deepcopy.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/fake/clientset_generated.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/fake/fake_gateway.solo.io_client.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/fake/fake_matchablehttpgateway.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/gateway.solo.io_client.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/generated_expansion.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/matchablehttpgateway.go
  projects/gateway/pkg/api/v1/kube/client/informers/externalversions/gateway.solo.io/v1/interface.go
  projects/gateway/pkg/api/v1/kube/client/informers/externalversions/gateway.solo.io/v1/matchablehttpgateway.go
  projects/gateway/pkg/api/v1/kube/client/informers/externalversions/generic.go
  projects/gateway/pkg/api/v1/kube/client/listers/gateway.solo.io/v1/expansion_generated.go
  projects/gateway/pkg/api/v1/kube/client/listers/gateway.solo.io/v1/matchablehttpgateway.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.sk.go
  projects/gateway/pkg/api/v1/matchable_http_gateway_client.sk.go
  projects/gateway/pkg/api/v1/matchable_http_gateway_reconciler.sk.go
  projects/gateway/pkg/syncer/setup_syncer.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/translator/opts.go
  projects/gloo/api/v1/core/selectors/selectors.proto
  projects/gloo/cli/pkg/cmd/install/util.go
  projects/gloo/pkg/api/v1/core/selectors/selectors.pb.clone.go
  projects/gloo/pkg/api/v1/core/selectors/selectors.pb.equal.go
  projects/gloo/pkg/api/v1/core/selectors/selectors.pb.go
  projects/gloo/pkg/api/v1/core/selectors/selectors.pb.hash.go
  projects/gloo/pkg/bootstrap/opts.go
  test/kube2e/helm/helm_test.go
  test/services/gateway.go
Labels: keep pr updated

#5842 socket options - change from 'STATE_LISTENING' to 'STATE_PREBIND'
  changelog/v1.11.0-beta8/docs-state_listening.yaml
  docs/content/guides/integrations/aws/_index.md
  docs/content/guides/integrations/aws/socket-options/_index.md
Labels: keep pr updated

#5862 backport(fix(gateway)): allow error clearing for gateways without children
  changelog/v1.10.5/5578-orphaned-gateway.yaml
  projects/gateway/pkg/reconciler/proxy_reconciler.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_integration_test.go
  projects/gateway/pkg/syncer/translator_syncer_test.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#5851 makefile: Bump envoy-gloo version to latest 1.20 for sts chaining
  Makefile
  changelog/v1.11.0-beta9/bump-envoy-get-aws-updates.yaml
  docs/content/guides/traffic_management/destination_types/aws_lambda/eks-service-accounts.md
Labels: work in progress, keep pr updated

#5870 .gitattributes: Add some more file types to auto-collapse without bro…
  .gitattributes
Labels: keep pr updated

#5871 Doc - update the doc on the installation of the admin UI
  changelog/v1.11.0-beta9/clarify-admin-ui-installation.yaml
  docs/.gitignore
  docs/content/installation/enterprise/_index.md
Labels: keep pr updated

#5843 Slack Notification when CI Fails
  .github/workflows/docs-gen.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.11.0-beta9/notify-on-gha-failure.yaml
Labels: keep pr updated

#5875 Fix indentation for custom HTTPS Gateway settings
  changelog/v1.11.0-beta9/fix-helm-indentation-https-gw.yaml
  install/helm/gloo/templates/8-default-gateways.yaml
Labels: keep pr updated

#5878 [non-user-facing]: add GraphQL stats prefix to API and some WASM docs fixes
  changelog/v1.11.0-beta9/add-gql-stats-api.yaml
  docs/content/installation/advanced_configuration/wasm.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/graphql/graphql.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto.sk.md
  install/helm/gloo/crds/graphql.gloo.solo.io_v1alpha1_GraphQLSchema.yaml
  projects/gloo/api/external/envoy/extensions/graphql/graphql.proto
  projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/graphql/v2/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.hash.go
Labels: keep pr updated

#5880 Helm/backport fix https gw to v1.10
  changelog/v1.10.6/fix-helm-indentation-https-gw.yaml
  install/helm/gloo/templates/8-default-gateways.yaml
Labels: keep pr updated

#5873 Add hybrid gateway link to multi-gateway doc
  docs/content/installation/advanced_configuration/multi-gw-deployment.md
Labels: Type: Docs, keep pr updated

#5884 Doc fixes to bump versions
  changelog/v1.11.0-beta9/docs-bump-version.yaml
  docs/active_versions.json
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#5872 Validate Integrity of TLS Secrets
  changelog/v1.11.0-beta9/tls-secret-error-handling.yaml
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
  test/e2e/happypath_test.go
  test/samples/sample_gloo_api_snapshot.go
Labels: keep pr updated

#5886 Fix TLS secrets
  changelog/v1.11.0-beta9/fix-tls-secrets.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/secret.proto.sk.md
  docs/content/reference/cli/glooctl_create_secret.md
  docs/content/reference/cli/glooctl_create_secret_oauth.md
  docs/content/reference/cli/glooctl_create_secret_tls.md
  projects/gloo/api/v1/secret.proto
  projects/gloo/cli/pkg/cmd/create/secret/extauth_oauth.go
  projects/gloo/cli/pkg/cmd/create/secret/root.go
  projects/gloo/cli/pkg/cmd/create/secret/secret_test.go
  projects/gloo/cli/pkg/cmd/create/secret/tls.go
  projects/gloo/pkg/api/converters/kube/opaque_secret.go
  projects/gloo/pkg/api/converters/kube/opaque_secret_test.go
  projects/gloo/pkg/api/converters/kube/secretconverter.go
  projects/gloo/pkg/api/converters/kube/secretconverter_test.go
  projects/gloo/pkg/api/v1/secret.pb.go
Labels: keep pr updated

#5893 Fix TLS secrets [1.10]
  changelog/v1.10.6/fix-tls-secrets.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/secret.proto.sk.md
  docs/content/reference/cli/glooctl_create_secret.md
  docs/content/reference/cli/glooctl_create_secret_oauth.md
  docs/content/reference/cli/glooctl_create_secret_tls.md
  projects/gloo/api/v1/secret.proto
  projects/gloo/cli/pkg/cmd/create/secret/extauth_oauth.go
  projects/gloo/cli/pkg/cmd/create/secret/root.go
  projects/gloo/cli/pkg/cmd/create/secret/secret_test.go
  projects/gloo/cli/pkg/cmd/create/secret/tls.go
  projects/gloo/pkg/api/converters/kube/opaque_secret.go
  projects/gloo/pkg/api/converters/kube/opaque_secret_test.go
  projects/gloo/pkg/api/converters/kube/secretconverter.go
  projects/gloo/pkg/api/converters/kube/secretconverter_test.go
  projects/gloo/pkg/api/v1/secret.pb.go
Labels: keep pr updated

#5887 Feature/unused filters
  changelog/v1.11.0-beta10/dont-add-unused-filters.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gateway/pkg/api/v1/kube/apis/gateway.solo.io/v1/zz_generated.deepcopy.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/plugins/csrf/plugin.go
  projects/gloo/pkg/plugins/csrf/plugin_test.go
  projects/gloo/pkg/plugins/faultinjection/plugin.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/plugins/registry/registry_test.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/transformation/plugin_test.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#5897 Docs: version bumps
  changelog/v1.11.0-beta10/docs-bump-version.yaml
  docs/active_versions.json
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
Labels: keep pr updated

#5899 Backport change to allow running certgen job on upgrade
  changelog/v1.10.7/certgen-preupgrade.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#5882 Translate MatchableHttpGateway into Proxy
  changelog/v1.11.0-beta11/new-http-gateway-implementation.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gateway/api/v1/gateway.proto
  projects/gateway/pkg/api/v1/gateway.pb.clone.go
  projects/gateway/pkg/api/v1/gateway.pb.equal.go
  projects/gateway/pkg/api/v1/gateway.pb.go
  projects/gateway/pkg/api/v1/gateway.pb.hash.go
  projects/gateway/pkg/reconciler/proxy_reconciler_test.go
  projects/gateway/pkg/reporting/add_proxy_validation_result_test.go
  projects/gateway/pkg/reporting/check_source_reports_test.go
  projects/gateway/pkg/translator/http_gateway_selector.go
  projects/gateway/pkg/translator/http_gateway_selector_test.go
  projects/gateway/pkg/translator/http_translator.go
  projects/gateway/pkg/translator/http_translator_test.go
  projects/gateway/pkg/translator/hybrid.go
  projects/gateway/pkg/translator/hybrid_translator.go
  projects/gateway/pkg/translator/hybrid_translator_test.go
  projects/gateway/pkg/translator/listener_translator.go
  projects/gateway/pkg/translator/tcp.go
  projects/gateway/pkg/translator/tcp_translator.go
  projects/gateway/pkg/translator/tcp_translator_test.go
  projects/gateway/pkg/translator/translator.go
  projects/gateway/pkg/translator/translator_test.go
  projects/gateway/pkg/validation/validator.go
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/v1/proxy.pb.clone.go
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.hash.go
  projects/gloo/pkg/utils/vhosts.go
Labels: keep pr updated

#5901 Add UUID regex path matching example
  docs/content/guides/traffic_management/destination_selection/path_matching/_index.md
  docs/content/guides/traffic_management/destination_selection/path_matching/regex_vs_uuid.yaml
Labels: Type: Docs, keep pr updated

#5913 add graphql to fed clusterrole
  changelog/v1.11.0-beta11/graphql-fed-cluster-reg.yaml
  projects/gloo/cli/pkg/cmd/federation/register/root.go
Labels: keep pr updated

#5907 Avoid stackdumps in glooctl check
  changelog/v1.11.0-beta11/glooctl-check-fix.yaml
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/helpers/clients.go
Labels: keep pr updated

#5903 v1.9.x: Bump envoy-gloo version to v1.20.0-patch3
  Makefile
  changelog/v1.9.8/envoy-gloo-bump.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto.sk.md
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
  projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation_ee/transformation.pb.go
  test/services/envoy.go
Labels: keep pr updated

#5912 HybridListeners mutliple SslConfig support
  changelog/v1.11.0-beta11/http-gw-gloo-translation.yaml
  projects/gloo/pkg/defaults/port.go
  projects/gloo/pkg/translator/filter_chain.go
  projects/gloo/pkg/translator/listener_subsystem.go
  projects/gloo/pkg/translator/ssl_configuration.go
  projects/gloo/pkg/translator/ssl_configuration_test.go
  projects/gloo/pkg/translator/translator_test.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#5923 Avoid stackdumps in glooctl check (v1.10.x backport)
  changelog/v1.10.8/glooctl-check-fix.yaml
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/helpers/clients.go
Labels: keep pr updated

#5925 Doc fixes for 1.10.x
  changelog/v1.10.9/docs-fixes.yaml
  docs/content/installation/glooctl_setup.md
Labels: Type: Docs, keep pr updated, bug

#5931 Fix extauth logging curl cmd for OPA docs
  docs/content/guides/security/auth/extauth/opa/_index.md
Labels: Type: Docs, keep pr updated

#5915 v1.10.x: Bump envoy-gloo version to v1.20.0-patch3
  Makefile
  changelog/v1.10.9/envoy-gloo-bump.yaml
Labels: keep pr updated

#5932 Backport change to add the --force-rotation flag to cert rotation
  changelog/v1.10.9/certgen-cronjob-force.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
Labels: keep pr updated

#5943 install/helm: Respect helm values for aws lambda features other than …
  changelog/v1.10.9/aws-respecthelm.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#5942 Fix control plane logging curl cmd for debugging docs
  docs/content/operations/debugging_gloo/_index.md
Labels: Type: Docs, keep pr updated

#5950 Add support for exlcuding all types with glooctl check -x
  changelog/v1.11.0-beta12/glooctl-check-exclude.yaml
  docs/content/reference/cli/glooctl_check.md
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/check/root_test.go
  projects/gloo/cli/pkg/flagutils/metadata.go
Labels: keep pr updated

#5929 Doc fixes
  changelog/v1.11.0-beta12/docs-fixes.yaml
  docs/active_versions.json
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/operations/production_deployment/_index.md
  docs/content/operations/upgrading/1.10.0.md
  docs/content/operations/upgrading/1.9.0.md
  docs/content/reference/values.txt
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  install/helm/gloo/generate/values.go
Labels: keep pr updated

#5951 Backport: Doc fixes
  changelog/v1.10.10/docs-fixes.yaml
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/operations/production_deployment/_index.md
  docs/content/operations/upgrading/1.10.0.md
  docs/content/operations/upgrading/1.9.0.md
  docs/content/reference/values.txt
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n-1.md
  install/helm/gloo/generate/values.go
Labels: keep pr updated

#5959 fix regex route short circuiting check
  changelog/v1.11.0-beta12/fix-regex-route-short-circuiting.yaml
  projects/gateway/pkg/translator/http_translator.go
  projects/gateway/pkg/translator/http_translator_test.go
Labels: keep pr updated

#5963 fix regex route short circuiting check [1.10]
  changelog/v1.10.10/fix-regex-route-short-circuiting.yaml
  projects/gateway/pkg/translator/http_translator.go
  projects/gateway/pkg/translator/http_translator_test.go
Labels: keep pr updated

#5964 fix regex route short circuiting check [1.9]
  changelog/v1.9.9/fix-regex-route-short-circuiting.yaml
  projects/gateway/pkg/translator/http.go
  projects/gateway/pkg/translator/translator_test.go
Labels: keep pr updated

#5965 fix regex route short circuiting check [1.8]
  changelog/v1.8.25/fix-regex-route-short-circuiting.yaml
  projects/gateway/pkg/translator/http.go
  projects/gateway/pkg/translator/translator_test.go
Labels: keep pr updated

#5966 Bump envoy gloo to 1.19.0-patch5
  Makefile
  changelog/v1.8.25/bump-envoy.yaml
Labels: keep pr updated

#5968 bump envoy-gloo to 1.20.0-patch4
  Makefile
  changelog/v1.10.10/envoy-bump.yaml
Labels: keep pr updated

#5967 [1.9] bump envoy-gloo to 1.20.0-patch4
  Makefile
  changelog/v1.9.9/envoy-bump.yaml
Labels: keep pr updated

#5973 un-nest the JwtValidation and IntrospectionValidation fields
  changelog/v1.11.0-beta12/unnest-extauth-fields.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#5956 Add Lambda cold start latency docs
  docs/content/guides/traffic_management/destination_types/aws_lambda/eks-service-accounts.md
Labels: Type: Docs, keep pr updated

#5977 Update GraphQL API
  changelog/v1.11.0-beta13/graphql-caching-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/graphql/graphql.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto.sk.md
  docs/data/ProtoMap.yaml
  go.mod
  go.sum
  install/helm/gloo/crds/graphql.gloo.solo.io_v1alpha1_GraphQLSchema.yaml
  projects/gloo/api/external/envoy/extensions/graphql/graphql.proto
  projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/graphql/v2/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.hash.go
Labels: keep pr updated

#5983 Doc backport for week of 2/21/22
  README.md
  changelog/v1.10.11/docs-backport.yaml
  docs/content/guides/gloo_federation/getting_started.md
  docs/content/introduction/_index.md
  docs/content/introduction/gloo_federation.md
  docs/content/operations/upgrading/1.10.0.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#5975 simplify custom CA with volumes
  docs/content/installation/advanced_configuration/extauth_custom_ca.md
Labels: Type: Docs, keep pr updated

#5981 Fix gloo fed demo
  changelog/v1.11.0-beta14/fix-gloo-fed-demo.yaml
  docs/content/reference/cli/glooctl_demo_federation.md
  projects/gloo/cli/pkg/cmd/demo/federation.go
  projects/gloo/cli/pkg/flagutils/install.go
Labels: keep pr updated

#5937 Extend timeout for secret client in glooctl check
  changelog/v1.11.0-beta14/glooctl-check-secret-timeout.yaml
  docs/content/installation/advanced_configuration/glooctl-config.md
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/config_file.go
  projects/gloo/cli/pkg/cmd/options/options.go
Labels: keep pr updated
