Repository kgateway-dev/kgateway, pull requests merged in 2022-03, with the labels that each got.

#5971 Expose enable_trailers setting in Envoy HCM
  changelog/v1.11.0-beta14/expose-enable-trailers.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/connection.proto
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/connection.pb.clone.go
  projects/gloo/pkg/api/v1/connection.pb.equal.go
  projects/gloo/pkg/api/v1/connection.pb.go
  projects/gloo/pkg/api/v1/connection.pb.hash.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.clone.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.equal.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.hash.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/plugins/upstreamconn/plugin.go
  projects/gloo/pkg/plugins/upstreamconn/plugin_test.go
Labels: keep pr updated

#5957 Helm improvements for docs
  changelog/v1.11.0-beta14/helm-improvements.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures.go
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  install/test/merge_ingress_values.yaml
  install/test/svc_accnt_test.go
  install/test/values/val_consul_discovery_test_inputs.yaml
  install/test/values/val_consul_test_inputs.yaml
  install/test/values/val_custom_gateways.yaml
  install/test/values/val_default_gateway_access_logging_service.yaml
  install/test/values/val_tracing_provider_cluster.yaml
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#5997 V1.10.x: Expose enable trailers setting
  changelog/v1.10.11/expose-enable-trailers.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/connection.proto
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/connection.pb.clone.go
  projects/gloo/pkg/api/v1/connection.pb.equal.go
  projects/gloo/pkg/api/v1/connection.pb.go
  projects/gloo/pkg/api/v1/connection.pb.hash.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.clone.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.equal.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.hash.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/plugins/upstreamconn/plugin.go
  projects/gloo/pkg/plugins/upstreamconn/plugin_test.go
Labels: keep pr updated

#6000 Backport doc updates to 1.10.x
  changelog/v1.10.11/docs-backport2.yaml
  docs/content/reference/support.md
Labels: Type: Docs, keep pr updated

#5982 Doc fixes for week of 2/21/22
  .github/ISSUE_TEMPLATE/DOCS-ISSUE.yml
  changelog/v1.11.0-beta15/docs-fixes2.yaml
  docs/active_versions.json
  docs/content/guides/gloo_federation/getting_started.md
  docs/content/guides/traffic_management/request_processing/graphql/_index.md
  docs/content/introduction/_index.md
  docs/content/introduction/gloo_federation.md
  docs/content/reference/api/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#6006 feat(upstreamconn): header transform support
  changelog/v1.11.0-beta15/header-casing-issue.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/connection.proto
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/connection.pb.clone.go
  projects/gloo/pkg/api/v1/connection.pb.equal.go
  projects/gloo/pkg/api/v1/connection.pb.go
  projects/gloo/pkg/api/v1/connection.pb.hash.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/plugins/upstreamconn/plugin.go
  projects/gloo/pkg/plugins/upstreamconn/plugin_test.go
Labels: keep pr updated, 6006

#6007 feat(upstreamconn): header transform support online
  changelog/v1.10.11/header-casing-issue.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/connection.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/connection.proto
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/connection.pb.clone.go
  projects/gloo/pkg/api/v1/connection.pb.equal.go
  projects/gloo/pkg/api/v1/connection.pb.go
  projects/gloo/pkg/api/v1/connection.pb.hash.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/plugins/upstreamconn/plugin.go
  projects/gloo/pkg/plugins/upstreamconn/plugin_test.go
Labels: keep pr updated, 6006

#6001 Helm improvements for monitoring
  changelog/v1.11.0-beta15/helm-improvements.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/2-gloo-service.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/helm/gloo/templates/3-discovery-service.yaml
  install/helm/gloo/templates/5-gateway-deployment.yaml
  install/helm/gloo/templates/5-gateway-service.yaml
  install/helm/gloo/templates/6-access-logger-deployment.yaml
  install/helm/gloo/templates/6-access-logger-service.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/8-gateway-proxy-service.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6002 [1.10] Helm improvements
  changelog/v1.10.11/helm-improvements.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/templates/2-gloo-service.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/helm/gloo/templates/3-discovery-service.yaml
  install/helm/gloo/templates/5-gateway-deployment.yaml
  install/helm/gloo/templates/5-gateway-service.yaml
  install/helm/gloo/templates/6-access-logger-deployment.yaml
  install/helm/gloo/templates/6-access-logger-service.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/8-gateway-proxy-service.yaml
  install/test/fixtures.go
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  install/test/merge_ingress_values.yaml
  install/test/svc_accnt_test.go
  install/test/values/val_consul_discovery_test_inputs.yaml
  install/test/values/val_consul_test_inputs.yaml
  install/test/values/val_custom_gateways.yaml
  install/test/values/val_default_gateway_access_logging_service.yaml
  install/test/values/val_tracing_provider_cluster.yaml
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#5974 Fix route replacement when service is missing
  changelog/v1.11.0-beta16/fix-invalid-routes.yaml
  projects/gateway/pkg/translator/http_translator.go
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer.go
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer_test.go
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer.go
Labels: keep pr updated

#6011 Fix route replacement when service is missing [1.10]
  changelog/v1.10.12/fix-invalid-routes.yaml
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer.go
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer_test.go
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer.go
Labels: keep pr updated

#5987 [Helm] Move pod-level options out of container config
  changelog/v1.11.0-beta17/helm-gateway-proxy-pod-level-config-fix.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6017 Make default gateways disable-able
  changelog/v1.11.0-beta17/disable-default-gateways.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/8-default-gateways.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6013 Helm update for disabled discovery
  changelog/v1.11.0-beta18/helm-fix-discovery-disabled.yaml
  install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
  install/helm/gloo/templates/3-discovery-service-account.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  install/test/rbac_test.go
Labels: keep pr updated

#6025 Helm update for disabled discovery [1.10]
  changelog/v1.10.13/helm-fix-discovery-disabled.yaml
  install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
  install/helm/gloo/templates/3-discovery-service-account.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  install/test/rbac_test.go
  projects/gateway/pkg/api/v1/kube/apis/gateway.solo.io/v1/zz_generated.deepcopy.go
Labels: keep pr updated

#6030 Disable tests on release builds to improve ci times and reliability
  Makefile
  changelog/v1.11.0-beta18/improve-release-times.yaml
Labels: keep pr updated

#6031 Run tests releases only 1.10
  Makefile
  changelog/v1.10.13/improve-ci-releases-times.yaml
Labels: keep pr updated

#6033 Run tests releases only 1.8
  Makefile
  changelog/v1.8.26/improve-ci-times.yaml
Labels: keep pr updated

#6032 Run tests releases only 1.9
  Makefile
  changelog/v1.9.10/improve-ci-release-times.yaml
Labels: keep pr updated

#6020 Add docs for injecting request header into response
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/inject_response_header/_index.md
Labels: keep pr updated

#6024 ci(regression-tests): added opt-in slack notify-on-failure step
  .github/workflows/notify-on-regression-failure-list.json
  .github/workflows/regression-tests.yaml
  changelog/v1.11.0-beta18/notify-on-failure.yaml
Labels: keep pr updated, 6024

#6036 Deep-merge-upstream-annotation-config
  changelog/v1.11.0-beta18/deep-merge-upstream-annotation-config.yaml
  docs/content/guides/traffic_management/destination_types/discovered_upstream/discovered-upstream-configuration.md
  docs/content/static/content/osa_provided.md
  go.mod
  projects/gloo/pkg/plugins/kubernetes/serviceconverter/general_annotation_converter.go
  projects/gloo/pkg/plugins/kubernetes/uds_convert_test.go
Labels: keep pr updated

#6014 Docs: Expanding the GraphQL section
  changelog/v1.11.0-beta18/docs-graphql.yaml
  docs/content/guides/dev_portal/_index.md
  docs/content/guides/graphql/_index.md
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/guides/graphql/caching.md
  docs/content/guides/graphql/debugging.md
  docs/content/guides/graphql/getting_started.md
  docs/content/guides/graphql/graphql_ui.md
  docs/content/guides/graphql/observability.md
  docs/content/guides/graphql/resolver_config.md
  docs/content/guides/graphql/stitching.md
Labels: keep pr updated

#6040 Backport: Docs: Remove placeholder graphql files
  changelog/v1.10.13/docs-graphql.yaml
  docs/content/guides/dev_portal/_index.md
  docs/content/guides/graphql/_index.md
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/guides/graphql/getting_started.md
  docs/content/guides/graphql/resolver_config.md
  docs/content/guides/traffic_management/request_processing/graphql/_index.md
Labels: keep pr updated

#6038 Backport deep merge for upstream annotation config to v1.10.x
  changelog/v1.10.13/deep-merge-upstream-annotation-config.yaml
  docs/content/guides/traffic_management/destination_types/discovered_upstream/discovered-upstream-configuration.md
  docs/content/static/content/osa_provided.md
  go.mod
  projects/gloo/pkg/plugins/kubernetes/serviceconverter/general_annotation_converter.go
  projects/gloo/pkg/plugins/kubernetes/uds_convert_test.go
Labels: keep pr updated

#6043 Fix indent in discovery service template
  changelog/v1.11.0-beta18/helm-fix-discovery-service.yaml
  install/helm/gloo/templates/3-discovery-service.yaml
Labels: keep pr updated

#6037 Deprecate opaque route metadata
  changelog/v1.11.0-beta18/gateway-route-visitor-optimization.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gateway/pkg/translator/config_source.go
  projects/gateway/pkg/translator/http_translator.go
  projects/gateway/pkg/translator/http_translator_test.go
  projects/gateway/pkg/translator/translator_test.go
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/v1/proxy.pb.clone.go
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.hash.go
Labels: keep pr updated

#6048 ci(regression-tests): added opt-in slack notify-on-failure step (#6024)
  .github/workflows/notify-on-regression-failure-list.json
  .github/workflows/regression-tests.yaml
  changelog/v1.10.14/notify-on-failure.yaml
Labels: keep pr updated

#6050 ci(regression-tests): added opt-in slack notify-on-failure step (#6024)
  .github/workflows/notify-on-regression-failure-list.json
  .github/workflows/regression-tests.yaml
  changelog/v1.8.26/notify-on-failure.yaml
Labels: keep pr updated

#6047 speed up transformation validation
  changelog/v1.11.0-beta18/speed-up-transformation-validation.yaml
  projects/gloo/pkg/plugins/transformation/plugin.go
Labels: keep pr updated

#6053 cherry pick speed-up-gateway-translation
  changelog/v1.10.14/gateway-route-visitor-optimization.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gateway/pkg/translator/config_source.go
  projects/gateway/pkg/translator/http_translator.go
  projects/gateway/pkg/translator/http_translator_test.go
  projects/gateway/pkg/translator/translator_test.go
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/v1/proxy.pb.clone.go
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.hash.go
Labels: keep pr updated

#6045 [1.10] Fix indent in discovery service template
  changelog/v1.10.14/helm-fix-discovery-service.yaml
  install/helm/gloo/templates/3-discovery-service.yaml
Labels: keep pr updated

#6055 feat(docker-compose) add missing setup directory
  changelog/v1.11.0-beta19/docker-compose-repair.yaml
  install/docker-compose-file/prepare-directories.sh
Labels: keep pr updated

#5998 Fix discovery when multiple discoveries apply to a single upstream
  changelog/v1.11.0-beta19/fix-multiple-function-discoveries.yaml
  projects/discovery/pkg/fds/discoveries/aws/aws.go
  projects/discovery/pkg/fds/discoveries/grpc/grpc.go
  projects/discovery/pkg/fds/discoveries/swagger/swagger.go
  projects/discovery/pkg/fds/updater.go
  projects/discovery/pkg/fds/updater_test.go
Labels: keep pr updated

#6054 Dynamic forwarding proxy
  changelog/v1.11.0-beta19/dfp.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/core/v3/resolver.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/network/dns_resolver/apple/v3/apple_dns_resolver.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  docs/data/ProtoMap.yaml
  hack/filter_types/filter_types.gen.go
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/external/envoy/config/core/v3/resolver.proto
  projects/gloo/api/external/envoy/extensions/network/dns_resolver/apple/v3/apple_dns_resolver.proto
  projects/gloo/api/external/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.proto
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.clone.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.hash.go
  projects/gloo/pkg/api/external/envoy/extensions/network/dns_resolver/apple/v3/apple_dns_resolver.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.pb.go
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.clone.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.equal.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.hash.go
  projects/gloo/pkg/api/v1/proxy.pb.clone.go
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.hash.go
  projects/gloo/pkg/plugins/consul/subsets.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/dfp_suite_test.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin_test.go
  projects/gloo/pkg/plugins/pluginutils/headers.go
  projects/gloo/pkg/plugins/pluginutils/per_filter_config.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/route_config.go
  test/e2e/dynamic_forward_proxy_test.go
  test/services/gateway.go
Labels: keep pr updated

#6059 Dynamic forwarding proxy v1.10
  changelog/v1.10.15/dfp.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/core/v3/resolver.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/network/dns_resolver/apple/v3/apple_dns_resolver.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  docs/data/ProtoMap.yaml
  hack/filter_types/filter_types.gen.go
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/external/envoy/config/core/v3/resolver.proto
  projects/gloo/api/external/envoy/extensions/network/dns_resolver/apple/v3/apple_dns_resolver.proto
  projects/gloo/api/external/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.proto
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.clone.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.hash.go
  projects/gloo/pkg/api/external/envoy/extensions/network/dns_resolver/apple/v3/apple_dns_resolver.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.pb.go
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.clone.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.equal.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.hash.go
  projects/gloo/pkg/api/v1/proxy.pb.clone.go
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.hash.go
  projects/gloo/pkg/plugins/consul/subsets.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/dfp_suite_test.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin_test.go
  projects/gloo/pkg/plugins/pluginutils/headers.go
  projects/gloo/pkg/plugins/pluginutils/per_filter_config.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/route_config.go
  test/e2e/dynamic_forward_proxy_test.go
  test/services/gateway.go
Labels: keep pr updated

#6061 Docs: Add version static files
  changelog/v1.10.15/docs-versions.yaml
  docs/content/guides/graphql/getting_started.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
Labels: keep pr updated

#6046 Docs: Bump active versions
  changelog/v1.11.0-beta19/docs-versions.yaml
  docs/active_versions.json
  docs/content/guides/graphql/getting_started.md
  docs/content/guides/observability/prometheus/_index.md
  docs/content/guides/observability/prometheus/metrics.md
  docs/content/introduction/observability.md
  docs/content/introduction/traffic_management/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
Labels: keep pr updated

#6066 Docs: Backport temp rm of prom metrics page
  changelog/v1.10.16/docs-prom-metrics.yaml
  docs/content/guides/observability/prometheus/_index.md
  docs/content/guides/observability/prometheus/metrics.md
  docs/content/introduction/observability.md
  docs/content/static/content/version_geoss_latest.md
Labels: keep pr updated

#6071 main: Fix solo-apis; gloo apis should not be in envoy/external/.. dir
  changelog/v1.11.0-beta19/fix-solo-apis.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto.sk.md
  docs/data/ProtoMap.yaml
  hack/filter_types/filter_types.gen.go
  projects/gloo/api/external/envoy/config/core/v3/resolver.proto
  projects/gloo/api/external/envoy/extensions/network/dns_resolver/apple/v3/apple_dns_resolver.proto
  projects/gloo/api/external/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.proto
  projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.clone.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.hash.go
  projects/gloo/pkg/api/external/envoy/extensions/network/dns_resolver/apple/v3/apple_dns_resolver.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.pb.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.clone.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.equal.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.hash.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin_test.go
Labels: keep pr updated

#6070 Fix solo-apis; gloo apis should not be in envoy/external/.. dir
  changelog/v1.10.16/fix-solo-apis.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto.sk.md
  docs/data/ProtoMap.yaml
  hack/filter_types/filter_types.gen.go
  projects/gloo/api/external/envoy/config/core/v3/resolver.proto
  projects/gloo/api/external/envoy/extensions/network/dns_resolver/apple/v3/apple_dns_resolver.proto
  projects/gloo/api/external/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.proto
  projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.clone.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/resolver.pb.hash.go
  projects/gloo/pkg/api/external/envoy/extensions/network/dns_resolver/apple/v3/apple_dns_resolver.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.pb.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.clone.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.equal.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.hash.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin_test.go
Labels: keep pr updated

#6073 makefile: Upgrade envoy-gloo version for aws fixes
  Makefile
  changelog/v1.11.0-beta20/bump-envoy.yaml
Labels: keep pr updated

#6069 Docs: Backport: Image fix
  changelog/v1.10.17/docs-fix-images.yaml
  docs/content/guides/graphql/getting_started.md
  docs/content/introduction/traffic_management/_index.md
Labels: keep pr updated

#6077 makefile: Upgrade envoy-gloo version for aws fixes
  Makefile
  changelog/v1.10.17/bump-envoy.yaml
Labels: keep pr updated

#6079 expose hcm setting strip_any_host_port
  changelog/v1.11.0-beta20/expose-strip-any-host-port.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.clone.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.equal.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.hash.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
Labels: keep pr updated

#6068 fix: AWS transformations work together with regular transformations
  Makefile
  changelog/v1.11.0-beta20/aws-transform-interaction.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.hash.go
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
  projects/gloo/pkg/plugins/pluginutils/per_filter_config.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  test/e2e/aws_test.go
Labels: keep pr updated

#6080 backport - expose strip_any_host_port
  changelog/v1.10.17/expose-strip-any-host-port.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.clone.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.equal.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.hash.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
Labels: keep pr updated

#6082 Doc/refresh debugging guidelines
  changelog/v1.11.0-beta21/doc-refresh-debugging-tips.yaml
  docs/content/img/envoy-ui.png
  docs/content/operations/debugging_gloo/_index.md
Labels: keep pr updated

#6085 10/feat(docker-compose): repair docker-compose launch script
  Makefile
  changelog/v1.10.17/docker-compose-repair.yaml
  install/docker-compose-file/docker-compose.yaml
  install/docker-compose-file/prepare-directories.sh
Labels: keep pr updated

#6086 8/feat(docker-compose): repair docker-compose launch script
  Makefile
  changelog/v1.8.26/docker-compose-repair.yaml
  install/docker-compose-file/docker-compose.yaml
Labels: keep pr updated

#6087 9/feat(docker-compose): repair docker-compose launch script
  Makefile
  changelog/v1.9.10/docker-compose-repair.yaml
  install/docker-compose-file/docker-compose.yaml
Labels: keep pr updated

#6094 Rename DeepMergeAnnotationPrefix to be a valid Annotation
  changelog/v1.11.0-beta21/fix-annotation-config-merge-annotation.yaml
  docs/content/guides/traffic_management/destination_types/discovered_upstream/discovered-upstream-configuration.md
  projects/gloo/pkg/plugins/kubernetes/serviceconverter/general_annotation_converter.go
Labels: keep pr updated

#5922 gloo/cli/pkg/cmd: Upgrade follows semver instead of temporal structure
  changelog/v1.11.0-beta22/ctl-upgrade-parsing.yaml
  docs/content/reference/cli/glooctl_upgrade.md
  projects/gloo/cli/pkg/cmd/upgrade/cmd.go
  projects/gloo/cli/pkg/cmd/upgrade/cmd_test.go
  projects/gloo/cli/pkg/cmd/upgrade/upgrade_suite_test.go
Labels: keep pr updated

#6101 docs/glooctl fixes for header secrets
  docs/content/guides/traffic_management/request_processing/append_remove_headers/_index.md
  projects/gloo/cli/pkg/printers/secret.go
  projects/gloo/pkg/api/converters/kube/header_secret.go
Labels: keep pr updated

#6102 docs/glooctl fixes for header secrets [1.10]
  docs/content/guides/traffic_management/request_processing/append_remove_headers/_index.md
  projects/gloo/cli/pkg/printers/secret.go
  projects/gloo/pkg/api/converters/kube/header_secret.go
Labels: keep pr updated

#6107 fix typo in gql shortname
  install/helm/gloo/crds/graphql.gloo.solo.io_v1alpha1_GraphQLApi.yaml
  projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graph_ql_api.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.go
Labels: keep pr updated

#6104 Add interpolation for static resources
  changelog/v1.11.0-beta22/static-resource-interpolation.yaml
  projects/envoyinit/cmd/README.md
  projects/envoyinit/cmd/utils/utils.go
  projects/envoyinit/pkg/downward/transform.go
  projects/envoyinit/pkg/downward/transform_test.go
Labels: keep pr updated

#6110 Stitching Control Plane API
  changelog/v1.11.0-beta22/stitching-control-plane-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/graphql/stitching.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/stitching_info.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/graphql.gloo.solo.io_v1alpha1_GraphQLApi.yaml
  install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
  install/helm/gloo/templates/22-namespace-clusterrole-knative.yaml
  install/test/rbac_test.go
  install/test/util.go
  projects/gloo/api/external/envoy/extensions/graphql/stitching.proto
  projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto
  projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/stitching_info.proto
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/graphql/v2/stitching.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/stitching_info.pb.go
Labels: keep pr updated

#6026 [Helm] Update flags for Istio discovery address
  changelog/v1.11.0-beta22/update-flag-for-helm-istio-discovery-address.yaml
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
  docs/content/reference/cli/glooctl_istio_inject.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
  install/test/values/val_custom_istio_sidecar.yaml
  projects/gloo/cli/pkg/cmd/istio/inject.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.6.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7-1.19.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/matcher.go
  projects/gloo/cli/pkg/cmd/istio/util.go
  projects/gloo/cli/pkg/cmd/options/options.go
Labels: keep pr updated

#6117 [Helm] Update flags for Istio discovery address (backport 1.10.x)
  changelog/v1.10.18/update-flag-for-helm-istio-discovery-address.yaml
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
  docs/content/reference/cli/glooctl_istio_inject.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
  install/test/values/val_custom_istio_sidecar.yaml
  projects/gloo/cli/pkg/cmd/istio/inject.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.6.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7-1.19.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/matcher.go
  projects/gloo/cli/pkg/cmd/istio/util.go
  projects/gloo/cli/pkg/cmd/options/options.go
Labels: keep pr updated

#6119 [Helm] Update flags for Istio discovery address (backport 1.9.x)
  changelog/v1.9.11/update-flag-for-helm-istio-discovery-address.yaml
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
  docs/content/reference/cli/glooctl_istio_inject.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
  install/test/values/val_custom_istio_sidecar.yaml
  projects/gloo/cli/pkg/cmd/istio/inject.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.6.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7-1.19.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/matcher.go
  projects/gloo/cli/pkg/cmd/istio/util.go
  projects/gloo/cli/pkg/cmd/options/options.go
Labels: keep pr updated

#6120 [Helm] Update flags for Istio discovery address (backport 1.8.x)
  changelog/v1.8.27/update-flag-for-helm-istio-discovery-address.yaml
  docs/content/guides/integrations/service_mesh/gloo_istio_mtls/_index.md
  docs/content/reference/cli/glooctl_istio_inject.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
  install/test/values/val_custom_istio_sidecar.yaml
  projects/gloo/cli/pkg/cmd/istio/inject.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.6.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7-1.8-1.9-1.10.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/matcher.go
  projects/gloo/cli/pkg/cmd/istio/util.go
  projects/gloo/cli/pkg/cmd/options/options.go
Labels: keep pr updated

#6124 OPA fix comparison operators and remove obsolete version reference
  docs/content/guides/security/auth/extauth/opa/_index.md
Labels: Type: Docs, keep pr updated

#6129 Add changelog
  changelog/v1.11.0-beta23/placeholder.yaml
  changelog/v1.11.0-beta24/placeholder.yaml
Labels: keep pr updated

#6121 Doc version bump
  changelog/v1.11.0-beta24/doc-fixes.yaml
  docs/active_versions.json
  docs/content/reference/api/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#6134 Prep 1.11 RC
  changelog/v1.11.0-rc1/doc-fixes.yaml
  changelog/v1.11.0-rc1/placeholder.yaml
Labels: keep pr updated

#6091 guidelines for OSS users willing to contribute to the documentation
  changelog/v1.11.0-rc2/doc-allow-oss-contributions.yaml
  docs/content/contributing/documentation/editing_locally.md
  docs/content/reference/security-updates/enterprise/_index.md
  docs/content/reference/security-updates/open_source/_index.md
Labels: Type: Docs, keep pr updated

#6133 Mock resolver API
  changelog/v1.11.0-rc2/mock-resolver.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/graphql/graphql.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/graphql.gloo.solo.io_v1alpha1_GraphQLApi.yaml
  projects/gloo/api/external/envoy/extensions/graphql/graphql.proto
  projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/graphql/v2/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.hash.go
Labels: keep pr updated

#6089 new page compiling all the timeout settings
  changelog/v1.11.0-rc2/doc-timeouts-cheatsheet.yaml
  docs/content/reference/cheatsheets/_index.md
  docs/content/reference/cheatsheets/timeouts/_index.md
Labels: Type: Docs, keep pr updated

#6135 Add Instruqt track to the getting started
  changelog/v1.11.0-rc2/doc-instruqt.yaml
  docs/content/getting_started/_index.md
Labels: Type: Docs, keep pr updated

#6123 ui settings
  changelog/v1.11.0-rc2/console-settings.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
Labels: keep pr updated

#6132 Initialize the validation_gateway_solo_io_valid_config metric to 1
  changelog/v1.11.0-rc2/initialize-valid-config-metric.yaml
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#6145 (v1.10.x) Bump alpine to 3.13.8
  changelog/v1.10.18/bump-alpine.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6147 (v1.8.x) Bump alpine to 3.13.8
  changelog/v1.8.27/bump-alpine.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6150 Doc fixes for logo and formatting
  changelog/v1.11.0-rc3/doc-fixes.yaml
  docs/content/getting_started/_index.md
  docs/content/img/Gloo-01-350-by-65.png
  docs/docs.toml
Labels: Type: Docs, keep pr updated

#6142 Bump alpine to v3.13.8
  changelog/v1.11.0-rc3/bump-alpine.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6154 (v1.10.x) Initialize the validation_gateway_solo_io_valid_config metric
  changelog/v1.10.18/initialize-valid-config-metric.yaml
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#6156 (v1.8.x) Initialize the validation_gateway_solo_io_valid_config metric
  changelog/v1.8.27/initialize-valid-config-metric.yaml
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#6155 (v1.9.x) Initialize the validation_gateway_solo_io_valid_config metric
  changelog/v1.9.11/initialize-valid-config-metric.yaml
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
Labels: keep pr updated

#6159 Include app=gloo label on gateway proxy services
  install/helm/gloo/templates/8-gateway-proxy-service.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6160 Include app=gloo label on gateway proxy services
  install/helm/gloo/templates/8-gateway-proxy-service.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6166 10/fix(ssl.go): prevent isValidSslKeyPair with only rootCa
  changelog/v1.10.18/less-strict-ssl-validation.yaml
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: keep pr updated

#6165 master/fix(ssl.go): prevent isValidSslKeyPair with only rootCa
  changelog/v1.11.0-rc3/less-strict-ssl-validation.yaml
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: keep pr updated

#6157 Renames doc files that have patch versions to remove the patch version
  changelog/v1.11.0-rc3/doc-file-names.yaml
  docs/content/operations/production_deployment/_index.md
  docs/content/operations/upgrading/faq.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/operations/upgrading/v0.18.md
  docs/content/operations/upgrading/v1.0.md
  docs/content/operations/upgrading/v1.10.md
  docs/content/operations/upgrading/v1.3.md
  docs/content/operations/upgrading/v1.4.md
  docs/content/operations/upgrading/v1.5.md
  docs/content/operations/upgrading/v1.7.md
  docs/content/operations/upgrading/v1.8.md
  docs/content/operations/upgrading/v1.9.md
Labels: Type: Docs, keep pr updated

#6164 plugins/transformations: Update error handling logic on successful transforms
  changelog/v1.11.0-rc3/glooctl-check-versions.yaml
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/transformation/plugin_test.go
Labels: keep pr updated

#6167 Backport fix for ca bundle in validating webhook configuration
  changelog/v1.10.19/fix-certgen-Cabundle.yaml
  jobs/pkg/run/run.go
Labels: keep pr updated

#6176 Backport doc updates to 1.8.x
  changelog/v1.8.27/doc-fixes.yaml
  docs/content/getting_started/_index.md
  docs/content/img/Gloo-01-350-by-65.png
  docs/docs.toml
Labels: Type: Docs, keep pr updated

#6174 Backport doc updates to 1.10.x
  changelog/v1.10.19/doc-fixes.yaml
  docs/content/getting_started/_index.md
  docs/content/img/Gloo-01-350-by-65.png
  docs/docs.toml
Labels: Type: Docs, keep pr updated

#6175 Backport doc updates to 1.9.x
  changelog/v1.9.11/doc-fixes.yaml
  docs/content/getting_started/_index.md
  docs/content/img/Gloo-01-350-by-65.png
  docs/docs.toml
Labels: Type: Docs, keep pr updated

#6173 Small CONTRIBUTING.md updates to better match Gloo's current state
  CONTRIBUTING.md
Labels: keep pr updated

#6181 Upgrade moby/moby for CVE-2014-9356
  changelog/v1.11.0-rc4/bump-moby.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#6169 Add SameSite
  changelog/v1.11.0-rc4/add-samesite.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6182 [1.10] Upgrade moby/moby for CVE-2014-9356
  changelog/v1.10.19/bump-moby.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#6183 [1.9] Upgrade moby/moby for CVE-2014-9356
  changelog/v1.9.11/bump-moby.yaml
  go.mod
  go.sum
Labels: keep pr updated

#6140 Expose Envoy's UuidRequestIdConfig in HCM
  changelog/v1.11.0-rc4/expose-envoy-uuidrequestid.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.clone.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.equal.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.hash.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
Labels: keep pr updated

#6186 introduce graphql sensitive logging api
  changelog/v1.11.0-rc4/chanelog.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/graphql/graphql.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto.sk.md
  install/helm/gloo/crds/graphql.gloo.solo.io_v1alpha1_GraphQLApi.yaml
  projects/gloo/api/external/envoy/extensions/graphql/graphql.proto
  projects/gloo/api/v1/enterprise/options/graphql/v1alpha1/graphql.proto
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/graphql/v2/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1alpha1/graphql.pb.hash.go
Labels: keep pr updated

#6191 CI(docs): cat out security utils file
  changelog/v1.11.0-rc5/docs-debug.yaml
  docs/Makefile
Labels: keep pr updated

#6197 [1.10] Make default gateways disable-able
  changelog/v1.10.20/disable-default-gateways.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/8-default-gateways.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6188 Added Default Value to SameSite
  changelog/v1.11.0-rc5/add-default-value-samesite.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#6192 Bump doc versions
  changelog/v1.11.0-rc5/docs-bump-version.yaml
  docs/active_versions.json
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#6194 Docs: Upgrade guide updates
  changelog/v1.11.0-rc6/doc-upgrade-guide.yaml
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/gloo_federation.md
  docs/content/installation/ingress/_index.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/operations/upgrading/v1.11.md
  docs/content/static/content/upgrade-crd.md
Labels: keep pr updated
