Repository kgateway-dev/kgateway, pull requests merged in 2022-05, with the labels that each got.

#6395 Doc fixes
  changelog/v1.12.0-beta9/doc-fixes.yaml
  docs/active_versions.json
  docs/content/guides/graphql/stitching.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#6396 Doc fixes and backports for 1.11.x
  changelog/v1.11.8/doc-fixes.yaml
  docs/active_versions.json
  docs/content/guides/graphql/getting_started.md
  docs/content/guides/graphql/resolver_config.md
  docs/content/guides/graphql/stitching.md
  docs/content/guides/graphql/stitching.txt
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#6405 Waf dlp docs update
  changelog/v1.12.0-beta9/waf-dlp-doc-fixes.yaml
  docs/Makefile
  docs/content/guides/security/data_loss_prevention/_index.md
  docs/content/guides/security/waf/_index.md
Labels: keep pr updated

#6404 Split http_gateway and matchable_http_gateway into separate files
  changelog/v1.12.0-beta9/split-gateway-protos.yaml
  docs/content/reference/api/envoy.glooe.solo.io.project.sk.md
  docs/content/reference/api/gateway.solo.io.project.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/http_gateway.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/matchable_http_gateway.proto.sk.md
  docs/content/reference/api/gloo.solo.io.project.sk.md
  docs/content/reference/api/glooe.solo.io.project.sk.md
  docs/data/ProtoMap.yaml
  projects/gateway/api/v1/http_gateway.proto
  projects/gateway/api/v1/matchable_http_gateway.proto
  projects/gateway/pkg/api/v1/http_gateway.pb.clone.go
  projects/gateway/pkg/api/v1/http_gateway.pb.equal.go
  projects/gateway/pkg/api/v1/http_gateway.pb.go
  projects/gateway/pkg/api/v1/http_gateway.pb.hash.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.pb.clone.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.pb.equal.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.pb.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.pb.hash.go
Labels: keep pr updated

#6349 Fix Gloo Edge install when failurePolicy is Fail
  changelog/v1.12.0-beta9/failure-policy-fail.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-gateway-cleanup-job.yaml
  install/helm/gloo/templates/5-gateway-validation-rollout-job.yaml
  install/helm/gloo/templates/8-default-gateways.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  jobs/pkg/certgen/gen_certs.go
  jobs/pkg/kube/secret.go
  jobs/pkg/kube/secret_test.go
  jobs/pkg/run/run.go
  test/kube2e/helm/helm_suite_test.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#6407 helm docs updates
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
Labels: keep pr updated

#6411 RemoveUnusedFilters evaluated per HttpListener
  changelog/v1.12.0-beta10/unused-filters-followup.yaml
  projects/gateway/pkg/utils/metrics/metrics.go
  projects/gloo/cli/pkg/cmd/install/util.go
  projects/gloo/pkg/plugins/cors/plugin.go
  projects/gloo/pkg/plugins/csrf/plugin.go
  projects/gloo/pkg/plugins/csrf/plugin_test.go
  projects/gloo/pkg/plugins/faultinjection/plugin.go
  projects/gloo/pkg/plugins/grpcweb/plugin.go
  projects/gloo/pkg/plugins/registry/registry_test.go
  projects/gloo/pkg/plugins/transformation/plugin.go
Labels: keep pr updated

#6413 [1.11] Recent HttpGateway Improvements
  changelog/v1.11.8/unused-filters-followup.yaml
  docs/content/reference/api/envoy.glooe.solo.io.project.sk.md
  docs/content/reference/api/gateway.solo.io.project.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/http_gateway.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/matchable_http_gateway.proto.sk.md
  docs/content/reference/api/gloo.solo.io.project.sk.md
  docs/content/reference/api/glooe.solo.io.project.sk.md
  docs/data/ProtoMap.yaml
  projects/gateway/api/v1/http_gateway.proto
  projects/gateway/api/v1/matchable_http_gateway.proto
  projects/gateway/pkg/api/v1/http_gateway.pb.clone.go
  projects/gateway/pkg/api/v1/http_gateway.pb.equal.go
  projects/gateway/pkg/api/v1/http_gateway.pb.go
  projects/gateway/pkg/api/v1/http_gateway.pb.hash.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.pb.clone.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.pb.equal.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.pb.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.pb.hash.go
  projects/gateway/pkg/utils/metrics/metrics.go
  projects/gloo/cli/pkg/cmd/install/util.go
  projects/gloo/pkg/plugins/cors/plugin.go
  projects/gloo/pkg/plugins/csrf/plugin.go
  projects/gloo/pkg/plugins/csrf/plugin_test.go
  projects/gloo/pkg/plugins/faultinjection/plugin.go
  projects/gloo/pkg/plugins/grpcweb/plugin.go
  projects/gloo/pkg/plugins/registry/registry_test.go
  projects/gloo/pkg/plugins/transformation/plugin.go
Labels: keep pr updated

#6414 feat(DelegatedHttpGateway): allow top-level config setting/sharing
  changelog/v1.11.9/5993-gateway-config-lift.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  projects/gateway/api/v1/gateway.proto
  projects/gateway/pkg/api/v1/gateway.pb.clone.go
  projects/gateway/pkg/api/v1/gateway.pb.equal.go
  projects/gateway/pkg/api/v1/gateway.pb.go
  projects/gateway/pkg/api/v1/gateway.pb.hash.go
  projects/gateway/pkg/translator/hybrid_translator.go
  projects/gateway/pkg/translator/hybrid_translator_test.go
Labels: keep pr updated

#6394 feat(DelegatedHttpGateway): allow top-level config setting/sharing
  changelog/v1.12.0-beta11/5993-gateway-config-lift.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  projects/gateway/api/v1/gateway.proto
  projects/gateway/pkg/api/v1/gateway.pb.clone.go
  projects/gateway/pkg/api/v1/gateway.pb.equal.go
  projects/gateway/pkg/api/v1/gateway.pb.go
  projects/gateway/pkg/api/v1/gateway.pb.hash.go
  projects/gateway/pkg/translator/hybrid_translator.go
  projects/gateway/pkg/translator/hybrid_translator_test.go
Labels: keep pr updated

#6416 fix cleanup job
  changelog/v1.12.0-beta11/fix-cleanup-job.yaml
  docs/content/guides/dev/example-proxy-controller.md
  install/helm/gloo/templates/5-gateway-cleanup-job.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
  projects/gloo/pkg/syncer/setup/proxy_cleanup.go
  projects/gloo/pkg/syncer/setup/proxy_cleanup_test.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#6419 Doc fixes and version bump
  changelog/v1.12.0-beta12/doc-fixes.yaml
  docs/active_versions.json
  docs/content/guides/graphql/resolver_config.md
  docs/content/guides/graphql/stitching.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#6426 failurePolicy=Fail backports [1.11]
  changelog/v1.11.10/failure-policy-backports.yaml
  docs/content/guides/dev/example-proxy-controller.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-gateway-cleanup-job.yaml
  install/helm/gloo/templates/5-gateway-validation-rollout-job.yaml
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/templates/8-default-gateways.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  jobs/pkg/certgen/gen_certs.go
  jobs/pkg/kube/secret.go
  jobs/pkg/kube/secret_test.go
  jobs/pkg/run/run.go
  test/kube2e/helm/helm_suite_test.go
  test/kube2e/helm/helm_test.go
  test/kube2e/knative/knative_manual_tls_test.go
Labels: keep pr updated

#6431 Fix for robustness test flake
  changelog/v1.12.0-beta12/robustness_test_fix.yaml
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#6432 Backport option to truncate proxy statuses to 1.11
  changelog/v1.11.10/proxy_status_size.yaml
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/api/compress/compress.go
  projects/gloo/pkg/api/compress/compress_test.go
Labels: keep pr updated

#6433 Backport option to truncate long status messages to v1.8
  changelog/v1.8.28/proxy_status_size.yaml
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_test.go
  projects/gloo/cli/pkg/cmd/add/add_suite_test.go
  projects/gloo/cli/pkg/cmd/create/authconfig/authconfig_suite_test.go
  projects/gloo/cli/pkg/cmd/create/create_suite_test.go
  projects/gloo/cli/pkg/cmd/create/secret/secret_suite_test.go
  projects/gloo/cli/pkg/cmd/debug/debug_suite_test.go
  projects/gloo/cli/pkg/cmd/del/del_suite_test.go
  projects/gloo/cli/pkg/cmd/edit/route/ratelimit/ratelimit_suite_test.go
  projects/gloo/cli/pkg/cmd/edit/route/route_suite_test.go
  projects/gloo/cli/pkg/cmd/edit/settings/config_suite_test.go
  projects/gloo/cli/pkg/cmd/edit/settings/ratelimit/ratelimit_suite_test.go
  projects/gloo/cli/pkg/cmd/edit/upstream/upstream_suite_test.go
  projects/gloo/cli/pkg/cmd/edit/virtualservice/virtualservice_suite_test.go
  projects/gloo/cli/pkg/cmd/gateway/gateway_suite_test.go
  projects/gloo/cli/pkg/cmd/get/get_suite_test.go
  projects/gloo/cli/pkg/cmd/install/install_suite_test.go
  projects/gloo/cli/pkg/cmd/remove/remove_suite_test.go
  projects/gloo/cli/pkg/cmd/route/route_suite_test.go
  projects/gloo/cli/pkg/cmd/version/version_suite_test.go
  projects/gloo/cli/pkg/helpers/helpers_suite_test.go
  projects/gloo/cli/pkg/prerun/prerun_suite_test.go
  projects/gloo/cli/pkg/printers/printers_suite_test.go
  projects/gloo/cli/pkg/surveyutils/surveyutils_suite_test.go
  projects/gloo/cli/test/test_suite_test.go
  projects/gloo/pkg/api/compress/compress.go
  projects/gloo/pkg/api/compress/compress_test.go
Labels: keep pr updated

#6440 Backport fix to truncate proxy statuses
  changelog/v1.9.14/proxy_status_size.yaml
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/api/compress/compress.go
  projects/gloo/pkg/api/compress/compress_test.go
Labels: keep pr updated

#6441 Istio compat - use kub service ip for upstreams
  changelog/v1.12.0-beta13/istio-ip-routing.yaml
  install/helm/gloo/templates/1-gloo-deployment.yaml
  projects/gloo/pkg/plugins/kubernetes/eds.go
  projects/gloo/pkg/plugins/kubernetes/eds_test.go
Labels: keep pr updated

#6448 test: Try retrying on access log streaming for unready upstreams
  changelog/v1.12.0-beta13/retries-grpc-stream.yaml
  test/e2e/access_log_test.go
Labels: keep pr updated

#6437 mod: go-utils bump for scanning changes
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.12.0-beta13/go-utils-for-scans.yaml
  docs/cmd/securityscanutils/README.md
  go.mod
  go.sum
Labels: keep pr updated

#6446 gloo/cli/cmd/install: Update the error message on enterprise install
  changelog/v1.12.0-beta13/ctl-install-error-str.yaml
  projects/gloo/cli/pkg/cmd/install/installer.go
Labels: keep pr updated

#6428 API support for KeyValueMatcher
  changelog/v1.12.0-beta13/key-value-action.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/dlp/dlp.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto
  projects/gloo/api/v1/enterprise/options/dlp/dlp.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation_ee/transformation.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.hash.go
Labels: keep pr updated

#6443 DLP/WAF integration API changes
  changelog/v1.12.0-beta13/dlp-in-waf.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/waf/waf.proto.sk.md
  projects/gloo/api/external/envoy/extensions/waf/waf.proto
  projects/gloo/pkg/api/external/envoy/extensions/waf/waf.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/waf/waf.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/waf/waf.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/waf/waf.pb.hash.go
Labels: keep pr updated

#6412 Feature/caching service
  changelog/v1.12.0-beta14/caching-service.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/cache/grpc/config.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/caching/caching.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/data/ProtoMap.yaml
  hack/filter_types/filter_types.gen.go
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/external/envoy/extensions/cache/grpc/config.proto
  projects/gloo/api/v1/enterprise/options/caching/caching.proto
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/external/envoy/extensions/cache/grpc/config.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/caching/caching.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/caching/caching.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/caching/caching.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/caching/caching.pb.hash.go
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/plugins/enterprise_warning/plugin.go
Labels: keep pr updated

#6333 Update Gloo Edge Consul+Vault Docs
  docs/content/installation/gateway/development/docker-compose-consul/_index.md
  docs/content/installation/gateway/nomad/_index.md
Labels: keep pr updated

#6442 Fix DLP proto comments to reflect changes in solo-projects regex patterns
  changelog/v1.12.0-beta15/dlp-re2.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/dlp/dlp.proto.sk.md
  projects/gloo/api/v1/enterprise/options/dlp/dlp.proto
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.go
Labels: keep pr updated

#6451 V1.11: API support for KeyValueMatcher
  changelog/v1.11.11/key-value-action.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/dlp/dlp.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/external/envoy/extensions/transformation_ee/transformation.proto
  projects/gloo/api/v1/enterprise/options/dlp/dlp.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation_ee/transformation.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/dlp/dlp.pb.hash.go
Labels: work in progress, keep pr updated

#6465 Reconcile Proxies using both new and old labels
  changelog/v1.12.0-beta15/set-based-proxy-label-selection.yaml
  go.mod
  go.sum
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/gateway/pkg/reconciler/proxy_reconciler.go
  projects/gateway/pkg/reconciler/proxy_reconciler_test.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/ingress/pkg/translator/translator_syncer.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#6458 Doc fixes 1.11.x
  docs/content/img/screenshots/graphql_details.png
  docs/content/img/screenshots/graphql_ov.png
  docs/content/img/screenshots/graphql_resolver.png
Labels: keep pr updated

#6455 graphql inspector settings api
  changelog/v1.12.0-beta15/graphql-inspector-settings.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1beta1/stitching_info.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  projects/gloo/api/v1/enterprise/options/graphql/v1beta1/stitching_info.proto
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/stitching_info.pb.go
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
Labels: keep pr updated

#6461 [1.11] Reconcile Proxies using both new and old labels
  changelog/v1.11.11/set-based-proxy-label-selection.yaml
  go.mod
  go.sum
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/gateway/pkg/reconciler/proxy_reconciler.go
  projects/gateway/pkg/reconciler/proxy_reconciler_test.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/ingress/pkg/translator/translator_syncer.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#6468 [1.10] Reconcile Proxies using both new and old labels
  changelog/v1.10.25/set-based-proxy-label-selection.yaml
  go.mod
  go.sum
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/gateway/pkg/reconciler/proxy_reconciler.go
  projects/gateway/pkg/reconciler/proxy_reconciler_test.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/ingress/pkg/translator/translator_syncer.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#6469 [1.9] Reconcile Proxies using both new and old labels
  changelog/v1.9.15/set-based-proxy-selection.yaml
  go.mod
  go.sum
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/gateway/pkg/reconciler/proxy_reconciler.go
  projects/gateway/pkg/reconciler/proxy_reconciler_test.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/ingress/pkg/translator/translator_syncer.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#6471 fix broken xDS github link and point to correct new location
  docs/content/introduction/architecture/_index.md
Labels: keep pr updated

#6475 placeholder for 1.11.12
  changelog/v1.11.12/placeholder.yaml
Labels: keep pr updated

#6481 bump to 18.2
  .github/workflows/codegen.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.12.0-beta16/bump-go.yaml
  cloudbuild-cache.yaml
Labels: keep pr updated

#6488 Doc fixes
  docs/active_versions.json
  docs/content/guides/graphql/stitching.md
  docs/content/guides/observability/prometheus/_index.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#6484 [docs] add note about mtls certgen cronjob
  docs/content/guides/security/tls/mtls/_index.md
Labels: Type: Docs, keep pr updated

#6489 Doc fixes (backport of #6488)
  docs/content/guides/graphql/stitching.md
  docs/content/guides/observability/prometheus/_index.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#6483 Add READMEs around Envoy receiving static and dynamic configuration
  changelog/v1.12.0-beta17/envoy-readmes.yaml
  projects/envoyinit/README.md
  projects/envoyinit/cmd/README.md
  projects/envoyinit/cmd/main.go
  projects/envoyinit/cmd/utils/utils.go
  projects/envoyinit/hack/envoy.yaml
  projects/envoyinit/hack/filter_types/filter_types.gen.go
  projects/envoyinit/hack/filter_types/filter_types.go
  projects/gloo/cli/pkg/xdsinspection/get_last_config.go
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/xds/README.md
  projects/gloo/pkg/xds/cache.go
  projects/gloo/pkg/xds/envoy.go
  projects/gloo/pkg/xds/envoy_server_v3.go
  projects/gloo/pkg/xds/fallback_snapshot.go
  projects/gloo/pkg/xds/utils.go
  test/e2e/README.md
Labels: keep pr updated

#6502 Tracing update
  docs/content/guides/observability/tracing.md
Labels: work in progress, keep pr updated

#6506 fix-tracing
  docs/content/guides/observability/tracing.md
Labels: keep pr updated

#6507 Tracing fixes
  docs/content/guides/observability/tracing.md
Labels: keep pr updated

#6508 Docs: Add CRD info to canary upgrade
  changelog/v1.12.0-beta17/docs-canary.yaml
  docs/content/operations/upgrading/canary.md
  docs/content/operations/upgrading/v1.10.md
  docs/content/operations/upgrading/v1.11.md
Labels: keep pr updated

#6510 Docs: Add note about prefix matching to header matcher doc
  changelog/v1.12.0-beta17/docs-canary copy.yaml
  docs/content/guides/traffic_management/destination_selection/header_matching/_index.md
Labels: keep pr updated

#6511 Doc backport to 1.10.x
  changelog/v1.10.26/doc-backport.yaml
  docs/content/guides/observability/tracing.md
  docs/content/operations/upgrading/1.10.0.md
  docs/content/operations/upgrading/canary.md
Labels: Type: Docs, keep pr updated

#6512 Doc backport to 1.11.x
  changelog/v1.11.13/doc-backport.yaml
  docs/content/guides/observability/tracing.md
  docs/content/operations/upgrading/canary.md
  docs/content/operations/upgrading/v1.10.md
  docs/content/operations/upgrading/v1.11.md
Labels: Type: Docs, keep pr updated
