Repository kgateway-dev/kgateway, pull requests merged in 2022-08, with the labels that each got.

#6831 Placeholder changelog for 1.12.0
  changelog/v1.12.0/placeholder.yaml
Labels: keep pr updated

#6829 Docs - change name back so backported branch logos work
  changelog/v1.12.1/doc-logo.yaml
  docs/content/img/Gloo-01-350-by-65.png
  docs/docs.toml
Labels: Type: Docs, keep pr updated

#6836 Add key_prefix to InternalSession - 1.11 backport
  changelog/v1.11.26/add-key-prefix-to-extauth-cookies.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6841 Add key_prefix to InternalSession - 1.8 backport
  changelog/v1.8.37/add-key-prefix-to-extauth-cookies.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6839 Add key_prefix to InternalSession - 1.10 backport
  changelog/v1.10.35/add-key-prefix-to-extauth-cookies.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6845 Add logo for readme
  docs/content/img/Gloo-01.png
Labels: Type: Docs, keep pr updated

#6832 Add changelog
  changelog/v1.13.0-beta1/placeholder.yaml
Labels: keep pr updated

#6846 Docs: Caching
  docs/content/guides/traffic_management/listener_configuration/caching.md
  docs/content/installation/enterprise/_index.md
Labels: keep pr updated

#6800 LDAP Proto
  changelog/v1.12.1/doc-logo.yaml
  changelog/v1.13.0-beta1/ldap.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6851 Docs version bumps for 1.12
  docs/active_versions.json
  docs/content/guides/integrations/aws/_index.md
  docs/content/guides/integrations/datadog/_index.md
  docs/content/guides/security/tls/client_tls.md
  docs/content/guides/security/waf/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/xslt_transformation/_index.md
  docs/content/installation/advanced_configuration/multiple-gloo-installs.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/operations/advanced/zero-downtime-gateway-rollout/_index.md
  docs/content/operations/production_deployment/_index.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#6850 update bitnami/kubectl image [1.11]
  changelog/v1.11.27/update-bitnami-image.yaml
  docs/content/reference/values.txt
  install/helm/gloo/values-template.yaml
Labels: keep pr updated

#6849 update bitnami/kubectl image [1.12]
  changelog/v1.12.1/update-bitnami-image.yaml
  docs/content/reference/values.txt
  install/helm/gloo/values-template.yaml
Labels: keep pr updated

#6848 update bitnami/kubectl image
  changelog/v1.13.0-beta1/update-bitnami-image.yaml
  docs/content/reference/values.txt
  install/helm/gloo/values-template.yaml
Labels: keep pr updated

#6864 ci: added hack script to compress changelogs by minor version
  changelog/v1.13.0-beta1/changelog-compressor.yaml
  hack/squash-changelogs.sh
Labels: keep pr updated

#6865 Doc fixes
  docs/active_versions.json
  docs/content/installation/glooctl_setup.md
Labels: keep pr updated

#6844 Add config for fail-on-redirect
  changelog/v1.13.0-beta1/extauth-fail-on-redirect.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6853 Trivyignore on master
  .trivyignore
  changelog/v1.13.0-beta2/trivyignore.yaml
Labels: keep pr updated

#6859 Kubectl image
  Makefile
  changelog/v1.13.0-beta2/kubectl-image.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate.go
  install/helm/gloo/values-template.yaml
  jobs/kubectl/Dockerfile
Labels: keep pr updated

#6861 Set Ipv4Compat only on listeners with Ipv6 bind address
  changelog/v1.13.0-beta2/ipv4-legacy-support.yaml
  projects/gloo/pkg/translator/listener.go
  projects/gloo/pkg/translator/utils.go
  projects/gloo/pkg/translator/utils_test.go
Labels: keep pr updated

#6877 Logo fix
  docs/content/img/Gloo-01-350-by-65.png
  docs/content/operations/upgrading/v1.12.md
Labels: keep pr updated

#6822 Add Timeout to Jobs
  changelog/v1.13.0-beta2/activeDeadlineSeconds.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6886 Add internal config field for fail-on-redirect
  changelog/v1.13.0-beta2/extauth-fail-on-redirect-patch.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6889 v1.12.x LDAP Proto
  changelog/v1.12.2/LDAP.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6890 v1.10.x LDAP Proto
  changelog/v1.10.36/ldap.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6892 v1.9.x LDAP Proto
  changelog/v1.9.23/ldap.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6879 bump go-utils to nil-notes-errors branch
  changelog/v1.13.0-beta3/go-utils-bump.yaml
  go.mod
  go.sum
Labels: keep pr updated

#6863 [1.11] Add config for fail-on-redirect
  Makefile
  changelog/v1.11.27/extauth-fail-on-redirect.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6891 Back1.12/ipv4 only compat
  changelog/v1.12.2/ipv4-legacy-support.yaml
  projects/gloo/pkg/translator/listener.go
  projects/gloo/pkg/translator/utils.go
  projects/gloo/pkg/translator/utils_test.go
Labels: keep pr updated

#6903 Kubectl image [1.12]
  Makefile
  changelog/v1.12.3/kubectl-image.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate.go
  install/helm/gloo/values-template.yaml
  jobs/kubectl/Dockerfile
Labels: keep pr updated

#6904 Kubectl image [1.11]
  Makefile
  changelog/v1.11.28/kubectl-image.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate.go
  install/helm/gloo/values-template.yaml
  jobs/kubectl/Dockerfile
Labels: keep pr updated

#6852 fix(static/plugin.go): prevent auto-overwrite for host-level HC's
  changelog/v1.13.0-beta3/static-upstream-host-healthchecks.yaml
  projects/gloo/pkg/plugins/static/plugin.go
  projects/gloo/pkg/plugins/static/plugin_test.go
Labels: keep pr updated

#6909 10 | fix(static/plugin.go): prevent auto-overwrite for host-level HC's
  changelog/v1.10.36/static-upstream-host-healthchecks.yaml
  projects/gloo/pkg/plugins/static/plugin.go
  projects/gloo/pkg/plugins/static/plugin_test.go
Labels: keep pr updated

#6907 12 | fix(static/plugin.go): prevent auto-overwrite for host-level HC's
  changelog/v1.12.3/static-upstream-host-healthchecks.yaml
  projects/gloo/pkg/plugins/static/plugin.go
  projects/gloo/pkg/plugins/static/plugin_test.go
Labels: keep pr updated

#6910 9 | fix(static/plugin.go): prevent auto-overwrite for host-level HC's
  changelog/v1.9.23/static-upstream-host-healthchecks.yaml
  projects/gloo/pkg/plugins/static/plugin.go
  projects/gloo/pkg/plugins/static/plugin_test.go
Labels: keep pr updated

#6908 11 | fix(static/plugin.go): prevent auto-overwrite for host-level HC's
  changelog/v1.11.28/static-upstream-host-healthchecks.yaml
  projects/gloo/pkg/plugins/static/plugin.go
  projects/gloo/pkg/plugins/static/plugin_test.go
Labels: keep pr updated

#6902 Helm customization for rollout/migration/cleanup jobs
  changelog/v1.13.0-beta3/helm-job-customization.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6915 Helm customization for rollout/migration/cleanup jobs [1.12]
  changelog/v1.12.3/helm-job-customization.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6916 Helm customization for rollout/migration/cleanup jobs [1.11]
  changelog/v1.11.28/helm-job-customization.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6895 Set MaxCallSendMsgSize on proxy debug client
  changelog/v1.13.0-beta4/proxy-max-size-checking.yaml
  projects/gloo/cli/pkg/common/get.go
Labels: keep pr updated

#6919 Restore PluginRegistryFactory
  changelog/v1.13.0-beta4/plugin-registry-factory.yaml
  projects/gloo/pkg/plugins/plugins.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/plugins/registry/registry_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/validation/server_test.go
  test/benchmark/snapshot_benchmark_test.go
  test/kube2e/gloo/setup_syncer_test.go
Labels: keep pr updated

#6917 buildSds() creates GoogleGrpc TargetSpecifier if TargetUri is not empty
  changelog/v1.13.0-beta5/target-uri-fix.yaml
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: keep pr updated

#6923 v1.12.x Set MaxCallSendMsgSize on proxy debug client
  changelog/v1.12.4/proxy-max-size-checking.yaml
  projects/gloo/cli/pkg/common/get.go
Labels: keep pr updated

#6924 Backport for PluginRegistry fix
  changelog/v1.12.4/plugin-registry-factory.yaml
  projects/gloo/pkg/plugins/plugins.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/plugins/registry/registry_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/validation/server_test.go
  test/benchmark/snapshot_benchmark_test.go
  test/kube2e/gloo/setup_syncer_test.go
Labels: keep pr updated

#6931 Fix target uri 1.9
  changelog/v1.9.23/target-uri-fix.yaml
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: keep pr updated

#6929 Fix target uri 1.11
  changelog/v1.11.29/target-uri-fix.yaml
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: keep pr updated

#6928 Fix target uri 1.12
  changelog/v1.12.4/target-uri-fix.yaml
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: keep pr updated

#6882 Add target domain to extauth proto
  changelog/v1.13.0-beta5/add-target-domain-to-extauth-cookies.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: work in progress, keep pr updated

#6937 placeholder for release [1.12]
  changelog/v1.12.5/placeholder.yaml
Labels: keep pr updated

#6918 Doc fixes
  docs/content/guides/security/waf/_index.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/development/docker-compose-consul/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/operations/upgrading/v1.12.md
  docs/content/reference/support.md
Labels: keep pr updated

#6947 1.11 auto map for meta data 6782
  changelog/v1.11.30/oidc-dynamic-values.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#6948 Doc fixes 1.12.x
  docs/active_versions.json
  docs/content/guides/security/waf/_index.md
  docs/content/guides/traffic_management/listener_configuration/caching.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/development/docker-compose-consul/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/operations/upgrading/v1.12.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#6926 Introduce Leader Election for Gloo
  changelog/v1.13.0-beta6/gloo-leader-election.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
  install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
  install/test/rbac_test.go
  install/test/util.go
  pkg/bootstrap/leaderelector/election_factory.go
  pkg/bootstrap/leaderelector/identity.go
  pkg/bootstrap/leaderelector/kube/factory.go
  pkg/bootstrap/leaderelector/kube/metrics.go
  pkg/bootstrap/leaderelector/kube/provider.go
  pkg/bootstrap/leaderelector/singlereplica/factory.go
  pkg/utils/namespaces.go
  pkg/utils/setuputils/main_setup.go
  pkg/utils/setuputils/setup_syncer.go
  pkg/utils/setuputils/setup_syncer_test.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_integration_test.go
  projects/gateway/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/api/converters/kube/artifact_converter.go
  projects/gloo/pkg/bootstrap/opts.go
  projects/gloo/pkg/setup/setup.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  projects/ingress/pkg/setup/setup_syncer.go
  test/helpers/input_resources.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gateway/robustness_test.go
  test/kube2e/gloo/setup_syncer_test.go
  test/kube2e/util.go
  test/services/gateway.go
Labels: keep pr updated

#6952 Remove default activeDeadlineSeconds from jobs [1.12]
  changelog/v1.12.6/remove-default-activedeadline.yaml
  docs/content/reference/values.txt
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6951 Remove default activeDeadlineSeconds from jobs
  changelog/v1.13.0-beta6/remove-default-activedeadline.yaml
  docs/content/reference/values.txt
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6953 Remove default activeDeadlineSeconds from jobs [1.11]
  changelog/v1.11.31/remove-default-activedeadline.yaml
  docs/content/reference/values.txt
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#6954 Back 1.12/leader elect
  .github/workflows/regression-tests.yaml
  changelog/v1.12.6/gloo-leader-election.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
  install/helm/gloo/templates/23-namespace-clusterrolebinding-gateway.yaml
  install/test/rbac_test.go
  install/test/util.go
  pkg/bootstrap/leaderelector/election_factory.go
  pkg/bootstrap/leaderelector/identity.go
  pkg/bootstrap/leaderelector/kube/factory.go
  pkg/bootstrap/leaderelector/kube/metrics.go
  pkg/bootstrap/leaderelector/kube/provider.go
  pkg/bootstrap/leaderelector/singlereplica/factory.go
  pkg/utils/namespaces.go
  pkg/utils/setuputils/main_setup.go
  pkg/utils/setuputils/setup_syncer.go
  pkg/utils/setuputils/setup_syncer_test.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_integration_test.go
  projects/gateway/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/api/converters/kube/artifact_converter.go
  projects/gloo/pkg/bootstrap/opts.go
  projects/gloo/pkg/plugins/tls_inspector/plugin.go
  projects/gloo/pkg/plugins/tls_inspector/plugin_test.go
  projects/gloo/pkg/setup/setup.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  projects/ingress/pkg/setup/setup_syncer.go
  test/helpers/input_resources.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gateway/robustness_test.go
  test/kube2e/gloo/setup_syncer_test.go
  test/kube2e/util.go
  test/services/gateway.go
Labels: keep pr updated

#6944 fix(tls_inspector): added AggregateListener support
  changelog/v1.13.0-beta6/isolate-virtual-hosts-sharing.yaml
  projects/gloo/pkg/plugins/tls_inspector/plugin.go
  projects/gloo/pkg/plugins/tls_inspector/plugin_test.go
Labels: keep pr updated

#6962 Fix namespace check when registering cluster
  changelog/v1.13.0-beta6/fix-fed-ns-check.yaml
  projects/gloo/cli/pkg/cmd/federation/register/register.go
Labels: keep pr updated

#6964 Fix namespace check when registering cluster [1.11]
  changelog/v1.11.31/fix-fed-ns-check.yaml
  projects/gloo/cli/pkg/cmd/federation/register/register.go
Labels: keep pr updated

#6965 Fix namespace check when registering cluster [1.10]
  changelog/v1.10.37/fix-fed-ns-check.yaml
  projects/gloo/cli/pkg/cmd/federation/register/register.go
Labels: keep pr updated

#6966 Fix namespace check when registering cluster [1.9]
  changelog/v1.9.24/fix-fed-ns-check.yaml
  projects/gloo/cli/pkg/cmd/federation/register/register.go
Labels: keep pr updated

#6963 Fix namespace check when registering cluster [1.12]
  changelog/v1.12.7/fix-fed-ns-check.yaml
  projects/gloo/cli/pkg/cmd/federation/register/register.go
Labels: keep pr updated

#6968 bump alpine to 3.15.6
  changelog/v1.13.0-beta6/bump-alpine.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6969 bump alpine to 3.15.6 [1.12]
  changelog/v1.12.7/bump-alpine.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6970 bump alpine to 3.15.6 [1.11]
  changelog/v1.11.31/bump-alpine.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6971 bump alpine to 3.15.6 [1.10]
  changelog/v1.10.37/bump-alpine.yaml
  docs/content/guides/dev/writing_auth_plugins/_index.md
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6972 bump alpine to 3.15.6 [1.9]
  changelog/v1.9.24/bump-alpine.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#6974 Use 1 Gloo Replica in Gateway Kube Test
  test/kube2e/gateway/gateway_suite_test.go
Labels: keep pr updated

#6958 ISSUEFORM: Update for 1.12 release
  .github/ISSUE_TEMPLATE/BUG-ISSUE.yml
  .github/ISSUE_TEMPLATE/DOCS-ISSUE.yml
  .github/ISSUE_TEMPLATE/FEATURE-ISSUE.yml
Labels: keep pr updated

#6976 11 | fix(tls_inspector): added AggregateListener support
  changelog/v1.11.32/isolate-virtual-hosts-sharing.yaml
  projects/gloo/pkg/plugins/tls_inspector/plugin.go
  projects/gloo/pkg/plugins/tls_inspector/plugin_test.go
Labels: keep pr updated

#6979 Back 1.12/lambda role based
  changelog/v1.12.8/lambda-by-resource-policy.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/options/aws/aws.proto
  projects/gloo/pkg/api/v1/options/aws/aws.pb.clone.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.equal.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.hash.go
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
Labels: keep pr updated

#6996 awslambda: allow for explicit resource policy based upstreams
  Makefile
  changelog/v1.13.0-beta7/lambda-no-chain.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/aws/filter.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/external/envoy/extensions/aws/filter.proto
  projects/gloo/api/v1/options/aws/aws.proto
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.hash.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.clone.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.equal.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.hash.go
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
Labels: keep pr updated

#6997 awslambda: allow for explicit resource policy based upstreams (#6996)
  Makefile
  changelog/v1.12.8/lambda-no-chain.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/aws/filter.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/external/envoy/extensions/aws/filter.proto
  projects/gloo/api/v1/options/aws/aws.proto
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.hash.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.clone.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.equal.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.hash.go
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
Labels: keep pr updated

#7001 Upgrade GHA to use Ubuntu-22.04
  .github/workflows/codegen.yaml
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  test/kube2e/containers/testrunner/Dockerfile
Labels: keep pr updated

#7004 [1.10] Upgrade GHA to use Ubuntu-22.04
  .github/workflows/codegen.yaml
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  test/kube2e/containers/testrunner/Dockerfile
Labels: keep pr updated

#7003 [1.11] Upgrade GHA to use Ubuntu-22.04
  .github/workflows/codegen.yaml
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  test/kube2e/containers/testrunner/Dockerfile
Labels: keep pr updated

#6950 Consul Default Query and Agent Caching
  changelog/v1.13.0-beta7/emitter-ratelimit.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/consul/query_options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/consul/consul.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/consul/query_options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/static/content/osa_included.md
  docs/data/ProtoMap.yaml
  go.mod
  go.sum
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/options/consul/consul.proto
  projects/gloo/api/v1/options/consul/query_options.proto
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/options/consul/consul.pb.clone.go
  projects/gloo/pkg/api/v1/options/consul/consul.pb.equal.go
  projects/gloo/pkg/api/v1/options/consul/consul.pb.go
  projects/gloo/pkg/api/v1/options/consul/consul.pb.hash.go
  projects/gloo/pkg/api/v1/options/consul/query_options.pb.clone.go
  projects/gloo/pkg/api/v1/options/consul/query_options.pb.equal.go
  projects/gloo/pkg/api/v1/options/consul/query_options.pb.go
  projects/gloo/pkg/api/v1/options/consul/query_options.pb.hash.go
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/discovery/discovery.go
  projects/gloo/pkg/plugins/consul/eds.go
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/plugins/consul/plugin.go
  projects/gloo/pkg/plugins/consul/plugin_test.go
  projects/gloo/pkg/upstreams/consul/consul_client.go
  projects/gloo/pkg/upstreams/consul/conversions.go
  projects/gloo/pkg/upstreams/consul/mocks/mock_watcher.go
  projects/gloo/pkg/upstreams/consul/upstream_client.go
  projects/gloo/pkg/upstreams/consul/upstream_client_test.go
  projects/gloo/pkg/upstreams/consul/watcher.go
  test/e2e/consul_test.go
Labels: keep pr updated

#7011 github: Regression test matrix success with no cancel due to prevelan…
  .github/workflows/regression-tests.yaml
Labels: keep pr updated

#7013 k8sadmission: Update to have logger with all useful fields
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook.go
Labels: keep pr updated

#7008 Backport httpconnect headers
  Makefile
  changelog/v1.12.9/upstream-httpconnect-headers.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  install/test/helm_suite_test.go
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/upstream.pb.clone.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/tunneling/plugin.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  test/e2e/http_tunneling_test.go
  test/make/make_test.go
Labels: keep pr updated

#7010 Validation Webhook: Auto-Accept Status Updates
  changelog/v1.13.0-beta7/vwh-accept-status-updates.yaml
  projects/gateway/pkg/services/k8sadmission/README.md
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook.go
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook_test.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/util.go
Labels: keep pr updated

#7016 [1.12] Validation Webhook: Auto-Accept Status Updates
  changelog/v1.12.9/vwh-accept-status-updates.yaml
  projects/gateway/pkg/services/k8sadmission/README.md
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook.go
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook_test.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/util.go
Labels: keep pr updated

#6959 Feat/lambda byaccountid
  changelog/v1.13.0-beta7/lambda-by-resource-policy.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/options/aws/aws.proto
  projects/gloo/pkg/api/v1/options/aws/aws.pb.clone.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.equal.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.hash.go
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
Labels: keep pr updated

#7018 Debug ci
  Makefile
Labels: keep pr updated

#7012 github: Regression test matrix success with no cancel due to prevelan…
  .github/workflows/regression-tests.yaml
Labels: keep pr updated

#7021 changelog: placeholder for release
  changelog/v1.12.10/placeholder-gosum.yaml
Labels: keep pr updated

#7025 Fix make tests for ci
  test/make/make_test.go
Labels: keep pr updated

#7026 Fix make tests for ci
  test/make/make_test.go
Labels: keep pr updated

#7007 Helm CVE
  .github/workflows/regression-tests.yaml
  changelog/v1.9.25/helm-cve.yaml
  cloudbuild.yaml
  docs/content/reference/values.txt
  docs/content/static/content/osa_included.md
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  hack/filter_types/filter_types.gen.go
  projects/clusteringress/pkg/translator/translate_test.go
  projects/gloo/cli/pkg/cmd/root.go
  projects/gloo/cli/pkg/xdsinspection/get_last_config.go
  projects/gloo/pkg/plugins/kubernetes/eds.go
  projects/gloo/pkg/utils/any.go
  projects/gloo/pkg/validation/server_test.go
  projects/knative/api/external/knative/ingress.go
  projects/knative/pkg/translator/translate.go
  projects/knative/pkg/translator/translate_test.go
  projects/knative/pkg/translator/translator_syncer_test.go
  projects/sds/pkg/server/server.go
  test/e2e/happypath_test.go
  test/mocks/kubernetes/kubeinterface.go
Labels: keep pr updated

#7027 Consul filtering by tag
  changelog/v1.13.0-beta8/consul-service-tags-allowlist.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  go.mod
  go.sum
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/discovery/pkg/uds/syncer/setup_syncer.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/upstreams/consul/consul_client.go
  projects/gloo/pkg/upstreams/consul/consul_client_test.go
  projects/gloo/pkg/upstreams/consul/mocks/mock_consul_client.go
  projects/gloo/pkg/upstreams/consul/upstream_client_test.go
  projects/gloo/pkg/upstreams/consul/watcher.go
  projects/gloo/pkg/upstreams/hybrid_client.go
  projects/gloo/pkg/upstreams/hybrid_client_test.go
  test/e2e/consul_test.go
  test/services/gateway.go
Labels: keep pr updated

#7034 x/net CVE
  changelog/v1.9.25/xnet-cve.yaml
  go.mod
  go.sum
Labels: keep pr updated

#6984 Doc fixes
  changelog/v1.13.0-beta9/doc-fixes.yaml
  docs/active_versions.json
  docs/content/getting_started/_index.md
  docs/content/guides/security/waf/_index.md
  docs/content/guides/traffic_management/destination_types/grpc/_index.md
  docs/content/guides/traffic_management/request_processing/health_checks/_index.md
  docs/content/img/Gloo-01-350-by-60.png
  docs/content/img/Gloo-01-350-by-65.png
  docs/content/installation/enterprise/_index.md
  docs/content/introduction/_index.md
  docs/content/introduction/architecture/_index.md
  docs/content/operations/updating_license/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  docs/docs.toml
Labels: work in progress, Type: Docs, keep pr updated

#7035 validation: Update a couple debug logs that can be large with large p…
  changelog/v1.13.0-beta10/validation-debug-overhead.yaml
  projects/gateway/pkg/validation/validator.go
Labels: keep pr updated

#7043 Fix gateway ssl test flakes
  test/e2e/gateway_test.go
Labels: keep pr updated

#7053 Un-revert change to expose hcm internal address config
  changelog/v1.13.0-beta10/internal-address.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.clone.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.equal.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.hash.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/plugins/hcm/testing/expected_hcm_fields.json
Labels: keep pr updated

#7033 Consul EDS Blocking Queries
  .gitignore
  changelog/v1.13.0-beta10/consul-eds-blocking-queries.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/bootstrap/opts.go
  projects/gloo/pkg/plugins/consul/eds.go
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/plugins/consul/plugin.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/upstreams/consul/watcher.go
  test/e2e/consul_test.go
  test/services/consul.go
Labels: keep pr updated

#7015 Trivy scan gateway images fix
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.13.0-beta10/gateway-trivy-scan.yaml
  docs/cmd/generate_docs.go
  docs/cmd/securityscanutils/securityscan_utils.go
Labels: work in progress, keep pr updated

#7046 validation: Update a couple debug logs that can be large with large p…
  changelog/v1.12.11/validation-debug-overhead.yaml
  projects/gateway/pkg/validation/validator.go
Labels: keep pr updated

#7041 fix(hcm): made all fields/subfields nullable
  changelog/v1.13.0-beta10/hcm-0-value-overrides.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/trace/v3/datadog.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/trace/v3/zipkin.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/tracing/tracing.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  pkg/utils/api_conversion/trace.go
  projects/gateway/pkg/translator/hybrid_translator_test.go
  projects/gloo/api/external/envoy/config/trace/v3/datadog.proto
  projects/gloo/api/external/envoy/config/trace/v3/zipkin.proto
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/api/v1/options/tracing/tracing.proto
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.clone.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.hash.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/zipkin.pb.clone.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/zipkin.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/zipkin.pb.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/zipkin.pb.hash.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.clone.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.equal.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.hash.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.clone.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.equal.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.go
  projects/gloo/pkg/api/v1/options/tracing/tracing.pb.hash.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/plugins/tracing/plugin.go
  projects/gloo/pkg/plugins/tracing/plugin_test.go
Labels: keep pr updated

#7062 Fix CVEs for Week of August 29
  .trivyignore
  Makefile
  changelog/v1.13.0-beta10/graphql-go-cve.yaml
  docs/Makefile
  docs/cmd/generate_docs.go
  docs/cmd/securityscanutils/README.md
Labels: keep pr updated

#7064 1.9.26 placeholder yaml
  changelog/v1.9.26/placeholder.yaml
Labels: keep pr updated

#7052 Small helm fixes and test updates to enable istio integration
  changelog/v1.13.0-beta11/sidecar-helm-fixes.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/0-namespace.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated
