Repository kgateway-dev/kgateway, pull requests merged in 2023-05, with the labels that each got.

#8143 Regex fixes
  changelog/v1.15.0-beta6/routeoptions-regex-validation.yaml
  pkg/utils/regexutils/regex.go
  pkg/utils/regexutils/regex_test.go
  projects/gateway/pkg/translator/http_translator_test.go
  projects/gateway/pkg/translator/virtual_service_translator.go
Labels: keep pr updated

#8170 1.14.x API adding OIDC ciphers (#8011)
  changelog/v1.14.2/user-session-encryption.yaml
  docs/content/guides/security/auth/extauth/oauth/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/secret.proto.sk.md
  docs/content/reference/cli/glooctl_create_secret.md
  docs/content/reference/cli/glooctl_create_secret_encryptionkey.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  pkg/utils/syncutil/log_redactor_test.go
  projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/api/v1/secret.proto
  projects/gloo/cli/pkg/cmd/create/secret/encryption_key.go
  projects/gloo/cli/pkg/cmd/create/secret/encryption_key_test.go
  projects/gloo/cli/pkg/cmd/create/secret/root.go
  projects/gloo/pkg/api/converters/kube/encryption_key_secret.go
  projects/gloo/pkg/api/converters/kube/encryption_key_secret_test.go
  projects/gloo/pkg/api/converters/kube/secretconverter.go
  projects/gloo/pkg/api/converters/kube/secretconverter_test.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
  projects/gloo/pkg/api/v1/secret.pb.clone.go
  projects/gloo/pkg/api/v1/secret.pb.equal.go
  projects/gloo/pkg/api/v1/secret.pb.go
  projects/gloo/pkg/api/v1/secret.pb.hash.go
Labels: keep pr updated

#8179 Regex fixes 1.14
  changelog/v1.14.2/routeoptions-regex-validation.yaml
  pkg/utils/regexutils/regex.go
  pkg/utils/regexutils/regex_test.go
  projects/gateway/pkg/translator/http_translator_test.go
  projects/gateway/pkg/translator/virtual_service_translator.go
Labels: keep pr updated

#8173 [1.14] Expose Envoy's OCSP Stapling Configuration
  changelog/v1.14.2/expose-envoy-ocsp-stapling-support.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/secret.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/ssl/ssl.proto.sk.md
  docs/content/reference/cli/glooctl_create_secret_tls.md
  docs/content/static/content/osa_provided.md
  go.mod
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/secret.proto
  projects/gloo/api/v1/ssl/ssl.proto
  projects/gloo/cli/pkg/cmd/create/secret/secret_interactive_test.go
  projects/gloo/cli/pkg/cmd/create/secret/secret_test.go
  projects/gloo/cli/pkg/cmd/create/secret/tls.go
  projects/gloo/cli/pkg/cmd/options/secret.go
  projects/gloo/pkg/api/converters/kube/secretconverter.go
  projects/gloo/pkg/api/converters/kube/secretconverter_test.go
  projects/gloo/pkg/api/v1/secret.pb.clone.go
  projects/gloo/pkg/api/v1/secret.pb.equal.go
  projects/gloo/pkg/api/v1/secret.pb.go
  projects/gloo/pkg/api/v1/secret.pb.hash.go
  projects/gloo/pkg/api/v1/ssl/ssl.pb.clone.go
  projects/gloo/pkg/api/v1/ssl/ssl.pb.equal.go
  projects/gloo/pkg/api/v1/ssl/ssl.pb.go
  projects/gloo/pkg/api/v1/ssl/ssl.pb.hash.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
  projects/sds/pkg/run/certs/ocsp_response.der
  projects/sds/pkg/run/run_e2e_test.go
  projects/sds/pkg/server/certs/ocsp_response.der
  projects/sds/pkg/server/server.go
  projects/sds/pkg/server/server_test.go
  test/e2e/tls_ocsp_test.go
  test/helpers/certs.go
Labels: keep pr updated

#8186 Backport fix generated kube tests flake
  changelog/v1.13.17/envoy-gloo-cross-account-bump.yaml
  projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go
Labels: keep pr updated

#8183 Regex Fixes 1.13
  changelog/v1.13.17/routeoptions-regex-validation.yaml
  projects/gateway/pkg/translator/http_translator_test.go
  projects/gateway/pkg/translator/virtual_service_translator.go
Labels: keep pr updated

#8189 Backport fix generated kube tests flake1.12
  changelog/v1.12.54/envoy-gloo-cross-account-bump.yaml
  projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go
Labels: keep pr updated

#8188 Regex fixes 1.12
  changelog/v1.12.54/routeoptions-regex-validation.yaml
  projects/gateway/pkg/translator/http_translator_test.go
  projects/gateway/pkg/translator/virtual_service_translator.go
Labels: keep pr updated

#8152 [v1.13.x] Test fix for resource-based cross-account lambda invocation
  changelog/v1.13.15/expand-release-branch.yaml
  changelog/v1.13.18/envoy-gloo-cross-account-bump.yaml
  test/e2e/aws_test.go
Labels: keep pr updated

#8154 Filter chain matching tests
  changelog/v1.15.0-beta6/filter-chain-matcher-tests.yaml
  projects/gateway/pkg/defaults/gateway.go
  test/e2e/hybrid_test.go
Labels: keep pr updated

#8180 Add user guide for cross-account lambda functionality
  changelog/v1.15.0-beta6/cross-account-lambda-docs.yaml
  docs/content/guides/traffic_management/destination_types/aws_lambda/cross-account.md
  projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go
Labels: keep pr updated

#8196 Doc fixes for week of 5/4/2023
  changelog/v1.15.0-beta6/docs-fixes.yaml
  docs/Makefile
  docs/active_versions.json
  docs/content/guides/security/rate_limiting/enterprise/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs

#8199 [1.14] Graphql per resolver timeout API
  changelog/v1.14.3/graphql-per-resolver-timeout.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1beta1/graphql.proto.sk.md
  install/helm/gloo/crds/graphql.gloo.solo.io_v1beta1_GraphQLApi.yaml
  projects/gloo/api/external/envoy/extensions/graphql/graphql.proto
  projects/gloo/api/v1/enterprise/options/graphql/v1beta1/graphql.proto
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/graphql/v2/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.hash.go
  test/v1helpers/test_upstream.go
Labels: keep pr updated

#8203 Backport change to allow migrating between grpc APIs without downtime
  changelog/v1.14.4/grpc-migration.yaml
  projects/discovery/pkg/fds/discoveries/grpc/grpc.go
  projects/gloo/pkg/plugins/grpc/plugin.go
  test/e2e/grpc_discovery_test.go
  test/e2e/grpc_plugin_test.go
Labels: keep pr updated

#8206 Upgrade tests not on prs
  .github/workflows/nightly-tests.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.15.0-beta6/remove-upgrade-tests-from-prs.yaml
Labels: keep pr updated

#8215 Document behavior around removing hosts with valid health checks
  changelog/v1.15.0-beta6/healthcheck-docs.yaml
  docs/content/guides/traffic_management/request_processing/upstream_health_checks/_index.md
Labels: keep pr updated

#8192 Add securityContext include and update templates
  changelog/v1.15.0-beta6/allow-securityContext-merge.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
Labels: keep pr updated

#8216 Doc fixes
  docs/content/guides/security/auth/extauth/apikey_auth/_index.md
  docs/content/guides/security/auth/jwt/access_control/access_control_examples.md
  docs/content/guides/security/auth/jwt/claim_routing.md
  docs/content/guides/traffic_management/destination_types/aws_lambda/cross-account.md
Labels: keep pr updated

#8220 12/actions prune
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/issue_board.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.12.55/actions-prune.yaml
Labels: keep pr updated

#8222 main/actions prune
  .github/workflows/do-not-submit.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.15.0-beta7/actions-prune.yaml
Labels: keep pr updated

#8221 11/actions prune
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.11.59/actions-prune.yaml
Labels: keep pr updated

#8218 14/actions prune
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/issue_board.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.14.4/actions-prune.yaml
Labels: keep pr updated

#8219 13/actions prune
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/issue_board.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.13.19/actions-prune.yaml
Labels: keep pr updated

#8231 Codegen improvements
  Makefile
  changelog/v1.15.0-beta7/codegen-targets.yaml
  ci/README.md
  projects/gloo/pkg/plugins/consul/dns_resolver.go
  projects/gloo/pkg/plugins/kubernetes/client.go
  test/mocks/mocks.go
Labels: keep pr updated

#8233 Stability: Demonstrate How To Run Subset of Tests
  .github/actions/regression-tests/action.yaml
  Makefile
  changelog/v1.15.0-beta7/ginkgo-labels.yaml
  ci/cloudbuild/run-tests.yaml
  projects/gloo/pkg/syncer/perf_test/perf_suite_test.go
  projects/gloo/pkg/syncer/perf_test/perf_test.go
  test/consulvaulte2e/e2e_suite_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/example_test.go
  test/ginkgo/labels/labels.go
  test/kube2e/README.md
Labels: keep pr updated

#8228 Fix non-persisted proxy validation in glooctl check
  changelog/v1.15.0-beta7/glooctl-proxy-fix.yaml
  projects/gloo/cli/pkg/cmd/check/check_test.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/common/get.go
Labels: keep pr updated

#8229 refactor(CI): use common base action
  .github/workflows/codegen.yaml
  .github/workflows/composite-actions/prep-go-runner/action.yaml
  .github/workflows/composite-actions/regression-tests/action.yaml
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.15.0-beta7/lift-common-actions.yaml
  ci/do-not-submit.sh
Labels: keep pr updated

#8245 [1.12.x] Fix non-persisted proxy validation in glooctl check
  changelog/v1.12.55/glooctl-proxy-fix.yaml
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/common/get.go
Labels: keep pr updated

#8243 [1.14.x] Fix non-persisted proxy validation in glooctl check
  changelog/v1.14.4/glooctl-proxy-fix.yaml
  projects/gloo/cli/pkg/cmd/check/check_test.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/common/get.go
Labels: keep pr updated

#8244 [1.13.x] Fix non-persisted proxy validation in glooctl check
  changelog/v1.13.19/glooctl-proxy-fix.yaml
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/common/get.go
Labels: keep pr updated

#8249 build(push-solo-apis): run setup steps from gloo directory
  .github/workflows/composite-actions/prep-go-runner/action.yaml
  .github/workflows/push-solo-apis-branch.yaml
  changelog/v1.15.0-beta8/cd-go-runner.yaml
Labels: keep pr updated

#8248 Stabilize HaveHttpResponseMatcher
  changelog/v1.15.0-beta8/have-http-response-matcher.yaml
  test/gomega/matchers/have_http_response.go
Labels: keep pr updated

#8253 Replace all calls to deprecated io/ioutil package
  changelog/v1.15.0-beta8/remove-ioutil.yaml
  docs/cmd/generate_docs.go
  docs/cmd/securityscanutils/securityscan_utils.go
  install/helm/gloo/generate.go
  install/test/helm_suite_test.go
  install/test/helm_test.go
  pkg/cliutil/logger.go
  pkg/cliutil/uri.go
  projects/discovery/pkg/fds/discoveries/swagger/swagger.go
  projects/envoyinit/pkg/downward/downward.go
  projects/envoyinit/pkg/downward/template.go
  projects/gateway/pkg/services/k8sadmission/cert_provider_test.go
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook.go
  projects/gateway/pkg/validation/validator_test.go
  projects/gloo/cli/pkg/cmd/check/proxy_prom_stats.go
  projects/gloo/cli/pkg/cmd/config_file.go
  projects/gloo/cli/pkg/cmd/create/root.go
  projects/gloo/cli/pkg/cmd/create/secret/secret_test.go
  projects/gloo/cli/pkg/cmd/debug/debug.go
  projects/gloo/cli/pkg/cmd/debug/debug_test.go
  projects/gloo/cli/pkg/cmd/gateway/dump.go
  projects/gloo/cli/pkg/cmd/initpluginmanager/initpluginmanager.go
  projects/gloo/cli/pkg/cmd/install/helm_client.go
  projects/gloo/cli/pkg/cmd/install/install_suite_test.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/install/knative_test.go
  projects/gloo/cli/pkg/cmd/options/secret.go
  projects/gloo/cli/pkg/cmd/plugin/list/list.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/utils/log_filtering_test.go
  projects/sds/pkg/server/server.go
  projects/sds/pkg/testutils/utils.go
  test/consulvaulte2e/consul_vault_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/grpc_json_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/happypath_test.go
  test/e2e/health_checks_test.go
  test/e2e/zipkin_test.go
  test/helpers/directories.go
  test/helpers/glooctl_debug_dump.go
  test/kube2e/gateway/robustness_test.go
  test/kube2e/ingress/ingress_suite_test.go
  test/kube2e/knative/knative_suite_test.go
  test/kube2e/upgrade/upgrade_test.go
  test/kube2e/util.go
  test/services/consul.go
  test/services/envoy.go
  test/services/nats.go
  test/services/nomad.go
Labels: keep pr updated

#8213 Add gRPC transcoding filter to routes
  changelog/v1.15.0-beta8/listener_filter.yaml
  projects/gloo/pkg/plugins/grpcjson/plugin.go
  projects/gloo/pkg/plugins/grpcjson/plugin_test.go
Labels: keep pr updated

#8235 K8s tests in kind
  changelog/v1.15.0-beta8/k8s-tests-in-kind.yaml
  projects/gateway/pkg/api/v1/kube/generated_kube_suite_test.go
  projects/gloo/pkg/bootstrap/utils_test.go
  projects/gloo/pkg/plugins/kubernetes/kubernetes_test.go
  projects/ingress/pkg/api/service/service_suite_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
  test/e2e/happypath_test.go
  test/kube2e/gloo/artifact_client_test.go
  test/kube2e/gloo/generated_kube_types_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/gloo/happypath_test.go
  test/kube2e/gloo/kubernetes_test.go
  test/kube2e/gloo/resource_client_test.go
  test/testutils/env.go
  test/testutils/requirements.go
Labels: keep pr updated

#8259 Backport docs 1.14
  docs/content/guides/traffic_management/configuration_validation/admission_control.md
  docs/content/guides/traffic_management/destination_types/aws_lambda/cross-account.md
Labels: keep pr updated

#8258 Backport docs 1.13
  docs/content/guides/traffic_management/configuration_validation/admission_control.md
Labels: keep pr updated

#8260 Backport docs 1.12
  docs/content/guides/traffic_management/configuration_validation/admission_control.md
Labels: keep pr updated

#8261 Refactor bootstrap clients
  changelog/v1.15.0-beta8/refactor-bootstrap.yaml
  projects/gloo/cli/pkg/flagutils/common.go
  projects/gloo/cli/pkg/helpers/clients.go
  projects/gloo/pkg/bootstrap/bootstrap_validation.go
  projects/gloo/pkg/bootstrap/clients/artifact.go
  projects/gloo/pkg/bootstrap/clients/clients_suite_test.go
  projects/gloo/pkg/bootstrap/clients/clients_test.go
  projects/gloo/pkg/bootstrap/clients/common.go
  projects/gloo/pkg/bootstrap/clients/config_factory.go
  projects/gloo/pkg/bootstrap/clients/consul.go
  projects/gloo/pkg/bootstrap/clients/kube.go
  projects/gloo/pkg/bootstrap/clients/kube_service.go
  projects/gloo/pkg/bootstrap/clients/secret.go
  projects/gloo/pkg/bootstrap/clients/vault.go
  projects/gloo/pkg/bootstrap/consul.go
  projects/gloo/pkg/bootstrap/utils.go
  projects/gloo/pkg/bootstrap/vault.go
  projects/gloo/pkg/plugins/aws/ec2/poll_test.go
  projects/gloo/pkg/syncer/setup/proxy_cleanup.go
  projects/gloo/pkg/syncer/setup/proxy_cleanup_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/ingress/pkg/setup/setup_syncer.go
  test/consulvaulte2e/consul_vault_test.go
  test/e2e/vault_aws_test.go
  test/e2e/vault_test.go
  test/services/gateway.go
Labels: keep pr updated

#8267 Backport change to put grpc transcoding filters on routes
  changelog/v1.15.0-beta8/listener_filter.yaml
  projects/gloo/pkg/plugins/grpcjson/plugin.go
  projects/gloo/pkg/plugins/grpcjson/plugin_test.go
Labels: keep pr updated

#8271 [1.14] move changelog
  changelog/v1.14.6/listener_filter.yaml
Labels: keep pr updated

#8270 Stability: Move Tests Which Adjust Validation Configuration to Same Context
  changelog/v1.15.0-beta8/gateway-kube2e-reorder.yaml
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#8273 Stability: Deflake Gloo Kube2e Tests
  changelog/v1.15.0-beta8/gloo-kube2e-consistent.yaml
  projects/gloo/pkg/bootstrap/clients/clients_test.go
  projects/gloo/pkg/bootstrap/utils_test.go
  test/kube2e/gloo/artifact_client_test.go
  test/kube2e/gloo/bootstrap_clients_test.go
  test/kube2e/gloo/generated_kube_types_test.go
  test/kube2e/gloo/happypath_test.go
  test/kube2e/gloo/kubernetes_test.go
  test/kube2e/gloo/resource_client_test.go
Labels: keep pr updated

#8274 Stability: Deflake Glooctl Kube2e Tests
  changelog/v1.15.0-beta8/glooctl-kube2e-debug.yaml
  projects/gloo/cli/pkg/cmd/debug/debug_test.go
  projects/gloo/cli/pkg/cmd/debug/root_test.go
  test/kube2e/glooctl/debug_test.go
  test/kube2e/glooctl/glooctl_suite_test.go
  test/kube2e/glooctl/glooctl_test.go
  test/kube2e/glooctl/istio_test.go
Labels: keep pr updated

#8262 Multiple secret sources api
  changelog/v1.15.0-beta8/multi-secret-client-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
Labels: keep pr updated

#8279 Stability: Deflake Glooctl Kube2e Tests
  changelog/v1.15.0-beta8/glooctl-kube2e-part-2.yaml
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/glooctl/check_crds_test.go
  test/kube2e/glooctl/check_test.go
  test/kube2e/glooctl/debug_test.go
  test/kube2e/glooctl/glooctl_suite_test.go
  test/kube2e/glooctl/istio_test.go
  test/kube2e/gloomtls/gloo_mtls_suite_test.go
  test/kube2e/istio/istio_suite_test.go
  test/kube2e/resource_clientset.go
Labels: keep pr updated

#8280 Stability: Deflake Gateway Kube2e Tests
  changelog/v1.15.0-beta8/gateway-kube2e-debug.yaml
  test/kube2e/gateway/gateway_test.go
  test/kube2e/gateway/robustness_test.go
Labels: keep pr updated

#8286 Stability: Remove PR Direct Slack Message
  .github/workflows/notify-on-regression-failure-list.json
  .github/workflows/regression-tests.yaml
  changelog/v1.15.0-beta8/remove-kube2e-pr-alerts.yaml
Labels: keep pr updated

#8296 1.14.x -- fix indentation in RBAC resources (#8265)
  changelog/v1.14.6/helm-indentation.yaml
  install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
Labels: keep pr updated

#8255 K8s 1.26 upgrade
  .github/workflows/nightly-tests.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.15.0-beta8/k8s-126-bump.yaml
  ci/kind/setup-kind.sh
  docs/content/reference/values.txt
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  hack/test.sh
  install/helm/gloo/generate/values.go
  jobs/kubectl/Dockerfile
  projects/ingress/pkg/status/status_syncer.go
  test/kube2e/ingress/status_syncer_test.go
  test/mocks/kubernetes/kubeinterface.go
Labels: keep pr updated

#8297 v1.13.x -- refactor: fix indentation in RBAC resources (#8265)
  changelog/v1.13.20/helm-indentation.yaml
  install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
Labels: keep pr updated

#8263 Multiple secret sources impl
  changelog/v1.15.0-beta9/multi-secret-client-impl.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  projects/gloo/api/v1/settings.proto
  projects/gloo/cli/pkg/helpers/clients.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/bootstrap/clients/clients_suite_test.go
  projects/gloo/pkg/bootstrap/clients/clients_test.go
  projects/gloo/pkg/bootstrap/clients/common.go
  projects/gloo/pkg/bootstrap/clients/consul_test.go
  projects/gloo/pkg/bootstrap/clients/kube.go
  projects/gloo/pkg/bootstrap/clients/secret.go
  projects/gloo/pkg/bootstrap/clients/secret_test.go
  projects/gloo/pkg/bootstrap/clients/vault.go
  projects/gloo/pkg/bootstrap/utils.go
  projects/gloo/pkg/bootstrap/vault.go
  projects/gloo/pkg/plugins/aws/ec2/poll_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/ingress/pkg/setup/setup_syncer.go
  test/consulvaulte2e/consul_vault_test.go
  test/kube2e/gloo/bootstrap_clients_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/services/consul.go
  test/services/gateway.go
Labels: keep pr updated

#8284 Stability: More Kube2e Fixes
  changelog/v1.15.0-beta9/kube2e-deflake.yaml
  test/helpers/input_resources.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/gloo/happypath_test.go
  test/kube2e/gloo/kubernetes_test.go
Labels: keep pr updated

#8303 Audit use of gomega.Consistently to check receives on unbuffered channels
  changelog/v1.15.0-beta9/consistently-receive-audit.yaml
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/upstreams/consul/upstream_client_test.go
  projects/gloo/pkg/upstreams/hybrid_client_test.go
Labels: keep pr updated

#8277 1.14/proxyprotocol clusters
  changelog/v1.14.6/upstream-proxy-protocol-hardening.yaml
  projects/gloo/pkg/plugins/static/plugin.go
  projects/gloo/pkg/plugins/static/plugin_test.go
  projects/gloo/pkg/plugins/utils/upstreamproxyprotocol/upstreamproxyprotocol.go
  projects/gloo/pkg/plugins/utils/upstreamproxyprotocol/upstreamproxyprotocol_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/listener.go
  projects/gloo/pkg/translator/listener_subsystem.go
  projects/gloo/pkg/translator/listener_subsystem_test.go
Labels: keep pr updated

#8306 Explicitly set duration/timeout and polling interval on async gomega assertions
  changelog/v1.15.0-beta9/explicit-defaults-async-assertions.yaml
  projects/gloo/pkg/discovery/discovery_test.go
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/upstreams/consul/upstream_client_test.go
  projects/gloo/pkg/upstreams/hybrid_client_test.go
  test/e2e/health_checks_test.go
  test/e2e/zipkin_test.go
  test/gomega/gomega.go
Labels: keep pr updated

#8309 1.14 translator/listener: Update aggregate listener to support tcp
  changelog/v1.14.6/isolatebyvs-support-tcp.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/validation/gloo_validation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gateway/pkg/translator/aggregate_translator.go
  projects/gateway/pkg/translator/hybrid_translator.go
  projects/gateway/pkg/translator/translator.go
  projects/gloo/api/grpc/validation/gloo_validation.proto
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.clone.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.equal.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.hash.go
  projects/gloo/pkg/api/v1/proxy.pb.clone.go
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.hash.go
  projects/gloo/pkg/translator/listener_subsystem.go
Labels: work in progress, keep pr updated

#8315 arduino-dep-pin
  .github/workflows/codegen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  changelog/v1.15.0-beta9/adruino-dep-pin.yaml
Labels: keep pr updated

#8317 v1.13 arduino-dep-pin
  .github/workflows/codegen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  changelog/v1.13.20/arduino-dep-pin.yaml
Labels: keep pr updated

#8318 v1.12 arduino-dep-pin
  .github/workflows/codegen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  changelog/v1.12.56/arduino-dep-pin.yaml
Labels: keep pr updated

#8319 v1.11 arduino dep pin
  .github/workflows/codegen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  changelog/v1.11.59/arduino-dep-pin.yaml
Labels: keep pr updated

#8307 Support Skip CI Directives
  .github/workflows/codegen.yaml
  .github/workflows/composite-actions/process-skip-directives/action.yaml
  .github/workflows/composite-actions/regression-tests/action.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.15.0-beta9/skip-ci-directive.yaml
  ci/README.md
  ci/github-actions/process-skip-directives/script.sh
Labels: keep pr updated

#8298 Performance tests job in nightly action
  .github/workflows/composite-actions/performance-tests/action.yaml
  .github/workflows/nightly-tests.yaml
  Makefile
  changelog/v1.15.0-beta9/nightly-tests-job.yaml
  projects/gloo/pkg/syncer/perf_test/perf_suite_test.go
  test/e2e/example_test.go
  test/ginkgo/labels/labels.go
Labels: keep pr updated

#8322 Remove intentionally-failing test
  changelog/v1.15.0-beta9/remove-intentionally-failing-test.yaml
  projects/gloo/pkg/syncer/perf_test/perf_test.go
Labels: keep pr updated
