Repository kgateway-dev/kgateway, pull requests merged in 2023-10, with the labels that each got.

#8731 Better support for unreleased envoy-gloo assets
  changelog/v1.16.0-beta12/unreleased-envoy-gloo-support.yaml
  ci/cloudbuild/run-tests.yaml
Labels: keep pr updated

#8730 Move to ubuntu based envoy dockerfiles
  Makefile
  changelog/v1.16.0-beta12/envoy-change.yaml
  projects/envoyinit/cmd/Dockerfile.envoyinit
  projects/gloo/cmd/Dockerfile
Labels: keep pr updated

#8741 1.15 Move to ubuntu based envoy dockerfiles (#8730)
  Makefile
  changelog/v1.15.8/envoy-change.yaml
  projects/envoyinit/cmd/Dockerfile.envoyinit
  projects/gloo/cmd/Dockerfile
Labels: keep pr updated

#8738 Add --wait to helm tests and other improvements to support CD tools
  changelog/v1.16.0-beta13/helm-wait.yaml
  install/helm/gloo/templates/0-namespace.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8716 OIDC code exchange add private key JWT token exchange
  changelog/v1.16.0-beta13/oidc-code-exchange-refactor.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#8742 [1.15] Add --wait to helm tests and other improvements to support CD tools
  changelog/v1.15.9/helm-wait.yaml
  install/helm/gloo/templates/0-namespace.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8743 [1.14] Add --wait to helm tests and other improvements to support CD tools
  changelog/v1.14.22/helm-wait.yaml
  install/helm/gloo/templates/0-namespace.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8744 [1.13] Add --wait to helm tests and other improvements to support CD tools
  changelog/v1.13.28/helm-wait.yaml
  install/helm/gloo/templates/0-namespace.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8733 fix: Changes to configmaps do not automatically trigger a new rollout
  changelog/v1.16.0-beta14/fix-configmaps.yaml
  install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
  install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
  install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
  install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/helm_test.go
  projects/gloo/cli/pkg/cmd/gateway/dump.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#8714 Fixed minor typos with the Vault integration
  changelog/v1.16.0-beta14/vault-integration-fixes.yaml
  docs/content/guides/integrations/vault/aws-irsa-auth/_index.md
Labels: keep pr updated

#8751 [1.15] fix: Skip directives script failing on no changelog
  changelog/v1.15.9/fix-check-skip-directives-again.yaml
  ci/github-actions/process-skip-directives/script.sh
Labels: keep pr updated

#8746 [1.14] fix: Changes to configmaps do not automatically trigger a new rollout
  changelog/v1.14.22/fix-configmaps.yaml
  install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
  install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
  install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
  install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/helm_test.go
  projects/gloo/cli/pkg/cmd/gateway/dump.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#8750 1.15: Add tests for non custom probes and add wget back
  changelog/v1.15.9/reenable-probes.yaml
  projects/envoyinit/cmd/Dockerfile.envoyinit
  projects/gloo/cmd/Dockerfile
  test/kube2e/helm/artifacts/helm.yaml
Labels: keep pr updated

#8747 [1.13] fix: Changes to configmaps do not automatically trigger a new rollout
  changelog/v1.13.28/fix-configmaps.yaml
  install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
  install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
  install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
  install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/helm_test.go
  projects/gloo/cli/pkg/cmd/gateway/dump.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#8752 Removing redundant checks in configmaps
  changelog/v1.16.0-beta14/configmap-checks.yaml
  install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
Labels: keep pr updated

#8676 Istio 1.18 support
  changelog/v1.16.0-beta14/istio-1.18.yaml
  ci/kind/setup-kind.sh
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  test/helpers/kube_dump.go
  test/kube2e/istio/artifacts/helm.yaml
  test/kube2e/istio/artifacts/httpbin.yaml
  test/kube2e/istio/artifacts/peerauth_permissive.yaml
  test/kube2e/istio/artifacts/peerauth_strict.yaml
  test/kube2e/istio/istio_integration_test.go
  test/kube2e/istio/istio_suite_test.go
Labels: work in progress, keep pr updated

#8753 Istio 1.18 support (#8676)
  changelog/v1.15.10/istio-1.18.yaml
  ci/kind/setup-kind.sh
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  test/helpers/kube_dump.go
  test/kube2e/istio/artifacts/helm.yaml
  test/kube2e/istio/artifacts/httpbin.yaml
  test/kube2e/istio/artifacts/peerauth_permissive.yaml
  test/kube2e/istio/artifacts/peerauth_strict.yaml
  test/kube2e/istio/istio_integration_test.go
  test/kube2e/istio/istio_suite_test.go
Labels: keep pr updated

#8764 Doc fixes
  changelog/v1.16.0-beta15/doc-fixes.yaml
  docs/content/guides/observability/tracing/otel-config.yaml
  docs/content/guides/observability/tracing/otel.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#8757 Istio fix backport 1.14
  changelog/v1.14.22/istio-spiffe-volumes.yaml
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  test/kube2e/istio/artifacts/helm.yaml
  test/kube2e/istio/artifacts/httpbin.yaml
  test/kube2e/istio/artifacts/peerauth_permissive.yaml
  test/kube2e/istio/artifacts/peerauth_strict.yaml
  test/kube2e/istio/istio_integration_test.go
  test/kube2e/istio/istio_suite_test.go
Labels: keep pr updated

#8758 Istio Spiffe fix 1.13
  changelog/v1.13.28/istio-spiffe-volumes.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#8765 Istio support matrix
  changelog/v1.16.0-beta15/istio-support-matrix.yaml
  docs/content/reference/support.md
  test/kube2e/istio/README.md
Labels: keep pr updated

#8756 Fix nightly upgrade test failure
  changelog/v1.16.0-beta15/fix-nightly-tests.yaml
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8761 [1.15] fix: custom readiness probe with custom healthCheck path not working
  changelog/v1.15.10/fix-readiness-probe.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/templates/5-resource-rollout-job-check.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/helm_test.go
  projects/gateway/pkg/translator/aggregate_translator.go
  projects/gateway/pkg/translator/aggregate_translator_test.go
  projects/gateway/pkg/translator/http_translator.go
  projects/gateway/pkg/translator/http_translator_test.go
  projects/gateway/pkg/translator/hybrid_translator.go
  projects/gateway/pkg/translator/hybrid_translator_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/translator/network_filters.go
  test/kube2e/helm/artifacts/custom-readiness-probe.yaml
  test/kube2e/helm/artifacts/upgrade-override.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8763 [1.14] fix: custom readiness probe with custom healthCheck path not working
  changelog/v1.14.22/fix-readiness-probe.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/templates/5-resource-rollout-job-check.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/helm_test.go
  projects/gateway/pkg/translator/aggregate_translator.go
  projects/gateway/pkg/translator/aggregate_translator_test.go
  projects/gateway/pkg/translator/http_translator.go
  projects/gateway/pkg/translator/http_translator_test.go
  projects/gateway/pkg/translator/hybrid_translator.go
  projects/gateway/pkg/translator/hybrid_translator_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/translator/network_filters.go
  test/kube2e/helm/artifacts/custom-readiness-probe.yaml
  test/kube2e/helm/artifacts/upgrade-override.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8762 [1.13] fix: custom readiness probe with custom healthCheck path not working
  changelog/v1.13.28/fix-readiness-probe.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/templates/5-resource-rollout-job-check.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/helm_test.go
  projects/gateway/pkg/translator/aggregate_translator.go
  projects/gateway/pkg/translator/aggregate_translator_test.go
  projects/gateway/pkg/translator/http_translator.go
  projects/gateway/pkg/translator/http_translator_test.go
  projects/gateway/pkg/translator/hybrid_translator.go
  projects/gateway/pkg/translator/hybrid_translator_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/translator/network_filters.go
  test/kube2e/helm/artifacts/custom-readiness-probe.yaml
  test/kube2e/helm/artifacts/upgrade-override.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8766 Istio support matrix 1.15
  changelog/v1.15.10/istio-support-matrix.yaml
  docs/content/reference/support.md
  test/kube2e/istio/README.md
Labels: keep pr updated

#8740 fix: Validate on `Secret` deletions
  changelog/v1.16.0-beta15/gateway-validate-secret-deletion.yaml
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  install/test/5-gateway-validation-webhook-configuration_test.go
  projects/gateway/pkg/services/k8sadmission/README.md
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook.go
  projects/gateway/pkg/validation/validator.go
  projects/gloo/pkg/translator/performance_test.go
  test/helpers/scaled_snapshots.go
  test/helpers/secrets.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#8771 Fix go-control-plane replace
  changelog/v1.16.0-beta15/go-control-plane-fork.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#8772 Fix go-control-plane replace [1.15]
  changelog/v1.15.11/go-control-plane-fork.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#8778 Do not print full cluster information on cluster validation errors
  changelog/v1.16.0-beta15/do-not-log-envoy-cluster-on-computeCluster.yaml
  projects/gloo/pkg/translator/clusters.go
Labels: keep pr updated

#8780 [1.14] helm: Adding a longer timeout for the resource rollout job to complete
  changelog/v1.14.23/add-timeout-resource-rollout-job.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-resource-rollout-job-check.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#8781 [1.13] helm: Adding a longer timeout for the resource rollout job to complete
  changelog/v1.13.29/add-timeout-resource-rollout-job.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-resource-rollout-job-check.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#8789 [1.12] Do not print full cluster information on cluster validation errors
  changelog/v1.12.59/do-not-log-envoy-cluster-on-computeCluster.yaml
  projects/gloo/pkg/translator/clusters.go
Labels: keep pr updated

#8777 helm: Adding a longer timeout for the resource rollout job to complete
  changelog/v1.16.0-beta15/add-timeout-resource-rollout-job.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-resource-rollout-job-check.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#8783 [v1.14.x] Bump envoy-gloo and cloud-builders
  Makefile
  changelog/v1.14.23/bump_envoy_gloo.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
Labels: keep pr updated

#8787 Bump envoy-gloo and cloud-builders
  Makefile
  changelog/v1.16.0-beta15/bump_envoy_gloo.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
Labels: keep pr updated

#8788 [1.13] Do not print full cluster information on cluster validation errors
  changelog/v1.13.29/do-not-log-envoy-cluster-on-computeCluster.yaml
  projects/gloo/pkg/translator/clusters.go
Labels: keep pr updated

#8785 [1.15] Do not print full cluster information on cluster validation errors
  changelog/v1.15.11/do-not-log-envoy-cluster-on-computeCluster.yaml
  projects/gloo/pkg/translator/clusters.go
Labels: keep pr updated

#8791 Preconnectpolicy
  changelog/v1.16.0-beta15/preconnect.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/upstream.pb.clone.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#8792 1.15 Preconnectpolicy (#8791)
  changelog/v1.15.11/preconnect.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/upstream.pb.clone.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#8794 [1.12.x] Bump envoy-gloo to fix CVE-2023-44487
  Makefile
  changelog/v1.12.59/bump-envoy-gloo.yaml
Labels: keep pr updated

#8793 [1.13.x] Bump envoy-gloo to fix CVE-2023-44487
  Makefile
  changelog/v1.13.29/bump-envoy-gloo.yaml
  cloudbuild.yaml
Labels: keep pr updated

#8797 Docs admission control
  changelog/v1.16.0-beta16/docs-admission-control.yaml
  docs/content/guides/traffic_management/configuration_validation/admission_control.md
Labels: keep pr updated

#8798 Docs access log filter
  changelog/v1.16.0-beta16/docs-access-log-filter.yaml
  docs/content/guides/security/access_logging/_index.md
Labels: keep pr updated

#8796 [1.15.x] Add support for envoy local rate limit filters
  changelog/v1.15.12/add-local-ratelimit.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/connection_limit/connection_limit.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/local_ratelimit/local_ratelimit.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableTcpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/connection_limit/connection_limit.proto
  projects/gloo/api/v1/options/local_ratelimit/local_ratelimit.proto
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.hash.go
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/options/connection_limit/connection_limit.pb.go
  projects/gloo/pkg/api/v1/options/local_ratelimit/local_ratelimit.pb.clone.go
  projects/gloo/pkg/api/v1/options/local_ratelimit/local_ratelimit.pb.equal.go
  projects/gloo/pkg/api/v1/options/local_ratelimit/local_ratelimit.pb.go
  projects/gloo/pkg/api/v1/options/local_ratelimit/local_ratelimit.pb.hash.go
  projects/gloo/pkg/plugins/connection_limit/plugin.go
  projects/gloo/pkg/plugins/local_ratelimit/local_ratelimit_suite_test.go
  projects/gloo/pkg/plugins/local_ratelimit/plugin.go
  projects/gloo/pkg/plugins/local_ratelimit/plugin_test.go
  projects/gloo/pkg/plugins/local_ratelimit/utils.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/translator/translator_test.go
  test/e2e/local_ratelimit_test.go
  test/gomega/matchers/contain_headers.go
  test/gomega/matchers/contain_headers_test.go
  test/gomega/transforms/transforms.go
Labels: keep pr updated

#8799 Doc fixes 1.15
  changelog/v1.15.12/doc-fixes.yaml
  docs/content/guides/security/access_logging/_index.md
  docs/content/guides/traffic_management/configuration_validation/admission_control.md
Labels: keep pr updated

#8795 Fix kube2e gateway_test flakes due to recent secret deletion validation
  changelog/v1.16.0-beta16/fix-secret-deletion-validation-flake-gw-kube2e.yaml
  test/helpers/certs.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#8800 [1.15] Fix kube2e gateway_test flakes due to recent secret deletion validation
  changelog/v1.15.13/fix-secret-deletion-validation-flake-gw-kube2e.yaml
  test/helpers/certs.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#8805 Docs: FIPS Validation
  changelog/v1.16.0-beta16/fips-validation.yaml
  docs/content/installation/advanced_configuration/fips.md
Labels: keep pr updated

#8813 Docs: Hosting portal images
  changelog/v1.16.0-beta16/docs-portal-images.yaml
  docs/content/img/portal/banner.png
  docs/content/img/portal/favicon.png
  docs/content/img/portal/primaryLogo.png
Labels: keep pr updated

#8819 Doc fixes
  changelog/v1.16.0-beta16/doc-fixes.yaml
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/introduction/integrations.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/reference/values.txt
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  install/helm/gloo/generate/values.go
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: Type: Docs, keep pr updated

#8814 Revert custom readiness probe fix
  changelog/v1.16.0-beta16/revert-readiness-check.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-resource-rollout-job-check.yaml
  install/helm/gloo/templates/5-resource-rollout-job-clusterrole.yaml
  install/helm/gloo/templates/5-resource-rollout-job-clusterrolebinding.yaml
  install/helm/gloo/templates/5-resource-rollout-job-role.yaml
  install/helm/gloo/templates/5-resource-rollout-job-rolebinding.yaml
  install/helm/gloo/templates/5-resource-rollout-job-service-account.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/helm_test.go
  pkg/utils/setuputils/setup_syncer.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  test/kube2e/helm/artifacts/custom-readiness-probe.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8817 [1.15] Revert custom readiness probe fix
  changelog/v1.15.13/revert-readiness-check.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-resource-rollout-job-check.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/helm_test.go
  pkg/utils/setuputils/setup_syncer.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  test/kube2e/helm/artifacts/custom-readiness-probe.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8815 [1.14] Revert custom readiness probe fix
  changelog/v1.14.24/revert-readiness-check.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-resource-rollout-job-check.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/helm_test.go
  pkg/utils/setuputils/setup_syncer.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  test/kube2e/helm/artifacts/custom-readiness-probe.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8816 [1.13] Revert custom readiness probe fix
  changelog/v1.13.30/revert-readiness-check.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-resource-rollout-job-check.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/helm_test.go
  pkg/utils/setuputils/setup_syncer.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  test/kube2e/helm/artifacts/custom-readiness-probe.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#8695 Rotate certs without downtime
  changelog/v1.16.0-beta16/cert-rotation.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  jobs/certgen/cmd/main.go
  jobs/pkg/kube/secret.go
  jobs/pkg/kube/secret_test.go
  jobs/pkg/run/run.go
  projects/sds/pkg/server/server.go
Labels: keep pr updated

#8820 Backport v1.15.x docs
  changelog/v1.15.13/doc-backport.yaml
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/guides/security/local_rate_limiting/_index.md
  docs/content/guides/security/local_rate_limiting/http.md
  docs/content/guides/security/local_rate_limiting/overview.md
  docs/content/guides/security/local_rate_limiting/tcp.md
  docs/content/guides/security/rate_limiting/_index.md
  docs/content/guides/traffic_management/configuration_validation/admission_control.md
  docs/content/img/local-rate-limiting.svg
  docs/content/img/local-rl-tokens.svg
  docs/content/introduction/integrations.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/reference/values.txt
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  install/helm/gloo/generate/values.go
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: Type: Docs, keep pr updated

#8822 Expose labelSelector in Internal API
  changelog/v1.15.14/label-selector-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#8827 Expose labelSelector in Internal API (#8822)
  changelog/v1.16.0-beta17/label-selector-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#8829 Apikey label selector 1.14
  changelog/v1.14.25/label-selector-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#8830 Apikey label selector 1.13
  changelog/v1.13.31/label-selector-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#8825 cli: Comment and update helper function for retrieving kuberenets context to use
  changelog/v1.16.0-beta18/cli-kubecontext.yaml
  projects/gloo/cli/pkg/cmd/check-crds/root.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/istio/util.go
  projects/gloo/cli/pkg/cmd/options/contextoptions/contextoptions.go
  projects/gloo/cli/pkg/cmd/version/clients.go
  projects/gloo/cli/pkg/helpers/clients.go
Labels: keep pr updated

#8807 Sha1 for basic auth
  changelog/v1.16.0-beta18/sha1-for-basicauth.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#8806 Add `claimsToHeaders` to internal ee ext-auth api
  changelog/v1.16.0-beta18/expose-claims-to-headers-in-internal-ee-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#8842 Doc fixes
  changelog/v1.16.0-beta19/doc-fixes.yaml
  docs/content/guides/security/rate_limiting/envoy/_index.md
  docs/content/installation/enterprise/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#8851 Doc fixes 1.15
  changelog/v1.15.16/doc-fixes.yaml
  docs/content/guides/security/rate_limiting/envoy/_index.md
  docs/content/installation/enterprise/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated
