Repository kgateway-dev/kgateway, pull requests merged in 2023-09, with the labels that each got.

#8622 Expand Credential Support for Vault's AWS Integration
  changelog/v1.16.0-beta7/make-vault-aws-aim-creds-optional.yaml
  devel/testing/aws-tests.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures/settings/set_secretSettings_in_settings.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/bootstrap/clients/vault.go
  test/e2e/README.md
  test/e2e/vault_aws_test.go
  test/services/vault.go
Labels: keep pr updated

#8637 GHA timeouts
  .github/workflows/add-pr-label.yaml
  .github/workflows/cache-eviction.yaml
  .github/workflows/cache-setup.yaml
  .github/workflows/codegen.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/issue_board.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.16.0-beta7/gha-timeouts.yaml
Labels: keep pr updated

#8638 GHA timeouts 1.15
  .github/workflows/add-pr-label.yaml
  .github/workflows/cache-setup.yaml
  .github/workflows/codegen.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/issue_board.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.15.3/gha-timeouts.yaml
Labels: keep pr updated

#8639 GHA timeouts 1.14
  .github/workflows/add-pr-label.yaml
  .github/workflows/cache-setup.yaml
  .github/workflows/codegen.yaml
  .github/workflows/do-not-submit.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.14.19/gha-timeouts.yaml
Labels: keep pr updated

#8640 GHA timeouts 1.13
  .github/workflows/add-pr-label.yaml
  .github/workflows/cache-setup.yaml
  .github/workflows/codegen.yaml
  .github/workflows/do-not-submit.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.13.26/gha-timeouts.yaml
Labels: keep pr updated

#8646 [1.15] Expand Credential Support for Vault's AWS Integration
  changelog/v1.15.3/make-vault-aws-aim-creds-optional.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures/settings/set_secretSettings_in_settings.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/bootstrap/clients/vault.go
  test/e2e/vault_aws_test.go
  test/services/vault.go
Labels: keep pr updated

#8618 feat: Add support for envoy local rate limit filters
  changelog/v1.16.0-beta7/add-local-ratelimit.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/connection_limit/connection_limit.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/local_ratelimit/local_ratelimit.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableTcpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/connection_limit/connection_limit.proto
  projects/gloo/api/v1/options/local_ratelimit/local_ratelimit.proto
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.hash.go
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/options/connection_limit/connection_limit.pb.go
  projects/gloo/pkg/api/v1/options/local_ratelimit/local_ratelimit.pb.clone.go
  projects/gloo/pkg/api/v1/options/local_ratelimit/local_ratelimit.pb.equal.go
  projects/gloo/pkg/api/v1/options/local_ratelimit/local_ratelimit.pb.go
  projects/gloo/pkg/api/v1/options/local_ratelimit/local_ratelimit.pb.hash.go
  projects/gloo/pkg/plugins/connection_limit/plugin.go
  projects/gloo/pkg/plugins/local_ratelimit/local_ratelimit_suite_test.go
  projects/gloo/pkg/plugins/local_ratelimit/plugin.go
  projects/gloo/pkg/plugins/local_ratelimit/plugin_test.go
  projects/gloo/pkg/plugins/local_ratelimit/utils.go
  projects/gloo/pkg/plugins/registry/registry.go
  projects/gloo/pkg/translator/translator_test.go
  test/e2e/local_ratelimit_test.go
  test/gomega/matchers/contain_headers.go
  test/gomega/matchers/contain_headers_test.go
  test/gomega/transforms/transforms.go
Labels: keep pr updated

#8653 Fix Version Tagging on PRs
  Makefile
  changelog/v1.16.0-beta8/fix-version-on-prs.yaml
Labels: keep pr updated

#8651 [v1.15.x] - Backport OIDC add claims to headers
  changelog/v1.15.4/add-claims-to-headers-for-oidc-plugin.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#8654 Docs bump version
  changelog/v1.16.0-beta8/docs-bump-version.yaml
  docs/active_versions.json
Labels: keep pr updated

#8656 Docs: Note to use 1.15.1+ only
  changelog/v1.16.0-beta8/docs-1.15.0-warning.yaml
  docs/content/installation/glooctl_setup.md
  docs/content/operations/upgrading/canary.md
  docs/content/operations/upgrading/faq.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#8657 Fix broken extauth opa auth options proto message
  changelog/v1.16.0-beta8/fix-broken-opaauthoptions.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#8658 Fix gateway yaml when using kube overrides
  changelog/v1.16.0-beta9/fix-gateway-yaml.yaml
  go.mod
  go.sum
  install/helm/gloo/templates/_8-default-gateways.tpl
  install/test/helm_test.go
Labels: keep pr updated

#8659 Fix gateway yaml [1.15]
  changelog/v1.15.5/fix-gateway-yaml.yaml
  go.mod
  go.sum
  install/helm/gloo/templates/_8-default-gateways.tpl
  install/test/helm_test.go
Labels: keep pr updated

#8661 Fix gateway yaml [1.13]
  changelog/v1.13.26/fix-gateway-yaml.yaml
  go.mod
  go.sum
  install/helm/gloo/templates/_8-default-gateways.tpl
  install/test/helm_test.go
Labels: keep pr updated

#8663 fix failover gw
  install/helm/gloo/templates/_8-default-gateways.tpl
  install/test/helm_test.go
Labels: keep pr updated

#8660 Fix gateway yaml [1.14]
  changelog/v1.14.19/fix-gateway-yaml.yaml
  go.mod
  go.sum
  install/helm/gloo/templates/_8-default-gateways.tpl
  install/test/helm_test.go
Labels: keep pr updated

#8665 fix failover gw [1.13]
  install/helm/gloo/templates/_8-default-gateways.tpl
  install/test/helm_test.go
Labels: keep pr updated

#8664 fix failover gw [1.15]
  changelog/v1.15.5/fix-failover-gw.yaml
  install/helm/gloo/templates/_8-default-gateways.tpl
  install/test/helm_test.go
Labels: keep pr updated

#8668 V1.15.x doc fixes
  changelog/v1.15.5/doc-fixes.yaml
  docs/content/guides/security/limit-connection.md
  docs/content/guides/traffic_management/hello_world/_index.md
  docs/content/guides/traffic_management/listener_configuration/caching/_index.md
  docs/content/installation/enterprise/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#8667 mod: fork go control plane
  changelog/v1.16.0-beta9/envoy-gloo-bump.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/core/v3/grpc_service.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extproc/extproc.proto.sk.md
  go.mod
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/external/envoy/config/core/v3/grpc_service.proto
  projects/gloo/api/v1/enterprise/options/extproc/extproc.proto
  projects/gloo/pkg/api/external/envoy/config/core/v3/grpc_service.pb.clone.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/grpc_service.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/grpc_service.pb.go
  projects/gloo/pkg/api/external/envoy/config/core/v3/grpc_service.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/extproc/extproc.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extproc/extproc.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extproc/extproc.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extproc/extproc.pb.hash.go
Labels: Area: Envoy, keep pr updated

#8674 1.15: mod: fork go control plane (#8667)
  Makefile
  changelog/v1.15.5/envoy-gloo-bump.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extproc/extproc.proto.sk.md
  go.mod
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/enterprise/options/extproc/extproc.proto
  projects/gloo/pkg/api/v1/enterprise/options/extproc/extproc.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extproc/extproc.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extproc/extproc.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extproc/extproc.pb.hash.go
Labels: keep pr updated

#8605 Handle STS Credentials region
  Makefile
  changelog/v1.16.0-beta10/handle-sts-credentials-region.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/aws/filter.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  projects/gloo/api/external/envoy/extensions/aws/filter.proto
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.hash.go
  test/e2e/aws_test.go
Labels: keep pr updated

#8683 Restore tag_regex in Makefile
  Makefile
  changelog/v1.16.0-beta10/restore-tag-regex.yaml
Labels: keep pr updated

#8682 [v1.13.x] Backport Handle STS Credentials region (#8605)
  Makefile
  changelog/v1.13.27/handle-sts-credentials-region.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/aws/filter.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  projects/gloo/api/external/envoy/extensions/aws/filter.proto
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.hash.go
  test/e2e/aws_test.go
Labels: keep pr updated

#8680 [v1.15.x] Backport Handle STS Credentials region (#8605)
  Makefile
  changelog/v1.15.6/handle-sts-credentials-region.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/aws/filter.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/templates/18-settings.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  projects/gloo/api/external/envoy/extensions/aws/filter.proto
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/aws/filter.pb.hash.go
  test/e2e/aws_test.go
Labels: keep pr updated

#8688 Fix tagging [1.15]
  Makefile
  changelog/v1.15.6/fix-version-on-prs.yaml
Labels: keep pr updated

#8678 Use appendAction for translated HeaderValueOptions
  changelog/v1.16.0-beta10/translate-to-envoy-append-action.yaml
  docs/content/guides/traffic_management/request_processing/append_remove_headers/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/headers/headers.proto.sk.md
  pkg/utils/api_conversion/type.go
  pkg/utils/api_conversion/type_test.go
  projects/gloo/api/v1/options/headers/headers.proto
  projects/gloo/pkg/api/v1/options/headers/headers.pb.go
  projects/gloo/pkg/plugins/headers/plugin.go
  projects/gloo/pkg/plugins/headers/plugin_test.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#8697 [1.15] Add Vault + AWS IRSA Integration Docs
  .github/workflows/regression-tests.yaml
  changelog/v1.15.6/docs-for-vault-aws-irsa-integration.yaml
  docs/content/guides/integrations/vault/_index.md
  docs/content/guides/integrations/vault/aws-irsa-auth/_index.md
  test/e2e/vault_aws_test.go
Labels: keep pr updated

#8703 remove 1.11 from scans, docs, issue template
  .github/ISSUE_TEMPLATE/DOCS-ISSUE.yml
  .github/workflows/docs-gen.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  Makefile
  changelog/v1.16.0-beta10/remove-1.11-scans.yaml
  docs/Makefile
Labels: keep pr updated

#8692 Expose most_specific_header_mutations_wins
  changelog/v1.16.0-beta10/expose-most-specific-header-mutations-wins.yaml
  docs/content/guides/traffic_management/request_processing/append_remove_headers/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gateway/pkg/translator/translator_test.go
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
  test/e2e/headers_test.go
  test/gomega/matchers/contain_headers.go
  test/gomega/matchers/contain_headers_test.go
  test/helpers/route_tables.go
  test/helpers/routes.go
  test/services/gloo.go
Labels: keep pr updated

#8704 [1.15] Expose most_specific_header_mutations wins and use append_action
  changelog/v1.15.6/append-action-and-most-specific-header-mutations-wins.yaml
  docs/content/guides/traffic_management/request_processing/append_remove_headers/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/headers/headers.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  pkg/utils/api_conversion/type.go
  pkg/utils/api_conversion/type_test.go
  projects/gateway/pkg/translator/translator_test.go
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/headers/headers.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/options/headers/headers.pb.go
  projects/gloo/pkg/plugins/headers/plugin.go
  projects/gloo/pkg/plugins/headers/plugin_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
  projects/gloo/pkg/translator/translator_test.go
  test/e2e/headers_test.go
  test/gomega/matchers/contain_headers.go
  test/gomega/matchers/contain_headers_test.go
  test/helpers/route_tables.go
  test/helpers/routes.go
  test/services/gloo.go
Labels: keep pr updated

#8705 [1.14] Expose most_specific_header_mutations wins and use append_action
  changelog/v1.14.20/append-action-and-most-specific-header-mutations-wins.yaml
  docs/content/guides/traffic_management/request_processing/append_remove_headers/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/headers/headers.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  pkg/utils/api_conversion/type.go
  pkg/utils/api_conversion/type_test.go
  projects/gateway/pkg/translator/translator_test.go
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/headers/headers.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/options/headers/headers.pb.go
  projects/gloo/pkg/plugins/headers/plugin.go
  projects/gloo/pkg/plugins/headers/plugin_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
  projects/gloo/pkg/translator/translator_test.go
  test/e2e/headers_test.go
  test/gomega/matchers/contain_headers.go
  test/gomega/matchers/contain_headers_test.go
  test/gomega/matchers/matchers_suite_test.go
  test/helpers/route_tables.go
  test/helpers/routes.go
  test/services/gateway.go
Labels: keep pr updated

#8702 OIDC auth0 doc update
  changelog/v1.16.0-beta11/docs-for-vault-aws-irsa-integration copy.yaml
  docs/content/guides/security/auth/extauth/oauth/auth0/_index.md
Labels: keep pr updated

#8708 Helm support for FIPS Discovery image
  changelog/v1.16.0-beta11/discovery-fips.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
Labels: keep pr updated

#8710 Doc fixes
  changelog/v1.16.0-beta11/doc-fixes.yaml
  docs/content/guides/security/waf/_index.md
  docs/content/guides/traffic_management/destination_types/aws_lambda/eks-service-accounts.md
Labels: keep pr updated

#8711 [1.13] Helm support for FIPS Discovery image
  changelog/v1.13.27/discovery-fips.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
Labels: keep pr updated

#8707 Docs: Local rate limiting
  changelog/v1.16.0-beta12/docs-local-rl.yaml
  docs/content/guides/security/local_rate_limiting/_index.md
  docs/content/guides/security/local_rate_limiting/http.md
  docs/content/guides/security/local_rate_limiting/overview.md
  docs/content/guides/security/local_rate_limiting/tcp.md
  docs/content/guides/security/rate_limiting/_index.md
  docs/content/img/local-rate-limiting.svg
  docs/content/img/local-rl-tokens.svg
Labels: Type: Docs, keep pr updated, release/1.16

#8717 [1.14] Helm support for FIPS Discovery image
  changelog/v1.14.21/discovery-fips.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
Labels: keep pr updated

#8718 [1.15] Helm support for FIPS Discovery image
  changelog/v1.15.7/discovery-fips.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
Labels: keep pr updated
