Repository kgateway-dev/kgateway, pull requests merged in 2023-03, with the labels that each got.

#7889 Simplify token use in workflows
  .github/actions/regression-tests/action.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.14.0-beta15/token-simplification.yaml
Labels: keep pr updated

#7892 ci: bump go to 1.18.6 to prevent possible denial of service to control plane stats end point CVE-2022-27664
  .github/actions/regression-tests/action.yaml
  .github/workflows/codegen.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  Makefile
  changelog/v1.13.9/go-bump.yaml
  cloudbuild-cache.yaml
  cloudbuild.yaml
Labels: keep pr updated

#7911 ci: bump go to 1.18.6 to prevent possible denial of service to control plane stats end point CVE-2022-27664 (#7892)
  .github/actions/regression-tests/action.yaml
  .github/workflows/codegen.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  Makefile
  changelog/v1.12.47/go-bump.yaml
  cloudbuild-cache.yaml
  cloudbuild.yaml
Labels: keep pr updated

#7909 Docs revision to the Wasm guide
  changelog/v1.14.0-beta16/doc-wasm.yaml
  docs/content/guides/traffic_management/hello_world/_index.md
  docs/content/installation/advanced_configuration/wasm.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/glooctl_setup.md
  docs/content/installation/platform_configuration/cluster_setup.md
Labels: Type: Docs, keep pr updated

#7915 Doc fixes 02/27
  changelog/v1.14.0-beta16/doc-fixes.yaml
  docs/content/guides/integrations/ingress/_index.md
  docs/content/guides/security/auth/jwt/access_control/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#7844 Update lambda guide for request/response transformations
  changelog/v1.14.0-beta16/lambda-guide-wrap-transform.yaml
  docs/content/guides/traffic_management/destination_types/aws_lambda/_index.md
Labels: work in progress, Type: Docs, keep pr updated

#7905 Initial slow start support (#7810)
  changelog/v1.13.9/envoy-slow-start-config.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/load_balancer.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/load_balancer.proto
  projects/gloo/pkg/api/v1/load_balancer.pb.clone.go
  projects/gloo/pkg/api/v1/load_balancer.pb.equal.go
  projects/gloo/pkg/api/v1/load_balancer.pb.go
  projects/gloo/pkg/api/v1/load_balancer.pb.hash.go
  projects/gloo/pkg/plugins/loadbalancer/plugin.go
  projects/gloo/pkg/plugins/loadbalancer/plugin_test.go
Labels: keep pr updated

#7918 Stability: Fix Istio Kube2e Flake
  changelog/v1.14.0-beta16/kube2e-test-cleanup.yaml
  test/kube2e/gloo/artifacts/helm.yaml
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/glooctl/artifacts/helm.yaml
  test/kube2e/glooctl/glooctl_suite_test.go
  test/kube2e/istio/artifacts/helm.yaml
  test/kube2e/istio/istio_suite_test.go
Labels: keep pr updated

#7910 Improve Build-Bot Execution
  BUILD.md
  Makefile
  artifacts.yaml
  changelog/v1.14.0-beta16/cloudbuild-sub-builds.yaml
  ci/README.md
  ci/cloudbuild/README.md
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  ci/spell.sh
  cloudbuild.yaml
Labels: keep pr updated

#7922 Stability: Document TestUpstream
  test/v1helpers/test_upstream.go
Labels: Type: Docs, keep pr updated

#7921 Stability: Fix Route Transformation Test Flake
  changelog/v1.14.0-beta16/route-transformation-e2e-flake.yaml
  test/e2e/example_test.go
  test/e2e/fault_injection_test.go
  test/e2e/route_transformation_test.go
  test/e2e/staged_transformation_test.go
  test/e2e/test_context.go
Labels: keep pr updated

#7930 1.12 - backport upgrade tests
  changelog/v1.12.48/backport-upgrade-tests.yaml
  test/kube2e/upgrade/README.md
  test/kube2e/upgrade/artifacts/helm.yaml
  test/kube2e/upgrade/upgrade_suite_test.go
  test/kube2e/upgrade/upgrade_test.go
  test/kube2e/upgrade/upgrade_utils.go
  test/kube2e/util.go
Labels: keep pr updated

#7933 1.12 gloo/docker: Missed alpine bump, now bumped
  changelog/v1.12.48/alpine-bump.yaml
  projects/gloo/Dockerfile
Labels: keep pr updated

#7935 gloo/docker: Missed alpine bump, now bumped
  changelog/v1.14.0-beta16/alpine-bump.yaml
  projects/gloo/Dockerfile
Labels: keep pr updated

#7937 12/build(glooctl): removed ginkgo and gomega dependencies
  .gitignore
  changelog/v1.12.48/reduce-dependency-footprint.yaml
  hack/dependency-hunter.py
  pkg/cliutil/install/kubernetes.go
  pkg/cliutil/testutil/testutil.go
  projects/gloo/cli/pkg/cmd/debug/debug_test.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/install/uninstall_test.go
Labels: keep pr updated

#7938 11/build(glooctl): removed ginkgo and gomega dependencies
  .gitignore
  changelog/v1.11.54/reduce-dependency-footprint.yaml
  hack/dependency-hunter.py
  pkg/cliutil/install/kubernetes.go
  pkg/cliutil/testutil/testutil.go
  projects/gloo/cli/pkg/cmd/debug/debug_test.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/install/uninstall_test.go
Labels: keep pr updated

#7934 1.13 gloo/docker: Missed alpine bump, now bumped
  changelog/v1.13.10/alpine-bump.yaml
  projects/gloo/Dockerfile
Labels: keep pr updated

#7936 13/build(glooctl): removed ginkgo and gomega dependencies
  .gitignore
  changelog/v1.13.10/reduce-dependency-footprint.yaml
  hack/dependency-hunter.py
  pkg/cliutil/install/kubernetes.go
  pkg/cliutil/testutil/testutil.go
  projects/gloo/cli/pkg/cmd/debug/debug_test.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/install/uninstall_test.go
Labels: keep pr updated

#7945 Docs - rate limiting setup and generic key guide updates
  changelog/v1.14.0-beta16/doc-rate-limit.yaml
  docs/content/guides/security/rate_limiting/envoy/_index.md
  docs/content/guides/security/rate_limiting/setup.md
  docs/content/static/content/rl-setup-before-you-begin
  docs/content/static/content/rl-setup-check-vs
  docs/content/static/content/rl-setup-implement
  docs/content/static/content/rl-setup-rlc-step
  docs/content/static/content/rl-setup-rlc-vs-host
  docs/content/static/content/rl-setup-rlc-vs-ov
  docs/content/static/content/rl-setup-rlc-vs-route
  docs/content/static/content/rl-setup-separate-settings
  docs/content/static/content/rl-setup-separate-vs-host
  docs/content/static/content/rl-setup-separate-vs-ov
  docs/content/static/content/rl-setup-separate-vs-route
Labels: Type: Docs, keep pr updated

#7942 test(gateway): add test specs to better detect future flakes
  changelog/v1.14.0-beta16/add-failure-context.yaml
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#7946 Docs grpc
  changelog/v1.14.0-beta16/docs-grpc
  docs/content/guides/traffic_management/destination_types/grpc/_index.md
  docs/content/guides/traffic_management/destination_types/grpc/about.md
  docs/content/guides/traffic_management/destination_types/grpc/grpc-transcoding.md
  docs/content/guides/traffic_management/destination_types/grpc/simple-routing.md
  docs/content/guides/traffic_management/destination_types/grpc/transcoding-reference.md
  docs/content/guides/traffic_management/destination_types/grpc_to_rest/_index.md
  docs/content/guides/traffic_management/destination_types/grpc_to_rest_advanced/_index.md
Labels: keep pr updated

#7947 test(upgrade): allow time for helper ns to be deleted in upgrade testing
  changelog/v1.14.0-beta16/wait-delete-ns.yaml
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#7955 [1.13] Resolve CVEs
  Makefile
  changelog/v1.13.11/xnet-cve.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#7948 Make Consul E2E Test Run in Order
  changelog/v1.14.0-beta16/consul-e2e-ordered.yaml
  test/e2e/consul_test.go
Labels: keep pr updated

#7957 [1.12] Resolve CVEs
  Makefile
  changelog/v1.12.49/xnet-cve.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#7954 Resolve golang.org/x/net CVE (CVE-2022-41723)
  changelog/v1.14.0-beta16/xnet-cve.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#7962 Improve istio plugin translation time
  changelog/v1.14.0-beta16/istio-plugin-speedup.yaml
  projects/gloo/pkg/plugins/istio_integration/istio_suite_test.go
  projects/gloo/pkg/plugins/istio_integration/plugin.go
  projects/gloo/pkg/plugins/istio_integration/plugin_test.go
  projects/gloo/pkg/plugins/registry/registry.go
Labels: keep pr updated

#7967 Improve istio plugin translation time [1.12]
  changelog/v1.12.49/istio-plugin-speedup.yaml
  projects/gloo/pkg/plugins/istio_integration/istio_suite_test.go
  projects/gloo/pkg/plugins/istio_integration/plugin.go
  projects/gloo/pkg/plugins/istio_integration/plugin_test.go
  projects/gloo/pkg/plugins/registry/registry.go
Labels: keep pr updated

#7968 Improve istio plugin translation time [1.13]
  changelog/v1.13.11/istio-plugin-speedup.yaml
  projects/gloo/pkg/plugins/istio_integration/istio_suite_test.go
  projects/gloo/pkg/plugins/istio_integration/plugin.go
  projects/gloo/pkg/plugins/istio_integration/plugin_test.go
  projects/gloo/pkg/plugins/registry/registry.go
Labels: keep pr updated

#7969 [1.10] Resolve CVEs
  changelog/v1.10.46/xnet-cve.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  test/e2e/dynamic_forward_proxy_test.go
Labels: keep pr updated

#7854 AWS plugin update to support additional metadata in responseTransformation
  Makefile
  changelog/v1.14.0-beta17/merge-responsetransformation-unwrapas.yaml
  docs/content/operations/upgrading/v1.14.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk.md
  projects/gloo/api/external/envoy/extensions/aws/filter.proto
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/api/v1/options/aws/aws.proto
  projects/gloo/pkg/api/v1/options/aws/aws.pb.go
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
  projects/gloo/pkg/plugins/enterprise_warning/plugin.go
  projects/gloo/pkg/plugins/enterprise_warning/plugin_test.go
  test/e2e/aws_test.go
  test/gomega/matchers/http.go
  test/gomega/transforms/transforms.go
Labels: keep pr updated

#7924 7472 sha1 auth
  changelog/v1.14.0-beta17/add_hmac_extauth.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/secret.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  pkg/utils/syncutil/log_redactor_test.go
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/api/v1/secret.proto
  projects/gloo/cli/pkg/printers/authconfig.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
  projects/gloo/pkg/api/v1/secret.pb.go
Labels: keep pr updated

#7978 makefile: Quiet alerts for alpine versions
  Makefile
  changelog/v1.13.11/alpinebump.yaml
Labels: keep pr updated

#7812 API changes for upstream grpc-rest plugin
  changelog/v1.14.0-beta17/grpc-options.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/grpc/grpc.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/service_spec.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/discovery/pkg/fds/discoveries/grpc/grpc.go
  projects/gloo/api/v1/options/grpc/grpc.proto
  projects/gloo/api/v1/options/service_spec.proto
  projects/gloo/pkg/api/v1/options/grpc/grpc.pb.go
  projects/gloo/pkg/api/v1/options/service_spec.pb.clone.go
  projects/gloo/pkg/api/v1/options/service_spec.pb.equal.go
  projects/gloo/pkg/api/v1/options/service_spec.pb.go
  projects/gloo/pkg/api/v1/options/service_spec.pb.hash.go
  projects/gloo/pkg/plugins/grpc/plugin.go
  projects/gloo/pkg/plugins/grpcjson/plugin.go
  test/e2e/grpc_discovery_test.go
  test/e2e/grpc_json_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/health_checks_test.go
  test/e2e/test_context.go
  test/v1helpers/test_grpc_service/descriptors/proto-paths.pb
  test/v1helpers/test_grpc_service/descriptors/proto.pb
  test/v1helpers/test_grpc_service/glootest/protos/glootest.pb.go
  test/v1helpers/test_grpc_service/glootest/protos/glootest_grpc.pb.go
  test/v1helpers/test_grpc_service/protos/glootest.proto
  test/v1helpers/test_grpc_service/testgrpcservice.go
Labels: keep pr updated

#7927 Envoy-gloo bump to support headerBodyTransform improvements
  Makefile
  changelog/v1.14.0-beta17/request-transform-improvements.yaml
  docs/content/guides/traffic_management/destination_types/aws_lambda/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk.md
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/api/v1/options/aws/aws.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
  projects/gloo/pkg/api/v1/options/aws/aws.pb.go
  test/e2e/aws_test.go
  test/e2e/route_transformation_test.go
  test/gomega/transforms/transforms.go
Labels: keep pr updated

#7997 Stability: Fix Leader Elector Test Flake
  changelog/v1.14.0-beta18/leader-elector-test-flake.yaml
  pkg/bootstrap/leaderelector/leader.go
  pkg/bootstrap/leaderelector/leader_test.go
Labels: keep pr updated

#7979 build: remove race image from CI
  Makefile
  changelog/v1.14.0-beta18/remove-race-image.yaml
Labels: keep pr updated

#8010 Doc fixes 1.12.x
  changelog/v1.12.50/doc-fixes.yaml
  docs/Makefile
  docs/content/guides/integrations/cert_manager/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/xslt_transformation/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#8007 Doc fixes 1.14
  changelog/v1.14.0-beta18/doc-fixes.yaml
  docs/content/guides/integrations/cert_manager/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/xslt_transformation/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#8000 Changes to docs to reflect current behavior with respect to licensing
  changelog/v1.14.0-beta18/licensing-docs-changes.yaml
  docs/content/img/k9s-license-expired.png
  docs/content/operations/updating_license/_index.md
Labels: keep pr updated

#8013 Fix instructions for installing OIDC with Dex
  changelog/v1.14.0-beta18/oidc-docs.yaml
  docs/content/guides/security/auth/extauth/oauth/dex/_index.md
Labels: keep pr updated

#8016 build: resolved GHA warnings
  .github/actions/regression-tests/action.yaml
  .github/workflows/add-pr-label.yaml
  .github/workflows/codegen.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.14.0-beta18/remove-gha-warnings.yaml
Labels: keep pr updated

#8015 [1.10]] CVE fix
  changelog/v1.10.47/cves.yaml
  docs/content/guides/dev/writing_auth_plugins/_index.md
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#7995 Contraining certgen jobs acess permissions to secrets within cluster via `global.glooRbac.namespaced`
  changelog/v1.14.0-beta18/certgen-job-namespacing.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/test/helm_test.go
  install/test/rbac_test.go
Labels: keep pr updated

#8012 Docs: GraphQL remote execution
  changelog/v1.14.0-beta18/doc-graphql-remote.yaml
  docs/content/guides/graphql/_index.md
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/guides/graphql/getting_started.md
  docs/content/guides/graphql/getting_started/_index.md
  docs/content/guides/graphql/getting_started/local_executor.md
  docs/content/guides/graphql/getting_started/remote_executor.md
  docs/content/guides/graphql/getting_started/secure_api.md
  docs/content/guides/graphql/getting_started/setup.md
  docs/content/guides/graphql/getting_started/simple_discovery.md
  docs/content/guides/graphql/observability.md
  docs/content/guides/graphql/resolver_config.md
Labels: keep pr updated

#7999 Fix SslConfig Merge When Using isolateVirtualHostsBySslConfig
  changelog/v1.14.0-beta18/ssl-merge-bug.yaml
  projects/gateway/pkg/translator/aggregate_translator.go
  projects/gateway/pkg/translator/ssl_configuration.go
  projects/gateway/pkg/translator/ssl_configuration_test.go
  test/e2e/aggregate_listener_test.go
  test/e2e/proxy_protocol_test.go
  test/helpers/helpers_suite_test.go
  test/helpers/virtual_services.go
  test/helpers/virtual_services_test.go
  test/testutils/http_client.go
  test/testutils/http_client_test.go
  test/testutils/http_request_test.go
  test/testutils/testutils_suite_test.go
  test/v1helpers/test_upstream.go
Labels: keep pr updated

#8028 Stability: Fix Dynamic Forward Proxy Test Flake
  changelog/v1.14.0-beta18/dfp-e2e-flake.yaml
  test/e2e/dynamic_forward_proxy_test.go
  test/testutils/http_client.go
Labels: keep pr updated

#8009 Adding IRSA + Upgrade cert-manager version
  docs/content/guides/integrations/cert_manager/_index.md
Labels: Type: Docs, keep pr updated

#8037 Doc fixes
  changelog/v1.14.0-beta18/doc-fixes2.yaml
  docs/content/guides/integrations/cert_manager/_index.md
  docs/content/guides/security/auth/extauth/opa/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/static/content/version_gee_latest.md
Labels: Type: Docs
