Repository kgateway-dev/kgateway, pull requests merged in 2023-02, with the labels that each got.

#7466 Istio Integration: Wrong Port When Service TargetPort Is Different Fix
  .github/workflows/regression-tests.yaml
  changelog/v1.14.0-beta8/fix-istio-integration-targetPort-endpoint-bug.yaml
  ci/deploy-to-kind-cluster.sh
  projects/gloo/pkg/plugins/kubernetes/eds.go
  test/helpers/kube_dump.go
  test/kube2e/istio/istio_integration_test.go
  test/kube2e/istio/istio_suite_test.go
  test/kube2e/util.go
Labels: keep pr updated

#7776 test(gateway): clean up secrets after tests
  changelog/v1.14.0-beta8/secret-existing-failure.yaml
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#7771 allow QP on re-writes
  changelog/v1.14.0-beta8/allow-query-parameters-on-re-writes.yaml
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
Labels: keep pr updated

#7783 allow QP on re-writes (#7771)
  changelog/v1.12.43/allow-query-parameters-on-re-writes.yaml
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
Labels: keep pr updated

#7784 allow QP on re-writes (#7771)
  changelog/v1.11.51/allow-query-parameters-on-re-writes.yaml
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
Labels: keep pr updated

#7782 allow QP on re-writes (#7771)
  changelog/v1.13.5/allow-query-parameters-on-re-writes.yaml
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
Labels: keep pr updated

#7785 allow QP on re-writes (#7771)
  changelog/v1.10.44/allow-query-parameters-on-re-writes.yaml
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
Labels: keep pr updated

#7808 1.12/make cli safe for testing
  changelog/v1.12.44/cli-leak-hardening.yaml
  projects/gloo/cli/pkg/helpers/clients.go
  test/kube2e/upgrade/upgrade_utils.go
Labels: keep pr updated

#7809 cli: context todo cleanup for gleak
  changelog/v1.14.0-beta9/cli-context-leak.yaml
  projects/gloo/cli/pkg/helpers/clients.go
Labels: keep pr updated

#7778 [1.12.x] Istio Integration: Wrong Port When Service TargetPort Is Different Fix
  .github/workflows/regression-tests.yaml
  changelog/v1.12.45/fix-istio-integration-targetPort-endpoint-bug.yaml
  ci/deploy-to-kind-cluster.sh
  projects/gloo/pkg/plugins/kubernetes/eds.go
  test/helpers/kube_dump.go
  test/kube2e/istio/istio_integration_test.go
  test/kube2e/istio/istio_suite_test.go
Labels: keep pr updated

#7754 gloo/plugins/faultinjection: Add extra validation gaurd rails in go code
  changelog/v1.14.0-beta10/fix-fault-plugin-validation.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/faultinjection/fault.proto.sk.md
  projects/gloo/api/v1/options/faultinjection/fault.proto
  projects/gloo/pkg/api/v1/options/faultinjection/fault.pb.go
  projects/gloo/pkg/plugins/faultinjection/plugin.go
  projects/gloo/pkg/plugins/faultinjection/plugin_test.go
Labels: keep pr updated

#7777 [1.13.x] Istio Integration: Wrong Port When Service TargetPort Is Different Fix
  .github/workflows/regression-tests.yaml
  changelog/v1.13.7/fix-istio-integration-targetPort-endpoint-bug.yaml
  ci/deploy-to-kind-cluster.sh
  projects/gloo/pkg/plugins/kubernetes/eds.go
  test/helpers/kube_dump.go
  test/kube2e/istio/istio_integration_test.go
  test/kube2e/istio/istio_suite_test.go
  test/kube2e/util.go
Labels: keep pr updated

#7797 Exposed `config.listener.v3.Listener.ConnectionBalanceConfig` as `gloo.solo.io.ListenerOptions.connection_balance_config`
  changelog/v1.14.0-beta10/listener-connection-config.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/advanced_http/advanced_http.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/options/advanced_http/advanced_http.pb.go
  projects/gloo/pkg/plugins/listener/plugin.go
  projects/gloo/pkg/plugins/listener/plugin_test.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#7823 Docs ldap svc account
  docs/content/guides/security/auth/extauth/ldap/_index.md
Labels: keep pr updated

#7819 [v1.10.x] Update gopkg.in/yaml.v3 to resolve CVE
  changelog/v1.10.45/security-update.yaml
  go.mod
  go.sum
Labels: keep pr updated

#7811 [lambda] Enforce mutual exclusivity between responseTransformation and unwrapAs
  changelog/v1.14.0-beta10/lambda-unwrap-no-transform.yaml
  projects/gloo/pkg/plugins/aws/plugin.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
Labels: keep pr updated

#7832 revert cloudbuild bumps
  changelog/v1.10.45/fix-cloudbuild.yaml
  cloudbuild.yaml
Labels: keep pr updated

#7833 revert cloudbuild bumps [1.11]
  changelog/v1.11.52/fix-cloudbuild.yaml
  cloudbuild.yaml
Labels: keep pr updated

#7804 Fix Istio Crash When Using Headless Services
  changelog/v1.14.0-beta10/fix-istio-integration-headless-service-crash.yaml
  projects/gloo/pkg/plugins/kubernetes/eds.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  test/kube2e/istio/istio_integration_test.go
Labels: keep pr updated

#7824 Prep Makefile for Ginkgo v2
  .github/actions/regression-tests/action.yaml
  Makefile
  changelog/v1.14.0-beta10/prep-ginkgo-v2.yaml
  cloudbuild.yaml
  pkg/bootstrap/leaderelector/leader_test.go
  projects/gateway/pkg/reconciler/proxy_reconciler_test.go
  projects/gateway/pkg/translator/translator_test.go
  projects/gloo/cli/pkg/cmd/edit/settings/extauth_test.go
  projects/gloo/cli/pkg/cmd/edit/settings/ratelimit/ratelimit_test.go
  projects/gloo/cli/pkg/cmd/edit/upstream/root_test.go
  projects/gloo/cli/pkg/cmd/edit/virtualservice/root_test.go
  projects/gloo/pkg/plugins/aws/plugin_test.go
  projects/gloo/pkg/plugins/stats/stats_test.go
  projects/gloo/pkg/upstreams/hybrid_client_test.go
  projects/sds/pkg/run/run_e2e_test.go
  test/make/make_test.go
Labels: keep pr updated

#7836 [1.12] Fix Istio Crash When Using Headless Services
  changelog/v1.12.45/fix-istio-integration-headless-service-crash.yaml
  projects/gloo/pkg/plugins/kubernetes/eds.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  test/kube2e/istio/istio_integration_test.go
Labels: keep pr updated

#7835 [1.13] Fix Istio Crash When Using Headless Services
  changelog/v1.13.7/fix-istio-integration-headless-service-crash.yaml
  projects/gloo/pkg/plugins/kubernetes/eds.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  test/kube2e/istio/istio_integration_test.go
Labels: keep pr updated

#7849 [v1.12.x] Bump Alpine version in Kubectl Docker image to resolve CVEs
  changelog/v1.12.46/alpine-bump.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#7727 7473 security context customization
  changelog/v1.14.0-beta11/helm-security-customization.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#7851 Doc fixes and version bump
  changelog/v1.14.0-beta11/doc-fixes.yaml
  docs/active_versions.json
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/guides/graphql/stitching.md
  docs/content/guides/security/auth/extauth/opa/_index.md
  docs/content/introduction/security/_index.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#7848 [v1.13.x] Bump Alpine version in Kubectl Docker image to resolve CVEs
  changelog/v1.13.8/alpine-bump.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#7847 Bump Alpine version in Kubectl Docker image to resolve CVEs
  changelog/v1.14.0-beta11/alpine-bump.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#7850 [v1.11.x] Bump Alpine version in Kubectl Docker image to resolve CVEs
  changelog/v1.11.53/alpine-bump.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#7815 Update .trivyignore to resolve security alerts
  .trivyignore
  changelog/v1.14.0-beta12/security-update.yaml
Labels: keep pr updated

#7857 Deflake Tests Failing after Randomize Flags Added
  Makefile
  changelog/v1.14.0-beta12/deflake-build-bot.yaml
  projects/gateway/pkg/translator/http_translator_test.go
  projects/gloo/pkg/validation/server_test.go
  test/e2e/dynamic_forward_proxy_test.go
  test/make/make_test.go
Labels: keep pr updated

#7855 Expose 'timeoutSeconds' on gloo-gateway-validation-webhook
  changelog/v1.14.0-beta12/webhook-timeout.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  install/test/helm_test.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#7834 Support RespectDnsTtl and DnsRefreshRate in Upstream API
  changelog/v1.14.0-beta12/dns-ttl.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/upstream.pb.clone.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/kubernetes/uds_convert_test.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/translator_test.go
  test/e2e/dns_test.go
  test/e2e/test_context.go
Labels: keep pr updated

#7828 feat(DFP): enable tls origination
  changelog/v1.14.0-beta12/7693-feature-complete.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.clone.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.equal.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.go
  projects/gloo/pkg/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.pb.hash.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin_test.go
Labels: keep pr updated

#7821 Upgrade Tests: Add checks to github tags
  changelog/v1.14.0-beta13/upgrade-test-flakes.yaml
  test/kube2e/upgrade/README.md
  test/kube2e/upgrade/upgrade_test.go
  test/kube2e/upgrade/upgrade_utils.go
Labels: keep pr updated

#7866 Trivy version
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.14.0-beta14/trivy-version.yaml
Labels: keep pr updated

#7871 build: repair broken tests
  changelog/v1.12.46/host-repair.yaml
  test/e2e/dynamic_forward_proxy_test.go
Labels: keep pr updated

#7872 build: repair broken tests
  changelog/v1.11.53/host-repair.yaml
  test/e2e/dynamic_forward_proxy_test.go
Labels: keep pr updated

#7874 docs: update to consume LTS branches, rather than patches
  .github/workflows/docs-gen.yaml
  changelog/v1.14.0-beta14/docs-patch-to-minor.yaml
  docs/active_versions.json
  docs/build-docs.sh
Labels: keep pr updated

#7881 fix incorrect merge with master
  Makefile
  test/kube2e/upgrade/upgrade_test.go
Labels: work in progress, keep pr updated

#7891 docs: enterprise proto docs now generate based on minor version
  .github/workflows/docs-gen.yaml
  changelog/v1.14.0-beta15/ee-proto-docs-fix.yaml
  docs/Makefile
  docs/build-docs.sh
Labels: keep pr updated

#7882 Stability: Cleanup Test Utilities And Remove Xds-Relay References in Tests
  changelog/v1.14.0-beta15/gw-kube2e-test-cleanup.yaml
  projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go
  projects/gloo/pkg/bootstrap/utils_test.go
  projects/gloo/pkg/plugins/kubernetes/kubernetes_test.go
  projects/ingress/pkg/api/service/resource_client_test.go
  test/aws_credentials/aws_credentials_suite_test.go
  test/aws_credentials/ec2_test.go
  test/consulvaulte2e/e2e_suite_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
  test/e2e/consul_test.go
  test/e2e/dynamic_forward_proxy_test.go
  test/e2e/example_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/happypath_test.go
  test/e2e/health_checks_test.go
  test/e2e/http_tunneling_test.go
  test/e2e/test_context.go
  test/e2e/vault_test.go
  test/e2e/zipkin_test.go
  test/kube2e/gateway/artifacts/helm.yaml
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gateway/robustness_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/glooctl/glooctl_suite_test.go
  test/kube2e/gloomtls/gloo_mtls_suite_test.go
  test/kube2e/helm/helm_suite_test.go
  test/kube2e/ingress/ingress_suite_test.go
  test/kube2e/istio/istio_suite_test.go
  test/kube2e/knative/knative_suite_test.go
  test/kube2e/upgrade/upgrade_suite_test.go
  test/testutils/env.go
  test/testutils/requirements.go
Labels: keep pr updated
