Repository kgateway-dev/kgateway, pull requests merged in 2023-04, with the labels that each got.

#8002 Added a paragraph to start capturing how to tweak log levels for othe…
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/operations/debugging_gloo/_index.md
Labels: Type: Docs

#8024 k8s 1.25
  .github/actions/regression-tests/action.yaml
  .github/workflows/codegen.yaml
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  Makefile
  changelog/v1.14.0-beta18/k8s-125.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  ci/deploy-to-kind-cluster.sh
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/operations/production_deployment/_index.md
  docs/content/reference/cli/glooctl_add_route.md
  docs/content/reference/cli/glooctl_create_authconfig.md
  docs/content/reference/cli/glooctl_create_virtualservice.md
  docs/content/reference/cli/glooctl_edit_route.md
  docs/content/reference/cli/glooctl_edit_route_externalauth.md
  docs/content/reference/cli/glooctl_edit_settings.md
  docs/content/reference/support.md
  docs/content/reference/values.txt
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  hack/test.sh
  install/helm/gloo/templates/8-gateway-proxy-pod-disruption-budget.yaml
  install/test/helm_test.go
  jobs/kubectl/Dockerfile
  projects/gloo/cli/pkg/cmd/demo/federation.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.6.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7-1.19.go
  projects/gloo/pkg/api/converters/kube/account_credentials_secret.go
  projects/gloo/pkg/api/converters/kube/header_secret.go
  projects/gloo/pkg/api/converters/kube/secretconverter.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  test/checks/checks_suite_test.go
  test/checks/checks_test.go
  test/e2e/consul_test.go
  test/e2e/happypath_test.go
  test/kube2e/README.md
  test/kube2e/gateway/gateway_test.go
  test/mocks/kubernetes/kubeinterface.go
  test/services/gateway.go
Labels: keep pr updated

#8053 remove race from cloudbuild step
  Makefile
  changelog/v1.14.0-beta19/remove-race-ci.yaml
Labels: keep pr updated

#8054 fix go mod path for push solo-apis action
  .github/workflows/push-solo-apis-branch.yaml
Labels: keep pr updated

#8032 Stability: Fix Recent Test Flakes
  changelog/v1.14.0-beta20/consul-e2e-flake.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  projects/gloo/cli/pkg/cmd/add/add_test.go
  projects/gloo/cli/pkg/cmd/create/create_test.go
  projects/gloo/pkg/bootstrap/utils_test.go
  test/consulvaulte2e/consul_vault_test.go
  test/e2e/consul_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/test_context.go
  test/e2e/vault_aws_test.go
  test/e2e/zipkin_test.go
  test/gomega/matchers/contain_substrings.go
  test/services/consul.go
  test/services/functions.go
  test/services/gateway.go
  test/services/gloo.go
  test/services/mesh.go
  test/services/prometheus.go
Labels: keep pr updated

#8067 Stability: Fix Gateway Kube2e Tests For Nightlies
  changelog/v1.14.0-rc1/gateway-kube2e-nighlies.yaml
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#8071 Envoy 1.25.4
  Makefile
  changelog/v1.14.0-rc1/envoy-alpine-cve.yaml
  docs/content/guides/dev/writing_auth_plugins/_index.md
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gloo/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#8074 1.12 make: Update envoy and alpine for cves
  Makefile
  changelog/v1.12.50/envoy-alpine-cve.yaml
  docs/content/guides/dev/writing_auth_plugins/_index.md
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gloo/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#8073 1.13 make: Update envoy and alpine for cves
  Makefile
  changelog/v1.13.12/envoy-alpine-cve.yaml
  docs/content/guides/dev/writing_auth_plugins/_index.md
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gloo/Dockerfile
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#8072 1.15 placeholder and update nightly test matrix
  .github/workflows/nightly-tests.yaml
  changelog/v1.15.0-beta1/placeholder.yaml
Labels: keep pr updated

#8075 Stability: Unit Test Custom Matchers
  test/gomega/matchers/contain_headers.go
  test/gomega/matchers/contain_headers_test.go
  test/gomega/matchers/contain_substrings_test.go
  test/gomega/matchers/matchers_suite_test.go
Labels: keep pr updated

#8064 (1.12) Bump Github Actions versions
  .github/actions/regression-tests/action.yaml
  .github/workflows/add-pr-label.yaml
  .github/workflows/codegen.yaml
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.12.51/github-actions-deprecations.yaml
Labels: keep pr updated

#8065 (1.11) Bump Github Actions versions
  .github/actions/regression-tests/action.yaml
  .github/workflows/add-pr-label.yaml
  .github/workflows/codegen.yaml
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.11.56/github-actions-deprecations.yaml
Labels: keep pr updated

#8062 Bump Github Actions versions
  .github/actions/regression-tests/action.yaml
  .github/workflows/codegen.yaml
  .github/workflows/do-not-submit.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.15.0-beta1/github-actions-deprecations.yaml
Labels: keep pr updated

#8061 Stability: Improve and Clarify How Envoy Test Runner Chooses Image Tag
  changelog/v1.15.0-beta1/e2e-default-tag.yaml
  projects/gateway/pkg/api/v1/kube/generated_kube_suite_test.go
  projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go
  test/e2e/README.md
  test/services/envoy.go
  test/testutils/env.go
  test/testutils/version/changelog.go
Labels: keep pr updated

#8044 Ensure gRPC discovery does not overwrite old API.
  changelog/v1.15.0-beta1/grpc-discovery.yaml
  projects/discovery/pkg/fds/discoveries/grpc/grpc.go
  projects/discovery/pkg/fds/updater.go
  projects/gloo/pkg/plugins/grpc/plugin.go
  test/e2e/grpc_discovery_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/test_context.go
  test/helpers/input_resources.go
  test/v1helpers/test_grpc_service/testgrpcservice.go
Labels: keep pr updated

#8082 Backport grpc discovery
  changelog/v1.14.0-rc2/grpc-discovery.yaml
  projects/discovery/pkg/fds/discoveries/grpc/grpc.go
  projects/discovery/pkg/fds/updater.go
  projects/gloo/pkg/plugins/grpc/plugin.go
  test/e2e/grpc_discovery_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/test_context.go
  test/helpers/input_resources.go
  test/v1helpers/test_grpc_service/testgrpcservice.go
Labels: keep pr updated

#8079 (1.14) Bump Github Actions versions
  .github/actions/regression-tests/action.yaml
  .github/workflows/codegen.yaml
  .github/workflows/do-not-submit.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.14.0-rc2/github-actions-deprecations.yaml
Labels: keep pr updated

#8088 Doc fixes
  docs/content/guides/graphql/getting_started/local_executor.md
  docs/content/guides/graphql/getting_started/remote_executor.md
  docs/content/guides/graphql/getting_started/secure_api.md
  docs/content/guides/graphql/getting_started/simple_discovery.md
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/operations/debugging_gloo/_index.md
Labels: keep pr updated

#8090 Update _index.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
Labels: keep pr updated

#8076 test/upgrade: Update version logic to still return last minors versio…
  changelog/v1.15.0-beta2/upgrade-panic-part2.yaml
  test/kube2e/upgrade/upgrade_suite_test.go
  test/kube2e/upgrade/upgrade_test.go
  test/kube2e/upgrade/upgrade_utils.go
  test/kube2e/upgrade/upgrade_utils_test.go
  test/testutils/version/changelog.go
  test/testutils/version/changelog_test.go
Labels: keep pr updated

#8089 Updating Documentation around config status metrics
  changelog/v1.15.0-beta2/resource-status-monitoring-docs.yaml
  docs/content/guides/traffic_management/configuration_validation/_index.md
  projects/gateway/pkg/validation/validator.go
Labels: keep pr updated

#8085 Graphql per resolver timeout API
  changelog/v1.15.0-beta2/graphql-per-resolver-timeout.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/graphql/v1beta1/graphql.proto.sk.md
  install/helm/gloo/crds/graphql.gloo.solo.io_v1beta1_GraphQLApi.yaml
  projects/gloo/api/external/envoy/extensions/graphql/graphql.proto
  projects/gloo/api/v1/enterprise/options/graphql/v1beta1/graphql.proto
  projects/gloo/pkg/api/external/envoy/extensions/filters/http/graphql/v2/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graphql.pb.hash.go
  test/v1helpers/test_upstream.go
Labels: keep pr updated

#8011 API adding OIDC ciphers
  changelog/v1.15.0-beta2/user-session-encryption.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/secret.proto.sk.md
  docs/content/reference/cli/glooctl_create_secret.md
  docs/content/reference/cli/glooctl_create_secret_encryptionkey.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  pkg/utils/syncutil/log_redactor_test.go
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/api/v1/secret.proto
  projects/gloo/cli/pkg/cmd/create/secret/encryption_key.go
  projects/gloo/cli/pkg/cmd/create/secret/encryption_key_test.go
  projects/gloo/cli/pkg/cmd/create/secret/root.go
  projects/gloo/pkg/api/converters/kube/encryption_key_secret.go
  projects/gloo/pkg/api/converters/kube/encryption_key_secret_test.go
  projects/gloo/pkg/api/converters/kube/secretconverter.go
  projects/gloo/pkg/api/converters/kube/secretconverter_test.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
  projects/gloo/pkg/api/v1/secret.pb.clone.go
  projects/gloo/pkg/api/v1/secret.pb.equal.go
  projects/gloo/pkg/api/v1/secret.pb.go
  projects/gloo/pkg/api/v1/secret.pb.hash.go
Labels: keep pr updated

#8060 Stability: Simplify Image Building and Publishing CI
  .github/actions/regression-tests/action.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  Makefile
  Makefile.ci
  changelog/v1.15.0-beta3/simplify-test-image-registry.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/deploy-to-kind-cluster.sh
  ci/extended-docker/Dockerfile
  ci/extended-docker/README.md
  ci/extended-docker/extended-docker.sh
  ci/kind/cluster.yaml
  ci/kind/setup-kind.sh
  docs/content/guides/dev/building-and-deploying-gloo.md
  docs/content/reference/support.md
  install/helm/gloo/generate.go
  test/kube2e/README.md
  test/kube2e/gloomtls/artifacts/helm.yaml
  test/kube2e/gloomtls/gloo_mtls_suite_test.go
  test/kube2e/upgrade/README.md
Labels: keep pr updated

#8104 Docs: Lambda transforms, glooctl check-crds
  changelog/v1.15.0-beta3/docs-lambda-transforms.yaml
  docs/content/guides/traffic_management/destination_types/aws_lambda/_index.md
  docs/content/operations/upgrading/v1.14.md
Labels: keep pr updated

#8100 devMode changes
  changelog/v1.15.0-beta3/add-dev-mode-helm.yaml
  docs/content/operations/debugging_gloo/_index.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#8110 Centralize where go version is specified
  Makefile
  changelog/v1.15.0-beta3/golang-version-location.yaml
  cloudbuild-cache.yaml
  go.mod
Labels: keep pr updated

#8101 Added File Based Standard Logging to docs.
  docs/content/guides/security/access_logging/_index.md
Labels: Type: Docs

#8096 build: reduce log burden by suppressing docker build logs
  Makefile
  Makefile.ci
  changelog/v1.15.0-beta3/suppress-ci-docker.yaml
  ci/kind/setup-kind.sh
Labels: keep pr updated

#8111 Docs for xds removal and keepalive note
  changelog/v1.15.0-beta3/docs-xds.yaml
  docs/content/installation/advanced_configuration/gateway-proxy-config.md
  docs/content/installation/advanced_configuration/multi-gw-deployment.md
  docs/content/installation/enterprise/_index.md
  docs/content/operations/advanced/xds_relay/_index.md
  docs/content/operations/production_deployment/_index.md
  docs/content/operations/upgrading/canary.md
  docs/content/operations/upgrading/v1.13.md
Labels: Type: Docs, keep pr updated

#8105 Doc fixes
  changelog/v1.15.0-beta4/doc-fixes.yaml
  docs/content/guides/integrations/datadog/_index.md
  docs/content/guides/security/access_logging/_index.md
  docs/content/guides/traffic_management/buffering/_index.md
  docs/content/guides/traffic_management/destination_types/ec2_upstream/_index.md
  docs/content/guides/traffic_management/request_processing/shadowing/_index.md
  docs/content/operations/upgrading/v1.14.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#8118 Backport v1.13.x docs
  changelog/v1.13.14/doc-backport.yaml
  docs/content/guides/integrations/datadog/_index.md
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/guides/security/access_logging/_index.md
  docs/content/guides/traffic_management/buffering/_index.md
  docs/content/guides/traffic_management/destination_types/ec2_upstream/_index.md
  docs/content/guides/traffic_management/request_processing/shadowing/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/installation/advanced_configuration/gateway-proxy-config.md
  docs/content/installation/advanced_configuration/multi-gw-deployment.md
  docs/content/installation/enterprise/_index.md
  docs/content/operations/advanced/xds_relay/_index.md
  docs/content/operations/debugging_gloo/_index.md
  docs/content/operations/production_deployment/_index.md
  docs/content/operations/upgrading/canary.md
  docs/content/operations/upgrading/v1.13.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#8121 [v1.13.x] Update go-version-file field in push-solo-apis-branch workflow
  .github/workflows/push-solo-apis-branch.yaml
  changelog/v1.13.14/update-mod-location.yaml
Labels: keep pr updated

#8122 [v1.12.x] Update go-version-file field in push-solo-apis-branch workflow
  .github/workflows/push-solo-apis-branch.yaml
  changelog/v1.12.52/update-mod-location.yaml
Labels: keep pr updated

#8123 [v1.11.x] Update go-version-file field in push-solo-apis-branch workflow
  .github/workflows/push-solo-apis-branch.yaml
  changelog/v1.11.57/update-mod-location.yaml
Labels: keep pr updated

#8124 fix make target for kind-reload-gloo-envoy-wrapper
  Makefile
Labels: keep pr updated

#8112 docs oidc cookie encryption
  changelog/v1.15.0-beta4/docs-oidc-cookie-encryption.yaml
  docs/content/guides/security/auth/extauth/oauth/_index.md
Labels: Type: Docs, keep pr updated, release/1.15

#8114 Cleanup Github Actions and Makefile
  .github/workflows/README.md
  .github/workflows/push-solo-apis-branch.yaml
  Makefile
Labels: keep pr updated

#8119 Backport v1.14.x docs
  changelog/v1.14.0-rc3/doc-backports.yaml
  docs/content/guides/graphql/getting_started/local_executor.md
  docs/content/guides/graphql/getting_started/remote_executor.md
  docs/content/guides/graphql/getting_started/secure_api.md
  docs/content/guides/graphql/getting_started/simple_discovery.md
  docs/content/guides/integrations/datadog/_index.md
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/guides/security/access_logging/_index.md
  docs/content/guides/traffic_management/buffering/_index.md
  docs/content/guides/traffic_management/configuration_validation/_index.md
  docs/content/guides/traffic_management/destination_types/aws_lambda/_index.md
  docs/content/guides/traffic_management/destination_types/ec2_upstream/_index.md
  docs/content/guides/traffic_management/request_processing/shadowing/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/installation/advanced_configuration/gateway-proxy-config.md
  docs/content/installation/advanced_configuration/multi-gw-deployment.md
  docs/content/installation/enterprise/_index.md
  docs/content/operations/advanced/xds_relay/_index.md
  docs/content/operations/debugging_gloo/_index.md
  docs/content/operations/production_deployment/_index.md
  docs/content/operations/upgrading/canary.md
  docs/content/operations/upgrading/v1.13.md
  docs/content/operations/upgrading/v1.14.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#8117 refactor(upgrade): simplify return branches of GetUpgradeVersions
  changelog/v1.15.0-beta4/upgrade-utils-refactor.yaml
  test/kube2e/upgrade/upgrade_suite_test.go
  test/kube2e/upgrade/upgrade_utils.go
Labels: keep pr updated

#8130 [v1.13.x] Expand RELEASE_BRANCH properly in push-solo-apis-branch
  .github/workflows/push-solo-apis-branch.yaml
  changelog/v1.13.15/expand-release-branch-yaml
Labels: keep pr updated

#8131 [v1.11.x] Ensure that RELEASE_BRANCH is set
  .github/workflows/push-solo-apis-branch.yaml
  changelog/v1.11.58/fix-release-branch
Labels: keep pr updated

#8132 Docs: Clarify Usage of kind-reload
  .github/workflows/README.md
  Makefile
Labels: keep pr updated

#8133 Stability: Fix Push Solo-Apis GHA
  .github/workflows/push-solo-apis-branch.yaml
Labels: keep pr updated

#8129 Remove CVE-2022-37315 from trivyignore
  .trivyignore
  changelog/v1.15.0-beta5/go-graphql-bump.yaml
Labels: keep pr updated

#8141 Stability: Ensure kind-reload-% always updates deployment
  Makefile
Labels: keep pr updated

#8148 Doc push 1.14 docs
  docs/active_versions.json
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_latest_minor.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#8150 Remove 1.10 docs
  docs/active_versions.json
Labels: keep pr updated

#8140 Pull in fix for resource-based cross-account lambda invocation
  Makefile
  changelog/v1.15.0-beta5/envoy-gloo-cross-account-bump.yaml
  test/e2e/aws_test.go
Labels: keep pr updated

#8149 build: release 14 ci updates
  .github/ISSUE_TEMPLATE/BUG-ISSUE.yml
  .github/ISSUE_TEMPLATE/DOCS-ISSUE.yml
  .github/ISSUE_TEMPLATE/FEATURE-ISSUE.yml
  .github/workflows/docs-gen.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  Makefile
  changelog/v1.15.0-beta5/release-14-ci-updates.yaml
  docs/Makefile
  docs/active_versions.json
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_latest_minor.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#8156 [1.14] bump envoy-gloo for april 26
  Makefile
  changelog/v1.14.1/bump-envoy-gloo-apr26.yaml
Labels: keep pr updated

#8157 [1.13] bump envoy-gloo for april 26
  Makefile
  changelog/v1.13.16/bump-envoy-gloo-apr26.yaml
Labels: keep pr updated

#8158 [1.12] bump envoy-gloo for april 26
  Makefile
  changelog/v1.12.53/bump-envoy-gloo-apr26.yaml
Labels: keep pr updated

#8155 bump envoy-gloo for april 26
  Makefile
  changelog/v1.15.0-beta5/bump-envoy-gloo-apr26.yaml
Labels: keep pr updated

#8095 Expose Envoy's OCSP Stapling Configuration
  changelog/v1.15.0-beta5/expose-envoy-ocsp-stapling-support.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/secret.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/ssl/ssl.proto.sk.md
  docs/content/reference/cli/glooctl_create_secret_tls.md
  docs/content/static/content/osa_provided.md
  go.mod
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/secret.proto
  projects/gloo/api/v1/ssl/ssl.proto
  projects/gloo/cli/pkg/cmd/create/secret/secret_interactive_test.go
  projects/gloo/cli/pkg/cmd/create/secret/secret_test.go
  projects/gloo/cli/pkg/cmd/create/secret/tls.go
  projects/gloo/cli/pkg/cmd/options/secret.go
  projects/gloo/pkg/api/converters/kube/secretconverter.go
  projects/gloo/pkg/api/converters/kube/secretconverter_test.go
  projects/gloo/pkg/api/v1/secret.pb.clone.go
  projects/gloo/pkg/api/v1/secret.pb.equal.go
  projects/gloo/pkg/api/v1/secret.pb.go
  projects/gloo/pkg/api/v1/secret.pb.hash.go
  projects/gloo/pkg/api/v1/ssl/ssl.pb.clone.go
  projects/gloo/pkg/api/v1/ssl/ssl.pb.equal.go
  projects/gloo/pkg/api/v1/ssl/ssl.pb.go
  projects/gloo/pkg/api/v1/ssl/ssl.pb.hash.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
  projects/sds/pkg/run/certs/ocsp_response.der
  projects/sds/pkg/run/run_e2e_test.go
  projects/sds/pkg/server/certs/ocsp_response.der
  projects/sds/pkg/server/server.go
  projects/sds/pkg/server/server_test.go
  test/e2e/tls_ocsp_test.go
  test/helpers/certs.go
Labels: keep pr updated

#8159 [DNM] DCP matchable tcp gateways
  docs/content/reference/api/envoy.glooe.solo.io.project.sk.md
  docs/content/reference/api/gateway.solo.io.project.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/matchable_tcp_gateway.proto.sk.md
  docs/content/reference/api/gloo.solo.io.project.sk.md
  docs/content/reference/api/glooe.solo.io.project.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  projects/gateway/api/v1/gateway.proto
  projects/gateway/api/v1/matchable_tcp_gateway.proto
  projects/gateway/pkg/api/v1/gateway.pb.clone.go
  projects/gateway/pkg/api/v1/gateway.pb.equal.go
  projects/gateway/pkg/api/v1/gateway.pb.go
  projects/gateway/pkg/api/v1/gateway.pb.hash.go
  projects/gateway/pkg/api/v1/kube/apis/gateway.solo.io/v1/register.go
  projects/gateway/pkg/api/v1/kube/apis/gateway.solo.io/v1/types.go
  projects/gateway/pkg/api/v1/kube/apis/gateway.solo.io/v1/zz_generated.deepcopy.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/clientset.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/fake/fake_gateway.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/fake/fake_gateway.solo.io_client.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/fake/fake_matchablehttpgateway.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/fake/fake_matchabletcpgateway.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/fake/fake_routeoption.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/fake/fake_routetable.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/fake/fake_virtualhostoption.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/fake/fake_virtualservice.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/gateway.solo.io_client.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/generated_expansion.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/matchablehttpgateway.go
  projects/gateway/pkg/api/v1/kube/client/clientset/versioned/typed/gateway.solo.io/v1/matchabletcpgateway.go
  projects/gateway/pkg/api/v1/kube/client/informers/externalversions/gateway.solo.io/v1/interface.go
  projects/gateway/pkg/api/v1/kube/client/informers/externalversions/gateway.solo.io/v1/matchabletcpgateway.go
  projects/gateway/pkg/api/v1/kube/client/informers/externalversions/generic.go
  projects/gateway/pkg/api/v1/kube/client/listers/gateway.solo.io/v1/expansion_generated.go
  projects/gateway/pkg/api/v1/kube/client/listers/gateway.solo.io/v1/matchabletcpgateway.go
  projects/gateway/pkg/api/v1/matchable_tcp_gateway.pb.clone.go
  projects/gateway/pkg/api/v1/matchable_tcp_gateway.pb.equal.go
  projects/gateway/pkg/api/v1/matchable_tcp_gateway.pb.go
  projects/gateway/pkg/api/v1/matchable_tcp_gateway.pb.hash.go
  projects/gateway/pkg/api/v1/matchable_tcp_gateway.sk.go
  projects/gateway/pkg/api/v1/matchable_tcp_gateway_client.sk.go
  projects/gateway/pkg/api/v1/matchable_tcp_gateway_reconciler.sk.go
  projects/gateway/pkg/translator/gateway_selector.go
  projects/gateway/pkg/translator/gateway_selector_test.go
  projects/gateway/pkg/translator/hybrid_translator.go
  projects/gloo/api/v1/gloosnapshot/solo-kit.json
  projects/gloo/pkg/api/v1/gloosnapshot/api_snapshot.sk.go
  projects/gloo/pkg/api/v1/gloosnapshot/api_snapshot_emitter.sk.go
  projects/gloo/pkg/api/v1/gloosnapshot/api_snapshot_simple_emitter.sk.go
  projects/gloo/pkg/bootstrap/opts.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
Labels: keep pr updated

#8167 [1.14] bump bitnami kubectl
  changelog/v1.14.1/bump-bitnami-kubectl.yaml
  jobs/kubectl/Dockerfile
Labels: keep pr updated

#8144 DCP: upstreams: Support proxy protocol versions
  Makefile
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/api/envoy/extensions/transport_sockets/proxy_protocol/v3/upstream_proxy_protocol.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/upstream.pb.clone.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/static/plugin.go
  projects/gloo/pkg/plugins/static/plugin_test.go
Labels: keep pr updated

#8127 [1.11] CVE 2023 0464
  Makefile
  changelog/v1.11.58/cves.yaml
  docs/content/guides/security/tls/Dockerfile
  docs/examples/session-affinity/Dockerfile
  docs/examples/xslt-guide/Dockerfile
  example/proxycontroller/Dockerfile
  jobs/certgen/cmd/Dockerfile
  jobs/kubectl/Dockerfile
  projects/accesslogger/cmd/Dockerfile
  projects/discovery/cmd/Dockerfile
  projects/examples/services/sleeper/Dockerfile
  projects/gateway/cmd/Dockerfile
  projects/gateway/pkg/api/v1/kube/generated_kube_types_test.go
  projects/ingress/cmd/Dockerfile
  projects/sds/cmd/Dockerfile
Labels: keep pr updated

#8168 [DNM] Dcp filterchainmatches poc1
  projects/gloo/pkg/plugins/plugins.go
  projects/gloo/pkg/plugins/tcp/plugin_test.go
  projects/gloo/pkg/translator/filter_chain.go
  projects/gloo/pkg/translator/listener.go
Labels: work in progress, keep pr updated
