Repository kgateway-dev/kgateway, pull requests merged in 2023-01, with the labels that each got.

#7617 v1.12.x-route-validation
  changelog/v1.12.40/validate-routes.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#7619 v1.10.x-route-validation
  changelog/v1.10.42/validate-routes.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#7616 v1.13-route-validation
  changelog/v1.13.2/validate-routes.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#7618 v1.11.x-route-validation
  changelog/v1.11.47/validate-routes.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
  projects/gloo/pkg/translator/translator_test.go
Labels: keep pr updated

#7622 Fix for glooctl nightly tests
  changelog/v1.14.0-beta5/glooctl-nightly.yaml
  test/kube2e/glooctl/glooctl_test.go
Labels: keep pr updated

#7625 Update _index.md
  docs/content/guides/traffic_management/hello_world/_index.md
Labels: keep pr updated

#7624 Local Gateway-Proxy Docker Compose
  install/local-gateway-proxy/.gitignore
  install/local-gateway-proxy/README.md
  install/local-gateway-proxy/docker-compose.yaml
  install/local-gateway-proxy/prepare-bootstrap.sh
  install/local-gateway-proxy/source_data/bootstrap.yaml
  projects/envoyinit/README.md
  test/e2e/example_test.go
  test/e2e/test_context.go
Labels: keep pr updated

#7621 build: prevent trivy scans for 1.9.x
  .github/workflows/docs-gen.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  Makefile
  changelog/v1.14.0-beta5/bump-min-trivy-version.yaml
  docs/Makefile
Labels: keep pr updated

#7626 fix a typo
  docs/content/guides/traffic_management/destination_selection/path_matching/_index.md
Labels: keep pr updated

#7628 Doc Hugo theme hardcoded
  docs/Makefile
Labels: Type: Bug, Type: Docs, keep pr updated

#7629 Update kube2e readme to cover nightly builds
  changelog/v1.14.0-beta5/readme.yaml
  test/kube2e/README.md
Labels: keep pr updated

#7639 Doc fixes to bump version
  .github/ISSUE_TEMPLATE/DOCS-ISSUE.yml
  .github/ISSUE_TEMPLATE/FEATURE-ISSUE.yml
  changelog/v1.14.0-beta5/doc-version-bump.yaml
  docs/active_versions.json
  docs/cmd/generate_docs.go
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/guides/security/auth/multi_authz/_index.md
  docs/content/operations/upgrading/canary.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#7630 Enhancements to Test Utilities
  changelog/v1.14.0-beta5/gomega-extensions.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  install/test/helm_test.go
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/plugins/grpcjson/plugin_test.go
  test/benchmark/snapshot_benchmark_test.go
  test/e2e/access_log_test.go
  test/e2e/buffer_test.go
  test/e2e/cors_test.go
  test/e2e/csrf_test.go
  test/e2e/dynamic_forward_proxy_test.go
  test/e2e/example_test.go
  test/e2e/fault_injection_test.go
  test/e2e/grpcweb_test.go
  test/e2e/gzip_test.go
  test/e2e/http_tunneling_test.go
  test/e2e/hybrid_test.go
  test/e2e/proxy_protocol_test.go
  test/e2e/ratelimit_test.go
  test/e2e/staged_transformation_test.go
  test/gomega/assertions/logging.go
  test/gomega/assertions/stats.go
  test/gomega/matchers/equal.go
  test/gomega/matchers/http.go
  test/gomega/transforms/regex.go
  test/gomega/transforms/transforms.go
  test/helpers/resource_clientset.go
  test/helpers/snapshot_writer.go
  test/kube2e/gloo/gloo_resources_test.go
  test/kube2e/resource_clientset.go
  test/kube2e/util.go
  test/services/gateway.go
  test/v1helpers/test_upstream.go
Labels: keep pr updated

#7632 docs: repaired preserve_header_... docs
  changelog/v1.14.0-beta5/header-format-docs-repair.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/hcm/hcm.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/protocol/protocol.proto.sk.md
  projects/gloo/api/v1/options/hcm/hcm.proto
  projects/gloo/api/v1/options/protocol/protocol.proto
  projects/gloo/pkg/api/v1/options/hcm/hcm.pb.go
  projects/gloo/pkg/api/v1/options/protocol/protocol.pb.go
Labels: keep pr updated

#7652 [1.11] Add topologyspreadconstraints to Gateway-Proxy
  changelog/v1.11.48/add-gateway-proxy-topologyspreadconstraints.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
  install/test/values/val_gwp_topologyspreadconstraints.yaml
Labels: keep pr updated

#7657 build(nightly-tests): combine/simplify slack alerts
  .github/workflows/helpers/notify-from-json.go
  .github/workflows/nightly-tests.yaml
  changelog/v1.14.0-beta6/combine-nightly-logs.yaml
Labels: keep pr updated

#7654 Fix istio-proxy pod being placed inside `tolerations` in helm template
  changelog/v1.10.43/fix-gateway-proxy-config-and-tolerations.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#7662 grafana docs: fix bad CM reference to glooe-observability-config
  docs/content/guides/observability/grafana/dashboards/_index.md
Labels: Type: Docs, keep pr updated

#7633 Feature/expose suppress envoy headers v2
  changelog/v1.14.0-beta6/suppress-envoy-headers.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/router/router.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/router/router.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/options/router/router.pb.go
  projects/gloo/pkg/translator/listener_subsystem_test.go
  projects/gloo/pkg/translator/network_filters.go
  test/e2e/happypath_test.go
Labels: keep pr updated

#7664 adding-tls-extauth-grpc-passthrough
  changelog/v1.14.0-beta6/add-tls-support-extauth-grpc-passthrough.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#7516 Docs for Gloo Fed canary upgrade
  changelog/v1.14.0-beta6/doc-fed-canary.yaml
  docs/content/operations/upgrading/canary.md
Labels: Type: Docs, keep pr updated

#7638 Support storing protoDescriptorBin in a ConfigMap
  changelog/v1.14.0-beta7/protodesc-configmap.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/grpc_json/grpc_json.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/4-configmaps.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/options/grpc_json/grpc_json.proto
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.clone.go
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.equal.go
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.go
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.hash.go
  projects/gloo/pkg/plugins/grpcjson/plugin.go
  projects/gloo/pkg/plugins/grpcjson/plugin_test.go
  test/e2e/grpc_json_test.go
Labels: keep pr updated

#7665 upgrade k8sutils
  changelog/v1.14.0-beta7/update-k8sutils-version.yaml
  go.mod
  go.sum
Labels: keep pr updated

#7671 Support storing protoDescriptorBin in a ConfigMap [1.13]
  changelog/v1.13.3/protodesc-configmap.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/grpc_json/grpc_json.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/4-configmaps.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/options/grpc_json/grpc_json.proto
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.clone.go
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.equal.go
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.go
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.hash.go
  projects/gloo/pkg/plugins/grpcjson/plugin.go
  projects/gloo/pkg/plugins/grpcjson/plugin_test.go
  test/e2e/grpc_json_test.go
  test/helpers/snapshot_writer.go
  test/kube2e/resource_clientset.go
  test/services/gateway.go
Labels: keep pr updated

#7673 Support storing protoDescriptorBin in a ConfigMap [1.12]
  .github/workflows/regression-tests.yaml
  changelog/v1.12.41/protodesc-configmap.yaml
  ci/deploy-to-kind-cluster.sh
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/grpc_json/grpc_json.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/4-configmaps.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/options/grpc_json/grpc_json.proto
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.clone.go
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.equal.go
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.go
  projects/gloo/pkg/api/v1/options/grpc_json/grpc_json.pb.hash.go
  projects/gloo/pkg/plugins/grpcjson/plugin.go
  projects/gloo/pkg/plugins/grpcjson/plugin_test.go
  test/e2e/grpc_json_test.go
  test/helpers/snapshot_writer.go
  test/kube2e/resource_clientset.go
  test/services/gateway.go
Labels: keep pr updated

#7648 backport topologySpreadConstraints in v1.12.x
  changelog/v1.12.41/add-gateway-proxy-topologyspreadconstraints.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
  install/test/values/val_gwp_topologyspreadconstraints.yaml
Labels: keep pr updated

#7661 7112 make back off limit configurable
  changelog/v1.14.0-beta7/expose-kube-jobspec-fields.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
Labels: keep pr updated

#7667 build(regression-tests): refactor to support weekly LTS CRON
  .github/actions/regression-tests/action.yaml
  .github/workflows/helpers/notify-from-json.go
  .github/workflows/nightly-tests.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.14.0-beta7/add-weekly-cron.yaml
Labels: keep pr updated

#7680 12/regression refactor
  .github/actions/regression-tests/action.yaml
  .github/workflows/helpers/notify-from-json.go
  .github/workflows/regression-tests.yaml
  changelog/v1.12.42/regression-tests-refactor.yaml
Labels: keep pr updated

#7684 10/regression refactor
  .github/actions/regression-tests/action.yaml
  .github/workflows/helpers/notify-from-json.go
  .github/workflows/regression-tests.yaml
  changelog/v1.10.44/regression-tests-refactor.yaml
Labels: keep pr updated

#7688 Fix caching doc gateway yaml block to use generic single quotes
  docs/content/guides/traffic_management/listener_configuration/caching/setup.md
Labels: Type: Docs, keep pr updated

#7690 fix typos in the docs
  docs/content/introduction/architecture/_index.md
  docs/content/introduction/architecture/concepts.md
  docs/content/introduction/architecture/custom_resources.md
  docs/content/introduction/architecture/deployment_arch.md
Labels: keep pr updated

#7698 Temp/no aws
  .github/actions/regression-tests/action.yaml
  changelog/v1.14.0-beta7/gke-ci-env.yaml
  cloudbuild.yaml
  test/aws_credentials/ec2_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
Labels: keep pr updated

#7721 [v1.10.x] Disable AWS tests in CI
  .github/actions/regression-tests/action.yaml
  changelog/v1.10.44/gke-ci-env.yaml
  cloudbuild.yaml
  test/e2e/aws_credentials/ec2_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
Labels: keep pr updated

#7692 Rollout job configmap
  changelog/v1.14.0-beta7/rollout-job-fix
  install/helm/gloo/templates/5-resource-configmap.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/test/helm_test.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#7719 [v1.12.x] Disable AWS tests in CI
  .github/actions/regression-tests/action.yaml
  changelog/v1.12.42/gke-ci-env.yaml
  cloudbuild.yaml
  test/e2e/aws_credentials/ec2_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
Labels: keep pr updated

#7669 Add authentication to Vault via AWS IAM
  changelog/v1.14.0-beta7/vault-secrets-aws-iam-auth.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/static/content/osa_included.md
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/bootstrap/vault.go
  test/e2e/vault_test.go
  test/services/vault.go
Labels: keep pr updated

#7703 back port changes for issue 7112 to v1.12
  changelog/v1.12.42/expose-kube-jobspec-fields.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
Labels: keep pr updated

#7723 Rollout job configmap [1.12]
  changelog/v1.12.42/rollout-job-fix
  install/helm/gloo/templates/5-resource-configmap.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/test/helm_test.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#7722 Rollout job configmap [1.13]
  changelog/v1.13.4/rollout-job-fix
  install/helm/gloo/templates/5-resource-configmap.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/test/helm_test.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#7728 fix glooctl goroutine leak [1.13]
  changelog/v1.13.4/goroutine-leak.yaml
  projects/gloo/cli/pkg/cmd/check/root.go
  test/kube2e/util.go
Labels: keep pr updated

#7729 fix glooctl goroutine leak [1.12]
  changelog/v1.12.42/goroutine-leak.yaml
  projects/gloo/cli/pkg/cmd/check/root.go
  test/kube2e/util.go
Labels: keep pr updated

#7730 fix glooctl goroutine leak [1.11]
  changelog/v1.11.50/goroutine-leak.yaml
  projects/gloo/cli/pkg/cmd/check/root.go
  test/kube2e/util.go
Labels: keep pr updated

#7717 added the envoyLogLevel field, along with it's tests
  changelog/v1.14.0-beta7/change-loglevel-to-envoyloglevel.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#7738 Doc fixes for week of 1/23/2023
  changelog/v1.14.0-beta7/doc-fixes2.yaml
  docs/content/guides/graphql/getting_started.md
  docs/content/guides/traffic_management/listener_configuration/caching/setup.md
  docs/content/operations/updating_license/_index.md
  docs/content/static/content/version_gee_n+1.md
Labels: Type: Docs, keep pr updated

#7745 back1.13: Tests now support aws again in ci
  ci/aws_credentials.enc
  cloudbuild.yaml
  test/e2e/aws_credentials/aws_credentials_suite_test.go
  test/e2e/aws_credentials/ec2_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
Labels: keep pr updated

#7740 7659 disable envoy core dumps
  changelog/v1.14.0-beta7/disable-core-dumps.yaml
  docs/content/reference/values.txt
  docs/content/static/content/osa_provided.md
  go.mod
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  projects/envoyinit/cmd/docker-entrypoint.sh
Labels: keep pr updated

#7746 back1.12: Tests now support aws again in ci
  ci/aws_credentials.enc
  cloudbuild.yaml
  test/e2e/aws_credentials/aws_credentials_suite_test.go
  test/e2e/aws_credentials/ec2_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
Labels: keep pr updated

#7736 fix(replaceInvalidRoutes): exempt dfp from route replacement
  changelog/v1.14.0-beta7/dfs-replace-route-fix.yaml
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin.go
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer.go
  test/e2e/dynamic_forward_proxy_test.go
Labels: keep pr updated

#7748 adding route path to invalid route message
  changelog/v1.14.0-beta7/add-route-path-transparency.yaml
  projects/gloo/pkg/translator/route_config.go
Labels: keep pr updated

#7734 Bump solo-kit [1.12]
  changelog/v1.12.42/rollout-job-fix.yaml
  changelog/v1.12.42/solo-kit-fix-statuses.yaml
  go.mod
  go.sum
  projects/clusteringress/pkg/api/external/knative/cluster_ingress.sk.go
  projects/clusteringress/pkg/api/v1/translator_snapshot.sk.go
  projects/gateway/pkg/api/v1/gateway.sk.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.sk.go
  projects/gateway/pkg/api/v1/route_option.sk.go
  projects/gateway/pkg/api/v1/route_table.sk.go
  projects/gateway/pkg/api/v1/virtual_host_option.sk.go
  projects/gateway/pkg/api/v1/virtual_service.sk.go
  projects/gloo/pkg/api/external/solo/ratelimit/rate_limit_config.sk.go
  projects/gloo/pkg/api/v1/artifact.sk.go
  projects/gloo/pkg/api/v1/discovery_snapshot.sk.go
  projects/gloo/pkg/api/v1/eds_snapshot.sk.go
  projects/gloo/pkg/api/v1/endpoint.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/auth_config.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_snapshot.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graph_ql_api.sk.go
  projects/gloo/pkg/api/v1/gloosnapshot/api_snapshot.sk.go
  projects/gloo/pkg/api/v1/proxy.sk.go
  projects/gloo/pkg/api/v1/secret.sk.go
  projects/gloo/pkg/api/v1/settings.sk.go
  projects/gloo/pkg/api/v1/setup_snapshot.sk.go
  projects/gloo/pkg/api/v1/upstream.sk.go
  projects/gloo/pkg/api/v1/upstream_group.sk.go
  projects/ingress/pkg/api/v1/ingress.sk.go
  projects/ingress/pkg/api/v1/kube_service.sk.go
  projects/ingress/pkg/api/v1/status_snapshot.sk.go
  projects/ingress/pkg/api/v1/translator_snapshot.sk.go
  projects/knative/pkg/api/external/knative/ingress.sk.go
  projects/knative/pkg/api/v1/translator_snapshot.sk.go
Labels: keep pr updated

#7749 Bump solo-kit
  changelog/v1.14.0-beta7/rollout-job-fix.yaml
  changelog/v1.14.0-beta7/solo-kit-fix-statuses.yaml
  go.mod
  go.sum
Labels: keep pr updated

#7750 bump solo-kit [1.13]
  changelog/v1.13.4/rollout-job-fix.yaml
  changelog/v1.13.4/solo-kit-fix-statuses.yaml
  go.mod
  go.sum
Labels: keep pr updated

#7742 bump solo-kit [1.11]
  changelog/v1.11.50/rollout-job-fix.yaml
  changelog/v1.11.50/solo-kit-fix-statuses.yaml
  go.mod
  go.sum
  projects/clusteringress/pkg/api/external/knative/cluster_ingress.sk.go
  projects/clusteringress/pkg/api/v1/translator_snapshot.sk.go
  projects/gateway/pkg/api/v1/api_snapshot.sk.go
  projects/gateway/pkg/api/v1/gateway.sk.go
  projects/gateway/pkg/api/v1/matchable_http_gateway.sk.go
  projects/gateway/pkg/api/v1/route_option.sk.go
  projects/gateway/pkg/api/v1/route_table.sk.go
  projects/gateway/pkg/api/v1/virtual_host_option.sk.go
  projects/gateway/pkg/api/v1/virtual_service.sk.go
  projects/gloo/pkg/api/external/solo/ratelimit/rate_limit_config.sk.go
  projects/gloo/pkg/api/v1/artifact.sk.go
  projects/gloo/pkg/api/v1/discovery_snapshot.sk.go
  projects/gloo/pkg/api/v1/eds_snapshot.sk.go
  projects/gloo/pkg/api/v1/endpoint.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/auth_config.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/enterprise_snapshot.sk.go
  projects/gloo/pkg/api/v1/enterprise/options/graphql/v1beta1/graph_ql_api.sk.go
  projects/gloo/pkg/api/v1/gloosnapshot/api_snapshot.sk.go
  projects/gloo/pkg/api/v1/proxy.sk.go
  projects/gloo/pkg/api/v1/secret.sk.go
  projects/gloo/pkg/api/v1/settings.sk.go
  projects/gloo/pkg/api/v1/setup_snapshot.sk.go
  projects/gloo/pkg/api/v1/upstream.sk.go
  projects/gloo/pkg/api/v1/upstream_group.sk.go
  projects/ingress/pkg/api/v1/ingress.sk.go
  projects/ingress/pkg/api/v1/kube_service.sk.go
  projects/ingress/pkg/api/v1/status_snapshot.sk.go
  projects/ingress/pkg/api/v1/translator_snapshot.sk.go
  projects/knative/pkg/api/external/knative/ingress.sk.go
  projects/knative/pkg/api/v1/translator_snapshot.sk.go
Labels: keep pr updated

#7751 fix(replaceInvalidRoutes): exempt http-tunneling from route replacement
  changelog/v1.14.0-beta7/http-tunneling-repair.yaml
  projects/gloo/constants/clusters.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin.go
  projects/gloo/pkg/plugins/tunneling/plugin.go
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer.go
  test/e2e/dynamic_forward_proxy_test.go
  test/e2e/http_tunneling_test.go
Labels: keep pr updated

#7752 fix(replaceInvalidRoutes): exempt dfp and tunneling from route replac…
  changelog/v1.13.4/replace-route-fix.yaml
  projects/gloo/constants/clusters.go
  projects/gloo/pkg/plugins/dynamic_forward_proxy/plugin.go
  projects/gloo/pkg/plugins/tunneling/plugin.go
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer.go
Labels: keep pr updated

#7653 Add vault secrets guide
  changelog/v1.14.0-beta8/vault-secrets-doc.yaml
  docs/content/installation/advanced_configuration/vault_secrets.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
Labels: keep pr updated

#7760 Backport V1.12.x docs
  changelog/v1.12.43/doc-backports.yaml
  docs/Makefile
  docs/active_versions.json
  docs/content/guides/graphql/getting_started.md
  docs/content/guides/observability/tracing.md
  docs/content/guides/traffic_management/listener_configuration/caching/setup.md
  docs/content/img/caching-unvalidated.svg
  docs/content/img/caching-validated.svg
  docs/content/operations/advanced/zero-downtime-gateway-rollout/_index.md
  docs/content/operations/updating_license/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: Type: Docs, keep pr updated

#7761 Backport V1.13.x docs
  .github/ISSUE_TEMPLATE/DOCS-ISSUE.yml
  .github/ISSUE_TEMPLATE/FEATURE-ISSUE.yml
  changelog/v1.13.5/doc-backports.yaml
  docs/Makefile
  docs/active_versions.json
  docs/cmd/generate_docs.go
  docs/content/guides/dev/_index.md
  docs/content/guides/dev/example-proxy-controller.txt
  docs/content/guides/gloo_federation/demo.md
  docs/content/guides/graphql/getting_started.md
  docs/content/guides/observability/tracing/_index.md
  docs/content/guides/observability/tracing/envoy.md
  docs/content/guides/observability/tracing/otel-config.yaml
  docs/content/guides/observability/tracing/otel.md
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/guides/security/auth/multi_authz/_index.md
  docs/content/guides/security/rate_limiting/enterprise/_index.md
  docs/content/guides/security/tls/server_tls.md
  docs/content/guides/traffic_management/listener_configuration/_index.md
  docs/content/guides/traffic_management/listener_configuration/caching.md
  docs/content/guides/traffic_management/listener_configuration/caching/_index.md
  docs/content/guides/traffic_management/listener_configuration/caching/about.md
  docs/content/guides/traffic_management/listener_configuration/caching/setup.md
  docs/content/guides/traffic_management/listener_configuration/tcp_proxy.md
  docs/content/img/caching-unvalidated.svg
  docs/content/img/caching-validated.svg
  docs/content/installation/gloo_federation.md
  docs/content/installation/glooctl_setup.md
  docs/content/introduction/faq.md
  docs/content/operations/advanced/crd_comperssion/_index.txt
  docs/content/operations/advanced/xds_relay/_index.md
  docs/content/operations/advanced/zero-downtime-gateway-rollout/_index.md
  docs/content/operations/updating_license/_index.md
  docs/content/operations/upgrading/canary.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/operations/upgrading/v1.10.md
  docs/content/operations/upgrading/v1.11.md
  docs/content/operations/upgrading/v1.12.md
  docs/content/operations/upgrading/v1.13.md
  docs/content/operations/upgrading/v1.4.md
  docs/content/operations/upgrading/v1.5.md
  docs/content/operations/upgrading/v1.7.md
  docs/content/operations/upgrading/v1.8.md
  docs/content/operations/upgrading/v1.9.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_latest_minor.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: Type: Docs, keep pr updated

#7763 [v1.12.x] Bump dependencies to resolve security alerts
  changelog/v1.12.43/security-update.yaml
  go.mod
  go.sum
Labels: keep pr updated

#7766 7659 disable envoy core dumps (#7740)
  changelog/v1.12.43/disable-core-dumps.yaml
  docs/content/reference/values.txt
  docs/content/static/content/osa_provided.md
  go.mod
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  projects/envoyinit/cmd/docker-entrypoint.sh
Labels: keep pr updated

#7765 7659 disable envoy core dumps (#7740)
  changelog/v1.13.5/disable-core-dumps.yaml
  docs/content/reference/values.txt
  docs/content/static/content/osa_provided.md
  go.mod
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_suite_test.go
  install/test/helm_test.go
  projects/envoyinit/cmd/docker-entrypoint.sh
Labels: keep pr updated

#7768 build(regression): added randomize flags to ginkgo runners
  .github/workflows/nightly-tests.yaml
  Makefile
  changelog/v1.14.0-beta8/nightly-add-ginkgo-flags.yaml
Labels: keep pr updated
