Repository kgateway-dev/kgateway, pull requests merged in 2024-10, with the labels that each got.

#10132 test/kubernetes/e2e: relax validation constraints for gloogateway.context
  changelog/v1.18.0-beta24/production-helm-profiles-in-tests-part2.yaml
  pkg/utils/helmutils/unmarshal.go
  test/kubernetes/e2e/test.go
  test/kubernetes/testutils/gloogateway/context.go
  test/testutils/helm_values.go
Labels: keep pr updated

#10134 Docs workflow 1.17.x
  .github/workflows/push-docs.yaml
  changelog/v1.17.11/doc-workflow-fix.yaml
Labels: keep pr updated

#10135 1.17 - Discovery resource version err (#10118)
  changelog/v1.17.11/discovery-watchlabels-bugfix.yaml
  projects/gloo/pkg/discovery/discovery.go
  test/kube2e/gateway/gateway_test.go
  test/kubernetes/e2e/debugging.md
  test/kubernetes/e2e/features/discovery_watchlabels/discovery_watchlabels_suite.go
  test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-with-labels.yaml
  test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-with-modified-labels.yaml
  test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-with-no-matching-labels.yaml
  test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-without-labels.yaml
  test/kubernetes/e2e/features/discovery_watchlabels/types.go
  test/kubernetes/e2e/tests/discovery_watchlabels_test.go
  test/kubernetes/e2e/tests/discovery_watchlabels_tests.go
  test/kubernetes/e2e/tests/manifests/discovery-watchlabels-test-helm.yaml
Labels: keep pr updated

#10136 1.16 - Discovery resource version err (#10118)
  changelog/v1.16.21/discovery-watchlabels-bugfix.yaml
  projects/gloo/pkg/discovery/discovery.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#10137 1.15 - Discovery resource version err (#10118)
  changelog/v1.15.32/discovery-watchlabels-bugfix.yaml
  projects/gloo/pkg/discovery/discovery.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#10142 trivy ignore pgx cve
  .trivyignore
  changelog/v1.18.0-beta25/trivy-ignore-pgx.yaml
Labels: keep pr updated

#10120 1.17: Poc/scrubbedsecrets
  changelog/v1.17.12/strict-tls-validation.yaml
  projects/gateway2/translator/listener/gateway_listener_translator.go
  projects/gateway2/translator/sslutils/ssl_utils.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: keep pr updated

#10153 1.17 - Relax gloogateway.Context validation
  changelog/v1.17.13/production-helm-profiles-in-tests-part2.yaml
  pkg/utils/helmutils/unmarshal.go
  test/kubernetes/e2e/test.go
  test/kubernetes/testutils/gloogateway/context.go
  test/testutils/helm_values.go
Labels: keep pr updated

#10149 1.15 metadata header validation
  changelog/v1.15.33/validate-apikey-data.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#10147 1.17 metadata header validation
  changelog/v1.17.14/validate-apikey-data.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#10141 Remove redundant Discovery tests
  changelog/v1.18.0-beta25/remove-kube2e-discovery-tests.yaml
  test/kube2e/gateway/gateway_test.go
  test/kubernetes/e2e/features/watch_namespace_selector/suite.go
Labels: keep pr updated

#10162 [1.17] tests: Fix flaky TestWatchNamespaceSelector
  Makefile
  changelog/v1.17.15/fix-watch-ns.yaml
  test/kube2e/gloo/bootstrap_clients_test.go
  test/kubernetes/e2e/features/watch_namespace_selector/suite.go
  test/kubernetes/e2e/features/watch_namespace_selector/types.go
Labels: keep pr updated

#10161 Fix DirectResponse e2e tests
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta25/fix-directresponse-test.yaml
  projects/gateway2/proxy_syncer/proxy_syncer.go
  test/kubernetes/e2e/features/directresponse/suite.go
  test/kubernetes/e2e/features/directresponse/types.go
  test/kubernetes/e2e/features/route_delegation/suite.go
  test/kubernetes/testutils/assertions/objects.go
  test/kubernetes/testutils/assertions/status.go
Labels: keep pr updated

#10151 scrubbedsecrets (#10120)
  changelog/v1.18.0-beta25/strict-tls-validation.yaml
  projects/gateway2/translator/listener/gateway_listener_translator.go
  projects/gateway2/translator/sslutils/ssl_utils.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: keep pr updated

#10163 test/kube2e: remove tests that do not run
  changelog/v1.18.0-beta25/migrate-e2e-tests-part1.yaml
  test/kube2e/argocd/argocd_suite_test.go
  test/kube2e/argocd/argocd_test.go
  test/kube2e/argocd/deploy-helm-server.sh
  test/kube2e/argocd/helm-override.yaml
  test/kube2e/argocd/helm-repo.yaml
  test/kube2e/ingress/ingress_suite_test.go
  test/kube2e/ingress/ingress_test.go
  test/kube2e/ingress/resource_client_test.go
  test/kube2e/ingress/status_syncer_test.go
  test/kube2e/knative/artifacts/knative-hello-service-tls.yaml
  test/kube2e/knative/artifacts/knative-hello-service.yaml
  test/kube2e/knative/knative_manual_tls_test.go
  test/kube2e/knative/knative_suite_test.go
  test/kube2e/knative/knative_test.go
Labels: keep pr updated

#10165 test/kubernetes/e2e: migrate helm tests
  .github/workflows/pr-kubernetes-tests.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.18.0-beta25/migrate-e2e-tests-part2.yaml
  test/kube2e/helm/artifacts/access-logging.yaml
  test/kube2e/helm/artifacts/custom-readiness-probe.yaml
  test/kube2e/helm/artifacts/helm.yaml
  test/kube2e/helm/artifacts/horizontal-scaling.yaml
  test/kube2e/helm/artifacts/performance.yaml
  test/kube2e/helm/artifacts/safeguards.yaml
  test/kube2e/helm/artifacts/upgrade-override.yaml
  test/kube2e/helm/helm_suite_test.go
  test/kube2e/helm/helm_test.go
  test/kubernetes/e2e/features/helm_settings/suite.go
  test/kubernetes/e2e/tests/helm_test.go
  test/kubernetes/e2e/tests/helm_tests.go
Labels: keep pr updated

#10171 tests: Remove helm from nightly suite
  .github/workflows/nightly-tests.yaml
  changelog/v1.18.0-beta25/remove-helm-nightly.yaml
Labels: keep pr updated

#10172 tests: Fix wrong path in TestHelmSettings
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta25/fix-helm-test-path.yaml
  test/kubernetes/e2e/features/helm_settings/suite.go
Labels: keep pr updated

#10090 validation: enhance translation with full envoy validation
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta25/expand-envoy-validation-functionality.yaml
  pkg/utils/envoyutils/bootstrap/bootstrap.go
  pkg/utils/envoyutils/bootstrap/bootstrap_suite_test.go
  pkg/utils/envoyutils/bootstrap/bootstrap_test.go
  pkg/utils/envoyutils/validation/validation.go
  pkg/utils/envoyutils/validation/validation_suite_test.go
  projects/gloo/pkg/translator/translator.go
  test/kubernetes/e2e/features/validation/full_envoy_validation/suite.go
  test/kubernetes/e2e/tests/full_envoy_validation_test.go
  test/kubernetes/e2e/tests/full_envoy_validation_tests.go
  test/kubernetes/e2e/tests/manifests/full-envoy-validation-helm.yaml
Labels: keep pr updated

#10173 Adding Argo CD guides
  changelog/v1.18.0-beta25/doc-argocd.yaml
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/argo.md
Labels: work in progress, keep pr updated

#10177 Doc fixes
  changelog/v1.18.0-beta25/doc-fixes.yaml
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: work in progress, keep pr updated

#10178 Doc fixes 1.17
  changelog/v1.17.15/doc-fixes.yaml
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/argo.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#10182 Doc fixes 1.15
  changelog/v1.15.34/doc-fixes.yaml
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/argo.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#10184 Doc fixes 1.13
  changelog/v1.13.40/docs-backport1.yaml
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/argo.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
Labels: keep pr updated

#10107 [gateway2] Updates Gateway Controller Watch Predicate
  changelog/v1.18.0-beta26/issue_10099.yaml
  projects/gateway2/controller/controller.go
  test/kubernetes/e2e/features/deployer/istio_integration_suite.go
  test/kubernetes/e2e/features/deployer/minimal_default_gatewayparameters_suite.go
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml
  test/kubernetes/e2e/features/deployer/testdata/gatewayparameters-custom.yaml
  test/kubernetes/e2e/features/deployer/types.go
Labels: keep pr updated

#10183 Doc fixes 1.14
  changelog/v1.14.33/doc-fixes1.yaml
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/argo.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
Labels: keep pr updated

#10179 tests: Append k8s version to artifacts uploaded and upload conformance test report only if run failed
  .github/workflows/composite-actions/kube-gateway-api-conformance-tests/action.yaml
  .github/workflows/composite-actions/kubernetes-e2e-tests/action.yaml
  .github/workflows/composite-actions/performance-tests/action.yaml
  .github/workflows/composite-actions/regression-tests/action.yaml
  changelog/v1.18.0-beta26/fix-conformance-tests-action.yaml
Labels: keep pr updated

#10188 backout APIKey skip_metadata_validation API change
  changelog/v1.15.34/validate-apikey-data.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#10190 JWT docs for route-level policy
  changelog/v1.18.0-beta26/docs-jwt.yaml
  docs/content/guides/security/auth/jwt/_index.md
  docs/content/guides/security/auth/jwt/claim_routing.md
  docs/content/guides/security/auth/jwt/route-jwt-policy.md
  docs/content/operations/debugging_gloo/_index.md
  docs/content/operations/upgrading/faq.md
  docs/content/static/content/cleanup.md
Labels: Type: Docs, keep pr updated

#10197 tests: Add missing Kubernetes tests to PR runs
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta26/run-missing-tests.yaml
  test/kubernetes/e2e/README.md
Labels: keep pr updated

#10198 tests: Fix flaky tests and cleanup leftover resources in tests
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta26/cleanup-tests.yaml
  test/kubernetes/e2e/features/validation/full_envoy_validation/suite.go
  test/kubernetes/e2e/features/validation/transformation_validation_disabled/suite.go
  test/kubernetes/e2e/features/validation/validation_allow_warnings/suite.go
  test/kubernetes/e2e/features/validation/validation_always_accept/suite.go
  test/kubernetes/e2e/features/validation/validation_reject_invalid/suite.go
  test/kubernetes/e2e/features/validation/validation_strict_warnings/suite.go
Labels: keep pr updated

#10199 [AI] API for Prompt Guard webhook
  changelog/v1.18.0-beta27/ai-prompt-guard-webhook.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.uniquehash.go
Labels: work in progress, keep pr updated

#10189 Add gemini api
  changelog/v1.18.0-beta27/add-gemini-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.uniquehash.go
Labels: keep pr updated

#10200 Doc fixes for week of Oct 7, 2024
  .github/workflows/push-docs.yaml
  changelog/v1.18.0-beta27/doc-fixes.yaml
  docs/content/reference/changelog/enterprise/_index.md
  docs/content/reference/changelog/open_source/_index.md
  docs/content/reference/values.txt
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_geoss_n+1.md
  install/helm/gloo/generate/values.go
Labels: Type: Docs, keep pr updated

#10191 Update datadog tracer config proto and preserve remote_config default behavior for envoy v1.31 (#10145)
  Makefile
  changelog/v1.18.0-beta27/update-datadog-tracer-config.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/trace/v3/datadog.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_HttpListenerOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  pkg/utils/api_conversion/trace.go
  projects/gloo/api/external/envoy/config/trace/v3/datadog.proto
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.clone.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.hash.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/datadog.pb.uniquehash.go
  projects/gloo/pkg/plugins/tracing/plugin_test.go
  test/e2e/local_ratelimit_test.go
Labels: keep pr updated

#10204 ci: Run the 1.16 nightlies against kube 1.28
  .github/workflows/nightly-tests.yaml
  changelog/v1.18.0-beta27/fix-116-nightlies.yaml
Labels: keep pr updated

#10206 Attempt to change http-echo image
  changelog/v1.17.15/change-echo-server-image.yaml
  test/kubernetes/e2e/defaults/testdata/http_echo.yaml
Labels: keep pr updated

#10219 Update documents for envoy 1.31 changes
  changelog/v1.18.0-beta28/envoy-1.31-doc-changes.yaml
  docs/content/operations/upgrading/faq.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_latest_minor.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  docs/content/static/content/version_geoss_n-1_minor.md
  docs/content/static/content/version_geoss_n-2_minor.md
Labels: keep pr updated

#10231 Fixing issue with Tilt setup and a 'missing' file
  Tiltfile
  changelog/v1.18.0-beta29/tilt-fix.yaml
  tilt-settings.yaml
Labels: keep pr updated

#10227 OPA auth API docs update
  changelog/v1.18.0-beta29/docs-opaAuthServer.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: Area: API, Type: Docs, keep pr updated

#10233 Install script - don't pull amd64 bin on arm64
  changelog/v1.18.0-beta29/install-script-arm64.yaml
  projects/gloo/cli/install.sh
Labels: keep pr updated

#10229 add stopwatches for translator and envoy syncer
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/translator/translator.go
Labels: keep pr updated

#10236 Doc fixes
  changelog/v1.18.0-beta30/doc-fixes.yaml
  docs/content/guides/traffic_management/destination_types/grpc/grpc-transcoding.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/route_table.proto.sk.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  projects/gateway/api/v1/route_table.proto
  projects/gateway/pkg/api/v1/route_table.pb.go
Labels: keep pr updated

#10235 Clarify envoy validation api comment
  changelog/v1.18.0-beta30/clarify-envoy-validation-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
Labels: keep pr updated

#10242 [1.17] fix: Handle errors in ggv2 plugins when resource is not in a watched namespace
  changelog/v1.17.15/fix-unwatched-resource-npe.yaml
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin.go
  projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin_test.go
Labels: keep pr updated

#10237 [AI] prompt guard regex additions
  changelog/v1.18.0-beta30/ai-prompt-guard-regex-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.uniquehash.go
Labels: work in progress, keep pr updated

#10243 1.17: add stopwatches for translator and envoy syncer (#10229)
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/translator/translator.go
Labels: keep pr updated

#10226 Add option to control Envoy closing connections on host set change
  changelog/v1.18.0-beta30/lb-close-connections-on-set-change.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/load_balancer.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/load_balancer.proto
  projects/gloo/pkg/api/v1/load_balancer.pb.clone.go
  projects/gloo/pkg/api/v1/load_balancer.pb.equal.go
  projects/gloo/pkg/api/v1/load_balancer.pb.go
  projects/gloo/pkg/api/v1/load_balancer.pb.hash.go
  projects/gloo/pkg/api/v1/load_balancer.pb.uniquehash.go
  projects/gloo/pkg/plugins/loadbalancer/plugin.go
  projects/gloo/pkg/plugins/loadbalancer/plugin_test.go
  test/e2e/loadbalancer_plugin_test.go
Labels: keep pr updated

#10221 Extauth gme parity
  changelog/v1.18.0-beta30/extauth-gme-parity.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.uniquehash.go
Labels: keep pr updated

#10248 aws_sts_cluster static cluster config for kubernetes gateway api
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta31/aws-sts-cluster-config.yaml
  install/test/k8sgateway_test.go
  projects/gateway2/controller/controller.go
  projects/gateway2/controller/start.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/tests/k8s_gw_aws_test.go
  test/kubernetes/e2e/tests/k8s_gw_aws_tests.go
  test/kubernetes/e2e/tests/manifests/aws-lambda-helm.yaml
  test/kubernetes/testutils/gloogateway/context.go
Labels: keep pr updated

#10254 Make k8s gateway Service labels/annotations configurable via helm
  changelog/v1.18.0-beta31/k8s-gw-svc-extra-anno.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/test/k8sgateway_test.go
  projects/gateway2/deployer/deployer_test.go
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml
Labels: keep pr updated

#10257 k8s gw: Service and ServiceAccount labels/annotations [1.17]
  changelog/v1.17.16/k8s-gw-svc-extra-anno.yaml
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/test/k8sgateway_test.go
  projects/gateway2/api/v1alpha1/gateway_parameters_types.go
  projects/gateway2/api/v1alpha1/kube_types.go
  projects/gateway2/api/v1alpha1/zz_generated.deepcopy.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/merge_test.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gloo/pkg/api/v1/kube/wellknown/types.go
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml
  test/kubernetes/e2e/features/deployer/types.go
Labels: keep pr updated

#10259 glooctl: check only proxy ns [1.17]
  changelog/v1.17.16/glooctl-check-proxy-ns.yaml
  projects/gloo/cli/pkg/cmd/check/root.go
Labels: keep pr updated
