Repository kgateway-dev/kgateway, pull requests merged in 2024-09, with the labels that each got.

#9974 [1.16] Warn on missing TLS secret
  changelog/v1.16.20/missing-tls-secret.yaml
  devel/tools/changelog.sh
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/validation/gloo_validation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/compressed_proxy_spec.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/disabled_gateway.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/enable_rest_eds_and_gloo_mtls.yaml
  install/test/fixtures/settings/gateway_circuit_breakers.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/gateway_validation.yaml
  install/test/fixtures/settings/graphql_fds_disabled.yaml
  install/test/fixtures/settings/isolate_virtual_hosts_by_ssl_config.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/ratelimit_server.yaml
  install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/fixtures/settings/set_regex_max_program_size_default.yaml
  install/test/fixtures/settings/set_secretSettings_in_settings.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/fixtures/settings/uds_disabled.yaml
  install/test/fixtures/settings/watched_discovery_labels.yaml
  install/test/helm_test.go
  projects/gateway/pkg/reporting/add_proxy_validation_result.go
  projects/gloo/api/grpc/validation/gloo_validation.proto
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.clone.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.equal.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.hash.go
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/filter_chain.go
  projects/gloo/pkg/translator/listener_subsystem.go
  projects/gloo/pkg/translator/listener_subsystem_test.go
  projects/gloo/pkg/translator/network_filters_test.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/validation/proxy_validation.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9958 Front Channel Logout
  changelog/v1.18.0-beta20/fc_logout.yaml
  docs/content/guides/security/auth/extauth/oauth/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#9991 Eitanya/ai azure openai
  changelog/v1.18.0-beta21/ai-gateway-azure-token.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.hash.go
Labels: work in progress, keep pr updated

#9986 [1.15] Warn on missing TLS secret
  changelog/v1.15.31/missing-tls-secret.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/validation/gloo_validation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/compressed_proxy_spec.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/disabled_gateway.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/enable_rest_eds_and_gloo_mtls.yaml
  install/test/fixtures/settings/gateway_circuit_breakers.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/gateway_validation.yaml
  install/test/fixtures/settings/graphql_fds_disabled.yaml
  install/test/fixtures/settings/isolate_virtual_hosts_by_ssl_config.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/ratelimit_server.yaml
  install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/fixtures/settings/set_regex_max_program_size_default.yaml
  install/test/fixtures/settings/set_secretSettings_in_settings.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/fixtures/settings/uds_disabled.yaml
  install/test/fixtures/settings/watched_discovery_labels.yaml
  install/test/helm_test.go
  projects/gateway/pkg/reporting/add_proxy_validation_result.go
  projects/gloo/api/grpc/validation/gloo_validation.proto
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.clone.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.equal.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.hash.go
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/translator/clusters.go
  projects/gloo/pkg/translator/filter_chain.go
  projects/gloo/pkg/translator/listener_subsystem.go
  projects/gloo/pkg/translator/listener_subsystem_test.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/validation/proxy_validation.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#10006 V1.15.x docs
  changelog/v1.15.32/doc-fixes.yaml
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/operations/production_deployment/_index.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
Labels: keep pr updated

#9998 [docs] update access log filters guide for usage clarity
  changelog/v1.18.0-beta21/access-log-filter.yaml
  docs/content/guides/security/access_logging/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/als/als.proto.sk.md
  projects/gloo/api/v1/options/als/als.proto
  projects/gloo/pkg/api/v1/options/als/als.pb.go
Labels: keep pr updated

#10015 Bump go and cloud builder versions
  changelog/v1.18.0-beta21/go-cve-bump-1-22-7access-log-filter.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  cloudbuild-cache.yaml
  go.mod
Labels: work in progress, keep pr updated

#10016 Expose max_buffered_{rx/tx}_bytes in the Tap filter (#9656)
  changelog/v1.18.0-beta21/new-fields-for-tap-filter.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/tap/tap.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_HttpListenerOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  projects/gloo/api/v1/enterprise/options/tap/tap.proto
  projects/gloo/pkg/api/v1/options/tap/tap.pb.go
Labels: keep pr updated

#10010 Add route name to output envoy config
  Makefile
  changelog/v1.18.0-beta21/fix-gateway-translator-tests.yaml
  projects/gateway2/query/httproute.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/httproute/translate_httproute_test.go
  projects/gateway2/translator/testutils/outputs/delegation/basic.yaml
  projects/gateway2/translator/testutils/outputs/delegation/basic_invalid_hostname.yaml
  projects/gateway2/translator/testutils/outputs/delegation/basic_parentref_match.yaml
  projects/gateway2/translator/testutils/outputs/delegation/basic_parentref_mismatch.yaml
  projects/gateway2/translator/testutils/outputs/delegation/bug-6621.yaml
  projects/gateway2/translator/testutils/outputs/delegation/child_rule_matcher.yaml
  projects/gateway2/translator/testutils/outputs/delegation/cyclic1.yaml
  projects/gateway2/translator/testutils/outputs/delegation/cyclic2.yaml
  projects/gateway2/translator/testutils/outputs/delegation/invalid_child_valid_standalone.yaml
  projects/gateway2/translator/testutils/outputs/delegation/multiple_children.yaml
  projects/gateway2/translator/testutils/outputs/delegation/multiple_parents.yaml
  projects/gateway2/translator/testutils/outputs/delegation/nested_absolute_relative.yaml
  projects/gateway2/translator/testutils/outputs/delegation/recursive.yaml
  projects/gateway2/translator/testutils/outputs/delegation/relative_paths.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_filter_override_merge.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_inheritance.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_inheritance_child_override_ignore.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_inheritance_child_override_ok.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_multi_level_inheritance_override_ok.yaml
  projects/gateway2/translator/testutils/outputs/http-routing-invalid-backend.yaml
  projects/gateway2/translator/testutils/outputs/http-routing-missing-backend.yaml
  projects/gateway2/translator/testutils/outputs/http-routing-proxy.yaml
  projects/gateway2/translator/testutils/outputs/http-with-azure-destination-proxy.yaml
  projects/gateway2/translator/testutils/outputs/http-with-header-modifier-proxy.yaml
  projects/gateway2/translator/testutils/outputs/http-with-lambda-destination-proxy.yaml
  projects/gateway2/translator/testutils/outputs/https-routing-proxy.yaml
  projects/gateway2/translator/testutils/outputs/route-sort.yaml
  projects/gateway2/translator/testutils/outputs/route_options/merge.yaml
Labels: keep pr updated

#10017 Glooctl check retries
  changelog/v1.18.0-beta22/glooctl-check-retries.yaml
  projects/gloo/cli/pkg/common/proxy.go
Labels: keep pr updated

#10021 1.17 glooctl check retries
  changelog/v1.17.8/glooctl-check-retries.yaml
  projects/gloo/cli/pkg/common/proxy.go
Labels: keep pr updated

#10023 Ignore CVE-2024-34156
  .trivyignore
  changelog/v1.18.0-beta22/ignore-cve-2024-34156.yaml
Labels: work in progress, keep pr updated

#10034 Doc fixes 1.17
  changelog/v1.17.8/doc-backports1.yaml
  docs/content/guides/security/access_logging/_index.md
Labels: keep pr updated

#10035 Doc fixes 1.16
  changelog/v1.16.21/doc-backports.yaml
  docs/content/guides/security/access_logging/_index.md
Labels: keep pr updated

#10037 Doc fixes 1.14
  changelog/v1.14.32/docs-backport1.yaml
  docs/content/guides/security/access_logging/_index.md
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/static/content/version_geoss_n+1.md
Labels: keep pr updated

#10028 Eitanya/ai custom labels
  changelog/v1.18.0-beta22/ai-additional-labels.yaml
  install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml
  projects/gateway2/api/v1alpha1/gateway_parameters_types.go
  projects/gateway2/api/v1alpha1/zz_generated.deepcopy.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
Labels: work in progress, keep pr updated

#10033 test/kube2e/upgrade: overhaul to actually do validation and make persistproxyspec not break
  changelog/v1.18.0-beta22/persist-proxy-upgrade-fix.yaml
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/utils/translators.go
  projects/ingress/pkg/translator/translator_syncer.go
  test/kube2e/upgrade/testdata/helm.yaml
  test/kube2e/upgrade/testdata/petstorebase/petstore_deployment.yaml
  test/kube2e/upgrade/testdata/petstorebase/petstore_svc.yaml
  test/kube2e/upgrade/testdata/petstorebase/petstore_ups.yaml
  test/kube2e/upgrade/testdata/petstorevs/vs_postupgrade.yaml
  test/kube2e/upgrade/testdata/petstorevs/vs_preupgrade.yaml
  test/kube2e/upgrade/upgrade_data_validation_test.go
  test/kube2e/upgrade/upgrade_test.go
Labels: keep pr updated

#10045 1.17 cli timeout increase
  changelog/v1.17.8/glooctl-check-metrics-timeout.yaml
  pkg/cliutil/uri.go
Labels: keep pr updated

#10046 .github/workflows: rebalance pr-kubernetes-tests
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta22/rebalance-kube-tests.yaml
  test/kubernetes/e2e/load_balances/14-May-2024.md
  test/kubernetes/e2e/load_balancing_tests.md
Labels: keep pr updated

#10048 1.17: projects/utils/ssl: Add a check for ssl secrets that will be rejected by envoy but not go
  changelog/v1.17.8/strict-tls-validation.yaml
  projects/gateway2/translator/sslutils/ssl_utils.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: Area: Stability, keep pr updated, Area: Secret Management, release-blocker

#10053 mod: upgrade go
  changelog/v1.18.0-beta22/upgrade-go.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  cloudbuild-cache.yaml
  go.mod
Labels: keep pr updated

#10047 projects/utils/ssl: Add a check for ssl secrets that will be rejected by envoy but not go
  changelog/v1.18.0-beta22/tls-secret-validation.yaml
  projects/gateway2/translator/sslutils/ssl_utils.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
Labels: keep pr updated

#10050 admindcli helper and test framework improvement (#9656)
  changelog/v1.18.0-beta23/admincli-helper-and-test-framework-improvement.yaml
  pkg/utils/envoyutils/admincli/client.go
  test/e2e/test_context.go
Labels: keep pr updated

#10063 [AI] weaviate support API
  changelog/v1.18.0-beta23/ai-weaviate.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.hash.go
Labels: work in progress, keep pr updated

#10064 validation/api: Expand envoy validate mode API
  changelog/v1.18.0-beta23/expand-envoy-validation-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/disabled_gateway.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/enable_rest_eds_and_gloo_mtls.yaml
  install/test/fixtures/settings/gateway_circuit_breakers.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/gateway_validation.yaml
  install/test/fixtures/settings/graphql_fds_disabled.yaml
  install/test/fixtures/settings/isolate_virtual_hosts_by_ssl_config.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/ratelimit_server.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/fixtures/settings/set_regex_max_program_size_default.yaml
  install/test/fixtures/settings/set_secretSettings_in_settings.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/fixtures/settings/uds_disabled.yaml
  install/test/fixtures/settings/watched_discovery_labels.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
Labels: keep pr updated

#10065 Add CVE-2024-45258 to trivyignore
  .trivyignore
  changelog/v1.18.0-beta23/update-trivyignore-cve-2024-45258.yaml
Labels: keep pr updated

#10077 Restructure Envoy bootstrap validation packages
  changelog/v1.18.0-beta23/expand-envoy-validation-pkg-restructure.yaml
  pkg/utils/envoyutils/bootstrap/bootstrap.go
  pkg/utils/envoyutils/bootstrap/bootstrap_suite_test.go
  pkg/utils/envoyutils/bootstrap/bootstrap_test.go
  pkg/utils/envoyutils/bootstrap/resources.go
  pkg/utils/envoyutils/validation/validation.go
  pkg/utils/envoyutils/validation/validation_suite_test.go
  pkg/utils/envutils/env.go
  projects/envoyinit/pkg/runner/run.go
  projects/gloo/constants/envoy.go
  projects/gloo/pkg/bootstrap/bootstrap_suite_test.go
  projects/gloo/pkg/bootstrap/bootstrap_validation.go
Labels: keep pr updated

#10087 Trivyignore updates
  .trivyignore
  changelog/v1.18.0-beta23/update-trivy0ignore-cve-2024-27289.yaml
Labels: keep pr updated

#10071 Expose Route on `WeightedDestinationPlugin`
  changelog/v1.18.0-beta23/modify-weighted-destination-params.yaml
  projects/gloo/pkg/plugins/buffer/plugin.go
  projects/gloo/pkg/plugins/buffer/plugin_test.go
  projects/gloo/pkg/plugins/csrf/plugin.go
  projects/gloo/pkg/plugins/csrf/plugin_test.go
  projects/gloo/pkg/plugins/extauth/plugin.go
  projects/gloo/pkg/plugins/extauth/plugin_test.go
  projects/gloo/pkg/plugins/headers/plugin.go
  projects/gloo/pkg/plugins/headers/plugin_test.go
  projects/gloo/pkg/plugins/plugins.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/transformation/plugin_test.go
  projects/gloo/pkg/translator/route_config.go
Labels: work in progress, keep pr updated

#10096 tests: Allow running TestWatchNamespaceSelector in Enterprise
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.17.10/watch-ns-tests.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  test/kubernetes/e2e/features/watch_namespace_selector/suite.go
  test/kubernetes/e2e/features/watch_namespace_selector/testdata/match-expressions.yaml
  test/kubernetes/e2e/features/watch_namespace_selector/testdata/match-labels.yaml
  test/kubernetes/e2e/features/watch_namespace_selector/testdata/random-ns-labeled.yaml
  test/kubernetes/e2e/features/watch_namespace_selector/types.go
  test/kubernetes/e2e/tests/base/base_suite.go
  test/kubernetes/e2e/tests/manifests/watch-namespace-selector.yaml
Labels: keep pr updated

#10061 Set GOMEMLIMIT / GOMAXPROCS [1.18]
  changelog/v1.18.0-beta23/gomemlimit.yaml
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/test/helm_test.go
  install/test/k8sgateway_test.go
  install/test/kube_utils.go
  pkg/utils/kubeutils/names.go
  test/kubernetes/e2e/tests/manifests/edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/k8s-gateway-test-helm.yaml
Labels: keep pr updated

#10078 improved TCP keepalive documentation (#9610)
  changelog/v1.18.0-beta23/tcp-keepalive-documentation.yaml
  docs/content/guides/integrations/aws/socket-options/_index.md
  docs/content/guides/traffic_management/tcp_keepalive/_index.md
  docs/content/operations/production_deployment/_index.md
Labels: keep pr updated

#10105 Bump go-utils to fix security scans
  changelog/v1.18.0-beta23/fix-trivy-extra-issues.yaml
  docs/cmd/generate_docs.go
  go.mod
  go.sum
Labels: keep pr updated

#10100 [AI] API for defining pools of AI related endpoints
  changelog/v1.18.0-beta23/ai-prioritized-endpoints.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/retries/retries.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/api/v1/options/retries/retries.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.uniquehash.go
  projects/gloo/pkg/api/v1/options/retries/retries.pb.clone.go
  projects/gloo/pkg/api/v1/options/retries/retries.pb.equal.go
  projects/gloo/pkg/api/v1/options/retries/retries.pb.go
  projects/gloo/pkg/api/v1/options/retries/retries.pb.hash.go
  projects/gloo/pkg/api/v1/options/retries/retries.pb.uniquehash.go
  projects/gloo/pkg/plugins/basicroute/plugin.go
  projects/gloo/pkg/plugins/basicroute/plugin_test.go
Labels: keep pr updated

#10121 *: Bump the sigs.k8s.io/gateway-api dependency to v1.1.0
  .github/workflows/composite-actions/kube-gateway-api-conformance-tests/action.yaml
  .github/workflows/conformance-tests.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/regression-tests.yaml
  Makefile
  changelog/v1.18.0-beta24/support-gw-api-1.1-conformance.yaml
  ci/kind/setup-kind.sh
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#10124 Bump go-utils
  changelog/v1.18.0-beta24/doc-bump-goutils.yaml
  go.mod
  go.sum
Labels: work in progress, keep pr updated

#10117 Validate Headers from API Key Metadata: add configuration flag
  changelog/v1.18.0-beta24/validate-apikey-data.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.uniquehash.go
Labels: keep pr updated

#10118 Discovery resource version err
  changelog/v1.18.0-beta24/discovery-watchlabels-bugfix.yaml
  projects/gloo/pkg/discovery/discovery.go
  test/kube2e/gateway/gateway_test.go
  test/kubernetes/e2e/debugging.md
  test/kubernetes/e2e/features/discovery_watchlabels/discovery_watchlabels_suite.go
  test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-with-labels.yaml
  test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-with-modified-labels.yaml
  test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-with-no-matching-labels.yaml
  test/kubernetes/e2e/features/discovery_watchlabels/testdata/service-without-labels.yaml
  test/kubernetes/e2e/features/discovery_watchlabels/types.go
  test/kubernetes/e2e/tests/discovery_watchlabels_test.go
  test/kubernetes/e2e/tests/discovery_watchlabels_tests.go
  test/kubernetes/e2e/tests/manifests/discovery-watchlabels-test-helm.yaml
Labels: keep pr updated
