Repository kgateway-dev/kgateway, pull requests merged in 2024-08, with the labels that each got.

#9849 .github: Add work in progress by default to stop auto merge by default
  .github/workflows/add-pr-label.yaml
  changelog/v1.18.0-beta13/work-in-progress-labler.yaml
Labels: keep pr updated

#9827 oneWayTls API for UpstreamSslConfig
  changelog/v1.18.0-beta13/upstreamsslconfig-onewaytls.yaml
  devel/tools/changelog.sh
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/ssl/ssl.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_HttpListenerOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  pkg/utils/envutils/env.go
  projects/gloo/api/v1/ssl/ssl.proto
  projects/gloo/pkg/api/v1/ssl/ssl.pb.clone.go
  projects/gloo/pkg/api/v1/ssl/ssl.pb.equal.go
  projects/gloo/pkg/api/v1/ssl/ssl.pb.go
  projects/gloo/pkg/api/v1/ssl/ssl.pb.hash.go
  projects/gloo/pkg/plugins/kubernetes/serviceconverter/use_ssl_annotation_converter.go
  projects/gloo/pkg/utils/ssl.go
  projects/gloo/pkg/utils/ssl_test.go
  test/kubernetes/e2e/features/client_tls/suite.go
  test/kubernetes/e2e/features/client_tls/testdata/annotated-nginx-svc.yaml
  test/kubernetes/e2e/features/client_tls/testdata/annotated-oneway-nginx-svc.yaml
  test/kubernetes/e2e/features/client_tls/testdata/nginx-oneway-upstream.yaml
  test/kubernetes/e2e/features/client_tls/testdata/nginx-upstream.yaml
  test/kubernetes/e2e/features/client_tls/testdata/tls-secret.yaml
  test/kubernetes/e2e/features/client_tls/testdata/vs-targeting-kube.yaml
  test/kubernetes/e2e/features/client_tls/testdata/vs-targeting-upstream.yaml
  test/kubernetes/e2e/features/client_tls/types.go
  test/kubernetes/e2e/features/gloomtls/gloomtls_edge_suite.go
  test/kubernetes/e2e/tests/edge_gw_tests.go
Labels: keep pr updated

#9852 Doc fixes 1.17
  changelog/v1.17.2/doc-fixes.yaml
  docs/content/guides/security/auth/extauth/apikey_auth/_index.md
  docs/content/guides/traffic_management/destination_types/aws_lambda/_index.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
Labels: keep pr updated

#9851 Doc fixes 1.16
  changelog/v1.16.19/doc-fixes.yaml
  docs/content/guides/security/auth/extauth/apikey_auth/_index.md
  docs/content/guides/traffic_management/destination_types/aws_lambda/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#9854 Doc fixes 1.15
  changelog/v1.15.31/doc-fixes.yaml
  docs/content/guides/security/auth/extauth/apikey_auth/_index.md
  docs/content/guides/traffic_management/destination_types/aws_lambda/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#9850 Doc fixes
  changelog/v1.18.0-beta13/doc-fixes.yaml
  docs/content/guides/traffic_management/destination_types/aws_lambda/_index.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
Labels: keep pr updated

#9840 tests: Return error if listener fails to close after checking if port is free
  changelog/v1.18.0-beta13/handle-failed-closed-listener.yaml
  test/ginkgo/parallel/ports.go
Labels: keep pr updated

#9856 admin/history: fast-follow PR feedback
  changelog/v1.18.0-beta13/admin-server-p4.yaml
  pkg/schemes/scheme.go
  pkg/utils/glooadminutils/admincli/README.md
  projects/gloo/pkg/servers/iosnapshot/history.go
  projects/gloo/pkg/servers/iosnapshot/resources.go
Labels: keep pr updated

#9857 Fix client tls tests
  changelog/v1.18.0-beta14/fix-clienttls.yaml
  test/kubernetes/e2e/features/client_tls/suite.go
  test/kubernetes/e2e/features/client_tls/types.go
  test/kubernetes/e2e/features/validation/validation_allow_warnings/suite.go
Labels: keep pr updated

#9858 add missing messages to status reports
  changelog/v1.17.2/add-httproute-status-messages.yaml
  projects/gateway2/query/query.go
  projects/gateway2/query/utils.go
  projects/gateway2/reports/status.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/testutils/inputs/http-routing-invalid-backend/manifests.yaml
  projects/gateway2/translator/testutils/inputs/http-routing-missing-backend/manifests.yaml
  projects/gateway2/translator/testutils/outputs/http-routing-invalid-backend.yaml
  projects/gateway2/translator/testutils/outputs/http-routing-missing-backend.yaml
  projects/gateway2/translator/translator_case_test.go
Labels: keep pr updated

#9868 [1.17 backport] validation tests
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.17.2/move-validation-tests-new-framework.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/plugins/static/plugin_test.go
  test/gomega/matchers/have_status.go
  test/helpers/input_resources.go
  test/kube2e/argocd/helm-override.yaml
  test/kube2e/gateway/gateway_test.go
  test/kube2e/util.go
  test/kubernetes/e2e/defaults/defaults.go
  test/kubernetes/e2e/defaults/testdata/curl_pod.yaml
  test/kubernetes/e2e/features/headless_svc/gloo_gateway_suite.go
  test/kubernetes/e2e/features/headless_svc/k8s_gw_suite.go
  test/kubernetes/e2e/features/listener_options/lis_opt_suite.go
  test/kubernetes/e2e/features/listener_options/lis_opt_types.go
  test/kubernetes/e2e/features/listener_options/testdata/setup.yaml
  test/kubernetes/e2e/features/validation/README.md
  test/kubernetes/e2e/features/validation/testdata/example-upstream.yaml
  test/kubernetes/e2e/features/validation/testdata/example-vs.yaml
  test/kubernetes/e2e/features/validation/testdata/invalid-resources/gateway.yaml
  test/kubernetes/e2e/features/validation/testdata/invalid-resources/invalid-upstream-no-port.yaml
  test/kubernetes/e2e/features/validation/testdata/invalid-resources/rlc.yaml
  test/kubernetes/e2e/features/validation/testdata/invalid-resources/vs-method-matcher.yaml
  test/kubernetes/e2e/features/validation/testdata/invalid-resources/vs-no-upstream.yaml
  test/kubernetes/e2e/features/validation/testdata/invalid-resources/vs-typo.yaml
  test/kubernetes/e2e/features/validation/testdata/secret-deletion/secret.yaml
  test/kubernetes/e2e/features/validation/testdata/secret-deletion/unused-secret.yaml
  test/kubernetes/e2e/features/validation/testdata/secret-deletion/vs-with-secret.yaml
  test/kubernetes/e2e/features/validation/testdata/switch-vs/invalid-vs.yaml
  test/kubernetes/e2e/features/validation/testdata/switch-vs/switch-valid-invalid.yaml
  test/kubernetes/e2e/features/validation/testdata/switch-vs/valid-vs.yaml
  test/kubernetes/e2e/features/validation/testdata/transformation/vs-transform-extractors.yaml
  test/kubernetes/e2e/features/validation/testdata/transformation/vs-transform-header-text.yaml
  test/kubernetes/e2e/features/validation/testdata/transformation/vs-transform-single-replace.yaml
  test/kubernetes/e2e/features/validation/transformation_validation_disabled/suite.go
  test/kubernetes/e2e/features/validation/types.go
  test/kubernetes/e2e/features/validation/validation_allow_warnings/suite.go
  test/kubernetes/e2e/features/validation/validation_always_accept/suite.go
  test/kubernetes/e2e/features/validation/validation_reject_invalid/suite.go
  test/kubernetes/e2e/features/validation/validation_strict_warnings/suite.go
  test/kubernetes/e2e/tests/disabled_transformation_validation_test.go
  test/kubernetes/e2e/tests/disabled_transformation_validation_tests.go
  test/kubernetes/e2e/tests/edge_gw_test.go
  test/kubernetes/e2e/tests/edge_gw_tests.go
  test/kubernetes/e2e/tests/manifests/disable-transformation-validation-helm.yaml
  test/kubernetes/e2e/tests/manifests/k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/validation-always-accept-helm.yaml
  test/kubernetes/e2e/tests/manifests/validation-strict-helm.yaml
  test/kubernetes/e2e/tests/validation_always_accept_test.go
  test/kubernetes/e2e/tests/validation_always_accept_tests.go
  test/kubernetes/e2e/tests/validation_strict_test.go
  test/kubernetes/e2e/tests/validation_strict_tests.go
  test/kubernetes/testutils/assertions/status.go
  test/kubernetes/testutils/gloogateway/clients.go
  test/kubernetes/testutils/gloogateway/context.go
Labels: keep pr updated

#9732 Kube E2E test migration: upgrade/helm
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta14/upgrade-helm.yaml
  install/test/grpc_json_transcoder_test.go
  pkg/utils/kubeutils/kubectl/cli.go
  test/kube2e/upgrade/upgrade_suite_test.go
  test/kube2e/upgrade/upgrade_utils.go
  test/kube2e/upgrade/upgrade_utils_test.go
  test/kube2e/util.go
  test/kubernetes/e2e/features/helm/suite.go
  test/kubernetes/e2e/features/helm/testdata/manifests/config-map-change.yaml
  test/kubernetes/e2e/features/helm/testdata/manifests/production-recommendations.yaml
  test/kubernetes/e2e/features/helm/testdata/manifests/upgrade-override.yaml
  test/kubernetes/e2e/features/helm/types.go
  test/kubernetes/e2e/features/upgrade/suite.go
  test/kubernetes/e2e/features/upgrade/testdata/manifests/secondary-gateway-namespace-validation.yaml
  test/kubernetes/e2e/features/upgrade/testdata/manifests/server-grpc-max-size-bytes.yaml
  test/kubernetes/e2e/features/upgrade/testdata/manifests/strict-validation.yaml
  test/kubernetes/e2e/test.go
  test/kubernetes/e2e/tests/base/base_suite.go
  test/kubernetes/e2e/tests/helm_test.go
  test/kubernetes/e2e/tests/helm_tests.go
  test/kubernetes/e2e/tests/manifests/test-helm.yaml
  test/kubernetes/e2e/tests/manifests/upgrade-base-test-helm.yaml
  test/kubernetes/e2e/tests/upgrade_test.go
  test/kubernetes/e2e/tests/upgrade_tests.go
  test/kubernetes/testutils/actions/provider.go
  test/kubernetes/testutils/helper/install.go
  test/kubernetes/testutils/helper/util_test.go
  test/kubernetes/testutils/runtime/env.go
Labels: keep pr updated

#9876 Doc fixes for week of Aug 5, 2024
  changelog/v1.18.0-beta14/doc-fixes.yaml
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/guides/observability/tracing/envoy.md
  docs/content/guides/security/auth/extauth/apikey_auth/_index.md
  docs/content/guides/security/auth/extauth/basic_auth/_index.md
  docs/content/guides/security/auth/extauth/oauth/auth0/_index.md
  docs/content/guides/security/auth/extauth/oauth/okta/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/guides/security/rate_limiting/_index.md
  docs/content/guides/traffic_management/destination_types/grpc/grpc-transcoding.md
  docs/content/installation/gateway/development/docker-compose-consul/_index.md
  docs/content/introduction/architecture/custom_resources.md
  docs/content/introduction/architecture/deployment_arch.md
  docs/content/introduction/faq.md
  docs/content/introduction/traffic_filter.md
  docs/content/introduction/traffic_management/_index.md
  docs/content/operations/upgrading/faq.md
  docs/content/reference/support.md
  docs/content/static/content/version_geoss_n+1.md
Labels: Type: Docs, keep pr updated

#9839 Add helm values validation to test installation
  changelog/v1.18.0-beta14/validate-values-before-e2e-test-install.yaml
  install/test/5-gateway-validation-webhook-configuration_test.go
  install/test/grpc_json_transcoder_test.go
  install/test/helm_suite_test.go
  install/test/helm_test.go
  install/test/k8sgateway_test.go
  install/test/rbac_test.go
  install/test/svc_accnt_test.go
  test/kube2e/gateway/artifacts/helm.yaml
  test/kube2e/gloo/artifacts/helm.yaml
  test/kube2e/helm/artifacts/helm.yaml
  test/kube2e/upgrade/artifacts/helm.yaml
  test/kubernetes/e2e/features/glooctl/check_suite.go
  test/kubernetes/e2e/test.go
  test/kubernetes/e2e/tests/manifests/disable-transformation-validation-helm.yaml
  test/kubernetes/e2e/tests/manifests/edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/glooctl-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/glooctl-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/gloomtls-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-automtls-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-automtls-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-regression-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-revision-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-revision-k8s-gateway-helm.yaml
  test/kubernetes/e2e/tests/manifests/k8s-gateway-minimal-default-gatewayparameters-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/k8s-gateway-no-webhook-validation-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/test-helm.yaml
  test/kubernetes/e2e/tests/manifests/upgrade-base-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/validation-always-accept-helm.yaml
  test/kubernetes/e2e/tests/manifests/validation-strict-helm.yaml
  test/testutils/helm_values.go
Labels: keep pr updated

#9869 Fix image digests
  changelog/v1.18.0-beta14/fix-image-digests.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_suite_test.go
  install/test/helm_test.go
  test/makefile/make_suite_test.go
  test/makefile/make_test.go
  test/makefile/makefile.go
Labels: keep pr updated

#9870 Add edge happy path routing test
  changelog/v1.18.0-beta14/add-happy-path-routing-test.yaml
  test/kubernetes/e2e/features/basicrouting/edge_suite.go
  test/kubernetes/e2e/tests/edge_gw_tests.go
Labels: work in progress, keep pr updated

#9878 1.17.x Backport helm validation in e2e tests
  changelog/v1.17.2/validate-values-before-e2e-test-install.yaml
  install/test/5-gateway-validation-webhook-configuration_test.go
  install/test/helm_suite_test.go
  install/test/helm_test.go
  install/test/k8sgateway_test.go
  install/test/rbac_test.go
  install/test/svc_accnt_test.go
  test/kube2e/gateway/artifacts/helm.yaml
  test/kube2e/gloo/artifacts/helm.yaml
  test/kube2e/helm/artifacts/helm.yaml
  test/kube2e/upgrade/artifacts/helm.yaml
  test/kubernetes/e2e/features/glooctl/check_suite.go
  test/kubernetes/e2e/test.go
  test/kubernetes/e2e/tests/manifests/disable-transformation-validation-helm.yaml
  test/kubernetes/e2e/tests/manifests/edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/glooctl-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/glooctl-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/gloomtls-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-automtls-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-automtls-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-regression-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-revision-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-revision-k8s-gateway-helm.yaml
  test/kubernetes/e2e/tests/manifests/k8s-gateway-minimal-default-gatewayparameters-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/k8s-gateway-no-webhook-validation-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/validation-always-accept-helm.yaml
  test/kubernetes/e2e/tests/manifests/validation-strict-helm.yaml
  test/testutils/helm_values.go
Labels: keep pr updated

#9872 Ensure endpoints for upstreams are listed within watchNamespaces
  changelog/v1.18.0-beta14/fix-eds-error.yaml
  projects/gloo/pkg/plugins/kubernetes/eds.go
  projects/gloo/pkg/plugins/kubernetes/eds_test.go
  test/kube2e/helm/helm_test.go
  test/kubernetes/e2e/features/helm/testdata/manifests/production-recommendations.yaml
Labels: work in progress, keep pr updated

#9880 Fix image digests [1.17]
  changelog/v1.17.2/fix-image-digests.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_suite_test.go
  install/test/helm_test.go
  test/makefile/make_suite_test.go
  test/makefile/make_test.go
  test/makefile/makefile.go
Labels: keep pr updated

#9835 Global floatingUserId to support OpenShift
  changelog/v1.18.0-beta14/consistent-floating-user-id.yaml
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/10-ingress-deployment.yaml
  install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
  install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
  install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-check-job.yaml
  install/helm/gloo/templates/5-resource-rollout-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6-access-logger-deployment.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-cronjob.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  install/test/k8sgateway_test.go
  install/test/securitycontext/utils.go
  install/utils/kuberesource/kuberesource_suite_test.go
  install/utils/kuberesource/unstructured.go
  install/utils/kuberesource/unstructured_test.go
  jobs/kubectl/Dockerfile
  jobs/kubectl/Dockerfile.distroless
  projects/gateway2/api/v1alpha1/gateway_parameters_types.go
  projects/gateway2/api/v1alpha1/zz_generated.deepcopy.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
Labels: keep pr updated

#9871 Glooctl license check
  changelog/v1.18.0-beta14/glooctl-license-check.yaml
  docs/content/reference/cli/glooctl.md
  docs/content/reference/cli/glooctl_license.md
  docs/content/reference/cli/glooctl_license_validate.md
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  projects/gloo/cli/pkg/cmd/license/license_suite_test.go
  projects/gloo/cli/pkg/cmd/license/root.go
  projects/gloo/cli/pkg/cmd/license/validate.go
  projects/gloo/cli/pkg/cmd/license/validate_test.go
  projects/gloo/cli/pkg/cmd/options/options.go
  projects/gloo/cli/pkg/cmd/root.go
  projects/gloo/cli/pkg/flagutils/install.go
  projects/gloo/cli/pkg/flagutils/license.go
  test/kube2e/helper/install.go
  test/kubernetes/testutils/helper/install.go
Labels: keep pr updated

#9881 [1.17] Ensure endpoints for upstreams are listed within watchNamespaces
  changelog/v1.17.2/fix-eds-error.yaml
  projects/gloo/pkg/plugins/kubernetes/eds.go
  projects/gloo/pkg/plugins/kubernetes/eds_test.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#9882 1.17.x global floating userId
  changelog/v1.17.3/consistent-floating-user-id.yaml
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/10-ingress-deployment.yaml
  install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
  install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
  install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-check-job.yaml
  install/helm/gloo/templates/5-resource-rollout-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6-access-logger-deployment.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-cronjob.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  install/test/k8sgateway_test.go
  install/test/securitycontext/utils.go
  install/utils/kuberesource/kuberesource_suite_test.go
  install/utils/kuberesource/unstructured.go
  install/utils/kuberesource/unstructured_test.go
  jobs/kubectl/Dockerfile
  jobs/kubectl/Dockerfile.distroless
  projects/gateway2/api/v1alpha1/gateway_parameters_types.go
  projects/gateway2/api/v1alpha1/zz_generated.deepcopy.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
Labels: keep pr updated

#9884 [v1.17.x] - Backport doc updates
  changelog/v1.17.3/docs-backport.yaml
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/guides/observability/tracing/envoy.md
  docs/content/guides/security/auth/extauth/apikey_auth/_index.md
  docs/content/guides/security/auth/extauth/basic_auth/_index.md
  docs/content/guides/security/auth/extauth/oauth/auth0/_index.md
  docs/content/guides/security/auth/extauth/oauth/okta/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/guides/security/rate_limiting/_index.md
  docs/content/guides/traffic_management/destination_types/grpc/grpc-transcoding.md
  docs/content/installation/gateway/development/docker-compose-consul/_index.md
  docs/content/introduction/architecture/custom_resources.md
  docs/content/introduction/architecture/deployment_arch.md
  docs/content/introduction/faq.md
  docs/content/introduction/traffic_filter.md
  docs/content/introduction/traffic_management/_index.md
  docs/content/operations/upgrading/faq.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
Labels: Type: Docs, keep pr updated

#9885 [v1.16.x] - Backport doc updates
  changelog/v1.16.19/doc-backports.yaml
  docs/content/guides/observability/tracing/envoy.md
  docs/content/guides/security/auth/extauth/apikey_auth/_index.md
  docs/content/guides/security/auth/extauth/basic_auth/_index.md
  docs/content/guides/security/auth/extauth/oauth/auth0/_index.md
  docs/content/guides/security/auth/extauth/oauth/okta/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/guides/traffic_management/destination_types/grpc/grpc-transcoding.md
  docs/content/installation/gateway/development/docker-compose-consul/_index.md
  docs/content/introduction/architecture/custom_resources.md
  docs/content/introduction/faq.md
  docs/content/introduction/traffic_filter.md
  docs/content/introduction/traffic_management/_index.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#9886 [v1.15.x] - Backport doc updates
  changelog/v1.15.31/doc-backports.yaml
  docs/content/guides/observability/tracing/envoy.md
  docs/content/guides/security/auth/extauth/apikey_auth/_index.md
  docs/content/guides/security/auth/extauth/basic_auth/_index.md
  docs/content/guides/security/auth/extauth/oauth/auth0/_index.md
  docs/content/guides/security/auth/extauth/oauth/okta/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/guides/traffic_management/destination_types/grpc/grpc-transcoding.md
  docs/content/installation/gateway/development/docker-compose-consul/_index.md
  docs/content/introduction/faq.md
  docs/content/introduction/traffic_filter.md
  docs/content/introduction/traffic_management/_index.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#9887 [v1.14.x] - Backport doc updates
  changelog/v1.14.32/docs-backport.yaml
  docs/content/guides/observability/tracing/envoy.md
  docs/content/guides/security/auth/extauth/apikey_auth/_index.md
  docs/content/guides/security/auth/extauth/basic_auth/_index.md
  docs/content/guides/security/auth/extauth/oauth/auth0/_index.md
  docs/content/guides/security/auth/extauth/oauth/okta/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/_index.md
  docs/content/guides/security/auth/extauth/passthrough_auth/http/_index.md
  docs/content/guides/traffic_management/destination_types/grpc/grpc-transcoding.md
  docs/content/installation/gateway/development/docker-compose-consul/_index.md
  docs/content/introduction/faq.md
  docs/content/introduction/traffic_filter.md
  docs/content/introduction/traffic_management/_index.md
  docs/content/reference/support.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#9889 docs - image variants
  changelog/v1.18.0-beta15/docs-image-variants.yaml
  docs/content/reference/support.md
Labels: work in progress, keep pr updated

#9891 Improve sync status time and add metrics
  changelog/v1.18.0-beta15/fix-only-update-status-on-change.yaml
  pkg/utils/setuputils/setup_syncer.go
  pkg/utils/statsutils/metrics/metrics.go
  pkg/utils/statsutils/metrics/metrics_internal_test.go
  pkg/utils/statsutils/metrics/metrics_suite_test.go
  pkg/utils/statsutils/metrics/metrics_test.go
  pkg/utils/statsutils/statsutils.go
  pkg/utils/statsutils/stopwatch.go
  pkg/utils/statsutils/translation_metrics.go
  projects/accesslogger/pkg/runner/run.go
  projects/gateway/pkg/services/k8sadmission/cert_provider.go
  projects/gateway/pkg/services/k8sadmission/validating_admission_webhook.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_integration_test.go
  projects/gateway/pkg/syncer/translator_syncer_test.go
  projects/gateway/pkg/translator/opts.go
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
  projects/gateway2/proxy_syncer/proxy_syncer.go
  projects/gateway2/proxy_syncer/proxy_syncer_test.go
  projects/gateway2/reports/status.go
  projects/gateway2/translator/gateway_translator.go
  projects/gloo/pkg/bootstrap/clients/vault/auth.go
  projects/gloo/pkg/bootstrap/clients/vault/renewal.go
  projects/gloo/pkg/bootstrap/clients/vault/stats.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/utils/validator/options.go
  projects/gloo/pkg/plugins/utils/validator/validator.go
  projects/gloo/pkg/plugins/utils/validator/validator_test.go
  projects/gloo/pkg/syncer/sanitizer/route_replacing_sanitizer.go
  projects/gloo/pkg/syncer/sanitizer/upstream_removing_sanitizer.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  test/e2e/gateway_test.go
Labels: keep pr updated

#9888 Ensure namespace override consistency
  .github/workflows/nightly-tests.yaml
  .github/workflows/pr-unit-tests.yaml
  Makefile
  changelog/v1.18.0-beta15/test-summaries.yaml
  pkg/utils/env/env.go
  pkg/utils/envutils/env.go
  test/kubernetes/e2e/example/debug_logging_test.go
  test/kubernetes/e2e/tests/automtls_istio_edge_api_test.go
  test/kubernetes/e2e/tests/automtls_istio_test.go
  test/kubernetes/e2e/tests/disabled_transformation_validation_test.go
  test/kubernetes/e2e/tests/edge_gw_test.go
  test/kubernetes/e2e/tests/glooctl_edge_gw_test.go
  test/kubernetes/e2e/tests/glooctl_istio_inject_test.go
  test/kubernetes/e2e/tests/glooctl_k8s_gw_test.go
  test/kubernetes/e2e/tests/gloomtls_edge_api_test.go
  test/kubernetes/e2e/tests/helm_test.go
  test/kubernetes/e2e/tests/istio_edge_api_test.go
  test/kubernetes/e2e/tests/istio_regression_test.go
  test/kubernetes/e2e/tests/k8s_gw_istio_test.go
  test/kubernetes/e2e/tests/k8s_gw_minimal_default_gatewayparameters_test.go
  test/kubernetes/e2e/tests/k8s_gw_no_validation_test.go
  test/kubernetes/e2e/tests/k8s_gw_test.go
  test/kubernetes/e2e/tests/revision_istio_edge_gw_test.go
  test/kubernetes/e2e/tests/revision_istio_k8s_gw_test.go
  test/kubernetes/e2e/tests/validation_always_accept_test.go
  test/kubernetes/e2e/tests/validation_strict_test.go
Labels: keep pr updated

#9883 reorg and rename various components to be more readable
  changelog/v1.18.0-beta15/minor-reorg-and-rename.yaml
  devel/contributing/conventions.md
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_integration_test.go
  projects/gateway2/install.sh
  projects/gloo/pkg/discovery/discovery.go
  projects/gloo/pkg/discovery/run.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
Labels: keep pr updated

#9892 Deallocate TLS slots on worker threads - v1.16.x
  Makefile
  changelog/v1.16.19/deallocate-tls-on-worker-thread.yaml
Labels: keep pr updated

#9895 Deallocate TLS slots on worker threads - v1.17.x
  Makefile
  changelog/v1.17.4/update-envoy-gloo.yaml
Labels: keep pr updated

#9867 Append cors settings (ExposeHeaders)
  changelog/v1.18.0-beta15/merge-cors-exposeheaders.yaml
  docs/content/guides/security/cors/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/virtual_service.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/cors/cors.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  pkg/utils/sliceutils/sliceutils.go
  pkg/utils/sliceutils/sliceutils_suite_test.go
  pkg/utils/sliceutils/sliceutils_test.go
  projects/gateway/api/v1/virtual_service.proto
  projects/gateway/pkg/api/v1/virtual_service.pb.go
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/cors/cors.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/options/cors/cors.pb.clone.go
  projects/gloo/pkg/api/v1/options/cors/cors.pb.equal.go
  projects/gloo/pkg/api/v1/options/cors/cors.pb.go
  projects/gloo/pkg/api/v1/options/cors/cors.pb.hash.go
  projects/gloo/pkg/plugins/cors/plugin.go
  projects/gloo/pkg/plugins/cors/route_plugin_test.go
  projects/gloo/pkg/translator/route_config.go
  test/e2e/cors_test.go
Labels: keep pr updated

#9898 [1.16] fix: allows setting Istio CA_ADDR independently
  changelog/v1.16.19/istio-spiffe-cert-provider-address.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
Labels: keep pr updated

#9900 [1.17] Ensure namespace override consistency
  .github/workflows/nightly-tests.yaml
  .github/workflows/pr-unit-tests.yaml
  Makefile
  changelog/v1.17.4/test-summaries.yaml
  pkg/utils/env/env.go
  pkg/utils/envutils/env.go
  test/kubernetes/e2e/example/debug_logging_test.go
  test/kubernetes/e2e/tests/automtls_istio_edge_api_test.go
  test/kubernetes/e2e/tests/automtls_istio_test.go
  test/kubernetes/e2e/tests/disabled_transformation_validation_test.go
  test/kubernetes/e2e/tests/edge_gw_test.go
  test/kubernetes/e2e/tests/glooctl_edge_gw_test.go
  test/kubernetes/e2e/tests/glooctl_istio_inject_test.go
  test/kubernetes/e2e/tests/glooctl_k8s_gw_test.go
  test/kubernetes/e2e/tests/gloomtls_edge_api_test.go
  test/kubernetes/e2e/tests/istio_edge_api_test.go
  test/kubernetes/e2e/tests/istio_regression_test.go
  test/kubernetes/e2e/tests/k8s_gw_istio_test.go
  test/kubernetes/e2e/tests/k8s_gw_minimal_default_gatewayparameters_test.go
  test/kubernetes/e2e/tests/k8s_gw_no_validation_test.go
  test/kubernetes/e2e/tests/k8s_gw_test.go
  test/kubernetes/e2e/tests/revision_istio_edge_gw_test.go
  test/kubernetes/e2e/tests/revision_istio_k8s_gw_test.go
  test/kubernetes/e2e/tests/validation_always_accept_test.go
  test/kubernetes/e2e/tests/validation_strict_test.go
  test/kubernetes/testutils/helper/util_test.go
Labels: keep pr updated

#9896 gateway2: merge multiple targetRef based Route & VirtualHost options
  changelog/v1.17.4/options-merge.yaml
  projects/gateway/pkg/translator/merge.go
  projects/gateway/pkg/translator/merge_test.go
  projects/gateway/pkg/translator/virtual_service_translator.go
  projects/gateway2/translator/plugins/routeoptions/query/query.go
  projects/gateway2/translator/plugins/routeoptions/query/query_test.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin.go
  projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin_test.go
  projects/gloo/pkg/utils/merge.go
  test/kubernetes/e2e/features/route_options/suite.go
  test/kubernetes/e2e/features/route_options/testdata/merge.yaml
  test/kubernetes/e2e/features/route_options/types.go
  test/kubernetes/e2e/features/virtualhost_options/testdata/extra-vho-merge.yaml
  test/kubernetes/e2e/features/virtualhost_options/types.go
  test/kubernetes/e2e/features/virtualhost_options/vhost_opt_suite.go
Labels: keep pr updated

#9902 helm: support PriorityClassName on gateway-proxy
  changelog/v1.18.0-beta16/helm-priority-class-name.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#9906 remove duplicated config entry
  changelog/v1.18.0-beta16/fix-docker-bootstrap-config.yaml
  install/docker-compose-file/source_data/envoy-config.yaml
Labels: work in progress, keep pr updated

#9907 [1.17] helm: support PriorityClassName on gateway-proxy
  changelog/v1.17.4/helm-priority-class-name.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/test/helm_test.go
Labels: keep pr updated

#9913 add missing messages to status reports
  changelog/v1.18.0-beta16/add-httproute-status-messages.yaml
  projects/gateway2/query/query.go
  projects/gateway2/query/utils.go
  projects/gateway2/reports/status.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/testutils/inputs/http-routing-invalid-backend/manifests.yaml
  projects/gateway2/translator/testutils/inputs/http-routing-missing-backend/manifests.yaml
  projects/gateway2/translator/testutils/outputs/http-routing-invalid-backend.yaml
  projects/gateway2/translator/testutils/outputs/http-routing-missing-backend.yaml
  projects/gateway2/translator/translator_case_test.go
Labels: keep pr updated

#9914 [v1.17.x] reorg and rename various components to be more readable
  changelog/v1.17.5/minor-reorg-and-rename.yaml
  devel/contributing/conventions.md
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer_integration_test.go
  projects/gateway2/install.sh
  projects/gloo/pkg/discovery/discovery.go
  projects/gloo/pkg/discovery/run.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
Labels: keep pr updated

#9918 .github: Update PR template to use comment formatting for instructions
  .github/pull_request_template.md
  changelog/v1.18.0-beta16/update-pull-request-template.yaml
Labels: keep pr updated

#9917 Add ginkgo to make install-go-tools command
  Makefile
  changelog/v1.18.0-beta16/install-ginkgo-make-install-go-tools.yaml
Labels: work in progress, keep pr updated

#9927 go.*: Remove the stale github.com/Sirupsen/logrus replace directive
  changelog/v1.18.0-beta16/remove-stale-replace-pin.yaml
  go.mod
Labels: keep pr updated

#9929 Replace Gloo Edge references in CONTRIBUTING.md
  CONTRIBUTING.md
  changelog/v1.18.0-beta17/update-contributing.yaml
Labels: keep pr updated

#9924 Fix 1.16.x ingress test
  changelog/v1.16.20/fix-status-syncer-test.yaml
  test/kube2e/ingress/status_syncer_test.go
Labels: keep pr updated

#9923 .github,Makefile: Add on-demand support for generating conformance reports
  .github/workflows/composite-actions/kube-gateway-api-conformance-tests/action.yaml
  .github/workflows/composite-actions/regression-tests/action.yaml
  .github/workflows/conformance-tests.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/regression-tests.yaml
  Makefile
  changelog/v1.18.0-beta17/publish-extended-conformance-results-release.yaml
  ci/kind/setup-kind.sh
Labels: keep pr updated

#9922 fix: fix NPE if an empty params is provided
  changelog/v1.18.0-beta17/fix-empty-gwp.yaml
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/helm/gloo-gateway/values.yaml
Labels: keep pr updated

#9940 Docs redirects and version bumps
  changelog/v1.18.0-beta17/docs-redirects.yaml
  docs/build-docs.sh
  docs/content/contributing/documentation/editing_locally.md
  docs/content/contributing/documentation/style_guide.md
  docs/content/guides/traffic_management/destination_types/grpc/migration.txt
  docs/content/introduction/development.md
  docs/content/operations/production_deployment/_index.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: work in progress, Type: Docs, keep pr updated

#9941 Doc redirect fixes
  changelog/v1.18.0-beta17/docs-redirect-fixes.yaml
  docs/build-docs.sh
  docs/content/reference/support.md
Labels: work in progress, keep pr updated

#9943 Redirect fixes
  changelog/v1.18.0-beta17/docs-redirects2.yaml
  docs/build-docs.sh
Labels: work in progress, keep pr updated

#9950 Update actions/cache to use v4/node20
  .github/workflows/composite-actions/prep-go-runner/action.yaml
  changelog/v1.18.0-beta17/update-actions-cache-to-v4.yaml
Labels: keep pr updated

#9931 [AI] Semantic Cache API Updates, (mode, score_threshold)
  changelog/v1.18.0-beta17/semantic-caching-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.hash.go
Labels: work in progress, keep pr updated

#9953 Docs redirects backport 1.17
  changelog/v1.17.6/doc-fixes.yaml
  docs/build-docs.sh
Labels: keep pr updated

#9957 Docs redirect 1.14
  changelog/v1.14.32/doc-fixes.yaml
  docs/build-docs.sh
Labels: keep pr updated

#9955 Docs redirect 1.16
  changelog/v1.16.20/doc-redirects.yaml
  docs/build-docs.sh
Labels: keep pr updated

#9956 Docs redirects 1.15
  changelog/v1.15.31/doc-redirects.yaml
  docs/build-docs.sh
Labels: keep pr updated

#9926 Minor flake fixes
  Makefile
  changelog/v1.18.0-beta18/minor-flake-fixes.yaml
  test/gomega/matchers/pod.go
  test/kube2e/helm/helm_test.go
  test/kubernetes/e2e/features/listener_options/lis_opt_suite.go
  test/kubernetes/e2e/features/validation/validation_reject_invalid/suite.go
  test/kubernetes/e2e/features/virtualhost_options/testdata/setup.yaml
  test/kubernetes/e2e/features/virtualhost_options/types.go
  test/kubernetes/e2e/features/virtualhost_options/vhost_opt_suite.go
  test/kubernetes/testutils/assertions/pods.go
Labels: keep pr updated

#9952 1.17.x edge basic routing suite
  .githooks/pre-commit
  changelog/v1.17.6/add-happy-path-routing-test.yaml
  test/kubernetes/e2e/features/basicrouting/edge_suite.go
  test/kubernetes/e2e/tests/edge_gw_tests.go
Labels: keep pr updated

#9903 Test summaries
  .github/workflows/composite-actions/kubernetes-e2e-tests/action.yaml
  Makefile
  changelog/v1.18.0-beta18/test-summaries-2.yaml
  ci/github-actions/go-test-summary/go_test_summary.go
  ci/github-actions/go-test-summary/tree.go
  ci/github-actions/go-test-summary/tree_test.go
Labels: keep pr updated

#9971 helm/gloo: introduce component label for grouping resources
  changelog/v1.18.0-beta18/group-certgen-helm.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-cronjob.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job-secret-create-role.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job-secret-create-rolebinding.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job-service-account.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job-vwc-update-clusterrole.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job-vwc-update-clusterrolebinding.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/test/helm_test.go
  install/test/rbac_test.go
Labels: work in progress, keep pr updated

#9972 Makefile: Fix the conformance-* targets
  Makefile
  changelog/v1.18.0-beta18/fix-conformance-make-target.yaml
Labels: keep pr updated

#9978 Doc fixes
  changelog/v1.18.0-beta19/doc-fixes.yaml
  docs/README.md
  docs/content/guides/traffic_management/request_processing/delegation/_index.md
  docs/content/operations/production_deployment/_index.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
Labels: Type: Docs, keep pr updated
