Repository kgateway-dev/kgateway, pull requests merged in 2024-05, with the labels that each got.

#9425 gateway2/delegation: update cyclic reference status message and tweak…
  changelog/v1.17.0-beta25/delegation-misc.yaml
  projects/gateway2/translator/httproute/delegation.go
  test/kubernetes/e2e/features/route_delegation/inputs/basic.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/cyclic.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/header_query_match.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/invalid_child.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/recursive.yaml
  test/kubernetes/e2e/features/route_delegation/suite.go
Labels: keep pr updated

#9398 Add port routing e2e tests
  changelog/v1.17.0-beta25/add-port-routing-e2e-test.yaml
  test/kubernetes/e2e/features/port_routing/suite.go
  test/kubernetes/e2e/features/port_routing/testdata/invalid-port-and-invalid-targetport.yaml
  test/kubernetes/e2e/features/port_routing/testdata/invalid-port-and-valid-targetport.yaml
  test/kubernetes/e2e/features/port_routing/testdata/invalid-port-without-targetport.yaml
  test/kubernetes/e2e/features/port_routing/testdata/match-pod-port-without-targetport.yaml
  test/kubernetes/e2e/features/port_routing/testdata/match-port-and-targetport.yaml
  test/kubernetes/e2e/features/port_routing/testdata/setup.yaml
  test/kubernetes/e2e/features/port_routing/types.go
  test/kubernetes/e2e/features/route_options/suite.go
  test/kubernetes/e2e/k8sgateway/k8s_gw_test.go
  test/kubernetes/testutils/assertions/objects.go
Labels: keep pr updated

#9429 gateway2/delegation: add test for multiple parents scenario
  changelog/v1.17.0-beta25/deleg-mulitple-parents.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/testutils/inputs/delegation/multiple_parents.yaml
  projects/gateway2/translator/testutils/outputs/delegation/multiple_parents.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/multiple_parents.yaml
  test/kubernetes/e2e/features/route_delegation/suite.go
  test/kubernetes/e2e/features/route_delegation/types.go
Labels: keep pr updated

#9391 Status Reporting for VirtualHostOptions in Kube GW
  changelog/v1.17.0-beta25/vhopts-statuses.yaml
  devel/architecture/external-options.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/validation/gloo_validation.proto.sk.md
  projects/gateway2/controller/start.go
  projects/gateway2/extensions/extensions.go
  projects/gateway2/translator/listenerutils/utils.go
  projects/gateway2/translator/plugins/registry/plugin_registry.go
  projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin.go
  projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin_test.go
  projects/gateway2/translator/translator_case_test.go
  projects/gateway2/translator/vhostutils/utils.go
  projects/gloo/api/grpc/validation/gloo_validation.proto
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.clone.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.equal.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.go
  projects/gloo/pkg/api/grpc/validation/gloo_validation.pb.hash.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/setup/start_func.go
  test/gomega/matchers/have_status.go
  test/kubernetes/e2e/features/virtualhost_options/inputs/extra-vho.yaml
  test/kubernetes/e2e/features/virtualhost_options/inputs/header-manipulation-targetref.yaml
  test/kubernetes/e2e/features/virtualhost_options/inputs/section-name-vho.yaml
  test/kubernetes/e2e/test.go
  test/kubernetes/testutils/assertions/status.go
  test/kubernetes/testutils/gloogateway/clients.go
Labels: keep pr updated

#9426 test: improve leak detection
  Makefile
  changelog/v1.17.0-beta25/reduce-recent-test-flakes.yaml
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  test/e2e/e2e_suite_test.go
  test/e2e/zipkin_test.go
  test/ginkgo/parallel/ports.go
  test/ginkgo/parallel/ports_test.go
  test/helpers/debug.go
  test/services/envoy/instance.go
  test/v1helpers/test_upstream.go
Labels: keep pr updated

#9431 gateway2/delegation: update translator test names and use WithHostHeader
  changelog/v1.17.0-beta25/deleg-test-updates.yaml
  projects/gateway2/translator/gateway_translator_test.go
  test/kubernetes/e2e/features/route_delegation/suite.go
Labels: keep pr updated

#9430 Remove old changelog tools
  changelog/v1.17.0-beta25/remove-hack-make-changelog-entry.yaml
  devel/tools/changelog.sh
  hack/increment_semver.sh
  hack/make-changelog-entry.sh
  hack/squash-changelogs.sh
Labels: keep pr updated

#9396 API for configuring GCP upstreams
  changelog/v1.17.0-beta25/6828-cloud-run-integration.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/gcp/gcp.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/enterprise/options/gcp/gcp.proto
  projects/gloo/api/v1/upstream.proto
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/pkg/api/v1/enterprise/options/gcp/gcp.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/gcp/gcp.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/gcp/gcp.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/gcp/gcp.pb.hash.go
  projects/gloo/pkg/api/v1/upstream.pb.clone.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/enterprise_warning/plugin.go
Labels: keep pr updated

#9432 gateway2/delegation: tweak status for invalid hostname and update tests
  changelog/v1.17.0-beta25/deleg-misc-1.yaml
  projects/gateway2/translator/httproute/delegation.go
  test/kubernetes/e2e/features/route_delegation/inputs/basic.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/common.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/cyclic.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/header_query_match.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/invalid_child.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/multiple_parents.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/recursive.yaml
Labels: keep pr updated

#9420 Adding tilt for enhanced development
  Makefile
  Tiltfile
  changelog/v1.17.0-beta25/add-tilt.yaml
  devel/tilt/tilt.md
  tilt-settings.yaml
Labels: keep pr updated

#9433 update readme and install script
  changelog/v1.17.0-beta25/script-cleanup.yaml
  projects/gateway2/README.md
  projects/gateway2/install.sh
Labels: keep pr updated

#9418 Add Istio strict/permissive auth e2e test
  Makefile
  changelog/v1.17.0-beta25/add-istio-peerauth-tests.yaml
  test/gomega/matchers/have_http_response.go
  test/kubernetes/e2e/classicedge/classic_api_test.go
  test/kubernetes/e2e/classicedge/manifests/classic-gateway-test-helm.yaml
  test/kubernetes/e2e/debugging.md
  test/kubernetes/e2e/features/headless_svc/classic_suite.go
  test/kubernetes/e2e/features/headless_svc/k8s_gw_suite.go
  test/kubernetes/e2e/features/headless_svc/resources.go
  test/kubernetes/e2e/features/headless_svc/suite.go
  test/kubernetes/e2e/features/istio/auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/inputs/k8srouting.yaml
  test/kubernetes/e2e/features/istio/inputs/permissive-peer-auth.yaml
  test/kubernetes/e2e/features/istio/inputs/setup.yaml
  test/kubernetes/e2e/features/istio/inputs/strict-peer-auth.yaml
  test/kubernetes/e2e/features/istio/no_mtls_suite.go
  test/kubernetes/e2e/features/istio/types.go
  test/kubernetes/e2e/k8sgateway/automtls_istio_test.go
  test/kubernetes/e2e/k8sgateway/istio_test.go
  test/kubernetes/e2e/k8sgateway/k8s_gw_test.go
  test/kubernetes/e2e/k8sgateway/manifests/istio-automtls-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/k8sgateway/manifests/istio-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/test.go
  test/kubernetes/e2e/utils/generate_resources.go
  test/kubernetes/testutils/assertions/glooctl.go
  test/testutils/env.go
Labels: keep pr updated

#9437 Secret Delete Flake Fix
  changelog/v1.17.0-beta26/secret-delete-flake-fix-attempt.yaml
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9439 V1.16.x secret delete flake fix
  changelog/v1.16.11/secret-delete-flake-fix-attempt.yaml
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9438 V1.15.x secret delete flake fix
  changelog/v1.15.26/secret-delete-flake-fix-attempt.yaml
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9445 gateway2/route-delegation: report child ref status and add more tests
  .gitignore
  Makefile
  changelog/v1.17.0-beta26/deleg-test-1.yaml
  projects/gateway2/translator/backendref/types.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/httproute/delegation.go
  projects/gateway2/translator/testutils/inputs/delegation/invalid_child_valid_standalone.yaml
  projects/gateway2/translator/testutils/outputs/delegation/invalid_child_valid_standalone.yaml
  test/kubernetes/e2e/debugging.md
  test/kubernetes/e2e/features/route_delegation/inputs/invalid_child_valid_standalone.yaml
  test/kubernetes/e2e/features/route_delegation/inputs/unresolved_child.yaml
  test/kubernetes/e2e/features/route_delegation/suite.go
  test/kubernetes/e2e/features/route_delegation/types.go
Labels: keep pr updated

#9447 gateway2/test: address follow-up changes from 1c322ee25
  changelog/v1.17.0-beta26/deleg-test-2.yaml
  projects/gateway2/translator/gateway_translator_test.go
  test/kubernetes/e2e/features/route_delegation/suite.go
Labels: keep pr updated

#9454 1.16.x - CVE fix bump bitnami/kubectl image
  changelog/v1.16.12/cve-kubectl-update.yaml
  jobs/kubectl/Dockerfile
Labels: work in progress, keep pr updated

#9459 CVE fix bump bitnami/kubectl image
  changelog/v1.17.0-beta26/cve-kubctl-update.yaml
  jobs/kubectl/Dockerfile
Labels: keep pr updated

#9453 1.15.x - CVE fix bump bitnami/kubectl image
  changelog/v1.15.27/cve-kubctl-update.yaml
  jobs/kubectl/Dockerfile
Labels: work in progress, keep pr updated

#9449 Fix headless svc manifest generation
  Makefile
  changelog/v1.17.0-beta26/fix-headless-svc.yaml
  devel/tools/README.md
  test/kubernetes/e2e/features/headless_svc/generate/generate.go
  test/kubernetes/e2e/features/headless_svc/generate/generated_example/gloo_gateway_api.gen.yaml
  test/kubernetes/e2e/features/headless_svc/generate/generated_example/k8s_api.gen.yaml
  test/kubernetes/e2e/features/headless_svc/gloo_gateway_suite.go
  test/kubernetes/e2e/features/headless_svc/k8s_gw_suite.go
  test/kubernetes/e2e/features/headless_svc/resources.go
  test/kubernetes/e2e/gloo_gateway_edge/gloo_gateway_api_test.go
  test/kubernetes/e2e/gloo_gateway_edge/manifests/gloo-gateway-test-helm.yaml
  test/kubernetes/e2e/k8sgateway/automtls_istio_test.go
  test/kubernetes/e2e/k8sgateway/istio_test.go
  test/kubernetes/e2e/k8sgateway/k8s_gw_test.go
Labels: keep pr updated

#9434 Add VirtualHostOptions e2e tests
  changelog/v1.17.0-beta26/vhopts-status-e2e-tests.yaml
  devel/tools/changelog.sh
  projects/gateway/pkg/syncer/translator_syncer_integration_test.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin_test.go
  projects/gateway2/translator/translator_case_test.go
  projects/gloo/pkg/defaults/reporter.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/setup/start_func.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/utils/validation/proxy_validation.go
  test/kubernetes/e2e/features/route_delegation/testdata/basic.yaml
  test/kubernetes/e2e/features/route_delegation/testdata/common.yaml
  test/kubernetes/e2e/features/route_delegation/testdata/cyclic.yaml
  test/kubernetes/e2e/features/route_delegation/testdata/header_query_match.yaml
  test/kubernetes/e2e/features/route_delegation/testdata/invalid_child.yaml
  test/kubernetes/e2e/features/route_delegation/testdata/invalid_child_valid_standalone.yaml
  test/kubernetes/e2e/features/route_delegation/testdata/multiple_parents.yaml
  test/kubernetes/e2e/features/route_delegation/testdata/recursive.yaml
  test/kubernetes/e2e/features/route_delegation/testdata/unresolved_child.yaml
  test/kubernetes/e2e/features/route_delegation/types.go
  test/kubernetes/e2e/features/route_options/suite.go
  test/kubernetes/e2e/features/route_options/testdata/fault-injection-filter-extension.yaml
  test/kubernetes/e2e/features/route_options/testdata/fault-injection-targetref.yaml
  test/kubernetes/e2e/features/route_options/types.go
  test/kubernetes/e2e/features/upstreams/suite.go
  test/kubernetes/e2e/features/virtualhost_options/suite.go
  test/kubernetes/e2e/features/virtualhost_options/testdata/bad-vho.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/basic-vho.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/extra-vho.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/section-name-vho.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/setup.yaml
  test/kubernetes/e2e/features/virtualhost_options/types.go
  test/kubernetes/e2e/k8sgateway/k8s_gw_test.go
  test/kubernetes/testutils/assertions/status.go
Labels: keep pr updated

#9461 test/kube/e2e: use run flag to separate tests across clusters
  .github/workflows/composite-actions/kubernetes-e2e-tests/action.yaml
  .github/workflows/composite-actions/setup-kind-cluster/action.yaml
  .github/workflows/pr-kubernetes-tests.yaml
  Makefile
  changelog/v1.17.0-beta26/kube-e2e-cluster-partition.yaml
  test/kubernetes/e2e/README.md
  test/kubernetes/e2e/example/README.md
  test/kubernetes/e2e/example/debug_logging_test.go
  test/kubernetes/e2e/example/manifests/error-example.yaml
  test/kubernetes/e2e/load_balancing_tests.md
  test/kubernetes/e2e/tests/debug_logging_test.go
  test/kubernetes/e2e/tests/manifests/debug-example.yaml
Labels: keep pr updated

#9452 V1.13.x CVE 2023 45288
  .trivyignore
  changelog/v1.13.37/cve-kubctl-update.yaml
  cloudbuild.yaml
Labels: keep pr updated

#9451 V1.14.x CVE 2023 45288
  .trivyignore
  changelog/v1.14.30/cve-kubctl-update.yaml
  ci/cloudbuild/publish-artifacts.yaml
  jobs/kubectl/Dockerfile
Labels: keep pr updated

#9455 Lambda non-string header tests
  Makefile
  changelog/v1.17.0-beta26/envoy-bump-and-test-multivalueheader-fix.yaml
  devel/testing/aws-tests.md
  test/e2e/aws_test.go
  test/gomega/matchers/contain_headers.go
Labels: work in progress, keep pr updated

#9450 test/kube/e2e: migrate glooctl tests
  Makefile
  changelog/v1.17.0-beta26/glooctl-action.yaml
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/root.go
  projects/gloo/cli/pkg/testutils/cli.go
  projects/gloo/cli/pkg/testutils/utils.go
  test/kubernetes/e2e/debugging.md
  test/kubernetes/e2e/features/glooctl/check.go
  test/kubernetes/e2e/features/glooctl/check_suite.go
  test/kubernetes/e2e/features/glooctl/debug_suite.go
  test/kubernetes/e2e/features/headless_svc/gloo_gateway_suite.go
  test/kubernetes/e2e/features/headless_svc/k8s_gw_suite.go
  test/kubernetes/e2e/gloo_gateway_edge/gloo_gateway_api_test.go
  test/kubernetes/e2e/k8sgateway/automtls_istio_test.go
  test/kubernetes/e2e/k8sgateway/istio_test.go
  test/kubernetes/e2e/k8sgateway/k8s_gw_test.go
  test/kubernetes/e2e/migrating_tests.md
  test/kubernetes/e2e/test.go
  test/kubernetes/testutils/actions/provider.go
  test/kubernetes/testutils/cluster/kind.go
  test/kubernetes/testutils/runtime/output.go
  test/testutils/project.go
Labels: keep pr updated

#9468 Lambda non-string header tests 1.15
  Makefile
  changelog/v1.15.28/envoy-bump-and-test-multivalueheader-fix.yaml
  devel/testing/aws-tests.md
  test/e2e/aws_test.go
  test/gomega/matchers/contain_headers.go
Labels: keep pr updated

#9467 Lambda non-string header tests 1.16
  Makefile
  changelog/v1.16.13/envoy-bump-and-test-multivalueheader-fix.yaml
  devel/testing/aws-tests.md
  test/e2e/aws_test.go
  test/gomega/matchers/contain_headers.go
Labels: keep pr updated

#9448 E2E Test framework updates
  changelog/v1.17.0-beta26/e2e-test-framework-updates.yaml
  test/kubernetes/e2e/test.go
  test/kubernetes/testutils/clients/clients.go
  test/kubernetes/testutils/cluster/kind.go
  test/kubernetes/testutils/gloogateway/clients.go
Labels: keep pr updated

#9458 Add istio bug report on failure
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.17.0-beta26/add-istio-bug-report-on-failure.yaml
  test/kubernetes/e2e/README.md
  test/kubernetes/e2e/features/headless_svc/testdata/setup.yaml
  test/kubernetes/e2e/features/istio/auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/inputs/setup.yaml
  test/kubernetes/e2e/features/istio/no_mtls_suite.go
  test/kubernetes/e2e/features/istio/types.go
  test/kubernetes/e2e/features/port_routing/testdata/setup.yaml
  test/kubernetes/e2e/features/route_options/testdata/fault-injection-filter-extension.yaml
  test/kubernetes/e2e/features/route_options/testdata/fault-injection-targetref.yaml
  test/kubernetes/e2e/features/upstreams/inputs/route-with-upstream.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/setup.yaml
  test/kubernetes/e2e/k8sgateway/automtls_istio_test.go
  test/kubernetes/e2e/k8sgateway/istio_test.go
  test/kubernetes/e2e/test.go
  test/kubernetes/testutils/cluster/istio.go
  test/kubernetes/testutils/runtime/env.go
Labels: keep pr updated

#9464 ggv2: gateway.networking.k8s.io/gateway-name
  changelog/v1.17.0-beta27/ggv2-gateway-name-label.yaml
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/helm/gloo-gateway/templates/_helpers.tpl
Labels: keep pr updated

#9469 test/kube/e2e: improved dependency injection
  changelog/v1.17.0-beta27/test-framework-for-portal.yaml
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/glooctl/check_suite.go
  test/kubernetes/e2e/features/route_delegation/suite.go
  test/kubernetes/e2e/gloo_gateway_edge/gloo_gateway_api_test.go
  test/kubernetes/e2e/k8sgateway/automtls_istio_test.go
  test/kubernetes/e2e/k8sgateway/istio_test.go
  test/kubernetes/e2e/k8sgateway/k8s_gw_test.go
  test/kubernetes/e2e/test.go
  test/kubernetes/e2e/tests/debug_logging_test.go
  test/kubernetes/testutils/clients/clients.go
  test/kubernetes/testutils/cluster/kind.go
Labels: keep pr updated

#9475 Doc fixes for week of 2024-05-06
  changelog/v1.17.0-beta27/doc-fixes.yaml
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/img/portal/petstore-food-bowl-collar.png
  docs/content/installation/_index.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/introduction/faq.md
  docs/content/operations/updating_license/_index.md
  docs/content/static/content/enterprise_only_feature_disclaimer
  docs/content/static/content/license-key
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  docs/content/support/about.md
  docs/content/support/support-ticket.md
Labels: Type: Docs, keep pr updated

#9473 gateway2/routes: prioritize regex over prefix and ignore regex lengths
  changelog/v1.17.0-beta27/route-sort.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/routeutils/sortable_route.go
  projects/gateway2/translator/routeutils/sortable_route_test.go
  projects/gateway2/translator/testutils/inputs/route-sort.yaml
  projects/gateway2/translator/testutils/outputs/delegation/multiple_children.yaml
  projects/gateway2/translator/testutils/outputs/delegation/multiple_parents.yaml
  projects/gateway2/translator/testutils/outputs/route-sort.yaml
Labels: keep pr updated

#9436 Add Istio strict/permissive auth e2e tests for Gloo Edge Gateway apis using new testing framework
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.17.0-beta27/add-edge-gateway-e2e-test.yaml
  projects/gloo/cli/pkg/cmd/istio/constants.go
  projects/gloo/cli/pkg/cmd/istio/inject.go
  projects/gloo/cli/pkg/cmd/istio/uninject.go
  projects/gloo/cli/pkg/testutils/cli.go
  test/gomega/matchers/pod.go
  test/kubernetes/e2e/features/glooctl/istio_inject_suite.go
  test/kubernetes/e2e/features/glooctl/istio_uninject_suite.go
  test/kubernetes/e2e/features/istio/generate/generate.go
  test/kubernetes/e2e/features/istio/generate/generated_example/automtls-enabled-edge-apis-routing.gen.yaml
  test/kubernetes/e2e/features/istio/generate/generated_example/edge-apis-routing.gen.yaml
  test/kubernetes/e2e/features/istio/gloo_gateway_auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/gloo_gateway_no_auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/k8s_gateway_auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/k8s_gateway_no_auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/resources.go
  test/kubernetes/e2e/gloo_gateway_edge/automtls_istio_edge_api_test.go
  test/kubernetes/e2e/gloo_gateway_edge/glooctl_istio_inject_test.go
  test/kubernetes/e2e/gloo_gateway_edge/istio_edge_api_test.go
  test/kubernetes/e2e/gloo_gateway_edge/manifests/automtls-istio-edge-api-gateway-test-helm.yaml
  test/kubernetes/e2e/gloo_gateway_edge/manifests/istio-edge-api-gateway-test-helm.yaml
  test/kubernetes/testutils/assertions/pods.go
Labels: keep pr updated

#9477 kube e2e test cleanup
  .github/workflows/composite-actions/kubernetes-e2e-tests/action.yaml
  changelog/v1.17.0-beta28/e2e-cleanup.yaml
  test/gomega/matchers/have_kubegateway_status.go
  test/kubernetes/e2e/debugging.md
  test/kubernetes/e2e/example/debug_logging_test.go
  test/kubernetes/e2e/example/manifests/debug-example.yaml
  test/kubernetes/e2e/features/headless_svc/generate/generate.go
  test/kubernetes/e2e/features/headless_svc/gloo_gateway_suite.go
  test/kubernetes/e2e/features/headless_svc/k8s_gw_suite.go
  test/kubernetes/e2e/features/headless_svc/resources.go
  test/kubernetes/e2e/features/istio/generate/generate.go
  test/kubernetes/e2e/features/istio/gloo_gateway_auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/gloo_gateway_no_auto_mtls_suite.go
  test/kubernetes/e2e/features/route_delegation/suite.go
  test/kubernetes/e2e/tests/automtls_istio_edge_api_test.go
  test/kubernetes/e2e/tests/automtls_istio_test.go
  test/kubernetes/e2e/tests/edge_gw_test.go
  test/kubernetes/e2e/tests/glooctl_istio_inject_test.go
  test/kubernetes/e2e/tests/istio_edge_api_test.go
  test/kubernetes/e2e/tests/istio_test.go
  test/kubernetes/e2e/tests/k8s_gw_test.go
  test/kubernetes/e2e/tests/manifests/edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-automtls-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-automtls-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/utils/status.go
  test/kubernetes/testutils/assertions/status.go
  test/kubernetes/testutils/resources/generate_resources.go
Labels: keep pr updated

#9470 RouteOptions e2e tests
  changelog/v1.17.0-beta28/rtopts-e2e-tests.yaml
  test/kubernetes/e2e/features/route_options/suite.go
  test/kubernetes/e2e/features/route_options/testdata/bad-rto-targetref.yaml
  test/kubernetes/e2e/features/route_options/testdata/bad-rto.yaml
  test/kubernetes/e2e/features/route_options/testdata/basic-rto-targetref.yaml
  test/kubernetes/e2e/features/route_options/testdata/basic-rto.yaml
  test/kubernetes/e2e/features/route_options/testdata/extra-rto-targetref.yaml
  test/kubernetes/e2e/features/route_options/testdata/extra-rto.yaml
  test/kubernetes/e2e/features/route_options/testdata/fault-injection-filter-extension.yaml
  test/kubernetes/e2e/features/route_options/testdata/httproute1-bad-extension.yaml
  test/kubernetes/e2e/features/route_options/testdata/httproute1-extension.yaml
  test/kubernetes/e2e/features/route_options/testdata/httproute1-multiple-extensions.yaml
  test/kubernetes/e2e/features/route_options/testdata/httproute1.yaml
  test/kubernetes/e2e/features/route_options/testdata/httproute2.yaml
  test/kubernetes/e2e/features/route_options/testdata/setup.yaml
  test/kubernetes/e2e/features/route_options/types.go
  test/kubernetes/e2e/features/virtualhost_options/types.go
Labels: keep pr updated

#9483 Rebalance Kubernetes e2e test clusters
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.17.0-beta28/rebalance-kubernetes-tests.yaml
  test/kubernetes/e2e/load_balances/14-May-2024.md
  test/kubernetes/e2e/load_balancing_tests.md
Labels: keep pr updated

#9486 gateway2/route-options: merge ExtensionRef override with targetRef attachment
  changelog/v1.17.0-beta28/deleg-extref.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/httproute/delegation.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/plugins/plugins.go
  projects/gateway2/translator/plugins/routeoptions/query/query.go
  projects/gateway2/translator/plugins/routeoptions/query/query_test.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/plugins/utils/plugin_utils.go
  projects/gateway2/translator/plugins/utils/plugin_utils_test.go
  projects/gateway2/translator/testutils/inputs/delegation/route_options_filter_override_merge.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_filter_override_merge.yaml
  test/gomega/matchers/have_status.go
Labels: keep pr updated

#9495 glooctl get proxy: remove --proxy-ns and --all flags
  changelog/v1.17.0-beta29/glooctl-remove-proxy-ns.yaml
  docs/content/reference/cli/glooctl_get_proxy.md
  projects/gloo/cli/pkg/cmd/options/options.go
  projects/gloo/cli/pkg/common/proxy.go
  projects/gloo/cli/pkg/flagutils/proxy.go
  projects/gloo/cli/pkg/printers/helpers.go
  projects/gloo/cli/pkg/printers/proxy.go
Labels: keep pr updated

#9496 Doc fixes
  changelog/v1.17.0-beta29/doc-fixes.yaml
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#9497 Doc fixes
  changelog/v1.17.0-beta29/doc-fixes1.yaml
  docs/content/guides/graphql/automatic_discovery.md
Labels: keep pr updated

#9498 gateway2: simplify how plugins handle delegated routes
  changelog/v1.17.0-beta29/deleg-plugin.yaml
  pkg/utils/env/env.go
  projects/gateway/pkg/translator/converter.go
  projects/gateway2/translator/httproute/delegation.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/plugins/plugins.go
  projects/gateway2/translator/plugins/routeoptions/query/query.go
  projects/gateway2/translator/plugins/routeoptions/query/query_test.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go
  projects/gateway2/translator/routeutils/utils.go
  projects/gateway2/translator/testutils/outputs/delegation/route_options_filter_override_merge.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_inheritance_child_override_ok.yaml
  projects/gateway2/translator/testutils/outputs/delegation/route_options_multi_level_inheritance_override_ok.yaml
  projects/gloo/pkg/utils/merge.go
  projects/gloo/pkg/utils/merge_test.go
  test/kubernetes/e2e/tests/k8s_gw_test.go
  test/testutils/env.go
Labels: keep pr updated

#9402 Add istio and sds values to GatewayParameters
  changelog/v1.17.0-beta29/add-sds-and-istio-gw-params.yaml
  install/helm/gloo/crds/gateway.gloo.solo.io_crds.yaml
  projects/gateway2/api/v1alpha1/gateway_parameters.proto
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/extensions/extensions.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/helm/gloo-gateway/values.yaml
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.hash.go
  test/kubernetes/e2e/features/deployer/istio_integration_deployer_suite.go
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/deployer/testdata/deployer-provision.yaml
  test/kubernetes/e2e/features/deployer/testdata/gateway-parameters.yaml
  test/kubernetes/e2e/features/deployer/testdata/istio-gateway-parameters.yaml
  test/kubernetes/e2e/features/deployer/types.go
  test/kubernetes/e2e/features/port_routing/suite.go
  test/kubernetes/e2e/tests/istio_test.go
Labels: keep pr updated

#9490 Pod security standards restricted defaults
  changelog/v1.17.0-beta29/pod-security-standards.yaml
  docs/content/reference/values.txt
  go.mod
  go.sum
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/10-ingress-deployment.yaml
  install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
  install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
  install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-check-job.yaml
  install/helm/gloo/templates/5-resource-rollout-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6-access-logger-deployment.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-cronjob.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
  test/kube2e/argocd/helm-override.yaml
  test/kube2e/gateway/artifacts/helm.yaml
  test/kube2e/gloo/artifacts/helm.yaml
  test/kube2e/glooctl/artifacts/helm.yaml
  test/kube2e/gloomtls/artifacts/helm.yaml
  test/kube2e/istio/artifacts/helm.yaml
  test/kube2e/upgrade/artifacts/helm.yaml
Labels: keep pr updated

#9501 V1.16.x pod security standards
  changelog/v1.16.14/pod-security-standards.yaml
  docs/content/reference/values.txt
  go.mod
  go.sum
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/10-ingress-deployment.yaml
  install/helm/gloo/templates/11-ingress-proxy-deployment.yaml
  install/helm/gloo/templates/14-clusteringress-proxy-deployment.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-cronjob.yaml
  install/helm/gloo/templates/19-gloo-mtls-certgen-job.yaml
  install/helm/gloo/templates/26-knative-external-proxy-deployment.yaml
  install/helm/gloo/templates/29-knative-internal-proxy-deployment.yaml
  install/helm/gloo/templates/3-discovery-deployment.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-migration-job.yaml
  install/helm/gloo/templates/5-resource-rollout-check-job.yaml
  install/helm/gloo/templates/5-resource-rollout-cleanup-job.yaml
  install/helm/gloo/templates/5-resource-rollout-job.yaml
  install/helm/gloo/templates/6-access-logger-deployment.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-cronjob.yaml
  install/helm/gloo/templates/6.5-gateway-certgen-job.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/templates/_helpers.tpl
  install/test/helm_test.go
  test/kube2e/argocd/helm-override.yaml
  test/kube2e/gateway/artifacts/helm.yaml
  test/kube2e/gloo/artifacts/helm.yaml
  test/kube2e/glooctl/artifacts/helm.yaml
  test/kube2e/gloomtls/artifacts/helm.yaml
  test/kube2e/istio/artifacts/helm.yaml
  test/kube2e/upgrade/artifacts/helm.yaml
Labels: keep pr updated

#9509 ginkgo/parallel: add tests for AdvancePortSafeListen
  changelog/v1.17.0-beta30/advance-port-safe.yaml
  test/ginkgo/parallel/ports.go
  test/ginkgo/parallel/ports_test.go
Labels: keep pr updated

#9489 Docs/proxy latency
  changelog/v1.17.0-beta30/proxy-latency.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/proxylatency/proxylatency.proto.sk.md
  projects/gloo/api/external/envoy/extensions/proxylatency/proxylatency.proto
  projects/gloo/pkg/api/external/envoy/extensions/proxylatency/proxylatency.pb.go
Labels: keep pr updated

#9507 TearDownSuite Resource Cleanup
  changelog/v1.17.0-beta30/route_delegation_test.yaml
  test/kubernetes/e2e/features/route_options/suite.go
  test/kubernetes/e2e/features/virtualhost_options/suite.go
Labels: keep pr updated

#9512 Fix missing listener data for HTTPS listeners during proxy translation
  changelog/v1.17.0-beta31/append-missing-https-listener-data.yaml
  projects/gateway2/translator/listener/gateway_listener_translator.go
Labels: keep pr updated

#9513 gateway2/delegation: enable optional parent matcher inheritance
  changelog/v1.17.0-beta32/deleg-relative.yaml
  projects/gateway2/query/delegation.go
  projects/gateway2/query/delegation_test.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/httproute/delegation.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/testutils/inputs/delegation/nested_absolute_relative.yaml
  projects/gateway2/translator/testutils/inputs/delegation/relative_paths.yaml
  projects/gateway2/translator/testutils/outputs/delegation/nested_absolute_relative.yaml
  projects/gateway2/translator/testutils/outputs/delegation/relative_paths.yaml
  test/kubernetes/e2e/features/route_delegation/suite.go
  test/kubernetes/e2e/features/route_delegation/testdata/matcher_inheritance.yaml
  test/kubernetes/e2e/features/route_delegation/types.go
Labels: keep pr updated

#9515 Fix HTTPRoute deletion
  Makefile
  changelog/v1.17.0-beta32/fix-httproute-deletion.yaml
  projects/gateway2/controller/controller.go
Labels: keep pr updated

#9519 Envoy 1.30.bump
  Makefile
  changelog/v1.17.0-beta32/envoy-1.30-bump.yaml
Labels: keep pr updated

#9493 Default GatewayParameters
  Makefile
  changelog/v1.17.0-beta32/default-gatewayparameters.yaml
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_crds.yaml
  install/helm/gloo/generate.go
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/helm/gloo/templates/44-gatewayclass.yaml
  install/helm/gloo/values-template.yaml
  install/test/k8sgateway_test.go
  projects/gateway2/api/v1alpha1/gateway_parameters.proto
  projects/gateway2/api/v1alpha1/kube/service.proto
  projects/gateway2/controller/controller.go
  projects/gateway2/controller/controller_suite_test.go
  projects/gateway2/controller/start.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/extensions/extensions.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/helm/gloo-gateway/values.yaml
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.hash.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/kube/service.pb.go
  projects/gateway2/translator/backendref/types_test.go
  projects/gateway2/translator/plugins/mirror/mirror_plugin_test.go
  projects/gateway2/translator/plugins/redirect/redirect_plugin_test.go
  projects/gateway2/translator/plugins/urlrewrite/url_rewrite_test.go
  projects/gateway2/wellknown/controller.go
  test/gomega/matchers/contain_map_elements.go
  test/gomega/matchers/contain_map_elements_test.go
  test/kube2e/istio/istio_integration_test.go
  test/kubernetes/e2e/features/deployer/testdata/istio-gateway-parameters.yaml
Labels: work in progress, keep pr updated

#9520 Make GatewayParameters fields nullable
  changelog/v1.17.0-beta32/gwp-nullable.yaml
  install/helm/gloo/crds/gateway.gloo.solo.io_crds.yaml
  projects/gateway2/api/v1alpha1/gateway_parameters.proto
  projects/gateway2/api/v1alpha1/kube/container.proto
  projects/gateway2/api/v1alpha1/kube/service.proto
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.hash.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/kube/container.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/kube/container.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/kube/container.pb.hash.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/kube/service.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/kube/service.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/kube/service.pb.hash.go
Labels: keep pr updated

#9500 Istio 1.21 Support
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.17.0-beta33/istio-1.21.yaml
  ci/kind/setup-kind.sh
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/reference/support.md
  docs/content/reference/values.txt
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/istio.sh
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7-1.19.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/matcher.go
  test/kube2e/istio/artifacts/automtls-helm.yaml
  test/kube2e/istio/artifacts/gloo-gateway-helm.yaml
  test/kube2e/istio/artifacts/helm.yaml
Labels: keep pr updated

#9528 Reconcile upstreams
  changelog/v1.17.0-beta33/fix-upstream-resync.yaml
  projects/gateway2/controller/controller.go
  test/kubernetes/e2e/features/upstreams/inputs/route-with-upstream.yaml
  test/kubernetes/e2e/features/upstreams/inputs/upstream-for-route.yaml
  test/kubernetes/e2e/features/upstreams/suite.go
  test/kubernetes/e2e/features/upstreams/types.go
Labels: keep pr updated

#9511 chore: Bump k8s to 1.29
  .github/workflows/istio-tests.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/pr-kubernetes-tests.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.17.0-beta33/bump-k8s-129.yaml
  docs/content/reference/support.md
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/install/knative_test_yaml.yaml
  test/mocks/kubernetes/kubeinterface.go
Labels: keep pr updated

#9499 [v1.16.x] Backport docs
  changelog/v1.16.15/docs-backport.yaml
  docs/Makefile
  docs/content/_index.md
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/guides/traffic_management/destination_types/kubernetes_services/_index.md
  docs/content/guides/traffic_management/destination_types/static_upstream/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/img/portal/petstore-food-bowl-collar.png
  docs/content/installation/_index.md
  docs/content/installation/advanced_configuration/vault_secrets.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/introduction/faq.md
  docs/content/operations/production_deployment/_index.md
  docs/content/operations/updating_license/_index.md
  docs/content/static/content/enterprise_only_feature_disclaimer
  docs/content/static/content/license-key
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  docs/content/support/about.md
  docs/content/support/support-ticket.md
Labels: Type: Docs, keep pr updated

#9526 .github/workflows: introduce nightly-kubernetes-tests, fix slack notifications
  .github/workflows/.env/nightly-tests/max_versions.env
  .github/workflows/.env/nightly-tests/min_versions.env
  .github/workflows/composite-actions/istio-tests/action.yaml
  .github/workflows/composite-actions/kubernetes-e2e-tests/action.yaml
  .github/workflows/composite-actions/performance-tests/action.yaml
  .github/workflows/composite-actions/regression-tests/action.yaml
  .github/workflows/helpers/notify-from-json.go
  .github/workflows/helpers/notify/slack.go
  .github/workflows/nightly-tests.yaml
  .github/workflows/pr-kubernetes-tests.yaml
  Makefile
  changelog/v1.17.0-beta33/nightly-kube-e2e-tests.yaml
  test/kubernetes/e2e/test.go
  test/kubernetes/testutils/cluster/context.go
  test/kubernetes/testutils/cluster/kind.go
  test/testutils/env.go
Labels: keep pr updated

#9533 CVEs - update .trivyignore with vulnerabilities unfixable in 1.13
  .github/workflows/trivy-analysis-scheduled.yaml
  .trivyignore
  Makefile
  changelog/v1.17.0-beta33/CVES-update-trivyignore.yaml
Labels: keep pr updated

#9537 1.16.x - Clear .trivyignore file
  .trivyignore
  changelog/v1.16.15/clear-trivyignore.yaml
Labels: keep pr updated

#9536 1.15.x - Clear .trivyignore file
  .trivyignore
  changelog/v1.15.29/clear-trivyignore.yaml
Labels: keep pr updated

#9534 1.13.x - Clear .trivyignore file
  .trivyignore
  changelog/v1.13.38/clear-trivyignore.yaml
Labels: keep pr updated

#9538 .github/workflows: further iterations to running e2e tests consistently
  .github/workflows/.env/pr-tests/versions.env
  .github/workflows/helpers/notify/slack.go
  .github/workflows/nightly-tests.yaml
  .github/workflows/pr-kubernetes-tests.yaml
  Makefile
  changelog/v1.17.0-beta34/ci-iterations.yaml
  ci/kind/setup-kind.sh
Labels: keep pr updated

#9531 Default GatewayParameters use only valid fields for image definitions
  changelog/v1.17.0-beta34/fix-image-default-gwp.yaml
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/helm/gloo/templates/_gg-helpers.tpl
  install/test/k8sgateway_test.go
Labels: keep pr updated

#9540 gateway2: enable self-managed Gateways
  changelog/v1.17.0-beta34/unmanaged-gw.yaml
  install/helm/gloo/crds/gateway.gloo.solo.io_crds.yaml
  projects/gateway2/api/v1alpha1/gateway_parameters.proto
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/merge_test.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.hash.go
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/deployer/testdata/self-managed-gateway.yaml
  test/kubernetes/e2e/features/deployer/types.go
  test/kubernetes/testutils/assertions/objects.go
Labels: keep pr updated

#9506 Glooctl get proxy fixes
  changelog/v1.17.0-beta34/glooctl-get-proxy-fixes.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/debug/proxy_endpoint.proto.sk.md
  docs/content/reference/cli/glooctl_get_proxy.md
  projects/gateway2/proxy_syncer/proxy_syncer.go
  projects/gloo/api/grpc/debug/proxy_endpoint.proto
  projects/gloo/cli/pkg/common/proxy.go
  projects/gloo/cli/pkg/flagutils/proxy.go
  projects/gloo/cli/pkg/testutils/cli.go
  projects/gloo/pkg/api/grpc/debug/proxy_endpoint.pb.go
  projects/gloo/pkg/debug/proxy_endpoint.go
  projects/gloo/pkg/debug/proxy_endpoint_test.go
  projects/gloo/pkg/debug/source.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/setup/start_func.go
  test/gomega/matchers/object.go
  test/kubernetes/e2e/features/glooctl/get_proxy_suite.go
  test/kubernetes/e2e/features/glooctl/testdata/backend.yaml
  test/kubernetes/e2e/features/glooctl/testdata/edge-gateway-gateways.yaml
  test/kubernetes/e2e/features/glooctl/testdata/edge-gateway-routes.yaml
  test/kubernetes/e2e/features/glooctl/testdata/kube-gateway-routes.yaml
  test/kubernetes/e2e/features/glooctl/types.go
  test/kubernetes/e2e/tests/k8s_gw_test.go
  test/kubernetes/testutils/clients/clients.go
Labels: keep pr updated

#9546 Fix helm test flake introduced in #9531
  changelog/v1.17.0-beta34/fix-gatewayparameters-helm-test.yaml
  install/test/k8sgateway_test.go
Labels: keep pr updated

#9542 .github/workflows: update actions to use node20
  .github/dependabot.yml
  .github/workflows/cache-eviction.yaml
  .github/workflows/cache-setup.yaml
  .github/workflows/composite-actions/istio-tests/action.yaml
  .github/workflows/composite-actions/kube-gateway-api-conformance-tests/action.yaml
  .github/workflows/composite-actions/performance-tests/action.yaml
  .github/workflows/composite-actions/prep-go-runner/action.yaml
  .github/workflows/composite-actions/regression-tests/action.yaml
  .github/workflows/composite-actions/setup-kind-cluster/action.yaml
  .github/workflows/docs-gen.yaml
  .github/workflows/istio-tests.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/pr-kubernetes-tests.yaml
  .github/workflows/pr.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/static-analysis.yaml
  .github/workflows/trivy-analysis-scheduled.yaml
  changelog/v1.17.0-beta34/gha-node20.yaml
Labels: keep pr updated

#9539 Istio 1.22 support
  .github/workflows/.env/nightly-tests/max_versions.env
  .github/workflows/.env/nightly-tests/min_versions.env
  .github/workflows/.env/pr-tests/versions.env
  .github/workflows/composite-actions/kubernetes-e2e-tests/action.yaml
  .github/workflows/composite-actions/setup-kind-cluster/action.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.17.0-beta34/istio-1.22.yaml
  ci/kind/setup-kind.sh
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/reference/support.md
  docs/content/reference/values.txt
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  install/test/k8sgateway_test.go
  projects/gateway2/istio.sh
  test/kube2e/istio/artifacts/automtls-helm.yaml
  test/kube2e/istio/artifacts/gloo-gateway-helm.yaml
  test/kube2e/istio/artifacts/helm.yaml
Labels: keep pr updated

#9552 .github/workflows: dependabot updates to actions
  .github/dependabot.yml
  .github/workflows/docs-gen.yaml
  .github/workflows/push-solo-apis-branch.yaml
  .github/workflows/stalebot.yaml
  .github/workflows/static-analysis.yaml
  changelog/v1.17.0-beta34/dependabot-updates.yaml
Labels: keep pr updated

#9555 Set persistProxySpec to false in kubernetes e2e tests
  changelog/v1.17.0-beta34/persistproxy-false.yaml
  test/kubernetes/e2e/tests/manifests/edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-automtls-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-automtls-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/k8s-gateway-no-webhook-validation-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/k8s-gateway-test-helm.yaml
Labels: keep pr updated

#9554 Fix Istio upstream upgrade test
  changelog/v1.17.0-beta34/fix-istio-integration-upgrade-test.yaml
  test/kubernetes/e2e/features/istio/generate/generate.go
  test/kubernetes/e2e/features/istio/generate/generated_example/automtls-disabled-edge-apis-routing.gen.yaml
  test/kubernetes/e2e/features/istio/generate/generated_example/automtls-enabled-edge-apis-routing.gen.yaml
  test/kubernetes/e2e/features/istio/generate/generated_example/sslconfig-and-automtls-disabled-edge-apis-routing.gen.yaml
  test/kubernetes/e2e/features/istio/generate/generated_example/sslconfig-edge-apis-routing.gen.yaml
  test/kubernetes/e2e/features/istio/gloo_gateway_auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/gloo_gateway_no_auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/resources.go
Labels: keep pr updated

#9560 glooctl test fixes
  changelog/v1.17.0-beta34/glooctl-test-fixes.yaml
  projects/gateway2/proxy_syncer/proxy_syncer.go
  projects/gateway2/translator/gateway_translator.go
  test/kubernetes/e2e/features/glooctl/get_proxy_suite.go
Labels: keep pr updated

#9529 Mark double proxy Istio integration helm values for deprecation
  changelog/v1.17.0-beta34/mark-double-proxy-values-as-deprecated.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/values-template.yaml
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/plugins/istio_integration/plugin.go
  projects/gloo/pkg/plugins/kubernetes/eds.go
  projects/gloo/pkg/plugins/kubernetes/eds_test.go
Labels: keep pr updated
