Repository kgateway-dev/kgateway, pull requests merged in 2024-06, with the labels that each got.

#9566 [v1.15.x] Backport docs (#9499)
  changelog/v1.15.29/docs-backport.yaml
  docs/Makefile
  docs/content/_index.md
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/guides/traffic_management/destination_types/kubernetes_services/_index.md
  docs/content/guides/traffic_management/destination_types/static_upstream/_index.md
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/img/portal/petstore-food-bowl-collar.png
  docs/content/installation/_index.md
  docs/content/installation/advanced_configuration/vault_secrets.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/introduction/faq.md
  docs/content/operations/production_deployment/_index.md
  docs/content/operations/updating_license/_index.md
  docs/content/static/content/enterprise_only_feature_disclaimer
  docs/content/static/content/license-key
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  docs/content/support/about.md
  docs/content/support/support-ticket.md
Labels: Type: Docs, keep pr updated

#9567 [v1.14.x] Backport docs (#9499)
  changelog/v1.14.31/docs-backports.yaml
  docs/Makefile
  docs/content/_index.md
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/guides/traffic_management/destination_types/kubernetes_services/_index.md
  docs/content/guides/traffic_management/destination_types/static_upstream/_index.md
  docs/content/img/portal/petstore-food-bowl-collar.png
  docs/content/installation/_index.md
  docs/content/installation/advanced_configuration/vault_secrets.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/introduction/faq.md
  docs/content/operations/production_deployment/_index.md
  docs/content/operations/updating_license/_index.md
  docs/content/static/content/enterprise_only_feature_disclaimer
  docs/content/static/content/license-key
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  docs/content/support/about.md
  docs/content/support/support-ticket.md
Labels: Type: Docs, keep pr updated

#9568 [v1.13.x] Backport docs (#9499)
  changelog/v1.13.38/docs-backport.yaml
  docs/Makefile
  docs/content/_index.md
  docs/content/guides/graphql/automatic_discovery.md
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/guides/traffic_management/destination_types/kubernetes_services/_index.md
  docs/content/guides/traffic_management/destination_types/static_upstream/_index.md
  docs/content/img/portal/petstore-food-bowl-collar.png
  docs/content/installation/_index.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/introduction/faq.md
  docs/content/operations/production_deployment/_index.md
  docs/content/operations/updating_license/_index.md
  docs/content/static/content/enterprise_only_feature_disclaimer
  docs/content/static/content/license-key
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  docs/content/support/about.md
  docs/content/support/support-ticket.md
Labels: Type: Docs, keep pr updated

#9572 iosnapshot: support Kubernetes Gateway resources in input snapshot
  changelog/v1.17.0-beta35/expand-debug-snapshot.yaml
  projects/gateway2/controller/start.go
  projects/gloo/pkg/servers/admin/server.go
  projects/gloo/pkg/servers/iosnapshot/history.go
  projects/gloo/pkg/servers/iosnapshot/history_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/setup/start_func.go
Labels: keep pr updated

#9571 Fix CurlEventuallyShouldOutput regression
  changelog/v1.17.0-beta35/eventually-curl-succeeds-ignores-errors.yaml
  test/kube2e/helper/curl.go
Labels: keep pr updated

#9576 convert RtOpt, VHostOpt to targetRefs
  changelog/v1.17.0-beta36/route-vhost-opts-targetrefs.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/external_options.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  projects/gateway/api/v1/external_options.proto
  projects/gateway/pkg/api/v1/external_options.pb.clone.go
  projects/gateway/pkg/api/v1/external_options.pb.equal.go
  projects/gateway/pkg/api/v1/external_options.pb.go
  projects/gateway/pkg/api/v1/external_options.pb.hash.go
  projects/gateway2/examples/example-http-route-with-attached-options.yaml
  projects/gateway2/translator/plugins/listeneroptions/query/query.go
  projects/gateway2/translator/plugins/routeoptions/query/indexers.go
  projects/gateway2/translator/plugins/routeoptions/query/query.go
  projects/gateway2/translator/plugins/routeoptions/query/query_test.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/plugins/utils/plugin_utils.go
  projects/gateway2/translator/plugins/virtualhostoptions/query/indexers.go
  projects/gateway2/translator/plugins/virtualhostoptions/query/query.go
  projects/gateway2/translator/plugins/virtualhostoptions/query/query_test.go
  projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin_test.go
  projects/gateway2/translator/testutils/inputs/delegation/route_options.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_filter.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_filter_override_merge.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_inheritance.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_inheritance_child_override_ignore.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_inheritance_child_override_ok.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_inheritance_filter_override.yaml
  projects/gateway2/translator/testutils/inputs/delegation/route_options_multi_level_inheritance_override_ok.yaml
  projects/gateway2/translator/translator_case_test.go
  projects/gateway2/validation/validator_test.go
  test/kubernetes/e2e/features/route_delegation/testdata/route_options.yaml
  test/kubernetes/e2e/features/route_options/testdata/bad-rto-targetref.yaml
  test/kubernetes/e2e/features/route_options/testdata/basic-rto-targetref.yaml
  test/kubernetes/e2e/features/route_options/testdata/extra-rto-targetref.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/basic-vho.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/extra-vho.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/section-name-vho.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/webhook-reject-bad-vho.yaml
Labels: keep pr updated

#9583 New global istio integration enabled field
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/k8sgateway_test.go
Labels: keep pr updated

#9485 proxy api: support destination ip/port matching
  changelog/v1.17.0-beta36/proxy-destination-matchers.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  projects/gateway/pkg/translator/hybrid_translator.go
  projects/gateway2/proxy_syncer/proxy_syncer.go
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/v1/proxy.pb.clone.go
  projects/gloo/pkg/api/v1/proxy.pb.equal.go
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/api/v1/proxy.pb.hash.go
  projects/gloo/pkg/translator/filter_chain.go
  projects/gloo/pkg/translator/listener_subsystem.go
  projects/gloo/pkg/translator/listener_subsystem_test.go
Labels: keep pr updated

#9582 plugins: respect allowWarnings, introduce ConfigurationError
  changelog/v1.17.0-rc1/add-error-types-for-plugins.yaml
  changelog/v1.17.0-rc1/k8s-gateway-istio-integration-values.yaml
  changelog/v1.17.0-rc1/proxy-destination-matchers.yaml
  changelog/v1.17.0-rc1/route-vhost-opts-targetrefs.yaml
  projects/gloo/pkg/plugins/configuration_error.go
  projects/gloo/pkg/plugins/plugins.go
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/translator/reporting.go
  projects/gloo/pkg/translator/reporting_test.go
  projects/gloo/pkg/translator/route_config.go
Labels: keep pr updated

#9584 Rename helm value for kube gateway envoy image
  changelog/v1.17.0-rc2/gwp-helm-envoy-image.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate.go
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/helm/gloo/values-template.yaml
  install/test/k8sgateway_test.go
Labels: keep pr updated

#9586 Ensure `json_to_proto` is passed through to envoy
  changelog/v1.17.0-rc2/passthrough-json-to-proto.yaml
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/transformation/plugin_test.go
Labels: keep pr updated

#9589 Doc fixes
  changelog/v1.17.0-rc2/doc-fixes.yaml
  docs/content/guides/security/access_logging/_index.md
  docs/content/guides/security/rate_limiting/setup.md
  docs/content/introduction/faq.md
Labels: keep pr updated

#9593 Doc fixes 1.13
  changelog/v1.13.38/docs-backport1.yaml
  docs/content/guides/security/access_logging/_index.md
  docs/content/introduction/faq.md
Labels: keep pr updated

#9592 Doc fixes 1.14
  changelog/v1.14.31/docs-backports1.yaml
  docs/content/guides/security/access_logging/_index.md
  docs/content/guides/security/rate_limiting/setup.md
  docs/content/introduction/faq.md
Labels: keep pr updated

#9591 Doc fixes 1.15
  changelog/v1.15.29/docs-backport1.yaml
  docs/content/guides/security/access_logging/_index.md
  docs/content/guides/security/rate_limiting/setup.md
  docs/content/introduction/faq.md
Labels: keep pr updated

#9590 Doc fixes 1.16
  changelog/v1.16.15/docs-backport1.yaml
  docs/content/guides/security/access_logging/_index.md
  docs/content/guides/security/rate_limiting/setup.md
  docs/content/introduction/faq.md
Labels: keep pr updated

#9599 Fix istioIntegration.enabled, only use istioIntegration.enabled for Istio automtls
  changelog/v1.17.0-rc3/fix-istio-integration-helm-values.yaml
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/plugins/istio_automtls/plugin.go
  test/kube2e/istio/README.md
  test/kube2e/istio/artifacts/automtls-helm.yaml
  test/kube2e/istio/artifacts/gloo-gateway-helm.yaml
  test/kube2e/istio/istio_suite_test.go
  test/kubernetes/e2e/tests/manifests/istio-automtls-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-automtls-k8s-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-edge-gateway-test-helm.yaml
  test/kubernetes/e2e/tests/manifests/istio-k8s-gateway-test-helm.yaml
Labels: keep pr updated

#9602 make: bump envoy for 1.27.6 to address cve scanners
  Makefile
  changelog/v1.16.15/envoy-bump.yaml
Labels: keep pr updated

#9600 Stateful Session filter
  Makefile
  changelog/v1.17.0-rc3/stateful_session.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/stateful_session/stateful_session.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/statefulsession/statefulsession.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/statefulsession/statefulsession.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_HttpListenerOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  pkg/utils/requestutils/curl/option.go
  pkg/utils/requestutils/curl/request.go
  projects/gloo/api/v1/enterprise/options/stateful_session/stateful_session.proto
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/enterprise/options/stateful_session/stateful_session.pb.go
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/plugins/enterprise_warning/plugin.go
  projects/gloo/pkg/plugins/enterprise_warning/plugin_test.go
  test/gomega/transforms/curl_test.go
  test/gomega/transforms/transforms.go
  test/kubernetes/e2e/debugging.md
Labels: keep pr updated

#9611 Fix MetalLB setup for Kube GW API conformance tests
  changelog/v1.17.0-rc3/fix-conformance-setup.yaml
  ci/kind/setup-kind.sh
Labels: keep pr updated

#9615 skip istio regression tests
  .github/workflows/regression-tests.yaml
Labels: keep pr updated

#9606 Test curl fixes
  changelog/v1.17.0-rc3/test-curl-fixes.yaml
  pkg/utils/kubeutils/kubectl/cli.go
  test/gomega/transforms/curl.go
  test/gomega/transforms/curl_test.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/helper/curl.go
  test/kubernetes/testutils/assertions/curl.go
Labels: keep pr updated

#9617 test: print stdout and stderr of Curl request
  changelog/v1.17.0-rc4/test-dbg.yaml
  test/kubernetes/testutils/assertions/curl.go
Labels: keep pr updated

#9587 Validation passes settings in params
  .github/workflows/regression-tests.yaml
  changelog/v1.17.0-rc4/add-allow-warnings-validating-admission-webhook.yaml
  projects/gateway2/validation/validator_test.go
  projects/gloo/pkg/plugins/consul/subsets.go
  projects/gloo/pkg/plugins/extauth/config_generator.go
  projects/gloo/pkg/plugins/extauth/config_generator_test.go
  projects/gloo/pkg/plugins/istio_integration/plugin.go
  projects/gloo/pkg/plugins/linkerd/plugin.go
  projects/gloo/pkg/plugins/pluginutils/destination_upstreams.go
  projects/gloo/pkg/plugins/pluginutils/headers.go
  projects/gloo/pkg/plugins/pluginutils/per_filter_config.go
  projects/gloo/pkg/plugins/ratelimit/plugin.go
  projects/gloo/pkg/plugins/tcp/plugin.go
  projects/gloo/pkg/plugins/tracing/plugin.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/translator/filter_chain.go
  projects/gloo/pkg/translator/reporting.go
  projects/gloo/pkg/translator/reporting_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/validation/server_test.go
  projects/gloo/pkg/validation/validator.go
  test/samples/sample_gloo_api_snapshot.go
Labels: keep pr updated

#9607 resync on service update
  changelog/v1.17.0-rc4/ggv2-resync-on-svc.yaml
  projects/gateway2/controller/controller.go
  test/kubernetes/e2e/features/services/inputs/route-with-service.yaml
  test/kubernetes/e2e/features/services/inputs/service-for-route.yaml
  test/kubernetes/e2e/features/services/suite.go
  test/kubernetes/e2e/features/services/types.go
  test/kubernetes/e2e/tests/k8s_gw_test.go
Labels: keep pr updated

#9594 Lambda support
  changelog/v1.17.0-rc4/ggv2-function-routing.yaml
  projects/gateway2/parameters/README.md
  projects/gateway2/parameters/parameters.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/httproute/gateway_http_route_translator_test.go
  projects/gateway2/translator/testutils/inputs/http-with-azure-destination/manifests.yaml
  projects/gateway2/translator/testutils/inputs/http-with-lambda-destination/manifests.yaml
  projects/gateway2/translator/testutils/outputs/http-with-azure-destination-proxy.yaml
  projects/gateway2/translator/testutils/outputs/http-with-lambda-destination-proxy.yaml
Labels: keep pr updated

#9618 fix `glooctl check` when default gateway proxy is disabled
  changelog/v1.17.0-rc4/glooctl-check-fix-prom-stats.yaml
  projects/gloo/cli/pkg/cmd/check/proxy_prom_stats.go
Labels: keep pr updated

#9619 changelog: introduce 1.18 beta1 folder
  changelog/v1.18.0-beta1/1-18-beta1.yaml
Labels: keep pr updated

#9620 .github/workflows: update nightly tests to include 1.17
  .github/workflows/nightly-tests.yaml
  changelog/v1.18.0-beta1/update-lts.yaml
Labels: keep pr updated

#9608 Add support for host_rewrite_header
  changelog/v1.18.0-beta1/add-host-rewrite-header.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  pkg/utils/api_conversion/type.go
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/plugins/basicroute/plugin.go
  projects/gloo/pkg/plugins/basicroute/plugin_test.go
  projects/gloo/pkg/plugins/utils/headers/headers_suite_test.go
  projects/gloo/pkg/plugins/utils/headers/validate.go
  projects/gloo/pkg/plugins/utils/headers/validate_test.go
Labels: keep pr updated

#9614 gateway2: merge multiple targetRef based Route & VirtualHost options
  changelog/v1.18.0-beta1/options-merge.yaml
  projects/gateway/pkg/translator/merge.go
  projects/gateway/pkg/translator/merge_test.go
  projects/gateway/pkg/translator/virtual_service_translator.go
  projects/gateway2/translator/plugins/routeoptions/query/query.go
  projects/gateway2/translator/plugins/routeoptions/query/query_test.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin.go
  projects/gateway2/translator/plugins/virtualhostoptions/virtualhost_options_plugin_test.go
  projects/gloo/pkg/utils/merge.go
  test/kubernetes/e2e/features/route_options/suite.go
  test/kubernetes/e2e/features/route_options/testdata/merge.yaml
  test/kubernetes/e2e/features/route_options/types.go
  test/kubernetes/e2e/features/virtualhost_options/testdata/extra-vho-merge.yaml
  test/kubernetes/e2e/features/virtualhost_options/types.go
  test/kubernetes/e2e/features/virtualhost_options/vhost_opt_suite.go
Labels: keep pr updated

#9624 [1.16] Add support for host_rewrite_header
  changelog/v1.16.16/add-host-rewrite-header.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  pkg/utils/api_conversion/type.go
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/plugins/basicroute/plugin.go
  projects/gloo/pkg/plugins/basicroute/plugin_test.go
  projects/gloo/pkg/plugins/utils/headers/headers_suite_test.go
  projects/gloo/pkg/plugins/utils/headers/validate.go
  projects/gloo/pkg/plugins/utils/headers/validate_test.go
Labels: keep pr updated

#9623 [1.17] Add support for host_rewrite_header
  .github/workflows/regression-tests.yaml
  changelog/v1.17.1/add-host-rewrite-header.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  pkg/utils/api_conversion/type.go
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/plugins/basicroute/plugin.go
  projects/gloo/pkg/plugins/basicroute/plugin_test.go
  projects/gloo/pkg/plugins/utils/headers/headers_suite_test.go
  projects/gloo/pkg/plugins/utils/headers/validate.go
  projects/gloo/pkg/plugins/utils/headers/validate_test.go
Labels: keep pr updated

#9581 Refactor Kubernetes E2E test definition for ease of use
  changelog/v1.18.0-beta1/e2e-tests-cleanup.yaml
  test/kubernetes/e2e/README.md
  test/kubernetes/e2e/features/deployer/istio_integration_deployer_suite.go
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/example/suite.go
  test/kubernetes/e2e/features/glooctl/check_suite.go
  test/kubernetes/e2e/features/glooctl/debug_suite.go
  test/kubernetes/e2e/features/glooctl/get_proxy_suite.go
  test/kubernetes/e2e/features/glooctl/istio_inject_suite.go
  test/kubernetes/e2e/features/glooctl/istio_uninject_suite.go
  test/kubernetes/e2e/features/headless_svc/gloo_gateway_suite.go
  test/kubernetes/e2e/features/headless_svc/k8s_gw_suite.go
  test/kubernetes/e2e/features/http_listener_options/http_lis_opt_suite.go
  test/kubernetes/e2e/features/istio/gloo_gateway_auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/gloo_gateway_no_auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/k8s_gateway_auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/k8s_gateway_no_auto_mtls_suite.go
  test/kubernetes/e2e/features/listener_options/lis_opt_suite.go
  test/kubernetes/e2e/features/port_routing/suite.go
  test/kubernetes/e2e/features/route_delegation/suite.go
  test/kubernetes/e2e/features/route_options/suite.go
  test/kubernetes/e2e/features/upstreams/suite.go
  test/kubernetes/e2e/features/virtualhost_options/vhost_opt_suite.go
  test/kubernetes/e2e/suite.go
  test/kubernetes/e2e/tests/automtls_istio_edge_api_test.go
  test/kubernetes/e2e/tests/automtls_istio_edge_api_tests.go
  test/kubernetes/e2e/tests/automtls_istio_test.go
  test/kubernetes/e2e/tests/automtls_istio_tests.go
  test/kubernetes/e2e/tests/edge_gw_test.go
  test/kubernetes/e2e/tests/edge_gw_tests.go
  test/kubernetes/e2e/tests/glooctl_istio_inject_test.go
  test/kubernetes/e2e/tests/glooctl_istio_inject_tests.go
  test/kubernetes/e2e/tests/istio_edge_api_test.go
  test/kubernetes/e2e/tests/istio_edge_api_tests.go
  test/kubernetes/e2e/tests/istio_test.go
  test/kubernetes/e2e/tests/istio_tests.go
  test/kubernetes/e2e/tests/k8s_gw_no_validation_test.go
  test/kubernetes/e2e/tests/k8s_gw_no_validation_tests.go
  test/kubernetes/e2e/tests/k8s_gw_test.go
  test/kubernetes/e2e/tests/k8s_gw_tests.go
Labels: keep pr updated

#9635 prevent Proxy namespace from being modified
  changelog/v1.17.0-rc5/add-host-rewrite-header.yaml
  changelog/v1.17.0-rc5/stop-status-spamming.yaml
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
Labels: keep pr updated

#9563 Retry on leader lease renewal failure
  changelog/v1.18.0-beta1/dont-crash-on-failed-lease-renewal.yaml
  ci/kind/cluster.yaml
  ci/kind/setup-kind.sh
  pkg/bootstrap/leaderelector/identity.go
  pkg/bootstrap/leaderelector/kube/factory.go
  pkg/utils/kubeutils/kubectl/cli.go
  projects/gloo/pkg/setup/setup.go
  test/kube2e/gloo/artifacts/block-gloo-apiserver.yaml
  test/kube2e/gloo/artifacts/block-labels.yaml
  test/kube2e/gloo/artifacts/helm.yaml
  test/kube2e/gloo/bootstrap_clients_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/gloo/setup_syncer_test.go
  test/kube2e/helper/install.go
  test/kube2e/helper/kube.go
Labels: keep pr updated

#9632 helm: support webhook.enablePolicyApi
  changelog/v1.18.0-beta1/helm-policy-validation-api.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  install/helm/gloo/values-template.yaml
  install/test/5-gateway-validation-webhook-configuration_test.go
Labels: keep pr updated

#9634 tests: Update how kube2e tests report and update the glooctl check tests
  .github/workflows/composite-actions/kubernetes-e2e-tests/action.yaml
  changelog/v1.18.0-beta1/update-kube2e-tests.yaml
  test/kubernetes/e2e/features/glooctl/check_suite.go
Labels: keep pr updated

#9639 [1.17] Retry on leader lease renewal failure
  changelog/v1.17.0-rc5/dont-crash-on-failed-lease-renewal.yaml
  ci/kind/cluster.yaml
  ci/kind/setup-kind.sh
  pkg/bootstrap/leaderelector/identity.go
  pkg/bootstrap/leaderelector/kube/factory.go
  pkg/utils/kubeutils/kubectl/cli.go
  projects/gloo/pkg/setup/setup.go
  test/kube2e/gloo/artifacts/block-gloo-apiserver.yaml
  test/kube2e/gloo/artifacts/block-labels.yaml
  test/kube2e/gloo/artifacts/helm.yaml
  test/kube2e/gloo/bootstrap_clients_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/gloo/setup_syncer_test.go
  test/kube2e/helper/install.go
  test/kube2e/helper/kube.go
Labels: keep pr updated

#9648 ci: disable ingress on 1.17 nightlies
  .github/workflows/nightly-tests.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.18.0-beta1/disable-ingress-nightlies.yaml
Labels: keep pr updated

#9625 Fix status syncer and fix Istio integration values for discoveryAddress, istioMetaMeshId and istioMetaClusterId
  changelog/v1.18.0-beta1/fix-proxy-status-sync.yaml
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/proxy_syncer/proxy_syncer.go
  projects/gateway2/status/status_syncer.go
  projects/gateway2/status/status_syncer_test.go
Labels: keep pr updated

#9646 introduce test coverage reporting, update devel with Gloo Gateway references
  .github/workflows/pr-unit-tests.yaml
  .github/workflows/pr.yaml
  Makefile
  README.md
  changelog/v1.18.0-beta1/test-coverage-p1.yaml
  devel/README.md
  devel/architecture/endpoint-discovery.md
  devel/architecture/external-options.md
  devel/architecture/istio-integration.md
  devel/architecture/static_metadata.md
  devel/architecture/upstream-discovery.md
  devel/contributing/backports.md
  devel/contributing/documentation.md
  devel/contributing/issues.md
  devel/contributing/pull-request-reviews.md
  devel/contributing/pull-requests.md
  devel/debugging/envoy-segfault.md
  devel/testing/aws-tests.md
  devel/testing/e2e-tests.md
  devel/testing/flaky-tests.md
  devel/testing/kube-e2e-tests.md
  devel/testing/run-tests.md
  devel/tools/README.md
  install/README.md
  projects/envoyinit/README.md
  test_coverage.yml
Labels: keep pr updated

#9651 gateway2/deployer: fix race due to context cancellation
  changelog/v1.18.0-beta1/deployer-test-race.yaml
  projects/gateway2/deployer/deployer.go
  projects/gloo/cli/pkg/cmd/install/kubegateway/install.go
  projects/gloo/cli/pkg/cmd/install/kubegateway/uninstall.go
Labels: keep pr updated

#9652 [1.17] backport recent changes to main
  .github/workflows/pr-unit-tests.yaml
  .github/workflows/pr.yaml
  Makefile
  README.md
  changelog/v1.17.0-rc6/backport-recent-changes.yaml
  devel/README.md
  devel/architecture/endpoint-discovery.md
  devel/architecture/external-options.md
  devel/architecture/static_metadata.md
  devel/architecture/upstream-discovery.md
  devel/contributing/backports.md
  devel/contributing/documentation.md
  devel/contributing/issues.md
  devel/contributing/pull-request-reviews.md
  devel/contributing/pull-requests.md
  devel/debugging/envoy-segfault.md
  devel/testing/aws-tests.md
  devel/testing/e2e-tests.md
  devel/testing/flaky-tests.md
  devel/testing/kube-e2e-tests.md
  devel/testing/run-tests.md
  devel/tools/README.md
  docs/content/reference/values.txt
  install/README.md
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/5-gateway-validation-webhook-configuration.yaml
  install/helm/gloo/values-template.yaml
  install/test/5-gateway-validation-webhook-configuration_test.go
  projects/envoyinit/README.md
  projects/gateway2/deployer/deployer.go
  projects/gloo/cli/pkg/cmd/install/kubegateway/install.go
  projects/gloo/cli/pkg/cmd/install/kubegateway/uninstall.go
  projects/gloo/pkg/servers/iosnapshot/history_test.go
  test_coverage.yml
Labels: keep pr updated

#9655 [1.17] ci: Disable ingress suite on regression tests
  .github/workflows/regression-tests.yaml
  changelog/v1.17.0-rc6/disable-ingress.yaml
Labels: keep pr updated

#9647 fix: Reject a hybridGateway with no delegatedHttpGateways when no VS exist
  changelog/v1.18.0-beta2/fix-aggregate-gateway-error.yaml
  projects/gateway/pkg/translator/aggregate_translator.go
  projects/gateway/pkg/translator/aggregate_translator_test.go
  projects/gateway/pkg/translator/http_translator.go
Labels: keep pr updated

#9659 [1.17] fix: Reject a hybridGateway with no delegatedHttpGateways when no VS exist
  changelog/v1.17.0-rc6/fix-aggregate-gateway-error.yaml
  projects/gateway/pkg/translator/aggregate_translator.go
  projects/gateway/pkg/translator/aggregate_translator_test.go
  projects/gateway/pkg/translator/http_translator.go
Labels: keep pr updated

#9662 Doc fixes
  changelog/v1.18.0-beta2/doc-fixes.yaml
  docs/content/reference/gloo_port_reference.md
Labels: keep pr updated

#9621 make glooctl check work for kube gateways
  .github/workflows/composite-actions/regression-tests/action.yaml
  changelog/v1.18.0-beta2/glooctl-check.yaml
  ci/kind/setup-kind.sh
  docs/content/guides/gloo_federation/federated_configuration.md
  docs/content/operations/debugging_gloo/_index.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/reference/cli/glooctl_check.md
  docs/content/support/support-info.md
  projects/gloo/cli/pkg/cmd/check/gloo_instances.go
  projects/gloo/cli/pkg/cmd/check/internal/checks.go
  projects/gloo/cli/pkg/cmd/check/internal/kubegateway/check.go
  projects/gloo/cli/pkg/cmd/check/kube_gateway.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/install/kubegateway/install.go
  projects/gloo/cli/pkg/constants/constants.go
  projects/gloo/cli/pkg/flagutils/metadata.go
  projects/gloo/cli/pkg/kubegatewayutils/detect.go
  projects/gloo/cli/pkg/printers/check.go
  test/kube2e/README.md
  test/kube2e/glooctl/check_test.go
  test/kubernetes/e2e/features/glooctl/check.go
  test/kubernetes/e2e/tests/k8s_gw_tests.go
Labels: keep pr updated

#9663 Doc fixes 1.16 (#9662)
  changelog/v1.16.17/doc-fixes.yaml
  docs/content/reference/gloo_port_reference.md
Labels: keep pr updated

#9664 Doc fixes 1.15 (#9662)
  changelog/v1.15.29/doc-fixes.yaml
  docs/content/reference/gloo_port_reference.md
Labels: keep pr updated

#9665 Doc fixes 1.14 (#9662)
  changelog/v1.14.31/doc-fixes2.yaml
  docs/content/reference/gloo_port_reference.md
Labels: keep pr updated

#9649 Add distroless docs
  changelog/v1.18.0-beta2/add-distroless-docs.yaml
  devel/architecture/distroless.md
  pkg/utils/kubeutils/kubectl/cli.go
Labels: keep pr updated

#9666 [1.17] make glooctl check work for kube gateways
  .github/workflows/composite-actions/regression-tests/action.yaml
  changelog/v1.17.0-rc7/glooctl-check.yaml
  ci/kind/setup-kind.sh
  docs/content/guides/gloo_federation/federated_configuration.md
  docs/content/operations/debugging_gloo/_index.md
  docs/content/operations/upgrading/upgrade_steps.md
  docs/content/reference/cli/glooctl_check.md
  docs/content/support/support-info.md
  projects/gloo/cli/pkg/cmd/check/gloo_instances.go
  projects/gloo/cli/pkg/cmd/check/internal/checks.go
  projects/gloo/cli/pkg/cmd/check/internal/kubegateway/check.go
  projects/gloo/cli/pkg/cmd/check/kube_gateway.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/install/kubegateway/install.go
  projects/gloo/cli/pkg/constants/constants.go
  projects/gloo/cli/pkg/flagutils/metadata.go
  projects/gloo/cli/pkg/kubegatewayutils/detect.go
  projects/gloo/cli/pkg/printers/check.go
  test/kube2e/README.md
  test/kube2e/glooctl/check_test.go
  test/kubernetes/e2e/features/glooctl/check.go
  test/kubernetes/e2e/tests/k8s_gw_tests.go
Labels: keep pr updated

#9657 Fully default gwparams
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta2/fully-default-gwparams.yaml
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_crds.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/helm/gloo/values-template.yaml
  install/test/k8sgateway_test.go
  projects/gateway2/api/v1alpha1/gateway_parameters.proto
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/_helpers.tpl
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/helm/gloo-gateway/values.yaml
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.hash.go
  test/kubernetes/e2e/features/deployer/minimal_default_gatewayparameters_deployer_suite.go
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/deployer/testdata/basic-gateway.yaml
  test/kubernetes/e2e/features/deployer/testdata/deployer-provision.yaml
  test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml
  test/kubernetes/e2e/features/deployer/types.go
  test/kubernetes/e2e/tests/k8s_gw_minimal_default_gatewayparameters_test.go
  test/kubernetes/e2e/tests/k8s_gw_minimal_default_gatewayparameters_tests.go
  test/kubernetes/e2e/tests/manifests/k8s-gateway-minimal-default-gatewayparameters-test-helm.yaml
Labels: keep pr updated

#9676 setup kind fix for installing cilium
  changelog/v1.18.0-beta2/helm-repo-update-cilium.yaml
  ci/kind/setup-kind.sh
Labels: keep pr updated

#9677 [1.17] Fully default gwparams
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.17.0-rc7/fully-default-gwparams.yaml
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_crds.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/helm/gloo/values-template.yaml
  install/test/k8sgateway_test.go
  projects/gateway2/api/v1alpha1/gateway_parameters.proto
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/_helpers.tpl
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/helm/gloo-gateway/values.yaml
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.hash.go
  test/kubernetes/e2e/features/deployer/minimal_default_gatewayparameters_deployer_suite.go
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/deployer/testdata/basic-gateway.yaml
  test/kubernetes/e2e/features/deployer/testdata/deployer-provision.yaml
  test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml
  test/kubernetes/e2e/features/deployer/types.go
  test/kubernetes/e2e/tests/k8s_gw_minimal_default_gatewayparameters_test.go
  test/kubernetes/e2e/tests/k8s_gw_minimal_default_gatewayparameters_tests.go
  test/kubernetes/e2e/tests/manifests/k8s-gateway-minimal-default-gatewayparameters-test-helm.yaml
Labels: keep pr updated

#9675 Test propagation of fully defined GatewayParameters
  projects/gateway2/deployer/deployer_test.go
Labels: keep pr updated

#9674 glooctl: Improve performance of the check command by optimizing the creation of clients
  changelog/v1.18.0-beta2/optimize-glooctl-check.yaml
  projects/gloo/cli/pkg/cmd/check/root.go
  test/kube2e/glooctl/check_test.go
Labels: keep pr updated

#9658 GGv2: Add Prometheus stats listener to Envoy
  changelog/v1.18.0-beta2/add-stats-port-gwc2.yaml
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_crds.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/helm/gloo/values-template.yaml
  install/test/k8sgateway_test.go
  projects/gateway2/api/v1alpha1/gateway_parameters.proto
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.hash.go
Labels: keep pr updated

#9688 Backport fixes and metrics
  changelog/v1.17.0-rc7/various-gateway-touch-ups.yaml
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_crds.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/helm/gloo/values-template.yaml
  install/test/k8sgateway_test.go
  projects/gateway2/api/v1alpha1/gateway_parameters.proto
  projects/gateway2/controller/controller.go
  projects/gateway2/controller/controller_suite_test.go
  projects/gateway2/controller/gw_controller.go
  projects/gateway2/controller/start.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.hash.go
Labels: keep pr updated

#9686 5579 extended http methods (#9633)
  Makefile
  changelog/v1.17.0-rc8/5579-support-extended-http-methods.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/header_validation/header_validation.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_HttpListenerOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/header_validation/header_validation.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/options/header_validation/header_validation.pb.go
  projects/gloo/pkg/plugins/README.md
  projects/gloo/pkg/plugins/hcm/plugin.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  test/e2e/header_validation_test.go
  test/testutils/http_request.go
Labels: keep pr updated

#9682 Resuable Curl Pod for new framework e2e tests
  changelog/v1.18.0-beta2/curl-pod-manifest.yaml
  test/kubernetes/e2e/defaults/defaults.go
  test/kubernetes/e2e/defaults/testdata/curl_pod.yaml
  test/kubernetes/e2e/features/listener_options/lis_opt_suite.go
  test/kubernetes/e2e/features/listener_options/lis_opt_types.go
  test/kubernetes/e2e/features/listener_options/testdata/setup.yaml
Labels: work in progress

#9692 Remove glooctl init to not automatically register types to global scheme
  changelog/v1.17.0-rc8/remove-glooctl-init.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_instances.go
  projects/gloo/cli/pkg/cmd/check/root.go
Labels: keep pr updated

#9698 Remove glooctl init to not automatically register types to global scheme
  changelog/v1.18.0-beta2/remove-glooctl-init.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_instances.go
  projects/gloo/cli/pkg/cmd/check/root.go
Labels: keep pr updated

#9702 Fix services kubernetes e2e test
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.18.0-beta3/fix-services-test.yaml
  test/kubernetes/e2e/features/services/suite.go
  test/kubernetes/e2e/features/services/testdata/route-with-service.yaml
  test/kubernetes/e2e/features/services/testdata/service-for-route.yaml
  test/kubernetes/e2e/features/services/types.go
Labels: keep pr updated

#9701 GH readme update for Gloo Gateway
  README.md
  changelog/v1.18.0-beta3/docs-gh-update.yaml
  devel/README.md
  devel/contributing/documentation.md
  docs/content/img/gloo-gateway-architecture.svg
  docs/content/img/logo.svg
Labels: keep pr updated

#9697 1.13 - CVE Go bump
  changelog/v1.13.38/cve-24790.yaml
  cloudbuild.yaml
Labels: keep pr updated

#9695 1.14 - CVE bitnami/kubernetes and Go bump
  changelog/v1.14.31/cve-24790.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  jobs/kubectl/Dockerfile
Labels: keep pr updated

#9687 1.15 - CVE bitnami/kubectl and Go bump
  changelog/v1.15.29/cve-24790.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  jobs/kubectl/Dockerfile
Labels: keep pr updated

#9685 1.16 - CVE bitnami/kubernetes and Go bump
  changelog/v1.16.17/cve-24790.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  go.mod
  jobs/kubectl/Dockerfile
Labels: keep pr updated

#9678 main - CVE bitnami/kubectl and Go bump
  .trivyignore
  changelog/v1.18.0-beta3/cve-24790.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  cloudbuild-cache.yaml
  go.mod
  jobs/kubectl/Dockerfile
  jobs/kubectl/Dockerfile.distroless
Labels: keep pr updated

#9707 [1.17] Fix services kubernetes e2e test
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.17.0-rc9/fix-services-test.yaml
  test/kubernetes/e2e/features/services/suite.go
  test/kubernetes/e2e/features/services/testdata/route-with-service.yaml
  test/kubernetes/e2e/features/services/testdata/service-for-route.yaml
  test/kubernetes/e2e/features/services/types.go
Labels: keep pr updated

#9706 Docs: Istio auto-mTLS in Edge
  changelog/v1.18.0-beta3/docs-istio-automtls.yaml
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/operations/upgrading/faq.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_latest_minor.md
Labels: keep pr updated

#9703 gateway2: enable provisioning of AI extension
  changelog/v1.18.0-beta4/ai-ext-deploy.yaml
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_crds.yaml
  install/helm/gloo/generate.go
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  install/test/k8sgateway_test.go
  projects/gateway2/api/v1alpha1/gateway_parameters.proto
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.hash.go
Labels: keep pr updated
