Repository kgateway-dev/kgateway, pull requests merged in 2024-04, with the labels that each got.

#9303 Cleanup assets upload script
  Makefile
  changelog/v1.17.0-beta16/remove-pkgmgmt.yaml
  ci/README.md
  ci/upload_github_release_assets.go
  go.mod
  go.sum
Labels: keep pr updated

#9293 Doc fixes for week of March 25, 2024
  changelog/v1.17.0-beta16/doc-fixes.yaml
  docs/content/guides/security/waf/_index.md
  docs/content/installation/advanced_configuration/multiple-gloo-installs.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
Labels: Type: Docs, keep pr updated

#9276 GG deployer helm cleanup and use correct xds values
  changelog/v1.17.0-beta16/gg-deployer-xds-values.yaml
  pkg/utils/kubeutils/names.go
  projects/gateway2/controller/controller.go
  projects/gateway2/controller/controller_suite_test.go
  projects/gateway2/controller/gw_controller.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/hpa.yaml
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/helm/gloo-gateway/values.yaml
  projects/gloo/cli/pkg/cmd/install/v2/install.go
  projects/gloo/cli/pkg/cmd/install/v2/uninstall.go
  projects/gloo/pkg/bootstrap/opts.go
  projects/gloo/pkg/syncer/setup/controlplane.go
  projects/gloo/pkg/syncer/setup/controlplane_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  test/services/gloo.go
Labels: keep pr updated

#9286 Create and use a custom distroless-base as base for distroless variants
  Makefile
  changelog/v1.17.0-beta16/gloo-distroless-base.yaml
  projects/discovery/cmd/Dockerfile.distroless
  projects/distroless/Dockerfile
  projects/distroless/Dockerfile.utils
  projects/envoyinit/cmd/Dockerfile.envoyinit.distroless
  projects/gloo/cmd/Dockerfile.distroless
  projects/sds/cmd/Dockerfile.distroless
Labels: work in progress, keep pr updated

#9307 hardcode envoy's runtime flag for sanitize TE to false
  changelog/v1.17.0-beta16/envoy-sanitize-te-false.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/fixtures.go
  install/test/fixtures/envoy_config/bootstrap_extensions.yaml
  install/test/fixtures/envoy_config/custom_static_bootstrap.yaml
  install/test/fixtures/envoy_config/overload_manager.yaml
  install/test/fixtures/envoy_config/static_clusters.yaml
  install/test/fixtures/envoy_config/tcp_keepalive.yaml
  install/test/helm_test.go
Labels: keep pr updated

#9278 Add distroless variants to all images
  Makefile
  changelog/v1.17.0-beta16/distroless-all.yaml
  ci/kind/setup-kind.sh
  install/helm/gloo/templates/_helpers.tpl
  jobs/certgen/cmd/Dockerfile.distroless
  jobs/kubectl/Dockerfile.distroless
  projects/accesslogger/cmd/Dockerfile.distroless
  projects/distroless/Dockerfile.utils
  projects/ingress/cmd/Dockerfile.distroless
Labels: work in progress, keep pr updated

#9314 kubeutils: consolidate rest.Config and client construction
  changelog/v1.17.0-beta16/gg-kube-test-consolidate-utils.yaml
  pkg/cliutil/nsselect/setup.go
  pkg/cliutil/uri.go
  pkg/utils/envutils/env.go
  pkg/utils/kubeutils/rest_config.go
  pkg/utils/setuputils/main_setup.go
  projects/gateway2/tests/conformance/conformance_test.go
  projects/gloo/cli/pkg/cmd/check/gloo_instances.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/dashboard/root.go
  projects/gloo/cli/pkg/cmd/install/v2/install.go
  projects/gloo/cli/pkg/cmd/install/v2/uninstall.go
  projects/gloo/cli/pkg/cmd/version/clients.go
  projects/gloo/cli/pkg/helpers/clients.go
  projects/gloo/cli/pkg/helpers/kube.go
  projects/gloo/pkg/bootstrap/clients/common.go
  projects/gloo/pkg/bootstrap/clients/config_factory.go
  projects/gloo/pkg/bootstrap/clients/kube.go
  projects/gloo/pkg/bootstrap/utils.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/ingress/pkg/setup/setup_syncer.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gloo/bootstrap_clients_test.go
  test/kube2e/gloo/generated_kube_types_test.go
  test/kube2e/gloo/happypath_test.go
  test/kube2e/glooctl/glooctl_suite_test.go
  test/kube2e/gloomtls/gloo_mtls_suite_test.go
  test/kube2e/helm/helm_test.go
  test/kube2e/helper/test_container.go
  test/kube2e/ingress/ingress_test.go
  test/kube2e/ingress/resource_client_test.go
  test/kube2e/ingress/status_syncer_test.go
  test/kube2e/resource_clientset.go
  test/kube2e/upgrade/upgrade_test.go
  test/kube2e/util.go
  test/testutils/env.go
  test/testutils/kubeutils/clientset.go
  test/testutils/kubeutils/rest_config.go
Labels: keep pr updated

#9318 Refactor distroless dockerfiles
  Makefile
  changelog/v1.17.0-beta16/distorless-comments.yaml
  projects/distroless/Dockerfile
  projects/envoyinit/cmd/Dockerfile.envoyinit.distroless
  projects/gloo/cmd/Dockerfile.distroless
  projects/sds/cmd/Dockerfile.distroless
Labels: keep pr updated

#9312 gateway config crd tests
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gloo/pkg/syncer/setup/controlplane.go
  projects/gloo/pkg/syncer/setup/controlplane_test.go
Labels: keep pr updated

#9281 add RouteOption policy attachment
  changelog/v1.17.0-beta17/route-option-policy-attachment.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/external_options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/skv2/api/core/v1/core.proto.sk.md
  docs/data/ProtoMap.yaml
  go.mod
  go.sum
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  projects/gateway/api/v1/external_options.proto
  projects/gateway/pkg/api/v1/external_options.pb.clone.go
  projects/gateway/pkg/api/v1/external_options.pb.equal.go
  projects/gateway/pkg/api/v1/external_options.pb.go
  projects/gateway/pkg/api/v1/external_options.pb.hash.go
  projects/gateway2/controller/controller.go
  projects/gateway2/controller/controller_suite_test.go
  projects/gateway2/examples/example-http-route-with-attached-options.yaml
  projects/gateway2/extensions/extensions.go
  projects/gateway2/query/query.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/listener/validation.go
  projects/gateway2/translator/plugins/plugins.go
  projects/gateway2/translator/plugins/registry/plugin_registry.go
  projects/gateway2/translator/plugins/routeoptions/query/indexers.go
  projects/gateway2/translator/plugins/routeoptions/query/query.go
  projects/gateway2/translator/plugins/routeoptions/query/query_suite_test.go
  projects/gateway2/translator/plugins/routeoptions/query/query_test.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin_test.go
  projects/gateway2/translator/plugins/utils/plugin_utils.go
  projects/gateway2/translator/plugins/utils/sort_objects.go
  projects/gateway2/translator/plugins/utils/sort_objects_test.go
  projects/gateway2/translator/plugins/utils/utils_suite_test.go
  projects/gateway2/translator/testutils/inputs/http-with-header-modifier/manifests.yaml
  projects/gateway2/translator/testutils/outputs/http-with-header-modifier-proxy.yaml
  projects/gateway2/translator/testutils/test_queries.go
  projects/gateway2/translator/translator_case_test.go
  projects/gateway2/wellknown/gwapi.go
  projects/gloo/cli/pkg/cmd/check/internal/checks.go
Labels: keep pr updated

#9321 Expose disable dynamic stats (#9260)
  changelog/v1.16.10/expose-dynamic-stats.yaml
  docs/content/guides/dev/setting-up-dev-environment.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/router/router.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  projects/gloo/api/v1/options/router/router.proto
  projects/gloo/pkg/api/v1/options/router/router.pb.go
  projects/gloo/pkg/translator/listener_subsystem_test.go
  projects/gloo/pkg/translator/network_filters.go
  projects/gloo/pkg/translator/network_filters_test.go
Labels: keep pr updated

#9316 testutils: create curl and kubectl utilities
  changelog/v1.17.0-beta17/gg-kube-test-more-utils.yaml
  pkg/cliutil/install/kubernetes.go
  pkg/utils/cmdutils/cmd.go
  pkg/utils/cmdutils/local.go
  pkg/utils/cmdutils/run_error.go
  pkg/utils/kubeutils/kubectl/cli.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/install/uninstall.go
  test/gomega/matchers/contain_headers.go
  test/gomega/transforms/curl.go
  test/gomega/transforms/curl_test.go
  test/gomega/transforms/transforms_suite_test.go
  test/helpers/kube_dump.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/glooctl/istio_test.go
  test/kube2e/helper/curl.go
  test/kube2e/helper/test_container.go
  test/kube2e/istio/istio_integration_test.go
  test/testutils/curl_request.go
  test/testutils/http_request.go
Labels: keep pr updated

#9324 Doc fixes 1.16
  changelog/v1.16.10/doc-fixes.yaml
  docs/content/guides/integrations/service_mesh/istio.md
Labels: keep pr updated

#9325 Doc fixes 1.15
  changelog/v1.15.25/doc-fixes.yaml
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/support/_index.md
  docs/content/support/about.md
  docs/content/support/support-info.md
  docs/content/support/support-ticket.md
Labels: keep pr updated

#9326 Doc fixes 1.14
  changelog/v1.14.30/doc-fixes2.yaml
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/support/_index.md
  docs/content/support/about.md
  docs/content/support/support-info.md
  docs/content/support/support-ticket.md
Labels: keep pr updated

#9328 Doc fixes 1.13
  changelog/v1.13.37/doc-fixes1.yaml
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/support/_index.md
  docs/content/support/about.md
  docs/content/support/support-info.md
  docs/content/support/support-ticket.md
Labels: keep pr updated

#9336 feat: no compiler inlining
  Makefile
  changelog/v1.17.0-beta17/compiler-inlining.yaml
Labels: keep pr updated

#9335 utils: improve envoyutils and curl requestutils
  changelog/v1.17.0-beta17/gg-envoy-admin-cli.yaml
  pkg/utils/cmdutils/local.go
  pkg/utils/cmdutils/run_error.go
  pkg/utils/envoyutils/admincli/README.md
  pkg/utils/envoyutils/admincli/admincli_suite_test.go
  pkg/utils/envoyutils/admincli/client.go
  pkg/utils/envoyutils/admincli/client_test.go
  pkg/utils/kubeutils/kubectl/cli.go
  pkg/utils/protoutils/utils.go
  pkg/utils/requestutils/curl/curl_suite_test.go
  pkg/utils/requestutils/curl/option.go
  pkg/utils/requestutils/curl/request.go
  pkg/utils/requestutils/curl/request_test.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/install/uninstall.go
  projects/gloo/pkg/defaults/port.go
  test/e2e/happypath_test.go
  test/e2e/staged_transformation_test.go
  test/helpers/kube_dump.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/gateway/robustness_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/gloo/setup_syncer_test.go
  test/kube2e/helper/curl.go
  test/services/envoy/instance.go
  test/testutils/curl_request.go
Labels: keep pr updated

#9338 glooctl: resolve test flake
  .github/workflows/istio-tests.yaml
  .github/workflows/pr.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.17.0-beta18/glooctl-test-flake.yaml
  ci/kind/setup-kind.sh
  projects/gateway2/README.md
  projects/gloo/cli/pkg/cmd/istio/util.go
  projects/gloo/cli/pkg/prerun/version_warning.go
  projects/gloo/cli/pkg/prerun/version_warning_test.go
  test/kube2e/README.md
  test/kube2e/argocd/argocd_suite_test.go
  test/kube2e/glooctl/istio_test.go
  test/kube2e/istio/README.md
Labels: keep pr updated

#9346 kube2e: resolve recent test flakes
  changelog/v1.17.0-beta19/gg-kube-gateway-test-timeout.yaml
  pkg/utils/requestutils/curl/option.go
  pkg/utils/requestutils/curl/request.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/gloomtls/gloo_mtls_test.go
  test/kube2e/helper/curl.go
  test/kube2e/helper/test_container.go
Labels: keep pr updated

#9351 utils: Improve kubeutils, cmdutils, errutils
  changelog/v1.17.0-beta19/gg-kube-test-expand-utils.yaml
  pkg/utils/cmdutils/cmdutils_suite_test.go
  pkg/utils/cmdutils/file.go
  pkg/utils/cmdutils/file_test.go
  pkg/utils/cmdutils/local.go
  pkg/utils/errutils/concurrent.go
  pkg/utils/errutils/concurrent_test.go
  pkg/utils/errutils/errutils_suite_test.go
  pkg/utils/kubeutils/kubectl/cli.go
  pkg/utils/kubeutils/portforward/portforwarder.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9349 Add api for targetrefwithsectionname on vhostoptions
  changelog/v1.17.0-beta19/vhopts-targetref-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/external_options.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  projects/gateway/api/v1/external_options.proto
  projects/gateway/pkg/api/v1/external_options.pb.clone.go
  projects/gateway/pkg/api/v1/external_options.pb.equal.go
  projects/gateway/pkg/api/v1/external_options.pb.go
  projects/gateway/pkg/api/v1/external_options.pb.hash.go
Labels: keep pr updated

#9355 add pluginBuilderParams
  changelog/v1.17.0-beta19/gg-plugin-params.yaml
  projects/gateway2/controller/controller_suite_test.go
  projects/gateway2/controller/start.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/extensions/extensions.go
  projects/gateway2/xds/xds_syncer.go
Labels: keep pr updated

#9331 add xds input channels extensions factory
  changelog/v1.17.0-beta20/extensions-kick-channel.yaml
  projects/gateway2/controller/controller_suite_test.go
  projects/gateway2/controller/start.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/extensions/extensions.go
  projects/gateway2/xds/xds_syncer.go
Labels: keep pr updated

#9287 GG control plane helm cleanup
  .github/workflows/pr.yaml
  changelog/v1.17.0-beta20/gg-cp-helm-cleanup.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/1-gloo-deployment.yaml
  install/helm/gloo/templates/44-gatewayclass.yaml
  install/helm/gloo/templates/44-rbac.yaml
  install/helm/gloo/templates/_gg-helpers.tpl
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  install/test/k8sgateway_test.go
  install/test/kube_utils.go
  install/test/rbac_test.go
  install/test/rbac_utils.go
  projects/gateway2/README.md
  projects/gateway2/controller/gw_controller.go
  projects/gateway2/helm/gloo-gateway/templates/_helpers.tpl
  projects/gateway2/tests/conformance/test-values.yaml
  projects/gateway2/translator/plugins/utils/utils_suite_test.go
  test/kube2e/gateway/artifacts/helm.yaml
  test/kube2e/gloo/artifacts/helm.yaml
  test/kube2e/glooctl/artifacts/helm.yaml
  test/kube2e/gloomtls/artifacts/helm.yaml
  test/kube2e/helm/artifacts/helm.yaml
  test/kube2e/istio/README.md
  test/kube2e/istio/artifacts/automtls-helm.yaml
  test/kube2e/istio/artifacts/gloo-gateway-helm.yaml
  test/kube2e/istio/artifacts/helm.yaml
  test/kube2e/upgrade/artifacts/helm.yaml
Labels: keep pr updated

#9342 Bump go 1.22.2
  .github/workflows/pr.yaml
  .github/workflows/static-analysis.yaml
  .gitignore
  changelog/v1.17.0-beta21/bump-go.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
  ci/kind/setup-kind.sh
  cloudbuild-cache.yaml
  go.mod
  install/test/helm_test.go
  pkg/cliutil/input.go
  pkg/utils/syncutil/log_redactor.go
  projects/discovery/pkg/fds/updater.go
  projects/gateway/pkg/translator/aggregate_translator_test.go
  projects/gateway/pkg/translator/merge.go
  projects/gateway/pkg/validation/validator_test.go
  projects/gateway2/translator/plugins/utils/sort_objects.go
  projects/gloo/cli/pkg/cmd/upgrade/cmd.go
  projects/gloo/cli/pkg/printers/ratelimitconfig.go
  projects/gloo/pkg/api/compress/compress_test.go
  projects/gloo/pkg/plugins/hcm/plugin_test.go
  projects/gloo/pkg/plugins/kubernetes/serviceconverter/general_annotation_converter.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/translator/route_config_test.go
  projects/gloo/pkg/translator/ssl_configuration.go
  projects/gloo/pkg/translator/utils.go
  projects/gloo/pkg/upstreams/hybrid_client_test.go
  projects/gloo/pkg/utils/sort_routes_test.go
  projects/gloo/pkg/utils/validation/proxy_validation_test.go
  test/e2e/health_checks_test.go
  test/e2e/local_ratelimit_test.go
  test/gomega/matchers/benchmark_test.go
  test/helpers/routes.go
  test/helpers/scaled_snapshots.go
  test/helpers/scaled_snapshots_test.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/glooctl/check_test.go
Labels: keep pr updated

#9322 Refactor Makefile docker variant targets and fix for m1 machines
  .github/workflows/composite-actions/regression-tests/action.yaml
  Makefile
  changelog/v1.17.0-beta21/refactor-make.yaml
  ci/kind/setup-kind.sh
  projects/distroless/Dockerfile
Labels: keep pr updated

#9359 Bump envoy to 1.29.3-patch1
  Makefile
  changelog/v1.17.0-beta21/bump-envoy.yaml
  install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
  install/test/fixtures.go
  install/test/fixtures/envoy_config/bootstrap_extensions.yaml
  install/test/fixtures/envoy_config/custom_static_bootstrap.yaml
  install/test/fixtures/envoy_config/overload_manager.yaml
  install/test/fixtures/envoy_config/static_clusters.yaml
  install/test/fixtures/envoy_config/tcp_keepalive.yaml
  install/test/helm_test.go
Labels: keep pr updated

#9310 Switch separate Gloo Gateway xds to proxy syncer
  .github/workflows/pr.yaml
  changelog/v1.17.0-beta21/combine-xds-syncers.yaml
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/gateway/pkg/syncer/translator_syncer.go
  projects/gateway2/controller/start.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/values.go
  projects/gateway2/discovery/controller.go
  projects/gateway2/discovery/translator.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/helm/gloo-gateway/values.yaml
  projects/gateway2/proxy_syncer/proxy_syncer.go
  projects/gateway2/proxy_syncer/proxy_syncer_interface.go
  projects/gateway2/proxy_syncer/queue.go
  projects/gateway2/proxy_syncer/queue_test.go
  projects/gateway2/query/utils.go
  projects/gateway2/secrets/controller.go
  projects/gateway2/translator/backendref/types.go
  projects/gateway2/translator/backendref/types_test.go
  projects/gateway2/translator/gateway_translator.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/plugins/mirror/mirror_plugin.go
  projects/gateway2/translator/plugins/mirror/mirror_plugin_test.go
  projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go
  projects/gateway2/translator/testutils/outputs/http-routing-proxy.yaml
  projects/gateway2/translator/testutils/outputs/http-with-header-modifier-proxy.yaml
  projects/gateway2/translator/testutils/outputs/https-routing-proxy.yaml
  projects/gateway2/translator/translator_case_test.go
  projects/gateway2/xds/xds_syncer.go
  projects/gateway2/xds/xds_syncer_interface.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer_test.go
  projects/gloo/pkg/syncer/setup/proxy_cleanup.go
  projects/gloo/pkg/syncer/setup/proxy_cleanup_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/setup/start_func.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/translator/route_config.go
  projects/gloo/pkg/utils/translators.go
  projects/gloo/pkg/xds/cache.go
  projects/gloo/pkg/xds/cache_test.go
  projects/gloo/pkg/xds/node_hash.go
  projects/gloo/pkg/xds/node_hash_test.go
  projects/ingress/pkg/translator/translator_syncer.go
  projects/knative/pkg/translator/translator_syncer.go
  test/helpers/kube_dump.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/glooctl/glooctl_suite_test.go
  test/kube2e/gloomtls/gloo_mtls_suite_test.go
  test/kube2e/helm/helm_suite_test.go
  test/kube2e/ingress/ingress_suite_test.go
  test/kube2e/istio/artifacts/gloo-gateway-helm.yaml
  test/kube2e/istio/istio_suite_test.go
  test/kube2e/knative/knative_suite_test.go
  test/kube2e/upgrade/upgrade_suite_test.go
Labels: keep pr updated

#9361 1.16 bump: envoy-gloo and go (via cbuild) for http2 cont cve
  Makefile
  changelog/v1.16.10/envoy-gloo-cves.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
Labels: keep pr updated

#9362 1.15: Deps bump envoy and cloud builders
  Makefile
  changelog/v1.15.25/envoy-gloo-cves.yaml
  ci/cloudbuild/publish-artifacts.yaml
  ci/cloudbuild/run-tests.yaml
Labels: keep pr updated

#9366 kube/test: framework follow-ups
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.17.0-beta22/gg-kube-test-framework-part-2.yaml
  install/helm/gloo/templates/44-rbac.yaml
  pkg/utils/cmdutils/run_error.go
  pkg/utils/helmutils/client.go
  pkg/utils/helmutils/constants.go
  pkg/utils/kubeutils/kubectl/cli.go
  pkg/utils/kubeutils/pods.go
  pkg/utils/requestutils/curl/option.go
  pkg/utils/requestutils/curl/request.go
  pkg/utils/requestutils/curl/request_test.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/values.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gloo/cli/pkg/cmd/check-crds/root.go
  projects/gloo/cli/pkg/cmd/federation/register/register.go
  projects/gloo/cli/pkg/cmd/install/installer_test.go
  projects/gloo/cli/pkg/constants/constants.go
  test/kube2e/argocd/argocd_test.go
  test/kube2e/helm/artifacts/performance.yaml
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_suite_test.go
  test/kube2e/upgrade/upgrade_test.go
  test/kubernetes/e2e/features/deployer/gateway-parameters.yaml
  test/kubernetes/e2e/features/deployer/gateway_parameters.go
  test/kubernetes/e2e/framework.go
  test/kubernetes/e2e/k8sgateway/deployer_test.go
  test/kubernetes/e2e/k8sgateway/k8sgateway_suite_test.go
  test/kubernetes/e2e/k8sgateway/manifests/k8s-gateway-test-helm.yaml
  test/kubernetes/testutils/actions/glooctl/install.go
  test/kubernetes/testutils/assertions/deployments.go
  test/kubernetes/testutils/assertions/envoy.go
  test/kubernetes/testutils/assertions/provider.go
  test/kubernetes/testutils/operations/README.md
  test/kubernetes/testutils/operations/operator.go
  test/kubernetes/testutils/operations/operator_test.go
Labels: work in progress, keep pr updated

#9368 Fix virtualhostoptions rbac for k8s gateway
  changelog/v1.17.0-beta22/vhopts-rbac.yaml
  install/helm/gloo/templates/44-rbac.yaml
Labels: keep pr updated

#9374 Docs extproc 1.17 changes
  changelog/v1.17.0-beta22/doc-extproc-changes.yaml
  docs/content/guides/traffic_management/extproc/about.md
  docs/content/operations/upgrading/faq.md
Labels: keep pr updated

#9367 Always build and load sds standard image for tests
  Makefile
  changelog/v1.17.0-beta22/fix-glooctl-istio-inject.yaml
Labels: keep pr updated

#9377 [1.15.x] Gateway validation flake fix (#9119)
  changelog/v1.15.26/validation-test-flake-fix.yaml
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9376 [1.16.x] Gateway validation flake fix (#9119)
  changelog/v1.16.11/validation-test-flake-fix.yaml
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9371 Kubernetes Gateway API controller plumbing for VirtualHostOptions
  changelog/v1.17.0-beta22/vhopts-fix-controller.yaml
  projects/gateway2/controller/controller.go
  projects/gateway2/translator/listener/gateway_listener_translator.go
  projects/gateway2/translator/plugins/virtualhostoptions/query/query.go
Labels: keep pr updated

#9363 devel/pull-requests: Update documentation on PRs
  changelog/v1.17.0-beta23/pull-request-policy.yaml
  devel/contributing/pull-request-reviews.md
Labels: keep pr updated, release/1.17

#9385 kube2e/glooctl: fix invalid syntax
  changelog/v1.17.0-beta23/skip-glooctl-istio-test-attempt2.yaml
  test/kube2e/glooctl/istio_test.go
Labels: keep pr updated

#9388 Add route option e2e test
  changelog/v1.17.0-beta23/add-routeoption-e2e-test.yaml
  pkg/utils/kubeutils/kubectl/cli.go
  test/kube2e/helper/curl.go
  test/kubernetes/e2e/features/route_options/inputs/fault-injection-filter-extension.yaml
  test/kubernetes/e2e/features/route_options/inputs/fault-injection-targetref.yaml
  test/kubernetes/e2e/features/route_options/route_options.go
  test/kubernetes/e2e/k8sgateway/deployer_test.go
  test/kubernetes/e2e/k8sgateway/manifests/k8s-gateway-test-helm.yaml
  test/kubernetes/testutils/assertions/curl.go
Labels: keep pr updated

#9350 Bernie/kube dump logs
  changelog/v1.17.0-beta23/fix-kube-dumps-on-fail.yaml
  test/helpers/kube_dump.go
Labels: work in progress, keep pr updated

#9387 plugin/als: Access logging can be configured in multiple places this enables another level of it
  changelog/v1.17.0-beta23/http-listener-access-logs.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/als/als.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/options/als/als.proto
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/options/als/als.pb.go
  projects/gloo/pkg/plugins/als/converter.go
  projects/gloo/pkg/plugins/als/converters_test.go
  projects/gloo/pkg/plugins/als/plugin.go
  projects/gloo/pkg/plugins/als/plugin_test.go
Labels: keep pr updated

#9384 Bump golangci-lint for parity with CI and increase static analysis timeout
  .github/workflows/static-analysis.yaml
  .golangci.yaml
  Makefile
  changelog/v1.17.0-beta23/bump-linter.yaml.yaml
Labels: keep pr updated

#9397 Fix failure dump bugs
  changelog/v1.17.0-beta23/fix-envoy-dump-on-fail.yaml
  test/helpers/kube_dump.go
Labels: keep pr updated

#9395 tests/kube/e2e: Expand utilities, run tests multiple times on PRs
  .github/workflows/composite-actions/kubernetes-e2e-tests/action.yaml
  .github/workflows/pr-kubernetes-tests.yaml
  changelog/v1.17.0-beta23/cmd-data-race.yaml
  pkg/utils/kubeutils/dns.go
  pkg/utils/kubeutils/kubectl/cli.go
  pkg/utils/kubeutils/names.go
  projects/gloo/pkg/syncer/setup/controlplane.go
  test/kubernetes/e2e/features/route_options/route_options.go
  test/kubernetes/testutils/assertions/curl.go
Labels: keep pr updated

#9392 Fix: validation rejects kube US deletion
  changelog/v1.17.0-beta23/validate-kube-us-delete-fix.yaml
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
  projects/gloo/pkg/plugins/kubernetes/plugin.go
  projects/gloo/pkg/translator/translator.go
  projects/gloo/pkg/upstreams/kubernetes/conversions.go
  projects/gloo/pkg/upstreams/kubernetes/conversions_test.go
  projects/gloo/pkg/upstreams/kubernetes/upstream_client.go
  projects/gloo/pkg/validation/server.go
  projects/gloo/pkg/validation/server_test.go
Labels: keep pr updated

#9373 Add status syncer to fix RouteOptions statuses
  changelog/v1.17.0-beta24/add-status-syncer.yaml
  projects/gateway2/controller/start.go
  projects/gateway2/proxy_syncer/proxy_syncer.go
  projects/gateway2/status/status_syncer.go
  projects/gateway2/status/status_syncer_suite_test.go
  projects/gateway2/status/status_syncer_test.go
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/setup/start_func.go
  projects/gloo/pkg/syncer/translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  projects/gloo/pkg/utils/translators.go
  test/kubernetes/e2e/features/route_options/route_options.go
  test/kubernetes/testutils/assertions/status.go
Labels: keep pr updated

#9400 test/kube/e2e: introduce testify, create example suite
  changelog/v1.17.0-beta24/testify-e2e.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  test/kubernetes/e2e/example/README.md
  test/kubernetes/e2e/example/basic_installation_test.go
  test/kubernetes/e2e/example/complex_installation_test.go
  test/kubernetes/e2e/example/manifests/basic-example.yaml
  test/kubernetes/e2e/example/manifests/complex-example.yaml
  test/kubernetes/e2e/features/example/suite.go
  test/kubernetes/e2e/framework.go
  test/kubernetes/e2e/k8sgateway/deployer_test.go
  test/kubernetes/e2e/k8sgateway/k8sgateway_suite_test.go
  test/kubernetes/testutils/actions/glooctl/install.go
  test/kubernetes/testutils/assertions/curl.go
  test/kubernetes/testutils/assertions/deployments.go
  test/kubernetes/testutils/assertions/envoy.go
  test/kubernetes/testutils/assertions/glooctl.go
  test/kubernetes/testutils/assertions/objects.go
  test/kubernetes/testutils/assertions/provider.go
Labels: keep pr updated

#9406 Doc fixes for week of April 22, 2024
  changelog/v1.17.0-beta24/doc-fixes.yaml
  docs/Makefile
  docs/content/guides/integrations/service_mesh/istio.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: Type: Docs, keep pr updated

#9409 Turn off kubernetes gateway api integration by default
  .github/workflows/pr.yaml
  changelog/v1.17.0-beta24/disable-kube-gateway.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  install/test/k8sgateway_test.go
Labels: keep pr updated

#9405 test/kube/e2e: Expand deployer tests
  changelog/v1.17.0-beta24/e2e-tests-deployer.yaml
  pkg/utils/envoyutils/admincli/client.go
  pkg/utils/envoyutils/admincli/clusters.go
  projects/gloo/pkg/syncer/setup/controlplane.go
  test/kubernetes/e2e/README.md
  test/kubernetes/e2e/example/debug_logging_test.go
  test/kubernetes/e2e/example/error_logging_test.go
  test/kubernetes/e2e/example/manifests/basic-example.yaml
  test/kubernetes/e2e/example/manifests/complex-example.yaml
  test/kubernetes/e2e/example/manifests/debug-example.yaml
  test/kubernetes/e2e/example/manifests/error-example.yaml
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/example/suite.go
  test/kubernetes/e2e/features/route_options/suite.go
  test/kubernetes/e2e/features/route_options/types.go
  test/kubernetes/testutils/assertions/envoy.go
  test/kubernetes/testutils/assertions/provider.go
  test/kubernetes/testutils/gloogateway/clients.go
  test/services/envoy/instance.go
Labels: keep pr updated

#9411 Add indexes to k8s gateway translator test
  changelog/v1.17.0-beta24/fix-gw2-query-indexes.yaml
  projects/gateway2/translator/translator_case_test.go
Labels: keep pr updated

#9407 conformance test cleanup
  .github/workflows/composite-actions/kube-gateway-api-conformance-tests/action.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/pr.yaml
  .github/workflows/regression-tests.yaml
  Makefile
  changelog/v1.17.0-beta24/conformance-test-cleanup.yaml
  ci/kind/setup-kind.sh
  projects/gateway2/Makefile
  projects/gateway2/kind.sh
  projects/gateway2/tests/conformance/conformance_test.go
Labels: keep pr updated

#9417 protoc-gen-openapi: update to v0.2.2
  changelog/v1.17.0-beta24/update-protocgenopenapi.yaml
  go.mod
  go.sum
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableTcpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Proxy.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
  install/helm/gloo/crds/graphql.gloo.solo.io_v1beta1_GraphQLApi.yaml
Labels: keep pr updated

#9422 [1.15] fix: grpcJsonTranscoder Upstream is causing all the Routes to be on a warning state
  changelog/v1.15.26/fix-grpcjson-invalid-route.yaml
  projects/gloo/pkg/plugins/grpcjson/plugin.go
  projects/gloo/pkg/plugins/grpcjson/plugin_test.go
Labels: keep pr updated

#9421 [1.16] fix: grpcJsonTranscoder Upstream is causing all the Routes to be on a warning state
  changelog/v1.16.11/fix-grpcjson-invalid-route.yaml
  projects/gloo/pkg/plugins/grpcjson/plugin.go
  projects/gloo/pkg/plugins/grpcjson/plugin_test.go
Labels: keep pr updated

#9423 gateway v2: set hostnames in RouteContext for plugins
  changelog/v1.17.0-beta24/delegate-host.yaml
  projects/gateway2/translator/httproute/delegation.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/plugins/plugins.go
Labels: keep pr updated

#9415 test/e2e: add debugging guide for new framework
  changelog/v1.17.0-beta25/e2e-dbg.yaml
  test/kubernetes/e2e/README.md
  test/kubernetes/e2e/debugging.md
Labels: keep pr updated
