Repository kgateway-dev/kgateway, pull requests merged in 2024-07, with the labels that each got.

#9705 Custom liveness params
  changelog/v1.18.0-beta5/custom-liveness-port.yaml
  pkg/utils/probes/healthz.go
  pkg/utils/probes/probes.go
  pkg/utils/probes/probes_suite_test.go
  pkg/utils/probes/probes_test.go
Labels: keep pr updated

#9717 gateway2: misc fixes for AI extension
  changelog/v1.18.0-beta5/ai-uds-fixes.yaml
  docs/content/reference/values.txt
  install/helm/gloo/crds/gateway.gloo.solo.io_crds.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/43-gatewayparameters.yaml
  install/helm/gloo/values-template.yaml
  install/test/k8sgateway_test.go
  projects/gateway2/api/v1alpha1/gateway_parameters.proto
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/deployer/merge.go
  projects/gateway2/deployer/values.go
  projects/gateway2/deployer/values_helpers.go
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.equal.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.go
  projects/gateway2/pkg/api/gateway.gloo.solo.io/v1alpha1/gateway_parameters.pb.hash.go
Labels: keep pr updated

#9721 gloo/api: add missing protos and fields
  changelog/v1.18.0-beta5/add-missing-proto.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/service/ext_proc/v3/external_processor.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/type/v3/http_status.proto.sk.md
  docs/data/ProtoMap.yaml
  projects/envoyinit/hack/filter_types/filter_types.gen.go
  projects/gloo/api/external/envoy/annotations/deprecation.proto
  projects/gloo/api/external/envoy/service/ext_proc/v3/external_processor.proto
  projects/gloo/api/external/envoy/type/v3/http_status.proto
  projects/gloo/pkg/api/external/envoy/annotations/deprecation.pb.go
  projects/gloo/pkg/api/external/envoy/service/ext_proc/v3/external_processor.pb.clone.go
  projects/gloo/pkg/api/external/envoy/service/ext_proc/v3/external_processor.pb.equal.go
  projects/gloo/pkg/api/external/envoy/service/ext_proc/v3/external_processor.pb.go
  projects/gloo/pkg/api/external/envoy/service/ext_proc/v3/external_processor.pb.hash.go
  projects/gloo/pkg/api/external/envoy/type/v3/http_status.pb.clone.go
  projects/gloo/pkg/api/external/envoy/type/v3/http_status.pb.equal.go
  projects/gloo/pkg/api/external/envoy/type/v3/http_status.pb.go
  projects/gloo/pkg/api/external/envoy/type/v3/http_status.pb.hash.go
Labels: keep pr updated

#9719 [1.13] cli: Infer gloo deploy name
  changelog/v1.13.39/infer-gloo-deploy-name.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/check/root_test.go
  projects/gloo/cli/pkg/common/get.go
  projects/gloo/cli/pkg/helpers/clients.go
  projects/gloo/cli/pkg/xdsinspection/get_last_config.go
Labels: keep pr updated

#9725 [1.16] cli: Infer gloo deploy name && optimize glooctl check
  changelog/v1.16.18/infer-gloo-deploy-name.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/common/get.go
  projects/gloo/cli/pkg/helpers/clients.go
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/cli/pkg/printers/upstream_test.go
  projects/gloo/cli/pkg/xdsinspection/get_last_config.go
  test/kube2e/glooctl/check_test.go
Labels: keep pr updated

#9723 [1.14] cli: Infer gloo deploy name
  changelog/v1.14.32/infer-gloo-deploy-name-114.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/common/get.go
  projects/gloo/cli/pkg/helpers/clients.go
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/cli/pkg/printers/upstream_test.go
  projects/gloo/cli/pkg/xdsinspection/get_last_config.go
Labels: keep pr updated

#9727 cli: Infer gloo deploy name
  changelog/v1.18.0-beta6/infer-gloo-deploy-name.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/common/proxy.go
  projects/gloo/cli/pkg/helpers/clients.go
  projects/gloo/cli/pkg/kubegatewayutils/detect.go
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/cli/pkg/printers/upstream_test.go
  projects/gloo/cli/pkg/xdsinspection/get_last_config.go
Labels: keep pr updated

#9724 [1.15] cli: Infer gloo deploy name && optimize glooctl check
  changelog/v1.15.30/infer-gloo-deploy-name.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/common/get.go
  projects/gloo/cli/pkg/helpers/clients.go
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/cli/pkg/printers/upstream_test.go
  projects/gloo/cli/pkg/xdsinspection/get_last_config.go
  test/kube2e/glooctl/check_test.go
Labels: keep pr updated

#9726 [1.17] cli: Infer gloo deploy name && optimize glooctl check
  changelog/v1.17.0-rc10/optimize-glooctl-check.yaml
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/common/proxy.go
  projects/gloo/cli/pkg/helpers/clients.go
  projects/gloo/cli/pkg/kubegatewayutils/detect.go
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/cli/pkg/printers/upstream_test.go
  projects/gloo/cli/pkg/xdsinspection/get_last_config.go
  test/kube2e/glooctl/check_test.go
Labels: keep pr updated

#9742 fix changelog
  changelog/v1.17.0-rc11/kubebuilder.yaml
  changelog/v1.17.0-rc11/optimize-glooctl-check.yaml
  changelog/v1.17.0-rc11/skipci.yaml
Labels: keep pr updated

#9745 Fix GatewayParameters selfManaged
  changelog/v1.18.0-beta7/fix-self-managed.yaml
  install/helm/gloo/crds/gateway.gloo.solo.io_gatewayparameters.yaml
  projects/gateway2/api/v1alpha1/gateway_parameters_types.go
Labels: keep pr updated

#9734 Move gloomtls tests to new framework
  .github/workflows/nightly-tests.yaml
  .github/workflows/pr-kubernetes-tests.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.18.0-beta7/gloomtls-e2e-tests.yaml
  test/kube2e/README.md
  test/kubernetes/e2e/features/gloomtls/gloomtls_edge_suite.go
  test/kubernetes/e2e/features/gloomtls/testdata/edge_resources.yaml
  test/kubernetes/e2e/features/gloomtls/testdata/setup.yaml
  test/kubernetes/e2e/features/gloomtls/types.go
  test/kubernetes/e2e/tests/gloomtls_edge_api_test.go
  test/kubernetes/e2e/tests/gloomtls_edge_api_tests.go
  test/kubernetes/e2e/tests/manifests/gloomtls-edge-gateway-test-helm.yaml
Labels: keep pr updated

#9747 test/kube: namespaces from kubectl
  pkg/utils/kubeutils/kubectl/cli.go
  test/kubernetes/e2e/test.go
Labels: keep pr updated

#9750 Fix HTTPS listener aggregation with kube gateway
  changelog/v1.18.0-beta8/listeners-reuse-ports.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/listener/gateway_listener_translator.go
  projects/gateway2/translator/testutils/inputs/multiple-listeners-http-routing/gateway.yaml
  projects/gateway2/translator/testutils/inputs/multiple-listeners-https-routing/gateway.yaml
  projects/gateway2/translator/testutils/outputs/multiple-listeners-http-routing-proxy.yaml
  projects/gateway2/translator/testutils/outputs/multiple-listeners-https-routing-proxy.yaml
Labels: keep pr updated

#9751 [1.17] Migrate utils from `test/kube2e` to `test/kubernetes`
  changelog/v1.17.0-rc12/test-utils-debug.yaml
  pkg/utils/fsutils/fsutils.go
  pkg/utils/helmutils/client.go
  pkg/utils/helmutils/constants.go
  pkg/utils/kubeutils/kubectl/cli.go
  test/gomega/assertions/stats.go
  test/kube2e/helper/http_echo.go
  test/kube2e/helper/kube.go
  test/kube2e/helper/testserver.go
  test/kube2e/util.go
  test/kubernetes/e2e/README.md
  test/kubernetes/e2e/defaults/defaults.go
  test/kubernetes/e2e/defaults/testdata/http_echo.yaml
  test/kubernetes/e2e/defaults/testdata/nginx_pod.yaml
  test/kubernetes/e2e/defaults/testdata/tcp_echo.yaml
  test/kubernetes/e2e/example/debug_logging_test.go
  test/kubernetes/e2e/test.go
  test/kubernetes/e2e/tests/automtls_istio_edge_api_test.go
  test/kubernetes/e2e/tests/automtls_istio_test.go
  test/kubernetes/e2e/tests/edge_gw_test.go
  test/kubernetes/e2e/tests/glooctl_istio_inject_test.go
  test/kubernetes/e2e/tests/istio_edge_api_test.go
  test/kubernetes/e2e/tests/istio_regression_test.go
  test/kubernetes/e2e/tests/k8s_gw_istio_test.go
  test/kubernetes/e2e/tests/k8s_gw_minimal_default_gatewayparameters_test.go
  test/kubernetes/e2e/tests/k8s_gw_no_validation_test.go
  test/kubernetes/e2e/tests/k8s_gw_test.go
  test/kubernetes/testutils/assertions/deployments.go
  test/kubernetes/testutils/assertions/glooctl.go
  test/kubernetes/testutils/helper/docker/Dockerfile
  test/kubernetes/testutils/helper/install.go
  test/kubernetes/testutils/helper/util.go
Labels: keep pr updated

#9752 [1.17] Fix HTTPS listener aggregation with kube gateway
  changelog/v1.17.0-rc12/listeners-reuse-ports.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/listener/gateway_listener_translator.go
  projects/gateway2/translator/testutils/inputs/multiple-listeners-http-routing/gateway.yaml
  projects/gateway2/translator/testutils/inputs/multiple-listeners-https-routing/gateway.yaml
  projects/gateway2/translator/testutils/outputs/multiple-listeners-http-routing-proxy.yaml
  projects/gateway2/translator/testutils/outputs/multiple-listeners-https-routing-proxy.yaml
Labels: keep pr updated

#9759 make: bump envoy for 1.30.4
  Makefile
  changelog/v1.17.0/envoy-1.30.4.yaml
Labels: keep pr updated

#9735 Fix/enforce regex inutils
  changelog/v1.18.0-beta8/cors-regex-safety.yaml
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  pkg/utils/regexutils/regex.go
  projects/gloo/pkg/plugins/cors/plugin.go
  projects/gloo/pkg/plugins/cors/route_plugin_test.go
  projects/gloo/pkg/plugins/cors/vhost_plugin_test.go
Labels: keep pr updated

#9763 1.16: Fix/enforce regex inutils (#9735)
  changelog/v1.16.18/cors-regex-safety.yaml
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  pkg/utils/regexutils/regex.go
  projects/gloo/pkg/plugins/cors/plugin.go
  projects/gloo/pkg/plugins/cors/route_plugin_test.go
  projects/gloo/pkg/plugins/cors/vhost_plugin_test.go
Labels: keep pr updated

#9762 1.17: Fix/enforce regex inutils (#9735)
  changelog/v1.17.0/cors-regex-safety.yaml
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  pkg/utils/regexutils/regex.go
  projects/gloo/pkg/plugins/cors/plugin.go
  projects/gloo/pkg/plugins/cors/route_plugin_test.go
  projects/gloo/pkg/plugins/cors/vhost_plugin_test.go
Labels: keep pr updated

#9760 Flatten resources returned by Admin endpoint
  changelog/v1.18.0-beta8/admin-endpoint-flatten.yaml
  projects/gateway2/wellknown/gwapi.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  projects/gloo/pkg/servers/iosnapshot/convert.go
  projects/gloo/pkg/servers/iosnapshot/convert_test.go
  projects/gloo/pkg/servers/iosnapshot/format.go
  projects/gloo/pkg/servers/iosnapshot/history.go
  projects/gloo/pkg/servers/iosnapshot/history_test.go
  test/gomega/assertions/structs.go
  test/helpers/virtual_services_test.go
  test/testutils/http_client_test.go
  test/testutils/http_request_test.go
Labels: keep pr updated

#9770 Nf/cors
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.go
  test/e2e/cors_test.go
Labels: keep pr updated

#9769 docs: mark 1.17 as latest stable
  .github/workflows/trivy-analysis-scheduled.yaml
  .trivyignore
  Makefile
  changelog/v1.18.0-beta8/1-17-ga.yaml
  docs/active_versions.json
Labels: keep pr updated

#9766 Admin endpoint: return more resources
  changelog/v1.18.0-beta8/admin-endpoint-resources.yaml
  projects/gateway2/api/v1alpha1/groupversion_info.go
  projects/gloo/pkg/servers/iosnapshot/convert.go
  projects/gloo/pkg/servers/iosnapshot/history.go
  projects/gloo/pkg/servers/iosnapshot/history_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
Labels: keep pr updated

#9773 Docs: 1.17 release notes
  changelog/v1.18.0-beta8/docs-relnotes.yaml
  docs/content/operations/upgrading/faq.md
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n+1.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  docs/content/static/content/version_geoss_n-1_minor.md
  docs/content/static/content/version_geoss_n-2_minor.md
Labels: Type: Docs, keep pr updated, release/1.17

#9771 Test/xds snap ctx aware and leak detector
  changelog/v1.18.0-beta8/devmode-cancel-xds.yaml
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  test/gomega/assertions/assertions_suite_test.go
  test/gomega/assertions/goroutines.go
  test/gomega/assertions/goroutines_test.go
  test/helpers/input_resources.go
  test/helpers/util.go
  test/helpers/util_test.go
  test/kube2e/helper/curl.go
  test/kube2e/helper/curl_test.go
Labels: keep pr updated

#9778 Update `docs-gen.yaml` to scan from 1.14+
  .github/workflows/docs-gen.yaml
  changelog/v1.18.0-beta9/update-docs-gen-scanner-min-version-1.14.yaml
Labels: keep pr updated

#9722 LLM Api
  changelog/v1.18.0-beta9/ai-gateway-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ai/ai.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/upstream.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gloo/api/v1/enterprise/options/ai/ai.proto
  projects/gloo/api/v1/options.proto
  projects/gloo/api/v1/upstream.proto
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ai/ai.pb.hash.go
  projects/gloo/pkg/api/v1/options.pb.clone.go
  projects/gloo/pkg/api/v1/options.pb.equal.go
  projects/gloo/pkg/api/v1/options.pb.go
  projects/gloo/pkg/api/v1/options.pb.hash.go
  projects/gloo/pkg/api/v1/upstream.pb.clone.go
  projects/gloo/pkg/api/v1/upstream.pb.equal.go
  projects/gloo/pkg/api/v1/upstream.pb.go
  projects/gloo/pkg/api/v1/upstream.pb.hash.go
  projects/gloo/pkg/plugins/static/plugin.go
Labels: keep pr updated

#9783 Backport 1.17: Test/xds snap ctx aware and leak detector (#9771)
  changelog/v1.17.1/devmode-cancel-xds.yaml
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/translator_syncer.go
  test/gomega/assertions/assertions_suite_test.go
  test/gomega/assertions/goroutines.go
  test/gomega/assertions/goroutines_test.go
  test/helpers/input_resources.go
  test/helpers/util.go
  test/helpers/util_test.go
  test/kube2e/helper/curl.go
  test/kube2e/helper/curl_test.go
Labels: keep pr updated

#9757 cors: clarify behavior when properties are defined on RouteOptions and VirtualHostOptions
  changelog/v1.18.0-beta9/cors.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk.md
  projects/gloo/api/v1/options.proto
  projects/gloo/pkg/api/v1/options.pb.go
  test/e2e/cors_test.go
Labels: keep pr updated

#9790 Add `AssertEventualCurlError`
  changelog/v1.18.0-beta10/curlEventuallyError.yaml
  test/kubernetes/testutils/assertions/curl.go
Labels: keep pr updated

#9795 Admin server backports [1.17]
  changelog/v1.17.1/admin-server-updates.yaml
  projects/gateway2/api/v1alpha1/groupversion_info.go
  projects/gateway2/controller/start.go
  projects/gateway2/extensions/extensions.go
  projects/gateway2/wellknown/gwapi.go
  projects/gloo/pkg/plugins/utils/update_upstream_spec_test.go
  projects/gloo/pkg/servers/iosnapshot/convert.go
  projects/gloo/pkg/servers/iosnapshot/convert_test.go
  projects/gloo/pkg/servers/iosnapshot/format.go
  projects/gloo/pkg/servers/iosnapshot/history.go
  projects/gloo/pkg/servers/iosnapshot/history_test.go
  projects/gloo/pkg/servers/iosnapshot/resources.go
  projects/gloo/pkg/syncer/setup/extensions.go
  projects/gloo/pkg/syncer/setup/extensions_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/translator_syncer_test.go
  test/gomega/assertions/structs.go
  test/helpers/virtual_services_test.go
  test/testutils/http_client_test.go
  test/testutils/http_request_test.go
Labels: keep pr updated

#9796 Doc fixes
  .github/ISSUE_TEMPLATE/DOCS-ISSUE.yml
  changelog/v1.18.0-beta10/doc-fixes.yaml
  docs/content/operations/upgrading/faq.md
  docs/content/static/content/version_geoss_n+1.md
Labels: keep pr updated

#9780 Docs for Google Cloud Platform
  changelog/v1.18.0-beta10/docs-cloud-run.yaml
  docs/content/guides/traffic_management/destination_types/google-cloud-run.md
Labels: Type: Docs, keep pr updated

#9801 [v1.17.x] Backport Docs for Google Cloud Platform
  changelog/v1.17.1/docs-cloud-run.yaml
  docs/content/guides/traffic_management/destination_types/google-cloud-run.md
  docs/content/operations/upgrading/faq.md
Labels: Type: Docs, keep pr updated

#9799 Glooctl grpc Upstream output in augmented status
  changelog/v1.18.0-beta10/glooctl-grpc-function-name-output.yaml
  projects/gloo/cli/pkg/cmd/create/upstream.go
  projects/gloo/cli/pkg/cmd/get/upstream.go
  projects/gloo/cli/pkg/common/create.go
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/cli/pkg/printers/upstream_test.go
Labels: keep pr updated

#9804 1.17 - Glooctl grpc Upstream output in augmented status
  changelog/v1.17.1/glooctl-grpc-function-name-output.yaml
  projects/gloo/cli/pkg/cmd/create/upstream.go
  projects/gloo/cli/pkg/cmd/get/upstream.go
  projects/gloo/cli/pkg/common/create.go
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/cli/pkg/printers/upstream_test.go
Labels: keep pr updated

#9806 1.15 - Glooctl grpc fix augment status
  changelog/v1.15.30/glooctl-grpc-function-name-output.yaml
  projects/gloo/cli/pkg/cmd/create/upstream.go
  projects/gloo/cli/pkg/cmd/get/upstream.go
  projects/gloo/cli/pkg/common/create.go
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/cli/pkg/printers/upstream_test.go
Labels: keep pr updated

#9807 1.14 - Glooctl grpc fix augment status
  changelog/v1.14.32/glooctl-grpc-function-name-output.yaml
  projects/gloo/cli/pkg/cmd/create/upstream.go
  projects/gloo/cli/pkg/cmd/get/upstream.go
  projects/gloo/cli/pkg/common/create.go
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/cli/pkg/printers/upstream_test.go
Labels: keep pr updated

#9805 1.16 - Glooctl grpc fix augment status
  changelog/v1.16.19/glooctl-grpc-function-name-output.yaml
  projects/gloo/cli/pkg/cmd/create/upstream.go
  projects/gloo/cli/pkg/cmd/get/upstream.go
  projects/gloo/cli/pkg/common/create.go
  projects/gloo/cli/pkg/printers/upstream.go
  projects/gloo/cli/pkg/printers/upstream_test.go
Labels: keep pr updated

#9809 gateway2/delegation: fix extraneous route arising from invalid child rule
  changelog/v1.18.0-beta11/deleg-fix-6621.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/httproute/delegation_helpers.go
  projects/gateway2/translator/testutils/inputs/delegation/bug-6621.yaml
  projects/gateway2/translator/testutils/outputs/delegation/bug-6621.yaml
Labels: keep pr updated

#9812 gateway2/delegation: resolve comments from 739b0e950
  changelog/v1.18.0-beta11/deleg-fix-6621-2.yaml
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/httproute/delegation_helpers.go
  projects/gateway2/translator/testutils/inputs/delegation/bug-6621.yaml
Labels: keep pr updated

#9808 gateway2/delegation: fix extraneous route arising from invalid child rule
  changelog/v1.17.2/deleg-fix-6621.yaml
  projects/gateway2/query/delegation.go
  projects/gateway2/translator/gateway_translator_test.go
  projects/gateway2/translator/testutils/inputs/delegation/bug-6621.yaml
  projects/gateway2/translator/testutils/outputs/delegation/bug-6621.yaml
Labels: keep pr updated

#9471 k8s gateway extensions: allow customizing translator
  changelog/v1.18.0-beta11/custom-gwclass-translation.yaml
  projects/gateway2/controller/controller.go
  projects/gateway2/controller/controller_suite_test.go
  projects/gateway2/controller/gw_controller_test.go
  projects/gateway2/controller/start.go
  projects/gateway2/extensions/extensions.go
  projects/gateway2/proxy_syncer/proxy_syncer.go
  projects/gloo/pkg/bootstrap/opts.go
Labels: keep pr updated

#9817 Ignore false positive istio cves
  .trivyignore
  changelog/v1.18.0-beta11/ignore-false-positive-istio-cve.yaml
Labels: keep pr updated

#9820 Sh/remove history managed fields part2
  changelog/v1.18.0-beta11/history-part3.yaml
  projects/gloo/pkg/servers/admin/server.go
  projects/gloo/pkg/servers/iosnapshot/convert.go
  projects/gloo/pkg/servers/iosnapshot/format.go
  projects/gloo/pkg/servers/iosnapshot/history.go
  projects/gloo/pkg/servers/iosnapshot/history_test.go
  test/gomega/matchers/custom_resource.go
Labels: keep pr updated

#9811 Remove old gloomtls and glooctl kube2e tests
  .github/workflows/nightly-tests.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.18.0-beta11/remove-old-glooctl-gloomtls-tests.yaml
  test/kube2e/glooctl/artifacts/helm.yaml
  test/kube2e/glooctl/check_crds_test.go
  test/kube2e/glooctl/check_test.go
  test/kube2e/glooctl/debug_test.go
  test/kube2e/glooctl/glooctl_suite_test.go
  test/kube2e/glooctl/petstore_peerauth_permissive.yaml
  test/kube2e/glooctl/petstore_peerauth_strict.yaml
  test/kube2e/glooctl/reject-me-too.yaml
  test/kube2e/glooctl/reject-me.yaml
  test/kube2e/gloomtls/artifacts/helm.yaml
  test/kube2e/gloomtls/gloo_mtls_suite_test.go
  test/kube2e/gloomtls/gloo_mtls_test.go
  test/kubernetes/e2e/defaults/defaults.go
  test/kubernetes/e2e/features/glooctl/get_proxy_suite.go
  test/kubernetes/e2e/features/glooctl/testdata/backend.yaml
  test/kubernetes/e2e/features/glooctl/testdata/upstream.yaml
  test/kubernetes/e2e/features/glooctl/types.go
  test/kubernetes/e2e/features/gloomtls/gloomtls_edge_suite.go
  test/kubernetes/e2e/features/gloomtls/testdata/edge_resources.yaml
  test/kubernetes/e2e/features/gloomtls/testdata/setup.yaml
  test/kubernetes/e2e/features/gloomtls/types.go
Labels: keep pr updated

#9744 tests: Set helm history-max to zero (unlimited) and other fixes for enterprise tests
  changelog/v1.18.0-beta11/set-max-history.yaml
  pkg/utils/requestutils/curl/option.go
  test/kube2e/argocd/argocd_test.go
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/helm/helm_test.go
  test/kube2e/upgrade/upgrade_test.go
  test/kube2e/util.go
  test/kubernetes/testutils/helper/install.go
Labels: keep pr updated

#9825 Update documentation with status code behaviour
  changelog/v1.18.0-beta12/opentelemetry-status-code-documentation.yaml
  docs/content/guides/observability/tracing/otel.md
Labels: keep pr updated

#9824 Doc fixes
  changelog/v1.18.0-beta12/doc-fixes.yaml
  docs/content/guides/security/auth/extauth/apikey_auth/_index.md
  docs/content/guides/traffic_management/destination_types/grpc/grpc-transcoding.md
  docs/content/guides/traffic_management/destination_types/grpc/simple-routing.md
Labels: keep pr updated

#9831 Add documentation on trivy scans
  changelog/v1.18.0-beta12/trivy-scan-documentation.yaml
  devel/security/README.md
Labels: keep pr updated

#9821 Transformation, add MergeJsonKeys API/functionality
  Makefile
  changelog/v1.18.0-beta12/bump-envoy.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/transformation/transformation.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableTcpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/api/v1/options/transformation/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.hash.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.clone.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.hash.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/transformation/plugin_test.go
  test/e2e/staged_transformation_test.go
Labels: keep pr updated

#9797 admin/history: expand implementation and tests
  .github/workflows/static-analysis.yaml
  changelog/v1.18.0-beta12/history-part2.yaml
  docs/content/operations/debugging_gloo/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/kube/wellknown/types.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/servers/admin/server.go
  projects/gloo/pkg/servers/iosnapshot/convert.go
  projects/gloo/pkg/servers/iosnapshot/format.go
  projects/gloo/pkg/servers/iosnapshot/history.go
  projects/gloo/pkg/servers/iosnapshot/history_test.go
  projects/gloo/pkg/servers/iosnapshot/resources.go
  projects/gloo/pkg/servers/iosnapshot/response.go
  projects/gloo/pkg/servers/iosnapshot/response_test.go
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  test/gomega/matchers/custom_resource.go
  test/gomega/matchers/custom_resource_test.go
  test/gomega/matchers/object.go
Labels: keep pr updated

#9837 Remove unneeded cat calls from our docs
  changelog/v1.18.0-beta12/remove-unneeded-cat.yaml
  docs/content/guides/dev/example-proxy-controller.txt
  docs/content/guides/graphql/getting_started/local_executor.md
  docs/content/guides/graphql/getting_started/remote_executor.md
  docs/content/guides/graphql/getting_started/secure_api.md
  docs/content/guides/graphql/getting_started/simple_discovery.md
  docs/content/guides/graphql/resolver_config.md
  docs/content/guides/integrations/cert_manager/_index.md
  docs/content/guides/integrations/ingress/_index.md
  docs/content/guides/security/csrf/_index.md
  docs/content/guides/security/rate_limiting/enterprise/_index.md
  docs/content/installation/advanced_configuration/session_affinity.md
  docs/content/installation/enterprise/_index.md
  docs/content/installation/gateway/kubernetes/_index.md
  docs/content/installation/platform_configuration/cluster_setup.md
  docs/content/installation/preparation.md
Labels: keep pr updated
