Repository kgateway-dev/kgateway, pull requests merged in 2024-02, with the labels that each got.

#9100 api: Add retryPolicy to PassThroughGrpc authconfig
  changelog/v1.17.0-beta6/grpc-passthrough-retry.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#9128 fix nightly compilation failure
  Makefile
  changelog/v1.17.0-beta7/fix-nightly-gw2.yaml
Labels: keep pr updated

#9102 Set `DISABLE_ENVOY` to disable running envoy as part of istio integration
  changelog/v1.17.0-beta7/add-disable-envoy-env.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  projects/gloo/cli/pkg/cmd/istio/sidecars/istio1.7-1.19.go
  projects/sds/pkg/run/run_main.go
  test/kube2e/README.md
  test/kube2e/istio/README.md
Labels: keep pr updated

#9130 Correct the extauth grpc passthroughauth retryproto comment
  changelog/v1.17.0-beta7/update-retry-proto-comment.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
Labels: keep pr updated

#9125 Istio X Forwarded Host toggle
  changelog/v1.17.0-beta7/istio-x-forwarded-host-toggle.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/compressed_proxy_spec.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/disabled_gateway.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/enable_rest_eds_and_gloo_mtls.yaml
  install/test/fixtures/settings/gateway_circuit_breakers.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/gateway_validation.yaml
  install/test/fixtures/settings/graphql_fds_disabled.yaml
  install/test/fixtures/settings/isolate_virtual_hosts_by_ssl_config.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/ratelimit_server.yaml
  install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/fixtures/settings/set_regex_max_program_size_default.yaml
  install/test/fixtures/settings/set_secretSettings_in_settings.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/fixtures/settings/uds_disabled.yaml
  install/test/fixtures/settings/watched_discovery_labels.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/plugins/istio_integration/plugin.go
  projects/gloo/pkg/plugins/istio_integration/plugin_test.go
Labels: keep pr updated

#9131 Revert mock update
  Makefile
  ci/tools.go
  docs/content/static/content/osa_provided.md
  docs/examples/grpc-json-transcoding/bookstore/go.sum
  docs/examples/grpc-passthrough-auth/go.sum
  example/proxycontroller/go.sum
  go.mod
  go.sum
  pkg/listers/mocks/mock_listers.go
  pkg/utils/selectionutils/mocks/mock_virtual_service.go
  pkg/utils/selectionutils/virtual_service_test.go
  projects/gateway/pkg/mocks/mock_gateway_client.go
  projects/gateway/pkg/mocks/mock_route_table_client.go
  projects/gateway/pkg/mocks/mock_v1/mock_gateway_client.go
  projects/gateway/pkg/mocks/mock_v1/mock_virtual_service_client.go
  projects/gateway/pkg/mocks/mock_virtual_service_client.go
  projects/gateway/pkg/syncer/translator_syncer_test.go
  projects/gateway/pkg/translator/mocks/mock_translator.go
  projects/gateway2/translator/plugins/mirror/mirror_plugin_test.go
  projects/gateway2/translator/plugins/mirror/mocks/mock_queries.go
  projects/gloo/cli/pkg/cmd/install/installer_test.go
  projects/gloo/cli/pkg/cmd/install/mocks/mock_helm_client.go
  projects/gloo/cli/pkg/cmd/install/mocks/mock_helm_installation.go
  projects/gloo/cli/pkg/cmd/install/mocks/mock_helm_release_list.go
  projects/gloo/cli/pkg/cmd/install/mocks/mock_helm_uninstallation.go
  projects/gloo/cli/pkg/cmd/install/uninstall_test.go
  projects/gloo/cli/pkg/cmd/version/mocks/mock_watcher.go
  projects/gloo/cli/pkg/cmd/version/version_test.go
  projects/gloo/pkg/bootstrap/clients/vault/auth_test.go
  projects/gloo/pkg/bootstrap/clients/vault/client_test.go
  projects/gloo/pkg/bootstrap/clients/vault/mocks/mock_auth.go
  projects/gloo/pkg/bootstrap/clients/vault/renewal_test.go
  projects/gloo/pkg/discovery/discovery_test.go
  projects/gloo/pkg/discovery/mocks/mock_discovery.go
  projects/gloo/pkg/mocks/mock_artifact_client.go
  projects/gloo/pkg/mocks/mock_endpoint_client.go
  projects/gloo/pkg/mocks/mock_proxy_client.go
  projects/gloo/pkg/mocks/mock_secret_client.go
  projects/gloo/pkg/mocks/mock_settings_client.go
  projects/gloo/pkg/mocks/mock_upstream_client.go
  projects/gloo/pkg/plugins/consul/eds_test.go
  projects/gloo/pkg/plugins/consul/mocks/dnsresolver_mock.go
  projects/gloo/pkg/plugins/consul/plugin_test.go
  projects/gloo/pkg/plugins/kubernetes/eds_test.go
  projects/gloo/pkg/plugins/kubernetes/mocks/kubesharedfactory_mock.go
  projects/gloo/pkg/plugins/tcp/plugin_test.go
  projects/gloo/pkg/translator/performance_test.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/upstreams/consul/consul_client_test.go
  projects/gloo/pkg/upstreams/consul/mocks/mock_consul_client.go
  projects/gloo/pkg/upstreams/consul/mocks/mock_watcher.go
  projects/gloo/pkg/upstreams/consul/upstream_client_test.go
  projects/gloo/pkg/upstreams/hybrid_client_test.go
  projects/gloo/pkg/utils/mocks/mock_ssl.go
  projects/gloo/pkg/validation/server_test.go
  test/mocks/cache/corecache.go
  test/mocks/gloo/validation_client.go
  test/mocks/kubernetes/kubeinterface.go
Labels: keep pr updated

#9133 Toggle x forwarded host [1.15]
  changelog/v1.15.23/istio-x-forwarded-host-toggle.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/compressed_proxy_spec.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/disabled_gateway.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/enable_rest_eds_and_gloo_mtls.yaml
  install/test/fixtures/settings/gateway_circuit_breakers.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/gateway_validation.yaml
  install/test/fixtures/settings/graphql_fds_disabled.yaml
  install/test/fixtures/settings/isolate_virtual_hosts_by_ssl_config.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/ratelimit_server.yaml
  install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/fixtures/settings/set_regex_max_program_size_default.yaml
  install/test/fixtures/settings/set_secretSettings_in_settings.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/fixtures/settings/uds_disabled.yaml
  install/test/fixtures/settings/watched_discovery_labels.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/plugins/istio_integration/plugin.go
  projects/gloo/pkg/plugins/istio_integration/plugin_test.go
Labels: keep pr updated

#9134 Toggle x forwarded host [1.16]
  changelog/v1.16.4/istio-x-forwarded-host-toggle.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/18-settings.yaml
  install/helm/gloo/values-template.yaml
  install/test/fixtures/settings/compressed_proxy_spec.yaml
  install/test/fixtures/settings/consul_config_upstream_discovery.yaml
  install/test/fixtures/settings/consul_config_values.yaml
  install/test/fixtures/settings/disable_kubernetes_destinations.yaml
  install/test/fixtures/settings/disable_proxy_garbage_collection.yaml
  install/test/fixtures/settings/disabled_gateway.yaml
  install/test/fixtures/settings/enable_default_credentials.yaml
  install/test/fixtures/settings/enable_rest_eds.yaml
  install/test/fixtures/settings/enable_rest_eds_and_gloo_mtls.yaml
  install/test/fixtures/settings/gateway_circuit_breakers.yaml
  install/test/fixtures/settings/gateway_settings.yaml
  install/test/fixtures/settings/gateway_validation.yaml
  install/test/fixtures/settings/graphql_fds_disabled.yaml
  install/test/fixtures/settings/isolate_virtual_hosts_by_ssl_config.yaml
  install/test/fixtures/settings/ratelimit_descriptors.yaml
  install/test/fixtures/settings/ratelimit_server.yaml
  install/test/fixtures/settings/read_gateways_from_all_namespaces.yaml
  install/test/fixtures/settings/set_regex_max_program_size.yaml
  install/test/fixtures/settings/set_regex_max_program_size_default.yaml
  install/test/fixtures/settings/set_secretSettings_in_settings.yaml
  install/test/fixtures/settings/sts_discovery.yaml
  install/test/fixtures/settings/translate_empty_gateway.yaml
  install/test/fixtures/settings/uds_disabled.yaml
  install/test/fixtures/settings/watched_discovery_labels.yaml
  install/test/helm_test.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.clone.go
  projects/gloo/pkg/api/v1/settings.pb.equal.go
  projects/gloo/pkg/api/v1/settings.pb.go
  projects/gloo/pkg/api/v1/settings.pb.hash.go
  projects/gloo/pkg/plugins/istio_integration/plugin.go
  projects/gloo/pkg/plugins/istio_integration/plugin_test.go
Labels: keep pr updated

#9135 13 fix: slow start aggression (#9031) (#9087)
  changelog/v1.13.36/fix-envoy-slow-start-agression.yaml
  projects/gloo/pkg/plugins/loadbalancer/plugin.go
  projects/gloo/pkg/plugins/loadbalancer/plugin_test.go
Labels: keep pr updated

#9132 14 fix: slow start aggression (#9031) (#9087)
  changelog/v1.14.29/fix-envoy-slow-start-agression.yaml
  projects/gloo/pkg/plugins/loadbalancer/plugin.go
  projects/gloo/pkg/plugins/loadbalancer/plugin_test.go
Labels: keep pr updated

#9140 1.17: Add tests for non custom probes and add wget back (#8750)
  changelog/v1.17.0-beta8/reenable-probes.yaml
  projects/envoyinit/cmd/Dockerfile.envoyinit
  projects/gloo/cmd/Dockerfile
  test/kube2e/helm/artifacts/helm.yaml
Labels: keep pr updated

#9145 Doc fixes
  changelog/v1.17.0-beta8/doc-fixes.yaml
  docs/content/guides/traffic_management/configuration_validation/admission_control.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
Labels: keep pr updated

#9147 Expose ratelimit grpc authority field
  changelog/v1.17.0-beta8/ratelimit-grpc-authority.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.hash.go
  projects/gloo/pkg/plugins/ratelimit/plugin.go
  projects/gloo/pkg/plugins/ratelimit/plugin_test.go
  projects/gloo/pkg/plugins/ratelimit/util.go
Labels: keep pr updated

#9149 [1.16] api: Add retryPolicy to PassThroughGrpc authconfig
  changelog/v1.16.4/grpc-passthrough-retry.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#9150 [1.15] api: Add retryPolicy to PassThroughGrpc authconfig
  changelog/v1.15.23/grpc-passthrough-retry.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/enterprise.gloo.solo.io_v1_AuthConfig.yaml
  projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.hash.go
Labels: keep pr updated

#9153 Expose ratelimit grpc authority field [1.16]
  changelog/v1.16.4/ratelimit-grpc-authority.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.hash.go
  projects/gloo/pkg/plugins/ratelimit/plugin.go
  projects/gloo/pkg/plugins/ratelimit/plugin_test.go
  projects/gloo/pkg/plugins/ratelimit/util.go
Labels: keep pr updated

#9154 Expose ratelimit grpc authority field [1.15]
  changelog/v1.15.23/ratelimit-grpc-authority.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.hash.go
  projects/gloo/pkg/plugins/ratelimit/plugin.go
  projects/gloo/pkg/plugins/ratelimit/plugin_test.go
  projects/gloo/pkg/plugins/ratelimit/util.go
Labels: keep pr updated

#9155 Expose ratelimit grpc authority field [1.14]
  changelog/v1.14.29/ratelimit-grpc-authority.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.hash.go
  projects/gloo/pkg/plugins/ratelimit/plugin.go
  projects/gloo/pkg/plugins/ratelimit/plugin_test.go
  projects/gloo/pkg/plugins/ratelimit/util.go
Labels: keep pr updated

#9156 Expose ratelimit grpc authority field [1.13]
  changelog/v1.13.36/ratelimit-grpc-authority.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto.sk.md
  docs/data/ProtoMap.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Settings.yaml
  projects/gloo/api/v1/enterprise/options/ratelimit/ratelimit.proto
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.clone.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.equal.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.go
  projects/gloo/pkg/api/v1/enterprise/options/ratelimit/ratelimit.pb.hash.go
  projects/gloo/pkg/plugins/ratelimit/plugin.go
  projects/gloo/pkg/plugins/ratelimit/plugin_test.go
  projects/gloo/pkg/plugins/ratelimit/util.go
Labels: keep pr updated

#9151 [1.14] Feb 8 CVEs bump envoy-gloo
  Makefile
  changelog/v1.14.29/envoy-gloo-cves.yaml
Labels: keep pr updated

#9152 [1.13] Feb 8 CVEs bump envoy-gloo
  Makefile
  changelog/v1.13.36/envoy-gloo-cves.yaml
Labels: keep pr updated

#9158 [1.15] CVE 8feb24 patch
  Makefile
  changelog/v1.15.23/envoy-gloo-cves.yaml
Labels: keep pr updated

#9159 [1.16] CVE 8feb24 patch
  Makefile
  changelog/v1.16.4/envoy-gloo-cves.yaml
Labels: keep pr updated

#9166 gloo-gateway: re-use ControlPlane server and cache
  install/helm/gloo/templates/2-gloo-service.yaml
  install/helm/gloo/values-template.yaml
  projects/envoyinit/pkg/runner/run.go
  projects/gateway2/controller/controller.go
  projects/gateway2/controller/main.go
  projects/gateway2/deployer/builder.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/examples/helm-install.yaml
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/helm/gloo-gateway/values.yaml
  projects/gloo/pkg/bootstrap/opts.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/xds/cache.go
  projects/gloo/pkg/xds/cache_test.go
  projects/gloo/pkg/xds/node_hash.go
  projects/gloo/pkg/xds/node_hash_test.go
Labels: keep pr updated

#9139 Use hostname for hashing
  changelog/v1.17.0-beta9/use-hostname-for-hashing.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/load_balancer.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/load_balancer.proto
  projects/gloo/pkg/api/v1/load_balancer.pb.clone.go
  projects/gloo/pkg/api/v1/load_balancer.pb.equal.go
  projects/gloo/pkg/api/v1/load_balancer.pb.go
  projects/gloo/pkg/api/v1/load_balancer.pb.hash.go
  projects/gloo/pkg/plugins/loadbalancer/plugin.go
  projects/gloo/pkg/plugins/loadbalancer/plugin_test.go
Labels: keep pr updated

#9169 Remove WasmHub and wasme from Edge docs
  changelog/v1.17.0-beta9/docs-rm-wasm.yaml
  docs/content/installation/advanced_configuration/wasm.md
Labels: Type: Docs, keep pr updated

#9171 [DNM] Helm and other merge cleanup
  install/helm/gloo/templates/44-deployment.yaml
  install/helm/gloo/templates/44-rbac.yaml
  install/helm/gloo/templates/44-service.yaml
  install/helm/gloo/templates/44-serviceaccount.yaml
  install/helm/gloo/templates/_gg-helpers.tpl
  install/helm/gloo/values-template.yaml
  projects/gateway2/helm/gloo-gateway/templates/_helpers.tpl
  projects/gateway2/helm/gloo-gateway/templates/deployment.yaml
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/helm/gloo-gateway/templates/gatewayclass.yaml
  projects/gateway2/helm/gloo-gateway/templates/rbac.yaml
  projects/gateway2/helm/gloo-gateway/templates/service.yaml
  projects/gateway2/helm/gloo-gateway/templates/serviceaccount.yaml
  projects/gateway2/helm/gloo-gateway/values.schema.json
  test/kube2e/gloo/setup_syncer_test.go
Labels: work in progress, keep pr updated

#9148 Combine Gloo Gateway and Gloo Edge binaries/helm charts
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  changelog/v1.17.0-beta9/combine-ge-gg.yaml
  ci/kind/setup-kind.sh
  docs/content/reference/cli/glooctl.md
  docs/content/reference/values.txt
  install/helm/gloo/.helmignore
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/2-gloo-service.yaml
  install/helm/gloo/templates/44-gatewayclass.yaml
  install/helm/gloo/templates/44-rbac.yaml
  install/helm/gloo/templates/_gg-helpers.tpl
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  install/test/rbac_test.go
  projects/gateway2/Dockerfile
  projects/gateway2/LICENSE
  projects/gateway2/Makefile
  projects/gateway2/cmd/controller.go
  projects/gateway2/cmd/root.go
  projects/gateway2/controller/controller.go
  projects/gateway2/controller/controller_suite_test.go
  projects/gateway2/controller/gw_controller.go
  projects/gateway2/controller/main.go
  projects/gateway2/controller/translator.go
  projects/gateway2/controller/xds.go
  projects/gateway2/deployer/builder.go
  projects/gateway2/deployer/deployer.go
  projects/gateway2/deployer/deployer_test.go
  projects/gateway2/examples/helm-install.yaml
  projects/gateway2/helm/gloo-gateway/.helmignore
  projects/gateway2/helm/gloo-gateway/templates/NOTES.txt
  projects/gateway2/helm/gloo-gateway/templates/_helpers.tpl
  projects/gateway2/helm/gloo-gateway/templates/deployment.yaml
  projects/gateway2/helm/gloo-gateway/templates/gateway/hpa.yaml
  projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
  projects/gateway2/helm/gloo-gateway/templates/gatewayclass.yaml
  projects/gateway2/helm/gloo-gateway/templates/service.yaml
  projects/gateway2/helm/gloo-gateway/templates/serviceaccount.yaml
  projects/gateway2/helm/gloo-gateway/values.schema.json
  projects/gateway2/helm/gloo-gateway/values.yaml
  projects/gateway2/kind.sh
  projects/gateway2/main.go
  projects/gateway2/tests/conformance/test-values.yaml
  projects/gateway2/xds/xds_syncer.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/install/v2/install.go
  projects/gloo/cli/pkg/cmd/install/v2/uninstall.go
  projects/gloo/cli/pkg/cmd/root.go
  projects/gloo/constants/gloo_gateway.go
  projects/gloo/pkg/bootstrap/opts.go
  projects/gloo/pkg/syncer/envoy_translator_syncer.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/xds/cache.go
  projects/gloo/pkg/xds/cache_test.go
  projects/gloo/pkg/xds/node_hash.go
  projects/gloo/pkg/xds/node_hash_test.go
  test/consulvaulte2e/e2e_suite_test.go
  test/kube2e/gloo/setup_syncer_test.go
  test/services/gloo.go
Labels: keep pr updated

#9176 backport sds and envoy log helm value
  changelog/v1.16.5/add-sds-log-level.yaml
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
  install/helm/gloo/values-template.yaml
  install/test/helm_test.go
  projects/sds/pkg/run/run_main.go
Labels: keep pr updated

#9168 Add Error section to contribution guide
  changelog/v1.17.0-beta9/update-contribution-conventions-with-error.yaml
  devel/contributing/conventions.md
Labels: keep pr updated

#9177 Update github to trigger on ready for review
  .github/workflows/README.md
  .github/workflows/docs-gen.yaml
  .github/workflows/pr.yaml
  .github/workflows/regression-tests.yaml
  changelog/v1.17.0-beta9/update-pr-trigger.yaml
Labels: keep pr updated

#9180 Doc fixes 1.15
  changelog/v1.15.24/doc-fixes.yaml
  docs/content/installation/advanced_configuration/multi-gw-deployment.md
Labels: keep pr updated

#9181 Doc fixes 1.14
  changelog/v1.14.30/doc-fixes.yaml
  docs/content/installation/advanced_configuration/multi-gw-deployment.md
Labels: keep pr updated

#9182 Doc fixes 1.13
  changelog/v1.13.37/doc-fixes.yaml
  docs/content/installation/advanced_configuration/multi-gw-deployment.md
Labels: keep pr updated

#9184 Doc fixes
  changelog/v1.17.0-beta9/doc-fixes.yam
  docs/content/installation/advanced_configuration/multi-gw-deployment.md
Labels: keep pr updated

#9193 Doc fixes 1.16
  changelog/v1.16.5/doc-fixes.yaml
  docs/content/installation/advanced_configuration/multi-gw-deployment.md
Labels: keep pr updated

#9183 Docs auth retries
  changelog/v1.17.0-beta9/docs-auth-retries.yaml
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/_index.md
Labels: keep pr updated

#9196 Doc fixes 1.16
  changelog/v1.16.5/doc-kube-services-note.yaml
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/_index.md
  docs/content/guides/traffic_management/destination_types/kubernetes_services/_index.md
  docs/content/installation/advanced_configuration/wasm.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  test/kube2e/helm/artifacts/helm.yaml
Labels: keep pr updated

#9197 Doc-fixes 1.15
  changelog/v1.15.24/docs-auth-retries.yaml
  docs/content/guides/security/auth/extauth/passthrough_auth/grpc/_index.md
  docs/content/guides/traffic_management/destination_types/kubernetes_services/_index.md
  docs/content/installation/advanced_configuration/wasm.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  test/kube2e/helm/artifacts/helm.yaml
Labels: keep pr updated

#9203 Doc fixes v1.14
  changelog/v1.14.30/docs-rm-wasm.yaml
  docs/content/guides/traffic_management/destination_types/kubernetes_services/_index.md
  docs/content/installation/advanced_configuration/wasm.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
  test/kube2e/helm/artifacts/helm.yaml
Labels: keep pr updated

#9205 Doc fixes v1.13
  changelog/v1.13.37/docs-rm-wasm.yaml
  docs/content/guides/traffic_management/destination_types/kubernetes_services/_index.md
  docs/content/installation/advanced_configuration/wasm.md
  docs/content/reference/values.txt
  install/helm/gloo/generate/values.go
Labels: keep pr updated

#9122 Secret Deletion validation against Previous State
  changelog/v1.17.0-beta9/secret-delete-with-revalidation.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
  projects/gateway/pkg/utils/gateway_filtering.go
  projects/gateway/pkg/utils/gateway_filtering_test.go
  projects/gateway/pkg/validation/validator.go
  projects/gateway/pkg/validation/validator_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/utils/validation/proxy_validation.go
  projects/gloo/pkg/validation/server.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/util.go
Labels: keep pr updated
