Repository kgateway-dev/kgateway, pull requests merged in 2024-03, with the labels that each got.

#9208 xds/hash: support non-proxy workload key generation
  changelog/v1.17.0-beta10/fix-xds-cache-key.yaml
  projects/gloo/pkg/xds/node_hash.go
  projects/gloo/pkg/xds/node_hash_test.go
Labels: keep pr updated

#9210 Doc fixes
  changelog/v1.17.0-beta11/doc-fixes.yaml
  docs/content/guides/traffic_management/destination_types/kubernetes_services/_index.md
  docs/content/operations/debugging_gloo/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk.md
  docs/content/reference/values.txt
  docs/content/static/content/version_gee_latest.md
  docs/content/static/content/version_gee_n-1.md
  docs/content/static/content/version_gee_n-1_oldpatch.md
  docs/content/static/content/version_geoss_latest.md
  docs/content/static/content/version_geoss_n+1.md
  docs/content/static/content/version_geoss_n-1.md
  install/helm/gloo/generate/values.go
  projects/gloo/api/v1/settings.proto
  projects/gloo/pkg/api/v1/settings.pb.go
Labels: keep pr updated

#9198 Fix CVE-2024-26147
  changelog/v1.17.0-beta11/bump-helm.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: keep pr updated

#9219 trivy: Ignore CVE-2024-26147 (helm)
  .trivyignore
  changelog/v1.17.0-beta11/ignore-helm-bump.yaml
Labels: keep pr updated

#9199 [1.16] Fix CVE-2024-26147
  changelog/v1.16.6/bump-helm-116.yaml
  docs/content/static/content/osa_provided.md
  go.mod
  go.sum
Labels: work in progress, keep pr updated

#9227 k8s-gateway: support configurable deployer and plugin translation
  changelog/v1.17.0-beta11/inject-enterprise-functionality.yaml
  projects/gateway2/controller/start.go
  projects/gateway2/controller/translator.go
  projects/gateway2/deployer/deployer.go
  projects/gloo/constants/gloo_gateway.go
  projects/gloo/pkg/syncer/setup/start_func.go
Labels: keep pr updated

#9201 k8sgateway/plugins: expose an extension point to inject enterprise-only plugins
  changelog/v1.17.0-beta11/portal-plugin-v2.yaml
  pkg/utils/stringutils/stringutils.go
  projects/gateway2/controller/start.go
  projects/gateway2/extensions/extensions.go
  projects/gateway2/translator/gateway_translator.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/listener/gateway_listener_translator.go
  projects/gateway2/translator/plugins/plugins.go
  projects/gateway2/translator/plugins/registry/plugin_registry.go
  projects/gateway2/translator/translator_case_test.go
  projects/gateway2/xds/xds_syncer.go
  projects/gloo/pkg/syncer/setup/extensions.go
  projects/gloo/pkg/syncer/setup/extensions_test.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/setup/start_func.go
Labels: keep pr updated

#9215 Add importas linter to enforce common package import alias
  .golangci.yaml
  changelog/v1.17.0-beta11/add-importas-linter.yaml
  install/helm/gloo/generate/values.go
  install/test/helm_suite_test.go
  install/test/helm_test.go
  jobs/certgen/cmd/main.go
  jobs/pkg/kube/secret.go
  jobs/pkg/kube/secret_test.go
  jobs/pkg/run/run.go
  pkg/cliutil/helm/hooks.go
  pkg/cliutil/uri.go
  projects/clusteringress/pkg/translator/translator_syncer.go
  projects/clusteringress/pkg/translator/translator_syncer_test.go
  projects/gateway/pkg/defaults/validation.go
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/proxy_prom_stats.go
  projects/gloo/cli/pkg/cmd/install/knative.go
  projects/gloo/cli/pkg/cmd/install/knative_test.go
  projects/gloo/cli/pkg/cmd/version/clients.go
  projects/gloo/pkg/api/converters/kube/account_credentials_secret.go
  projects/gloo/pkg/api/converters/kube/api_key_secret.go
  projects/gloo/pkg/api/converters/kube/artifact_converter.go
  projects/gloo/pkg/api/converters/kube/artifact_converter_test.go
  projects/gloo/pkg/api/converters/kube/encryption_key_secret.go
  projects/gloo/pkg/api/converters/kube/encryption_key_secret_test.go
  projects/gloo/pkg/api/converters/kube/header_secret.go
  projects/gloo/pkg/api/converters/kube/oauth_secret.go
  projects/gloo/pkg/api/converters/kube/opaque_secret.go
  projects/gloo/pkg/api/converters/kube/secretconverter.go
  projects/gloo/pkg/api/converters/kube/secretconverter_test.go
  projects/gloo/pkg/plugins/kubernetes/eds.go
  projects/gloo/pkg/plugins/kubernetes/serviceconverter/general_annotation_converter.go
  projects/gloo/pkg/plugins/kubernetes/serviceconverter/service_converter_interface.go
  projects/gloo/pkg/plugins/kubernetes/serviceconverter/use_http2_annotation_converter.go
  projects/gloo/pkg/plugins/kubernetes/serviceconverter/use_ssl_annotation_converter.go
  projects/gloo/pkg/plugins/kubernetes/uds.go
  projects/gloo/pkg/plugins/kubernetes/uds_convert.go
  projects/gloo/pkg/plugins/kubernetes/uds_convert_test.go
  projects/gloo/pkg/translator/translator_test.go
  projects/gloo/pkg/upstreams/kubernetes/conversions.go
  projects/ingress/pkg/api/service/resource_client.go
  projects/ingress/pkg/status/status_syncer.go
  projects/ingress/pkg/translator/translate.go
  projects/ingress/pkg/translator/translate_test.go
  projects/knative/pkg/translator/translator_syncer.go
  projects/knative/pkg/translator/translator_syncer_test.go
  projects/sds/pkg/run/run_main.go
  test/helpers/certs.go
  test/kube2e/gloo/bootstrap_clients_test.go
  test/kube2e/gloo/generated_kube_types_test.go
  test/kube2e/gloo/gloo_resources_test.go
  test/kube2e/gloo/happypath_test.go
  test/kube2e/gloo/kubernetes_test.go
  test/kube2e/gloo/resource_client_test.go
  test/kube2e/helper/install.go
  test/kube2e/ingress/resource_client_test.go
  test/kube2e/ingress/status_syncer_test.go
  test/kube2e/knative/knative_manual_tls_test.go
Labels: keep pr updated

#9220 Docs: Adding additional support info
  changelog/v1.17.0-beta12/doc-support-update.yaml
  docs/content/operations/debugging_gloo/_index.md
  docs/content/support/about.md
  docs/content/support/support-info.md
  docs/content/support/support-ticket.md
Labels: keep pr updated

#9230 Docs update support [1.16]
  changelog/v1.16.7/doc-support-update.yaml
  docs/content/operations/debugging_gloo/_index.md
  docs/content/support/about.md
  docs/content/support/support-info.md
  docs/content/support/support-ticket.md
Labels: keep pr updated

#9223 1.16 Use hostname for hashing (#9139)
  changelog/v1.16.7/use-hostname-for-hashing.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/load_balancer.proto.sk.md
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  projects/gloo/api/v1/load_balancer.proto
  projects/gloo/pkg/api/v1/load_balancer.pb.clone.go
  projects/gloo/pkg/api/v1/load_balancer.pb.equal.go
  projects/gloo/pkg/api/v1/load_balancer.pb.go
  projects/gloo/pkg/api/v1/load_balancer.pb.hash.go
  projects/gloo/pkg/plugins/loadbalancer/plugin.go
  projects/gloo/pkg/plugins/loadbalancer/plugin_test.go
Labels: keep pr updated

#9226 cli: get proxy API can query proxies from k8s-gateway
  changelog/v1.17.0-beta12/support-get-proxy-api.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/debug/proxy_endpoint.proto.sk.md
  docs/content/reference/cli/glooctl_get_proxy.md
  docs/content/static/content/osa_provided.md
  go.mod
  pkg/cliutil/uri.go
  pkg/utils/kubeutils/names.go
  pkg/utils/kubeutils/pods.go
  pkg/utils/kubeutils/portforward/api_forwarder.go
  pkg/utils/kubeutils/portforward/cli_portforwarder.go
  pkg/utils/kubeutils/portforward/options.go
  pkg/utils/kubeutils/portforward/portforwarder.go
  projects/gateway2/controller/start.go
  projects/gateway2/translator/httproute/gateway_http_route_translator.go
  projects/gateway2/translator/plugins/utils/plugin_utils.go
  projects/gateway2/xds/xds_syncer.go
  projects/gloo/api/grpc/debug/proxy_endpoint.proto
  projects/gloo/cli/pkg/cmd/check/check_test.go
  projects/gloo/cli/pkg/cmd/check/gloo_stats.go
  projects/gloo/cli/pkg/cmd/check/proxy_prom_stats.go
  projects/gloo/cli/pkg/cmd/check/root.go
  projects/gloo/cli/pkg/cmd/dashboard/root.go
  projects/gloo/cli/pkg/cmd/get/proxy.go
  projects/gloo/cli/pkg/cmd/options/options.go
  projects/gloo/cli/pkg/common/get.go
  projects/gloo/cli/pkg/common/proxy.go
  projects/gloo/cli/pkg/flagutils/proxy.go
  projects/gloo/pkg/api/grpc/debug/proxy_endpoint.pb.go
  projects/gloo/pkg/debug/proxy_endpoint.go
  projects/gloo/pkg/debug/proxy_endpoint_test.go
  projects/gloo/pkg/debug/source.go
  projects/gloo/pkg/syncer/setup/setup_syncer.go
  projects/gloo/pkg/syncer/setup/start_func.go
  test/gomega/assertions/stats.go
  test/kube2e/helm/helm_test.go
Labels: keep pr updated

#9124 Control plane support for Extractor regex replace
  Makefile
  changelog/v1.17.0-beta13/extractor-regex-replace.yaml
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/transformation/transformation.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableTcpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/api/v1/options/transformation/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.hash.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.clone.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.hash.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/transformation/plugin_test.go
  test/e2e/staged_transformation_test.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9239 Correct error in transformation/extractor user guide
  changelog/v1.17.0-beta13/update-extractor-doc.yaml
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/transformation/transformation.proto.sk.md
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/api/v1/options/transformation/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.go
Labels: keep pr updated

#9236 [v1.16.x] Backport Extractor Regex Replace functionality
  Makefile
  changelog/v1.16.8/extractor-regex-replace.yaml
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/transformation/transformation.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableTcpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/api/v1/options/transformation/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.hash.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.clone.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.hash.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/transformation/plugin_test.go
  test/e2e/staged_transformation_test.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9235 [v1.15.x] Backport Extractor Regex Replace functionality
  Makefile
  changelog/v1.15.24/extractor-regex-replace.yaml
  docs/content/guides/traffic_management/request_processing/transformations/_index.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/transformation/transformation.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableTcpGateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_RouteTable.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualHostOption.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_VirtualService.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml
  install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml
  projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
  projects/gloo/api/v1/options/transformation/transformation.proto
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.clone.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.go
  projects/gloo/pkg/api/external/envoy/extensions/transformation/transformation.pb.hash.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.clone.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.equal.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.go
  projects/gloo/pkg/api/v1/options/transformation/transformation.pb.hash.go
  projects/gloo/pkg/plugins/transformation/plugin.go
  projects/gloo/pkg/plugins/transformation/plugin_test.go
  test/e2e/staged_transformation_test.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9241 initialize k8s gw extensions factory just once, allow returning error
  changelog/v1.17.0-beta13/update-k8sgatewayextensions-definition.yaml
  projects/gateway2/controller/start.go
  projects/gateway2/extensions/extensions.go
  projects/gateway2/xds/xds_syncer.go
Labels: keep pr updated

#9237 Updates for deflaking dataplane per proxy tests
  changelog/v1.17.0-beta13/resource-cleanup-pre-delete.yaml
  install/helm/gloo/templates/5-resource-cleanup-job-clusterrole.yaml
  install/helm/gloo/templates/5-resource-cleanup-job-clusterrolebinding.yaml
  install/helm/gloo/templates/5-resource-cleanup-job-role.yaml
  install/helm/gloo/templates/5-resource-cleanup-job-rolebinding.yaml
  install/helm/gloo/templates/5-resource-cleanup-job-service-account.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  test/helpers/util.go
  test/kube2e/helper/curl.go
Labels: keep pr updated

#9242 syncer: reconcile proxies in memory cache
  changelog/v1.17.0-beta13/k8s-gw-syncer.yaml
  projects/gateway2/xds/xds_syncer.go
  projects/gloo/cli/pkg/common/proxy.go
  projects/gloo/pkg/api/v1/proxy_extensions.go
  projects/gloo/pkg/debug/proxy_endpoint.go
  projects/gloo/pkg/debug/source.go
  projects/gloo/pkg/syncer/setup/start_func.go
  projects/gloo/pkg/syncer/translator_syncer.go
Labels: keep pr updated

#9249 Resource cleanup pre-delete (backport #9237)
  changelog/v1.16.9/resource-cleanup-pre-delete.yaml
  install/helm/gloo/templates/5-resource-cleanup-job-clusterrole.yaml
  install/helm/gloo/templates/5-resource-cleanup-job-clusterrolebinding.yaml
  install/helm/gloo/templates/5-resource-cleanup-job-role.yaml
  install/helm/gloo/templates/5-resource-cleanup-job-rolebinding.yaml
  install/helm/gloo/templates/5-resource-cleanup-job-service-account.yaml
  install/helm/gloo/templates/5-resource-cleanup-job.yaml
  test/helpers/util.go
Labels: keep pr updated

#9212 Fixing #9211
  changelog/v1.17.0-beta14/9211-improve-glooctl-version.yaml
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/grpc/version/version.proto.sk.md
  docs/data/ProtoMap.yaml
  pkg/utils/protoutils/utils.go
  projects/gloo/api/grpc/version/version.proto
  projects/gloo/cli/pkg/cmd/version/clients.go
  projects/gloo/cli/pkg/cmd/version/clients_test.go
  projects/gloo/cli/pkg/cmd/version/cmd.go
  projects/gloo/cli/pkg/cmd/version/mocks/mock_watcher.go
  projects/gloo/cli/pkg/cmd/version/version_test.go
  projects/gloo/cli/pkg/prerun/version_warning.go
  projects/gloo/cli/pkg/prerun/version_warning_test.go
  projects/gloo/pkg/api/grpc/version/version.pb.clone.go
  projects/gloo/pkg/api/grpc/version/version.pb.equal.go
  projects/gloo/pkg/api/grpc/version/version.pb.go
  projects/gloo/pkg/api/grpc/version/version.pb.hash.go
Labels: keep pr updated, Area: CLI

#9255 Otel service name pr feedback 1
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/trace/v3/opentelemetry.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  pkg/utils/api_conversion/trace.go
  pkg/utils/api_conversion/trace_test.go
  projects/gloo/api/external/envoy/config/trace/v3/opentelemetry.proto
  projects/gloo/pkg/api/external/envoy/config/trace/v3/opentelemetry.pb.clone.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/opentelemetry.pb.equal.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/opentelemetry.pb.go
  projects/gloo/pkg/api/external/envoy/config/trace/v3/opentelemetry.pb.hash.go
  projects/gloo/pkg/plugins/tracing/plugin.go
Labels: keep pr updated

#9247 Add access log formatter support for metadata extension
  changelog/v1.17.0-beta14/metadata-access-log-formatter.yaml
  projects/gloo/pkg/plugins/als/plugin.go
  test/e2e/access_log_test.go
  test/testutils/http_request.go
  test/testutils/http_request_test.go
Labels: keep pr updated

#9252 Robustness test flake fix
  changelog/v1.17.0-beta14/robustness-test-flake-fix.yaml
  test/kube2e/gateway/gateway_test.go
  test/kube2e/util.go
Labels: keep pr updated

#9250 logging and verifyGlooValidationWorks
  changelog/v1.17.0-beta14/delete-secret-flake.yaml
  test/helpers/kube_dump.go
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9263 [1.16.x] secret delete and robustness flake backport
  changelog/v1.16.9/delete-secret-and-robustness-flake.yaml
  test/helpers/kube_dump.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/util.go
Labels: keep pr updated

#9265 [1.15.x] Delete secret flake mititgation
  changelog/v1.15.25/secret-delete-flake.yaml
  test/kube2e/gateway/gateway_test.go
Labels: keep pr updated

#9270 Update docs issue template for versions
  .github/ISSUE_TEMPLATE/DOCS-ISSUE.yml
  changelog/v1.17.0-beta14/docs-versions.yaml
Labels: keep pr updated

#9260 Expose disable dynamic stats
  changelog/v1.17.0-beta14/expose-dynamic-stats.yaml
  docs/content/guides/dev/setting-up-dev-environment.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/router/router.proto.sk.md
  install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
  install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml
  projects/gloo/api/v1/options/router/router.proto
  projects/gloo/pkg/api/v1/options/router/router.pb.go
  projects/gloo/pkg/translator/listener_subsystem_test.go
  projects/gloo/pkg/translator/network_filters.go
  projects/gloo/pkg/translator/network_filters_test.go
Labels: keep pr updated

#9240 Use gateway name for Otel service name
  changelog/v1.17.0-beta14/service-name-for-otel.yaml
  devel/architecture/static_metadata.md
  docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk.md
  pkg/utils/api_conversion/trace.go
  pkg/utils/api_conversion/trace_test.go
  projects/gloo/api/v1/proxy.proto
  projects/gloo/pkg/api/v1/proxy.pb.go
  projects/gloo/pkg/plugins/tracing/plugin.go
  projects/gloo/pkg/plugins/tracing/plugin_test.go
Labels: work in progress, keep pr updated

#9264 bump to envoy-gloo 1.29
  Makefile
  changelog/v1.17.0-beta14/envoy-1.29.yaml
  go.mod
Labels: keep pr updated

#9296 fix glooctl assets arch
  Makefile.ci
  changelog/v1.17.0-beta15/fix-glooctl-assets.yaml
Labels: keep pr updated

#9297 fix github asset publish script, add dry run for PRs
  Makefile
  changelog/v1.17.0-beta15/fix-github-release-script.yaml
  ci/upload_github_release_assets.go
Labels: keep pr updated
