Repository kgateway-dev/kgateway, pull requests merged in 2025-06, with the labels that each got.

#11324 Makefile: Fix the run target
  Makefile
Labels: kind/cleanup, release-note-none

#11282 feat: Allow overriding default LLM provider endpoints
  api/applyconfiguration/api/v1alpha1/authheaderoverride.go
  api/applyconfiguration/api/v1alpha1/llmprovider.go
  api/applyconfiguration/api/v1alpha1/pathoverride.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/ai_backend.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml
  internal/kgateway/extensions2/plugins/backend/ai/ai_backend_test.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster_test.go
  internal/kgateway/setup/testdata/standard/ai-custom-url-out.yaml
  internal/kgateway/setup/testdata/standard/ai-custom-url.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/aiextension/suite.go
  test/kubernetes/e2e/features/aiextension/testdata/backend-passthrough.yaml
  test/kubernetes/e2e/features/aiextension/testdata/backend-token.yaml
  test/kubernetes/e2e/features/aiextension/testdata/prompt-guard-streaming.yaml
  test/kubernetes/e2e/features/aiextension/testdata/prompt-guard.yaml
  test/kubernetes/e2e/features/aiextension/testdata/routes-basic.yaml
  test/kubernetes/e2e/features/aiextension/testdata/routes-with-extension-ref.yaml
  test/kubernetes/e2e/features/aiextension/testdata/routes-with-pg-regex-pattern-reject.yaml
  test/kubernetes/e2e/features/aiextension/tests/client/client.py
  test/kubernetes/e2e/features/aiextension/tests/routing.py
  test/mocks/mock-ai-provider-server/main.go
Labels: release-note, kind/feature

#11197 dynamic forward proxy
  .github/workflows/pr-kubernetes-tests.yaml
  api/applyconfiguration/api/v1alpha1/backendspec.go
  api/applyconfiguration/api/v1alpha1/dynamicforwardproxybackend.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/backend_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml
  internal/kgateway/extensions2/plugins/backend/dfp.go
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/dfp/simple.yaml
  internal/kgateway/translator/gateway/testutils/inputs/dfp/tls.yaml
  internal/kgateway/translator/gateway/testutils/outputs/dfp/simple.yaml
  internal/kgateway/translator/gateway/testutils/outputs/dfp/tls.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/dfp/suite.go
  test/kubernetes/e2e/features/dfp/testdata/common.yaml
  test/kubernetes/e2e/features/dfp/testdata/service.yaml
  test/kubernetes/e2e/features/dfp/types.go
  test/kubernetes/e2e/tests/kgateway_tests.go
  test/translator/test.go
Labels: release-note, kind/feature

#11341 deflake: try to deflake ipv6 setup tests.
  .github/workflows/pr-unit-tests.yaml
  Makefile
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  internal/kgateway/setup/setup_test.go
  pkg/envoyinit/run.go
  pkg/utils/cmdutils/cmd.go
  pkg/utils/cmdutils/local.go
  pkg/utils/controllerutils/admincli/client_test.go
  test/envtestutil/util.go
Labels: release-note-none, kind/flake

#11308 backendconfigpolicy: add ssl config
  api/applyconfiguration/api/v1alpha1/backendconfigpolicyspec.go
  api/applyconfiguration/api/v1alpha1/sslconfig.go
  api/applyconfiguration/api/v1alpha1/sslfiles.go
  api/applyconfiguration/api/v1alpha1/sslparameters.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin_test.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/ssl.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/ssl_test.go
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-alias.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-label.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-ssl-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-ssl.yaml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release-note, kind/feature

#11350 docs: update the Helm docs
  install/helm/kgateway/values.yaml
Labels: Type: Docs, Area: Helm, release-note, kind/documentation

#11358 Switch to exposing usedonly stats in StatsConfig
  install/test/fixtures.go
  install/test/fixtures/envoy_config/bootstrap_extensions.yaml
  install/test/fixtures/envoy_config/custom_static_bootstrap.yaml
  install/test/fixtures/envoy_config/overload_manager.yaml
  install/test/fixtures/envoy_config/static_clusters.yaml
  install/test/fixtures/envoy_config/tcp_keepalive.yaml
  install/test/k8sgateway_test.go
  internal/kgateway/deployer/deployer.go
  internal/kgateway/deployer/deployer_test.go
Labels: kind/breaking_change, release-note

#11321 fix: Ensure correct status reporting of AttachedListenerSets condition
  internal/kgateway/deployer/deployer.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/translator/listener/validation.go
  test/kubernetes/e2e/features/listenerset/suite.go
  test/kubernetes/e2e/features/listenerset/testdata/setup.yaml
  test/kubernetes/e2e/features/listenerset/testdata/valid-listenerset.yaml
  test/kubernetes/e2e/features/listenerset/types.go
Labels: release-note, kind/fix

#11380 docs: single-line Helm descriptions
  install/helm/kgateway/values.yaml
Labels: release-note-none, kind/documentation

#11335 allow empty address WorkloadEntry to reach endpoint plugin
  internal/kgateway/endpoints/prioritize.go
  internal/kgateway/extensions2/plugins/serviceentry/collections.go
  internal/kgateway/extensions2/plugins/serviceentry/endpoints.go
  internal/kgateway/setup/setup_test.go
  internal/kgateway/setup/testdata/serviceentry/dr/se-backendref-out.yaml
  internal/kgateway/setup/testdata/serviceentry/dr/se-backendref.yaml
  test/kubernetes/e2e/features/waypoint/testdata/common/test_apps.yaml
Labels: kind/cleanup, release-note-none

#11384 static backend app protocol
  api/applyconfiguration/api/v1alpha1/staticbackend.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/backend_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/backend-protocol/backend-default.yaml
  internal/kgateway/translator/gateway/testutils/inputs/backend-protocol/backend-h2c.yaml
  internal/kgateway/translator/gateway/testutils/inputs/backend-protocol/backend-ws.yaml
  internal/kgateway/translator/gateway/testutils/inputs/backend-protocol/svc-default.yaml
  internal/kgateway/translator/gateway/testutils/inputs/backend-protocol/svc-h2c.yaml
  internal/kgateway/translator/gateway/testutils/inputs/backend-protocol/svc-ws.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backend-protocol/backend-default.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backend-protocol/backend-h2c.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backend-protocol/backend-ws.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backend-protocol/svc-default.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backend-protocol/svc-h2c.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backend-protocol/svc-ws.yaml
  internal/kgateway/translator/irtranslator/backend.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/pluginsdk/ir/backend.go
  pkg/pluginsdk/ir/backend_test.go
Labels: release-note, kind/feature

#11397 Docs: Added link to documentation on Inference Extension.
  install/helm/kgateway/values.yaml
Labels: release-note-none, kind/documentation

#11385 add yq to tools
  Makefile
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
Labels: release-note-none, kind/fix

#11391 refactor: Centralize AI plugin environment variable
  internal/kgateway/extensions2/plugins/backend/ai/ai_backend.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_resources.go
  internal/kgateway/extensions2/plugins/trafficpolicy/ai_env.go
  internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy_test.go
Labels: kind/cleanup, release-note-none

#11401 rename ssl config to tls
  api/applyconfiguration/api/v1alpha1/backendconfigpolicyspec.go
  api/applyconfiguration/api/v1alpha1/loadbalancer.go
  api/applyconfiguration/api/v1alpha1/loadbalancerleastrequestconfig.go
  api/applyconfiguration/api/v1alpha1/loadbalancerroundrobinconfig.go
  api/applyconfiguration/api/v1alpha1/parameters.go
  api/applyconfiguration/api/v1alpha1/slowstart.go
  api/applyconfiguration/api/v1alpha1/tls.go
  api/applyconfiguration/api/v1alpha1/tlsfiles.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/lb.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/lb_test.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/tls.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/tls_test.go
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-tls-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-tls.yaml
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/lb-config.yaml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/cleanup, release-note

#11329 actually write spec IPs to gateway status
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/gatewayclass_provisioner_test.go
  internal/kgateway/controller/gw_controller.go
  internal/kgateway/controller/gw_controller_test.go
Labels: release-note-none, kind/fix

#11413 internal: bump Go, fix port check, and remove unused param
  go.mod
  internal/kgateway/extensions2/plugins/backend/ai/ai_backend.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster_test.go
  internal/kgateway/extensions2/plugins/backend/aws.go
  internal/kgateway/extensions2/plugins/backend/dfp.go
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/extensions2/plugins/backend/static.go
  internal/kgateway/krtcollections/builtin.go
  internal/kgateway/krtcollections/endpoints.go
  internal/kgateway/krtcollections/endpoints_test.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/setup.go
Labels: kind/cleanup, release-note-none

#11410 Set observed generation for policy status
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/generation.yaml
  internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/generation.yaml
  internal/kgateway/translator/irtranslator/policy.go
  pkg/pluginsdk/reporter/types.go
  test/kubernetes/e2e/features/backendtls/suite.go
  test/kubernetes/e2e/features/transformation/suite.go
Labels: release-note-none, kind/fix

#11426 docs: enhance debugging guide with Tilt setup and usage instructions
  test/kubernetes/e2e/debugging.md
Labels: release-note-none, kind/documentation

#11390 Inference Extension: Use a Single Shared ExtProc Filter for all InferencePools
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/setup/testdata/inference_api/inferencepool-basic-out.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-basic.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-multi-route-single-pool-out.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-multi-route-single-pool.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-single-route-multi-pool-out.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-single-route-multi-pool.yaml
Labels: release-note-none, kind/fix

#11302 Add CSRF policy support to TrafficPolicy
  .github/workflows/pr-kubernetes-tests.yaml
  api/applyconfiguration/api/v1alpha1/csrfpolicy.go
  api/applyconfiguration/api/v1alpha1/stringmatcher.go
  api/applyconfiguration/api/v1alpha1/trafficpolicyspec.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/shared_types.go
  api/v1alpha1/traffic_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
  internal/kgateway/extensions2/plugins/trafficpolicy/builder.go
  internal/kgateway/extensions2/plugins/trafficpolicy/csrf_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/setup/testdata/standard/csrf-gw-out.yaml
  internal/kgateway/setup/testdata/standard/csrf-gw.yaml
  internal/kgateway/setup/testdata/standard/csrf-route-out.yaml
  internal/kgateway/setup/testdata/standard/csrf-route-shadowed-out.yaml
  internal/kgateway/setup/testdata/standard/csrf-route-shadowed.yaml
  internal/kgateway/setup/testdata/standard/csrf-route.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/csrf/suite.go
  test/kubernetes/e2e/features/csrf/testdata/common.yaml
  test/kubernetes/e2e/features/csrf/testdata/csrf-gw.yaml
  test/kubernetes/e2e/features/csrf/testdata/csrf-route.yaml
  test/kubernetes/e2e/features/csrf/testdata/csrf-shadowed-route.yaml
  test/kubernetes/e2e/features/csrf/types.go
  test/kubernetes/e2e/tests/kgateway_tests.go
Labels: release-note, kind/feature

#11427 translator: Use proper reason for HTTPRoute status conditions
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/http-routing-invalid-prefix/manifest.yaml
  internal/kgateway/translator/gateway/testutils/outputs/http-routing-invalid-prefix/manifest.yaml
  internal/kgateway/translator/irtranslator/route.go
Labels: release-note, kind/fix

#11405 Update Envoy to adopt Ubuntu 24.04
  Makefile
Labels: release-note-none, kind/fix

#11433 .github/workflows: Simplify job names in unit test workflow
  .github/workflows/pr-unit-tests.yaml
Labels: kind/cleanup, release-note-none

#11443 fix tests
  internal/kgateway/setup/testdata/standard/csrf-gw-out.yaml
  internal/kgateway/setup/testdata/standard/csrf-route-out.yaml
  internal/kgateway/setup/testdata/standard/csrf-route-shadowed-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/http-routing-invalid-prefix/manifest.yaml
Labels: kind/cleanup, release-note-none

#11442 api/aws: clarify implicit authentication method
  api/v1alpha1/backend_types.go
  design/10573.md
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/cleanup, release-note-none

#11407 [v2.0.x] Bump envoy 1.34.1 patch3
  Makefile
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  internal/envoyinit/hack/filter_types/filter_types.gen.go
  internal/envoyinit/rustformations/Cargo.lock
  internal/envoyinit/rustformations/Cargo.toml
  internal/envoyinit/rustformations/src/lib.rs
  internal/kgateway/extensions2/plugins/routepolicy/route_policy_plugin.go
  internal/kgateway/extensions2/plugins/routepolicy/transformation_plugin.go
Labels: release-note, do-not-merge/kind-invalid

#11440 remove HeadersWithUnderscoresAction from BackendConfigPolicy
  api/applyconfiguration/api/v1alpha1/commonhttpprotocoloptions.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin_test.go
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-alias-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-alias.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-label-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-label.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-tls-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-tls.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy.yaml
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/lb-config.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backendconfigpolicy/lb-config.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/backendconfigpolicy/testdata/setup.yaml
Labels: kind/cleanup, release-note

#11414 Inference Extension: Use single shared extproc filter
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/setup/testdata/inference_api/inferencepool-basic-out.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-basic.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-multi-route-single-pool-out.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-multi-route-single-pool.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-single-route-multi-pool-out.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-single-route-multi-pool.yaml
Labels: kind/bug_fix

#11449 BackendConfigPolicy : dont apply http1 options to http2 backend
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin_test.go
  test/kubernetes/e2e/features/backendconfigpolicy/suite.go
  test/kubernetes/e2e/features/backendconfigpolicy/testdata/setup.yaml
Labels: release-note, kind/fix

#11463 feat: Support custom envoy container environment variables
  api/applyconfiguration/api/v1alpha1/envoycontainer.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/gateway_parameters_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
  internal/kgateway/deployer/deployer.go
  internal/kgateway/deployer/deployer_test.go
  internal/kgateway/deployer/merge.go
  internal/kgateway/deployer/values.go
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release-note, kind/feature

#11467 refactor: Extract HTTP protocol options handling into separate file
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/protocoloptions.go
Labels: kind/cleanup, release-note-none

#11430 ai mock: fix gemini endpoint
  test/mocks/mock-ai-provider-server/main.go
Labels: kind/cleanup, release-note-none

#11346 support for extra GatewayParameters
  examples/plugin/main.go
  internal/kgateway/controller/controller.go
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/deployer/deployer.go
  internal/kgateway/deployer/deployer_test.go
  internal/kgateway/deployer/gateway_parameters.go
  internal/kgateway/deployer/gateway_parameters_test.go
  internal/kgateway/setup/setup.go
  pkg/setup/setup.go
  test/envtestutil/util.go
Labels: control-plane-parity, release-note, kind/feature

#11478 pluginsdk: move TargetRef util to exported pkg
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  pkg/pluginsdk/utils/policy.go
Labels: kind/cleanup, release-note-none

#11475 trafficpolicy: Preserve policy errors during route translation
  internal/kgateway/extensions2/plugins/trafficpolicy/merge_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
Labels: kind/cleanup, release-note-none

#11460 cancel existing builds before running new
  .github/workflows/action_lint.yaml
  .github/workflows/conformance-tests.yaml
  .github/workflows/lint-helm.yaml
  .github/workflows/lint-python.yaml
  .github/workflows/lint-rust.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/pr-kubernetes-tests.yaml
  .github/workflows/pr-unit-tests.yaml
  .github/workflows/regression-tests.yaml
  .github/workflows/static-analysis.yaml
Labels: kind/cleanup, release-note-none

#11487 Remove the github.com/saiskee/gettercheck tool
  Makefile
  go.mod
  go.sum
Labels: kind/cleanup, release-note-none

#11393 backendconfigpolicy: healthcheck
  api/applyconfiguration/api/v1alpha1/backendconfigpolicyspec.go
  api/applyconfiguration/api/v1alpha1/healthcheck.go
  api/applyconfiguration/api/v1alpha1/healthcheckgrpc.go
  api/applyconfiguration/api/v1alpha1/healthcheckhttp.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/healthcheck.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/healthcheck_test.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/healthcheck.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backendconfigpolicy/healthcheck.yaml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release-note, kind/feature

#11491 api/validation: use kubebuilder OneOf constraints
  .github/workflows/pr-kubernetes-tests.yaml
  api/applyconfiguration/api/v1alpha1/awsbackend.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/ai_backend.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/backend_types.go
  api/v1alpha1/gateway_parameters_types.go
  api/v1alpha1/http_listener_policy_types.go
  api/v1alpha1/shared_types.go
  api/v1alpha1/traffic_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_directresponses.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayextensions.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_httplistenerpolicies.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/api/v1alpha1/api_client.go
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/tests/api_validation_test.go
Labels: kind/cleanup, release-note-none

#11492 Makefile: Remove unused targets
  Makefile
Labels: kind/cleanup, release-note-none

#11377 Make it possible to reuse Deployer
  examples/plugin/main.go
  internal/kgateway/controller/controller.go
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/gw_controller.go
  internal/kgateway/controller/inferencepool_controller.go
  internal/kgateway/controller/inferencepool_controller_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/deployer/charts.go
  internal/kgateway/deployer/deployer.go
  internal/kgateway/deployer/deployer_factory.go
  internal/kgateway/deployer/gateway_parameters.go
  internal/kgateway/deployer/gateway_parameters_test.go
  internal/kgateway/deployer/inference_extension.go
  internal/kgateway/extensions2/settings/settings.go
  internal/kgateway/setup/agentgateway_test.go
  internal/kgateway/setup/setup.go
  internal/kgateway/setup/setup_test.go
  internal/kgateway/translator/irtranslator/backend.go
  internal/kgateway/utils/krtutil/options.go
  pkg/deployer/deployer.go
  pkg/deployer/deployer_suite_test.go
  pkg/deployer/deployer_test.go
  pkg/deployer/errors.go
  pkg/deployer/gateway_getter.go
  pkg/deployer/gateway_parameters.go
  pkg/deployer/helm_values_generator.go
  pkg/deployer/merge.go
  pkg/deployer/merge_test.go
  pkg/deployer/values.go
  pkg/deployer/values_helpers.go
  pkg/deployer/values_helpers_test.go
  pkg/deployer/wellknown.go
  pkg/pluginsdk/collections/collections.go
  pkg/pluginsdk/krtutil/options.go
  pkg/settings/settings.go
  pkg/settings/settings_test.go
  pkg/setup/setup.go
  test/envtestutil/util.go
  test/translator/test.go
Labels: kind/cleanup, release-note

#11455 backendconfigpolicy: http2 protocol options
  api/applyconfiguration/api/v1alpha1/backendconfigpolicyspec.go
  api/applyconfiguration/api/v1alpha1/http2protocoloptions.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin_test.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/protocoloptions.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/http2.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backendconfigpolicy/http2.yaml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release-note, kind/feature

#11505 allow setting per connection buffer limit on Gateway with annotation
  api/annotations/gateway.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/translator/gateway/gateway_translator.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/gateway-per-conn-buf-lim/gateway.yaml
  internal/kgateway/translator/gateway/testutils/outputs/gateway-per-conn-buf-lim/proxy.yaml
  internal/kgateway/translator/irtranslator/gateway.go
  pkg/pluginsdk/ir/backend.go
  pkg/pluginsdk/ir/gw2.go
Labels: release-note, kind/feature

#11506 api: Replace CEL validation with AtMostOneOf marker for HTTP protocol options
  api/v1alpha1/backend_config_policy_types.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/tests/api_validation_test.go
Labels: kind/cleanup, release-note-none

#11227 EP-10625: Invalid Route Replacement
  design/10625.md
Labels: kind/design, release-note-none

#11527 api: Remove unused Extended enum value from GatewayExtensionType
  api/v1alpha1/gateway_extensions_types.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayextensions.yaml
Labels: kind/cleanup, release-note-none

#11462 Add new fields to HCM config on HTTPListenerPolicy
  .github/workflows/pr-kubernetes-tests.yaml
  api/applyconfiguration/api/v1alpha1/httplistenerpolicyspec.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/http_listener_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  examples/example-http-listener-policy-with-additional-fields.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_httplistenerpolicies.yaml
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/http_listener_policy/suite.go
  test/kubernetes/e2e/features/http_listener_policy/testdata/gateway.yaml
  test/kubernetes/e2e/features/http_listener_policy/testdata/http-listener-policy-all-fields.yaml
  test/kubernetes/e2e/features/http_listener_policy/testdata/http-listener-policy-server-header.yaml
  test/kubernetes/e2e/features/http_listener_policy/testdata/httproute.yaml
  test/kubernetes/e2e/features/http_listener_policy/testdata/setup.yaml
  test/kubernetes/e2e/features/http_listener_policy/types.go
  test/kubernetes/e2e/tests/kgateway_tests.go
Labels: release-note, kind/feature

#11510 Refactor to use names from startup config
  examples/plugin/main.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/controller/controller.go
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/deployer/gateway_parameters.go
  internal/kgateway/deployer/gateway_parameters_test.go
  internal/kgateway/extensions2/plugins/waypoint/plugin.go
  internal/kgateway/extensions2/registry/registry.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/reports/reporter_test.go
  internal/kgateway/setup/setup.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/httproute/translate_httproute_test.go
  internal/kgateway/wellknown/controller.go
  pkg/deployer/deployer_test.go
  pkg/deployer/gateway_parameters.go
  pkg/setup/setup.go
  test/envtestutil/util.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#11539 Inference: Bumps CRDs
  internal/kgateway/crds/inferencemodels.yaml
  internal/kgateway/crds/inferencepools.yaml
Labels: kind/cleanup, release-note
