Repository kgateway-dev/kgateway, pull requests merged in 2025-10, with the labels that each got.

#11777 EP-10553: Support Leader Election
  design/10553.md
Labels: kind/design, release-note-none

#12471 xDS: enable JWT based auth by default
  api/settings/settings.go
  api/settings/settings_test.go
  api/v1alpha1/shared_types.go
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  install/helm/kgateway/templates/role.yaml
  internal/kgateway/helm/kgateway/templates/gateway/agent-gateway-deployment.yaml
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
  internal/kgateway/krtcollections/uniqueclients.go
  internal/kgateway/krtcollections/uniqueclients_test.go
  internal/kgateway/setup/agentgateway_test.go
  internal/kgateway/setup/authn.go
  internal/kgateway/setup/controlplane.go
  internal/kgateway/setup/setup.go
  internal/kgateway/setup/setup_test.go
  internal/kgateway/xds/utils.go
  pkg/deployer/testdata/base-gateway-out.yaml
  pkg/deployer/testdata/omit-default-security-context-out.yaml
  pkg/deployer/wellknown.go
  pkg/metrics/metricstest/metricstest.go
  test/envtestutil/util.go
  test/kubernetes/e2e/features/metrics/suite.go
Labels: release-note, kind/feature

#11921 Tooling: Splits-Up `setup` Make Target
  Makefile
Labels: kind/cleanup, release-note

#12476 reorg deployer helm tests to allow for extendability
  internal/kgateway/controller/controller.go
  pkg/deployer/deployer_test.go
  pkg/deployer/internal_helm_test.go
  test/deployer/deployer_helm.go
  test/deployer/internal_helm_test.go
  test/deployer/testdata/agentgateway-out.yaml
  test/deployer/testdata/agentgateway.yaml
  test/deployer/testdata/base-gateway-out.yaml
  test/deployer/testdata/base-gateway.yaml
  test/deployer/testdata/omit-default-security-context-out.yaml
  test/deployer/testdata/omit-default-security-context.yaml
  test/deployer/testutils.go
Labels: kind/cleanup, release-note-none

#12420 Check controller names instead of gateway classnames when doing gateway status syncing
  internal/kgateway/agentgatewaysyncer/status_syncer.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/proxy_syncer/status_syncer.go
  pkg/agentgateway/translator/gateway_collection.go
  pkg/agentgateway/translator/gatewayclass_collection.go
Labels: release-note-none, kind/fix

#12473 pkg/deployer now exports more routines.
  pkg/deployer/merge.go
Labels: release-note, kind/feature

#12464 Deflake agw gateway obs generation
  internal/kgateway/agentgatewaysyncer/syncer.go
  pkg/agentgateway/translator/resources.go
  pkg/reports/reporter.go
Labels: release-note-none, kind/flake

#12446 refactor: add imports entry for api/settings
  .golangci.yaml
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/deployer/gateway_parameters_test.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/validate.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/validate_test.go
  internal/kgateway/extensions2/plugins/kubernetes/k8s.go
  internal/kgateway/extensions2/plugins/trafficpolicy/validate.go
  internal/kgateway/extensions2/plugins/waypoint/waypoint_translator.go
  internal/kgateway/extensions2/registry/registry.go
  internal/kgateway/krtcollections/endpoints.go
  internal/kgateway/krtcollections/grpc_route_test.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/policy_test.go
  internal/kgateway/krtcollections/setup.go
  internal/kgateway/query/query_test.go
  internal/kgateway/setup/agentgateway_test.go
  internal/kgateway/setup/setup.go
  internal/kgateway/setup/setup_test.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/irtranslator/backend.go
  internal/kgateway/translator/irtranslator/backend_test.go
  internal/kgateway/translator/irtranslator/gateway.go
  internal/kgateway/translator/irtranslator/route.go
  internal/kgateway/translator/irtranslator/validate.go
  pkg/pluginsdk/collections/collections.go
  test/deployer/testutils.go
  test/envtestutil/util.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#12472 deployer: add new standard `gateway-class-name` label
  internal/kgateway/deployer/gateway_parameters.go
  internal/kgateway/helm/kgateway/templates/_helpers.tpl
  internal/kgateway/helm/kgateway/templates/gateway/agent-gateway-deployment.yaml
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
  internal/kgateway/wellknown/controller.go
  pkg/deployer/values.go
  test/deployer/testdata/agentgateway-out.yaml
  test/deployer/testdata/base-gateway-out.yaml
  test/deployer/testdata/omit-default-security-context-out.yaml
Labels: release-note, kind/feature

#12502 cleanup: remove unused utils pkgs
  pkg/utils/awsutils/env.go
  pkg/utils/channelutils/channelutils_suite_test.go
  pkg/utils/channelutils/wait.go
  pkg/utils/channelutils/wait_test.go
  pkg/utils/errutils/concurrent.go
  pkg/utils/errutils/concurrent_test.go
  pkg/utils/errutils/errutils_suite_test.go
  pkg/utils/sliceutils/sliceutils.go
  pkg/utils/sliceutils/sliceutils_suite_test.go
  pkg/utils/sliceutils/sliceutils_test.go
Labels: kind/cleanup, release-note-none

#12503 e2e cleanup: remove upgrade tests
  test/kubernetes/e2e/features/upgrade/suite.go
  test/kubernetes/e2e/features/upgrade/testdata/manifests/secondary-gateway-namespace-validation.yaml
  test/kubernetes/e2e/features/upgrade/testdata/manifests/server-grpc-max-size-bytes.yaml
  test/kubernetes/e2e/features/upgrade/testdata/manifests/strict-validation.yaml
  test/kubernetes/e2e/tests/upgrade_test.go
  test/kubernetes/e2e/tests/upgrade_tests.go
  test/kubernetes/testutils/helper/util.go
  test/kubernetes/testutils/helper/util_test.go
Labels: kind/cleanup, release-note-none

#12506 e2e cleanup: remove server_tls suite
  test/kubernetes/e2e/features/server_tls/suite.go
  test/kubernetes/e2e/features/server_tls/testdata/tls-secret-1.yaml
  test/kubernetes/e2e/features/server_tls/testdata/tls-secret-2.yaml
  test/kubernetes/e2e/features/server_tls/testdata/tls-secret-with-ca.yaml
  test/kubernetes/e2e/features/server_tls/types.go
Labels: kind/cleanup, release-note-none

#12514 Make Bedrock model field optional to allow user-specified models
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/ai_backend.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml
  internal/kgateway/agentgatewaysyncer/backend/translate.go
  internal/kgateway/agentgatewaysyncer/backend/translate_test.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_backend.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release-note, kind/fix

#12489 fix(builtin plugin): don't set both PrefixRewrite and RegexRewrite
  internal/kgateway/krtcollections/builtin.go
  internal/kgateway/krtcollections/builtin_test.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/delegation/url_rewrite_inherit_parent_matcher.yaml
  internal/kgateway/translator/gateway/testutils/outputs/delegation/url_rewrite_inherit_parent_matcher.yaml
Labels: release-note-none, kind/fix

#12525 fix: always rendering volumemounts in proxy-deployment
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
Labels: release-note, kind/fix

#12526 fix: Merge probeHandler to ensure only one action is returned
  pkg/deployer/merge.go
  pkg/deployer/merge_test.go
Labels: release-note, kind/fix

#12528 bump envoy-gloo to v1.35.2-patch4
  Makefile
  pkg/validator/validator.go
  pkg/validator/validator_test.go
Labels: kind/cleanup, release-note-none

#12527 Add options to GetContainerLogs
  pkg/utils/kubeutils/kubectl/cli.go
  pkg/utils/kubeutils/kubectl/logs_options.go
  pkg/utils/kubeutils/kubectl/logs_options_test.go
Labels: kind/cleanup, release-note-none

#12540 agentgateway: disable a2a tests run in the suite due flakiness
  test/kubernetes/e2e/tests/agent_gateway_tests.go
Labels: release-note-none, kind/flake

#12543 fix typo in devel docs
  devel/contributing/pull-request-reviews.md
  devel/testing/writing-tests.md
Labels: release-note-none, kind/documentation
