Repository kgateway-dev/kgateway, pull requests merged in 2025-05, with the labels that each got.

#10422 Add EP-10381: Overhauling changelog process
  design/10381.md
Labels: kind/design

#11163 policy/api: allow attachment using targetSelectors
  .github/workflows/pr-kubernetes-tests.yaml
  api/applyconfiguration/api/v1alpha1/httplistenerpolicyspec.go
  api/applyconfiguration/api/v1alpha1/localpolicytargetselector.go
  api/applyconfiguration/api/v1alpha1/trafficpolicyspec.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/http_listener_policy_types.go
  api/v1alpha1/shared_types.go
  api/v1alpha1/traffic_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_httplistenerpolicies.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/extensions2/pluginutils/policy.go
  internal/kgateway/krtcollections/grpc_route.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/policy_test.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/label_based.yaml
  internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/label_based.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/pluginsdk/ir/gw.go
  test/kubernetes/e2e/features/policyselector/suite.go
  test/kubernetes/e2e/features/policyselector/testdata/label_selector.yaml
  test/kubernetes/e2e/features/policyselector/types.go
  test/kubernetes/e2e/tests/kgateway_tests.go
Labels: release-note-needed, kind/new_feature

#11212 backends: use aliases for refs
  internal/kgateway/extensions2/plugin/plugin.go
  internal/kgateway/extensions2/plugins/serviceentry/backendref.go
  internal/kgateway/extensions2/plugins/serviceentry/backends.go
  internal/kgateway/extensions2/plugins/serviceentry/collections.go
  internal/kgateway/extensions2/plugins/serviceentry/plugin.go
  internal/kgateway/extensions2/plugins/waypoint/waypointquery/service_model.go
  internal/kgateway/krtcollections/grpc_route_test.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/policy_test.go
  internal/kgateway/krtcollections/setup.go
  internal/kgateway/query/query_test.go
  internal/kgateway/setup/testdata/serviceentry/dr/se-hostname-ref-out.yaml
  internal/kgateway/setup/testdata/serviceentry/dr/se-hostname-ref-polattach-out.yaml
  internal/kgateway/setup/testdata/serviceentry/dr/se-hostname-ref-polattach.yaml
  internal/kgateway/setup/testdata/serviceentry/dr/se-hostname-ref.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backend-plugin-proxy.yaml
  internal/kgateway/translator/gateway/testutils/test_translator.go
  internal/kgateway/wellknown/istio.go
  pkg/pluginsdk/ir/backend.go
  pkg/pluginsdk/types.go
Labels: release-note, kind/fix

#11216 turn off ambient DNS for waypoints by default
  internal/kgateway/deployer/deployer.go
Labels: release-note, kind/fix

#11234 feat: add tests for `fsutils`
  pkg/utils/fsutils/fsutils_test.go
Labels: release-note-none, kind/feature

#11238 multi-install: enable per-namespace install and resource discovery
  .github/workflows/pr-kubernetes-tests.yaml
  examples/plugin/main.go
  hack/generate.sh
  install/helm/kgateway/templates/deployment.yaml
  install/helm/kgateway/templates/inf_ext_rbac.yaml
  install/helm/kgateway/templates/role.yaml
  install/helm/kgateway/templates/serviceaccount.yaml
  install/helm/kgateway/values.yaml
  internal/kgateway/controller/controller.go
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/extensions2/plugins/backendtlspolicy/plugin.go
  internal/kgateway/extensions2/plugins/destrule/destrule.go
  internal/kgateway/extensions2/plugins/directresponse/direct_response_plugin.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/plugins/kubernetes/k8s.go
  internal/kgateway/extensions2/plugins/serviceentry/collections.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/extensions2/settings/settings.go
  internal/kgateway/extensions2/settings/settings_test.go
  internal/kgateway/krtcollections/gateway_extensions.go
  internal/kgateway/krtcollections/ns.go
  internal/kgateway/krtcollections/pods.go
  internal/kgateway/krtcollections/setup.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/discovery-namespace-selector/base.yaml
  internal/kgateway/translator/gateway/testutils/outputs/discovery-namespace-selector/base_select_all.yaml
  internal/kgateway/translator/gateway/testutils/outputs/discovery-namespace-selector/base_select_infra.yaml
  internal/kgateway/translator/gateway/testutils/test_translator.go
  pkg/pluginsdk/collections/collections.go
  pkg/pluginsdk/collections/discovery.go
  pkg/utils/helmutils/client.go
  pkg/utils/kubeutils/kubectl/cli.go
  test/gomega/matchers/pod.go
  test/kubernetes/e2e/features/multiinstall/suite.go
  test/kubernetes/e2e/features/multiinstall/testdata/basic.yaml
  test/kubernetes/e2e/features/multiinstall/types.go
  test/kubernetes/e2e/test.go
  test/kubernetes/e2e/tests/manifests/multiple_installs_values1.yaml
  test/kubernetes/e2e/tests/manifests/multiple_installs_values2.yaml
  test/kubernetes/e2e/tests/multiple_installs_test.go
Labels: release-note, kind/feature

#11222 .github: Add helm chart linting to CI workflows (#10283)
  .github/workflows/README.md
  .github/workflows/lint-helm.yaml
  .github/workflows/release.yaml
  install/helm/kgateway-crds/Chart.yaml
  install/helm/kgateway/Chart.yaml
Labels: kind/cleanup, release-note-none

#11241 Add kgateway label to data plane pod
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
  test/kubernetes/e2e/features/deployer/suite.go
Labels: kind/cleanup, release-note

#11151 Agent gateway integration
  .github/actions/setup-kind-cluster/action.yaml
  .github/workflows/pr-kubernetes-tests.yaml
  Makefile
  api/applyconfiguration/api/v1alpha1/agentgateway.go
  api/applyconfiguration/api/v1alpha1/kubernetesproxyconfig.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/gateway_parameters_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  hack/generate.sh
  hack/kind/setup-kind.sh
  hack/utils/oss_compliance/osa_provided.md
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
  install/helm/kgateway/templates/deployment.yaml
  install/helm/kgateway/values.yaml
  internal/kgateway/agentgatewaysyncer/README.md
  internal/kgateway/agentgatewaysyncer/const.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/agentgatewaysyncer/syncer_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/deployer/deployer.go
  internal/kgateway/deployer/deployer_test.go
  internal/kgateway/deployer/merge.go
  internal/kgateway/deployer/values.go
  internal/kgateway/deployer/values_helpers.go
  internal/kgateway/extensions2/settings/settings.go
  internal/kgateway/extensions2/settings/settings_test.go
  internal/kgateway/helm/kgateway/templates/gateway/agent-gateway-deployment.yaml
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
  internal/kgateway/helm/kgateway/values.yaml
  internal/kgateway/krtcollections/setup.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/setup/agentgateway_test.go
  internal/kgateway/setup/setup_test.go
  internal/kgateway/wellknown/controller.go
  pkg/generated/openapi/zz_generated.openapi.go
  test/gomega/matchers/have_http_response.go
  test/kubernetes/e2e/features/agentgateway/a2a-example/Dockerfile
  test/kubernetes/e2e/features/agentgateway/a2a-example/README.md
  test/kubernetes/e2e/features/agentgateway/a2a-example/main.py
  test/kubernetes/e2e/features/agentgateway/a2a-example/pyproject.toml
  test/kubernetes/e2e/features/agentgateway/suite.go
  test/kubernetes/e2e/features/agentgateway/testdata/a2a.yaml
  test/kubernetes/e2e/features/agentgateway/testdata/agentgateway-deploy.yaml
  test/kubernetes/e2e/features/agentgateway/types.go
  test/kubernetes/e2e/file.go
  test/kubernetes/e2e/tests/agent_gateway_test.go
  test/kubernetes/e2e/tests/agent_gateway_tests.go
  test/kubernetes/e2e/tests/manifests/agent-gateway-integration.yaml
  test/kubernetes/testutils/assertions/curl.go
Labels: Type: Enhancement, release-note, kind/feature

#11224 Enable annotations to be set on `Deployment` in `kgateway` Helm chart
  install/helm/kgateway/templates/deployment.yaml
  install/helm/kgateway/values.yaml
Labels: release-note, kind/feature

#11244 logging: enable sloglint and make logs consistent
  .github/workflows/static-analysis.yaml
  .golangci.yaml
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  internal/kgateway/admin/server.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/agentgatewaysyncer/syncer_test.go
  internal/kgateway/endpoints/prioritize.go
  internal/kgateway/extensions2/plugins/backendtlspolicy/plugin.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/access_logging_converter.go
  internal/kgateway/extensions2/plugins/serviceentry/endpoints.go
  internal/kgateway/krtcollections/endpoints.go
  internal/kgateway/krtcollections/uniqueclients.go
  internal/kgateway/proxy_syncer/kube_gw_translator_syncer.go
  internal/kgateway/proxy_syncer/perclient.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/reports/reporter.go
  internal/kgateway/reports/status.go
  internal/kgateway/setup/controlplane.go
  internal/kgateway/translator/gateway/testutils/test_file_loader.go
  internal/kgateway/translator/httproute/delegation.go
  internal/kgateway/translator/irtranslator/fc.go
  internal/kgateway/translator/irtranslator/route.go
  internal/kgateway/translator/listener/gateway_listener_translator.go
  internal/kgateway/translator/translator.go
  internal/kgateway/utils/sanitize.go
  internal/sds/pkg/run/run.go
  internal/sds/pkg/run/run_main.go
  internal/sds/pkg/server/server.go
  pkg/utils/kubeutils/portforward/api_forwarder.go
  test/kubernetes/testutils/cluster/istio.go
Labels: kind/cleanup, release-note-none

#11247 fix tlsroute flake
  test/kubernetes/e2e/features/services/tlsroute/suite.go
Labels: release-note-none, kind/flake

#11249 enable local ratelimit test
  .github/workflows/pr-kubernetes-tests.yaml
  test/kubernetes/e2e/features/rate_limit/testdata/common.yaml
Labels: kind/cleanup, release-note-none

#11250 update kube dump on fail
  test/helpers/kube_dump.go
Labels: kind/cleanup, release-note-none

#11251 remove kube2e tests
  .github/actions/regression-tests/action.yaml
  .github/workflows/README.md
  .github/workflows/nightly-tests.yaml
  .github/workflows/regression-tests.yaml
  .gitignore
  Makefile
  devel/testing/kube-e2e-tests.md
  devel/testing/nightly-tests.md
  devel/testing/run-tests.md
  devel/testing/writing-tests.md
  test/kube2e/README.md
  test/kube2e/containers/testrunner/Dockerfile
  test/kube2e/containers/testrunner/root.crt
  test/kube2e/gateway/artifacts/helm.yaml
  test/kube2e/gateway/gateway_suite_test.go
  test/kube2e/gateway/gateway_test.go
  test/kube2e/gateway/robustness_test.go
  test/kube2e/gloo/artifacts/block-gloo-apiserver.yaml
  test/kube2e/gloo/artifacts/block-labels.yaml
  test/kube2e/gloo/artifacts/helm.yaml
  test/kube2e/gloo/bootstrap_clients_test.go
  test/kube2e/gloo/eds_test.go
  test/kube2e/gloo/generated_kube_types_test.go
  test/kube2e/gloo/gloo_resources_test.go
  test/kube2e/gloo/gloo_suite_test.go
  test/kube2e/gloo/happypath_test.go
  test/kube2e/gloo/kubernetes_test.go
  test/kube2e/gloo/setup_syncer_test.go
  test/kube2e/gloo/snapshot_writer_test.go
  test/kube2e/helper/curl.go
  test/kube2e/helper/curl_test.go
  test/kube2e/helper/docker/Dockerfile
  test/kube2e/helper/helper_suite_test.go
  test/kube2e/helper/http_echo.go
  test/kube2e/helper/install.go
  test/kube2e/helper/kube.go
  test/kube2e/helper/test_container.go
  test/kube2e/helper/test_container_test.go
  test/kube2e/helper/testserver.go
  test/kube2e/resource_clientset.go
  test/kube2e/upgrade/README.md
  test/kube2e/upgrade/testdata/helm.yaml
  test/kube2e/upgrade/testdata/petstorebase/petstore_deployment.yaml
  test/kube2e/upgrade/testdata/petstorebase/petstore_svc.yaml
  test/kube2e/upgrade/testdata/petstorebase/petstore_ups.yaml
  test/kube2e/upgrade/testdata/petstorevs/vs_postupgrade.yaml
  test/kube2e/upgrade/testdata/petstorevs/vs_preupgrade.yaml
  test/kube2e/upgrade/upgrade_data_validation_test.go
  test/kube2e/upgrade/upgrade_suite_test.go
  test/kube2e/upgrade/upgrade_test.go
  test/kube2e/util.go
  test/kubernetes/e2e/migrating_tests.md
Labels: kind/cleanup, release-note-none

#11246 Translate DestinationRule tcpKeepalive settings
  internal/kgateway/extensions2/plugins/destrule/destrule_plugin.go
  internal/kgateway/setup/testdata/istio_destination_rule/failover-default-diffns-out.yaml
  internal/kgateway/setup/testdata/istio_destination_rule/failover-default-diffns.yaml
  internal/kgateway/setup/testdata/istio_destination_rule/failover-default-out.yaml
  internal/kgateway/setup/testdata/istio_destination_rule/failover-default.yaml
  internal/kgateway/setup/testdata/istio_destination_rule/failover-out.yaml
  internal/kgateway/setup/testdata/istio_destination_rule/failover.yaml
Labels: release-note, kind/feature

#11257 linter: forbid usage of kclient.New to honor discoveryNamespaceSelectors
  .golangci.yaml
  internal/kgateway/krtcollections/setup.go
Labels: kind/cleanup, release-note-none

#11259 test: Update the Python base image in the A2A example image
  test/kubernetes/e2e/features/agentgateway/a2a-example/Dockerfile
Labels: release-note-none, kind/flake

#11243 allow re-using of traffic policies
  internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extproc_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/transformation_plugin.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/translator/irtranslator/route.go
  pkg/plugins/gwextbase/base.go
  pkg/pluginsdk/ir/iface.go
Labels: kind/cleanup, release-note-none

#11263 Bump gateway-api to v1.3.0
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/cleanup, release-note

#11260 docs: Add note about XDS service IP and steps for local debugging, README cleanup
  devel/debugging/local-controller.md
  test/kubernetes/e2e/README.md
Labels: kind/cleanup, release-note-none, kind/documentation

#11269 Fix typo in Waypoint Test yamls
  internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz-gateway-ref-fakegw.yaml
  internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz-gateway-ref.yaml
  internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz-gatewayclass-ref-nonrootns.yaml
  internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz-gatewayclass-ref.yaml
  internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz-multi-service.yaml
  internal/kgateway/extensions2/plugins/waypoint/testdata/input/authz.yaml
  internal/kgateway/extensions2/plugins/waypoint/testdata/input/httproute-gateway.yaml
  internal/kgateway/extensions2/plugins/waypoint/testdata/input/httproute-svc.yaml
  internal/kgateway/extensions2/plugins/waypoint/testdata/input/ns-use-waypoint.yaml
Labels: kind/cleanup, release-note-none

#11271 Remove .github/pull_request_template.md
  .github/pull_request_template.md
Labels: kind/cleanup, release-note-none

#11266 cleanup: use gateway api duration for better CEL validation.
  api/applyconfiguration/api/v1alpha1/ratelimitprovider.go
  api/applyconfiguration/api/v1alpha1/tokenbucket.go
  api/v1alpha1/gateway_extensions_types.go
  api/v1alpha1/traffic_policy_types.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayextensions.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
  internal/kgateway/extensions2/plugins/trafficpolicy/global_rate_limit_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/global_rate_limit_plugin_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/local_rate_limit_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
Labels: release-note, kind/feature

#11279 cleanup: only have section name in TrafficPolicies
  api/applyconfiguration/api/v1alpha1/localpolicytargetreference.go
  api/applyconfiguration/api/v1alpha1/localpolicytargetreferencewithsectionname.go
  api/applyconfiguration/api/v1alpha1/trafficpolicyspec.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/shared_types.go
  api/v1alpha1/traffic_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_httplistenerpolicies.yaml
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/extensions2/pluginutils/policy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/cleanup, release-note-none

#11280 Makefile: Add run target to automate dev environment setup
  Makefile
Labels: kind/cleanup, release-note-none

#11276 Onboarding doc updates
  devel/architecture/kgateway/DEV.md
  devel/testing/writing-tests.md
  devel/tilt/tilt.md
  test/kubernetes/e2e/debugging.md
Labels: release-note-none, kind/documentation

#11214 api: add BackendConfigPolicy api for configuring envoy clusters
  api/applyconfiguration/api/v1alpha1/backendconfigpolicy.go
  api/applyconfiguration/api/v1alpha1/backendconfigpolicyspec.go
  api/applyconfiguration/api/v1alpha1/commonhttpprotocoloptions.go
  api/applyconfiguration/api/v1alpha1/http1protocoloptions.go
  api/applyconfiguration/api/v1alpha1/tcpkeepalive.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.register.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  install/helm/kgateway/templates/role.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin_test.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/status.go
  internal/kgateway/extensions2/registry/registry.go
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy.yaml
  internal/kgateway/wellknown/kgw.go
  pkg/client/clientset/versioned/typed/api/v1alpha1/api_client.go
  pkg/client/clientset/versioned/typed/api/v1alpha1/backendconfigpolicy.go
  pkg/client/clientset/versioned/typed/api/v1alpha1/fake/fake_api_client.go
  pkg/client/clientset/versioned/typed/api/v1alpha1/fake/fake_backendconfigpolicy.go
  pkg/client/clientset/versioned/typed/api/v1alpha1/generated_expansion.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release-note, kind/feature

#11290 Avoid publishing GH releases for main branch pushes
  .github/workflows/release.yaml
  .goreleaser.yaml
Labels: kind/cleanup, release-note-none

#11289 feat: add TargetSelectors to BackendConfigPolicy
  api/applyconfiguration/api/v1alpha1/backendconfigpolicyspec.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-alias-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-alias.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-label-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-label.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/pluginsdk/ir/backend.go
Labels: release-note, kind/feature

#11297 plugins: export trafficpolicy merge, order plugin application
  internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/extensions2/plugins/waypoint/waypoint_translator_test.go
  internal/kgateway/krtcollections/builtin.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/irtranslator/fc.go
  internal/kgateway/translator/irtranslator/gateway.go
  internal/kgateway/translator/irtranslator/route.go
  pkg/plugins/gwextbase/base.go
  pkg/pluginsdk/ir/gw.go
  pkg/pluginsdk/ir/gw_test.go
  test/translator/file_loader.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#11307 policy: propagate ExtensionRef errors to PolicyAtt and fix reporting
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/translator/irtranslator/route.go
Labels: kind/cleanup, release-note-none

#11304 EP-11303 - Metric Naming Conventions
  design/11303.md
Labels: kind/design, release-note-none

#11311 copy spec addresses to status
  internal/kgateway/controller/gw_controller.go
Labels: release-note, kind/fix

#11310 add e2e test for backendconfigpolicy
  .github/workflows/pr-kubernetes-tests.yaml
  pkg/utils/envoyutils/admincli/client.go
  pkg/utils/envoyutils/admincli/clusters.go
  test/kubernetes/e2e/features/backendconfigpolicy/suite.go
  test/kubernetes/e2e/features/backendconfigpolicy/testdata/setup.yaml
  test/kubernetes/e2e/features/backendconfigpolicy/types.go
  test/kubernetes/e2e/tests/kgateway_tests.go
Labels: kind/cleanup, release-note-none

#11316 plugins: Remove redundant empty method implementations
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/extensions2/plugins/directresponse/direct_response_plugin.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
Labels: kind/cleanup, release-note-none

#11198 support: http upgrades
  Makefile
  api/applyconfiguration/api/v1alpha1/httplistenerpolicyspec.go
  api/applyconfiguration/api/v1alpha1/upgradeconfig.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/http_listener_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_httplistenerpolicies.yaml
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/https-listener-pol/upgrades.yaml
  internal/kgateway/translator/gateway/testutils/inputs/https-listener-pol/ws-backend.yaml
  internal/kgateway/translator/gateway/testutils/outputs/https-listener-pol/upgrades.yaml
  internal/kgateway/translator/gateway/testutils/outputs/https-listener-pol/ws-backend.yaml
  internal/kgateway/translator/irtranslator/route.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/pluginsdk/ir/backend.go
Labels: release-note, kind/feature

#11299 calculate backend name on ctor
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/plugins/kubernetes/k8s.go
  internal/kgateway/extensions2/plugins/serviceentry/backends.go
  internal/kgateway/krtcollections/endpoints_test.go
  internal/kgateway/krtcollections/grpc_route_test.go
  internal/kgateway/krtcollections/policy_test.go
  pkg/pluginsdk/ir/backend.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none
