Repository kgateway-dev/kgateway, pull requests merged in 2025-08, with the labels that each got.

#11807 make envtest fast
  internal/kgateway/setup/setup.go
  internal/kgateway/setup/setup_test.go
  test/envtestutil/util.go
Labels: kind/cleanup, release-note-none

#11810 Inference: Refactor Plugin for Static + Subset LB Clusters
  Makefile
  go.mod
  go.sum
  hack/kind/setup-kind.sh
  hack/utils/oss_compliance/osa_provided.md
  internal/kgateway/crds/inferencemodels.yaml
  internal/kgateway/crds/inferencepools.yaml
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/backends.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/backends_test.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/collections.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/ir.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/ir_test.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin_test.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/status.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/validation.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/validation_test.go
  internal/kgateway/setup/testdata/inference_api/inferencepool-basic-out.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-basic.yaml
  test/kubernetes/e2e/features/inferenceextension/testdata/epp.yaml
  test/kubernetes/e2e/features/inferenceextension/testdata/pool.yaml
Labels: kind/cleanup, release-note, kind/feature

#11869 translator test flake fix
  internal/kgateway/krtcollections/policy.go
Labels: release-note-none, kind/flake

#11873 Attempt to fix flake CSRF tests
  test/kubernetes/e2e/features/csrf/suite.go
Labels: release-note-none, kind/flake

#11836 backendconfigpolicy: add option to preserve http1 header casing
  api/applyconfiguration/api/v1alpha1/http1protocoloptions.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/http_listener_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin_test.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/protocoloptions.go
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/lb-config.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backendconfigpolicy/lb-config.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/http_listener_policy/suite.go
  test/kubernetes/e2e/features/http_listener_policy/testdata/preserve-http1-header-case.yaml
Labels: release-note, kind/feature, kind/fix

#11770 fix(metrics): cleanup some metrics interfaces, docs, and improve tests
  devel/metrics/README.md
  internal/kgateway/controller/controller.go
  internal/kgateway/controller/gatewayclass_provisioner.go
  internal/kgateway/controller/gw_controller.go
  internal/kgateway/controller/inferencepool_controller.go
  internal/kgateway/controller/metrics.go
  internal/kgateway/controller/metrics_test.go
  internal/kgateway/krtcollections/metrics.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/setup.go
  internal/kgateway/proxy_syncer/metrics.go
  internal/kgateway/proxy_syncer/metrics_test.go
  internal/kgateway/proxy_syncer/perclient.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/setup/setup_test.go
  internal/kgateway/translator/gateway/gateway_translator.go
  internal/kgateway/translator/httproute/gateway_http_route_translator.go
  internal/kgateway/translator/irtranslator/backend.go
  internal/kgateway/translator/irtranslator/gateway.go
  internal/kgateway/translator/irtranslator/metrics_test.go
  internal/kgateway/translator/listener/gateway_listener_translator.go
  internal/kgateway/translator/metrics/metrics.go
  internal/kgateway/translator/metrics/metrics_test.go
  pkg/metrics/metricstest/metricstest.go
  test/kubernetes/e2e/features/metrics/suite.go
Labels: kind/cleanup, release-note-none

#11861 Move away from knative dependency
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/agentgatewaysyncer/conversion.go
  internal/kgateway/agentgatewaysyncer/gateway_collection.go
  internal/kgateway/agentgatewaysyncer/model.go
  internal/kgateway/agentgatewaysyncer/policy_collections.go
  internal/kgateway/agentgatewaysyncer/route_collections.go
  internal/kgateway/agentgatewaysyncer/route_collections_test.go
  internal/kgateway/agentgatewaysyncer/service.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/agentgatewaysyncer/workloads.go
  internal/kgateway/controller/start.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/plugins/kubernetes/k8s.go
  internal/kgateway/extensions2/plugins/waypoint/waypointquery/service_model.go
  pkg/utils/kubeutils/dns.go
  pkg/utils/kubeutils/domain.go
  pkg/utils/kubeutils/domain_test.go
  test/kubernetes/e2e/features/waypoint/curl_helper.go
Labels: kind/cleanup, release-note

#11876 Add basic route replacement e2e suite
  .github/workflows/pr-kubernetes-tests.yaml
  test/kubernetes/e2e/defaults/defaults.go
  test/kubernetes/e2e/defaults/testdata/httpbin.yaml
  test/kubernetes/e2e/features/routereplacement/suite.go
  test/kubernetes/e2e/features/routereplacement/testdata/setup.yaml
  test/kubernetes/e2e/features/routereplacement/testdata/strict-mode-invalid-policy.yaml
  test/kubernetes/e2e/features/routereplacement/types.go
  test/kubernetes/e2e/tests/kgateway_tests.go
  test/kubernetes/testutils/assertions/objects.go
Labels: kind/cleanup, release-note-none

#11875 Fix flake SDS test
  internal/sds/pkg/run/run_e2e_test.go
  internal/sds/pkg/server/server.go
Labels: release-note-none, kind/flake

#11900 add gwext name to error message
  internal/kgateway/extensions2/plugins/trafficpolicy/constructor.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
Labels: kind/cleanup, release-note-none

#11910 Fix BackendConfigPolicy e2e flake
  test/kubernetes/e2e/features/backendconfigpolicy/suite.go
Labels: release-note-none, kind/flake

#11880 Refactor AgentGateway backend plugins and re-use BackendIndex in agentgw syncer
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/agentgatewaysyncer/conversion.go
  internal/kgateway/agentgatewaysyncer/plugins/builtin/builtin.go
  internal/kgateway/agentgatewaysyncer/route_collections.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/extensions2/plugins/backend/agentgateway/ai_backend.go
  internal/kgateway/extensions2/plugins/backend/agentgateway/ir.go
  internal/kgateway/extensions2/plugins/backend/agentgateway/mcp.go
  internal/kgateway/extensions2/plugins/backend/agentgateway/plugin.go
  internal/kgateway/extensions2/plugins/backend/agentgateway/static.go
  internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go
  internal/kgateway/extensions2/plugins/backend/agentgateway_mcp.go
  internal/kgateway/extensions2/plugins/backend/agentgateway_static.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_agentgateway_backend.go
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/setup/setup_test.go
  pkg/agentgateway/ir/context.go
  pkg/agentgateway/ir/interfaces.go
  pkg/agentgateway/translator/backend_translator.go
  pkg/agentgateway/translator/translator.go
  pkg/pluginsdk/ir/gw.go
  pkg/pluginsdk/ir/iface.go
  pkg/pluginsdk/types.go
Labels: kind/cleanup, release-note-none

#11925 Updated the misleading error message
  internal/kgateway/extensions2/plugins/trafficpolicy/constructor.go
Labels: kind/cleanup, release-note-none

#11920 httplistenerpolicy: replace deprecated ExactMatch with StringMatch
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/translator/gateway/testutils/outputs/httplistenerpolicy/merge.yaml
  internal/kgateway/translator/gateway/testutils/outputs/httplistenerpolicy/route-and-pol.yaml
Labels: release-note-none, kind/fix

#11913 Add TopologySpreadConstraints to Pod kube_types
  api/applyconfiguration/api/v1alpha1/pod.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/kube_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
  internal/kgateway/deployer/gateway_parameters.go
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
  pkg/deployer/deployer_test.go
  pkg/deployer/merge.go
  pkg/deployer/values.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release-note, kind/feature

#11938 test/translator: convert to stdlib Go test
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/status_test.go
  internal/kgateway/translator/gateway/translator_suite_test.go
  test/translator/assertions.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#11948 remove legacy in-memory e2e tests
  devel/testing/e2e-tests.md
  test/e2e/README.md
  test/e2e/aggregate_listener_test.go
  test/e2e/aws_ec2_test.go
  test/e2e/aws_test.go
  test/e2e/buffer_test.go
  test/e2e/connection_limit_test.go
  test/e2e/consul_test.go
  test/e2e/cors_test.go
  test/e2e/csrf_test.go
  test/e2e/custom_auth_test.go
  test/e2e/dns_test.go
  test/e2e/dynamic_forward_proxy_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/envoyconfigs/zipkin-envoy-conf.yaml
  test/e2e/example_test.go
  test/e2e/fault_injection_test.go
  test/e2e/gateway_test.go
  test/e2e/global_ratelimit_test.go
  test/e2e/grpc_discovery_test.go
  test/e2e/grpc_json_test.go
  test/e2e/grpc_plugin_test.go
  test/e2e/gzip_test.go
  test/e2e/happypath_test.go
  test/e2e/header_validation_test.go
  test/e2e/headers_test.go
  test/e2e/health_checks_test.go
  test/e2e/http_tunneling_test.go
  test/e2e/hybrid_test.go
  test/e2e/loadbalancer_plugin_test.go
  test/e2e/local_ratelimit_test.go
  test/e2e/proxy_protocol_test.go
  test/e2e/ratelimit_test.go
  test/e2e/route_transformation_test.go
  test/e2e/staged_transformation_test.go
  test/e2e/tcp_stats_test.go
  test/e2e/test_context.go
  test/e2e/tls_ocsp_test.go
  test/e2e/vault_aws_test.go
  test/e2e/vault_test.go
  test/e2e/zipkin_test.go
  test/kubernetes/e2e/features/extauth/testdata/ext-authz-server.yaml
Labels: kind/cleanup, release-note-none

#11949 Fix data race with writer trying to log after test cleanup
  internal/kgateway/setup/agentgateway_test.go
  internal/kgateway/setup/setup_test.go
Labels: release-note-none, kind/flake

#11950 Log error if failed to start a test SDS server
  internal/sds/pkg/run/run_e2e_test.go
Labels: release-note-none, kind/flake

#11894 Docs: Update Releasing Guide for GW API Bump
  devel/contributing/releasing.md
Labels: release-note-none, kind/documentation

#11933 initial agw bedrock support
  api/applyconfiguration/api/v1alpha1/awsguardrailconfig.go
  api/applyconfiguration/api/v1alpha1/bedrockconfig.go
  api/applyconfiguration/api/v1alpha1/supportedllmprovider.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/ai_backend.go
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml
  internal/kgateway/agentgatewaysyncer/agentgateway_translator_test.go
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend-protocol/bedrock-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend-protocol/bedrock-backend.yaml
  internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go
  internal/kgateway/extensions2/plugins/backend/agentgateway/translate_test.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_backend.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster.go
  internal/kgateway/extensions2/plugins/backend/aws.go
  internal/kgateway/wellknown/constants.go
  pkg/deployer/wellknown.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release-note, kind/feature

#11853 Moved internal/kgateway/utils/krtutil/index.go to pkg/
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/agentgatewaysyncer/gateway_collection.go
  internal/kgateway/agentgatewaysyncer/gatewayclass_collection.go
  internal/kgateway/agentgatewaysyncer/references_collection.go
  internal/kgateway/agentgatewaysyncer/route_collections.go
  internal/kgateway/agentgatewaysyncer/route_collections_test.go
  internal/kgateway/agentgatewaysyncer/service.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/agentgatewaysyncer/workloads.go
  internal/kgateway/controller/start.go
  internal/kgateway/extensions2/plugins/destrule/destrule.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/backends_test.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/collections.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/ir_test.go
  internal/kgateway/extensions2/plugins/kubernetes/k8s.go
  internal/kgateway/extensions2/plugins/serviceentry/backends.go
  internal/kgateway/extensions2/plugins/serviceentry/collections.go
  internal/kgateway/extensions2/plugins/serviceentry/endpoints.go
  internal/kgateway/extensions2/plugins/waypoint/waypointquery/waypoint_authz.go
  internal/kgateway/extensions2/plugins/waypoint/waypointquery/waypoint_query.go
  internal/kgateway/krtcollections/endpoints.go
  internal/kgateway/krtcollections/endpoints_test.go
  internal/kgateway/krtcollections/gateway_extensions.go
  internal/kgateway/krtcollections/grpc_route_test.go
  internal/kgateway/krtcollections/ns.go
  internal/kgateway/krtcollections/pods.go
  internal/kgateway/krtcollections/pods_test.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/policy_test.go
  internal/kgateway/krtcollections/setup.go
  internal/kgateway/krtcollections/uniqueclients.go
  internal/kgateway/krtcollections/uniqueclients_test.go
  internal/kgateway/proxy_syncer/backends.go
  internal/kgateway/proxy_syncer/cla.go
  internal/kgateway/proxy_syncer/metrics_test.go
  internal/kgateway/proxy_syncer/perclient.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/query/query_test.go
  pkg/utils/krtutil/index.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#11958 Added tolerations for agent gateway deployment template
  internal/kgateway/helm/kgateway/templates/gateway/agent-gateway-deployment.yaml
Labels: release-note-none, kind/fix

#11942 Upgrade go mod deps and cleanup
  Makefile
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  test/kubernetes/e2e/README.md
  test/kubernetes/e2e/debugging.md
Labels: kind/cleanup, release-note-none

#11973 upgrade to go 1.24.6
  go.mod
  hack/utils/applier/go.mod
  hack/utils/applier/go.sum
  test/mocks/mock-ai-provider-server/go.mod
Labels: kind/cleanup, release-note-none

#11990 use Go patch version in submodules
  hack/utils/applier/go.mod
  test/mocks/mock-ai-provider-server/go.mod
Labels: kind/cleanup, release-note-none

#11976 upgrade helm to v3.18.4
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
Labels: kind/cleanup, release-note-none

#11991 agentgateway: fix MCP backend filter
  internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go
Labels: release-note-none, kind/fix

#11974 Add bedrock example
  internal/kgateway/agentgatewaysyncer/README.md
Labels: release-note-none, kind/documentation

#11970 trafficpolicy: add timeout and retry policies
  .github/workflows/pr-kubernetes-tests.yaml
  api/applyconfiguration/api/v1alpha1/localpolicytargetselectorwithsectionname.go
  api/applyconfiguration/api/v1alpha1/retry.go
  api/applyconfiguration/api/v1alpha1/timeouts.go
  api/applyconfiguration/api/v1alpha1/trafficpolicyspec.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/shared_types.go
  api/v1alpha1/traffic_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
  internal/kgateway/extensions2/plugins/trafficpolicy/constructor.go
  internal/kgateway/extensions2/plugins/trafficpolicy/cors_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/merge.go
  internal/kgateway/extensions2/plugins/trafficpolicy/timeout_retry.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/krtcollections/builtin.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/httproute-timeout-retry/builtin.yaml
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/timeout-retry.yaml
  internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/timeout-retry.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/pluginsdk/policy/cors.go
  pkg/pluginsdk/policy/cors_test.go
  pkg/pluginsdk/policy/retry.go
  pkg/pluginsdk/policy/retry_test.go
  pkg/pluginsdk/utils/policy.go
  test/kubernetes/e2e/features/timeoutretry/suite.go
  test/kubernetes/e2e/features/timeoutretry/testdata/setup.yaml
  test/kubernetes/e2e/features/timeoutretry/types.go
  test/kubernetes/e2e/tests/api_validation_test.go
  test/kubernetes/e2e/tests/kgateway_tests.go
Labels: work in progress, release-note, kind/feature

#11992 translator: Add separate reasons for dropping vs replacing invalid routes
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/irtranslator/route.go
  pkg/pluginsdk/reporter/types.go
  test/translator/assertions.go
Labels: kind/cleanup, release-note-none, kind/fix

#11996 Dev docs cleanup part 2
  devel/README.md
  devel/architecture/metrics.md
  devel/architecture/overview.md
  devel/contributing/automation.md
  devel/contributing/backports.md
  devel/contributing/code-generation.md
  devel/contributing/documentation.md
  devel/contributing/pull-requests.md
  devel/debugging/envoy-segfault.md
  devel/debugging/tilt.md
  devel/security/README.md
  devel/testing/aws-tests.md
  devel/testing/flaky-tests.md
  devel/testing/run-tests.md
  devel/testing/writing-tests.md
  tilt-settings.yaml
Labels: kind/cleanup, release-note-none

#12004 flake: add assertions gw and httproute accepted
  test/kubernetes/e2e/features/csrf/suite.go
Labels: release-note-none, kind/flake

#12002 flake: Add accepted route checks to TestMatcherInheritance test
  test/kubernetes/e2e/features/route_delegation/suite.go
Labels: release-note-none, kind/flake

#12001 deflake: agw backend translator test collections
  internal/kgateway/extensions2/plugins/backend/agentgateway/translate_test.go
Labels: release-note-none, kind/flake

#11890 feat: Add support for leader election
  .github/workflows/pr-kubernetes-tests.yaml
  api/v1alpha1/doc.go
  install/helm/kgateway/templates/role.yaml
  internal/kgateway/agentgatewaysyncer/resources.go
  internal/kgateway/agentgatewaysyncer/status_syncer.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/controller/controller.go
  internal/kgateway/controller/gatewayclass_provisioner.go
  internal/kgateway/controller/gw_controller.go
  internal/kgateway/controller/start.go
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/registry/registry.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/proxy_syncer/status_syncer.go
  internal/kgateway/setup/setup.go
  internal/kgateway/wellknown/controller.go
  pkg/pluginsdk/types.go
  pkg/settings/settings.go
  pkg/settings/settings_test.go
  test/kubernetes/e2e/defaults/defaults.go
  test/kubernetes/e2e/features/agentgateway/suite.go
  test/kubernetes/e2e/features/agentgateway/types.go
  test/kubernetes/e2e/features/leaderelection/suite.go
  test/kubernetes/e2e/features/leaderelection/testdata/backend.yaml
  test/kubernetes/e2e/features/leaderelection/testdata/gateway.yaml
  test/kubernetes/e2e/features/leaderelection/testdata/route.yaml
  test/kubernetes/e2e/features/leaderelection/types.go
  test/kubernetes/e2e/features/routereplacement/suite.go
  test/kubernetes/e2e/tests/kgateway_tests.go
  test/kubernetes/testutils/assertions/status.go
Labels: release-note, kind/feature

#11881 [cleanup] Goroutine moinitor for tests using `envtest`
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/gatewayclass_provisioner_test.go
  internal/kgateway/controller/gw_controller_test.go
  internal/kgateway/controller/inferencepool_controller_test.go
  internal/kgateway/controller/metrics_test.go
  test/gomega/assertions/assertions_suite_test.go
  test/gomega/assertions/goroutines.go
  test/gomega/assertions/goroutines_test.go
Labels: kind/cleanup, release-note-none

#12011 add clarifying API docs for HLP useRemoteAddress
  api/v1alpha1/http_listener_policy_types.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/httplistenerpolicy/use-remote-addr-absent.yaml
  internal/kgateway/translator/gateway/testutils/inputs/httplistenerpolicy/use-remote-addr-false.yaml
  internal/kgateway/translator/gateway/testutils/inputs/httplistenerpolicy/use-remote-addr-true.yaml
  internal/kgateway/translator/gateway/testutils/outputs/httplistenerpolicy/use-remote-addr-absent.yaml
  internal/kgateway/translator/gateway/testutils/outputs/httplistenerpolicy/use-remote-addr-false.yaml
  internal/kgateway/translator/gateway/testutils/outputs/httplistenerpolicy/use-remote-addr-true.yaml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/cleanup, release-note-none

#12008 flake: bump timeout self managed gw test
  test/kubernetes/e2e/features/deployer/suite.go
Labels: release-note-none, kind/flake

#12030 flake: bump timeout for linter
  .github/workflows/static-analysis.yaml
Labels: release-note-none, kind/flake

#12024 Contributing guide cleanup
  CONTRIBUTING.md
  README.md
  devel/contributing/README.md
Labels: kind/cleanup, release-note-none

#12035 Update some ratelimit filter default values
  api/v1alpha1/gateway_extensions_types.go
  docs/global-rate-limiting.md
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayextensions.yaml
  internal/kgateway/extensions2/plugins/trafficpolicy/gateway_extension.go
  internal/kgateway/extensions2/plugins/trafficpolicy/global_rate_limit_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/global_rate_limit_plugin_test.go
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/rate-limit.yaml
  internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/rate-limit.yaml
Labels: kind/cleanup, release-note

#12016 Change source of the curl image
  test/kubernetes/e2e/defaults/testdata/curl_pod.yaml
  test/kubernetes/e2e/defaults/testdata/httpbin.yaml
  test/kubernetes/e2e/features/headless_svc/testdata/setup.yaml
  test/kubernetes/e2e/features/http_listener_options/testdata/setup.yaml
  test/kubernetes/e2e/features/http_listener_policy/testdata/setup.yaml
  test/kubernetes/e2e/features/inferenceextension/testdata/curl_pod.yaml
  test/kubernetes/e2e/features/istio/testdata/setup.yaml
  test/kubernetes/e2e/features/port_routing/testdata/setup.yaml
  test/kubernetes/e2e/features/route_options/testdata/setup.yaml
  test/kubernetes/e2e/features/services/httproute/testdata/route-with-service.yaml
  test/kubernetes/e2e/features/services/tcproute/testdata/cross-ns-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tcproute/testdata/cross-ns-no-refgrant-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tcproute/testdata/multi-listener-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tcproute/testdata/single-listener-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/cross-ns-no-refgrant-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/multi-listener-gateway-and-client.yaml
  test/kubernetes/e2e/features/services/tlsroute/testdata/single-listener-gateway-and-client.yaml
  test/kubernetes/e2e/features/waypoint/testdata/common/test_apps.yaml
Labels: kind/cleanup, release-note-none, kind/flake

#12072 Attempts to fix a data race.
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/ir.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
Labels: release-note-none, kind/fix

#12051 Fix leader election flake
  pkg/utils/kubeutils/kubectl/cli.go
  test/helpers/kube_dump.go
  test/kubernetes/e2e/features/leaderelection/suite.go
  test/kubernetes/e2e/test.go
Labels: release-note-none, kind/flake

#12062 agentgateway: separate policy collections
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/agentgatewaysyncer/agentgateway_translator_test.go
  internal/kgateway/agentgatewaysyncer/policy_collections.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend-protocol/a2a-backend.yaml
  internal/kgateway/controller/start.go
  internal/kgateway/setup/setup.go
  pkg/agentgateway/plugins/a2a_plugin.go
  pkg/agentgateway/plugins/inference_plugin.go
  pkg/agentgateway/plugins/interfaces.go
  pkg/agentgateway/plugins/manager.go
  pkg/agentgateway/plugins/registry.go
  pkg/agentgateway/plugins/traffic_plugin.go
  pkg/deployer/wellknown.go
  pkg/setup/setup.go
Labels: kind/cleanup, release-note

#12045 Support applying HPA for a gateway
  api/applyconfiguration/api/v1alpha1/proxydeployment.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/gateway_parameters_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
  internal/kgateway/deployer/gateway_parameters.go
  internal/kgateway/helm/kgateway/templates/gateway/agent-gateway-deployment.yaml
  internal/kgateway/helm/kgateway/templates/gateway/hpa.yaml
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
  internal/kgateway/helm/kgateway/values.yaml
  pkg/deployer/deployer_test.go
  pkg/deployer/gateway_parameters.go
  pkg/deployer/merge.go
  pkg/deployer/merge_test.go
  pkg/deployer/values.go
  pkg/deployer/values_helpers.go
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/tests/api_validation_test.go
Labels: release-note, kind/feature

#12089 agentgateway: add externaltrafficpolicy, sa agw
  api/applyconfiguration/api/v1alpha1/service.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/kube_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
  internal/kgateway/helm/kgateway/templates/gateway/agent-gateway-deployment.yaml
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
  pkg/deployer/deployer_test.go
  pkg/deployer/merge.go
  pkg/deployer/values.go
  pkg/deployer/values_helpers.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release-note, kind/feature

#11598 feat(tests): add load testing suite for gateway performance
  .github/actions/kube-gateway-api-load-tests/action.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/release.yaml
  Makefile
  test/kubernetes/e2e/features/loadtesting/README.md
  test/kubernetes/e2e/features/loadtesting/attachedroutes_suite.go
  test/kubernetes/e2e/features/loadtesting/loadtest_manager.go
  test/kubernetes/e2e/features/loadtesting/types.go
  test/kubernetes/e2e/features/loadtesting/vcluster_simulator.go
  test/kubernetes/e2e/tests/kgateway_tests.go
Labels: release-note, kind/feature

#12113 agentgateway: fix MCP protocol for selector-based Backends
  api/v1alpha1/backend_types.go
  api/v1alpha1/mcp_backend.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/agentgatewaysyncer/agentgateway_translator_test.go
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend-protocol/mcp-backend-selector.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend-protocol/mcp-backend-selector.yaml
  internal/kgateway/extensions2/plugins/backend/agentgateway/mcp.go
  internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go
Labels: kind/cleanup, release-note-none

#12066 agentgateway: cel rbac support
  api/v1alpha1/traffic_policy_types.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
  internal/kgateway/agentgatewaysyncer/agentgateway_translator_test.go
  internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/rbac/http-rbac.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/rbac/mcp-rbac.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/rbac/http-rbac.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/rbac/mcp-rbac.yaml
  internal/kgateway/extensions2/plugins/trafficpolicy/constructor.go
  pkg/agentgateway/plugins/collection.go
  pkg/agentgateway/plugins/traffic_plugin.go
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/agentgateway/rbac/suite.go
  test/kubernetes/e2e/features/agentgateway/rbac/testdata/cel-rbac.yaml
  test/kubernetes/e2e/features/agentgateway/rbac/testdata/setup.yaml
  test/kubernetes/e2e/features/agentgateway/rbac/types.go
  test/kubernetes/e2e/tests/agent_gateway_tests.go
  test/kubernetes/e2e/tests/api_validation_test.go
Labels: release-note, kind/feature

#12012 Removed the dev-mode override that forced text logs so logs remain JSON
  internal/kgateway/controller/start.go
Labels: release-note-none, kind/fix

#12111 policy: deep-merging API for extAuth, extProc, transformations
  api/annotations/policy.go
  install/helm/kgateway/templates/deployment.yaml
  install/helm/kgateway/values.yaml
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_httpfilters.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/merge.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extproc_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extproc_policy_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/gateway_extension.go
  internal/kgateway/extensions2/plugins/trafficpolicy/merge.go
  internal/kgateway/extensions2/plugins/trafficpolicy/merge_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/utils.go
  internal/kgateway/extensions2/plugins/waypoint/filters.go
  internal/kgateway/extensions2/registry/registry.go
  internal/kgateway/krtcollections/gateway_extensions.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/policy_test.go
  internal/kgateway/plugins/stages.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/extauth-deep-merge.yaml
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/extproc-deep-merge.yaml
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/transformation-deep-merge.yaml
  internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/extauth-deep-merge.yaml
  internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/extproc-deep-merge.yaml
  internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/transformation-deep-merge.yaml
  pkg/pluginsdk/filters/stages.go
  pkg/pluginsdk/ir/gatewayextension.go
  pkg/pluginsdk/ir/gw.go
  pkg/pluginsdk/ir/iface.go
  pkg/pluginsdk/policy/merge.go
  pkg/pluginsdk/utils/policy.go
  pkg/pluginsdk/utils/policy_test.go
  pkg/settings/settings.go
  pkg/settings/settings_test.go
  test/translator/test.go
Labels: release-note, kind/feature

#12060 fix(metrics): cleanup resource xds sync metrics
  internal/kgateway/controller/metrics.go
  internal/kgateway/controller/start.go
  internal/kgateway/krtcollections/metrics.go
  internal/kgateway/krtcollections/metrics/metrics.go
  internal/kgateway/krtcollections/metrics/metrics_test.go
  internal/kgateway/krtcollections/metrics_test.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/setup.go
  internal/kgateway/proxy_syncer/kube_gw_translator_syncer.go
  internal/kgateway/proxy_syncer/metrics.go
  internal/kgateway/proxy_syncer/metrics_test.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/proxy_syncer/status_syncer.go
  internal/kgateway/translator/httproute/gateway_http_route_translator.go
  internal/kgateway/translator/irtranslator/policy.go
  internal/kgateway/translator/metrics/metrics.go
  internal/kgateway/translator/metrics/metrics_test.go
  internal/kgateway/translator/translator.go
  test/kubernetes/e2e/features/metrics/suite.go
Labels: release-note-none, kind/fix

#12127 test: Enhance route replacement attachment cases
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/route-replacement/attachment/gateway-invalid.yaml
  internal/kgateway/translator/gateway/testutils/inputs/route-replacement/attachment/httproute-invalid.yaml
  internal/kgateway/translator/gateway/testutils/inputs/route-replacement/attachment/httproute-rule-invalid.yaml
  internal/kgateway/translator/gateway/testutils/inputs/route-replacement/attachment/listener-invalid.yaml
  internal/kgateway/translator/gateway/testutils/inputs/route-replacement/attachment/xlistenerset-invalid.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/attachment/gateway-invalid-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/attachment/httproute-invalid-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/attachment/listener-invalid-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/attachment/xlistenerset-invalid-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/attachment/gateway-invalid-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/attachment/httproute-invalid-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/attachment/listener-invalid-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/attachment/xlistenerset-invalid-out.yaml
  test/translator/assertions.go
Labels: kind/cleanup, release-note-none

#12136 Fix route rule attachment
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  internal/kgateway/agentgatewaysyncer/agentgateway_translator_test.go
  internal/kgateway/agentgatewaysyncer/conversion.go
  internal/kgateway/agentgatewaysyncer/gateway_collection.go
  internal/kgateway/agentgatewaysyncer/route_collections.go
  internal/kgateway/agentgatewaysyncer/route_collections_test.go
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend-protocol/a2a-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend-protocol/backend-default.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend-protocol/bedrock-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend-protocol/mcp-backend-selector.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend-protocol/mcp-backend-static.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend-protocol/openai-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend-protocol/svc-default.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/direct-response.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/direct-response/invalid-backendref-filter.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/direct-response/missing-ref-output.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/direct-response/missing-ref.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/direct-response/overlapping-filters-output.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/direct-response/overlapping-filters.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/grpc-routing/basic-proxy.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/grpc-routing/invalid-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/grpc-routing/missing-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/grpc-routing/multi-backend-proxy.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/http-routing-proxy.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/httproute-timeout-retry-proxy.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/no-route.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/ai/route-level.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/extauth-gateway.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/extauth-listener.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/extauth-route.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/rbac/http-rbac.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/rbac/mcp-rbac.yaml
  internal/kgateway/setup/testdata/agentgateway/direct-response-out.json
  internal/kgateway/setup/testdata/agentgateway/grpcroute-out.json
  internal/kgateway/setup/testdata/agentgateway/httproute-out.json
  internal/kgateway/setup/testdata/agentgateway/inferencepool-out.json
  internal/kgateway/setup/testdata/agentgateway/tcproute-out.json
  pkg/agentgateway/plugins/traffic_plugin.go
  pkg/agentgateway/utils/utils.go
  pkg/deployer/wellknown.go
  test/kubernetes/e2e/features/agentgateway/extauth/suite.go
Labels: release-note, kind/fix

#12144 Update listenerset validation with example workflow
  internal/kgateway/translator/listener/validation.go
Labels: kind/cleanup, release-note-none

#12137 translate host override fields for ai backends for agentgateway
  internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go
Labels: release-note-none, kind/fix

#12148 agentgateway: implement BackendTLSPolicy
  api/annotations/agentgateway.go
  api/applyconfiguration/api/v1alpha1/mcp.go
  api/applyconfiguration/api/v1alpha1/mcpselector.go
  api/applyconfiguration/api/v1alpha1/mcptarget.go
  api/applyconfiguration/api/v1alpha1/mcptargetselector.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/mcp_backend.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml
  internal/kgateway/agentgatewaysyncer/README.md
  internal/kgateway/agentgatewaysyncer/agentgateway_translator_test.go
  internal/kgateway/agentgatewaysyncer/model.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/a2a-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/backend-default.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/backend-tls.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/bedrock-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/mcp-backend-selector.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/mcp-backend-static.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/openai-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/svc-default.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/rbac/mcp-rbac.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend/a2a-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend/backend-default.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend/backend-tls.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend/bedrock-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend/mcp-backend-selector.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend/mcp-backend-static.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend/openai-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend/svc-default.yaml
  internal/kgateway/extensions2/plugins/backend/agentgateway/translate.go
  internal/kgateway/extensions2/plugins/backend/agentgateway/translate_test.go
  internal/kgateway/setup/testdata/agentgateway/direct-response-out.json
  internal/kgateway/setup/testdata/agentgateway/grpcroute-out.json
  internal/kgateway/setup/testdata/agentgateway/httproute-out.json
  internal/kgateway/setup/testdata/agentgateway/inferencepool-out.json
  internal/kgateway/setup/testdata/agentgateway/tcproute-out.json
  pkg/agentgateway/plugins/backend_tls_plugin.go
  pkg/agentgateway/plugins/collection.go
  pkg/agentgateway/plugins/registry.go
  pkg/agentgateway/plugins/traffic_plugin.go
  pkg/agentgateway/utils/utils.go
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/backends/suite.go
  test/kubernetes/e2e/features/backends/testdata/backend.yaml
  test/kubernetes/e2e/features/backends/testdata/base.yaml
  test/kubernetes/e2e/features/backendtls/suite.go
  test/kubernetes/e2e/features/backendtls/testdata/base-agw.yaml
  test/kubernetes/e2e/features/backendtls/testdata/base.yaml
  test/kubernetes/e2e/features/backendtls/testdata/configmap.yaml
  test/kubernetes/e2e/features/backendtls/testdata/nginx.yaml
  test/kubernetes/e2e/tests/agent_gateway_tests.go
Labels: kind/cleanup, release-note-none, kind/feature

#12041 feat: dynamically extract agentgateway version from go.mod
  pkg/deployer/agentgateway_version.go
  pkg/deployer/agentgateway_version_test.go
  pkg/deployer/gateway_parameters.go
  pkg/deployer/wellknown.go
Labels: release-note-none, kind/feature
