Repository kgateway-dev/kgateway, pull requests merged in 2025-07, with the labels that each got.

#11515 EP-11387 Listener-level perConnectionBufferLimitBytes.
  design/11387.md
Labels: kind/design, release-note-none

#11564 update validation for maxRequestSize in traffic policy
  api/v1alpha1/traffic_policy_types.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/buffer-gateway.yaml
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/buffer-route.yaml
Labels: release-note, kind/fix

#11572 Makefile: Add dedicated 'setup' target
  Makefile
Labels: kind/cleanup, release-note-none

#11378 Modular Deployer EP
  design/11376.md
  design/resources/deployer-current-implementation.png
  design/resources/deployer-proposed-changes.png
Labels: release-note-none, kind/documentation

#11585 policy: enable global cross-namespace targetSelector attachment
  design/11466.md
  design/11584.md
  internal/kgateway/deployer/gateway_parameters_test.go
  internal/kgateway/krtcollections/grpc_route_test.go
  internal/kgateway/krtcollections/metrics_test.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/policy_test.go
  internal/kgateway/krtcollections/setup.go
  internal/kgateway/query/query_test.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/label_based.yaml
  internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/label_based_global_policy.yaml
  pkg/deployer/deployer_test.go
  pkg/settings/settings.go
  pkg/settings/settings_test.go
  test/kubernetes/e2e/defaults/defaults.go
  test/kubernetes/e2e/defaults/testdata/httpbin.yaml
  test/kubernetes/e2e/features/policyselector/suite.go
  test/kubernetes/e2e/features/policyselector/testdata/label_selector.yaml
  test/kubernetes/e2e/features/policyselector/types.go
  test/kubernetes/e2e/test.go
  test/kubernetes/e2e/tests/kgateway_test.go
  test/kubernetes/testutils/install/context.go
Labels: release-note, kind/feature

#11593 fix: ensure HTTPListenerPolicy is accepted before running tests
  test/kubernetes/e2e/features/accesslog/suite.go
  test/kubernetes/e2e/features/accesslog/testdata/otel.yaml
  test/kubernetes/e2e/features/tracing/suite.go
  test/kubernetes/e2e/features/tracing/testdata/tracing-policy.yaml
  test/kubernetes/testutils/assertions/status.go
Labels: release-note-none, kind/flake

#11581 Add support for wildcards in CORS allowOrigins
  internal/kgateway/extensions2/plugins/trafficpolicy/cors_policy.go
  internal/kgateway/krtcollections/builtin.go
  internal/kgateway/setup/testdata/standard/cors-httproute-rule-out.yaml
  internal/kgateway/setup/testdata/standard/cors-httproute-rule.yaml
  internal/kgateway/setup/testdata/standard/cors-trafficpolicy-route-out.yaml
  internal/kgateway/setup/testdata/standard/cors-trafficpolicy-route.yaml
  internal/kgateway/utils/cors.go
  internal/kgateway/utils/cors_test.go
  test/kubernetes/e2e/features/cors/suite.go
  test/kubernetes/e2e/features/cors/testdata/httproutes-cors.yaml
  test/kubernetes/e2e/features/cors/testdata/tp-route-cors.yaml
Labels: release-note, kind/feature

#11596 feat(tests): re-enable DirectResponse feature tests and update test c…
  .github/workflows/pr-kubernetes-tests.yaml
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/directresponse/invalid-backendref-filter.yaml
  internal/kgateway/translator/gateway/testutils/inputs/directresponse/missing-ref.yaml
  internal/kgateway/translator/gateway/testutils/inputs/directresponse/overlapping-filters.yaml
  internal/kgateway/translator/gateway/testutils/outputs/directresponse/invalid-backendref-filter.yaml
  internal/kgateway/translator/gateway/testutils/outputs/directresponse/missing-ref.yaml
  internal/kgateway/translator/gateway/testutils/outputs/directresponse/overlapping-filters.yaml
  test/kubernetes/e2e/features/directresponse/suite.go
  test/kubernetes/e2e/features/directresponse/types.go
  test/kubernetes/e2e/tests/kgateway_tests.go
Labels: release-note-none, kind/fix

#11580 use correct commit for release
  .github/workflows/release.yaml
  .goreleaser.yaml
Labels: kind/cleanup, release-note-none

#11617 Add e2e testing for HTTPRoute path matching and simple prefix rewrites
  .github/workflows/pr-kubernetes-tests.yaml
  test/kubernetes/e2e/features/path_matching/suite.go
  test/kubernetes/e2e/features/path_matching/testdata/exact.yaml
  test/kubernetes/e2e/features/path_matching/testdata/prefix-rewrite.yaml
  test/kubernetes/e2e/features/path_matching/testdata/prefix.yaml
  test/kubernetes/e2e/features/path_matching/testdata/regex.yaml
  test/kubernetes/e2e/features/path_matching/testdata/setup.yaml
  test/kubernetes/e2e/features/path_matching/types.go
  test/kubernetes/e2e/tests/kgateway_tests.go
Labels: kind/cleanup, release-note-none

#11618 fix: output per route config for SessionPersistence on RouteRules
  internal/kgateway/krtcollections/builtin.go
  internal/kgateway/translator/gateway/testutils/outputs/session-persistence/cookie.yaml
  internal/kgateway/translator/gateway/testutils/outputs/session-persistence/header.yaml
Labels: release-note, kind/fix

#11591 refactor: Three variables from file.go have been moved to their individual files.
  test/kubernetes/e2e/file.go
  test/kubernetes/e2e/tests/agent_gateway_test.go
  test/kubernetes/e2e/tests/ai_extension_test.go
  test/kubernetes/e2e/tests/inference_extension_test.go
Labels: kind/cleanup, release-note-none

#11626 fix: handle PerConnectionBufferLimitBytes in Gateway Equals
  pkg/pluginsdk/ir/backend.go
Labels: release-note, kind/fix

#11643 *: Move internal/kgateway/reports -> pkg/reports
  examples/plugin/main.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/extensions2/plugins/directresponse/direct_response_plugin.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/plugins/sandwich/plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/krtcollections/builtin.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/proxy_syncer/proxy_syncer_test.go
  internal/kgateway/proxy_syncer/status.go
  internal/kgateway/proxy_syncer/status_test.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/httproute/translate_httproute_test.go
  internal/kgateway/translator/irtranslator/fc_test.go
  internal/kgateway/translator/irtranslator/gateway.go
  internal/kgateway/translator/irtranslator/route.go
  internal/kgateway/translator/listener/gateway_listener_translator_test.go
  internal/kgateway/translator/listener/validation_test.go
  internal/kgateway/translator/translator.go
  pkg/plugins/gwextbase/base.go
  pkg/pluginsdk/ir/iface.go
  pkg/pluginsdk/types.go
  pkg/reports/policy.go
  pkg/reports/policy_test.go
  pkg/reports/reporter.go
  pkg/reports/reporter_suite_test.go
  pkg/reports/reporter_test.go
  pkg/reports/status.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#11641 Add session persistence e2e tests
  .github/workflows/pr-kubernetes-tests.yaml
  internal/kgateway/translator/gateway/testutils/inputs/session-persistence/cookie.yaml
  test/kubernetes/e2e/features/session_persistence/suite.go
  test/kubernetes/e2e/features/session_persistence/testdata/cookie-session-persistence.yaml
  test/kubernetes/e2e/features/session_persistence/testdata/echo-service.yaml
  test/kubernetes/e2e/features/session_persistence/testdata/header-session-persistence.yaml
  test/kubernetes/e2e/features/session_persistence/types.go
  test/kubernetes/e2e/tests/kgateway_tests.go
Labels: kind/cleanup, release-note-none

#11645 pkg/validator: Add functional options for envoy configuration
  pkg/validator/validator.go
  pkg/validator/validator_test.go
Labels: kind/cleanup, release-note-none

#11653 Port-mapping Security Context fix
  internal/kgateway/deployer/gateway_parameters.go
Labels: release-note-none, kind/fix

#11657 Do not ignore 'not found errors' from Deployer
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/gw_controller.go
Labels: release-note-none, kind/fix

#11666 CI: update k8s versions to 1.30-1.33
  .github/workflows/.env/nightly-tests/max_versions.env
  .github/workflows/.env/nightly-tests/min_versions.env
  .github/workflows/.env/pr-tests/versions.env
  .github/workflows/conformance-tests.yaml
  .github/workflows/nightly-tests.yaml
  .github/workflows/regression-tests.yaml
  hack/kind/setup-kind.sh
  internal/kgateway/istio.sh
Labels: kind/cleanup, release-note-none

#11672 Unit test to cover missing PodTemplate
  pkg/deployer/deployer_test.go
Labels: release-note-none, kind/fix

#11687 e2e: Updates Inference Extension EPP Manifest
  test/kubernetes/e2e/features/inferenceextension/testdata/epp.yaml
Labels: release-note, kind/flake

#11629 Add HealthCheck filter policy
  Makefile
  api/applyconfiguration/api/v1alpha1/envoyhealthcheck.go
  api/applyconfiguration/api/v1alpha1/httplistenerpolicyspec.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/http_listener_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_httplistenerpolicies.yaml
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/httplistenerpolicy/route-and-pol.yaml
  internal/kgateway/translator/gateway/testutils/outputs/httplistenerpolicy/route-and-pol.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/pluginsdk/ir/iface.go
  test/kubernetes/e2e/features/http_listener_policy/suite.go
  test/kubernetes/e2e/features/http_listener_policy/testdata/http-listener-policy-all-fields.yaml
Labels: release-note, kind/feature

#11673 refactor sds component
  cmd/sds/main.go
  internal/sds/pkg/run/run.go
  internal/sds/pkg/run/run_e2e_test.go
  pkg/sds/run.go
Labels: kind/cleanup, release-note-none

#11688 logging fixes
  internal/kgateway/controller/start.go
  pkg/logging/level.go
Labels: release-note, kind/fix

#11718 fix: failed redact
  internal/kgateway/proxy_syncer/xdswrapper.go
  internal/kgateway/proxy_syncer/xdswrapper_test.go
Labels: release-note-none, kind/fix

#11721 fix Equals for PolicyAtt and PolicyWrapper
  internal/kgateway/extensions2/plugins/trafficpolicy/gateway_extension.go
  pkg/pluginsdk/ir/gw.go
  pkg/pluginsdk/ir/iface.go
Labels: release-note, kind/fix

#11710 Add 15008 port to Waypoint deployment
  internal/kgateway/extensions2/plugins/waypoint/rbac.go
  internal/kgateway/extensions2/plugins/waypoint/waypoint_translator.go
  pkg/deployer/gateway_parameters.go
  pkg/deployer/values_helpers.go
  pkg/deployer/wellknown.go
Labels: kind/cleanup, kind/design, release-note-none, kind/fix

#11707 Fix agw statuses
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  internal/kgateway/agentgatewaysyncer/README.md
  internal/kgateway/agentgatewaysyncer/gateway_collection.go
  internal/kgateway/agentgatewaysyncer/model.go
  internal/kgateway/agentgatewaysyncer/route_collections.go
  internal/kgateway/agentgatewaysyncer/route_collections_test.go
  internal/kgateway/agentgatewaysyncer/service.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/agentgatewaysyncer/syncer_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/reports/reporter.go
  internal/kgateway/reports/status.go
  test/kubernetes/e2e/features/agentgateway/testdata/agentgateway-deploy.yaml
  test/kubernetes/e2e/tests/api_validation_test.go
Labels: release-note-none, kind/fix

#11729 Inference: Replace Deprecated AddToScheme() with Install()
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/deployer/gateway_parameters_test.go
  pkg/deployer/deployer_test.go
  pkg/schemes/extended_scheme.go
Labels: kind/cleanup, release-note

#11338 bugfix: compare before deploying
  pkg/deployer/deployer.go
  pkg/deployer/deployer_test.go
Labels: release-note, kind/fix

#11728 refactor: Update GetLocalChartPath to accept optional assetDir parameter
  test/kubernetes/e2e/test.go
  test/kubernetes/testutils/helper/install.go
Labels: kind/cleanup, release-note-none

#11726 feat: Add helmPath configuration to Client for customizable helm executable path
  pkg/utils/helmutils/client.go
Labels: kind/cleanup, release-note-none

#11685 [cleanup] Comparison utility with nil handling
  internal/kgateway/extensions2/plugins/backend/aws.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/lb.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extproc_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/global_rate_limit_plugin.go
  internal/kgateway/extensions2/plugins/waypoint/waypoint_translator.go
  pkg/utils/cmputils/cmputils.go
  pkg/utils/cmputils/cmputils_test.go
Labels: kind/cleanup, release-note-none

#11605 fix(metrics): implement resources managed and sync metrics
  .github/workflows/pr-kubernetes-tests.yaml
  devel/metrics/README.md
  internal/kgateway/controller/metrics.go
  internal/kgateway/controller/metrics_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/krtcollections/endpoints.go
  internal/kgateway/krtcollections/endpoints_test.go
  internal/kgateway/krtcollections/metrics.go
  internal/kgateway/krtcollections/metrics_test.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/setup.go
  internal/kgateway/proxy_syncer/kube_gw_translator_syncer.go
  internal/kgateway/proxy_syncer/metrics.go
  internal/kgateway/proxy_syncer/metrics_test.go
  internal/kgateway/proxy_syncer/perclient.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/translator/gateway/gateway_translator.go
  internal/kgateway/translator/httproute/gateway_http_route_translator.go
  internal/kgateway/translator/irtranslator/backend.go
  internal/kgateway/translator/irtranslator/gateway.go
  internal/kgateway/translator/irtranslator/route.go
  internal/kgateway/translator/metrics/metrics.go
  internal/kgateway/translator/metrics/metrics_test.go
  internal/kgateway/translator/translator.go
  pkg/metrics/cmd/findmetrics/main.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/metricstest/metricstest.go
  test/kubernetes/e2e/features/metrics/suite.go
  test/kubernetes/e2e/features/metrics/testdata/example-route.yaml
  test/kubernetes/e2e/features/metrics/testdata/metric-resources.yaml
  test/kubernetes/e2e/features/metrics/testdata/setup.yaml
  test/kubernetes/e2e/features/metrics/types.go
  test/kubernetes/e2e/tests/kgateway_tests.go
  test/kubernetes/e2e/tests/metrics_test.go
  test/kubernetes/e2e/tests/metrics_tests.go
Labels: kind/cleanup, release-note-none, kind/fix

#11749 Update Duration types in APIs
  api/applyconfiguration/api/v1alpha1/aiextensiontrace.go
  api/applyconfiguration/api/v1alpha1/ratelimitprovider.go
  api/applyconfiguration/api/v1alpha1/tokenbucket.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/gateway_extensions_types.go
  api/v1alpha1/gateway_parameters_types.go
  api/v1alpha1/http_listener_policy_types.go
  api/v1alpha1/traffic_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayextensions.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_httplistenerpolicies.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
  internal/kgateway/extensions2/plugins/trafficpolicy/gateway_extension.go
  internal/kgateway/extensions2/plugins/trafficpolicy/global_rate_limit_plugin_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/local_rate_limit_plugin.go
  pkg/deployer/deployer_test.go
  pkg/deployer/values.go
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/tests/api_validation_test.go
Labels: kind/cleanup, release-note-none

#11594 fix: add default value validation for AI policy configuration
  internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy_test.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/ai-invalid-default-value.yaml
  internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/ai-invalid-default-value.yaml
Labels: release-note-none, kind/fix

#11759 refactor: rename regression-tests.yaml to conformance.yaml
  .github/workflows/conformance.yaml
Labels: kind/cleanup, release-note-none

#11701 only apply UseHostnameForHashing to strict dns type clusters
  api/applyconfiguration/api/v1alpha1/loadbalancer.go
  api/applyconfiguration/api/v1alpha1/loadbalancermaglevconfig.go
  api/applyconfiguration/api/v1alpha1/loadbalancerringhashconfig.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/lb.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/lb_test.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/lb-config.yaml
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/lb-usehostnameforhashing.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backendconfigpolicy/lb-config.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backendconfigpolicy/lb-usehostnameforhashing.yaml
  internal/kgateway/translator/gateway/testutils/outputs/loadbalancer/route.yaml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release-note-none, kind/fix

#11602 Reuse controller manager
  cmd/kgateway/main.go
  examples/plugin/main.go
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/setup/controlplane.go
  internal/kgateway/setup/setup.go
  pkg/pluginsdk/collections/collections.go
  pkg/setup/setup.go
  test/envtestutil/util.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#11768 improve status message when referencing missing cert in gateway
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/https-routing/invalid-cert.yaml
  internal/kgateway/translator/gateway/testutils/outputs/https-invalid-cert-proxy.yaml
  internal/kgateway/translator/listener/gateway_listener_translator.go
  internal/kgateway/translator/sslutils/ssl_utils.go
Labels: release-note-none, kind/fix

#11782 in envtests call posStart functions before applying test yaml files
  test/envtestutil/util.go
Labels: release-note-none, kind/fix

#11772 test: log apply output when unexpected error occurs in APIValidation
  test/kubernetes/e2e/tests/api_validation_test.go
Labels: kind/cleanup, release-note, kind/fix

#11788 add basic status messages
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/listener/gateway_listener_translator.go
  pkg/reports/status.go
Labels: kind/cleanup, release-note-none

#11647 add message to ListenerReasonInvalidRouteKinds status
  internal/kgateway/translator/listener/validation.go
  internal/kgateway/translator/listener/validation_test.go
Labels: kind/cleanup, release-note-none

#11781 Fix route collection syncing for agentgateway
  go.mod
  internal/kgateway/agentgatewaysyncer/adp.go
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/agentgatewaysyncer/agentgateway_translator_suite_test.go
  internal/kgateway/agentgatewaysyncer/agentgateway_translator_test.go
  internal/kgateway/agentgatewaysyncer/model.go
  internal/kgateway/agentgatewaysyncer/route_collections.go
  internal/kgateway/agentgatewaysyncer/route_collections_test.go
  internal/kgateway/agentgatewaysyncer/testdata/inputs/http-routing/bar-httproute.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/http-routing/foo-httproute.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/http-routing/gateway.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/http-routing-proxy.yaml
  internal/kgateway/setup/agentgateway_test.go
Labels: release-note-none, kind/fix

#11802 Move all agentgateway backend translation into plugins
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/extensions2/plugins/backend/agentgateway_mcp.go
  internal/kgateway/extensions2/plugins/backend/agentgateway_static.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_agentgateway_backend.go
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/extensions2/plugins/backend/static.go
  pkg/pluginsdk/ir/gw.go
Labels: kind/cleanup, release-note-none

#11797 do not override ctrl manager init function if passed in params are nil
  internal/kgateway/setup/setup.go
  pkg/setup/setup.go
  test/envtestutil/util.go
Labels: release-note-none, kind/fix

#11806 Bump istio dependency to latest
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/extensions2/plugins/destrule/destrule.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/plugins/serviceentry/collections.go
  internal/kgateway/extensions2/plugins/waypoint/waypointquery/waypoint_authz.go
  internal/kgateway/extensions2/plugins/waypoint/waypointquery/waypoint_query.go
  internal/kgateway/krtcollections/endpoints.go
  internal/kgateway/krtcollections/endpoints_test.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/proxy_syncer/backends.go
  internal/kgateway/proxy_syncer/cla.go
  internal/kgateway/proxy_syncer/metrics_test.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/utils/krtutil/index.go
  pkg/utils/filter_types/filter_types.gen.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#11661 feat(telemetry): initialize OTel tracer from user-side configuration
  api/applyconfiguration/api/v1alpha1/aiextensiontrace.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/gateway_parameters_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
  pkg/deployer/deployer_test.go
  pkg/deployer/merge.go
  pkg/deployer/values.go
  pkg/deployer/values_helpers.go
  pkg/generated/openapi/zz_generated.openapi.go
  python/ai_extension/telemetry/tracing.py
  python/ai_extension/test/test_data/tracing_config.b64
  python/ai_extension/test/test_data/tracing_config.json
  python/ai_extension/test/test_tracing.py
  python/requirements-dev.txt
  python/requirements.txt
  test/kubernetes/e2e/features/aiextension/testdata/tracing.yaml
  test/kubernetes/e2e/features/aiextension/tests/client/client.py
Labels: release-note-none, kind/feature

#11697 Adds Retries to Updating Gateway Status
  internal/kgateway/controller/gw_controller.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  pkg/reports/status.go
Labels: release-note, kind/fix

#11787 Update gateway-api-inference-extension to v0.5.0 (Fixes #11765)
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  test/kubernetes/e2e/features/inferenceextension/testdata/epp.yaml
Labels: kind/cleanup, release-note-none

#11825 Add dev docs for agentgateway
  internal/kgateway/agentgatewaysyncer/README.md
  test/kubernetes/e2e/features/agentgateway/testdata/a2a-backend.yaml
  test/kubernetes/e2e/features/agentgateway/testdata/agentgateway-deploy.yaml
  test/kubernetes/e2e/features/agentgateway/testdata/ai-backend.yaml
  test/kubernetes/e2e/features/agentgateway/testdata/grpc-agw.yaml
  test/kubernetes/e2e/features/agentgateway/testdata/mcp-backend.yaml
  test/kubernetes/e2e/features/agentgateway/testdata/static-backend.yaml
  test/kubernetes/e2e/features/agentgateway/testdata/tcp-agw.yaml
Labels: release-note-none, kind/documentation

#11828 status: use Accepted=False,Reason=RouteRuleDropped for replaced rule
  internal/kgateway/query/httproute.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/httproute/gateway_http_route_translator.go
  internal/kgateway/translator/irtranslator/route.go
  pkg/pluginsdk/ir/gw2.go
  pkg/pluginsdk/reporter/types.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#11813 traffic policy: add nil check for route action
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/delegation/traffic_policy_route_policy.yaml
  internal/kgateway/translator/gateway/testutils/outputs/delegation/traffic_policy_route_policy.yaml
Labels: release-note-none, kind/fix

#11829 httplistenerpolicy: preserve http1 header case
  api/applyconfiguration/api/v1alpha1/http1protocoloptions.go
  api/applyconfiguration/api/v1alpha1/httplistenerpolicyspec.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/http_listener_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_httplistenerpolicies.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin_test.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/protocoloptions.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/merge.go
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-label-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-label.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-tls-out.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-tls.yaml
  internal/kgateway/setup/testdata/standard/backendconfigpolicy.yaml
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/lb-config.yaml
  internal/kgateway/translator/gateway/testutils/inputs/httplistenerpolicy/preserve-http1-header-case.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backendconfigpolicy/lb-config.yaml
  internal/kgateway/translator/gateway/testutils/outputs/httplistenerpolicy/preserve-http1-header-case.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/backendconfigpolicy/testdata/setup.yaml
  test/kubernetes/e2e/features/http_listener_policy/suite.go
  test/kubernetes/e2e/features/http_listener_policy/testdata/preserve-http1-header-case.yaml
  test/kubernetes/e2e/features/http_listener_policy/types.go
  test/kubernetes/e2e/tests/api_validation_test.go
Labels: release-note, kind/feature, kind/fix

#11831 plugins/tp: Rename TrafficPolicyBuilder to TrafficPolicyConstructor
  internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/auto_host_rewrite.go
  internal/kgateway/extensions2/plugins/trafficpolicy/buffer.go
  internal/kgateway/extensions2/plugins/trafficpolicy/buffer_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/constructor.go
  internal/kgateway/extensions2/plugins/trafficpolicy/cors_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/csrf_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extproc_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/global_rate_limit_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/hash_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/hash_policy_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/local_rate_limit_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/transformation_plugin.go
  pkg/plugins/gwextbase/base.go
Labels: kind/cleanup, release-note-none

#11835 ir: fix Equals for HttpRouteIr and PolicyAtt
  devel/contributing/conventions.md
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/translator/httproute/delegation_helpers.go
  pkg/pluginsdk/ir/gw.go
  pkg/pluginsdk/ir/gw_test.go
  pkg/pluginsdk/ir/routes.go
  pkg/pluginsdk/ir/routes_test.go
Labels: release-note-none, kind/fix
