Repository kgateway-dev/kgateway, pull requests merged in 2025-09, with the labels that each got.

#12175 test/sds: refactor extremely flaky test
  internal/sds/pkg/run/run_e2e_suite_test.go
  internal/sds/pkg/run/run_e2e_test.go
  internal/sds/pkg/run/run_test.go
  internal/sds/pkg/run/testdata/ocsp_response.der
Labels: release-note-none, kind/flake

#12187 agentgateway: restore workloads.go
  internal/kgateway/agentgatewaysyncer/workloads.go
Labels: kind/cleanup, release-note-none

#12149 backendconfigpolicy: option to use system CA certs
  api/applyconfiguration/api/v1alpha1/tls.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/tls.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/tls_test.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/tls-system-ca.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backendconfigpolicy/tls-system-ca.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/backendconfigpolicy/suite.go
  test/kubernetes/e2e/features/backendconfigpolicy/testdata/system-ca.yaml
  test/kubernetes/e2e/features/backendconfigpolicy/types.go
Labels: release-note, kind/feature

#12183 test/sds: wait for server to shutdown between tests
  internal/sds/pkg/run/run_test.go
Labels: release-note-none, kind/flake

#12166 Inference: Bump to v1.0.0-rc.2
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  internal/kgateway/crds/inference-crds.yaml
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/backends_test.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/ir.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/ir_test.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/validation.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/validation_test.go
  internal/kgateway/setup/testdata/agentgateway/inferencepool.yaml
  internal/kgateway/setup/testdata/inference_api/inferencepool-basic.yaml
  pkg/agentgateway/plugins/inference_plugin.go
  test/kubernetes/e2e/features/inferenceextension/testdata/epp.yaml
  test/kubernetes/e2e/features/inferenceextension/testdata/pool.yaml
Labels: kind/cleanup, release-note

#12190 More descriptive error message about unexpected port in backendref
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/policy_test.go
  internal/kgateway/query/utils.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/backends/backend-ref-port-error.yaml
  internal/kgateway/translator/gateway/testutils/outputs/backends/backend-ref-port-error.yaml
Labels: release-note, kind/fix

#12191 wds: bring more changes from Istio in
  internal/kgateway/agentgatewaysyncer/nodes.go
  internal/kgateway/agentgatewaysyncer/service.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/agentgatewaysyncer/testdata/outputs/backend/backend-tls.yaml
  internal/kgateway/agentgatewaysyncer/waypoint.go
  internal/kgateway/agentgatewaysyncer/workloads.go
  pkg/agentgateway/plugins/collection.go
Labels: release-note-none, kind/fix

#12206 fix cel validation for TrafficPolicy buffer MaxRequestSize
  api/v1alpha1/traffic_policy_types.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
  test/kubernetes/e2e/tests/api_validation_test.go
Labels: release-note-none, kind/fix

#12211 Added envoy-gloo upgrade doc
  devel/envoy/envoy-upgrade.md
Labels: release-note-none, kind/documentation

#12215 e2e route replacement flake fix
  test/kubernetes/e2e/features/routereplacement/suite.go
  test/kubernetes/e2e/features/routereplacement/types.go
Labels: release-note-none, kind/flake

#12217 e2e headermodifiers flake fix
  test/gomega/matchers/json_contains.go
Labels: release-note-none, kind/flake

#12164 e2e deployer selfManaged flake
  internal/kgateway/proxy_syncer/status_syncer.go
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml
  test/kubernetes/e2e/features/deployer/testdata/gateway-without-parameters.yaml
  test/kubernetes/e2e/features/deployer/testdata/istio-gateway-parameters.yaml
  test/kubernetes/e2e/features/deployer/types.go
Labels: release-note-none, kind/flake

#12231 e2e: Remove the upgrade-related code from the base suite
  test/kubernetes/e2e/features/agentgateway/extauth/suite.go
  test/kubernetes/e2e/features/agentgateway/local-rate-limit/suite.go
  test/kubernetes/e2e/features/watch_namespace_selector/suite.go
  test/kubernetes/e2e/tests/base/base_suite.go
Labels: kind/cleanup, release-note-none

#12117 agentgateway: add additional resource extension and configuration for volume/volumeMount
  api/applyconfiguration/api/v1alpha1/pod.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/kube_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/agentgatewaysyncer/gateway_collection.go
  internal/kgateway/agentgatewaysyncer/model.go
  internal/kgateway/agentgatewaysyncer/policy_collections.go
  internal/kgateway/agentgatewaysyncer/route_collections.go
  internal/kgateway/agentgatewaysyncer/route_collections_test.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/agentgatewaysyncer/syncer_test.go
  internal/kgateway/controller/controller.go
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/gatewayclass_provisioner.go
  internal/kgateway/controller/gatewayclass_provisioner_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/deployer/gateway_parameters.go
  internal/kgateway/helm/kgateway/templates/gateway/agent-gateway-deployment.yaml
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
  internal/kgateway/setup/setup.go
  pkg/agentgateway/ir/ir.go
  pkg/agentgateway/plugins/collection.go
  pkg/agentgateway/plugins/interfaces.go
  pkg/agentgateway/plugins/registry.go
  pkg/deployer/gatewayclass.go
  pkg/deployer/merge.go
  pkg/deployer/values.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/setup/setup.go
Labels: release-note, kind/feature

#12226 agent gateway: global rate limiting support
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  pkg/agentgateway/plugins/traffic_plugin.go
  pkg/deployer/wellknown.go
  test/kubernetes/e2e/features/agentgateway/global-rate-limit/testdata/common.yaml
  test/kubernetes/e2e/features/rate_limit/suite.go
  test/kubernetes/e2e/features/rate_limit/types.go
  test/kubernetes/e2e/tests/agent_gateway_tests.go
Labels: release-note-none, kind/feature

#12222 e2e: add prompt guard webhook test
  internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/ai/route-level.yaml
  internal/kgateway/setup/testdata/standard/ai-prompt-guard-webhook-out.yaml
  internal/kgateway/setup/testdata/standard/ai-prompt-guard-webhook.yaml
  python/ai_extension/api/kgateway/policy/ai/prompt_guard.py
  python/ai_extension/guardrails/webhook.py
  python/ai_extension/test/test_server.py
  test/kubernetes/e2e/features/aiextension/suite.go
  test/kubernetes/e2e/features/aiextension/testdata/prompt-guard-webhook.yaml
  test/kubernetes/e2e/features/aiextension/tests/prompt_guard_webhook.py
  test/kubernetes/e2e/features/aiextension/types.go
  test/mocks/mock-ai-provider-server/main.go
  test/mocks/mock-ai-provider-server/mocks/promptguard-webhook/request/openai-mask.json
  test/mocks/mock-ai-provider-server/mocks/promptguard-webhook/request/openai-pass.json
  test/mocks/mock-ai-provider-server/mocks/promptguard-webhook/request/openai-reject.json
  test/mocks/mock-ai-provider-server/mocks/promptguard-webhook/response/openai-mask.json
  test/mocks/mock-ai-provider-server/mocks/promptguard-webhook/response/openai-pass.json
Labels: release-note-none, kind/feature

#12176 Support backend annotation to disable Istio auto-mtls
  .github/workflows/pr-kubernetes-tests.yaml
  api/annotations/policy.go
  devel/architecture/tls-configuration-ordering.md
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/plugins/istio/plugin.go
  internal/kgateway/extensions2/plugins/kubernetes/k8s.go
  internal/kgateway/extensions2/plugins/serviceentry/backends.go
  internal/kgateway/setup/testdata/istio_mtls/istio-svc-mtls-disabled-out.yaml
  internal/kgateway/setup/testdata/istio_mtls/istio-svc-mtls-disabled.yaml
  pkg/pluginsdk/ir/backend.go
  test/kubernetes/e2e/features/istio/auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/custom_tls_suite.go
  test/kubernetes/e2e/features/istio/resources.go
  test/kubernetes/e2e/features/istio/testdata/k8s-routing-backend.yaml
  test/kubernetes/e2e/features/istio/testdata/nginx-backend-route.yaml
  test/kubernetes/e2e/features/istio/testdata/nginx-bcp-mtls.yml
  test/kubernetes/e2e/features/istio/testdata/nginx-bcp-simple-tls.yml
  test/kubernetes/e2e/features/istio/testdata/nginx-btp-simple-tls.yml
  test/kubernetes/e2e/features/istio/testdata/nginx-mtls-config.yml
  test/kubernetes/e2e/features/istio/testdata/setup-nginx-mtls.yml
  test/kubernetes/e2e/features/istio/types.go
  test/kubernetes/e2e/tests/automtls_istio_test.go
  test/kubernetes/e2e/tests/automtls_istio_tests.go
  test/kubernetes/e2e/tests/manifests/istio-automtls-enabled-helm.yaml
Labels: release-note, kind/feature

#12268 Inference: Updates Agentgateway e2e Test Values
  test/kubernetes/e2e/tests/manifests/agent-gateway-integration.yaml
Labels: kind/cleanup, release-note

#12202 agentgateway: Add support for transformation in trafficpolicy
  api/applyconfiguration/api/v1alpha1/bodytransformation.go
  api/applyconfiguration/api/v1alpha1/headertransformation.go
  api/v1alpha1/traffic_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  internal/kgateway/agentgatewaysyncer/agentgateway_translator_test.go
  internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/transformation.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/transformation.yaml
  pkg/agentgateway/plugins/traffic_plugin.go
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/agentgateway/transformation/suite.go
  test/kubernetes/e2e/features/agentgateway/transformation/testdata/gateway-attached-transform.yaml
  test/kubernetes/e2e/features/agentgateway/transformation/testdata/gateway.yaml
  test/kubernetes/e2e/features/agentgateway/transformation/testdata/service.yaml
  test/kubernetes/e2e/features/agentgateway/transformation/testdata/transform-for-body.yaml
  test/kubernetes/e2e/features/agentgateway/transformation/testdata/transform-for-headers.yaml
  test/kubernetes/e2e/features/agentgateway/transformation/types.go
  test/kubernetes/e2e/tests/agent_gateway_tests.go
Labels: release-note, kind/feature

#12272 Bump deps mock ai provider server
  hack/utils/applier/go.mod
  hack/utils/applier/go.sum
  test/mocks/mock-ai-provider-server/go.mod
  test/mocks/mock-ai-provider-server/go.sum
Labels: kind/cleanup, release-note-none

#12084 Modernizes e2e session_persistence test re: NewBaseTestingSuite.
  pkg/utils/kubeutils/kubectl/cli.go
  test/kubernetes/e2e/features/session_persistence/suite.go
  test/kubernetes/e2e/features/session_persistence/testdata/echo-service.yaml
  test/kubernetes/e2e/features/session_persistence/types.go
Labels: release-note-none, kind/flake

#12286 api/rate-limit: reject invalid fillInterval value
  api/v1alpha1/traffic_policy_types.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_trafficpolicies.yaml
Labels: kind/cleanup, release-note-none

#12266 agentgateway: Fix auth initialization for openAI moderation on AI traffic policies
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/agentgatewaysyncer/agentgateway_translator_test.go
  internal/kgateway/agentgatewaysyncer/backend/translate.go
  internal/kgateway/agentgatewaysyncer/backend/translate_test.go
  internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/ai/route-level-bearer.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/ai/route-level-bearer.yaml
  pkg/agentgateway/plugins/traffic_plugin.go
  pkg/utils/kubeutils/secrets.go
Labels: release-note-none, kind/fix

#12291 e2e: Extend route replacement policy tests
  test/kubernetes/e2e/features/routereplacement/suite.go
  test/kubernetes/e2e/features/routereplacement/testdata/gateway-wide-invalid-policy.yaml
  test/kubernetes/e2e/features/routereplacement/testdata/listener-merge-blast-radius.yaml
  test/kubernetes/e2e/features/routereplacement/testdata/listener-specific-invalid-policy.yaml
  test/kubernetes/e2e/features/routereplacement/types.go
Labels: kind/cleanup, release-note-none

#12188 controller: Set status with InvalidParameters reason for invalid GWP refs
  internal/kgateway/controller/gw_controller.go
  internal/kgateway/controller/gw_controller_test.go
  pkg/reports/status.go
  test/kubernetes/e2e/features/deployer/suite.go
Labels: release-note-none, kind/fix

#12298 *: Move envoyinit executable to cmd/ directory
  .goreleaser.yaml
  Makefile
  cmd/envoyinit/Dockerfile
  cmd/envoyinit/docker-entrypoint.sh
  cmd/envoyinit/main.go
Labels: kind/cleanup, release-note-none

#12299 agentgateway: wait for secrets sync in translator tests before building adp resources.
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
Labels: release-note-none, kind/flake

#12297 test/translator: fix defaulting and detect unknown fields
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/mcp-backend-selector.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/multipool-inline-auth.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/multipool-priority-levels.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/multipool-secret-auth.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/ai/route-level-bearer.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/ai/route-level.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/rbac/mcp-rbac.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/ai/route-level-bearer.yaml
  internal/kgateway/agentgatewaysyncer/testdata/outputs/trafficpolicy/ai/route-level.yaml
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/extproc-full-config.yaml
  internal/kgateway/translator/gateway/testutils/inputs/traffic-policy/rate-limit-full-config.yaml
  internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/extproc-full-config.yaml
  internal/kgateway/translator/gateway/testutils/outputs/traffic-policy/rate-limit-full-config.yaml
  test/translator/crd.go
  test/translator/file_loader.go
Labels: kind/cleanup, release-note-none

#12305 Clean up unused metrics and other test helpers
  pkg/utils/statsutils/statsutils.go
  pkg/utils/statsutils/stopwatch.go
  pkg/utils/statsutils/stopwatch_suite_test.go
  pkg/utils/statsutils/stopwatch_test.go
  pkg/utils/statsutils/translation_metrics.go
  test/gomega/assertions/logging.go
  test/gomega/assertions/stats.go
  test/gomega/transforms/metrics.go
  test/helpers/metrics.go
  test/kubernetes/README.md
  test/kubernetes/e2e/README.md
  test/kubernetes/e2e/debugging.md
  test/testutils/http_client.go
  test/testutils/http_client_test.go
  test/testutils/http_request.go
  test/testutils/http_request_test.go
  test/testutils/testutils_suite_test.go
Labels: kind/cleanup, release-note-none

#12307 Makefile: Remove prerequisite from the gie-crds target
  Makefile
Labels: kind/cleanup, release-note-none

#12310 Makefile: Refactor conformance reporting
  Makefile
Labels: kind/cleanup, release-note-none

#12313 Delete old e2e tests part 1
  .github/workflows/pr-kubernetes-tests.yaml
  internal/kgateway/admin/resources.go
  internal/kgateway/translator/gateway/testutils/inputs/delegation/route_policy_filter.yaml
  internal/kgateway/translator/gateway/testutils/inputs/delegation/route_policy_inheritance_filter_override.yaml
  test/kubernetes/e2e/example/info_logging_test.go
  test/kubernetes/e2e/example/manifests/example-profile.yaml
  test/kubernetes/e2e/example/manifests/info-example.yaml
  test/kubernetes/e2e/features/crd_categories/suite.go
  test/kubernetes/e2e/features/crd_categories/types.go
  test/kubernetes/e2e/features/example/suite.go
  test/kubernetes/e2e/features/helm/suite.go
  test/kubernetes/e2e/features/helm/testdata/manifests/config-map-change.yaml
  test/kubernetes/e2e/features/helm/testdata/manifests/production-recommendations.yaml
  test/kubernetes/e2e/features/helm/testdata/manifests/upgrade-override.yaml
  test/kubernetes/e2e/features/helm/types.go
  test/kubernetes/e2e/features/helm_settings/suite.go
  test/kubernetes/e2e/features/http_listener_options/http_lis_opt_suite.go
  test/kubernetes/e2e/features/http_listener_options/lis_opt_types.go
  test/kubernetes/e2e/features/http_listener_options/testdata/basic-http-lis-opt.yaml
  test/kubernetes/e2e/features/http_listener_options/testdata/gateway.yaml
  test/kubernetes/e2e/features/http_listener_options/testdata/not-attached-http-lis-opt.yaml
  test/kubernetes/e2e/features/http_listener_options/testdata/setup.yaml
  test/kubernetes/e2e/features/listener_options/lis_opt_suite.go
  test/kubernetes/e2e/features/listener_options/lis_opt_types.go
  test/kubernetes/e2e/features/listener_options/testdata/basic-lisopt.yaml
  test/kubernetes/e2e/features/listener_options/testdata/setup.yaml
  test/kubernetes/e2e/features/route_options/suite.go
  test/kubernetes/e2e/features/route_options/testdata/bad-rto-targetref.yaml
  test/kubernetes/e2e/features/route_options/testdata/bad-rto.yaml
  test/kubernetes/e2e/features/route_options/testdata/basic-rto-targetref.yaml
  test/kubernetes/e2e/features/route_options/testdata/basic-rto.yaml
  test/kubernetes/e2e/features/route_options/testdata/extra-rto-targetref.yaml
  test/kubernetes/e2e/features/route_options/testdata/extra-rto.yaml
  test/kubernetes/e2e/features/route_options/testdata/httproute1-bad-extension.yaml
  test/kubernetes/e2e/features/route_options/testdata/httproute1-extension.yaml
  test/kubernetes/e2e/features/route_options/testdata/httproute1-multiple-extensions.yaml
  test/kubernetes/e2e/features/route_options/testdata/httproute1.yaml
  test/kubernetes/e2e/features/route_options/testdata/httproute2.yaml
  test/kubernetes/e2e/features/route_options/testdata/merge.yaml
  test/kubernetes/e2e/features/route_options/testdata/setup.yaml
  test/kubernetes/e2e/features/route_options/types.go
  test/kubernetes/e2e/features/virtualhost_options/testdata/setup.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/vho-merge-remove-x-baz.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/vho-remove-x-bar.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/vho-remove-x-baz.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/vho-section-add-x-foo.yaml
  test/kubernetes/e2e/features/virtualhost_options/testdata/vho-webhook-reject.yaml
  test/kubernetes/e2e/features/virtualhost_options/types.go
  test/kubernetes/e2e/features/virtualhost_options/vhost_opt_suite.go
  test/kubernetes/e2e/tests/helm_test.go
  test/kubernetes/e2e/tests/helm_tests.go
  test/kubernetes/e2e/tests/kgateway_tests.go
  test/kubernetes/e2e/tests/no_validation_test.go
  test/kubernetes/e2e/tests/no_validation_tests.go
Labels: kind/cleanup, release-note-none

#12247 Allows for specifying rollout strategies
  api/applyconfiguration/api/v1alpha1/proxydeployment.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/gateway_parameters_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  hack/generate.sh
  hack/helm/dev.yaml
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
  install/helm/kgateway/templates/deployment.yaml
  install/helm/kgateway/values.yaml
  internal/kgateway/deployer/gateway_parameters.go
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
  internal/kgateway/helm/kgateway/values.yaml
  pkg/deployer/merge.go
  pkg/deployer/values.go
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/deployer/testdata/gateway-with-parameters.yaml
  test/kubernetes/e2e/tests/api_validation_test.go
Labels: release-note, kind/feature

#12322 Fix potential race condition between agw and envoy syncers on openAI moderation fields
  internal/kgateway/extensions2/plugins/trafficpolicy/ai_policy.go
Labels: release-note-none, kind/fix

#12324 e2e: Refactor route replacement tests to standalone suite
  .github/workflows/pr-kubernetes-tests.yaml
  test/kubernetes/e2e/features/routereplacement/suite.go
  test/kubernetes/e2e/features/routereplacement/testdata/invalid-matcher.yaml
  test/kubernetes/e2e/features/routereplacement/testdata/invalid-route-rule-filter.yaml
  test/kubernetes/e2e/features/routereplacement/testdata/route-attached-invalid-policy.yaml
  test/kubernetes/e2e/features/routereplacement/types.go
  test/kubernetes/e2e/tests/kgateway_tests.go
  test/kubernetes/e2e/tests/route_replacement_test.go
  test/kubernetes/e2e/tests/route_replacement_tests.go
Labels: kind/cleanup, release-note-none

#12332 irtranslator: Remove gomega assertions from unit tests
  internal/kgateway/translator/irtranslator/backend_test.go
  internal/kgateway/translator/irtranslator/fc_test.go
  internal/kgateway/translator/irtranslator/route_test.go
Labels: kind/cleanup, release-note-none

#12330 *: Move pkg/settings -> api/settings
  api/settings/settings.go
  api/settings/settings_test.go
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/controller/controller_suite_test.go
  internal/kgateway/controller/start.go
  internal/kgateway/deployer/gateway_parameters_test.go
  internal/kgateway/extensions2/plugins/kubernetes/k8s.go
  internal/kgateway/extensions2/plugins/trafficpolicy/validate.go
  internal/kgateway/extensions2/plugins/waypoint/waypoint_translator.go
  internal/kgateway/extensions2/registry/registry.go
  internal/kgateway/krtcollections/endpoints.go
  internal/kgateway/krtcollections/grpc_route_test.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/policy_test.go
  internal/kgateway/krtcollections/setup.go
  internal/kgateway/query/query_test.go
  internal/kgateway/setup/agentgateway_test.go
  internal/kgateway/setup/setup.go
  internal/kgateway/setup/setup_test.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/irtranslator/backend.go
  internal/kgateway/translator/irtranslator/gateway.go
  internal/kgateway/translator/irtranslator/route.go
  internal/kgateway/translator/irtranslator/validate.go
  pkg/deployer/deployer_test.go
  pkg/pluginsdk/collections/collections.go
  test/envtestutil/util.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#12334 Test cleanup, part 3
  pkg/reports/reporter_test.go
  test/gomega/assertions/structs.go
  test/gomega/matchers/benchmark.go
  test/gomega/matchers/benchmark_test.go
  test/gomega/matchers/client_object.go
  test/gomega/matchers/contain_substrings_test.go
  test/gomega/matchers/custom_resource.go
  test/gomega/matchers/custom_resource_test.go
  test/gomega/transforms/benchmark.go
  test/gomega/transforms/regex.go
  test/gomega/transforms/transforms_suite_test.go
  test/helpers/benchmark.go
  test/helpers/benchmark_darwin.go
  test/helpers/benchmark_linux.go
  test/helpers/certs.go
  test/helpers/debug.go
  test/helpers/helpers_suite_test.go
  test/helpers/util.go
  test/helpers/util_test.go
  test/kubernetes/e2e/features/istio/no_auto_mtls_suite.go
  test/kubernetes/e2e/features/istio/resources.go
  test/kubernetes/e2e/features/route_delegation/types.go
  test/kubernetes/testutils/assertions/resources.go
  test/kubernetes/testutils/clients/clients.go
  test/kubernetes/testutils/clients/rest_config.go
  test/kubernetes/testutils/resources/generate_resources.go
Labels: kind/cleanup, release-note-none

#12276 docs: Add initial SECURITY.md file with vulnerability reporting guide…
  README.md
  SECURITY.md
Labels: release-note-none, kind/documentation

#12327 api/ai-backend: simplify provider group API
  api/applyconfiguration/api/v1alpha1/aibackend.go
  api/applyconfiguration/api/v1alpha1/authheader.go
  api/applyconfiguration/api/v1alpha1/llmprovider.go
  api/applyconfiguration/api/v1alpha1/multipoolconfig.go
  api/applyconfiguration/api/v1alpha1/pathoverride.go
  api/applyconfiguration/api/v1alpha1/priority.go
  api/applyconfiguration/api/v1alpha1/prioritygroup.go
  api/applyconfiguration/api/v1alpha1/supportedllmprovider.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/ai_backend.go
  api/v1alpha1/zz_generated.deepcopy.go
  design/10494.md
  docs/ai/quick-start-ai-gateway-locally.md
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml
  internal/kgateway/agentgatewaysyncer/agentgateway_translator_test.go
  internal/kgateway/agentgatewaysyncer/backend/translate.go
  internal/kgateway/agentgatewaysyncer/backend/translate_test.go
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/bedrock-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/multipool-inline-auth.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/multipool-priority-levels.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/multipool-secret-auth.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/backend/openai-backend.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/ai/route-level-bearer.yaml
  internal/kgateway/agentgatewaysyncer/testdata/inputs/trafficpolicy/ai/route-level.yaml
  internal/kgateway/extensions2/plugins/backend/ai/ai_backend.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_backend_test.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster_test.go
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/setup/testdata/standard/ai-anthropic-passthrough.yaml
  internal/kgateway/setup/testdata/standard/ai-azure-and-openai.yaml
  internal/kgateway/setup/testdata/standard/ai-custom-url.yaml
  internal/kgateway/setup/testdata/standard/ai-deepseek-prompt-guard.yaml
  internal/kgateway/setup/testdata/standard/ai-model-failover.yaml
  internal/kgateway/setup/testdata/standard/ai-multi-port-override-plaintext.yaml
  internal/kgateway/setup/testdata/standard/ai-multi-port-override-tls.yaml
  internal/kgateway/setup/testdata/standard/ai-openai-moderation-promptguard.yaml
  internal/kgateway/setup/testdata/standard/ai-prompt-guard-webhook.yaml
  internal/kgateway/setup/testdata/standard/ai-vertex-ai-streaming.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/aiextension/testdata/backend-passthrough.yaml
  test/kubernetes/e2e/features/aiextension/testdata/backend-token.yaml
Labels: kind/cleanup, kind/breaking_change, release-note

#12343 Update AI backend path nesting
  api/applyconfiguration/api/v1alpha1/llmprovider.go
  api/applyconfiguration/api/v1alpha1/pathoverride.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/ai_backend.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backends.yaml
  internal/kgateway/agentgatewaysyncer/backend/translate.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_backend_test.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_model_cluster_test.go
  internal/kgateway/setup/testdata/standard/ai-custom-url.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  test/kubernetes/e2e/features/aiextension/testdata/backend-passthrough.yaml
  test/kubernetes/e2e/features/aiextension/testdata/backend-token.yaml
Labels: kind/cleanup, release-note-none

#12345 rename ai stats annotation
  internal/kgateway/helm/kgateway/templates/gateway/proxy-deployment.yaml
Labels: kind/cleanup, release-note-none

#12314 Wrong expected extension type in error
  internal/kgateway/extensions2/plugins/trafficpolicy/extproc_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/global_rate_limit_plugin.go
Labels: release-note-none, kind/fix

#12346 .github/workflows: Add stalebot for open PRs
  .github/workflows/stalebot.yaml
Labels: kind/cleanup, release-note-none

#12347 fix BCP api redundant naming and inconsistency
  api/applyconfiguration/api/v1alpha1/parameters.go
  api/applyconfiguration/api/v1alpha1/tls.go
  api/applyconfiguration/api/v1alpha1/tlsparameters.go
  api/applyconfiguration/internal/internal.go
  api/applyconfiguration/utils.go
  api/v1alpha1/backend_config_policy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_backendconfigpolicies.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/tls.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/tls_test.go
  internal/kgateway/setup/testdata/standard/backendconfigpolicy-tls.yaml
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/simple-tls.yaml
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/tls-san.yaml
  internal/kgateway/translator/gateway/testutils/inputs/backendconfigpolicy/tls-system-ca.yaml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/cleanup, release-note-none

#12341 Agentgateway; docs for configuring tracing using configmap
  internal/kgateway/agentgatewaysyncer/README.md
Labels: release-note-none, kind/documentation

#12300 Change extauth's filter to the AuthN stage
  api/v1alpha1/ext_auth_types.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/policy/policy-extauth-extension-ref-invalid-out.yaml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release-note, kind/fix

#12361 *: Remove extensions2/plugin aliases
  examples/plugin/main.go
  internal/kgateway/deployer/gateway_parameters_test.go
  internal/kgateway/extensions2/factory.go
  internal/kgateway/extensions2/plugin/plugin.go
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/status.go
  internal/kgateway/extensions2/plugins/backendtlspolicy/plugin.go
  internal/kgateway/extensions2/plugins/backendtlspolicy/status.go
  internal/kgateway/extensions2/plugins/destrule/destrule_plugin.go
  internal/kgateway/extensions2/plugins/directresponse/direct_response_plugin.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/status.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/plugins/istio/plugin.go
  internal/kgateway/extensions2/plugins/kubernetes/k8s.go
  internal/kgateway/extensions2/plugins/sandwich/plugin.go
  internal/kgateway/extensions2/plugins/serviceentry/plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/status.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/extensions2/plugins/waypoint/plugin.go
  internal/kgateway/extensions2/plugins/waypoint/waypoint_translator.go
  internal/kgateway/krtcollections/builtin.go
  internal/kgateway/krtcollections/grpc_route_test.go
  internal/kgateway/krtcollections/policy.go
  internal/kgateway/krtcollections/policy_test.go
  internal/kgateway/krtcollections/setup.go
  internal/kgateway/query/query_test.go
  internal/kgateway/translator/gateway/gateway_translator.go
  internal/kgateway/translator/irtranslator/backend.go
  internal/kgateway/translator/irtranslator/fc_test.go
  internal/kgateway/translator/irtranslator/gateway.go
  internal/kgateway/translator/translator.go
  pkg/agentgateway/translator/backend_translator.go
  pkg/agentgateway/translator/translator.go
  pkg/deployer/deployer_test.go
  pkg/pluginsdk/collections/collections.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#12375 agentgateway: add MCP Backend tests
  test/kubernetes/e2e/features/agentgateway/mcp/Dockerfile
  test/kubernetes/e2e/features/agentgateway/mcp/README.md
  test/kubernetes/e2e/features/agentgateway/mcp/helpers.go
  test/kubernetes/e2e/features/agentgateway/mcp/suite.go
  test/kubernetes/e2e/features/agentgateway/mcp/testdata/common.yaml
  test/kubernetes/e2e/features/agentgateway/mcp/testdata/dynamic.yaml
  test/kubernetes/e2e/features/agentgateway/mcp/testdata/static.yaml
  test/kubernetes/e2e/features/agentgateway/mcp/types.go
  test/kubernetes/e2e/tests/agent_gateway_tests.go
Labels: kind/cleanup, release-note-none

#12380 *: Remove ctx parameter from ProxyTranslationPass methods
  examples/plugin/main.go
  internal/kgateway/extensions2/plugins/backend/ai/ai_resources.go
  internal/kgateway/extensions2/plugins/backend/plugin.go
  internal/kgateway/extensions2/plugins/directresponse/direct_response_plugin.go
  internal/kgateway/extensions2/plugins/httplistenerpolicy/httplistener_plugin.go
  internal/kgateway/extensions2/plugins/inferenceextension/endpointpicker/plugin.go
  internal/kgateway/extensions2/plugins/sandwich/plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/auto_host_rewrite_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/extauth_policy_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/validate.go
  internal/kgateway/krtcollections/builtin.go
  internal/kgateway/translator/irtranslator/fc.go
  internal/kgateway/translator/irtranslator/fc_test.go
  internal/kgateway/translator/irtranslator/gateway.go
  internal/kgateway/translator/irtranslator/route.go
  pkg/plugins/gwextbase/base.go
  pkg/pluginsdk/ir/iface.go
  pkg/pluginsdk/types.go
Labels: kind/cleanup, release-note-none

#12382 gateway: detect reserved port usage and report status
  internal/kgateway/controller/gw_controller.go
  internal/kgateway/deployer/gateway_parameters.go
  internal/kgateway/deployer/gateway_parameters_test.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/validation/gateway-reserved-port.yaml
  internal/kgateway/translator/gateway/testutils/inputs/validation/xlistenerset-reserved-port.yaml
  internal/kgateway/translator/gateway/testutils/outputs/validation/gateway-reserved-port.yaml
  internal/kgateway/translator/gateway/testutils/outputs/validation/xlistenerset-reserved-port.yaml
  internal/kgateway/translator/listener/validation.go
  internal/kgateway/validate/gateway.go
  pkg/deployer/deployer_test.go
  pkg/deployer/values_helpers.go
  test/translator/test.go
Labels: release-note-none, kind/fix

#12373 agentgateway: allow HBONE protocol
  internal/kgateway/agentgatewaysyncer/conversion.go
  internal/kgateway/translator/listener/validation.go
  internal/kgateway/translator/listener/validation_test.go
Labels: kind/cleanup, release-note-none

#12360 translator: Implement CDS validation
  internal/kgateway/extensions2/plugins/backendconfigpolicy/lb.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin_test.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/protocoloptions.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/validate.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/validate_test.go
  internal/kgateway/extensions2/registry/registry.go
  internal/kgateway/proxy_syncer/backends.go
  internal/kgateway/proxy_syncer/perclient.go
  internal/kgateway/proxy_syncer/proxy_syncer.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/testutils/inputs/route-replacement/backendconfigpolicy/invalid-cipher-suites.yaml
  internal/kgateway/translator/gateway/testutils/inputs/route-replacement/backendconfigpolicy/invalid-missing-secret.yaml
  internal/kgateway/translator/gateway/testutils/inputs/route-replacement/backendconfigpolicy/invalid-outlier-detection-zero-interval.yaml
  internal/kgateway/translator/gateway/testutils/inputs/route-replacement/backendconfigpolicy/invalid-tlsfiles-nonexistent.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/backendconfigpolicy/invalid-cipher-suites-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/backendconfigpolicy/invalid-missing-secret-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/backendconfigpolicy/invalid-outlier-detection-zero-interval-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/standard/backendconfigpolicy/invalid-tlsfiles-nonexistent-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/backendconfigpolicy/invalid-cipher-suites-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/backendconfigpolicy/invalid-missing-secret-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/backendconfigpolicy/invalid-outlier-detection-zero-interval-out.yaml
  internal/kgateway/translator/gateway/testutils/outputs/route-replacement/strict/backendconfigpolicy/invalid-tlsfiles-nonexistent-out.yaml
  internal/kgateway/translator/irtranslator/backend.go
  internal/kgateway/translator/irtranslator/backend_test.go
  internal/kgateway/translator/translator.go
  test/translator/test.go
Labels: release-note-none, kind/feature

#12394 complete set of reserved ports
  internal/kgateway/validate/gateway.go
Labels: release-note-none, kind/fix

#12379 internal/kgateway: Remove legacy parameters package
  internal/kgateway/parameters/README.md
  internal/kgateway/parameters/parameters.go
  internal/kgateway/translator/httproute/gateway_http_route_translator_test.go
Labels: kind/cleanup, release-note-none

#12401 test/translator: remove custom status assertions
  internal/kgateway/extensions2/plugins/waypoint/waypoint_translator_test.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/gateway/status_test.go
  test/translator/assertions.go
  test/translator/test.go
Labels: kind/cleanup, release-note-none

#12393 agentgateway: Refactor translator logic
  internal/kgateway/agentgatewaysyncer/agentgateway_testutils.go
  internal/kgateway/agentgatewaysyncer/policy_collections.go
  internal/kgateway/agentgatewaysyncer/status_syncer.go
  internal/kgateway/agentgatewaysyncer/syncer.go
  internal/kgateway/agentgatewaysyncer/syncer_test.go
  internal/kgateway/setup/agentgateway_test.go
  pkg/agentgateway/translator/agw.go
  pkg/agentgateway/translator/builtin_helpers.go
  pkg/agentgateway/translator/conditions.go
  pkg/agentgateway/translator/const.go
  pkg/agentgateway/translator/conversion.go
  pkg/agentgateway/translator/gateway_collection.go
  pkg/agentgateway/translator/gatewayclass_collection.go
  pkg/agentgateway/translator/model.go
  pkg/agentgateway/translator/references_collection.go
  pkg/agentgateway/translator/resources.go
  pkg/agentgateway/translator/route_collections.go
  pkg/agentgateway/translator/route_collections_test.go
  pkg/agentgateway/translator/translator.go
Labels: kind/cleanup, release-note-none

#12411 Envoyutils cleanup
  pkg/utils/envoyutils/bootstrap/bootstrap.go
  pkg/utils/envoyutils/bootstrap/bootstrap_suite_test.go
  pkg/utils/envoyutils/bootstrap/bootstrap_test.go
  pkg/utils/envoyutils/bootstrap/resources.go
  pkg/utils/envoyutils/validation/validation.go
  test/envoyutils/admincli/README.md
  test/envoyutils/admincli/admincli_suite_test.go
  test/envoyutils/admincli/client.go
  test/envoyutils/admincli/client_test.go
  test/envoyutils/admincli/clusters.go
  test/helpers/kube_dump.go
  test/kubernetes/e2e/features/backendconfigpolicy/suite.go
  test/kubernetes/e2e/features/deployer/suite.go
  test/kubernetes/e2e/features/timeoutretry/suite.go
  test/kubernetes/e2e/features/transformation/suite.go
  test/kubernetes/testutils/assertions/envoy.go
Labels: kind/cleanup, release-note-none

#12397 Bump agentgateway to v0.9.0
  go.mod
  go.sum
  hack/utils/oss_compliance/osa_provided.md
  pkg/deployer/wellknown.go
  test/kubernetes/e2e/features/agentgateway/mcp/types.go
Labels: kind/cleanup, release-note-none

#12419 internal/kgateway: Remove unmaintained files
  internal/kgateway/.gitignore
  internal/kgateway/Makefile
  internal/kgateway/README.md
  internal/kgateway/istio.sh
  internal/kgateway/run_envoy_local.sh
Labels: kind/cleanup, release-note-none

#12428 Makefile: Enable several unsupported conformance tests
  Makefile
Labels: kind/cleanup, release-note-none

#12418 Deprecates 'FloatingUserId' and adds 'OmitDefaultSecurityContext'
  api/applyconfiguration/api/v1alpha1/kubernetesproxyconfig.go
  api/applyconfiguration/internal/internal.go
  api/v1alpha1/gateway_parameters_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  hack/utils/oss_compliance/osa_provided.md
  install/helm/kgateway-crds/templates/gateway.kgateway.dev_gatewayparameters.yaml
  install/helm/kgateway/templates/deployment.yaml
  internal/kgateway/deployer/gateway_parameters.go
  internal/kgateway/helm/kgateway/templates/gateway/agent-gateway-deployment.yaml
  internal/kgateway/helm/kgateway/values.yaml
  pkg/deployer/deployer_test.go
  pkg/deployer/gateway_parameters.go
  pkg/deployer/merge.go
  pkg/deployer/values.go
  pkg/generated/openapi/zz_generated.openapi.go
  test/gomega/matchers/equal.go
  test/kubernetes/e2e/features/agentgateway/mcp/helpers.go
  test/kubernetes/e2e/features/agentgateway/mcp/suite.go
Labels: release-note, kind/feature, kind/deprecation

#12436 fix: issue caused by sharing a securityContext between agw and envoy
  internal/kgateway/deployer/gateway_parameters_test.go
  pkg/deployer/gateway_parameters.go
  pkg/deployer/merge.go
  pkg/deployer/merge_test.go
Labels: release-note, kind/fix

#12445 agentgateway: ensure auth policies generated for backends follow policy naming conventions
  internal/kgateway/agentgatewaysyncer/syncer.go
Labels: release-note-none, kind/fix

#12400 *: Rename route replacement feature
  api/settings/settings.go
  api/settings/settings_test.go
  design/10625.md
  install/helm/kgateway/templates/_helpers.tpl
  install/helm/kgateway/templates/deployment.yaml
  install/helm/kgateway/values.yaml
  internal/kgateway/extensions2/plugins/backendconfigpolicy/plugin.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/validate.go
  internal/kgateway/extensions2/plugins/backendconfigpolicy/validate_test.go
  internal/kgateway/extensions2/plugins/trafficpolicy/traffic_policy_plugin.go
  internal/kgateway/extensions2/plugins/trafficpolicy/validate.go
  internal/kgateway/translator/gateway/gateway_translator_test.go
  internal/kgateway/translator/irtranslator/backend.go
  internal/kgateway/translator/irtranslator/backend_test.go
  internal/kgateway/translator/irtranslator/gateway.go
  internal/kgateway/translator/irtranslator/route.go
  internal/kgateway/translator/irtranslator/validate.go
  internal/kgateway/translator/translator.go
  test/kubernetes/e2e/tests/validation_test.go
Labels: release-note-none, kind/feature
